force-app/main/default/objects/Case/fields/I_RM_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Affiliation</description>
    <label>Affiliation</label>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/I_ST_School_or_Educational_body__c.field-meta.xml
<CustomField>
    <fullName>I_ST_School_or_Educational_body__c</fullName>
    <label>School Or Educational Body</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_ST_Personal_Email__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Personal_Email__c</fullName>
    <description>Created to allow user to store personal email</description>
    <externalId>true</externalId>
    <inlineHelpText>The personal email for this person.</inlineHelpText>
    <label>Student Lead Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/I_RM_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Part of the remediation project to store different personas</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <description>Indicates the status of the Affiliation.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>I_RM_Role__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>I_ST_Contact_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_IL_Student_Lead_Int.recordType-meta.xml
<RecordType>
    <fullName>I_IL_Student_Lead_Int</fullName>
    <active>true</active>
    <description>New International Lead who can be a prospective student of La Trobe University</description>
    <label>Student Lead (Int)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_Applicant.recordType-meta.xml
<RecordType>
    <fullName>I_RM_Applicant</fullName>
    <active>true</active>
    <description>An individual who has applied to study at La Trobe University</description>
    <label>Student Applicant (Dom)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_Lead.recordType-meta.xml
<RecordType>
    <fullName>I_RM_Lead</fullName>
    <active>true</active>
    <description>New Domestic Lead who is a prospective student of La Trobe University</description>
    <label>Student Lead (Dom)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/I_RM_Affiliation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Affiliation Settings</label>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/I_ST_Contact_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Admitted</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And LOA</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Not Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Considered</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Made</fullName>
    </customValue>
    <customValue>
        <fullName>Await Academic Advice</fullName>
    </customValue>
    <customValue>
        <fullName>Await Applicant Comms</fullName>
    </customValue>
    <customValue>
        <fullName>Await Further Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Awaiting Interview</fullName>
    </customValue>
    <customValue>
        <fullName>Await Required Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Escalated</fullName>
    </customValue>
    <customValue>
        <fullName>Make A Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make Alternate Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make An Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Nearing Completion</fullName>
    </customValue>
    <customValue>
        <fullName>Not Processed</fullName>
    </customValue>
    <customValue>
        <fullName>Not Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Lapsed</fullName>
    </customValue>
    <customValue>
        <fullName>Other Preference Offered</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Results</fullName>
    </customValue>
    <customValue>
        <fullName>Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <description>Global value set is created for lead(contact) object ST -51</description>
    <masterLabel>I_ST_Contact_Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/I_RM_VilomaContactDeletionSchedulerTest.cls
@isTest
private class I_RM_VilomaContactDeletionSchedulerTest {

    public static Id affiliationDomesticLeadRecordTypeId = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Lead').getRecordTypeId();

    @TestSetup
    static void makeData(){

        String recTypeIdsForAffScoring = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Applicant').getRecordTypeId();
        recTypeIdsForAffScoring += ',' + Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Lead').getRecordTypeId();
        recTypeIdsForAffScoring += ',' + Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_IL_Student_Lead_Int').getRecordTypeId();
        TestUtility.createBatchScoringCustomSettings(recTypeIdsForAffScoring);
        
        List<Contact>listDomesticLeadContacts = new List<Contact>();
        List<I_RM_Affiliation__c> listLeadAffiliations = new List<I_RM_Affiliation__c>();
    
        I_RM_Affiliation_Settings__c objAffiliationSettings1 = new I_RM_Affiliation_Settings__c(Name = 'I_RM_Inactive_Status',I_RM_Status__c = 'Inactive',
        Value__c = '1');
        Insert  objAffiliationSettings1;
        I_RM_Affiliation_Settings__c objAffiliationSettings2 = new I_RM_Affiliation_Settings__c(Name = 'I_RM_No_of_days',I_RM_Status__c = 'Inactive',
        Value__c = '1');
        Insert  objAffiliationSettings2;
        for(integer i=0; i<=10; i++){
            Contact newLeadContact = I_ST_UnitTestUtilities.createContactForScore('test_unique001'+i,
                                                                                  'unique_test001'+i,
                                                                                  'test_unique001'+i+'@unique.com',
                                                                                  'test_unique001'+i+'@unique.com',                                                                                 
                                                                                  '3029');
            listDomesticLeadContacts.add(newLeadContact);
        }
        insert listDomesticLeadContacts;
        
        List<I_RM_Affiliation__c> lstAffiliations = new List<I_RM_Affiliation__c>();
        for(Integer j=0; j<listDomesticLeadContacts.size(); j++) {
            listLeadAffiliations = I_ST_UnitTestUtilities.createAffiliationRecords(affiliationDomesticLeadRecordTypeId,listDomesticLeadContacts[j].Id);
            lstAffiliations.addAll(listLeadAffiliations);
        }
        
        insert lstAffiliations;
        Contact portalContact = new Contact(FirstName='pcontact1',LastName='pconact1',I_ST_Personal_Email__c='test4@email.com');
        insert portalContact;


    } 

    @isTest
    public static  void vilomaContactDeletionSchedulerTest() {        
         test.startTest();
         List<Contact> listOfContactsWOAffls = new List<Contact>();
         Contact listOfContactsWOAffls1 = new Contact(FirstName='TestFirst1',LastName='TestLast1',I_ST_Personal_Email__c='test1@email.com');
         listOfContactsWOAffls.add(listOfContactsWOAffls1);
         Contact listOfContactsWOAffls2 = new Contact(FirstName='TestFirst2',LastName='TestLast2',I_ST_Personal_Email__c='test2@email.com');
         listOfContactsWOAffls.add(listOfContactsWOAffls2);
         Contact listOfContactsWOAffls3 = new Contact(FirstName='TestFirst3',LastName='TestLast3',I_ST_Personal_Email__c='test3@email.com');
         listOfContactsWOAffls.add(listOfContactsWOAffls3);
         Insert listOfContactsWOAffls;
         I_RM_VilomaContactDeletionBatchScheduler myClass = new I_RM_VilomaContactDeletionBatchScheduler ();   
         String chron = '0 0 23 * * ?';        
         system.schedule('Test Sched', chron, myClass);
         List<Contact> cont = new List<Contact>();
         cont = [Select Id, name from Contact];
         test.stopTest();
         system.assert(cont != null);
    }

    @isTest
    public static void vilomaContactDeletionwithCasesTest() {        
        test.startTest();
        List<Contact> listOfContactsWOAffls = new List<Contact>();
        Contact listOfContactsWOAffls1 = new Contact(FirstName='TestFirst1',LastName='TestLast1',I_ST_Personal_Email__c='test1@email.com');
        listOfContactsWOAffls.add(listOfContactsWOAffls1);
        Contact listOfContactsWOAffls2 = new Contact(FirstName='TestFirst2',LastName='TestLast2',I_ST_Personal_Email__c='test2@email.com');
        listOfContactsWOAffls.add(listOfContactsWOAffls2);
        Contact listOfContactsWOAffls3 = new Contact(FirstName='TestFirst3',LastName='TestLast3',I_ST_Personal_Email__c='test3@email.com');
        listOfContactsWOAffls.add(listOfContactsWOAffls3);
        Insert listOfContactsWOAffls;

        case c= new case(
        subject='CaseOfTypeUnmatched',
        ContactId = listOfContactsWOAffls1.Id,
        Origin='Email',SuppliedEmail='unmatched@ibm.com',
        SuppliedName='Unmatched Case',
        SuppliedPhone='6478390245',
        I_ST_School_or_Educational_body__c='Unmatched Account');
        insert c;
        List<Contact> allContacts1 = [Select Id, Name from Contact];
        I_RM_VilomaContactDeletionBatchScheduler myClass = new I_RM_VilomaContactDeletionBatchScheduler ();   
        String chron = '0 0 23 * * ?';        
        system.schedule('Test Sched', chron, myClass);
        List<Contact> cont = new List<Contact>();
        cont = [Select Id, name from Contact];
        test.stopTest();
        system.assert(cont != null);
   }

   @isTest 
   public static void vilomaContactDeletionwithPUsersTest() {        
    test.startTest();
    List<Contact> listOfContactsWOAffls = new List<Contact>();
    Contact listOfContactsWOAffls1 = new Contact(FirstName='TestFirst1',LastName='TestLast1',I_ST_Personal_Email__c='test1@email.com');
    listOfContactsWOAffls.add(listOfContactsWOAffls1);
    Contact listOfContactsWOAffls2 = new Contact(FirstName='TestFirst2',LastName='TestLast2',I_ST_Personal_Email__c='test2@email.com');
    listOfContactsWOAffls.add(listOfContactsWOAffls2);
    Contact listOfContactsWOAffls3 = new Contact(FirstName='TestFirst3',LastName='TestLast3',I_ST_Personal_Email__c='test3@email.com');
    listOfContactsWOAffls.add(listOfContactsWOAffls3);
    Insert listOfContactsWOAffls;
    List<Contact> portalContact = [Select Id from Contact where LastName = 'pconact1'];
    Profile profile1 = [Select Id from Profile where name = 'LTU Partner Community User'];
    User portalAccountOwner1 = new User(
        ProfileId = profile1.Id,
        ContactId = portalContact[0].Id,
        Username = Math.random()+'@'+UserInfo.getOrganizationid()+'.test',
        Alias = 'frtman',
        Email='TestUserF124.TestUserL125@test124562.com',
        EmailEncodingKey='UTF-8',
        Firstname='TestUserF124',
        Lastname='TestUserL125',
        TimeZoneSidKey = 'America/Los_Angeles',
        LocaleSidKey = 'en_US',
        LanguageLocaleKey = 'en_US');
        Database.insert(portalAccountOwner1);

    List<Contact> allContacts1 = [Select Id, Name from Contact];
    I_RM_VilomaContactDeletionBatchScheduler myClass = new I_RM_VilomaContactDeletionBatchScheduler ();   
    String chron = '0 0 23 * * ?';        
    system.schedule('Test Sched', chron, myClass);
    List<Contact> cont = new List<Contact>();
    cont = [Select Id, name from Contact];
    test.stopTest();
    system.assert(cont != null);
}
}