force-app/main/default/objects/Case/fields/I_RM_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Affiliation</description>
    <label>Affiliation</label>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/I_ST_Incremental_Score__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Incremental_Score__c</fullName>
    <label>Incremental Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/I_IL_LTU_INT_Enquiry.recordType-meta.xml
<RecordType>
    <fullName>I_IL_LTU_INT_Enquiry</fullName>
    <active>true</active>
    <businessProcess>IST ENQUIRY</businessProcess>
    <description>Inbound case for LTU INT Team received via Phone/Email/Chat etc.</description>
    <label>LTU INT - Enquiry</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/I_ST_Enquiry.recordType-meta.xml
<RecordType>
    <fullName>I_ST_Enquiry</fullName>
    <active>true</active>
    <businessProcess>IST ENQUIRY</businessProcess>
    <description>Inbound Case for SACE Team received via Phone/Email/Chat etc.</description>
    <label>Enquiry</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/IST.recordType-meta.xml
<RecordType>
    <fullName>IST</fullName>
    <active>true</active>
    <businessProcess>PRIME</businessProcess>
    <description>Record type for IST Support</description>
    <label>IST</label>
</RecordType>

force-app/main/default/objects/Contact/fields/I_ST_Incremental_Score__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Incremental_Score__c</fullName>
    <label>Activity Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/I_RM_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Part of the remediation project to store different personas</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <description>Indicates the status of the Affiliation.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>I_RM_Role__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>I_ST_Contact_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_IL_Student_Lead_Int.recordType-meta.xml
<RecordType>
    <fullName>I_IL_Student_Lead_Int</fullName>
    <active>true</active>
    <description>New International Lead who can be a prospective student of La Trobe University</description>
    <label>Student Lead (Int)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_Applicant.recordType-meta.xml
<RecordType>
    <fullName>I_RM_Applicant</fullName>
    <active>true</active>
    <description>An individual who has applied to study at La Trobe University</description>
    <label>Student Applicant (Dom)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_Lead.recordType-meta.xml
<RecordType>
    <fullName>I_RM_Lead</fullName>
    <active>true</active>
    <description>New Domestic Lead who is a prospective student of La Trobe University</description>
    <label>Student Lead (Dom)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/I_RM_Affiliation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Affiliation Settings</label>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_ST_Interaction__c/I_ST_Interaction__c.object-meta.xml
<CustomObject>
    <description>For Lead Forms, tracks interactions(forms) filled out by the Lead (domestic)</description>
    <label>Interaction</label>
    <nameField>
        <displayFormat>INT-{DD}{MM}{YY}-{0000}</displayFormat>
        <label>Interaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_ST_Interaction__c/fields/I_RM_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Affiliation__c</fullName>
    <description>Facilitate relationship with the Affiliation object</description>
    <label>Affiliation</label>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>Interactions</relationshipLabel>
    <relationshipName>Interactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/I_ST_Interaction__c/fields/I_ST_Incremental_Score__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Incremental_Score__c</fullName>
    <label>Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/I_ST_Interaction__c/recordTypes/I_ST_Lead_Interaction.recordType-meta.xml
<RecordType>
    <fullName>I_ST_Lead_Interaction</fullName>
    <active>true</active>
    <label>Lead Interaction</label>
</RecordType>

force-app/main/default/globalValueSets/I_ST_Contact_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Admitted</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And LOA</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Not Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Considered</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Made</fullName>
    </customValue>
    <customValue>
        <fullName>Await Academic Advice</fullName>
    </customValue>
    <customValue>
        <fullName>Await Applicant Comms</fullName>
    </customValue>
    <customValue>
        <fullName>Await Further Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Awaiting Interview</fullName>
    </customValue>
    <customValue>
        <fullName>Await Required Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Escalated</fullName>
    </customValue>
    <customValue>
        <fullName>Make A Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make Alternate Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make An Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Nearing Completion</fullName>
    </customValue>
    <customValue>
        <fullName>Not Processed</fullName>
    </customValue>
    <customValue>
        <fullName>Not Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Lapsed</fullName>
    </customValue>
    <customValue>
        <fullName>Other Preference Offered</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Results</fullName>
    </customValue>
    <customValue>
        <fullName>Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <description>Global value set is created for lead(contact) object ST -51</description>
    <masterLabel>I_ST_Contact_Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GlobalConstants.cls
/**
 * Created by burnside on 2019-05-03.
 */

public with sharing class GlobalConstants {

    //Contact record type names
  //  public static String CONTACT_RECORD_TYPE_NAME_LTU_STAFF = 'I_RS_La_Trobe_Staff';
 //   public static String CONTACT_RECORD_TYPE_NAME_LTU_STUDENT = 'I_RS_La_Trobe_Student';
   // public static String CONTACT_RECORD_TYPE_NAME_EXTERNAL_CONTACT = 'I_RS_External_Contact';
    
    //set of strings that require Sponsored flag on Affiliation to be set Yes
    public static final List<String> COUNTRYOFCITIZENSHIPSET = ( I_RM_Affiliation_Settings__c.getInstance('I_IL_Sponsored_by_Citizenship') != null )
                                                               ? I_RM_Affiliation_Settings__c.getInstance('I_IL_Sponsored_by_Citizenship').Value__c.split(';')
                                                               : new List<String>();
    //set of strings that require Sponsored flag on Affiliation to be set Yes
    public static final List<String> INTENDEDFUNDINGSRCSET = ( I_RM_Affiliation_Settings__c.getInstance('I_IL_Sponsored_by_Citizenship') != null )
                                                             ? I_RM_Affiliation_Settings__c.getInstance('I_IL_Sponsored_by_Citizenship').I_RM_Status__c.split(';')
                                                             : new List<String>();
    
    //sObject API Names
    public static String AFFILIATION_OBJECT_API_NAME = 'I_RM_Affiliation__c';
    public static String CONTACT_OBJECT_API_NAME = 'Contact';
    public static String CASE_OBJECT_API_NAME = 'Case';
    public static String INTERACTION_OBJECT_API_NAME = 'I_ST_Interaction__c';
    
    
    //Custom Setting Records
    public static String I_RM_AFFILIATIONSCORING ='I_RM_AffiliationScoring';
    public static String I_ST_CONTACTSCORING = 'I_ST_ContactScoring';
    public static String I_ST_CASESCORING = 'I_ST_CaseScoring';
    public static String I_ST_INTERACTIONSCORING = 'I_ST_InteractionScoring';
    public static String I_RM_AFFILIATION_SETTINGS = 'I_RM_Inactive_Status';
    public static String I_RM_INACTIVE_APPLICATION_SETTINGS = 'I_RM_Inactive_Application_Status';
    public static String I_RM_Early_Entry_Courses = 'I_RM_Early_Entry_Courses';
    //IST Contact record type API names
  //  public static String CONTACT_RECORD_TYPE_API_NAME_DOMESTIC_LEAD = 'I_ST_Domestic_Lead';
    
    //IST Case record type API names
    public static String CASE_RECORD_TYPE_API_NAME_ENQUIRY = 'I_ST_Enquiry';
    
    //Case record type names
    public static String CASE_RECORD_TYPE_NAME_ENQUIRY = 'Enquiry';
    public static String CASE_RECORD_TYPE_NAME_INT_ENQUIRY = 'I_IL_LTU_INT_Enquiry';
    
    
    //Affiliation record type names
     public static String AFFILIATION_RECORD_TYPE_NAME_LEAD ='I_RM_Lead'; 
     public static String AFFILIATION_RECORD_TYPE_NAME_APPLICANT = 'I_RM_Applicant';
     public static String AFFILIATION_RECORD_TYPE_NAME_INT_LEAD = 'I_IL_Student_Lead_Int';
    
     //Affiliation record type Ids
     public static Id AFFILIATION_RECORD_TYPE_ID_INT_LEAD = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get(AFFILIATION_RECORD_TYPE_NAME_INT_LEAD).getRecordTypeId();
    
     //Case Incremental score field namee
    public static String CASE_INCREMENTAL_SCORE_FIELD = 'I_ST_Incremental_Score__c';
    
    //Interaction RecordType API Names
    public static String INTERACTION_RECORD_TYPE_API_NAME_LEAD_INTERACTION = 'I_ST_Lead_Interaction';
    
    //Interaction Incremental score field namee
    public static String INTERACTION_INCREMENTAL_SCORE_FIELD = 'I_ST_Incremental_Score__c';

    //Organisation record type names
    public static String ACCOUNT_RECORD_TYPE_NAME_LTU_ORG_UNIT = 'I_RS_La_Trobe_Organisation_Unit';
    public static String ACCOUNT_RECORD_TYPE_NAME_EXTERNAL_ORG = 'I_RS_External_Organisation';
    public static String ACCOUNT_RECORD_TYPE_NAME_Admin_Account = 'I_ST_Lead_Account';

    //Project Team Member Status Values
    public static String PROJECT_TEAM_MEMBER_STATUS_ACCEPTED = 'Accepted';
    public static String PROJECT_TEAM_MEMBER_STATUS_REJECTED = 'Rejected';
    
    //Project Team Member Role Values 
    public static String PROJECT_TEAM_MEMBER_ROLE_LEAD_CI = 'Lead Chief Investigator';
    
    //Project Proposal Status Values
    public static String PROJECT_PROPOSAL_STATUS_REVIEW_BY_RESEARCH_OFFICE = 'Review by Research Office';
    public static String PROJECT_PROPOSAL_STATUS_APPROVALS = 'Approvals';
    public static String PROJECT_PROPOSAL_STATUS_SUCCESSFUL = 'Successful';
    public static String PROJECT_PROPOSAL_STATUS_UNSUCCESSFUL = 'Unsuccessful';

    //Project Team Member share access constants
    public static String PROJECT_TEAM_MEMBER_SHARING_PROJ_PROP_ACCESS = 'Edit';
    public static String PROJECT_TEAM_MEMBER_SHARING_PROJ_TEAM_MEMBER_ACCESS = 'Read';
    public static String PROJECT_TEAM_MEMBER_SHARING_CONTRACT_ACCESS = 'Read';
    public static String PROJECT_TEAM_MEMBER_SHARING_RELATED_CONTRACT_ACCESS = 'Read';
    public static String PROJECT_TEAM_MEMBER_SHARING_WBS_ACCESS = 'Edit';
    public static String PROJECT_TEAM_MEMBER_SHARING_CLASSIF_CODE_ACCESS = 'Edit';
    public static String PROJECT_TEAM_MEMBER_SHARING_JUNCTION_ACCESS = 'Read';

    //Project Hierarchy share access constants
    public static String PROJECT_HIERARCHY_SHARING_PROJ_PROP_ACCESS = 'Edit';
    public static String PROJECT_HIERARCHY_SHARING_PROJ_TEAM_MEMBER_ACCESS = 'Edit';
    public static String PROJECT_HIERARCHY_SHARING_CONTRACT_ACCESS = 'Edit';
    public static String PROJECT_HIERARCHY_SHARING_RELATED_CONTRACT_ACCESS = 'Edit';
    public static String PROJECT_HIERARCHY_SHARING_WBS_ACCESS = 'Edit';
    public static String PROJECT_HIERARCHY_SHARING_CLASSIF_CODE_ACCESS = 'Edit';
    public static String PROJECT_HIERARCHY_SHARING_JUNCTION_ACCESS = 'Edit';

    //Classification Master Types
    public static string CLASSIFICATION_MASTER_TYPE_FOR = 'Fields of Research (FOR)';
    public static string CLASSIFICATION_MASTER_TYPE_FOR_2008 = 'Fields of Research - 2008 (FOR - 08)';
    public static string CLASSIFICATION_MASTER_TYPE_SEO = 'Socio-Economic Objective (SEO)';
    public static string CLASSIFICATION_MASTER_TYPE_SEO_2008 = 'Socio-economic Objective - 2008 (SEO - 08)';
    public static string CLASSIFICATION_MASTER_TYPE_TOA = 'Type of Activity (TOA)';
    
    //Ethics Team Member share access constants
    public static String ETHICS_TEAM_MEMBER_SHARING_ACCESS = 'Edit';
    
    public static String RES_OPP_TEAM_MEMBER_STATUS_ACCEPTED = 'Accepted';
    public static String RES_OPP_TEAM_MEMBER_STATUS_REJECTED = 'Rejected';

    public static String RES_OPP_TEAM_MEMBER_SHARING_OPP_ACCESS = 'Edit';
    public static String RES_OPP_TEAM_MEMBER_SHARING_OPP_TEAM_MEMBER_ACCESS = 'Edit';
    //public static String RES_OPP_TEAM_MEMBER_SHARING_MILESTONE_ACCESS = 'Edit';
    //public static String RES_OPP_TEAM_MEMBER_SHARING_CLASSIF_CODE_ACCESS = 'Edit';
    
    //Trigger error description
    public static String ADDED_ERROR_ATTACHMENT_UPLOAD_PROECT_IN_REVIEW = 'Project proposal is currently locked down until Research Office has approved. You cannot upload/modify any attachments';
    public static String RESTRICT_DOCUMENT_UPLOAD_BY_RESEARCHER = 'You cannot upload/modify any attachments';
    public static String ADDED_ERROR_LEAD_CI_HAS_VALID_EMAIL_ADDRESS = 'Please ensure the Lead Chief Investigator has a valid email address';
    
    //Profile Names
    public static String PROFILE_NAME_LTU_PARTNER_COMMUNITY_USER = 'LTU Partner Community User';
    public static List<String> COMMUNITYPROFILENAMES = System.Label.Partner_Community_Profile_Label.split(',');

    public static String COMMA = ',';
    
    //Thesis
    public static String THESIS_GRADUATE_RESEARCHER = 'GR';
    public static String THESIS_PRINCIPLE_SUPERVISOR = 'PS';
    public static String THESIS_PRINCIPLE_SUPERVISOR_SUB = 'PSS';
    public static String THESIS_DGR = 'DGR';
    public static String THESIS_DGR_SUB = 'DGRS';
    public static String THESIS_DGS = 'DGS';
    public static String THESIS_DGS_SUB = 'DGSS';

}