force-app/main/default/objects/Case/fields/I_RM_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Affiliation</description>
    <label>Affiliation</label>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/I_ST_Incremental_Score__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Incremental_Score__c</fullName>
    <label>Incremental Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/I_ST_Score_Calculated__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Score_Calculated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>I ST Score Calculated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/I_ST_Study_Interest__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Study_Interest__c</fullName>
    <description>Created for IST 188</description>
    <label>Study Interest</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>I_ST_Study_Interest</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/I_ST_Enquiry.recordType-meta.xml
<RecordType>
    <fullName>I_ST_Enquiry</fullName>
    <active>true</active>
    <businessProcess>IST ENQUIRY</businessProcess>
    <description>Inbound Case for SACE Team received via Phone/Email/Chat etc.</description>
    <label>Enquiry</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/IST.recordType-meta.xml
<RecordType>
    <fullName>IST</fullName>
    <active>true</active>
    <businessProcess>PRIME</businessProcess>
    <description>Record type for IST Support</description>
    <label>IST</label>
</RecordType>

force-app/main/default/objects/Contact/fields/I_ST_Incremental_Score__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Incremental_Score__c</fullName>
    <label>Activity Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_ST_Study_Interest__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Study_Interest__c</fullName>
    <description>Created for IST-43. This field is a controlling for Career Interest Field</description>
    <label>Study Interest</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>I_ST_Study_Interest</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/I_RM_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Part of the remediation project to store different personas</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Contact__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Contact__c</fullName>
    <description>The person/contact who this Affiliation relates to</description>
    <inlineHelpText>The person this affiliation relates to</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Affiliations</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Incremental_Score__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Incremental_Score__c</fullName>
    <description>This field is used for automated Contact scoring</description>
    <label>Activity Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_Lead.recordType-meta.xml
<RecordType>
    <fullName>I_RM_Lead</fullName>
    <active>true</active>
    <description>New Domestic Lead who is a prospective student of La Trobe University</description>
    <label>Student Lead (Dom)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/I_RM_Affiliation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Affiliation Settings</label>
</CustomObject>

force-app/main/default/objects/I_ST_BatchScoring__c/I_ST_BatchScoring__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>I_ST_BatchScoring</label>
</CustomObject>

force-app/main/default/objects/I_ST_BatchScoring__c/fields/I_ST_BatchSize__c.field-meta.xml
<CustomField>
    <fullName>I_ST_BatchSize__c</fullName>
    <description>This is the batch size to control the Lead/Activity scoring jobs for IST</description>
    <label>I_ST_BatchSize</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/I_ST_BatchScoring__c/fields/I_ST_Last_N_Hour__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Last_N_Hour__c</fullName>
    <description>Used for Activity Scoring batch to run batch and pick records modified &apos;N&apos; hours before current time</description>
    <label>I_ST_Last_N_Hour</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/I_ST_BatchScoring__c/fields/I_ST_RecordType_SFIDs__c.field-meta.xml
<CustomField>
    <fullName>I_ST_RecordType_SFIDs__c</fullName>
    <description>Provide comma separated RecordTypeIds of Case object which is to be considered for Activity Scoring. To get the record type Ids =&gt; Navigate to Setup -&gt; Object Manager -&gt; Case -&gt; RecordTypes -&gt; Select the record type -&gt; copy the 18 digit Id from the URL</description>
    <label>I_ST_RecordType_SFIDs</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/I_ST_Study_Interest.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Any</fullName>
    </customValue>
    <customValue>
        <fullName>Arts, Social Sciences and Communications</fullName>
    </customValue>
    <customValue>
        <fullName>Business and Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Education and teaching</fullName>
    </customValue>
    <customValue>
        <fullName>Health</fullName>
    </customValue>
    <customValue>
        <fullName>IT and engineering</fullName>
    </customValue>
    <customValue>
        <fullName>Law and criminology</fullName>
    </customValue>
    <customValue>
        <fullName>Science</fullName>
    </customValue>
    <customValue>
        <fullName>General</fullName>
        <isActive>false</isActive>
        <label>General</label>
    </customValue>
    <customValue>
        <fullName>Aspire</fullName>
        <isActive>false</isActive>
        <label>Aspire</label>
    </customValue>
    <customValue>
        <fullName>Pathways</fullName>
        <isActive>false</isActive>
        <label>Pathways</label>
    </customValue>
    <customValue>
        <fullName>Information technology</fullName>
        <isActive>false</isActive>
        <label>Information technology</label>
    </customValue>
    <customValue>
        <fullName>Engineering</fullName>
        <isActive>false</isActive>
        <label>Engineering</label>
    </customValue>
    <customValue>
        <fullName>Law</fullName>
        <isActive>false</isActive>
        <label>Law</label>
    </customValue>
    <customValue>
        <fullName>Criminology</fullName>
        <isActive>false</isActive>
        <label>Criminology</label>
    </customValue>
    <description>Created for IST-43</description>
    <masterLabel>I_ST_Study_Interest</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/I_ST_ActivityScoring_BatchTest.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* I_ST_ActivityScoring_BatchTest
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Teja Yenduri   <tyenduri@au1.ibm.com>
* @version        1.0
* @created        2022-02-18
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* @changes
* v1.0           Teja Yenduri
* 2022-02-18      Created
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/
@isTest
public class I_ST_ActivityScoring_BatchTest{ 
    @TestSetup
    static void setup() {
        String affiliationRecordTypIds = I_ST_UnitTestUtilities.recordTypeIds(GlobalConstants.AFFILIATION_OBJECT_API_NAME,GlobalConstants.AFFILIATION_RECORD_TYPE_NAME_LEAD);
        String caseRecordTypeIds = I_ST_UnitTestUtilities.recordTypeIds(GlobalConstants.CASE_OBJECT_API_NAME,GlobalConstants.CASE_RECORD_TYPE_API_NAME_ENQUIRY);  
        String interactionRecordTypeIds = I_ST_UnitTestUtilities.recordTypeIds(GlobalConstants.INTERACTION_OBJECT_API_NAME,GlobalConstants.INTERACTION_RECORD_TYPE_API_NAME_LEAD_INTERACTION);
        
        List<I_ST_BatchScoring__c> listBatchScoringSetting = I_ST_UnitTestUtilities.createBatchScoringCustomSetting(affiliationRecordTypIds,20,caseRecordTypeIds,20,interactionRecordTypeIds,20);           
        insert listBatchScoringSetting;  
        
        Id caseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('I_ST_Enquiry').getRecordTypeId();        
        Id affiliationDomesticLeadRecordTypeId = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Lead').getRecordTypeId();
        
        List<I_RM_Affiliation__c> listLeadAffiliations = new List<I_RM_Affiliation__c>();
        List<Contact>listDomesticLeadContacts = new List<Contact>();
       	I_RM_Affiliation_Settings__c objAffiliationSettings = I_ST_UnitTestUtilities.createAffiliationSettings();
        insert objAffiliationSettings;
       
        
        for(integer i=0; i<=10; i++){
             Contact newLeadContact = I_ST_UnitTestUtilities.createContactForScore('test_unique001'+i,
                                                                              'unique_test001'+i,
                                                                              'test_unique001'+i+'@unique.com',
                                                                              'test_unique001'+i+'@unique.com',                                                                              
                                                                              '3029');
            listDomesticLeadContacts.add(newLeadContact);
        }
        insert listDomesticLeadContacts;
        
       /* List<I_RM_Affiliation__c> lstAffiliations = new List<I_RM_Affiliation__c>();
         for(Integer j=0; j<listDomesticLeadContacts.size(); j++) {
        	listLeadAffiliations = I_ST_UnitTestUtilities.createAffiliationRecords(affiliationDomesticLeadRecordTypeId,listDomesticLeadContacts[j].Id);
         	lstAffiliations.addAll(listLeadAffiliations);
         }
        insert lstAffiliations;*/
        
        //Insert first batch of 10 cases - 1 for each Contact 
        List<Case> casesListForScoreTestBatch1 = New List<Case>();
        for(Integer j=0; j<listDomesticLeadContacts.size(); j++) {
            case newcase =  I_ST_UnitTestUtilities.newListOfContactRelatedCases(caseRecordTypeId,listDomesticLeadContacts[j],10,false,'Title First'+j,'Open','test_uniquee001'+j+'@unique.com', null);           
            casesListForScoreTestBatch1.add(newcase);
        } 
        insert casesListForScoreTestBatch1;
        
        //Insert second batch of 10 cases - 1 for each Contact
        /*List<Case> casesListForScoreTestBatch2 = New List<Case>();
        for(Integer k=0; k<listDomesticLeadContacts.size(); k++) {
            case newcase =  I_ST_UnitTestUtilities.newListOfContactRelatedCases(caseRecordTypeId,listDomesticLeadContacts[k],20,false,'Title Second'+k,'Open', listLeadAffiliations[0]);         
            casesListForScoreTestBatch2.add(newcase);
        }
        Insert casesListForScoreTestBatch2;*/
    }
    
    
    //IST - Test method to test the scheduler - I_ST_ActivityScoring_Batch_Scheduler2 
    @isTest
    public static void testActivityScoreScheduler2(){
        
        I_ST_BatchScoring__c batchScoringSettingCase = I_ST_BatchScoring__c.getValues(GlobalConstants.I_ST_CASESCORING);
        Integer lastNHours = (Integer)batchScoringSettingCase.I_ST_Last_N_Hour__c;
        Set<Id> newrecordTypeIds = GlobalUtility.convertCommaSeparatedStringsToSetIds(batchScoringSettingCase.I_ST_RecordType_SFIDs__c);
        
        String jobId = '';
        Test.startTest();           
        jobId  = I_ST_ActivityScoring_Batch_Scheduler.scheduleActivityScoring();
        Test.stopTest();     
        System.assert(String.isNotBlank(jobId));
    }
    
    //IST - Test method to test the execution of batch class - I_ST_ActivityScoring_Batch2 - Positive Test
    @isTest
    public static void testCalculateActivityScoreBatch2(){
        
        List<String> contactIdsForCases = new List<String>();
        for(Case cs: [Select Subject,I_ST_Study_Interest__c,I_ST_Score_Calculated__c,I_ST_Incremental_Score__c,
                     I_RM_Affiliation__c,I_RM_Affiliation__r.I_RM_Incremental_Score__c,
                      ContactId 
                      FROM Case 
                      WHERE I_RM_Affiliation__c != null 
                      AND I_ST_Score_Calculated__c = false
                      AND (Subject LIKE 'Title First%'
                      OR Subject LIKE 'Title Second%')
                      ]) {
                          System.debug('** cs.I_RM_Affiliation__c >> '+cs.I_RM_Affiliation__c);                         
                          contactIdsForCases.add(cs.ContactId);
                      }
        List<I_RM_Affiliation__c> affiliationAfterBatchUpdate = new List<I_RM_Affiliation__c>();
      
        I_ST_BatchScoring__c batchScoringSettingCase = I_ST_BatchScoring__c.getValues(GlobalConstants.I_ST_CASESCORING);
        Integer lastNHours = (Integer)batchScoringSettingCase.I_ST_Last_N_Hour__c;
        Integer batchSize = (Integer)batchScoringSettingCase.I_ST_BatchSize__c;
        Set<Id> newrecordTypeIds = GlobalUtility.convertCommaSeparatedStringsToSetIds(batchScoringSettingCase.I_ST_RecordType_SFIDs__c);
        
        Test.startTest();            
            I_ST_ActivityScoring_Batch leadScoringBatch = new I_ST_ActivityScoring_Batch(GlobalConstants.CASE_OBJECT_API_NAME,newrecordTypeIds,lastNHours);
            Database.executeBatch(leadScoringBatch,batchSize);        
        Test.stopTest();
        
        affiliationAfterBatchUpdate = [SELECT Id,I_RM_Contact__c,I_RM_Incremental_Score__c FROM I_RM_Affiliation__c WHERE I_RM_Contact__c =:contactIdsForCases];
        system.debug('outsideaffiliationAfterBatchUpdate:'+affiliationAfterBatchUpdate);
        //Assert on Score calculated based on metadata mapping in Lead Scoring metadata. Hence asserting increment in score NOT actual score calculated as it keeps on changing
        system.assert(Integer.valueOf(affiliationAfterBatchUpdate[1].I_RM_Incremental_Score__c)>0);  
       
    }
}