force-app/main/default/objects/Case/fields/I_RM_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Affiliation</description>
    <label>Affiliation</label>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/I_ST_Enquiry.recordType-meta.xml
<RecordType>
    <fullName>I_ST_Enquiry</fullName>
    <active>true</active>
    <businessProcess>IST ENQUIRY</businessProcess>
    <description>Inbound Case for SACE Team received via Phone/Email/Chat etc.</description>
    <label>Enquiry</label>
</RecordType>

force-app/main/default/objects/Contact/fields/I_RM_Applicant_Email__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Applicant_Email__c</fullName>
    <description>Technical Field. Email address of the applicant. It is copied from Personal email on applicant via a trigger</description>
    <label>Applicant Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_RM_Examiner_Email__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Examiner_Email__c</fullName>
    <description>LTU360-1395 - This field captures external emails of related affiliations to be used in Quick Action for sending email to examiners for Examiner Interaction.</description>
    <label>Examiner Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_RS_Citizenship__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Citizenship__c</fullName>
    <label>Country of Citizenship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>I_RM_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/I_RS_Deceased__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Deceased__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deceased</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_ST_Personal_Email__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Personal_Email__c</fullName>
    <description>Created to allow user to store personal email</description>
    <externalId>true</externalId>
    <inlineHelpText>The personal email for this person.</inlineHelpText>
    <label>Student Lead Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_ST_Student_Email__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Student_Email__c</fullName>
    <description>Created to allow student to store their email address</description>
    <externalId>true</externalId>
    <inlineHelpText>The student email for this person.</inlineHelpText>
    <label>Student Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/I_RM_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Part of the remediation project to store different personas</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_IL_Intended_Funding_Source__c.field-meta.xml
<CustomField>
    <fullName>I_IL_Intended_Funding_Source__c</fullName>
    <description>Depicts candidate’s education funding source</description>
    <label>Intended Funding Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Self-funded</fullName>
            </value>
            <value>
                <fullName>Family-funded</fullName>
            </value>
            <value>
                <fullName>Coursework Scholarship</fullName>
            </value>
            <value>
                <fullName>Graduate Research Scholarship</fullName>
            </value>
            <value>
                <fullName>Graduate Research External Sponsorship</fullName>
            </value>
            <value>
                <fullName>Coursework External Sponsorship</fullName>
            </value>
            <value>
                <fullName>Bank Loan</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Coursework External Scholarship</fullName>
                <isActive>false</isActive>
                <label>Coursework External Scholarship</label>
            </value>
            <value>
                <fullName>Graduate Research External Scholarship</fullName>
                <isActive>false</isActive>
                <label>Graduate Research External Scholarship</label>
            </value>
            <value>
                <fullName>Research External Scholarship/Sponsorship</fullName>
                <isActive>false</isActive>
                <label>Research External Scholarship/Sponsorship</label>
            </value>
            <value>
                <fullName>Scholarship</fullName>
                <isActive>false</isActive>
                <label>Scholarship</label>
            </value>
            <value>
                <fullName>Sponsored by University</fullName>
                <isActive>false</isActive>
                <label>Sponsored by University</label>
            </value>
            <value>
                <fullName>Sponsored by company or organisation</fullName>
                <isActive>false</isActive>
                <label>Sponsored by company or organisation</label>
            </value>
            <value>
                <fullName>Sponsored by government</fullName>
                <isActive>false</isActive>
                <label>Sponsored by government</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_IL_Sponsored__c.field-meta.xml
<CustomField>
    <fullName>I_IL_Sponsored__c</fullName>
    <description>Depicts whether a candidate is sponsored</description>
    <label>Sponsored</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Calculate_Affiliation_Score__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Calculate_Affiliation_Score__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Technical Field. Depicts if batch process needs to recalculate the affiliation&apos;s Lead Score.</description>
    <label>Calculate Affiliation Score</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Contact__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Contact__c</fullName>
    <description>The person/contact who this Affiliation relates to</description>
    <inlineHelpText>The person this affiliation relates to</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Affiliations</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Email__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Email__c</fullName>
    <description>Depicts Personal Email</description>
    <inlineHelpText>The personal email for this person.</inlineHelpText>
    <label>Personal Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_EndDate__c.field-meta.xml
<CustomField>
    <fullName>I_RM_EndDate__c</fullName>
    <description>Depicts Affiliations End Date.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Enquirer_Type__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Enquirer_Type__c</fullName>
    <description>Depicts how best to describe the Enquirer, Applicable for Student Lead (Dom),Student Applicant (Dom) and Secondary School Rep</description>
    <inlineHelpText>This is the Enquirer Type</inlineHelpText>
    <label>What best describes you?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>I_ST_Enquirer_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Incremental_Score__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Incremental_Score__c</fullName>
    <description>This field is used for automated Contact scoring</description>
    <label>Activity Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Mobile_Phone__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Mobile_Phone__c</fullName>
    <description>Depicts affiliation&apos;s Mobile Phone number</description>
    <label>Mobile Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Role__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Role__c</fullName>
    <description>This represents the role of the affiliation</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Domestic Lead</fullName>
                <label>Student Lead (Dom)</label>
            </value>
            <value>
                <fullName>Applicant</fullName>
                <label>Student Applicant (Dom)</label>
            </value>
            <value>
                <fullName>La Trobe Staff</fullName>
            </value>
            <value>
                <fullName>School Representative</fullName>
                <label>Secondary School Representative</label>
            </value>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>External Contact</fullName>
            </value>
            <value>
                <fullName>HDR Student</fullName>
                <label>Graduate Researcher</label>
            </value>
            <value>
                <fullName>Student Lead (Int)</fullName>
            </value>
            <value>
                <fullName>Nominated Affiliation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Score__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Score__c</fullName>
    <description>This Fields shows the calculated score of an affiliation based on key attributes being populated</description>
    <label>Affiliation Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <description>Indicates the status of the Affiliation.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>I_RM_Role__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>I_ST_Contact_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Student_Email__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Student_Email__c</fullName>
    <description>Depicts Students Email address</description>
    <inlineHelpText>The student email for this person.</inlineHelpText>
    <label>Student Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Time_Frame_to_Study__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Time_Frame_to_Study__c</fullName>
    <description>Student Lead (Dom) Affiliation&apos;s time trame to study.</description>
    <label>Time Frame to Study</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>I_ST_Time_Frame_to_Study</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Work_Email__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Work_Email__c</fullName>
    <description>Depicts Work Email address</description>
    <inlineHelpText>Note: Graduate researchers, this is their institutional email (or staff email if they are also staff)</inlineHelpText>
    <label>Work Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/L_PR_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Contact_Name__c</fullName>
    <label>Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_IL_Student_Lead_Int.recordType-meta.xml
<RecordType>
    <fullName>I_IL_Student_Lead_Int</fullName>
    <active>true</active>
    <description>New International Lead who can be a prospective student of La Trobe University</description>
    <label>Student Lead (Int)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_Applicant.recordType-meta.xml
<RecordType>
    <fullName>I_RM_Applicant</fullName>
    <active>true</active>
    <description>An individual who has applied to study at La Trobe University</description>
    <label>Student Applicant (Dom)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_External_Contact.recordType-meta.xml
<RecordType>
    <fullName>I_RM_External_Contact</fullName>
    <active>true</active>
    <description>A Person external to La Trobe (i.e. partner)</description>
    <label>External Contact</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_HDR_Student.recordType-meta.xml
<RecordType>
    <fullName>I_RM_HDR_Student</fullName>
    <active>true</active>
    <description>An individual who is completing a graduate research degree (masters by research, PhD or professional doctorate) at La Trobe.</description>
    <label>Graduate Researcher</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_La_Trobe_Staff.recordType-meta.xml
<RecordType>
    <fullName>I_RM_La_Trobe_Staff</fullName>
    <active>true</active>
    <description>La Trobe staff member</description>
    <label>La Trobe Staff</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_Lead.recordType-meta.xml
<RecordType>
    <fullName>I_RM_Lead</fullName>
    <active>true</active>
    <description>New Domestic Lead who is a prospective student of La Trobe University</description>
    <label>Student Lead (Dom)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_Student.recordType-meta.xml
<RecordType>
    <fullName>I_RM_Student</fullName>
    <active>true</active>
    <description>Persons who are currently a student of La Trobe</description>
    <label>Student</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/I_RM_Affiliation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Affiliation Settings</label>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_ST_BatchScoring__c/I_ST_BatchScoring__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>I_ST_BatchScoring</label>
</CustomObject>

force-app/main/default/objects/Order/fields/I_RM_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Affiliation</description>
    <label>Affiliation</label>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/I_RM_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Åland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Argentinian Antarctic Territory</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Australian Antarctic Territory</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas (the)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia (Plurinational State of)</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Saudi Arabia</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/I_ST_Contact_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Admitted</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And LOA</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Not Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Considered</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Made</fullName>
    </customValue>
    <customValue>
        <fullName>Await Academic Advice</fullName>
    </customValue>
    <customValue>
        <fullName>Await Applicant Comms</fullName>
    </customValue>
    <customValue>
        <fullName>Await Further Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Awaiting Interview</fullName>
    </customValue>
    <customValue>
        <fullName>Await Required Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Escalated</fullName>
    </customValue>
    <customValue>
        <fullName>Make A Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make Alternate Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make An Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Nearing Completion</fullName>
    </customValue>
    <customValue>
        <fullName>Not Processed</fullName>
    </customValue>
    <customValue>
        <fullName>Not Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Lapsed</fullName>
    </customValue>
    <customValue>
        <fullName>Other Preference Offered</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Results</fullName>
    </customValue>
    <customValue>
        <fullName>Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <description>Global value set is created for lead(contact) object ST -51</description>
    <masterLabel>I_ST_Contact_Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/I_ST_Enquirer_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Year 9</fullName>
    </customValue>
    <customValue>
        <fullName>Year 10</fullName>
    </customValue>
    <customValue>
        <fullName>Year 11</fullName>
    </customValue>
    <customValue>
        <fullName>Year 12</fullName>
    </customValue>
    <customValue>
        <fullName>Recent school leaver (18-20)</fullName>
    </customValue>
    <customValue>
        <fullName>Mature age (21+)</fullName>
    </customValue>
    <customValue>
        <fullName>Industry qualified or experienced</fullName>
    </customValue>
    <customValue>
        <fullName>Direct applicant</fullName>
    </customValue>
    <customValue>
        <fullName>University graduate (other uni)</fullName>
    </customValue>
    <customValue>
        <fullName>University graduate (LTU)</fullName>
    </customValue>
    <customValue>
        <fullName>International (outside Australia)</fullName>
    </customValue>
    <customValue>
        <fullName>International (inside Australia)</fullName>
    </customValue>
    <customValue>
        <fullName>TAFE graduate</fullName>
    </customValue>
    <customValue>
        <fullName>Current students (LTU) - UG</fullName>
    </customValue>
    <customValue>
        <fullName>Current students (LTU) - PG</fullName>
    </customValue>
    <customValue>
        <fullName>Current students (other uni) - UG</fullName>
    </customValue>
    <customValue>
        <fullName>Current students (other uni) - PG</fullName>
    </customValue>
    <customValue>
        <fullName>Current student (other) - TAFE</fullName>
    </customValue>
    <customValue>
        <fullName>Current student (LTU) - Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Parent</fullName>
    </customValue>
    <customValue>
        <fullName>Careers advisor / Careers counsellor</fullName>
    </customValue>
    <customValue>
        <fullName>Teacher</fullName>
    </customValue>
    <customValue>
        <fullName>Principal</fullName>
    </customValue>
    <customValue>
        <fullName>International agent</fullName>
    </customValue>
    <customValue>
        <fullName>Business Owner / Contact</fullName>
    </customValue>
    <customValue>
        <fullName>Industry partner</fullName>
    </customValue>
    <customValue>
        <fullName>Industry association</fullName>
    </customValue>
    <customValue>
        <fullName>Accrediting Body</fullName>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <customValue>
        <fullName>Staff</fullName>
    </customValue>
    <description>Created for IST-43</description>
    <masterLabel>I_ST_Enquirer_Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/I_ST_Time_Frame_to_Study.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1-3 months</fullName>
    </customValue>
    <customValue>
        <fullName>3-6 months</fullName>
    </customValue>
    <customValue>
        <fullName>6-12 months</fullName>
    </customValue>
    <customValue>
        <fullName>1-2 years</fullName>
    </customValue>
    <customValue>
        <fullName>2-3 years</fullName>
    </customValue>
    <customValue>
        <fullName>3+ years</fullName>
    </customValue>
    <customValue>
        <fullName>Unsure</fullName>
    </customValue>
    <customValue>
        <fullName>12+ months</fullName>
        <isActive>false</isActive>
        <label>12+ months</label>
    </customValue>
    <description>Created for IST 43</description>
    <masterLabel>I_ST_Time_Frame_to_Study</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/I_RM_AffiliationTriggerHelperTest.cls
/**
─────────────────────────────────────────────────────────────────────────────────────────────────┐
* I_RM_AffiliationTriggerHelperTest
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* @author Teja Yenduri
* @date 2022-02-18
* 
* * @description : markCalculateAffiliationScoreToTrue method is used to set I_RM_Calculate_Affiliation_Score__c to true
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/
@isTest
public class I_RM_AffiliationTriggerHelperTest {
    public static Id affiliationDomesticLeadRecordTypeId = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Lead').getRecordTypeId();
    public static Id affiliationIntLeadRecordTypeId = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_IL_Student_Lead_Int').getRecordTypeId();
    public static Id affiliationApplicantRecordTypeId = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Applicant').getRecordTypeId(); 
    public static Id affiliationStaffRecordTypeId = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_La_Trobe_Staff').getRecordTypeId();
    public static Id affiliationStudentRecordTypeId = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Student').getRecordTypeId();
    public static Id affiliationECRecordTypeId = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_External_Contact').getRecordTypeId();  
    public static Id affiliationHDRStudentRecordTypeId = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_HDR_Student').getRecordTypeId();
    
    
    @TestSetup
    static void setup() {

        String recTypeIdsForAffScoring = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Applicant').getRecordTypeId();
        recTypeIdsForAffScoring += ',' + Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Lead').getRecordTypeId();
        recTypeIdsForAffScoring += ',' + Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_IL_Student_Lead_Int').getRecordTypeId();
        TestUtility.createBatchScoringCustomSettings(recTypeIdsForAffScoring);
        
        string affiliationRecordTypIds = I_ST_UnitTestUtilities.recordTypeIds(GlobalConstants.AFFILIATION_OBJECT_API_NAME,GlobalConstants.AFFILIATION_RECORD_TYPE_NAME_LEAD);
        string caseRecordTypeIds = I_ST_UnitTestUtilities.recordTypeIds(GlobalConstants.CASE_OBJECT_API_NAME,GlobalConstants.CASE_RECORD_TYPE_API_NAME_ENQUIRY);
        string applicantaffiliationRecordTypIds = I_ST_UnitTestUtilities.recordTypeIds(GlobalConstants.AFFILIATION_OBJECT_API_NAME,GlobalConstants.AFFILIATION_RECORD_TYPE_NAME_APPLICANT);
        
        List<I_ST_BatchScoring__c> listBatchScoringSetting = I_ST_UnitTestUtilities.createBatchScoringCustomSetting(affiliationRecordTypIds,20,caseRecordTypeIds,20,null,null);           
        insert listBatchScoringSetting; 
        
        Id caseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('I_ST_Enquiry').getRecordTypeId();        
        Id affiliationDomesticLeadRecordTypeId = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Lead').getRecordTypeId();
        Id affiliationApplicantRecordTypeId = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Applicant').getRecordTypeId();
        
        List<I_RM_Affiliation__c> listLeadAffiliations = new List<I_RM_Affiliation__c>();
        List<I_RM_Affiliation__c> listAppAffiliations  = new List<I_RM_Affiliation__c>();
        List<Contact>listDomesticLeadContacts = new List<Contact>();
        I_RM_Affiliation_Settings__c objAffiliationSettings = I_ST_UnitTestUtilities.createAffiliationSettings();
        insert objAffiliationSettings;
        
        for(integer i=0; i<=10; i++){
            Contact newLeadContact = I_ST_UnitTestUtilities.createContactForScore('test_unique001'+i,
                                                                                  'unique_test001'+i,
                                                                                  'test_unique001'+i+'@unique.com',
                                                                                  'test_unique001'+i+'@unique.com',                                                                                 
                                                                                  '3029');
            listDomesticLeadContacts.add(newLeadContact);
        }
        insert listDomesticLeadContacts;
        
        List<I_RM_Affiliation__c> lstAffiliations = new List<I_RM_Affiliation__c>();
        for(Integer j=0; j<listDomesticLeadContacts.size(); j++) {
            listLeadAffiliations = I_ST_UnitTestUtilities.createAffiliationRecords(affiliationDomesticLeadRecordTypeId,listDomesticLeadContacts[j].Id);
            lstAffiliations.addAll(listLeadAffiliations);
        }
        
        insert lstAffiliations;
        
        List<I_RM_Affiliation__c> lstApplicantAffiliations = new List<I_RM_Affiliation__c>();
        for(Integer j=0; j<listDomesticLeadContacts.size(); j++) {
            listAppAffiliations = I_ST_UnitTestUtilities.createApplicantAffiliationRecords(affiliationApplicantRecordTypeId,listDomesticLeadContacts[j].Id);
            lstApplicantAffiliations.addAll(listAppAffiliations);
        }
        
      //  insert lstApplicantAffiliations;
        
        
    } 
    
    //Teja Yenduri IBM, Bluewolf 18/02/2022/////////
    @isTest
    public static void testmarkCalculateAffiliationScoreToTrue(){
        
        List<I_RM_Affiliation__c> domesticLeadAffiliation = [SELECT Id, Name,I_RM_Calculate_Affiliation_Score__c FROM I_RM_Affiliation__c];        
        
        try{
            I_RM_Affiliation__c updateAffiliation = new I_RM_Affiliation__c();
            updateAffiliation.id= domesticLeadAffiliation[0].Id;
            updateAffiliation.I_RM_Enquirer_Type__c = 'Year 11';            
            test.startTest();
            update updateAffiliation;
            test.StopTest();
        }
        catch (Exception e) {
            System.debug('>>> ERROR ='+e);
        }   
        system.assertEquals(true, domesticLeadAffiliation[0].I_RM_Calculate_Affiliation_Score__c);
    }
    
    
    //Teja Yenduri IBM, Bluewolf 02/03/2022//
    @isTest
    public static void testActiveLeadAffiliation(){
        
        test.startTest();
        //List<I_RM_Affiliation__c> beforeUpadateAff = [SELECT Id, Name,I_RM_Status__c,I_RM_Contact__c FROM I_RM_Affiliation__c where I_RM_Status__c  ='Not Processed' AND  I_RM_Role__c ='Applicant' AND I_RM_EndDate__c = null ];
        Contact cont1 = new Contact(FirstName='TestFirst2',LastName='TestLast2',I_ST_Personal_Email__c='test2@email.com');
        Insert cont1;        
        
        
        I_RM_Affiliation__c aff1 =new I_RM_Affiliation__c(RecordTypeID=Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Lead').getrecordTypeId(),
                                                          I_RM_Contact__c= cont1.Id,
                                                          I_RM_Role__c='Domestic Lead',I_RM_Email__c='caseoftypeenquiry@ibm.com.invalid',
                                                          I_RM_Status__c='Not Qualified',
                                                          I_RM_Mobile_Phone__c='0415822666');
        
        insert aff1;
        
        I_RM_Affiliation__c aff2 =new I_RM_Affiliation__c(RecordTypeID=Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Lead').getrecordTypeId(),
                                                          I_RM_Contact__c= cont1.Id,
                                                          I_RM_Role__c='Domestic Lead',I_RM_Email__c='caseoftypeenquiry1@ibm.com.invalid',
                                                          I_RM_Status__c='Not Qualified',
                                                          I_RM_Mobile_Phone__c='0415822667');
        
        insert aff2;
        
        I_RM_Affiliation__c aff3 = new I_RM_Affiliation__c(RecordTypeID=Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Applicant').getrecordTypeId(),
                                                           I_RM_Contact__c = cont1.Id,
                                                           I_RM_Role__c = 'Applicant',
                                                           I_RM_Status__c = 'Inactive');
        
        insert aff3;  
        test.StopTest();
        
        
        List<I_RM_Affiliation__c> affToBeUpdated = [SELECT Id, Name,I_RM_Status__c,I_RM_Contact__c FROM I_RM_Affiliation__c where I_RM_Role__c ='Domestic Lead' AND I_RM_Contact__c =: cont1.Id];
        system.assertEquals('Qualified', affToBeUpdated[0].I_RM_Status__c);
        
    }        
    
    
    //Teja Yenduri IBM, Bluewolf 02/03/2022//
    @isTest
    public static void testInactiveLeadAffiliation(){
    
        Contact cont = new Contact(FirstName='TestFirst2',LastName='TestLast2',I_ST_Personal_Email__c='test2@email.com');
        Insert cont;
        
        
        I_RM_Affiliation__c aff1 =new I_RM_Affiliation__c(RecordTypeID=Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Lead').getrecordTypeId(),
                                                          I_RM_Contact__c= cont.Id,
                                                          I_RM_Role__c='Domestic Lead',I_RM_Email__c='caseoftypeenquiry@ibm.com.invalid',
                                                          I_RM_Status__c='Inactive',
                                                          I_RM_Mobile_Phone__c='0415822666');
        
        insert aff1;
        
        I_RM_Affiliation__c aff2 =new I_RM_Affiliation__c(RecordTypeID=Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Lead').getrecordTypeId(),
                                                          I_RM_Contact__c= cont.Id,
                                                          I_RM_Role__c='Domestic Lead',I_RM_Email__c='caseoftypeenquiry1@ibm.com.invalid',
                                                          I_RM_Status__c='Inactive',
                                                          I_RM_Mobile_Phone__c='0415822667');
        
        insert aff2;
        
        I_RM_Affiliation__c aff3 = new I_RM_Affiliation__c(RecordTypeID=Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Applicant').getrecordTypeId(),
                                                           I_RM_Contact__c = cont.Id,
                                                           I_RM_Role__c = 'Applicant',
                                                           I_RM_Status__c = 'Not Processed');
        
        insert aff3;       
        
      
        try{
            
            test.startTest();
            aff3.I_RM_Status__c = 'Inactive';
            update aff3;
            test.StopTest();
        }
        catch (Exception e) {
            System.debug('>>> ERROR ='+e);
        }  
        List<I_RM_Affiliation__c> affToBeUpdated = [SELECT Id, Name,I_RM_Status__c,I_RM_Contact__c FROM I_RM_Affiliation__c where I_RM_Role__c ='Domestic Lead' AND I_RM_Contact__c =: cont.Id ORDER BY createdDate DESC ];        
        system.assertEquals('Qualified', affToBeUpdated[0].I_RM_Status__c);
    }  
    @isTest
    public static void checkActiveDomAffiliationUpdate(){
        Test.startTest();
        Contact con = [SELECT Id FROM Contact WHERE I_ST_Personal_Email__c='test_unique0012@unique.com'];
        I_RM_Affiliation__c af=new I_RM_Affiliation__c(RecordTypeID = affiliationDomesticLeadRecordTypeId,
                                                       I_RM_Contact__c=con.Id,
                                                       I_RM_Role__c='Domestic Lead',
                                                       I_RM_Status__c='Qualified',I_RM_Mobile_Phone__c='0415822666');
        insert af;
        I_RM_Affiliation__c aff=new I_RM_Affiliation__c(RecordTypeID=affiliationApplicantRecordTypeId,
                                                        I_RM_Contact__c=con.Id,
                                                        I_RM_Role__c='Applicant',
                                                        I_RM_Status__c='Make An Offer',I_RM_Mobile_Phone__c='0415822667');
        insert aff;
         List<I_RM_Affiliation__c> beforeUpadateAff = [select ID,I_RM_EndDate__c,I_RM_Email__c from I_RM_Affiliation__c where ID =: aff.ID];
        List<I_RM_Affiliation__c> UpdateAff=new List<I_RM_Affiliation__c>();
        for(I_RM_Affiliation__c old:beforeUpadateAff){
            old.I_RM_Email__c = 'newemail@ibm.com';
            UpdateAff.add(old);
        }
         Contact c = [select ID,I_ST_Student_Email__c from contact where ID =: con.ID];
         I_RM_Affiliation__c postUpdate = [select ID,I_RM_Email__c from I_RM_Affiliation__c where ID IN: beforeUpadateAff];
         system.assertEquals(c.I_ST_Student_Email__c,postUpdate.I_RM_Email__c,'Email on Contact and Affiliation are synced');
        Test.stopTest();
    }    
    
    //create lead affliation record if applicant affliation record is inactive test.
    @isTest
    public static void createLeadAffliationsNegativeTest(){       
    
        Contact cont22 = new Contact(FirstName='TestFirst1',LastName='TestLast1',I_ST_Personal_Email__c='test1@email.com');
        insert cont22;
        
        I_RM_Affiliation__c affl = new I_RM_Affiliation__c(RecordTypeID=Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Applicant').getrecordTypeId(),
                                                           I_RM_Contact__c = cont22.Id,
                                                           I_RM_Role__c = 'Applicant',                                               
                                                           I_RM_Status__c = 'Not Processed');    
        insert affl;
        test.startTest();
        affl.I_RM_Status__c = 'Inactive';
        update affl;
        List<I_RM_Affiliation__c> leadAffls = new List<I_RM_Affiliation__c>();
        leadAffls = [Select Id,I_RM_Contact__c, I_RM_Role__c from  I_RM_Affiliation__c where I_RM_Role__c = 'Domestic Lead' AND I_RM_Contact__c =: cont22.id];
        test.stopTest();
        
        System.assertEquals(0, leadAffls.size());
    }

        //create lead affliation record if applicant affliation record is inactive test.
        @isTest
        public static void createLeadAffliationsPositiveTest(){       
        
            Contact cont22 = new Contact(FirstName='TestFirst1',LastName='TestLast1',I_ST_Personal_Email__c='test1@email.com');
            insert cont22;
            
            I_RM_Affiliation__c affl = new I_RM_Affiliation__c(RecordTypeID=Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Applicant').getrecordTypeId(),
                                                               I_RM_Contact__c = cont22.Id,
                                                               I_RM_Role__c = 'Applicant',
                                                               I_RM_Email__c = 'test12@email.com', 
                                                               I_RM_Mobile_Phone__c='0415822666',                                                
                                                               I_RM_Status__c = 'Not Processed');    
            insert affl;
            test.startTest();
            affl.I_RM_Status__c = 'Inactive';
            update affl;
            List<I_RM_Affiliation__c> leadAffls = new List<I_RM_Affiliation__c>();
            leadAffls = [Select Id,I_RM_Contact__c, I_RM_Role__c from  I_RM_Affiliation__c where I_RM_Role__c = 'Domestic Lead' AND I_RM_Contact__c =: cont22.id];
            test.stopTest();
            
            System.assertEquals('Domestic Lead', leadAffls[0].I_RM_Role__c);
        }
    
    //Teja Yenduri IBM, Bluewolf 07/03/2022//
    @isTest
    public static void testInactiveStudentAffiliation(){ 
        test.startTest();
        Contact newDomesticLead = new Contact(FirstName = 'Test1', 
                                              LastName = 'last1',
                                              Email = 'abc@ibm.com.invalid', 
                                              I_ST_Personal_Email__c = 'abc@ibm.com.invalid',                                              
                                              OtherPostalCode = '3029',
                                              I_RS_Deceased__c = FALSE);
        
        
        insert newDomesticLead; 
        
        
        
        I_RM_Affiliation__c aff1 =new I_RM_Affiliation__c(RecordTypeID=Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Lead').getrecordTypeId(),
                                                          I_RM_Contact__c= newDomesticLead.Id,
                                                          I_RM_Role__c='Domestic Lead',I_RM_Email__c='abc@ibm.com.invalid',                                                         
                                                          I_RM_Status__c='Inactive',
                                                          I_RM_Mobile_Phone__c='0415822666');
        
        insert aff1;        
        
        I_RM_Affiliation__c aff2 =new I_RM_Affiliation__c(RecordTypeID=Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Lead').getrecordTypeId(),
                                                          I_RM_Contact__c= newDomesticLead.Id,
                                                          I_RM_Role__c='Domestic Lead',I_RM_Email__c='abc1@ibm.com.invalid',                                                            
                                                          I_RM_Status__c='Not Qualified',
                                                          I_RM_Mobile_Phone__c='0415822667');
        
        insert aff2;
        
        I_RM_Affiliation__c aff3 =new I_RM_Affiliation__c(RecordTypeID=Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Lead').getrecordTypeId(),
                                                          I_RM_Contact__c= newDomesticLead.Id,
                                                          I_RM_Role__c='Domestic Lead',I_RM_Email__c='abc2@ibm.com.invalid',                                                            
                                                          I_RM_Status__c='Not Qualified',
                                                          I_RM_Mobile_Phone__c='0415822668');
        
        insert aff3;
        
        I_RM_Affiliation__c aff=new I_RM_Affiliation__c(RecordTypeID = affiliationStudentRecordTypeId,
                                                        I_RM_Contact__c=newDomesticLead.Id,
                                                        I_RM_Role__c='Student',I_RM_Email__c='caseoftypeenquiry@ibm.com',
                                                        I_RM_Status__c='Inactive',
                                                        I_RM_Mobile_Phone__c='0415822669');
        
        insert aff;        
        
        
        test.StopTest();
        List<I_RM_Affiliation__c> affToBeUpdated = [SELECT Id, Name,I_RM_Status__c,I_RM_Contact__c FROM I_RM_Affiliation__c where I_RM_Role__c ='Domestic Lead' AND I_RM_Contact__c =: newDomesticLead.Id];       
        system.assertEquals('Qualified', affToBeUpdated[2].I_RM_Status__c);
    }  
    
    @isTest 
    public static void updateContactEmailfieldsApplicantTest(){
        Test.startTest();
        Contact cont22 = new Contact(FirstName='TestFirst1',LastName='TestLast1',I_ST_Personal_Email__c='test1@email.com');
        insert cont22;
        I_RM_Affiliation__c aff=new I_RM_Affiliation__c(RecordTypeID=affiliationApplicantRecordTypeId,
                                                        I_RM_Contact__c=cont22.Id,
                                                        I_RM_Role__c='Applicant',
                                                        I_RM_Status__c='Make An Offer',
                                                        I_RM_Mobile_Phone__c='0415822666');
        insert aff;
        aff.I_RM_Email__c = 'teste1@gmail1.com';
        update aff;
        Contact cont = New Contact();
        cont = [Select Id, I_RM_Applicant_Email__c from Contact Where Id = :  aff.I_RM_Contact__c];
        system.assertEquals('teste1@gmail1.com', cont.I_RM_Applicant_Email__c );
        Test.stopTest();
    } 

    @isTest 
    public static void updateContactEmailfieldsDomesticLeadTest(){
        Test.startTest();
        /*List<I_RM_Affiliation__c> domesticLeadAffiliation = [SELECT Id, Name,I_RM_Work_Email__c,I_RM_Student_Email__c, I_RM_Email__c, 
        I_RM_Contact__c, I_RM_Contact__r.I_RM_Applicant_Email__c FROM I_RM_Affiliation__c WHERE I_RM_Role__c ='Domestic Lead'];
        domesticLeadAffiliation[0].I_RM_Email__c = 'teste1@gmail1.com';*/
        Contact newDomesticLead = new Contact(FirstName='TestFirstName', LastName='TestLastName', Email='test12@test.com.invalid');       
       	insert newDomesticLead;  
        I_RM_Affiliation__c domesticLeadAffiliation =new I_RM_Affiliation__c(RecordTypeID=Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Lead').getrecordTypeId(),
                                                          I_RM_Contact__c= newDomesticLead.Id,
                                                          I_RM_Role__c='Domestic Lead',I_RM_Email__c='abc2@ibm.com.invalid',                                                            
                                                          I_RM_Status__c='Not Qualified',
                                                          I_RM_Mobile_Phone__c='0415822668');
        
        insert domesticLeadAffiliation;
        domesticLeadAffiliation.I_RM_Email__c = 'teste1@gmail1.com';
        update domesticLeadAffiliation;
        List<Contact> cont = New List<Contact>();
        cont = [Select Id, I_ST_Personal_Email__c from Contact Where Id = :  domesticLeadAffiliation.I_RM_Contact__c];
        system.assertEquals('teste1@gmail1.com', cont[0].I_ST_Personal_Email__c );
        Test.stopTest();
    }

    @isTest 
    public static void updateContactEmailfieldsLaTrobeStaffTest(){
        Test.startTest();
        List<Contact> contactList  = [SELECT Id,FirstName, Name FROM Contact];
    	I_RM_Affiliation__c newAffiliation = new I_RM_Affiliation__c(I_RM_Contact__c = contactList[0].Id,
                                                                     recordTypeId = affiliationStaffRecordTypeId,
                                                                  I_RM_Enquirer_Type__c ='Year 11',
                                                                  I_RM_Time_Frame_to_Study__c= '3-6 months',
                                                                  I_RM_Incremental_Score__c = 0,
                                                                  I_RM_Mobile_Phone__c = '0415822665',
                                                                  I_RM_Role__c ='La Trobe Staff', 
                                                                  I_RM_Score__c = 0,
                                                                  I_RM_Work_Email__c =  'teste2@gmail1.com'
                                                                 );

        Insert newAffiliation;
        newAffiliation.I_RM_Work_Email__c = 'teste1@gmail1.com';
        update newAffiliation;
        Contact cont = New Contact();
        cont = [Select Id, Email from Contact Where Id = :  newAffiliation.I_RM_Contact__c];
        system.assertEquals('teste1@gmail1.com', cont.Email );
        Test.stopTest();
    }

    @isTest 
    public static void updateContactEmailfieldsStudentTest(){
        Test.startTest();
        List<Contact> contactList  = [SELECT Id,FirstName, Name FROM Contact];
    	I_RM_Affiliation__c newAffiliation = new I_RM_Affiliation__c(I_RM_Contact__c = contactList[0].Id,
                                                                     recordTypeId = affiliationStudentRecordTypeId,                                                                  
                                                                     I_RM_Mobile_Phone__c = '0415822665',
                                                                     I_RM_Role__c ='Student',                                                                 
                                                                     I_RM_Student_Email__c =  'teste2@gmail1.com'
                                                                 );

        Insert newAffiliation;
        newAffiliation.I_RM_Student_Email__c = 'teste1@gmail1.com';
        update newAffiliation;
        Contact cont = New Contact();
        cont = [Select Id, I_ST_Student_Email__c from Contact Where Id = :  newAffiliation.I_RM_Contact__c];
        system.assertEquals('teste1@gmail1.com', cont.I_ST_Student_Email__c );
        Test.stopTest();
    }
    
    @isTest 
    public static void updateContactEmailfieldsStudentInsertTest(){
        Test.startTest();
        List<Contact> contactList  = [SELECT Id,FirstName, Name FROM Contact];
    	I_RM_Affiliation__c newAffiliation = new I_RM_Affiliation__c(I_RM_Contact__c = contactList[0].Id,
                                                                     recordTypeId = affiliationStudentRecordTypeId,                                                                  
                                                                     I_RM_Mobile_Phone__c = '0415822665',
                                                                     I_RM_Role__c ='Student',                                                                  
                                                                     I_RM_Student_Email__c =  'teste2@gmail1.com'
                                                                 );

        Insert newAffiliation;
        Contact cont = New Contact();
        cont = [Select Id, I_ST_Student_Email__c from Contact Where Id = :  newAffiliation.I_RM_Contact__c];
        system.assertEquals('teste2@gmail1.com', cont.I_ST_Student_Email__c );
        Test.stopTest();
    }        
      

    /* @author Vanita Walia
     * @date  08/03/2022
     * @description - LTU360-1248 : test method for testing creation of new domestic lead when an inactive student affiliation is created
     */
    
    @IsTest
	private static void testcreateLeadAff_InactiveStudent_Insert() {
        Test.startTest();
        
        Contact con = new Contact(FirstName='TestFirstName', LastName='TestLastName', Email='test12@test.com.invalid');       
       	insert con;         
		
        if(con != Null){
            //Create Inactive student affiliation record which should create a qualified lead affiliation record
            I_RM_Affiliation__c stuAff1=new I_RM_Affiliation__c(RecordTypeID = affiliationStudentRecordTypeId,
                                                        I_RM_Contact__c=con.Id,
                                                        I_RM_Role__c='Student',I_RM_Email__c='testemail@test.com.invalid',
                                                        I_RM_Status__c='Inactive',
                                                        I_RM_Mobile_Phone__c='0412345678');
            I_RM_Affiliation__c stuAff2=new I_RM_Affiliation__c(RecordTypeID = affiliationStudentRecordTypeId,
                                                        I_RM_Contact__c=con.Id,
                                                        I_RM_Role__c='Student',I_RM_Email__c='testemail@test.com.invalid',
                                                        I_RM_Status__c='Inactive',
                                                        I_RM_Mobile_Phone__c='0412345679');
            
            List<I_RM_Affiliation__c> stuAff = new List<I_RM_Affiliation__c>{stuAff1,stuAff2};
            insert stuAff;            
        }
        List<I_RM_Affiliation__c> leadAff = [Select Id, I_RM_Status__c from I_RM_Affiliation__c where I_RM_Role__c = 'Domestic Lead' 
                                      		and I_RM_Contact__c=:con.Id ];
       // match the status of new created domestic lead affiliation record to Qualified
        system.assertEquals('Qualified', leadAff[0].I_RM_Status__c);
        Test.stopTest();
    }

    /* @author Vanita Walia
     * @date  28/03/2022
     * @description - LTU360-1248 : test method for test negative scenario when email and mobile is blank
     */
    @IsTest
	private static void testcreateLeadAff_InactiveStudent_NegativeTest() {
        Test.startTest();
        Contact con = new Contact(FirstName='TestFirstName', LastName='TestLastName', Email='test123@test.com.invalid');       
       	insert con;         
		
        if(con != Null){
            //Create student affiliation record
            I_RM_Affiliation__c stuAff=new I_RM_Affiliation__c(RecordTypeID = affiliationStudentRecordTypeId,
                                                        I_RM_Contact__c=con.Id,
                                                        I_RM_Role__c='Student',
                                                        I_RM_Status__c='Inactive');
            insert stuAff;        
        }
        List<I_RM_Affiliation__c> leadAff = [Select Id, I_RM_Status__c from I_RM_Affiliation__c where I_RM_Role__c = 'Domestic Lead' 
                                      		and I_RM_Contact__c=:con.Id ];        
       
        System.assertEquals(0, leadAff.size());
        Test.stopTest();
    }
    
    
     /* @author Vanita Walia
     * @date  08/03/2022
     * @description - LTU360-1248 : test method for testing creation of new domestic lead when a student affiliation is updated to Inactive status
     */
    @IsTest
	private static void testcreateLeadAff_InactiveStudent_Update() {
        Test.startTest();
        Contact con = new Contact(FirstName='TestFirstName', LastName='TestLastName', Email='test123@test.com.invalid');       
       	insert con;         
		
        if(con != Null){
            //Create student affiliation record
            I_RM_Affiliation__c stuAff=new I_RM_Affiliation__c(RecordTypeID = affiliationStudentRecordTypeId,
                                                        I_RM_Contact__c=con.Id,
                                                        I_RM_Role__c='Student',I_RM_Email__c='testemail2@test.com.invalid',
                                                        I_RM_Status__c='Nearing Completion',
                                                        I_RM_Mobile_Phone__c='0412345678');
            insert stuAff;            
        
        	//update the status of affiliation to inactive, it should create a qualified domestic lead affiliation record
        	stuAff.I_RM_Status__c ='Inactive';
        	update stuAff;
        }
        List<I_RM_Affiliation__c> leadAff = [Select Id, I_RM_Status__c from I_RM_Affiliation__c where I_RM_Role__c = 'Domestic Lead' 
                                      		and I_RM_Contact__c=:con.Id ];        
       
        system.assertEquals('Qualified', leadAff[0].I_RM_Status__c);
        Test.stopTest();
    }
    /* @author Rahul Kumar
     * @date  23/03/2022
     * @description - LTU360-1251 : test method for testing Update Active Applicant record when Student becomes Admitted And Enrolled
     */
    @isTest
    public static void updateActiveApplicant(){
        Test.startTest();
        Contact con = [SELECT Id FROM Contact WHERE I_ST_Personal_Email__c='test_unique0012@unique.com'];
        I_RM_Affiliation__c applicant=new I_RM_Affiliation__c(RecordTypeID = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Applicant').getrecordTypeId(),
                                                       I_RM_Contact__c=con.Id,
                                                       I_RM_Role__c='Applicant',
                                                       I_RM_Status__c='Make An Offer',I_RM_Email__c='applicant@invalid.com');
        insert applicant;
        I_RM_Affiliation__c student=new I_RM_Affiliation__c(RecordTypeID=Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Student').getRecordTypeId(),
                                                        I_RM_Contact__c=con.Id,
                                                        I_RM_Role__c='Student',
                                                        I_RM_Status__c='Admitted And Enrolled',I_RM_Email__c='student@invalid.com');
        insert student;
        I_RM_Affiliation__c postUpdate = [select ID,I_RM_Status__c from I_RM_Affiliation__c where I_RM_Contact__c =: con.ID and I_RM_Email__c='applicant@invalid.com'];
        //system.assertEquals('Inactive',postUpdate.I_RM_Status__c, 'Applicant status changes to inactive');
        Test.stopTest();
    }

    @IsTest
	private static void updateContactExternalEmalInsertTest() {
        Test.startTest();
        
        Contact con = new Contact(FirstName='TestFirstName', LastName='TestLastName', Email='test777@test.com.invalid');       
       	insert con;         
		
        if(con != Null){
            I_RM_Affiliation__c ecff1=new I_RM_Affiliation__c(RecordTypeID = affiliationECRecordTypeId,
                                                        I_RM_Contact__c=con.Id,
                                                        I_RM_Role__c='External Contact',I_RM_Email__c='testemail77@test.com.invalid',
                                                        I_RM_Status__c='Active',
                                                        I_RM_Work_Email__c = 'k1@g.com',
                                                        I_RM_Mobile_Phone__c='0412345678');
            I_RM_Affiliation__c ecff2=new I_RM_Affiliation__c(RecordTypeID = affiliationECRecordTypeId,
                                                        I_RM_Contact__c=con.Id,
                                                        I_RM_Role__c='External Contact',I_RM_Email__c='testemail88@test.com.invalid',
                                                        I_RM_Status__c='Inactive',
                                                        I_RM_Mobile_Phone__c='0412345679');
            
            List<I_RM_Affiliation__c> ecAff = new List<I_RM_Affiliation__c>{ecff1,ecff2};
            insert ecAff;            
        }
        List<Contact> contactList = [Select Id, I_RM_Examiner_Email__c from Contact where Id =: con.Id ];
       // match the status of new created domestic lead affiliation record to Qualified
        system.assertEquals('k1@g.com', contactList[0].I_RM_Examiner_Email__c);
        Test.stopTest();
    }

    @IsTest
	private static void updateContactExternalEmalUpdateTest() {
        Test.startTest();
        
        Contact con = new Contact(FirstName='TestFirstName', LastName='TestLastName', Email='test778@test.com.invalid');       
       	insert con;         
		
        if(con != Null){
            I_RM_Affiliation__c ecff1=new I_RM_Affiliation__c(RecordTypeID = affiliationECRecordTypeId,
                                                        I_RM_Contact__c=con.Id,
                                                        I_RM_Role__c='External Contact',I_RM_Email__c='testemail778@test.com.invalid',
                                                        I_RM_Status__c='Active',
                                                        I_RM_Work_Email__c = 'k1@g.com',
                                                        I_RM_Mobile_Phone__c='0412345678');
            I_RM_Affiliation__c ecff2=new I_RM_Affiliation__c(RecordTypeID = affiliationECRecordTypeId,
                                                        I_RM_Contact__c=con.Id,
                                                        I_RM_Role__c='External Contact',I_RM_Email__c='testemail779@test.com.invalid',
                                                        I_RM_Status__c='Active',
                                                        I_RM_Work_Email__c = 'k2@g.com',
                                                        I_RM_Mobile_Phone__c='0412345679');
            
            List<I_RM_Affiliation__c> ecAff = new List<I_RM_Affiliation__c>{ecff1,ecff2};
            insert ecAff;
            ecff1.I_RM_Work_Email__c = 'k3@g.com';
            update ecff1;
        }
        List<Contact> contactList = [Select Id, I_RM_Examiner_Email__c from Contact where Id =: con.Id ];
       // match the status of new created domestic lead affiliation record to Qualified
        system.assertEquals('k3@g.com;k2@g.com', contactList[0].I_RM_Examiner_Email__c);
        Test.stopTest();
    }

    @IsTest
	private static void updateContactExternalEmalDeleteTest() {
        Test.startTest();
        
        Contact con = new Contact(FirstName='TestFirstName', LastName='TestLastName', Email='test778@test.com.invalid');       
       	insert con;         
		
        if(con != Null){
            I_RM_Affiliation__c ecff1=new I_RM_Affiliation__c(RecordTypeID = affiliationECRecordTypeId,
                                                        I_RM_Contact__c=con.Id,
                                                        I_RM_Role__c='External Contact',I_RM_Email__c='testemail778@test.com.invalid',
                                                        I_RM_Status__c='Active',
                                                        I_RM_Work_Email__c = 'k1@g.com',
                                                        I_RM_Mobile_Phone__c='0412345678');
            I_RM_Affiliation__c ecff2=new I_RM_Affiliation__c(RecordTypeID = affiliationECRecordTypeId,
                                                        I_RM_Contact__c=con.Id,
                                                        I_RM_Role__c='External Contact',I_RM_Email__c='testemail778@test.com.invalid',
                                                        I_RM_Status__c='Active',
                                                        I_RM_Work_Email__c = 'k2@g.com',
                                                        I_RM_Mobile_Phone__c='0412345679');
            
            List<I_RM_Affiliation__c> ecAff = new List<I_RM_Affiliation__c>{ecff1,ecff2};
            insert ecAff;

            delete ecff1;
        }
        List<Contact> contactList = [Select Id, I_RM_Examiner_Email__c from Contact where Id =: con.Id ];
       // match the status of new created domestic lead affiliation record to Qualified
        system.assertEquals('k2@g.com', contactList[0].I_RM_Examiner_Email__c);
        Test.stopTest();
    }
    
    /* @author Vanita Walia
     * @date  22/04/2022
     * @description - LTU360-1492 : test method for testing creation of new domestic lead when an inactive graduate researcher affiliation is created
     */
    
    @IsTest
	private static void testcreateLeadAff_InactiveHDRStudent_Insert() {
        Test.startTest();
        
        Contact con = new Contact(FirstName='TestFirstName', LastName='TestLastName', Email='testhdr@test.com.invalid');       
       	insert con;         
		
        if(con != Null){
            //Create Inactive student affiliation record which should create a qualified lead affiliation record
            I_RM_Affiliation__c hdrStuAff1=new I_RM_Affiliation__c(RecordTypeID = affiliationHDRStudentRecordTypeId,
                                                        I_RM_Contact__c=con.Id,
                                                        I_RM_Role__c='HDR Student',I_RM_Email__c='testHDRemail1@test.com.invalid',
                                                        I_RM_Status__c='Inactive',
                                                        I_RM_Mobile_Phone__c='0442345678');
            I_RM_Affiliation__c hdrStuAff2=new I_RM_Affiliation__c(RecordTypeID = affiliationHDRStudentRecordTypeId,
                                                        I_RM_Contact__c=con.Id,
                                                        I_RM_Role__c='HDR Student',I_RM_Email__c='testHDRemail2@test.com.invalid',
                                                        I_RM_Status__c='Inactive',
                                                        I_RM_Mobile_Phone__c='0412345679');
            
            List<I_RM_Affiliation__c> hdrStuAff = new List<I_RM_Affiliation__c>{hdrStuAff1,hdrStuAff2};
            insert hdrStuAff;            
        }
        List<I_RM_Affiliation__c> leadAff = [Select Id, I_RM_Status__c from I_RM_Affiliation__c where I_RM_Role__c = 'Domestic Lead' 
                                      		and I_RM_Contact__c=:con.Id ];
       // match the status of new created domestic lead affiliation record to Qualified
        system.assertEquals('Qualified', leadAff[0].I_RM_Status__c);
        Test.stopTest();
    }
    @isTest
    public static void updateActiveLead(){
        Test.startTest();
        Contact con = [SELECT Id FROM Contact WHERE I_ST_Personal_Email__c='test_unique0012@unique.com'];
        I_RM_Affiliation__c lead=new I_RM_Affiliation__c(RecordTypeID = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Lead').getrecordTypeId(),
                                                       I_RM_Contact__c=con.Id,
                                                       I_RM_Role__c='Domestic Lead',
                                                       I_RM_Status__c='Not Qualified',I_RM_Email__c='lead@invalid.com');
        insert lead;
        I_RM_Affiliation__c applicant=new I_RM_Affiliation__c(RecordTypeID=Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Applicant').getRecordTypeId(),
                                                        I_RM_Contact__c=con.Id,
                                                        I_RM_Role__c='Applicant',I_RM_Email__c='applicant@invalid.com');
        insert applicant;
        I_RM_Affiliation__c updateApplicant=new I_RM_Affiliation__c(ID=applicant.ID,I_RM_Status__c='Admitted And Not Enrolled');
        update updateApplicant;
        
        I_RM_Affiliation__c postUpdate = [select ID,I_RM_Status__c from I_RM_Affiliation__c where I_RM_Contact__c =: con.ID and I_RM_Email__c='lead@invalid.com'];
        system.assertEquals('Inactive',postUpdate.I_RM_Status__c, 'Lead status changes to inactive');
        Test.stopTest();
    }
	
    /* @author Vanita Walia
     * @date  08/08/2022
     * @description - LTU360-2031 : test method for updating contact name on affiliation
     */
    @IsTest
	private static void testUpdateContactNameonAffiliation() {
        Test.startTest();
        Contact con = new Contact(FirstName='TestFirstName', LastName='TestLastName', Email='test123@test.com.invalid');       
       	insert con;         
		
        if(con != Null){
            //Create student affiliation record
            I_RM_Affiliation__c stuAff=new I_RM_Affiliation__c(RecordTypeID = affiliationStudentRecordTypeId,
                                                        I_RM_Contact__c=con.Id,
                                                        I_RM_Role__c='Student',
                                                        I_RM_Status__c='Inactive');
            insert stuAff;        
        }
        List<I_RM_Affiliation__c> aff = [Select Id, L_PR_Contact_Name__c from I_RM_Affiliation__c where I_RM_Contact__c =:con.Id ];        
        System.assertEquals(aff[0].L_PR_Contact_Name__c, 'TestFirstName TestLastName');
        
        Test.stopTest();
    }
    
    @isTest
    public static void setSponsoredFieldValue_Test(){
        
        Test.startTest();

        I_RM_Affiliation_Settings__c affSettings = (I_RM_Affiliation_Settings__c) TestUtility.newSObjectInstance(
            new Map<String, String> {
                'Name' => 'I_IL_Sponsored_by_Citizenship',
                'Value__c' => 'Saudi Arabia;Oman;United Arab Emirates;United Arab Emirates (the);Kuwait;Bahrain;Qatar',
                'I_RM_Status__c' => 'Coursework External Sponsorship;Graduate Research Scholarship;Graduate Research External Sponsorship;Other'
            },
            'I_RM_Affiliation_Settings__c'
        );
        insert affSettings;

        Account acc1 = (Account) TestUtility.newSObjectInstance(
            new Map<String, String> {
                'Name' => 'Test Account',
                'RecordTypeId' => Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(GlobalConstants.ACCOUNT_RECORD_TYPE_NAME_LTU_ORG_UNIT).getRecordTypeId()
            },
            'Account'
        );
        insert acc1;

        Contact cont1 = (Contact) TestUtility.newSObjectInstance(
            new Map<String, String> {
                'FirstName' => 'Test',
                'LastName' => 'Contact',
                'AccountId' => acc1.Id,
                'Email' => System.now().millisecond() + 'test@test.com', 
                'I_RS_Citizenship__c' => 'Saudi Arabia'
            },
            'Contact'
        );
        insert cont1;        
        
        
        I_RM_Affiliation__c aff1 = (I_RM_Affiliation__c) TestUtility.newSObjectInstance(
            new Map<String, String> {
                'RecordTypeId' => affiliationIntLeadRecordTypeId,
                'I_RM_Contact__c' => cont1.Id,
                'I_RM_Role__c' => 'Student Lead (Int)',
                'I_RM_Email__c' => 'caseoftypeenquiry@ibm.com.invalid',
                'I_RM_Status__c' => 'Not Qualified',
                'I_RM_Mobile_Phone__c' => '+61415822666'
            },
            'I_RM_Affiliation__c'
        );        
        insert aff1;

        System.assertEquals(
            'Yes', 
            [SELECT I_IL_Sponsored__c FROM I_RM_Affiliation__c WHERE Id = :aff1.Id].I_IL_Sponsored__c,
            'Expected Yes as the Country of residence matches one of the sponsorship countries'
        );
        
        aff1.I_IL_Intended_Funding_Source__c = 'Coursework External Sponsorship';
        update aff1;
        System.assertEquals(
            'Yes', 
            [SELECT I_IL_Sponsored__c FROM I_RM_Affiliation__c WHERE Id = :aff1.Id].I_IL_Sponsored__c,
            'Expected Yes as the Country of residence matches one of the sponsorship countries and intended funding source matches one of the list of acceptable values'
        );

        aff1.I_IL_Intended_Funding_Source__c = 'Self-funded';
        update aff1;
        System.assertEquals(
            'No', 
            [SELECT I_IL_Sponsored__c FROM I_RM_Affiliation__c WHERE Id = :aff1.Id].I_IL_Sponsored__c,
            'Expected No since the intended funding source doesn\'t match one of the list of acceptable values'
        );

        aff1.I_IL_Sponsored__c = 'Yes';
        update aff1;
        System.assertEquals(
            'Yes', 
            [SELECT I_IL_Sponsored__c FROM I_RM_Affiliation__c WHERE Id = :aff1.Id].I_IL_Sponsored__c,
            'Expected Yes as user enforced update bypasses the rules in the trigger'
        );

        Test.StopTest();        
    } 

    @isTest 
    public static void updateContactEmailfieldsInternationalLeadTest(){
        Test.startTest();

        Account acc1 = (Account) TestUtility.newSObjectInstance(
            new Map<String, String> {
                'Name' => 'Test Account',
                'RecordTypeId' => Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(GlobalConstants.ACCOUNT_RECORD_TYPE_NAME_LTU_ORG_UNIT).getRecordTypeId()
            },
            'Account'
        );
        insert acc1;

        Contact cont1 = (Contact) TestUtility.newSObjectInstance(
            new Map<String, String> {
                'FirstName' => 'Test',
                'LastName' => 'Contact',
                'AccountId' => acc1.Id,
                'Email' => System.now().millisecond() + 'test@test.com', 
                'I_RS_Citizenship__c' => 'Saudi Arabia'
            },
            'Contact'
        );
        insert cont1;        
        
        
        I_RM_Affiliation__c aff1 = (I_RM_Affiliation__c) TestUtility.newSObjectInstance(
            new Map<String, String> {
                'RecordTypeId' => affiliationIntLeadRecordTypeId,
                'I_RM_Contact__c' => cont1.Id,
                'I_RM_Role__c' => 'Student Lead (Int)',
                'I_RM_Email__c' => 'iltest@gmail.com.invalid',
                'I_RM_Status__c' => 'Not Qualified',
                'I_RM_Mobile_Phone__c' => '+61415822666'
            },
            'I_RM_Affiliation__c'
        );        
        insert aff1;
        System.assertEquals(
            aff1.I_RM_EMail__c,
            [SELECT I_ST_Personal_Email__c FROM Contact WHERE Id = :cont1.Id].I_ST_Personal_Email__c,
            'Personal email on contact should match RM_EMail__c on Affiliation for Intenational Leads');
        Test.stopTest();
    } 
}