force-app/main/default/objects/Case/fields/I_RM_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Affiliation</description>
    <label>Affiliation</label>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/I_ST_Campus_Interest__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Campus_Interest__c</fullName>
    <description>created for IST 188</description>
    <label>Campus Interest</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>I_ST_Campus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/I_ST_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Contact_First_Name__c</fullName>
    <description>To get the first name from webforms and to create new contact if the contact doesn&apos;t exist</description>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/I_ST_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Contact_Last_Name__c</fullName>
    <description>To get the last name from webforms and to create new contact if the contact doesn&apos;t exist</description>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/I_ST_Incremental_Score__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Incremental_Score__c</fullName>
    <label>Incremental Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/I_ST_Proposed_Activity_End_Datetime__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Proposed_Activity_End_Datetime__c</fullName>
    <description>Added for Activity booking web form</description>
    <label>Proposed Activity End Date and Time</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/I_ST_Proposed_Activity_Start_Datetime__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Proposed_Activity_Start_Datetime__c</fullName>
    <description>Proposed activity booking date and time provided by the requester</description>
    <label>Proposed Activity Start Date and Time</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/I_ST_School_or_Educational_body__c.field-meta.xml
<CustomField>
    <fullName>I_ST_School_or_Educational_body__c</fullName>
    <label>School Or Educational Body</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/I_ST_Score_Calculated__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Score_Calculated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>I ST Score Calculated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/I_ST_Study_Interest__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Study_Interest__c</fullName>
    <description>Created for IST 188</description>
    <label>Study Interest</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>I_ST_Study_Interest</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/I_ST_Study_Level__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Study_Level__c</fullName>
    <description>Added for IST -188</description>
    <label>Study Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>I_ST_Study_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/I_ST_Timeframe_To_Study__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Timeframe_To_Study__c</fullName>
    <description>Created for IST -188</description>
    <label>Timeframe To Study</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>I_ST_Time_Frame_to_Study</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/I_ST_Activity_Booking.recordType-meta.xml
<RecordType>
    <fullName>I_ST_Activity_Booking</fullName>
    <active>true</active>
    <businessProcess>IST Activity Booking</businessProcess>
    <description>Inbound Case received from Educational Institutes/Organisations for Tour/Event etc.</description>
    <label>Activity Booking</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/I_ST_Enquiry.recordType-meta.xml
<RecordType>
    <fullName>I_ST_Enquiry</fullName>
    <active>true</active>
    <businessProcess>IST ENQUIRY</businessProcess>
    <description>Inbound Case for SACE Team received via Phone/Email/Chat etc.</description>
    <label>Enquiry</label>
</RecordType>

force-app/main/default/objects/Contact/fields/I_RS_Related_User__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Related_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Refers to the user record associated to the contact</description>
    <label>Related User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_ST_Campus_Interest__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Campus_Interest__c</fullName>
    <description>Added for IST 43</description>
    <inlineHelpText>Gives Campus preference  for the contact</inlineHelpText>
    <label>Campus Interest</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>I_ST_Campus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/I_ST_Incremental_Score__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Incremental_Score__c</fullName>
    <label>Activity Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_ST_Personal_Email__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Personal_Email__c</fullName>
    <description>Created to allow user to store personal email</description>
    <externalId>true</externalId>
    <inlineHelpText>The personal email for this person.</inlineHelpText>
    <label>Student Lead Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_ST_Study_Interest__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Study_Interest__c</fullName>
    <description>Created for IST-43. This field is a controlling for Career Interest Field</description>
    <label>Study Interest</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>I_ST_Study_Interest</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/I_ST_Study_Level__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Study_Level__c</fullName>
    <description>Created for IST-43</description>
    <label>Study Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>I_ST_Study_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/I_RM_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Part of the remediation project to store different personas</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Account__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to organisation</description>
    <label>Organisation</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>I_RS_External_Organisation</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>I_RS_La_Trobe_Organisation_Unit</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>I_ST_Educational_Institution</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliations</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Contact__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Contact__c</fullName>
    <description>The person/contact who this Affiliation relates to</description>
    <inlineHelpText>The person this affiliation relates to</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Affiliations</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Email__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Email__c</fullName>
    <description>Depicts Personal Email</description>
    <inlineHelpText>The personal email for this person.</inlineHelpText>
    <label>Personal Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Mobile_Phone__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Mobile_Phone__c</fullName>
    <description>Depicts affiliation&apos;s Mobile Phone number</description>
    <label>Mobile Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Other_Phone__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Other_Phone__c</fullName>
    <description>Depicts affiliation&apos;s Work Phone number</description>
    <label>Work Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Phone__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Phone__c</fullName>
    <description>Depicts affiliation&apos;s Home Phone number</description>
    <label>Home Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Role__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Role__c</fullName>
    <description>This represents the role of the affiliation</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Domestic Lead</fullName>
                <label>Student Lead (Dom)</label>
            </value>
            <value>
                <fullName>Applicant</fullName>
                <label>Student Applicant (Dom)</label>
            </value>
            <value>
                <fullName>La Trobe Staff</fullName>
            </value>
            <value>
                <fullName>School Representative</fullName>
                <label>Secondary School Representative</label>
            </value>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>External Contact</fullName>
            </value>
            <value>
                <fullName>HDR Student</fullName>
                <label>Graduate Researcher</label>
            </value>
            <value>
                <fullName>Student Lead (Int)</fullName>
            </value>
            <value>
                <fullName>Nominated Affiliation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <description>Indicates the status of the Affiliation.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>I_RM_Role__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>I_ST_Contact_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Student_Email__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Student_Email__c</fullName>
    <description>Depicts Students Email address</description>
    <inlineHelpText>The student email for this person.</inlineHelpText>
    <label>Student Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Work_Email__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Work_Email__c</fullName>
    <description>Depicts Work Email address</description>
    <inlineHelpText>Note: Graduate researchers, this is their institutional email (or staff email if they are also staff)</inlineHelpText>
    <label>Work Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_External_Contact.recordType-meta.xml
<RecordType>
    <fullName>I_RM_External_Contact</fullName>
    <active>true</active>
    <description>A Person external to La Trobe (i.e. partner)</description>
    <label>External Contact</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/I_RM_Affiliation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Affiliation Settings</label>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_ST_BatchScoring__c/I_ST_BatchScoring__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>I_ST_BatchScoring</label>
</CustomObject>

force-app/main/default/objects/I_ST_BatchScoring__c/fields/I_ST_RecordType_SFIDs__c.field-meta.xml
<CustomField>
    <fullName>I_ST_RecordType_SFIDs__c</fullName>
    <description>Provide comma separated RecordTypeIds of Case object which is to be considered for Activity Scoring. To get the record type Ids =&gt; Navigate to Setup -&gt; Object Manager -&gt; Case -&gt; RecordTypes -&gt; Select the record type -&gt; copy the 18 digit Id from the URL</description>
    <label>I_ST_RecordType_SFIDs</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/I_ST_Contact_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Admitted</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And LOA</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Not Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Considered</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Made</fullName>
    </customValue>
    <customValue>
        <fullName>Await Academic Advice</fullName>
    </customValue>
    <customValue>
        <fullName>Await Applicant Comms</fullName>
    </customValue>
    <customValue>
        <fullName>Await Further Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Awaiting Interview</fullName>
    </customValue>
    <customValue>
        <fullName>Await Required Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Escalated</fullName>
    </customValue>
    <customValue>
        <fullName>Make A Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make Alternate Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make An Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Nearing Completion</fullName>
    </customValue>
    <customValue>
        <fullName>Not Processed</fullName>
    </customValue>
    <customValue>
        <fullName>Not Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Lapsed</fullName>
    </customValue>
    <customValue>
        <fullName>Other Preference Offered</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Results</fullName>
    </customValue>
    <customValue>
        <fullName>Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <description>Global value set is created for lead(contact) object ST -51</description>
    <masterLabel>I_ST_Contact_Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/I_ST_Study_Interest.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Any</fullName>
    </customValue>
    <customValue>
        <fullName>Arts, Social Sciences and Communications</fullName>
    </customValue>
    <customValue>
        <fullName>Business and Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Education and teaching</fullName>
    </customValue>
    <customValue>
        <fullName>Health</fullName>
    </customValue>
    <customValue>
        <fullName>IT and engineering</fullName>
    </customValue>
    <customValue>
        <fullName>Law and criminology</fullName>
    </customValue>
    <customValue>
        <fullName>Science</fullName>
    </customValue>
    <customValue>
        <fullName>General</fullName>
        <isActive>false</isActive>
        <label>General</label>
    </customValue>
    <customValue>
        <fullName>Aspire</fullName>
        <isActive>false</isActive>
        <label>Aspire</label>
    </customValue>
    <customValue>
        <fullName>Pathways</fullName>
        <isActive>false</isActive>
        <label>Pathways</label>
    </customValue>
    <customValue>
        <fullName>Information technology</fullName>
        <isActive>false</isActive>
        <label>Information technology</label>
    </customValue>
    <customValue>
        <fullName>Engineering</fullName>
        <isActive>false</isActive>
        <label>Engineering</label>
    </customValue>
    <customValue>
        <fullName>Law</fullName>
        <isActive>false</isActive>
        <label>Law</label>
    </customValue>
    <customValue>
        <fullName>Criminology</fullName>
        <isActive>false</isActive>
        <label>Criminology</label>
    </customValue>
    <description>Created for IST-43</description>
    <masterLabel>I_ST_Study_Interest</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/I_ST_Study_Level.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Undergraduate</fullName>
    </customValue>
    <customValue>
        <fullName>Postgraduate</fullName>
    </customValue>
    <customValue>
        <fullName>Graduate Research</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Non-award</fullName>
        <isActive>false</isActive>
        <label>Non-award</label>
    </customValue>
    <customValue>
        <fullName>Unsure</fullName>
        <isActive>false</isActive>
        <label>Unsure</label>
    </customValue>
    <customValue>
        <fullName>PG</fullName>
        <isActive>false</isActive>
        <label>PG</label>
    </customValue>
    <customValue>
        <fullName>Other award</fullName>
        <isActive>false</isActive>
        <label>Other award</label>
    </customValue>
    <customValue>
        <fullName>UG</fullName>
        <isActive>false</isActive>
        <label>UG</label>
    </customValue>
    <customValue>
        <fullName>Study Level</fullName>
        <isActive>false</isActive>
        <label>Study Level</label>
    </customValue>
    <description>Created for IST 43</description>
    <masterLabel>I_ST_Study_Level</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/I_ST_Time_Frame_to_Study.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1-3 months</fullName>
    </customValue>
    <customValue>
        <fullName>3-6 months</fullName>
    </customValue>
    <customValue>
        <fullName>6-12 months</fullName>
    </customValue>
    <customValue>
        <fullName>1-2 years</fullName>
    </customValue>
    <customValue>
        <fullName>2-3 years</fullName>
    </customValue>
    <customValue>
        <fullName>3+ years</fullName>
    </customValue>
    <customValue>
        <fullName>Unsure</fullName>
    </customValue>
    <customValue>
        <fullName>12+ months</fullName>
        <isActive>false</isActive>
        <label>12+ months</label>
    </customValue>
    <description>Created for IST 43</description>
    <masterLabel>I_ST_Time_Frame_to_Study</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/I_ST_CaseTriggerHandlerTest.cls
@isTest
public class I_ST_CaseTriggerHandlerTest {
	 @TestSetup
    static void setup() {
        String affiliationRecordTypIds = I_ST_UnitTestUtilities.recordTypeIds(GlobalConstants.AFFILIATION_OBJECT_API_NAME,GlobalConstants.AFFILIATION_RECORD_TYPE_NAME_LEAD);
        String caseRecordTypeIds = I_ST_UnitTestUtilities.recordTypeIds(GlobalConstants.CASE_OBJECT_API_NAME,GlobalConstants.CASE_RECORD_TYPE_API_NAME_ENQUIRY);
        
        List<I_ST_BatchScoring__c> listBatchScoringSetting = I_ST_UnitTestUtilities.createBatchScoringCustomSetting(affiliationRecordTypIds,20,caseRecordTypeIds,20,null,null);           
        insert listBatchScoringSetting;
        
        
		Id CaseRecordTypeId =  I_ST_BatchScoring__c.getValues('I_ST_CaseScoring').I_ST_RecordType_SFIDs__c.split(',')[0];
       
        I_ST_CaseTriggerHandler.setNotFired();       
        Account newExternalAccount = TestUtility.newEmptyExternalAccount('Test Account');
        insert newExternalAccount;
        List<Contact>listDomesticLeadContacts = new List<Contact>();
       	I_RM_Affiliation_Settings__c objAffiliationSettings = I_ST_UnitTestUtilities.createAffiliationSettings();
        insert objAffiliationSettings;
        for(Integer i =0; i<10; i++){
            Contact newDomesticLead = I_ST_UnitTestUtilities.createContactForScore('test_unique001'+i,
                                                                                   'unique_test001'+i,
                                                                                   'test_unique001'+i+'@unique.com',
                                                                                   'test_unique001'+i+'@unique.com',                                                                                  
                                                                                   '3029');
                                                                                           
            listDomesticLeadContacts.add(newDomesticLead);
        }
        Insert listDomesticLeadContacts;
        //Creating Cases to test incremental score on record creation.
        List<Case> casesforTest = New List<Case>();
        List<Case> enquiryCases = New List<Case>();
        for(Integer j=0; j<listDomesticLeadContacts.size(); j++) {
            case newcase =  I_ST_UnitTestUtilities.newListOfContactRelatedCases(CaseRecordTypeId,listDomesticLeadContacts[j],10,false,'Title First'+j,'Open','test@test.com.invalid',null);
            casesforTest.add(newcase);           
        }        
        Insert casesforTest;
        for(Integer i=0; i<listDomesticLeadContacts.size(); i++){
            case objEnquirycase =  I_ST_UnitTestUtilities.newListOfContactRelatedCases(caseRecordTypeIds,listDomesticLeadContacts[i],10,false,'Title FirstEnquiry'+i,'Open','test@test.com.invalid',null);
            enquiryCases.add(objEnquirycase);
        }
        
    }
    //Testing Incrementascore for update case.
    @isTest
    public static void testCalculateIncrementScore(){
        
        test.startTest();    	
            Contact domesticContact = [SELECT Id, Name, I_RS_Related_User__c FROM Contact WHERE email = 'test_unique0011@unique.com' LIMIT 1];
            List<Case> caseToProcess = [SELECT Id,Subject,Type,RecordTypeId,Origin,Status,ContactId,I_ST_Incremental_Score__c FROM case WHERE ContactId =: domesticContact.Id];             
            
            case caseToUpdate = new case();
            caseToUpdate.id = caseToProcess[0].id;        
            caseToUpdate.Origin = 'Email';
            I_ST_CaseTriggerHandler.setNotFired();      
            update caseToUpdate;
            
            I_ST_CaseTriggerHandler.hasFired();
        test.stopTest();
        
        system.assertEquals(20,caseToProcess[0].I_ST_Incremental_Score__c);
	}
    
    //Testing Case Affiliation update.
    @isTest
    public static void testCreateLeadAffiliation(){
        
        test.startTest();
        	String caseRecordTypeIds = I_ST_UnitTestUtilities.recordTypeIds(GlobalConstants.CASE_OBJECT_API_NAME,GlobalConstants.CASE_RECORD_TYPE_API_NAME_ENQUIRY);
        	Contact domesticContact = [SELECT Id, Name, I_RS_Related_User__c FROM Contact WHERE email = 'test_unique0011@unique.com' LIMIT 1];
            List<Case> caseToProcess = [SELECT Id,Subject,I_RM_Affiliation__c,I_RM_Affiliation__r.I_RM_Contact__c,I_ST_Campus_Interest__c,RecordTypeId,I_ST_Study_Interest__c,I_ST_Study_Level__c,I_ST_Timeframe_To_Study__c,ContactId,I_ST_Incremental_Score__c FROM case WHERE ContactId =: domesticContact.Id AND RecordTypeId =: caseRecordTypeIds];             
        	Case objUpdatedCase = caseToProcess[0];
        	system.assertEquals(objUpdatedCase.ContactId,objUpdatedCase.I_RM_Affiliation__r.I_RM_Contact__c,'Case contact and affiliation contact is match');
        test.stopTest();
    }
    
    //Testing Case Affiliation update.
    @isTest
    public static void testCreateLeadAffiliationWeb(){
       String caseRecordTypeIds = I_ST_UnitTestUtilities.recordTypeIds(GlobalConstants.CASE_OBJECT_API_NAME,GlobalConstants.CASE_RECORD_TYPE_API_NAME_ENQUIRY);
       Contact domesticContact = [SELECT Id, Name, I_RS_Related_User__c FROM Contact WHERE email = 'test_unique0011@unique.com' LIMIT 1];
       Case newCase2 = new Case(Subject = 'Title',
                                 Type='Entry Requirements',
                                 Origin = 'Web',
                                 SuppliedEmail = 'test_unique0011@unique.com.invalid',
                                 RecordTypeId = caseRecordTypeIds,                                 
                                 I_ST_Score_Calculated__c = false,                                
                                 ContactId = domesticContact.id);
        insert newCase2;
        
       test.startTest(); 
          
            List<Case> caseToProcess = [SELECT Id,Subject,I_RM_Affiliation__c,I_RM_Affiliation__r.I_RM_Contact__c,I_ST_Campus_Interest__c,RecordTypeId,I_ST_Study_Interest__c,I_ST_Study_Level__c,I_ST_Timeframe_To_Study__c,ContactId,I_ST_Incremental_Score__c FROM case WHERE ContactId =: domesticContact.Id AND RecordTypeId =: caseRecordTypeIds AND Origin = 'Web' ];             
        	Case objUpdatedCase = caseToProcess[0];
        	system.assertEquals(objUpdatedCase.ContactId,objUpdatedCase.I_RM_Affiliation__r.I_RM_Contact__c,'Case contact and affiliation contact is match');
        test.stopTest();
        
    }
        
        
        
        
        //Testing Case Affiliation update.
    @isTest
    public static void testCreateLeadAffiliationOfflineChat(){ 
         String caseRecordTypeIds = I_ST_UnitTestUtilities.recordTypeIds(GlobalConstants.CASE_OBJECT_API_NAME,GlobalConstants.CASE_RECORD_TYPE_API_NAME_ENQUIRY);
         Contact domesticContact = [SELECT Id, Name, I_RS_Related_User__c FROM Contact WHERE email = 'test_unique0011@unique.com' LIMIT 1];
        Case newCase3 = new Case(Subject = 'Title',
                                 Type='Entry Requirements',
                                 Origin = 'Offline Chat',
                                 SuppliedEmail = 'test_unique0011@unique.com.invalid',      
                                 RecordTypeId = CaseRecordTypeIds,
                                 ContactId = domesticContact.id);
        insert newCase3;
        test.startTest(); 
          
            List<Case> caseToProcess = [SELECT Id,Subject,I_RM_Affiliation__c,I_RM_Affiliation__r.I_RM_Contact__c,I_ST_Campus_Interest__c,RecordTypeId,I_ST_Study_Interest__c,I_ST_Study_Level__c,I_ST_Timeframe_To_Study__c,ContactId,I_ST_Incremental_Score__c FROM case WHERE ContactId =: domesticContact.Id AND RecordTypeId =: caseRecordTypeIds AND Origin = 'Offline Chat' ];             
        	Case objUpdatedCase = caseToProcess[0];
        	system.assertEquals(objUpdatedCase.ContactId,objUpdatedCase.I_RM_Affiliation__r.I_RM_Contact__c,'Case contact and affiliation contact is match');
        test.stopTest();
        
    }
       
    @isTest
    public static void checkForMatchingActivityCaseValue(){
      test.startTest();
        Account a=new Account(Name='fromcaseaccounttestclass1');
        insert a;
        Contact con=new Contact(FirstName='Activity',LastName='Case',I_ST_Personal_Email__c='caseoftypeenquiry@ibm.com',AccountId=a.Id);
        	insert con;
        I_RM_Affiliation__c aff=new I_RM_Affiliation__c(RecordTypeID=Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_External_Contact').getrecordTypeId(),
            					I_RM_Contact__c=con.Id,I_RM_Account__c=a.Id,I_RM_Phone__c='+61412345678',
                                I_RM_Role__c='School Representative',I_RM_Email__c='caseoftypeenquiry@ibm.com',
                                I_RM_Status__c='Active',
                                I_RM_Mobile_Phone__c='+61412345678',I_RM_Other_Phone__c='+61412345678');
            insert aff;
                                                       
   //insert case of type enquiry with available Email and Phone
        case c=new case(RecordTypeID=Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('I_ST_Activity_Booking').getrecordTypeId(),
                        subject='CaseOfTypeActivity',
                        Origin='Email',SuppliedEmail='caseoftypeenquiry@ibm.com',
                        SuppliedName='Enquiry Case',
                        SuppliedPhone='+61412345678',
                       I_ST_School_or_Educational_body__c='fromcaseaccounttestclass1');
		insert c;
        Case cs=[Select ID,ContactID,SuppliedEmail from Case where ID =: c.ID];
        system.assertEquals(cs.ContactID,con.ID);        
    test.stopTest();
    }  
    @isTest
    public static void checkForUnmatchedCaseValue(){
      test.startTest();
        Account a=new Account(Name='fromcaseaccounttestclass1');
        insert a;       
        Contact con=new Contact(FirstName='Activity',LastName='Case',I_ST_Personal_Email__c='caseoftypeenquiry@ibm.com',AccountId=a.Id);
        	insert con;
        I_RM_Affiliation__c aff=new I_RM_Affiliation__c(RecordTypeID=Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_External_Contact').getrecordTypeId(),
            					I_RM_Contact__c=con.Id,I_RM_Account__c=a.Id,I_RM_Phone__c='+61412345678',
                                I_RM_Role__c='School Representative',I_RM_Email__c='caseoftypeenquiry@ibm.com',
                                I_RM_Status__c='Active',
                                I_RM_Mobile_Phone__c='0441234563',I_RM_Other_Phone__c='0452648936');
            insert aff;                                                       
   //insert case of type Activity with unmatched Email and Phone
        case c=new case(RecordTypeID=Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('I_ST_Activity_Booking').getrecordTypeId(),
                        subject='CaseOfTypeUnmatched',
                        Origin='Email',SuppliedEmail='unmatched@ibm.com',
                        SuppliedName='Unmatched Case',
                        SuppliedPhone='0441234563',
                        I_ST_Proposed_Activity_Start_Datetime__c='2022-07-01 19:30:00',
                        I_ST_Proposed_Activity_End_Datetime__c = '2022-08-01 19:30:00',
                       I_ST_School_or_Educational_body__c='Unmatched Account');
		insert c;
        Case cs=[Select ID,ContactID,SuppliedEmail from Case where ID =: c.ID];
        Contact ct=[Select ID from Contact where ID =: cs.ContactID];
        system.assertEquals(cs.ContactID,ct.ID);        
    test.stopTest();  

    }
   
    @isTest
    public static void createContactAndAffiliation(){
        test.startTest();
        case c=new case(RecordTypeID=Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('I_ST_Enquiry').getrecordTypeId(),
                        subject='CaseCreateContact', 
                        SuppliedPhone='0441234563',
                        I_ST_Contact_First_Name__c  ='test1',
                        I_ST_Contact_Last_Name__c  ='last1'
                      );
		insert c;
        test.stopTest();        
    }
    @isTest
    public static void checkForNameandPhCaseValue(){
      test.startTest();
        Account a=new Account(Name='fromcaseaccounttestclass1');
        insert a;
        Contact con=new Contact(FirstName='Activity',LastName='Case',I_ST_Personal_Email__c='caseoftypeenquiry@ibm.com',AccountId=a.Id,MobilePhone='6374829760',Phone='6374829771',OtherPhone='6374829782');
        	insert con;
        I_RM_Affiliation__c aff=new I_RM_Affiliation__c(RecordTypeID=Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_External_Contact').getrecordTypeId(),
            					I_RM_Contact__c=con.Id,I_RM_Account__c=a.Id,I_RM_Phone__c='+61412345678',
                                I_RM_Role__c='School Representative',I_RM_Email__c='caseoftypeenquiry@ibm.com',
                                I_RM_Status__c='Active',
                                I_RM_Mobile_Phone__c='0441234563',I_RM_Other_Phone__c='0845264893');
            insert aff;                 
   //insert case of type Activity with SuppliedName and Phone
        case c=new case(RecordTypeID=Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('I_ST_Activity_Booking').getrecordTypeId(),
                        subject='CaseOfTypeUnmatched',
                        Origin='Email',
                        SuppliedName='Matched Phone',
                        SuppliedPhone='0441234563',
                        ContactId = con.Id,
                       I_ST_School_or_Educational_body__c='Unmatched Account');
		insert c;
        Case cs=[Select ID,ContactID,SuppliedEmail,I_RM_Affiliation__c from Case where ID =: c.ID];
        Contact ct=[Select ID,Name from contact where ID =: cs.ContactID];
        I_RM_Affiliation__c caseAff = [Select ID,I_RM_Contact__c from I_RM_Affiliation__c where ID =: cs.I_RM_Affiliation__c];
        
        system.assertEquals(cs.ContactID,ct.ID);       
        system.assertEquals(cs.ContactID,caseAff.I_RM_Contact__c);       
    test.stopTest();
    }
    @isTest
    public static void checkForStudentEmailMatchingAffiliation(){
      test.startTest();
        Account a=new Account(Name='fromcaseaccounttestclass1');
        insert a;
        Contact con=new Contact(FirstName='Activity',LastName='Case',I_ST_Personal_Email__c='caseoftypeactivity@ibm.com',AccountId=a.Id,MobilePhone='6374829760',Phone='6374829771',OtherPhone='6374829782');
        	insert con;
        I_RM_Affiliation__c aff=new I_RM_Affiliation__c(RecordTypeID=Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_External_Contact').getrecordTypeId(),
            					I_RM_Contact__c=con.Id,I_RM_Account__c=a.Id,I_RM_Phone__c='+61412345678',
                                I_RM_Role__c='School Representative',I_RM_Student_Email__c='caseoftypeactivity@ibm.com',
                                I_RM_Status__c='Active',
                                I_RM_Mobile_Phone__c='0441234563',I_RM_Other_Phone__c='0845264893');
            insert aff;                 
   //insert case of type Activity with SuppliedName and Phone
        case c=new case(RecordTypeID=Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('I_ST_Activity_Booking').getrecordTypeId(),
                        subject='CaseOfTypeUnmatched',
                        Origin='Email',
                        SuppliedEmail='caseoftypeactivity@ibm.com',
                        SuppliedName='Matched Phone',
                        SuppliedPhone='0441234563',
                       I_ST_School_or_Educational_body__c='Unmatched Account');
		insert c;
        Case cs=[Select ID,ContactID,SuppliedEmail,I_RM_Affiliation__c from Case where ID =: c.ID];
        Contact ct=[Select ID,Name from contact where ID =: cs.ContactID];
        I_RM_Affiliation__c caseAff = [Select ID,I_RM_Contact__c from I_RM_Affiliation__c where ID =: cs.I_RM_Affiliation__c];
        
        system.assertEquals(cs.ContactID,ct.ID);       
        system.assertEquals(cs.ContactID,caseAff.I_RM_Contact__c);       
    test.stopTest();
    }    
 @isTest
    public static void checkForAvailableSchoolRepOnCase(){
      test.startTest();
        Account a=new Account(Name='fromcaseaccounttestclass1');
        insert a;
        Contact con=new Contact(FirstName='Activity',LastName='Case',I_ST_Personal_Email__c='caseoftypeactivity@ibm.com',AccountId=a.Id,MobilePhone='6374829760',Phone='6374829771',OtherPhone='6374829782');
        	insert con;
        I_RM_Affiliation__c aff=new I_RM_Affiliation__c(RecordTypeID=Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_External_Contact').getrecordTypeId(),
            					I_RM_Contact__c=con.Id,I_RM_Account__c=a.Id,I_RM_Phone__c='+61412345678',
                                I_RM_Role__c='School Representative',I_RM_Work_Email__c='caseoftypeactivity@ibm.com',
                                I_RM_Status__c='Active',
                                I_RM_Mobile_Phone__c='0441234563',I_RM_Other_Phone__c='0845264893');
            insert aff;                 
   //insert case of type Activity with SuppliedName and Phone
        case c=new case(RecordTypeID=Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('I_ST_Activity_Booking').getrecordTypeId(),
                        subject='CaseForSchoolRep',
                        ContactId=con.ID,
                        Origin='Email',
                        SuppliedEmail='caseoftypeactivity@ibm.com',
                        SuppliedName='Matched Phone',
                        SuppliedPhone='0441234563',
                       I_ST_School_or_Educational_body__c='fromcaseaccounttestclass1');
		insert c;
        Case cs=[Select ID,ContactID,SuppliedEmail,I_RM_Affiliation__c from Case where ID =: c.ID];
        Contact ct=[Select ID,Name from contact where ID =: cs.ContactID];
        I_RM_Affiliation__c caseAff = [Select ID,I_RM_Contact__c from I_RM_Affiliation__c where ID =: cs.I_RM_Affiliation__c];
        
        system.assertEquals(cs.ContactID,ct.ID);       
        system.assertEquals(cs.I_RM_Affiliation__c,caseAff.ID);       
    test.stopTest();
    }
@isTest
    public static void checkForNoAvailableSchoolRepOnCase(){
      test.startTest();
        Account a=new Account(Name='fromcaseaccounttestclass1');
        insert a;
        Contact con=new Contact(FirstName='Activity',LastName='Case',I_ST_Personal_Email__c='caseoftypeactivity@ibm.com',AccountId=a.Id,MobilePhone='6374829760',Phone='6374829771',OtherPhone='6374829782');
        	insert con;
        I_RM_Affiliation__c aff=new I_RM_Affiliation__c(RecordTypeID=Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_External_Contact').getrecordTypeId(),
            					I_RM_Contact__c=con.Id,I_RM_Account__c=a.Id,I_RM_Phone__c='+61412345678',
                                I_RM_Role__c='School Representative',I_RM_Work_Email__c='caseoftypeactivity@ibm.com',
                                I_RM_Status__c='Inactive',
                                I_RM_Mobile_Phone__c='0441234563',I_RM_Other_Phone__c='0845264893');
            insert aff;                 
   //insert case of type Activity with SuppliedName and Phone
        case c=new case(RecordTypeID=Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('I_ST_Activity_Booking').getrecordTypeId(),
                        subject='CaseForSchoolRep',
                        ContactId=con.ID,
                        Origin='Email',
                        SuppliedEmail='caseoftypeactivity@ibm.com',
                        SuppliedName='Matched Phone',
                        SuppliedPhone='0441234563',
                       I_ST_School_or_Educational_body__c='fromcaseaccounttestclass1');
		insert c;
        Case cs=[Select ID,ContactID,SuppliedEmail,I_RM_Affiliation__c from Case where ID =: c.ID];
        Contact ct=[Select ID,Name from contact where ID =: cs.ContactID];
        I_RM_Affiliation__c caseAff = [Select ID,I_RM_Contact__c from I_RM_Affiliation__c where ID =: cs.I_RM_Affiliation__c];
        
        system.assertEquals(cs.ContactID,ct.ID);       
        system.assertEquals(cs.ContactID,caseAff.I_RM_Contact__c);       
    test.stopTest();
    } 
    @isTest
    public static void checkForNoNameOnCase(){
      test.startTest();
        Account a=new Account(Name='fromcaseaccounttestclass1');
        insert a;
        Contact con=new Contact(FirstName='Activity',LastName='Case',I_ST_Personal_Email__c='caseoftypeactivity@ibm.com',AccountId=a.Id,MobilePhone='6374829760',Phone='6374829771',OtherPhone='6374829782');
        	insert con;
        I_RM_Affiliation__c aff=new I_RM_Affiliation__c(RecordTypeID=Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_External_Contact').getrecordTypeId(),
            					I_RM_Contact__c=con.Id,I_RM_Account__c=a.Id,I_RM_Phone__c='+61412345678',
                                I_RM_Role__c='School Representative',I_RM_Work_Email__c='caseoftypeactivity@ibm.com',
                                I_RM_Status__c='Inactive',
                                I_RM_Mobile_Phone__c='0441234563',I_RM_Other_Phone__c='0845264893');
            insert aff;                 
   //insert case of type Activity with SuppliedName and Phone
        case c=new case(RecordTypeID=Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('I_ST_Activity_Booking').getrecordTypeId(),
                        subject='CaseWithNoName',
                        Origin='Email',
                        SuppliedEmail='caseoftypeactivity1@ibm.com',
                        SuppliedPhone='0441234563',
                       I_ST_School_or_Educational_body__c='fromcaseaccounttestclass1');
		insert c;
        Case cs=[Select ID,ContactID,SuppliedEmail,I_RM_Affiliation__c from Case where ID =: c.ID];
        
        system.assertEquals(cs.ContactID,NULL);      
    test.stopTest();
            }
    @isTest
    public static void errorlogs(){
        test.startTest();
        case c=new case(RecordTypeID=Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('I_ST_Activity_Booking').getrecordTypeId(),
                        subject='CaseOfErrorlogs',
                        Origin='Phone',                        
                        SuppliedEmail = 'doesnot@exist.com.invalid',
                        I_ST_Proposed_Activity_Start_Datetime__c='2022-07-01 19:30:00',
                        I_ST_Proposed_Activity_End_Datetime__c = '2022-08-01 19:30:00'
                       );
		insert c;
        test.stopTest();
    }
    @isTest
    public static void createInternationalContact_Test(){
        Test.startTest();

        Case caseRecNew = new Case(
            RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(GlobalConstants.CASE_RECORD_TYPE_NAME_INT_ENQUIRY).getRecordTypeId(),
            subject = 'CaseCreateContactAndAffiliation', 
            SuppliedPhone = '+61433776665',
            SuppliedEmail = 'test@test.com.invalid',
            Origin =  'Phone',
            I_ST_Contact_First_Name__c  = 'testIntLead1',
            I_ST_Contact_Last_Name__c  = 'last1'
        );
		insert caseRecNew;

        caseRecNew = [ SELECT contactId, I_RM_Affiliation__c 
                    FROM Case 
                    WHERE Id = :caseRecNew.Id];

        system.assertEquals(
            1,
            [SELECT Id 
             FROM Contact 
             WHERE Id = :caseRecNew.contactId].size(),
            'Expect new contact to be created and linked to case for International Enquiry'
        );
        system.assertEquals(
            1,
            [SELECT Id 
             FROM I_RM_Affiliation__c 
             WHERE Id = :caseRecNew.I_RM_Affiliation__c].size(),
            'Expect new affiliation to be created and linked to case for International Enquiry'
        );

        Case caseRecUpdate = new Case(
            RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(GlobalConstants.CASE_RECORD_TYPE_NAME_INT_ENQUIRY).getRecordTypeId(),
            subject = 'UpdateContactAndAffiliation', 
            SuppliedPhone = '+61433776665',            
            SuppliedEmail = 'test@test.com.invalid',
            Origin =  'Phone',
            I_ST_Contact_First_Name__c  = 'testIntLead1',
            I_ST_Contact_Last_Name__c  = 'last1'
        );
		insert caseRecUpdate;
        caseRecUpdate = [ SELECT contactId, I_RM_Affiliation__c 
                          FROM Case 
                          WHERE Id = :caseRecUpdate.Id];
        system.assertEquals(
            [SELECT Id 
             FROM Contact 
             WHERE Id = :caseRecNew.contactId].Id,
             caseRecUpdate.contactId,
            'Expect the previously created contact to be updated and linked to current case'
        );
        system.assertEquals(
            [SELECT Id 
             FROM I_RM_Affiliation__c 
             WHERE Id = :caseRecNew.I_RM_Affiliation__c].Id,
             caseRecUpdate.I_RM_Affiliation__c,
            'Expect the previously created affiliation to be updated and linked to current case'
        );
        Test.stopTest();        
    }
}