force-app/main/default/objects/URL_Variable__c/URL_Variable__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>URL Variable</label>
</CustomObject>

force-app/main/default/objects/URL_Variable__c/fields/I_RS_Researcher_Portal_Base_URL__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Researcher_Portal_Base_URL__c</fullName>
    <description>Base URL of the PRIME Researcher Portal. Used for hyperlinking.</description>
    <label>Researcher Portal Base URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/ReportMetadataAccess.cls
public class ReportMetadataAccess {
    
    @AuraEnabled(cacheable=true)
    public static Report getReportMetadata(String reportAPIName) {

        System.debug('getReportMetadata '+reportAPIName);

        Report report = [select Id from Report where DeveloperName = :reportAPIName];
        System.debug(report);

        return report;

    }


    @AuraEnabled(cacheable=true)
    public static String getReportPortalURL(String reportAPIName){

        Report report = getReportMetadata(reportAPIName);

        URL_Variable__c baseURLsVariable = URL_Variable__c.getOrgDefaults();
        String researcherPortalBaseURL =  baseURLsVariable.I_RS_Researcher_Portal_Base_URL__c;

        String reportURL = researcherPortalBaseURL + '/report/'+report.Id;

        System.debug('reportURL '+reportURL);

        return reportURL;

    }
}