force-app/main/default/objects/URL_Variable__c/URL_Variable__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>URL Variable</label>
</CustomObject>

force-app/main/default/objects/URL_Variable__c/fields/I_RS_Researcher_Portal_Base_URL__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Researcher_Portal_Base_URL__c</fullName>
    <description>Base URL of the PRIME Researcher Portal. Used for hyperlinking.</description>
    <label>Researcher Portal Base URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/ReportMetadataAccessTest.cls
@isTest(seeAllData=true)
public class ReportMetadataAccessTest {

    public static testmethod void linkedReportURLAccessTest() {

        if (URL_Variable__c.getOrgDefaults() == null){
            insert new URL_Variable__c(
                I_RS_Researcher_Portal_Base_URL__c = 'https://latrobe.prime.edu.au/s'
            );
        }

        Report anyRandomReport = [select DeveloperName from Report LIMIT 1];

        system.assert(
            ReportMetadataAccess.getReportPortalURL(anyRandomReport.DeveloperName)
            != null
        );

    }
}