force-app/main/default/objects/Graduate_Research_Examination__c/Graduate_Research_Examination__c.object-meta.xml
<CustomObject>
    <label>Graduate Research Examination</label>
    <nameField>
        <displayFormat>GRE-{00000}</displayFormat>
        <label>Record Title</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Graduate Research Examinations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Graduate_Research_Examination__c/fields/I_RS_Alternate_Supervisor__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Alternate_Supervisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Co-supervisor who has been nominated to act as approver if the principal supervisor is unavailable</inlineHelpText>
    <label>Alternate Supervisor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Graduate Research Examinations (Co-Supervisor)</relationshipLabel>
    <relationshipName>Co_Supervisor_Thesis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Graduate_Research_Examination__c/fields/I_RS_AS_User__c.field-meta.xml
<CustomField>
    <fullName>I_RS_AS_User__c</fullName>
    <description>Contains related user Id of contact &quot;I_RS_Alternate_Supervisor__c&quot;</description>
    <formula>I_RS_Alternate_Supervisor__r.I_RS_Related_User__c</formula>
    <label>AS User</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Graduate_Research_Examination__c/fields/I_RS_BGR_User__c.field-meta.xml
<CustomField>
    <fullName>I_RS_BGR_User__c</fullName>
    <description>Contains related user of the field &quot;I_RS_Board_of_Graduate_Research__c&quot; contact</description>
    <formula>I_RS_Board_of_Graduate_Research__r.I_RS_Related_User__c</formula>
    <label>BGR User</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Graduate_Research_Examination__c/fields/I_RS_Board_of_Graduate_Research__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Board_of_Graduate_Research__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Board of Graduate Research member with delegated responsibility to approve on behalf of the Board, normally the Chair</inlineHelpText>
    <label>Board of Graduate Research</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Graduate Research Examinations (Board of Graduate Research)</relationshipLabel>
    <relationshipName>Board_of_Graduate_Research_Thesis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Graduate_Research_Examination__c/fields/I_RS_DGR_User__c.field-meta.xml
<CustomField>
    <fullName>I_RS_DGR_User__c</fullName>
    <description>Contains Related user Id of Contact &quot;I_RS_Director_of_Graduate_Research__c&quot;</description>
    <formula>I_RS_Director_of_Graduate_Research__r.I_RS_Related_User__c</formula>
    <label>DGR User</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Graduate_Research_Examination__c/fields/I_RS_Director_of_Graduate_Research__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Director_of_Graduate_Research__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Director of Graduate Research for the candidate&apos;s school, unless they have a conflict, in which case will be an alternative, usually the Head of School</inlineHelpText>
    <label>Director of Graduate Research</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Graduate Research Examinations (Director of Graduate Research)</relationshipLabel>
    <relationshipName>Director_of_Graduate_Research_Thesis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Graduate_Research_Examination__c/fields/I_RS_Principal_Supervisor__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Principal_Supervisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Principal Supervisor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Graduate Research Examinations (Principal Supervisor)</relationshipLabel>
    <relationshipName>Principal_Supervisor_Thesis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Graduate_Research_Examination__c/fields/I_RS_PS_User__c.field-meta.xml
<CustomField>
    <fullName>I_RS_PS_User__c</fullName>
    <description>Contains Related user Id of Contact &quot;I_RS_Principal_Supervisor__c&quot;</description>
    <formula>I_RS_Principal_Supervisor__r.I_RS_Related_User__c</formula>
    <label>PS User</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Graduate_Research_Examination__c/fields/I_RS_SBGR_User__c.field-meta.xml
<CustomField>
    <fullName>I_RS_SBGR_User__c</fullName>
    <description>Formula field that contains related user Id of &quot;I_RS_Substitute_Board_Graduate_Research__c&quot; Contact</description>
    <formula>I_RS_Substitute_Board_Graduate_Research__r.I_RS_Related_User__c</formula>
    <label>SBGR User</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Graduate_Research_Examination__c/fields/I_RS_SDGR_Approver_User_Id__c.field-meta.xml
<CustomField>
    <fullName>I_RS_SDGR_Approver_User_Id__c</fullName>
    <formula>I_RS_SDGR_Approver__r.I_RS_Related_User__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SDGR Approver User Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Graduate_Research_Examination__c/fields/I_RS_SDGR_User__c.field-meta.xml
<CustomField>
    <fullName>I_RS_SDGR_User__c</fullName>
    <description>Contains Related user Id of the contact &quot;I_RS_Substitute_DirectorGraduateResearch__c&quot;</description>
    <formula>I_RS_Substitute_DirectorGraduateResearch__r.I_RS_Related_User__c</formula>
    <label>SDGR User</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Graduate_Research_Examination__c/fields/I_RS_Student__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Graduate Research Examinations</relationshipLabel>
    <relationshipName>Graduate_Research_Examinations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Graduate_Research_Examination__c/fields/I_RS_Student_User__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Student_User__c</fullName>
    <description>Contains related User Id of &quot;Student&quot;</description>
    <formula>I_RS_Student__r.I_RS_Related_User__c</formula>
    <label>Student User</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Graduate_Research_Examination__c/fields/I_RS_Substitute_Board_Graduate_Research__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Substitute_Board_Graduate_Research__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Deputy Chair or other member of the Board of Graduate Research with delegated responsibility for approvals on behalf of the BGR</inlineHelpText>
    <label>Alternate Board of Graduate Research</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Graduate Research Examinations (Substitute Board of Graduate Research)</relationshipLabel>
    <relationshipName>Substitute_Board_Thesis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Graduate_Research_Examination__c/fields/I_RS_Substitute_DirectorGraduateResearch__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Substitute_DirectorGraduateResearch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Nominated delegate who can approve on behalf of the School Director of Graduate Research if they are unavailable, usually the Head of School</inlineHelpText>
    <label>Alternate Director of Graduate Research</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Graduate Research Examinations (Substitute Director of Graduate Research)</relationshipLabel>
    <relationshipName>Substitute_Director_Thesis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/adhocThesisSharingCalcBatch.cls
public without sharing class adhocThesisSharingCalcBatch implements Database.batchable<SObject> {

    public String queryStr;
    public set<Id> contactSet;
    public Set<Id> thesisIds;

    public adhocThesisSharingCalcBatch(set<Schema.sObjectType> objectTypes, List<Id> recIds, List<Id> contactIds){
        queryStr = '';
        thesisIds = new Set<Id>();
        
        //populate contacts in set
        contactSet = new set<Id>();
        for (Id ctId: contactIds) {
            contactSet.add(ctId);
        }
        
        //get all ProjectProposal IDs
        for (Id thId: recIds) {
            if (thId.getSObjectType() == Graduate_Research_Examination__c.SobjectType) {
                thesisIds.add(thId);    
            }
        }
        
        if ((thesisIds.size() > 0) || (objectTypes.contains(Graduate_Research_Examination__c.SobjectType))) {
            queryStr = 'SELECT Id, I_RS_Student__c, I_RS_Student_User__c, I_RS_Principal_Supervisor__c, I_RS_PS_User__c, '+
                       'I_RS_Alternate_Supervisor__c, I_RS_AS_User__c, I_RS_Director_of_Graduate_Research__c, '+
                       'I_RS_DGR_User__c, I_RS_Substitute_DirectorGraduateResearch__c, I_RS_SDGR_User__c, '+
                	   'I_RS_Board_of_Graduate_Research__c, I_RS_BGR_User__c, I_RS_Substitute_Board_Graduate_Research__c, '+
                		'I_RS_SDGR_Approver_User_Id__c, '+
                       'I_RS_SBGR_User__c FROM Graduate_Research_Examination__c';
            if (thesisIds.size() > 0) {
                queryStr = queryStr + ' WHERE Id IN :thesisIds';
            }
        }
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        System.debug('Query String: ' + queryStr);
        //if empty query string, query user record as a dummy operation
        if (queryStr == '') {
            Id uId = UserInfo.getUserId();
            queryStr = 'SELECT Id, Name FROM User WHERE Id = :uId';
        }
        return Database.getQueryLocator(queryStr);
    }
    
    public void execute(Database.BatchableContext BC, List<sObject> scope){
    	Map<Id, Graduate_Research_Examination__c> oldList = new Map<Id, Graduate_Research_Examination__c>();
    	Map<Id, Graduate_Research_Examination__c> newList = new Map<Id, Graduate_Research_Examination__c>();
        Graduate_Research_Examination__c oldRec;
        for (SObject objRec: scope) {
            if (objRec instanceof Graduate_Research_Examination__c){
                Graduate_Research_Examination__c greRec = (Graduate_Research_Examination__c) objRec;
                oldRec = new Graduate_Research_Examination__c(Id = greRec.Id) ;
                if (contactSet.size() == 0) {
                    oldList.put(greRec.Id, oldRec);
                    newList.put(greRec.Id, greRec);
                } else if ((contactSet.Contains(greRec.I_RS_Student__c)) || 
                           (contactSet.Contains(greRec.I_RS_Principal_Supervisor__c)) || 
                           (contactSet.Contains(greRec.I_RS_Alternate_Supervisor__c)) || 
                           (contactSet.Contains(greRec.I_RS_Director_of_Graduate_Research__c)) || 
                           (contactSet.Contains(greRec.I_RS_Substitute_DirectorGraduateResearch__c)) || 
                           (contactSet.Contains(greRec.I_RS_Board_of_Graduate_Research__c)) || 
                           (contactSet.Contains(greRec.I_RS_Substitute_Board_Graduate_Research__c))){
                               
                               if (!contactSet.Contains(greRec.I_RS_Student__c)) {
                                    oldRec.I_RS_Student__c = greRec.I_RS_Student__c;  
                               }
                               if (!contactSet.Contains(greRec.I_RS_Principal_Supervisor__c)) {
                                    oldRec.I_RS_Principal_Supervisor__c = greRec.I_RS_Principal_Supervisor__c;  
                               }
                               if (!contactSet.Contains(greRec.I_RS_Alternate_Supervisor__c)) {
                                    oldRec.I_RS_Alternate_Supervisor__c = greRec.I_RS_Alternate_Supervisor__c;  
                               }
                               if (!contactSet.Contains(greRec.I_RS_Director_of_Graduate_Research__c)) {
                                    oldRec.I_RS_Director_of_Graduate_Research__c = greRec.I_RS_Director_of_Graduate_Research__c;  
                               }
                               if (!contactSet.Contains(greRec.I_RS_Substitute_DirectorGraduateResearch__c)) {
                                    oldRec.I_RS_Board_of_Graduate_Research__c = greRec.I_RS_Board_of_Graduate_Research__c;  
                               }
                               if (!contactSet.Contains(greRec.I_RS_Board_of_Graduate_Research__c)) {
                                    oldRec.I_RS_Substitute_DirectorGraduateResearch__c = greRec.I_RS_Substitute_DirectorGraduateResearch__c;  
                               }
                               if (!contactSet.Contains(greRec.I_RS_Substitute_Board_Graduate_Research__c)){
                                    oldRec.I_RS_Substitute_Board_Graduate_Research__c = greRec.I_RS_Substitute_Board_Graduate_Research__c;  
                               }
                    oldList.put(greRec.Id, oldRec);
                    newList.put(greRec.Id, greRec);
                }            
        	}
        }
        if (newList.size() > 0) {
            GraduateResearchExaminationHelper.calculateAccessForAffectedThesis(newList, oldList);
        }
    }
    
    public void finish(Database.BatchableContext BC){
    }
}