force-app/main/default/objects/CourseAvailability__c/CourseAvailability__c.object-meta.xml
<CustomObject>
    <label>Course Availability</label>
    <nameField>
        <displayFormat>AID-CA-{0000}</displayFormat>
        <label>Course Availability ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Availabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CourseAvailability__c/fields/L_AD_CourseInstance__c.field-meta.xml
<CustomField>
    <fullName>L_AD_CourseInstance__c</fullName>
    <label>Course Instance</label>
    <referenceTo>CourseInstance__c</referenceTo>
    <relationshipLabel>Course Availability</relationshipLabel>
    <relationshipName>Course_Availability</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CourseInstance__c/CourseInstance__c.object-meta.xml
<CustomObject>
    <description>Location specific details of a course</description>
    <label>Course Instance</label>
    <nameField>
        <displayFormat>AID-CI-{0000}</displayFormat>
        <label>Course Instance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Instance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/I_RM_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Part of the remediation project to store different personas</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/I_RM_Affiliation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Affiliation Settings</label>
</CustomObject>

force-app/main/default/objects/I_ST_Student_Course__c/I_ST_Student_Course__c.object-meta.xml
<CustomObject>
    <description>Junction object between Student (Contact) and Course (Course Availability)</description>
    <label>Student Course</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>Student Course Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_ST_Student_Course__c/fields/I_RM_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Affiliation</description>
    <label>Affiliation</label>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>Student Courses</relationshipLabel>
    <relationshipName>Student_Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/I_ST_Student_Course__c/fields/I_ST_Course_Admission_Stage_Code__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Course_Admission_Stage_Code__c</fullName>
    <description>IST-168</description>
    <label>Course Admission Stage Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_ST_Student_Course__c/fields/I_ST_Course_Admission_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Course_Admission_Status_Code__c</fullName>
    <description>for IST-168</description>
    <label>Course Admission Status Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_ST_Student_Course__c/fields/I_ST_CourseAvailability__c.field-meta.xml
<CustomField>
    <fullName>I_ST_CourseAvailability__c</fullName>
    <description>Course availability linkage as per IST-43,IST-168</description>
    <label>Course Availability</label>
    <referenceTo>CourseAvailability__c</referenceTo>
    <relationshipLabel>Student Courses</relationshipLabel>
    <relationshipName>Student_Courses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/I_ST_Student_Course__c/fields/I_ST_Student__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Student__c</fullName>
    <description>Student lookup as per IST-43,IST-168</description>
    <label>Student</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Courses</relationshipLabel>
    <relationshipName>Student_Courses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/I_ST_Student_CourseTriggerHandler.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* I_ST_Student_Course__c Trigger Handler
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Rahul Kumar
* @version        1.0
* @created        2021-03-23
* Description     LTU360-1314 Create alumini affiliation based on student course enrolment "Stage and Status"
* ─────────────────────────────────────────────────────────────────────────────────────────────────
*/
public with sharing class I_ST_Student_CourseTriggerHandler {
    public static Boolean hasFired = false;
     public static List<String> earlyEntryCourses = [SELECT Value__c FROM I_RM_Affiliation_Settings__c WHERE Name =:GlobalConstants.I_RM_Early_Entry_Courses].Value__c.split(',');    
   
  
    public static void execute() {
        List<I_ST_Student_Course__c> studentcourse = new List<I_ST_Student_Course__c>();
         map<Id,I_ST_Student_Course__c> mapOldCourses = (map<Id,I_ST_Student_Course__c>)Trigger.oldMap;
        if (Trigger.isAfter) {
           List<I_ST_Student_Course__c> stdCourse = [SELECT Id,I_ST_CourseAvailability__c,I_ST_Student__c,I_RM_Affiliation__c,I_ST_Course_Admission_Stage_Code__c,I_ST_Course_Admission_Status_Code__c,I_ST_CourseAvailability__r.L_AD_CourseInstance__r.L_AD_CourseParent__r.L_AD_Course_Type_Name__c 
                                                     FROM I_ST_Student_Course__c 
                                                     WHERE id IN: (List<I_ST_Student_Course__c>)trigger.New 
                                                     AND I_ST_CourseAvailability__r.L_AD_CourseInstance__r.L_AD_CourseParent__r.L_AD_Course_Type_Name__c NOT IN :earlyEntryCourses];
           
            if(Trigger.isInsert || Trigger.isUpdate){
                if(!hasFired){                	
                    for(I_ST_Student_Course__c st :stdCourse){ 
                    	if(st.I_ST_Student__c != NULL && st.I_RM_Affiliation__c != Null
                           && (Trigger.isInsert  ||  (Trigger.isUpdate 
                            && (st.I_ST_Course_Admission_Stage_Code__c != mapOldCourses.get(st.Id).I_ST_Course_Admission_Stage_Code__c 
                               || st.I_ST_Course_Admission_Status_Code__c != mapOldCourses.get(st.Id).I_ST_Course_Admission_Status_Code__c)))
                           && st.I_ST_Course_Admission_Stage_Code__c == 'COMP' && st.I_ST_Course_Admission_Status_Code__c== 'PASS'){
                        	studentcourse.add(st);
                    	}
                	}	
                    
                 	if(studentcourse.size() > 0){
              	   		I_ST_Student_CourseTriggerHelper.createAlumni(studentcourse);  
                 	}
                }
            }           
        }
    }
}