force-app/main/default/objects/Classification_Code__c/Classification_Code__c.object-meta.xml
<CustomObject>
    <description>Describes the relationship between a Classification Master and various objects</description>
    <label>Classification Code</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Title</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classification Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification_Code__c/fields/I_RS_Inactive_for_Non_Admins__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Inactive_for_Non_Admins__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, this record is hidden from end-user-facing UIs, but preserved in database for data tracking.</description>
    <inlineHelpText>When checked, this record is hidden from end-user-facing UIs, but preserved in database for data tracking.</inlineHelpText>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Classification_Master__c/Classification_Master__c.object-meta.xml
<CustomObject>
    <label>Classification Master</label>
    <nameField>
        <label>Classification Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classification Masters</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Proposal__c/Project_Proposal__c.object-meta.xml
<CustomObject>
    <description>Project Proposal: An application for funding either through a grant request, a tender response, or a contract proposal.
Project: The work that is undertaken to satisfy a commitment made to a funding body or client.  The commitment is likely to be a contract (and possible variations) resulting from the acceptance of a project proposal.  This occurs after a grant, contract of philanthropic donation has been awarded.</description>
    <label>Project Proposal</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Proposal__c/fields/I_RS_Theme__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Theme__c</fullName>
    <description>https://eawebdev.atlassian.net/browse/T2-876</description>
    <inlineHelpText>Select which theme(s) this project aligns to.</inlineHelpText>
    <label>Theme Alignment</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No theme alignment</fullName>
                <default>true</default>
                <label>No theme alignment</label>
            </value>
            <value>
                <fullName>A healthy, safe and equitable life course for everyone</fullName>
            </value>
            <value>
                <fullName>The production of quality foods &amp; medicines</fullName>
            </value>
            <value>
                <fullName>The protection &amp; restoration of vulnerable ecosystems</fullName>
            </value>
            <value>
                <fullName>Understanding &amp; preventing disease</fullName>
            </value>
            <value>
                <fullName>More just and equitable societies</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ResearchCodeGridSummaryTest.cls
@isTest
public with sharing class ResearchCodeGridSummaryTest {
    
    public static testmethod void positiveCase_AllData() {

        Project_Proposal__c projectProposal = TestUtility.newProjectProposal();
        projectProposal.I_RS_Theme__c = 'No theme alignment ';
        insert projectProposal;

        List<Classification_Master__c> cms = new List<Classification_Master__c>{
            TestUtility.newClassificationMaster('CM1', 'CM1', GlobalConstants.CLASSIFICATION_MASTER_TYPE_FOR, true),
            TestUtility.newClassificationMaster('CM2', 'CM2', GlobalConstants.CLASSIFICATION_MASTER_TYPE_FOR_2008, true),
            TestUtility.newClassificationMaster('CM3', 'CM3', GlobalConstants.CLASSIFICATION_MASTER_TYPE_SEO, true),
            TestUtility.newClassificationMaster('CM4', 'CM4', GlobalConstants.CLASSIFICATION_MASTER_TYPE_SEO_2008, true),
            TestUtility.newClassificationMaster('CM5', 'CM5', GlobalConstants.CLASSIFICATION_MASTER_TYPE_TOA, true)
        };
        insert cms;
        
        List<Classification_Code__c> ccs = new List<Classification_Code__c>();
        for (Classification_Master__c cm : cms){
            ccs.add(TestUtility.newClassificationCode(cm.Id, null, projectProposal.Id, null));
            ccs.add(TestUtility.newClassificationCode(cm.Id, null, projectProposal.Id, null));
            
            Classification_Code__c softDeletedCode = TestUtility.newClassificationCode(cm.Id, null, projectProposal.Id, null);
            softDeletedCode.I_RS_Inactive_for_non_admins__c = true;
            ccs.add(softDeletedCode);
        }
		insert ccs;
        
        List<ResearchCodeGridSummaryController.ERACodeGrouping> groupings = 
            ResearchCodeGridSummaryController.getSummaryData(projectProposal.Id, 'Classification_Codes_Project_Proposal');
        
        System.assertequals(5, groupings.size());
        
        for (ResearchCodeGridSummaryController.ERACodeGrouping grouping : groupings){
            System.assertequals(2, grouping.activeCodeCount);
        }
    }
    
    
 public static testmethod void positiveCase_NoData() {

        Project_Proposal__c projectProposal = TestUtility.newProjectProposal();
        projectProposal.I_RS_Theme__c = 'No theme alignment ';
        insert projectProposal;

        List<ResearchCodeGridSummaryController.ERACodeGrouping> groupings = 
            ResearchCodeGridSummaryController.getSummaryData(projectProposal.Id, 'Classification_Codes_Project_Proposal');
        
        System.assertequals(3, groupings.size());
        
        for (ResearchCodeGridSummaryController.ERACodeGrouping grouping : groupings){
            System.assertequals(0, grouping.activeCodeCount);
        }
    }
}