force-app/main/default/objects/Research_Opportunity__c/Research_Opportunity__c.object-meta.xml
<CustomObject>
    <label>Funding Opportunity</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Research_Opportunity__c/fields/I_RS_Funding_Category__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Funding_Category__c</fullName>
    <label>HERDC Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cat 1</fullName>
            </value>
            <value>
                <fullName>Cat 2</fullName>
            </value>
            <value>
                <fullName>Cat 3</fullName>
            </value>
            <value>
                <fullName>Cat 4</fullName>
            </value>
            <value>
                <fullName>Non-HERDC consulting</fullName>
                <label>Non-HERDC Consulting</label>
            </value>
            <value>
                <fullName>Non-HERDC Research</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Research_Opportunity__c/fields/I_RS_Minimum_Available_Budget__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Minimum_Available_Budget__c</fullName>
    <label>Minimum Available Budget</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Research_Opportunity__c/fields/I_RS_Student_led__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Student_led__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This funding opportunity is for a Student to lead</inlineHelpText>
    <label>Student led</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Research_Opportunity__c/fields/I_RS_Submission_Date__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Submission_Date__c</fullName>
    <inlineHelpText>The Funder&apos;s due date for the proposal</inlineHelpText>
    <label>Submission Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Research_Opportunity__c/fields/I_RS_Type_of_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Type_of_Opportunity__c</fullName>
    <label>Proposal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_Of_Opportunity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Research_Opportunity__c/recordTypes/I_RS_Funding_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>I_RS_Funding_Opportunity</fullName>
    <active>true</active>
    <label>Funding Opportunity</label>
</RecordType>

force-app/main/default/objects/URL_Variable__c/URL_Variable__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>URL Variable</label>
</CustomObject>

force-app/main/default/objects/URL_Variable__c/fields/I_RS_Researcher_Portal_Base_URL__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Researcher_Portal_Base_URL__c</fullName>
    <description>Base URL of the PRIME Researcher Portal. Used for hyperlinking.</description>
    <label>Researcher Portal Base URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/globalValueSets/Type_Of_Opportunity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Grant</fullName>
    </customValue>
    <customValue>
        <fullName>Quote/Proposal</fullName>
    </customValue>
    <customValue>
        <fullName>Tender/RFQ</fullName>
    </customValue>
    <customValue>
        <fullName>Research Collaboration</fullName>
        <isActive>false</isActive>
        <label>Research Collaboration</label>
    </customValue>
    <customValue>
        <fullName>Request for Proposal</fullName>
        <isActive>false</isActive>
        <label>Request for Proposal</label>
    </customValue>
    <customValue>
        <fullName>Scholarship</fullName>
        <isActive>false</isActive>
        <label>Scholarship</label>
    </customValue>
    <customValue>
        <fullName>Expression of interest</fullName>
        <isActive>false</isActive>
        <label>Expression of interest</label>
    </customValue>
    <customValue>
        <fullName>Request for quote</fullName>
        <isActive>false</isActive>
        <label>Request for quote</label>
    </customValue>
    <customValue>
        <fullName>Non-research Consultancy</fullName>
        <isActive>false</isActive>
        <label>Non-research Consultancy</label>
    </customValue>
    <customValue>
        <fullName>Postgraduate</fullName>
        <isActive>false</isActive>
        <label>Postgraduate</label>
    </customValue>
    <customValue>
        <fullName>Tender/Expression of Interest</fullName>
        <isActive>false</isActive>
        <label>Tender/Expression of Interest</label>
    </customValue>
    <customValue>
        <fullName>Research Consultancy</fullName>
        <isActive>false</isActive>
        <label>Research Consultancy</label>
    </customValue>
    <customValue>
        <fullName>Fellowship</fullName>
        <isActive>false</isActive>
        <label>Fellowship</label>
    </customValue>
    <customValue>
        <fullName>Consultancy Contract</fullName>
        <isActive>false</isActive>
        <label>Consultancy Contract</label>
    </customValue>
    <customValue>
        <fullName>Research Contract/collaboration</fullName>
        <isActive>false</isActive>
        <label>Research Contract/collaboration</label>
    </customValue>
    <masterLabel>Type Of Opportunity</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CustomSearchControllerTest2.cls
@isTest
public class CustomSearchControllerTest2 {

    static String searchConfigName = 'Funding_Opportunity_Researchers';

    static String keywordsToSearch = 'Test Research Opportunity';
    static String keywordsToExclude = 'Invalid';

    static Integer numberOfOppsToInsert = 3000;

    static List<Map<String, Object>> filters = new List<Map<String, Object>>{
        new Map<String, Object>{
            'filterType' => 'picklist',
            'field' => 'I_RS_Type_of_Opportunity__c',
            'operator' => '=',
            'value' => 'Grant'
        },
        new Map<String, Object>{
            'filterType' => 'picklist',
            'field' => 'I_RS_Funding_Category__c',
            'operator' => '=',
            'value' => 'Cat 1'
        },
        new Map<String, Object>{
            'filterType' => 'date',
            'field' => 'I_RS_Submission_Date__c',
            'operator' => '>=',
            'value' => '2000-01-01'
        }    };
    static String filterLogic = '1 AND 2 AND 3';


    public static testmethod void customSearchTest(){


        insert new URL_Variable__c(
            I_RS_Researcher_Portal_Base_URL__c = 'https://latrobe.prime.edu.au/s'
        );

        List<Research_Opportunity__c> researchOpps = [select Id from Research_Opportunity__c LIMIT 2000];
        Test.setFixedSearchResults(new List<Id>(new Map<Id, Research_Opportunity__c>(researchOpps).keySet()));

        Test.startTest();

            Integer setupCPUTime = Limits.getCPUTime();

            ResearchOpportunitySearchController2.Wrapper wrapper = 
                ResearchOpportunitySearchController2.getSearchResults(
                searchConfigName,
                keywordsToSearch,
                null,
                filters,
                filterLogic,
                'Name',
                'asc',
                10,
                0
            );

            Integer searchCPUTime = Limits.getCPUTime() - setupCPUTime;
            if (searchCPUTime > 3000)
            System.assert(false, 'Search is taking too long ('+Limits.getCPUTime()+' seconds');
        
            System.assertequals(2000, wrapper.totalRowCount);
            System.assertequals(10, wrapper.records.size());

        Test.stopTest();
        
    }



    public static testmethod void testColumnMetadataLogic(){

        System.assert(PicklistController.getPickListValues(
                        'Research_Opportunity__c', 'I_RS_Type_Of_Opportunity__c') != null);
    
        System.assert(ResearchOpportunitySearchController2.getColumns_DatatableMetadata(searchConfigName).size() > 0);

    }


    public static testmethod void saveAndLoadSavedSearch(){

       System.debug('---CustomSearchControllerTest2.saveAndLoadSavedSearch---'); 
        
		/*Map<String, Object> initialSearchLoadBeforeAnySaveHasOccurred = 
            ResearchOpportunitySearchController2.getUserSavedSearch();
        System.assertequals(null, initialSearchLoadBeforeAnySaveHasOccurred);*/
        //Would need to run as brand new user so we can guarantee there is no saved search
        
       Map<String, Object> saveSearchData = new Map<String, Object>{
            'keywordsToSearch' => keywordsToSearch,
            'keywordsToExclude' => keywordsToExclude,
            'filters' => filters,
            'useFilterLogic' => true,
            'filterLogic' => filterLogic
        };
            
       	ResearchOpportunitySearchController2.saveUserSearch(saveSearchData);
        
       	Map<String, Object> loadedSavedSearchData = 
           ResearchOpportunitySearchController2.getUserSavedSearch();
        
        System.debug('loadedSavedSearchData '+loadedSavedSearchData);
        
        System.assert(loadedSavedSearchData != null);
        
        System.debug('---CustomSearchControllerTest2.saveAndLoadSavedSearch END---'); 
    }


    @TestSetup
    static void makeData(){
        
        List<Research_Opportunity__c> opps = new List<Research_Opportunity__c>();
        
        Id recordTypeId = Schema.SObjectType.Research_Opportunity__c.getRecordTypeInfosByDeveloperName().get('I_RS_Funding_Opportunity').getRecordTypeId();
        System.assert(recordTypeId != null);

        for (Integer i=0; i<numberOfOppsToInsert; i++){ 
            Research_Opportunity__c opp = TestUtility.newResearchOpportunity(false);
            opp.recordTypeId = recordTypeId;
            opp.I_RS_Type_of_Opportunity__c = 'Grant';
            opp.I_RS_Funding_Category__c = 'Cat 1';
            opp.I_RS_Submission_Date__c = Date.today() + 365;
            opp.I_RS_Minimum_Available_Budget__c = 500;
            opp.I_RS_Student_Led__c = true;

            opps.add(opp);
        }
        insert opps;

    }

    
}