force-app/main/default/objects/Account/recordTypes/I_ST_Lead_Account.recordType-meta.xml
<RecordType>
    <fullName>I_ST_Lead_Account</fullName>
    <active>true</active>
    <description>An administrative account for Leads that are not associated with an Account.</description>
    <label>Lead Account</label>
</RecordType>

force-app/main/default/objects/Case/fields/I_RM_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Affiliation</description>
    <label>Affiliation</label>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/I_ST_Enquiry.recordType-meta.xml
<RecordType>
    <fullName>I_ST_Enquiry</fullName>
    <active>true</active>
    <businessProcess>IST ENQUIRY</businessProcess>
    <description>Inbound Case for SACE Team received via Phone/Email/Chat etc.</description>
    <label>Enquiry</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/IST.recordType-meta.xml
<RecordType>
    <fullName>IST</fullName>
    <active>true</active>
    <businessProcess>PRIME</businessProcess>
    <description>Record type for IST Support</description>
    <label>IST</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/I_RM_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Part of the remediation project to store different personas</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Campus_Interest__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Campus_Interest__c</fullName>
    <description>Added for IST 43</description>
    <inlineHelpText>Gives Campus preference for the contact</inlineHelpText>
    <label>Campus Interest</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>I_ST_Campus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Career_Area__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Career_Area__c</fullName>
    <description>Student Lead (Dom) Affiliation&apos;s Career Interest</description>
    <inlineHelpText>If the exact area is not listed, please select the closest value.</inlineHelpText>
    <label>Career Area</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>I_RM_Study_Interest__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>I_ST_Career_Interest</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Contact__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Contact__c</fullName>
    <description>The person/contact who this Affiliation relates to</description>
    <inlineHelpText>The person this affiliation relates to</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Affiliations</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Email__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Email__c</fullName>
    <description>Depicts Personal Email</description>
    <inlineHelpText>The personal email for this person.</inlineHelpText>
    <label>Personal Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Enquirer_Type__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Enquirer_Type__c</fullName>
    <description>Depicts how best to describe the Enquirer, Applicable for Student Lead (Dom),Student Applicant (Dom) and Secondary School Rep</description>
    <inlineHelpText>This is the Enquirer Type</inlineHelpText>
    <label>What best describes you?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>I_ST_Enquirer_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Lead_Source_Category__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Lead_Source_Category__c</fullName>
    <description>Depicts the source of the Affiliation</description>
    <label>Source Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>I_ST_Lead_Source_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Mobile_Phone__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Mobile_Phone__c</fullName>
    <description>Depicts affiliation&apos;s Mobile Phone number</description>
    <label>Mobile Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Role__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Role__c</fullName>
    <description>This represents the role of the affiliation</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Domestic Lead</fullName>
                <label>Student Lead (Dom)</label>
            </value>
            <value>
                <fullName>Applicant</fullName>
                <label>Student Applicant (Dom)</label>
            </value>
            <value>
                <fullName>La Trobe Staff</fullName>
            </value>
            <value>
                <fullName>School Representative</fullName>
                <label>Secondary School Representative</label>
            </value>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>External Contact</fullName>
            </value>
            <value>
                <fullName>HDR Student</fullName>
                <label>Graduate Researcher</label>
            </value>
            <value>
                <fullName>Student Lead (Int)</fullName>
            </value>
            <value>
                <fullName>Nominated Affiliation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <description>Indicates the status of the Affiliation.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>I_RM_Role__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>I_ST_Contact_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Study_Interest__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Study_Interest__c</fullName>
    <description>Student Lead (Dom) Affiliation&apos;s Study Interest</description>
    <label>Study Interest</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>I_ST_Study_Interest</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_IL_Student_Lead_Int.recordType-meta.xml
<RecordType>
    <fullName>I_IL_Student_Lead_Int</fullName>
    <active>true</active>
    <description>New International Lead who can be a prospective student of La Trobe University</description>
    <label>Student Lead (Int)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_Applicant.recordType-meta.xml
<RecordType>
    <fullName>I_RM_Applicant</fullName>
    <active>true</active>
    <description>An individual who has applied to study at La Trobe University</description>
    <label>Student Applicant (Dom)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_Lead.recordType-meta.xml
<RecordType>
    <fullName>I_RM_Lead</fullName>
    <active>true</active>
    <description>New Domestic Lead who is a prospective student of La Trobe University</description>
    <label>Student Lead (Dom)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/I_RM_Affiliation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Affiliation Settings</label>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/I_ST_Career_Interest.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Arts</fullName>
    </customValue>
    <customValue>
        <fullName>Creative Arts And English</fullName>
    </customValue>
    <customValue>
        <fullName>Historical And Cultural Studies</fullName>
    </customValue>
    <customValue>
        <fullName>International Relations And Development</fullName>
    </customValue>
    <customValue>
        <fullName>Languages And Linguistics</fullName>
    </customValue>
    <customValue>
        <fullName>Media, Communication And Journalism</fullName>
    </customValue>
    <customValue>
        <fullName>Planning, Environment And Sustainability</fullName>
    </customValue>
    <customValue>
        <fullName>Politics, Philosophy And Economics</fullName>
    </customValue>
    <customValue>
        <fullName>Social Sciences</fullName>
    </customValue>
    <customValue>
        <fullName>Accounting And Finance</fullName>
    </customValue>
    <customValue>
        <fullName>Business And Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Economics</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing And Management</fullName>
    </customValue>
    <customValue>
        <fullName>Technology Management</fullName>
    </customValue>
    <customValue>
        <fullName>Big Data</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering</fullName>
    </customValue>
    <customValue>
        <fullName>Information Technology</fullName>
    </customValue>
    <customValue>
        <fullName>Computer Science</fullName>
    </customValue>
    <customValue>
        <fullName>Teaching</fullName>
    </customValue>
    <customValue>
        <fullName>Outdoor And Environmental Education</fullName>
    </customValue>
    <customValue>
        <fullName>Career Development</fullName>
    </customValue>
    <customValue>
        <fullName>Linguistics And TESOL</fullName>
    </customValue>
    <customValue>
        <fullName>Allied Health And Rehabilitation</fullName>
    </customValue>
    <customValue>
        <fullName>Psychology, counselling and social work</fullName>
    </customValue>
    <customValue>
        <fullName>Dentistry and Oral Health</fullName>
        <label>Dentistry And Oral Health</label>
    </customValue>
    <customValue>
        <fullName>Health Management</fullName>
    </customValue>
    <customValue>
        <fullName>Ageing And End Of Life Care</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Sciences</fullName>
    </customValue>
    <customValue>
        <fullName>Nursing, Midwifery And Paramedicine</fullName>
    </customValue>
    <customValue>
        <fullName>Public Health</fullName>
    </customValue>
    <customValue>
        <fullName>Disability</fullName>
    </customValue>
    <description>Created fro IST- 43</description>
    <masterLabel>I_ST_Career_Interest</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/I_ST_Contact_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Admitted</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And LOA</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Not Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Considered</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Made</fullName>
    </customValue>
    <customValue>
        <fullName>Await Academic Advice</fullName>
    </customValue>
    <customValue>
        <fullName>Await Applicant Comms</fullName>
    </customValue>
    <customValue>
        <fullName>Await Further Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Awaiting Interview</fullName>
    </customValue>
    <customValue>
        <fullName>Await Required Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Escalated</fullName>
    </customValue>
    <customValue>
        <fullName>Make A Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make Alternate Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make An Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Nearing Completion</fullName>
    </customValue>
    <customValue>
        <fullName>Not Processed</fullName>
    </customValue>
    <customValue>
        <fullName>Not Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Lapsed</fullName>
    </customValue>
    <customValue>
        <fullName>Other Preference Offered</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Results</fullName>
    </customValue>
    <customValue>
        <fullName>Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <description>Global value set is created for lead(contact) object ST -51</description>
    <masterLabel>I_ST_Contact_Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/I_ST_Enquirer_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Year 9</fullName>
    </customValue>
    <customValue>
        <fullName>Year 10</fullName>
    </customValue>
    <customValue>
        <fullName>Year 11</fullName>
    </customValue>
    <customValue>
        <fullName>Year 12</fullName>
    </customValue>
    <customValue>
        <fullName>Recent school leaver (18-20)</fullName>
    </customValue>
    <customValue>
        <fullName>Mature age (21+)</fullName>
    </customValue>
    <customValue>
        <fullName>Industry qualified or experienced</fullName>
    </customValue>
    <customValue>
        <fullName>Direct applicant</fullName>
    </customValue>
    <customValue>
        <fullName>University graduate (other uni)</fullName>
    </customValue>
    <customValue>
        <fullName>University graduate (LTU)</fullName>
    </customValue>
    <customValue>
        <fullName>International (outside Australia)</fullName>
    </customValue>
    <customValue>
        <fullName>International (inside Australia)</fullName>
    </customValue>
    <customValue>
        <fullName>TAFE graduate</fullName>
    </customValue>
    <customValue>
        <fullName>Current students (LTU) - UG</fullName>
    </customValue>
    <customValue>
        <fullName>Current students (LTU) - PG</fullName>
    </customValue>
    <customValue>
        <fullName>Current students (other uni) - UG</fullName>
    </customValue>
    <customValue>
        <fullName>Current students (other uni) - PG</fullName>
    </customValue>
    <customValue>
        <fullName>Current student (other) - TAFE</fullName>
    </customValue>
    <customValue>
        <fullName>Current student (LTU) - Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Parent</fullName>
    </customValue>
    <customValue>
        <fullName>Careers advisor / Careers counsellor</fullName>
    </customValue>
    <customValue>
        <fullName>Teacher</fullName>
    </customValue>
    <customValue>
        <fullName>Principal</fullName>
    </customValue>
    <customValue>
        <fullName>International agent</fullName>
    </customValue>
    <customValue>
        <fullName>Business Owner / Contact</fullName>
    </customValue>
    <customValue>
        <fullName>Industry partner</fullName>
    </customValue>
    <customValue>
        <fullName>Industry association</fullName>
    </customValue>
    <customValue>
        <fullName>Accrediting Body</fullName>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <customValue>
        <fullName>Staff</fullName>
    </customValue>
    <description>Created for IST-43</description>
    <masterLabel>I_ST_Enquirer_Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/I_ST_Lead_Source_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Consultation</fullName>
    </customValue>
    <customValue>
        <fullName>Email</fullName>
    </customValue>
    <customValue>
        <fullName>Event</fullName>
    </customValue>
    <customValue>
        <fullName>Live Chat</fullName>
    </customValue>
    <customValue>
        <fullName>Loaded from list</fullName>
    </customValue>
    <customValue>
        <fullName>Other system</fullName>
    </customValue>
    <customValue>
        <fullName>Phone Call</fullName>
    </customValue>
    <customValue>
        <fullName>Physical</fullName>
    </customValue>
    <customValue>
        <fullName>Schools/account</fullName>
    </customValue>
    <customValue>
        <fullName>Social Media</fullName>
    </customValue>
    <customValue>
        <fullName>VTAC preference list</fullName>
    </customValue>
    <customValue>
        <fullName>Web Form</fullName>
    </customValue>
    <customValue>
        <fullName>Webinar</fullName>
    </customValue>
    <customValue>
        <fullName>Migrated</fullName>
    </customValue>
    <customValue>
        <fullName>Subscription Sites</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>QSES</fullName>
    </customValue>
    <customValue>
        <fullName>Student Ambassador</fullName>
    </customValue>
    <description>Created for IST-45</description>
    <masterLabel>I_ST_Lead_Source_Category</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/I_ST_Study_Interest.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Any</fullName>
    </customValue>
    <customValue>
        <fullName>Arts, Social Sciences and Communications</fullName>
    </customValue>
    <customValue>
        <fullName>Business and Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Education and teaching</fullName>
    </customValue>
    <customValue>
        <fullName>Health</fullName>
    </customValue>
    <customValue>
        <fullName>IT and engineering</fullName>
    </customValue>
    <customValue>
        <fullName>Law and criminology</fullName>
    </customValue>
    <customValue>
        <fullName>Science</fullName>
    </customValue>
    <customValue>
        <fullName>General</fullName>
        <isActive>false</isActive>
        <label>General</label>
    </customValue>
    <customValue>
        <fullName>Aspire</fullName>
        <isActive>false</isActive>
        <label>Aspire</label>
    </customValue>
    <customValue>
        <fullName>Pathways</fullName>
        <isActive>false</isActive>
        <label>Pathways</label>
    </customValue>
    <customValue>
        <fullName>Information technology</fullName>
        <isActive>false</isActive>
        <label>Information technology</label>
    </customValue>
    <customValue>
        <fullName>Engineering</fullName>
        <isActive>false</isActive>
        <label>Engineering</label>
    </customValue>
    <customValue>
        <fullName>Law</fullName>
        <isActive>false</isActive>
        <label>Law</label>
    </customValue>
    <customValue>
        <fullName>Criminology</fullName>
        <isActive>false</isActive>
        <label>Criminology</label>
    </customValue>
    <description>Created for IST-43</description>
    <masterLabel>I_ST_Study_Interest</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/I_ST_FlowMethods_Test.cls
/**
 * @author Jie Tan
 * @date 12/10/2020
 * 
 * @group IST
 * 
 * @description Test class for all invocable methods used by IST flows
 * Modification Log :
 * 24/02/2022 : By Vanita Walia - Modified existing and created new test methods as part of remediation as part of LTU360-868 & LTU360-1212
 */
@IsTest
private class I_ST_FlowMethods_Test {    

    //Vanita : Modified test setup method to create contact without record type and create related affiliations
    @testSetup static void setup() {

        String recTypeIdsForAffScoring = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Applicant').getRecordTypeId();
        recTypeIdsForAffScoring += ',' + Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Lead').getRecordTypeId();
        recTypeIdsForAffScoring += ',' + Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_IL_Student_Lead_Int').getRecordTypeId();
        TestUtility.createBatchScoringCustomSettings(recTypeIdsForAffScoring);
        
        
        I_RM_Affiliation_Settings__c objAffiliationSettings = new I_RM_Affiliation_Settings__c(Name = 'I_RM_Inactive_Status',I_RM_Status__c = 'Inactive');
        insert objAffiliationSettings;
		
        //create test contact records
        List<Contact> lstContacts = I_ST_UnitTestUtilities.createTestContactRecords(10,false);
       	//ContactTriggerHandler.runCTEAlways = true;
       	insert lstContacts;         
		system.debug('contact list' + lstContacts);
        
        // Find Domestic Lead Affiliation record type's Id & create affiliation records
        String affiliationRecordTypeIds = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Lead').getrecordTypeId();
        List<I_RM_Affiliation__c> affRecordsList = new List<I_RM_Affiliation__c>();
        for(Integer i=0;i<lstContacts.size();i++){
            I_RM_Affiliation__c affRecord = I_ST_UnitTestUtilities.createAffiliationRecords(affiliationRecordTypeIds,lstContacts[i].Id)[0];
            affRecord.I_RM_Email__c = 'test'+i+'@test.com.invalid';
            affRecord.I_RM_Mobile_Phone__c ='041111112'+i;
            system.debug('affRecord'+affRecord);
            affRecordsList.add(affRecord);
        }
        insert affRecordsList;
        system.debug('affRecordsList'+affRecordsList);

    }         
    
    /**
     * @description Test method for Apex class I_ST_FlowEncryptText & I_ST_FlowDecryptText
     */
    @IsTest
    static void testEncryptionDecryption() {
        //Test setup
        I_ST_GenericUtils.setupScheduler();

        Test.startTest();
        //Prepare inputs
        String clearText = 'clear text';
        List<String> inputs = new List<String>();
        inputs.add(clearText);

        //Encrypt
        List<String> outputs = I_ST_FlowEncryptText.getEncryptedStrings(inputs);

        //Decrypt
        String cipherText = I_ST_FlowDecryptText.getDecryptedStrings(outputs).get(0);

        //Assert
        System.assertEquals(clearText, cipherText);
        Test.stopTest();
    }

    /**
     * @description Test method for Apex class I_ST_FlowFlattenFields
     */
    @IsTest
    static void testFlattenFields() {
        Test.startTest();
        //Prepare inputs
        I_ST_FlowFlattenFields.ServiceAppointmentFields saf = new I_ST_FlowFlattenFields.ServiceAppointmentFields();
        saf.Description = 'test description';
        List<I_ST_FlowFlattenFields.ServiceAppointmentFields> inputs = new List<I_ST_FlowFlattenFields.ServiceAppointmentFields>();
        inputs.add(saf);

        //Get output
        String output = I_ST_FlowFlattenFields.getStrings(inputs).get(0);

        //Assert
        System.assertEquals(JSON.serialize(saf, true), output);
        Test.stopTest();
    }
    
    /**
     * @description Test method for Apex class I_ST_FlowFindDuplicates
     * @Modified by Vanita : 24/02/2022 as part of LTU360-868 - Modified the logic as per the new Flow find duplicate class
    */
    @IsTest
    static void testFindDuplicate() {
		
        Test.startTest();
        //Create input contact deatils to find duplicate record
        I_ST_FlowFindDuplicates.ContactFields con = new I_ST_FlowFindDuplicates.ContactFields();
        con.FirstName = 'TestFirst1';
        con.LastName ='TestLast1';
        con.Email ='test2@test.com.invalid';
        con.Mobile ='0411111120';
        con.AllOrFirst = False;

        List<I_ST_FlowFindDuplicates.ContactFields> conList = new List<I_ST_FlowFindDuplicates.ContactFields>();
        conList.add(con);        
        system.debug('conList' + conList);
        // Call the FindDuplicate Apex action
        List<Contact> duplicateCons = I_ST_FlowFindDuplicates.FindDuplicateContacts(conList);
        
        //assertion to check if duplicate record found
        if(!duplicateCons.isEmpty()) {
            System.assert(!String.isBlank(duplicateCons[0].Id)); 
        }
        
        // update the con record's AllOrFirst to true to return single record      
        con.AllOrFirst = True;
        conList = new List<I_ST_FlowFindDuplicates.ContactFields>();
        conList.add(con); 
             system.debug('conList' + conList);
        List<Contact> duplicateContacts = I_ST_FlowFindDuplicates.FindDuplicateContacts(conList);
        //assert if it return records
        if(!duplicateContacts.isEmpty()) {
            System.assert(!String.isBlank(duplicateContacts[0].Id)); 
        }
        Test.stopTest();
    }
    
    /**
     * @description Test method for Apex class I_ST_FlowInsertContact
     * @Modified by Vanita : 24/02/2022 as part of LTU360-868 & LTU360-1212 - Update test method and removed reference to flow update contact as that class is obselete
    */
    @IsTest
    static void testContactDuplicateSupport() {
		
        // Insert new contact record
        Test.startTest();
        Contact newContact = new Contact();
        newContact.FirstName = 'TestContact';
        newContact.LastName = 'TestLastName';
        newContact.Email = 'testingcontact@invalid.com';
        
        List<Contact> conList = new List<Contact>();
        conList.add(newContact);

        //Pass Input to Flow Insert Duplicate Apex action which will return contact Id
        String output = I_RM_FlowInsertContact.SaveContact(conList).get(0);

        Contact con =[Select Id from Contact where Email ='testingcontact@invalid.com' ];

        //Assertion output should not be blank and match the contact Id
        System.assert(!String.isBlank(output));
        System.assertEquals(con.Id, output);
        
        Test.stopTest();
    }
    
    /**
     * 
     * @description Test method for Apex class I_ST_FlowInsertAffiliations 
     * Vanita : 28/02/2022 as part of LTU360-1212 - Create test method for creating affiliation
    */
    @IsTest
    static void testInsertAffiliation() {

        Test.startTest();
		// Find contact with which affiliation will be linked
        List<Contact> conList = [Select Id from Contact];
		
        // Prepare Affiliation data which will then be passed to Flow Insert Affiliation class
        Id accountRecordTypeId = Schema.getGlobalDescribe().get('I_RM_Affiliation__c').getDescribe().getRecordTypeInfosByDeveloperName().get('I_RM_Lead').getRecordTypeId();
		List<I_RM_Affiliation__c> affList = new List<I_RM_Affiliation__c>();
		I_RM_Affiliation__c aff = new I_RM_Affiliation__c(I_RM_Campus_Interest__c = 'City Campus', I_RM_Study_Interest__c ='Health',
                                                          I_RM_Enquirer_Type__c ='International (inside Australia)',I_RM_Career_Area__c ='Disability',
                                                          I_RM_Email__c ='test23@test.com.invalid',I_RM_Mobile_Phone__c = '0411111120',I_RM_Contact__c = conList[0].Id,
                                                          I_RM_Role__c = 'Domestic Lead',I_RM_Lead_Source_Category__c = 'Consultation',RecordTypeId = accountRecordTypeId);
		affList.add(aff);
		system.debug('affList'+affList);

		// Call InsertAffiliation apex action to insert affiliation records
        List<String> AffRecords = new List<String>();
		AffRecords=I_RM_FlowInsertAffiliations.InsertAffiliation(affList);
		system.debug('AffRecords'+AffRecords);
        //query the affiliation record from the system which match the input data
        List<I_RM_Affiliation__c> insertedAff = [Select Id from I_RM_Affiliation__c where I_RM_Contact__c =: conList[0].Id and I_RM_Email__c ='test23@test.com.invalid'];
        
        // Assertion to check output from apex action call and system data
        System.assertEquals(insertedAff[0].Id, AffRecords[0]);
        Test.stopTest();
    }
    
    /**c
     * @description Test method for Apex class I_ST_FlowInsertAccount
    */
    @IsTest
    static void testAccountDuplicateSupport() {
        Id leadAcctRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('I_ST_Lead_Account').getRecordTypeId();
        
        //Insert an account
        Account acct1 = new Account(
            Name = 'Test Dup Account',
            RecordTypeId = leadAcctRTId
        );
        insert acct1;

        Test.startTest();

        //Create another account with the same name that will trigger dup rule and need to be overridden
        Account acct2 = new Account(
            Name = 'Test Dup Account',
            RecordTypeId = leadAcctRTId
        );
        //Prepare inputs
        List<Account> inputs = new List<Account>();
        inputs.add(acct2);

        //Get output
        String output = I_RM_FlowInsertAccount.SaveAccount(inputs).get(0);

        //Assert
        System.assertNotEquals(acct1.Id, output);
        
        Test.stopTest();
    }
    
    /**
     * @description Test method for Apex class I_ST_FlowLaunchScoring
    */
  /*  @IsTest
    static void testLaunchScoring() {
		
        Test.startTest();
        //Launch Contact Scoring
		Contact conToBeScored = [SELECT Id, FirstName FROM Contact WHERE FirstName = 'TestFirst2' LIMIT 1];
        
        List<I_ST_FlowLaunchScoring.Request> reqs = new List<I_ST_FlowLaunchScoring.Request>();
        I_ST_FlowLaunchScoring.Request req = new I_ST_FlowLaunchScoring.Request();
        req.flowType = 'Contact';
        req.objectID = conToBeScored.Id;
        reqs.add(req);
        I_ST_FlowLaunchScoring.ParseObjectValue(reqs);
        

        //Launch Case Scoring
        Case casToBeScored = new Case();
        casToBeScored.Subject = 'Test';
        casToBeScored.ContactId = conToBeScored.Id;
        casToBeScored.recordTypeId = [Select Id From RecordType Where DeveloperName = 'I_ST_Enquiry'].Id;
        system.debug('case inserted' + casToBeScored);
        insert casToBeScored; 
        
        List<I_ST_FlowLaunchScoring.Request> reqs2 = new List<I_ST_FlowLaunchScoring.Request>();
        I_ST_FlowLaunchScoring.Request req2 = new I_ST_FlowLaunchScoring.Request();
        req2.flowType = 'Case';
        req2.objectID = casToBeScored.Id;
        reqs2.add(req2);
        I_ST_FlowLaunchScoring.ParseObjectValue(reqs2);
        
        //assert
        //System.assert(!String.isBlank(duplicateCon.Id)); //fields returned by dup don't coincide with fields set
        Test.stopTest();
    }*/

    /**
     * @description Test method for Apex class OrgWideEmailAddressUtil
    */
    @IsTest
    static void testRetrieveOrgWideEmailAddressPositiveTest() {
        Test.startTest();
        List<String> displayNames = new List<String>();
        displayNames.add('Future Students');        
        List<String> orgWideEmailAddressIds = I_ST_OrgWideEmailAddressUtil.getOrgWideEmailAddressId(displayNames);
        Test.stopTest();
        System.assertEquals(1, orgWideEmailAddressIds.size());
    }


    /**
     * @description Test method for Apex class OrgWideEmailAddressUtil
    */
    @IsTest
    static void testRetrieveOrgWideEmailAddressNegativeTest() {
        String displayName = 'unknown';

        Test.startTest();
        List<String> displayNames = new List<String>();
        displayNames.add(displayName);

        try {
            List<String> orgWideEmailAddressIds = I_ST_OrgWideEmailAddressUtil.getOrgWideEmailAddressId(displayNames);
        } catch(Exception e) {
            System.assertEquals('There is no org wide email address for ' + displayName, e.getMessage());
        }
        Test.stopTest();
        // System.assertEquals(1, orgWideEmailAddressIds.size());
    }

    /**
     * @description Test method for Apex class I_ST_FlowUpdateServiceAppointment
    */
    @IsTest
    static void testUpdateServiceAppointment() {

        
        Id accountRecordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByDeveloperName().get('I_ST_Lead_Account').getRecordTypeId();

        Account leadAcct = new Account();
        leadAcct.recordTypeId = accountRecordTypeId;
        leadAcct.Name = 'testAccount';
        insert leadAcct;

        List<ServiceAppointment> sas = new List<ServiceAppointment>();

        sas.add(new ServiceAppointment(ParentRecordId = leadAcct.Id));
        insert sas;
        
        Test.startTest();
        I_ST_FlowUpdateServiceAppointment.updateServiceAppointments(sas);
        Test.stopTest();
    }
}