force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>A legally binding document that defines the obligations to which the contractual parties involved in conducting the research must adhere.</description>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/I_RS_Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Contract_End_Date__c</fullName>
    <label>Agreement/Variation End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/I_RS_Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Contract_Start_Date__c</fullName>
    <label>Agreement/Variation Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/I_RS_Organisation__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Organisation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Include the main Organisation for the Agreement. For Researcher Portal users if the organisation is not available, please include details in the Reasons for Agreement or Variation above.</inlineHelpText>
    <label>Organisation Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>You can only select Educational Institution or External Organisation record types</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Educational Institution</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>External Organisation</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/L_PR_Category__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Variation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/recordTypes/I_RS_New_La_Trobe_contract.recordType-meta.xml
<RecordType>
    <fullName>I_RS_New_La_Trobe_contract</fullName>
    <active>true</active>
    <label>La Trobe Agreement (No Template)</label>
</RecordType>

force-app/main/default/objects/Contract__c/recordTypes/L_PR_Agreement.recordType-meta.xml
<RecordType>
    <fullName>L_PR_Agreement</fullName>
    <active>true</active>
    <label>Partnership Agreement</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/L_PR_Location__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Location__c</fullName>
    <description>Identies the location associated with opportunity</description>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/L_PR_Location_Country__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Location_Country__c</fullName>
    <description>Identifies the country associated with location</description>
    <label>Location Country</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>L_PR_Location__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>I_RM_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/L_PR_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Sub_Type__c</fullName>
    <description>Provides a way of  further classifying/categorising this opportunity</description>
    <label>Opportunity Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>L_PR_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>L_PR_Sub_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/L_PR_Type__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Type__c</fullName>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>L_PR_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/PRM_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>PRM_Opportunity</fullName>
    <active>true</active>
    <businessProcess>PRM Opportunity Process</businessProcess>
    <label>PRM Opportunity</label>
</RecordType>

force-app/main/default/objects/Related_Contract__c/Related_Contract__c.object-meta.xml
<CustomObject>
    <label>Related Organisation</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Related Organisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Contract__c/fields/I_RS_Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Contract_Start_Date__c</fullName>
    <formula>I_RS_Contract__r.I_RS_Contract_Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agreement Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Related_Contract__c/fields/I_RS_Organisation__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Agreements</relationshipLabel>
    <relationshipName>Related_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Matrix__c/Task_Matrix__c.object-meta.xml
<CustomObject>
    <description>This object holds list of standard set of tasks that will be used to create standard Tasks for Project Proposal object</description>
    <label>Task Matrix</label>
    <nameField>
        <displayFormat>TM-{00000}</displayFormat>
        <label>Task Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Matrices</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Matrix__c/fields/I_RS_Inactive__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, Tasks for this Task Matrix record are not created during automations. Activating it does not retroactively create Tasks from updates that occurred previously.</description>
    <inlineHelpText>If checked, Tasks for this Task Matrix record are not created during automations. Activating it does not retroactively create Tasks from updates that occurred previously.</inlineHelpText>
    <label>Inactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Task_Matrix__c/fields/I_RS_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Object_Name__c</fullName>
    <description>Label/API Name of the Salesforce Object for which the &quot;tasks&quot; need to be created at the creation of project proposal or whenever the status of project proposal changes</description>
    <inlineHelpText>Label/API Name of the Salesforce Object for which the &quot;tasks&quot; need to be created at the creation of project proposal or whenever the status of project proposal changes</inlineHelpText>
    <label>Object Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Project_Proposal__c</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
                <default>true</default>
                <label>Opportunity</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Matrix__c/fields/I_RS_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Record_Type__c</fullName>
    <description>Name of the Record Type related to the Salesforce Object for which the Task has to be created.</description>
    <inlineHelpText>Name of the Record Type related to the Salesforce Object for which the Task has to be created.</inlineHelpText>
    <label>Record Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>I_RS_Object_Name__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>I_RS_Contract_La_Trobe_template</fullName>
                <label>Contract (La Trobe Template)</label>
            </value>
            <value>
                <fullName>I_RS_Contract_client_template</fullName>
                <label>Contract (Client Template)</label>
            </value>
            <value>
                <fullName>I_RS_Grant_with_limited_applications</fullName>
                <label>Grant with limited applications</label>
            </value>
            <value>
                <fullName>I_RS_Notice_of_intention</fullName>
                <label>Notice of intention</label>
            </value>
            <value>
                <fullName>I_RS_Other_grants</fullName>
                <label>Other grants</label>
            </value>
            <value>
                <fullName>I_RS_Proposal</fullName>
                <label>Proposal</label>
            </value>
            <value>
                <fullName>I_RS_Recommendation</fullName>
                <label>Recommendation</label>
            </value>
            <value>
                <fullName>I_RS_Non_Public_Proposal</fullName>
                <label>Non Public Proposal</label>
            </value>
            <value>
                <fullName>Placeholder</fullName>
            </value>
            <value>
                <fullName>I_RS_Project</fullName>
                <label>Project</label>
            </value>
            <value>
                <fullName>PRM Opportunity</fullName>
                <default>true</default>
                <label>PRM Opportunity</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Matrix__c/fields/I_RS_Subject__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Subject__c</fullName>
    <description>The value in this field will be the &quot;Subject&quot; of the Task.</description>
    <inlineHelpText>The value in this field will be the &quot;Subject&quot; of the Task.</inlineHelpText>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_Matrix__c/fields/L_PR_Agreement_Stage__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Agreement_Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Executed</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Matrix__c/fields/L_PR_Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Agreement_Type__c</fullName>
    <label>Agreement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Articulation Agreement</fullName>
            </value>
            <value>
                <fullName>Clinical Education Agreements (health)</fullName>
            </value>
            <value>
                <fullName>Clinical Trial Site Agreement</fullName>
            </value>
            <value>
                <fullName>Commercialisation Agreement</fullName>
            </value>
            <value>
                <fullName>Commercialisation Licence</fullName>
            </value>
            <value>
                <fullName>Confidentiality agreements</fullName>
            </value>
            <value>
                <fullName>Consulting Services Agreement (Non-Research)</fullName>
            </value>
            <value>
                <fullName>Contractors Agreement (services to LTU)</fullName>
            </value>
            <value>
                <fullName>Courseware Licensing</fullName>
            </value>
            <value>
                <fullName>Data Transfer Agreement</fullName>
            </value>
            <value>
                <fullName>Grant Funding Agreement</fullName>
            </value>
            <value>
                <fullName>Honorary/Adjunct/Visitors Deed</fullName>
            </value>
            <value>
                <fullName>Hospital/Health Services Agreement</fullName>
            </value>
            <value>
                <fullName>Individual Student Agreement - Placements</fullName>
            </value>
            <value>
                <fullName>Industry PhD Agreement</fullName>
            </value>
            <value>
                <fullName>Intellectual Property Assignment Deed</fullName>
            </value>
            <value>
                <fullName>Lease Agreement</fullName>
            </value>
            <value>
                <fullName>Licence to Occupy</fullName>
            </value>
            <value>
                <fullName>Material Transfer Agreement (receiving)</fullName>
            </value>
            <value>
                <fullName>Material Transfer Agreement (supplying)</fullName>
            </value>
            <value>
                <fullName>Memorandum of Understanding (MOU)</fullName>
            </value>
            <value>
                <fullName>Mobility – Overseas Short Programs</fullName>
            </value>
            <value>
                <fullName>Mobility – Semester Exchange</fullName>
            </value>
            <value>
                <fullName>Mobility – Study Abroad</fullName>
            </value>
            <value>
                <fullName>Mobility – Study Abroad and Exchange</fullName>
            </value>
            <value>
                <fullName>Mobility – Third Party Provider</fullName>
            </value>
            <value>
                <fullName>NDA (non-disclosure)</fullName>
            </value>
            <value>
                <fullName>Overarching Agreement - Placements</fullName>
            </value>
            <value>
                <fullName>Rental Agreement</fullName>
            </value>
            <value>
                <fullName>Research Collaboration Agreement</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/I_RM_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Åland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Argentinian Antarctic Territory</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Australian Antarctic Territory</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas (the)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia (Plurinational State of)</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/L_PR_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Education and Students</fullName>
    </customValue>
    <customValue>
        <fullName>Infrastructure &amp; Resources</fullName>
    </customValue>
    <customValue>
        <fullName>Innovation Ecosystem</fullName>
    </customValue>
    <customValue>
        <fullName>Research and Innovation</fullName>
    </customValue>
    <description>This picklist value set provides a categorisation/ classification  list for this Lead/Idea and opportunity.</description>
    <masterLabel>L_PR_Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContractTriggerTest.cls
@IsTest
public class ContractTriggerTest {
     /*  @author 		Vanita Walia
     * @date  			13/10/2022
     * @description 	test data setup method As part of Agreement conversion from Opportunity LTU360-2446
     */    
    public static Id prmAgreementRecordTypeId = Schema.SObjectType.Contract__c.getRecordTypeInfosByDeveloperName().get('L_PR_Agreement').getRecordTypeId();
    public static Id prmOpportunityRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('PRM_Opportunity').getRecordTypeId();
     
    @TestSetup
    static void setup(){
    	//create External organisation
        Account tstAccount = TestUtility.newEmptyExternalAccount('test External Organisation');
        insert tstAccount;
        
        Task_Matrix__c tm = new Task_Matrix__c();
        tm.L_PR_Agreement_Type__c = 'Articulation Agreement';
        tm.I_RS_Object_Name__c = 'Agreement';
        tm.I_RS_Record_Type__c = 'Partnership Agreement';
        tm.L_PR_Agreement_Stage__c = 'Executed';
        tm.I_RS_Subject__c = 'Test Subject1';
        tm.I_RS_Inactive__c = false;
        Insert tm;

        Task_Matrix__c tm2 = new Task_Matrix__c();
        tm2.L_PR_Agreement_Type__c = 'Articulation Agreement';
        tm2.I_RS_Object_Name__c = 'Agreement';
        tm2.I_RS_Record_Type__c = 'Partnership Agreement';
        tm2.L_PR_Agreement_Stage__c = 'Terminated';
        tm2.I_RS_Subject__c = 'Test Subject2';
        tm2.I_RS_Inactive__c = false;
        Insert tm2;
        //create opportunity
        Opportunity testOpp = new Opportunity();
        testOpp.RecordTypeId = prmOpportunityRecordTypeId;
        testOpp.AccountId = tstAccount.Id;
        testOpp.L_PR_Type__c = 'Education and Students';
        testOpp.L_PR_Sub_Type__c = 'Third Party Teaching';
        testOpp.L_PR_Location__c = 'Domestic';
        testOpp.L_PR_Location_Country__c = 'Australia';
        testOpp.CloseDate = System.today() +30;
        testOpp.StageName = 'Prospecting';
        testOpp.Name ='TestOpp1';
        Insert testOpp;

        Account extOrgAcc = TestUtility.newEmptyAccount('test ExtOrg1','I_RS_External_Organisation');
        Insert extOrgAcc;
        Account  laOrg1= TestUtility.newEmptyAccount('test laOrg1','I_RS_La_Trobe_Organisation_Unit');
        Insert laOrg1;

        Contract__c prmAgreement = new Contract__c();
        prmAgreement.Name ='Prm Agreement1';
        prmAgreement.recordTypeId = prmAgreementRecordTypeId;
        prmAgreement.I_RS_Organisation__c = extOrgAcc.Id;
        prmAgreement.L_PR_Category__c = 'New';
        prmAgreement.I_RS_Contract_Start_Date__c = System.today();
        prmAgreement.I_RS_Contract_End_Date__c = System.today() +10;
        prmAgreement.I_RS_Status__c = 'Executed';
        prmAgreement.I_RS_Agreement_Type__c = 'Articulation Agreement';
        Insert prmAgreement;
    }
    
    /*  @author 		Vanita Walia
     * @date  			13/10/2022
     * @description 	test method As part of Agreement conversion from Opportunity LTU360-2446
     */  
    @isTest
    public static void testupdateConvertedOpp(){

        Test.startTest();
		List<Account> acc = [Select Id from Account Limit 1];
        List<Opportunity> opp = [Select Id,AccountId, StageName from Opportunity Limit 1];
		//Create new Agreement from Opportunity
		Contract__c prmAgreement = new Contract__c(RecordTypeId = prmAgreementRecordTypeId,
                                                  Name ='Test Agreement', I_RS_Organisation__c = acc[0].Id,
                                                  L_PR_Category__c ='New', I_RS_Agreement_Type__c='Other',
                                                  I_RS_Contract_Start_Date__c = system.today(), 
                                                  I_RS_Contract_End_Date__c = system.today()+30, 
                                                  L_PR_Opportunity_Name__c = opp[0].Id,
                                                  L_PR_IsConverted__c = True);
        insert prmAgreement;
        
         List<Opportunity> updatedOpp = [Select Id,AccountId, StageName from Opportunity where Id =: opp[0].Id];
        system.assertEquals('Closed Won', updatedOpp[0].StageName);
        Test.stopTest();
    }
    
     /*  @author 		Vanita Walia
     * @date  			13/10/2022
     * @description 	this method will test exception handling
     */
	@isTest
    public static void testupdateConvertedOpp_Exception(){

        Test.startTest();
       Map<Id,Id> testMap = new Map<Id,Id>();
        testMap.put('a3T5P0000008qzFUAQ','a3T5P0000008qzFUAQ');
        try{
        	ContractTriggerHelper.updateOppStatusClosedWon(testMap);            
        }catch(exception e){
             System.debug ('Exception'+e);
        }
        
        Test.stopTest();
    }  
    

    @IsTest
    public static void deleteAsNonSysAdmin() {
        
        //Create deletion-blocker custom setting
        insert new Object_Metadata__c(
            Name = 'Contract__c',
            I_RS_Enable_Deletion_Blocker__c = true,
            I_RS_Deletion_Blocker_Check_Formula__c = 'I_RS_Valid_for_Deletion__c',
            I_RS_Deletion_Blocker_Error_Message__c = 'You cant delete record'
        );

        // create a management user 
        Profile gProfile = [SELECT Id FROM Profile WHERE Name='LTU PRIME'];
        User gUser;
        gUser = new User(Alias = 'gUser', Email='guser@ltu.com.test', 
            EmailEncodingKey='UTF-8', LastName='researcher', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_AU', ProfileId = gProfile.Id, 
            TimeZoneSidKey='Australia/Sydney', UserName='guser@ltu.com.test');
        insert gUser;
        
        Account acc = TestUtility.newEmptyExternalAccount('test Acc');
        Insert acc;
        
        //Create an agreement and related agreement;
        //Id RecTypeId = Schema.SObjectType.Contract__c.getRecordTypeInfosByDeveloperName().get('I_RS_New_La_Trobe_contract').getRecordTypeId();
        Contract__c pAgreement = new Contract__c(Name='Parent Agreement', I_RS_Organisation__c = acc.Id );
        Insert pAgreement;
        
        Contract__c cAgreement = new Contract__c(Name='Child Agreement', I_RS_Contract__c = pAgreement.Id, I_RS_Organisation__c = acc.Id);
        Insert cAgreement;
        
        List<Contract__c> agreements = [SELECT ID, Name FROM Contract__c];
        
        System.assertEquals(agreements.size(), 3, 'There should be three records');
        
        Test.startTest();
        System.runAs ( gUser ) {
            try{
            	delete pAgreement;
            }  catch (Exception e){
                system.debug('Exception Message: ' + e.getMessage());
            }
        }

        Test.stopTest();
            agreements.clear();
            agreements = [SELECT ID, Name FROM Contract__c];            
            System.assertEquals(agreements.size(), 3, 'There should be three records');
    }

    public static void deleteAsSysAdmin() {
        
        //Create deletion-blocker custom setting
        insert new Object_Metadata__c(
            Name = 'Contract__c',
            I_RS_Enable_Deletion_Blocker__c = true,
            I_RS_Deletion_Blocker_Check_Formula__c = 'I_RS_Valid_for_Deletion__c',
            I_RS_Deletion_Blocker_Error_Message__c = 'You cant delete record'
        );

        // create a management user 
        Profile gProfile = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User gUser;
        gUser = new User(Alias = 'gUser', Email='guser@ltu.com.test', 
            EmailEncodingKey='UTF-8', LastName='researcher', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_AU', ProfileId = gProfile.Id, 
            TimeZoneSidKey='Australia/Sydney', UserName='guser@ltu.com.test');
        insert gUser;
        
        Account acc = TestUtility.newEmptyExternalAccount('test Acc');
        Insert acc;
        
        //Create an agreement and related agreement;
        //Id RecTypeId = Schema.SObjectType.Contract__c.getRecordTypeInfosByDeveloperName().get('I_RS_New_La_Trobe_contract').getRecordTypeId();
        Contract__c pAgreement = new Contract__c(Name='Parent Agreement', I_RS_Organisation__c = acc.Id );
        Insert pAgreement;
        
        Contract__c cAgreement = new Contract__c(Name='Child Agreement', I_RS_Contract__c = pAgreement.Id, I_RS_Organisation__c = acc.Id);
        Insert cAgreement;
        
        List<Contract__c> agreements = [SELECT ID, Name FROM Contract__c];
        
        System.assertEquals(agreements.size(), 2, 'There should be two records');
        
        Test.startTest();
        System.runAs ( gUser ) {
            try{
            	delete pAgreement;
            }  catch (Exception e){
                system.debug('Exception Message: ' + e.getMessage());
            }
        }

        Test.stopTest();
            agreements.clear();
            agreements = [SELECT ID, Name FROM Contract__c];            
            System.assertEquals(agreements.size(), 0, 'There should be two records');
    }

    @isTest 
    public static void updateRelatedOrgStatusTest(){

        Test.startTest();
        List<Contract__c> agreements = new List<Contract__c>();
        agreements = [Select Name, I_RS_Organisation__c, I_RS_Status__c From Contract__c Where Name ='Prm Agreement1'];
        agreements[0].I_RS_Status__c = 'Closed';
        agreements[0].I_RS_Closure_Reason__c ='Expired';
        update agreements[0];
        Test.stopTest();
        system.assertEquals( agreements[0].I_RS_Status__c, 'Closed');
    }

    @isTest 
    public static void createUpdateRelatedExternalOrgsTest(){

        Test.startTest();
        List<Contract__c> agreements = new List<Contract__c>();
        agreements = [Select Name, I_RS_Organisation__c, I_RS_Status__c From Contract__c Where Name ='Prm Agreement1'];
        Account extOrgAcc1 = TestUtility.newEmptyAccount('test ExtOrg1','I_RS_External_Organisation');
        Insert extOrgAcc1;
        Account extOrgAcc2 = TestUtility.newEmptyAccount('test ExtOrg2','I_RS_External_Organisation');
        Insert extOrgAcc2;

        agreements[0].I_RS_Organisation__c = extOrgAcc1.Id;
        update agreements[0];
        agreements[0].I_RS_Organisation__c = extOrgAcc2.Id;
        update agreements[0];
        agreements[0].I_RS_Organisation__c = extOrgAcc1.Id;
        update agreements[0];
        List<Related_Contract__c> ro = new List<Related_Contract__c>();
        ro = [Select Id, L_PR_isPrimary__c from Related_Contract__c Where I_RS_Organisation__c =: extOrgAcc1.Id];
        system.assertEquals( ro[0].L_PR_isPrimary__c, true);
        Test.stopTest();
    }


    @isTest 
    public static void updateOppStatusClosedWonTest(){

        Test.startTest();
        Account extOrgAcc1 = TestUtility.newEmptyAccount('test ExtOrg1','I_RS_External_Organisation');
        Insert extOrgAcc1;
        Id oppRecordTypeId = 
            Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('PRM_Opportunity').getRecordTypeId();
        Opportunity opp = new Opportunity();
        opp.recordTypeId = oppRecordTypeId;
        opp.Name = 'PRM Opportunity1';
        opp.AccountId = extOrgAcc1.Id;
        opp.L_PR_Type__c = 'Research and Innovation';
        opp.L_PR_Sub_Type__c = 'Access to equipment';
        opp.L_PR_Location__c = 'Domestic';
        opp.L_PR_StartDate__c = System.today();
        opp.L_PR_Opportunity_Close_Date__c = System.today()+20;
        opp.StageName = 'Prospecting';
        opp.CloseDate = System.today()+20;
        Insert opp;
        Contract__c prmAgreement = new Contract__c();
        prmAgreement.Name ='Prm Agreement1';
        prmAgreement.L_PR_Opportunity_Name__c = opp.Id;
        prmAgreement.L_PR_IsConverted__c = true;
        prmAgreement.I_RS_Organisation__c = extOrgAcc1.Id;
        prmAgreement.L_PR_Category__c = 'New';
        prmAgreement.I_RS_Contract_Start_Date__c = System.today();
        prmAgreement.I_RS_Contract_End_Date__c = System.today() +10;
        prmAgreement.I_RS_Status__c = 'Executed';
        Insert prmAgreement;
        List<Opportunity> oppList = new List<Opportunity>();
        oppList = [Select Id, Name, StageName from Opportunity Where Id =: opp.Id];
        system.assertEquals( oppList[0].StageName, 'Closed Won');
        Test.stopTest();
    }

    @isTest 
    public static void createTasksFromTaskMatrixTest(){
        Id taskAgreementRecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName().get('L_PR_Agreement_Task').getRecordTypeId();
        Test.startTest();
        List<Contract__c> agreements = new List<Contract__c>();
        agreements = [Select Name, I_RS_Organisation__c, I_RS_Status__c, OwnerId From Contract__c Where Name ='Prm Agreement1'];
        agreements[0].I_RS_Closure_Reason__c = null;
        update agreements[0];
        Task tk = new Task();
        tk.Subject = 'prm agreement task test1';
        tk.WhatId = agreements[0].Id;
        tk.Status = 'Not Started';
        tk.RecordTypeId = taskAgreementRecordTypeId;
        tk.OwnerId =  agreements[0].OwnerId;
        tk.L_PR_Stage__c = 'Terminated';
        Insert tk;
        agreements[0].I_RS_Status__c ='Closed';
        agreements[0].I_RS_Closure_Reason__c = 'Terminated';
        agreements[0].L_PR_Reason_for_termination__c = 'Test1';
        agreements[0].L_PR_Termination_Date__c = System.today();
        update agreements[0];
        List<Task> tk2 = new List<Task>();
        tk2 = [Select Id,Subject from Task where whatId =: agreements[0].Id];
        system.assertEquals( tk2.size(), 3);
        Test.stopTest();
    }

}