force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>A legally binding document that defines the obligations to which the contractual parties involved in conducting the research must adhere.</description>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/I_RS_Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Agreement_Type__c</fullName>
    <label>Agreement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Articulation Agreement</fullName>
            </value>
            <value>
                <fullName>Clinical Education Agreements (health)</fullName>
            </value>
            <value>
                <fullName>Clinical Trial Site Agreement</fullName>
            </value>
            <value>
                <fullName>Commercialisation Agreement</fullName>
            </value>
            <value>
                <fullName>Commercialisation Licence</fullName>
            </value>
            <value>
                <fullName>Confidentiality agreements</fullName>
            </value>
            <value>
                <fullName>Confidentiality Deed/NDA</fullName>
            </value>
            <value>
                <fullName>Consulting Services Agreement (Non-Research)</fullName>
            </value>
            <value>
                <fullName>Contractors Agreement (services to LTU)</fullName>
            </value>
            <value>
                <fullName>Courseware Licensing</fullName>
            </value>
            <value>
                <fullName>Data Transfer Agreement</fullName>
            </value>
            <value>
                <fullName>Grant Funding Agreement</fullName>
            </value>
            <value>
                <fullName>Honorary/Adjunct/Visitors Deed</fullName>
            </value>
            <value>
                <fullName>Hospital/Health Services Agreement</fullName>
            </value>
            <value>
                <fullName>Individual Student Agreement - Placements</fullName>
            </value>
            <value>
                <fullName>Industry PhD Agreement</fullName>
            </value>
            <value>
                <fullName>Intellectual Property Assignment Deed</fullName>
            </value>
            <value>
                <fullName>International Agent Agreement</fullName>
            </value>
            <value>
                <fullName>Lease Agreement</fullName>
            </value>
            <value>
                <fullName>Licence Agreement (receiving)</fullName>
            </value>
            <value>
                <fullName>Licence Agreement (supplying)</fullName>
            </value>
            <value>
                <fullName>Licence to Occupy</fullName>
            </value>
            <value>
                <fullName>Master Services Agreement</fullName>
            </value>
            <value>
                <fullName>Material/Data Transfer Agreement (receiving)</fullName>
            </value>
            <value>
                <fullName>Material/Data Transfer Agreement (supplying)</fullName>
            </value>
            <value>
                <fullName>Material Transfer Agreement (receiving)</fullName>
            </value>
            <value>
                <fullName>Material Transfer Agreement (supplying)</fullName>
            </value>
            <value>
                <fullName>Memorandum of Understanding (MOU)</fullName>
            </value>
            <value>
                <fullName>Mobility – Overseas Short Programs</fullName>
            </value>
            <value>
                <fullName>Mobility – Semester Exchange</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/fields/I_RS_Contract__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hierarchy or related contracts in case of renewal or amendments</description>
    <inlineHelpText>Select an existing Agreement if this request is for Variations or Subcontract/Collaboration requests.</inlineHelpText>
    <label>Parent Agreement</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Child Agreements</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/I_RS_Organisation__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Organisation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Include the main Organisation for the Agreement. For Researcher Portal users if the organisation is not available, please include details in the Reasons for Agreement or Variation above.</inlineHelpText>
    <label>Organisation Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>You can only select Educational Institution or External Organisation record types</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Educational Institution</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>External Organisation</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/I_RS_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Status__c</fullName>
    <inlineHelpText>“Executed” is when the Agreement/Variation has been signed and is active.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Initial</fullName>
            </value>
            <value>
                <fullName>Preparing Instructions</fullName>
            </value>
            <value>
                <fullName>Instructions</fullName>
            </value>
            <value>
                <fullName>Engage Legal to Draft Variation</fullName>
            </value>
            <value>
                <fullName>Update Variation</fullName>
            </value>
            <value>
                <fullName>Notify Appropriate Stakeholders</fullName>
            </value>
            <value>
                <fullName>Create Letter</fullName>
                <label>Create Variation</label>
            </value>
            <value>
                <fullName>Completing Template</fullName>
            </value>
            <value>
                <fullName>Engage Legal to Draft Contract</fullName>
            </value>
            <value>
                <fullName>Reviewing Draft</fullName>
            </value>
            <value>
                <fullName>Client Review</fullName>
                <label>Other Party Review</label>
            </value>
            <value>
                <fullName>Legal Review</fullName>
            </value>
            <value>
                <fullName>Update Contract</fullName>
            </value>
            <value>
                <fullName>Researcher Review</fullName>
            </value>
            <value>
                <fullName>With Other Party</fullName>
            </value>
            <value>
                <fullName>La Trobe Signature</fullName>
            </value>
            <value>
                <fullName>Send to Client</fullName>
                <label>Send to Other Party</label>
            </value>
            <value>
                <fullName>Client Countersign</fullName>
                <label>Other Party Countersign</label>
            </value>
            <value>
                <fullName>Receive Client Signed Copy</fullName>
                <label>Receive Other Party Signed Copy</label>
            </value>
            <value>
                <fullName>Receive Executed Copy</fullName>
            </value>
            <value>
                <fullName>Notify of Variation Outcome</fullName>
            </value>
            <value>
                <fullName>La Trobe Countersign</fullName>
            </value>
            <value>
                <fullName>La Trobe University Signature</fullName>
            </value>
            <value>
                <fullName>Send Signed Copy Back</fullName>
            </value>
            <value>
                <fullName>Submit to Research Office</fullName>
            </value>
            <value>
                <fullName>Return Signed Copy to Client</fullName>
                <label>Return Signed Copy to Other Party</label>
            </value>
            <value>
                <fullName>Executed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/fields/L_PR_IsConverted__c.field-meta.xml
<CustomField>
    <fullName>L_PR_IsConverted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If Agreement is converted from opportunity</description>
    <label>IsConverted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/L_PR_La_Trobe_Organisation_Unit__c.field-meta.xml
<CustomField>
    <fullName>L_PR_La_Trobe_Organisation_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>La Trobe Organisation Unit</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You can only select La Trobe Organisation Unit Organisation</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>La Trobe Organisation Unit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agreements (La Trobe Organisation Unit)</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/L_PR_Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select the PRM Opportunity</errorMessage>
        <filterItems>
            <field>Opportunity.RecordType.Name</field>
            <operation>equals</operation>
            <value>PRM Opportunity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/recordTypes/L_PR_Agent_Agreement.recordType-meta.xml
<RecordType>
    <fullName>L_PR_Agent_Agreement</fullName>
    <active>true</active>
    <label>LTU Int Agent Agreement</label>
</RecordType>

force-app/main/default/objects/Contract__c/recordTypes/L_PR_Agreement.recordType-meta.xml
<RecordType>
    <fullName>L_PR_Agreement</fullName>
    <active>true</active>
    <label>Partnership Agreement</label>
</RecordType>

force-app/main/default/objects/Related_Contract__c/Related_Contract__c.object-meta.xml
<CustomObject>
    <label>Related Organisation</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Related Organisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Contract__c/fields/I_RS_Contract__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Contract__c</fullName>
    <label>Agreement</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Related Organisations</relationshipLabel>
    <relationshipName>Related_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Related_Contract__c/fields/I_RS_Organisation__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Agreements</relationshipLabel>
    <relationshipName>Related_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Contract__c/fields/L_PR_Agreement_Status__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Agreement_Status__c</fullName>
    <label>Agreement Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContractTriggerHandler.cls
/**
 * Created by burnside on 2019-04-23.
 */

public with sharing class ContractTriggerHandler {

    public static void execute(){

        System.debug('ContractTriggerHandler');

        System.debug(Trigger.operationType);


        if (Trigger.isBefore) {
            
	        if (Trigger.isDelete){
                
                List<Contract__c> agreementsThatFailedToDelete = DeletionBlocker.blockDelete('Contract__c', Trigger.Old);
                if (agreementsThatFailedToDelete != NULL && agreementsThatFailedToDelete.isEmpty()){
            		delete [SELECT Id FROM Related_Contract__c WHERE I_RS_Contract__c IN :Trigger.oldMap.keySet()];
                }
        	}
        }

        if (Trigger.isAfter) {

            if (Trigger.isInsert) {
                new ProjectTeamMemberRecordAccess3().runViaChildRecord('Contract__c');
                ProjectTeamMemberHierarchyAccess.handleContractRecordVisibility(null, (Map<Id, Contract__c>)Trigger.newMap);
            }

            if (Trigger.isUpdate) {
                new ProjectTeamMemberRecordAccess3().runViaChildRecord('Contract__c');

                //Invokes sharing code
                update [SELECT Id FROM Related_Contract__c
                    WHERE I_RS_Contract__c IN :Trigger.newMap.keySet() OR I_RS_Contract__c IN :Trigger.oldMap.keySet()
                ];

                ProjectTeamMemberHierarchyAccess.handleContractRecordVisibility((Map<Id, Contract__c>)Trigger.oldMap, (Map<Id, Contract__c>)Trigger.newMap);


            }

            //LTU360-2354

            if(Trigger.isUpdate || Trigger.isInsert){

                //LTU360-2384

                Map<Id,String> agreementStatusMap = new Map<Id,String>();
                Map<Id,Contract__c> mapOldAgreemets = (Map<Id,Contract__c>)Trigger.oldMap;
                Map<Id,Contract__c> mapOfAgreements = (Map<Id,Contract__c>)Trigger.newMap;
                Map<Id, Id> agrEOrgMap = new Map<Id,Id>(); 
                Map<Id, Id> agrIOrgMap = new Map<Id,Id>(); 
                Map<Id, Id> removeAgrEOrgMap = new Map<Id,Id>(); 
                Map<Id, Id> removeAgrIOrgMap = new Map<Id,Id>();
                Map<Id,Id> oppAggMap = new Map<Id,Id>();
                Map<Id, Contract__c> agreementMap = new Map<Id, Contract__c>();
                Id prmAgreementRecordTypeId = Schema.SObjectType.Contract__c.getRecordTypeInfosByDeveloperName().get('L_PR_Agreement').getRecordTypeId();
                Id agentAgreementRecordTypeId = Schema.SObjectType.Contract__c.getRecordTypeInfosByDeveloperName().get('L_PR_Agent_Agreement').getRecordTypeId();
                for(Contract__c agr : (List<Contract__c>)Trigger.new){  
                    // check if I_RS_Status__c is updated (to update on Related_Contract__c L_PR_Agreement_Status__c field)
                    if(agr.I_RS_Status__c != Null && Trigger.isUpdate && agr.I_RS_Status__c != mapOldAgreemets.get(agr.Id).I_RS_Status__c){
                        agreementStatusMap.put(agr.Id,agr.I_RS_Status__c);
                    }

                    // check if organisation is not blank or value is updated
                    if(agr.I_RS_Organisation__c != Null  && (Trigger.isInsert || (Trigger.isUpdate && agr.I_RS_Organisation__c != mapOldAgreemets.get(agr.Id).I_RS_Organisation__c))){                           
                        agrEOrgMap.put(agr.Id,agr.I_RS_Organisation__c);                               
                    }
                    else if(Trigger.isUpdate && agr.I_RS_Organisation__c == Null && agr.I_RS_Organisation__c != mapOldAgreemets.get(agr.Id).I_RS_Organisation__c){ 
                        //remove the record from list
                        removeAgrEOrgMap.put(agr.Id,mapOldAgreemets.get(agr.Id).I_RS_Organisation__c);
                    }

                    // check if LaTrobe organisation is not blank or value is updated
                    if(agr.L_PR_La_Trobe_Organisation_Unit__c != Null  && (Trigger.isInsert || (Trigger.isUpdate && agr.L_PR_La_Trobe_Organisation_Unit__c != mapOldAgreemets.get(agr.Id).L_PR_La_Trobe_Organisation_Unit__c))){                           
                        agrIOrgMap.put(agr.Id,agr.L_PR_La_Trobe_Organisation_Unit__c);                               
                    }
                    else if(Trigger.isUpdate && agr.L_PR_La_Trobe_Organisation_Unit__c == Null && agr.L_PR_La_Trobe_Organisation_Unit__c != mapOldAgreemets.get(agr.Id).L_PR_La_Trobe_Organisation_Unit__c){ 
                        //remove the record from list
                        removeAgrIOrgMap.put(agr.Id,mapOldAgreemets.get(agr.Id).L_PR_La_Trobe_Organisation_Unit__c);
                    }
                    
                    //check if agreement is converted from opportunity
                    if(Trigger.isInsert && agr.L_PR_Opportunity_Name__c != Null && agr.L_PR_IsConverted__c == True){
                        oppAggMap.put(agr.L_PR_Opportunity_Name__c,agr.Id);                                     
                    }

                    //LTU360-2659 Create agreement tasks from the Task Matrix
                    if(agr.recordTypeId == prmAgreementRecordTypeId || agr.recordTypeId == agentAgreementRecordTypeId){
                        if((agr.I_RS_Agreement_Type__c != Null  && (Trigger.isInsert || (Trigger.isUpdate && agr.I_RS_Agreement_Type__c != mapOldAgreemets.get(agr.Id).I_RS_Agreement_Type__c)))
                        || (agr.I_RS_Status__c != Null  && (Trigger.isInsert || (Trigger.isUpdate && agr.I_RS_Status__c != mapOldAgreemets.get(agr.Id).I_RS_Status__c)))){                           
                                agreementMap.put(agr.Id,agr);                               
                        }
                    }
                    if(!agreementMap.isEmpty()){
                        ContractTriggerHelper.createTasksFromTaskMatrix(agreementMap);
                    }
                }
                    if(agreementStatusMap != null){
                        ContractTriggerHelper.updateRelatedOrgStatus(agreementStatusMap);
                    }  
                    if(!agrEOrgMap.isEmpty() || !removeAgrEOrgMap.isEmpty()){
                       ContractTriggerHelper.createUpdateRelatedOrgs(agrEOrgMap, removeAgrEOrgMap, 'External', mapOfAgreements);
                    }

                    if(!agrIOrgMap.isEmpty() || !removeAgrIOrgMap.isEmpty()){
                       ContractTriggerHelper.createUpdateRelatedOrgs(agrIOrgMap, removeAgrIOrgMap, 'Internal', mapOfAgreements);
                    }

					//call helper method to mark opportunity as Closed Won
                    if(!oppAggMap.isEmpty()){
                        ContractTriggerHelper.updateOppStatusClosedWon(oppAggMap);
                    }


            }

            if (Trigger.isDelete) {

                ProjectTeamMemberHierarchyAccess.handleContractRecordVisibility((Map<Id, Contract__c>)Trigger.oldMap, null);
            }

        }

    }

}