force-app/main/default/objects/I_ST_BatchScoring__c/I_ST_BatchScoring__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>I_ST_BatchScoring</label>
</CustomObject>

force-app/main/default/objects/I_ST_BatchScoring__c/fields/I_ST_BatchSize__c.field-meta.xml
<CustomField>
    <fullName>I_ST_BatchSize__c</fullName>
    <description>This is the batch size to control the Lead/Activity scoring jobs for IST</description>
    <label>I_ST_BatchSize</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/I_ST_BatchScoring__c/fields/I_ST_CronExpression__c.field-meta.xml
<CustomField>
    <fullName>I_ST_CronExpression__c</fullName>
    <description>Example: 0 0 0,4,8,12,16,20 ? * *

Seconds - so 0 here i.e. start of the minute.
Minutes - 0 again so start of the hour.
Start Time - 0 means 12 am
Hours - 4 hours after start time
- 
- 
- 
-
Day_of_week - 1,2,3,4,5,6,7 here specifies days 1,2,3,4,5,6,7 in the week. We could also write this string as MON-FRI or preferably as * to indicate all values.</description>
    <inlineHelpText>For example. Use 0 0 0,4,8,12,16,20 ? * * to schedule every 4 hours</inlineHelpText>
    <label>I_ST_CronExpression</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_ST_BatchScoring__c/fields/I_ST_Last_N_Hour__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Last_N_Hour__c</fullName>
    <description>Used for Activity Scoring batch to run batch and pick records modified &apos;N&apos; hours before current time</description>
    <label>I_ST_Last_N_Hour</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/I_ST_BatchScoring__c/fields/I_ST_RecordType_SFIDs__c.field-meta.xml
<CustomField>
    <fullName>I_ST_RecordType_SFIDs__c</fullName>
    <description>Provide comma separated RecordTypeIds of Case object which is to be considered for Activity Scoring. To get the record type Ids =&gt; Navigate to Setup -&gt; Object Manager -&gt; Case -&gt; RecordTypes -&gt; Select the record type -&gt; copy the 18 digit Id from the URL</description>
    <label>I_ST_RecordType_SFIDs</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/I_ST_ActivityScoring_Batch_Scheduler.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* I_ST_ActivityScoring_Batch_Scheduler
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Teja Yenduri   <tyenduri@au1.ibm.com>
* @version        1.0
* @created        2022-02-18
* @Description	  This class is used to schedule the batch job to calaculate Activity Score on Affiliation
* @Params	  	  
*/
global class I_ST_ActivityScoring_Batch_Scheduler implements Schedulable {
    private Set<Id> recordTypeIds;
    private Integer lastNHours = 24;
    private Decimal batchSize = 30;
    
    //Call this method from developer console directly to schedule the batch
    //Use command I_ST_ActivityScoring_Batch_Scheduler2.scheduleActivityScoring() from developer console
    global static String scheduleActivityScoring() {
       
            String cronExpression = I_ST_BatchScoring__c.getValues(GlobalConstants.I_ST_CASESCORING).I_ST_CronExpression__c ;
            I_ST_ActivityScoring_Batch_Scheduler SC = new I_ST_ActivityScoring_Batch_Scheduler(); 
            return system.schedule('Activity Scoring Job', cronExpression, SC);
       
    }
    
    global void execute(SchedulableContext sc) { 
        
        //GET the Batch Scoring custom setting for required parameters      
        I_ST_BatchScoring__c batchScoringCustomSetting = I_ST_BatchScoring__c.getValues(GlobalConstants.I_ST_CASESCORING);
        
        lastNHours = (Integer)batchScoringCustomSetting.I_ST_Last_N_Hour__c;
        Set<Id> recordTypeIds = GlobalUtility.convertCommaSeparatedStringsToSetIds(batchScoringCustomSetting.I_ST_RecordType_SFIDs__c);
        batchSize = batchScoringCustomSetting.I_ST_BatchSize__c;
        
        I_ST_ActivityScoring_Batch leadScoringBatch = new I_ST_ActivityScoring_Batch(GlobalConstants.CASE_OBJECT_API_NAME,recordTypeIds,lastNHours);
        Database.executeBatch(leadScoringBatch,Integer.valueOf(batchSize));
        }
    }