force-app/main/default/objects/Account/fields/I_RS_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Proposed</fullName>
                <isActive>false</isActive>
                <label>Proposed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Budget__c/Budget__c.object-meta.xml
<CustomObject>
    <description>This is the summarised budget header details that goes for approval &amp; is maintained in system for any further progress, tracking or finance integration</description>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget__c/fields/I_RS_Line_Item_Permission_Delete__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Line_Item_Permission_Delete__c</fullName>
    <description>Whether deleting this Budget&apos;s Line Items - whether via the Calculator or standard means - is permitted</description>
    <formula>/*For Researchers, only Drafts can be deleted*/
(
TEXT(I_RS_Status__c) = &apos;Draft&apos; &amp;&amp;
$User.I_RS_Is_Researcher_User__c = &apos;1&apos;
)

||

/*Non-researchers have full access*/
$User.I_RS_Is_Researcher_User__c = &apos;0&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Line Item Permission - Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Status__c</fullName>
    <inlineHelpText>Draft: I&apos;m working on it; Active: This is the actual budget for the project; Superseded: Previous active versions.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Superseded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/Budget_Line_Item__c.object-meta.xml
<CustomObject>
    <description>This will capture the calculated budget line details from Budget Calculator tool. Please note that Budget Calculator will be a custom developed tool built &amp; integrated with Salesforce. Later the calculated values will be stored in this object.</description>
    <label>Budget Line Item</label>
    <nameField>
        <displayFormat>BLI-{00000}</displayFormat>
        <label>Budget Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Line_Item_Permission_Delete__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Line_Item_Permission_Delete__c</fullName>
    <description>Dictates whether a user is allowed (excluding config such as Profile) to delete this record. Is currently based solely on Budget object formula, but can be changed. Is used as safeguard on deleting Budget Line Items that shouldn&apos;t be deleted, in the event the Budget Calculator doesn&apos;t lock down properly.</description>
    <formula>I_RS_Budget__r.I_RS_Line_Item_Permission_Delete__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Line Item Permission - Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TBD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Object_Metadata__c/Object_Metadata__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Captures information about objects that would otherwise be hard to obtain, even with code. Useful for flows.

Used in: 
- &apos;Approval Process: Approver&apos;s Queue&apos; to filter results by a specific object, as object name is not readily available in underlying system data.</description>
    <label>Object Metadata</label>
</CustomObject>

force-app/main/default/objects/Object_Metadata__c/fields/I_RS_Deletion_Blocker_Check_Formula__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Deletion_Blocker_Check_Formula__c</fullName>
    <description>If the formula field specific equates to false, then a deletion of the given record is invalid and should be blocked in code.</description>
    <inlineHelpText>If the formula field specific equates to false, then a deletion of the given record is invalid and should be blocked in code.</inlineHelpText>
    <label>Deletion Blocker Check-Formula</label>
    <length>43</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_Metadata__c/fields/I_RS_Deletion_Blocker_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Deletion_Blocker_Error_Message__c</fullName>
    <description>The specific error message to appear if a deletion fails</description>
    <label>Deletion Blocker Error Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Object_Metadata__c/fields/I_RS_Enable_Deletion_Blocker__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Enable_Deletion_Blocker__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, invalid deletions will be prevented. Validity is provided through specified formula field</description>
    <inlineHelpText>If checked, invalid deletions will be prevented. Validity is provided through specified formula field</inlineHelpText>
    <label>Enable Deletion-Blocker</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_Proposal__c/Project_Proposal__c.object-meta.xml
<CustomObject>
    <description>Project Proposal: An application for funding either through a grant request, a tender response, or a contract proposal.
Project: The work that is undertaken to satisfy a commitment made to a funding body or client.  The commitment is likely to be a contract (and possible variations) resulting from the acceptance of a project proposal.  This occurs after a grant, contract of philanthropic donation has been awarded.</description>
    <label>Project Proposal</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Proposal__c/fields/I_RS_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PlaceHolder</fullName>
            </value>
            <value>
                <fullName>Create Proposal</fullName>
            </value>
            <value>
                <fullName>Proposal Review</fullName>
            </value>
            <value>
                <fullName>Recommended</fullName>
            </value>
            <value>
                <fullName>Dismissed</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Create EOI</fullName>
            </value>
            <value>
                <fullName>Drafting NOI</fullName>
            </value>
            <value>
                <fullName>Final draft</fullName>
            </value>
            <value>
                <fullName>Draft Proposal</fullName>
            </value>
            <value>
                <fullName>Provide Project Details</fullName>
            </value>
            <value>
                <fullName>Contract Instructions</fullName>
            </value>
            <value>
                <fullName>Review by Research Office</fullName>
            </value>
            <value>
                <fullName>Panel Review</fullName>
            </value>
            <value>
                <fullName>HoS NOI Validation</fullName>
            </value>
            <value>
                <fullName>Pitch Session</fullName>
            </value>
            <value>
                <fullName>Peer review draft</fullName>
            </value>
            <value>
                <fullName>Peer review draft complete</fullName>
            </value>
            <value>
                <fullName>Review Contract</fullName>
            </value>
            <value>
                <fullName>Draft contract</fullName>
            </value>
            <value>
                <fullName>Approvals</fullName>
            </value>
            <value>
                <fullName>Formalise Contract</fullName>
            </value>
            <value>
                <fullName>Submission to Client</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Ready for Submission to Funding Body</fullName>
            </value>
            <value>
                <fullName>Submission to Funding Body</fullName>
                <label>Funding Body Submission</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Rejoinders</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BudgetLineItemDeleteLockDownTest.cls
@isTest
public class BudgetLineItemDeleteLockDownTest {
    
  
    public static testmethod void budgetLineItemDeleteLockDownTest() {

        
        Account portalAccount = TestUtility.newEmptyExternalAccount('TestAccount');
        insert portalAccount;

        //Contact portalContact = TestUtility.newContact(GlobalConstants.CONTACT_RECORD_TYPE_NAME_LTU_STAFF, portalAccount.Id);
        Contact portalContact = TestUtility.createContact(portalAccount.Id);
        insert portalContact;

        User portalUser;
        User thisUser = [ select Id from User where Id = :UserInfo.getUserId() ];
        
        System.runAs ( thisUser ) {

            Profile portalProfile = [SELECT Id FROM Profile WHERE Name = 'LTU Partner Community Login User' Limit 1];
            //UserRole portalRole = [SELECT Id FROM UserRole WHERE PortalType = 'Partner' LIMIT 1];
            portalUser = TestUtility.newUser('test', portalProfile.Id, null, portalContact.Id);
            
            System.debug(portalUser);

            insert portalUser;
        }

        Project_Proposal__c pp = TestUtility.newProjectProposal();
        pp.OwnerId = portalUser.Id;
        insert pp;
        
        Budget__c budget = TestUtility.newBudget(pp.Id);
        insert budget;
        
        Budget_Line_Item__c lineItem = TestUtility.newBudgetLineItem(budget.Id);
        insert lineItem;

        Object_Metadata__c deletionBlockerCustomSetting = new Object_Metadata__c(
            Name = 'Budget_Line_Item__c',
            I_RS_Enable_Deletion_Blocker__c = true,
            I_RS_Deletion_Blocker_Check_Formula__c = 'I_RS_Line_Item_Permission_Delete__c',
            I_RS_Deletion_Blocker_Error_Message__c = 'Cant delete this'
        );
        insert deletionBlockerCustomSetting;

        budget.I_RS_Status__c = 'Active';
        update budget;

        System.runAs(portalUser){

            try {

                Budget_Line_Item__c budgetLineItem = [select Id, I_RS_Line_Item_Permission_Delete__c from Budget_Line_Item__c];
                System.debug(budgetLineItem);
                delete budgetLineItem;

                System.assert(false, 'Budget Line Item has deleted when it shouldn\'t have');
            }
            catch (DMLException e){
                System.assert(
                    e.getMessage().contains('CUSTOM_VALIDATION_EXCEPTION'),
                    'On Budget Line Item delete, Exception has happened as expected but for a different reason from what is expected. Please investigate.'
                );
            }

        }

    }

}