force-app/main/default/objects/Account/fields/I_RS_Confidential__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Confidential__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hidden from Researcher Portal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/I_ST_Educational_Institution.recordType-meta.xml
<RecordType>
    <fullName>I_ST_Educational_Institution</fullName>
    <active>true</active>
    <description>An educational institution.</description>
    <label>Educational Institution</label>
</RecordType>

force-app/main/default/objects/AccountContactRelation/fields/I_RS_Manual__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Manual__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manual</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/I_RM_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Affiliation</description>
    <label>Affiliation</label>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_RS_Citizenship__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Citizenship__c</fullName>
    <label>Country of Citizenship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>I_RM_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/I_RS_Confidential__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Confidential__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Tick to prevent Contact from appearing in the Prime Researcher Portal</inlineHelpText>
    <label>Hidden from Researcher Portal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_RS_Deceased__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Deceased__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deceased</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_RS_Is_Organisation_Confidential__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Is_Organisation_Confidential__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Organisation Confidential?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_RS_Related_User__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Related_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Refers to the user record associated to the contact</description>
    <label>Related User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_ST_Calculate_Contact_Score__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Calculate_Contact_Score__c</fullName>
    <defaultValue>false</defaultValue>
    <label>I ST Calculate Contact Score</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_ST_Personal_Email__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Personal_Email__c</fullName>
    <description>Created to allow user to store personal email</description>
    <externalId>true</externalId>
    <inlineHelpText>The personal email for this person.</inlineHelpText>
    <label>Student Lead Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/I_RM_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Part of the remediation project to store different personas</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_IL_Sponsored__c.field-meta.xml
<CustomField>
    <fullName>I_IL_Sponsored__c</fullName>
    <description>Depicts whether a candidate is sponsored</description>
    <label>Sponsored</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Contact__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Contact__c</fullName>
    <description>The person/contact who this Affiliation relates to</description>
    <inlineHelpText>The person this affiliation relates to</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Affiliations</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Email__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Email__c</fullName>
    <description>Depicts Personal Email</description>
    <inlineHelpText>The personal email for this person.</inlineHelpText>
    <label>Personal Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Mobile_Phone__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Mobile_Phone__c</fullName>
    <description>Depicts affiliation&apos;s Mobile Phone number</description>
    <label>Mobile Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Role__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Role__c</fullName>
    <description>This represents the role of the affiliation</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Domestic Lead</fullName>
                <label>Student Lead (Dom)</label>
            </value>
            <value>
                <fullName>Applicant</fullName>
                <label>Student Applicant (Dom)</label>
            </value>
            <value>
                <fullName>La Trobe Staff</fullName>
            </value>
            <value>
                <fullName>School Representative</fullName>
                <label>Secondary School Representative</label>
            </value>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>External Contact</fullName>
            </value>
            <value>
                <fullName>HDR Student</fullName>
                <label>Graduate Researcher</label>
            </value>
            <value>
                <fullName>Student Lead (Int)</fullName>
            </value>
            <value>
                <fullName>Nominated Affiliation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <description>Indicates the status of the Affiliation.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>I_RM_Role__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>I_ST_Contact_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/L_PR_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Contact_Name__c</fullName>
    <label>Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_IL_Student_Lead_Int.recordType-meta.xml
<RecordType>
    <fullName>I_IL_Student_Lead_Int</fullName>
    <active>true</active>
    <description>New International Lead who can be a prospective student of La Trobe University</description>
    <label>Student Lead (Int)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_Lead.recordType-meta.xml
<RecordType>
    <fullName>I_RM_Lead</fullName>
    <active>true</active>
    <description>New Domestic Lead who is a prospective student of La Trobe University</description>
    <label>Student Lead (Dom)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/I_RM_Affiliation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Affiliation Settings</label>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_ST_BatchScoring__c/I_ST_BatchScoring__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>I_ST_BatchScoring</label>
</CustomObject>

force-app/main/default/objects/I_ST_BatchScoring__c/fields/I_ST_RecordType_SFIDs__c.field-meta.xml
<CustomField>
    <fullName>I_ST_RecordType_SFIDs__c</fullName>
    <description>Provide comma separated RecordTypeIds of Case object which is to be considered for Activity Scoring. To get the record type Ids =&gt; Navigate to Setup -&gt; Object Manager -&gt; Case -&gt; RecordTypes -&gt; Select the record type -&gt; copy the 18 digit Id from the URL</description>
    <label>I_ST_RecordType_SFIDs</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/I_RM_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Åland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Argentinian Antarctic Territory</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Australian Antarctic Territory</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas (the)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia (Plurinational State of)</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Saudi Arabia</fullName>
    </customValue>
    <customValue>
        <fullName>United States of America (the)</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/I_ST_Contact_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Admitted</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And LOA</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Not Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Considered</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Made</fullName>
    </customValue>
    <customValue>
        <fullName>Await Academic Advice</fullName>
    </customValue>
    <customValue>
        <fullName>Await Applicant Comms</fullName>
    </customValue>
    <customValue>
        <fullName>Await Further Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Awaiting Interview</fullName>
    </customValue>
    <customValue>
        <fullName>Await Required Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Escalated</fullName>
    </customValue>
    <customValue>
        <fullName>Make A Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make Alternate Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make An Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Nearing Completion</fullName>
    </customValue>
    <customValue>
        <fullName>Not Processed</fullName>
    </customValue>
    <customValue>
        <fullName>Not Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Lapsed</fullName>
    </customValue>
    <customValue>
        <fullName>Other Preference Offered</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Results</fullName>
    </customValue>
    <customValue>
        <fullName>Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <description>Global value set is created for lead(contact) object ST -51</description>
    <masterLabel>I_ST_Contact_Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContactTriggerHelperTest.cls
@IsTest
public class ContactTriggerHelperTest {
	
     public static string affiliationRecordTypeIds = I_ST_UnitTestUtilities.recordTypeIds(GlobalConstants.AFFILIATION_OBJECT_API_NAME,GlobalConstants.AFFILIATION_RECORD_TYPE_NAME_LEAD);
     public static string caseRecordTypeIds = I_ST_UnitTestUtilities.recordTypeIds(GlobalConstants.CASE_OBJECT_API_NAME,GlobalConstants.CASE_RECORD_TYPE_API_NAME_ENQUIRY);
     public static Id affiliationIntLeadRecordTypeId = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_IL_Student_Lead_Int').getRecordTypeId();

    @TestSetup
    static void setup() {  

        I_RM_Affiliation_Settings__c objAffiliationSettings = new I_RM_Affiliation_Settings__c(
            Name = 'I_RM_Inactive_Status',
            I_RM_Status__c = 'Inactive'
        );
        insert objAffiliationSettings;
        
        I_RM_Affiliation_Settings__c affSettings = (I_RM_Affiliation_Settings__c) TestUtility.newSObjectInstance(
            new Map<String, String> {
                'Name' => 'I_IL_Sponsored_by_Citizenship',
                'Value__c' => 'Saudi Arabia;Oman;United Arab Emirates;United Arab Emirates (the);Kuwait;Bahrain;Qatar',
                'I_RM_Status__c' => 'Coursework External Sponsorship;Graduate Research Scholarship;Graduate Research External Sponsorship;Other'
            },
            'I_RM_Affiliation_Settings__c'
        );
        insert affSettings;
               
        List<I_ST_BatchScoring__c> listBatchScoringSetting = I_ST_UnitTestUtilities.createBatchScoringCustomSetting(affiliationRecordTypeIds,20,caseRecordTypeIds,20,null,null);           
        insert listBatchScoringSetting;        
        
        Account tstAccount = TestUtility.newEmptyExternalAccount('testAccount');
        insert tstAccount;
        tstAccount.isPartner = True;
        update tstAccount;
        
        Contact researcherContact = new Contact(FirstName = 'test', LastName = 'Researcher', email = 'researcher@test.com');
        //researcherContact.AccountId = tstAccount.Id;
        insert researcherContact;

      /*  I_RM_Affiliation__c affliation = new I_RM_Affiliation__c();
        affliation.I_RM_Contact__c = researcherContact.Id;
        affliation.I_RM_Status__c = 'Not Qualified';
        affiliation.I_RM_Mobile_Phone__c ='0411111111';
        insert affliation;*/
        
         

        Profile researcherProfile = [SELECT Id FROM Profile WHERE Name='LTU Partner Community Login User'];

        User researcher;
        researcher = new User(Alias = 'research', Email='researcher@ltu.com.test', 
            EmailEncodingKey='UTF-8', LastName='researcher', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_AU', ProfileId = researcherProfile.Id, ContactId =  researcherContact.Id,
            TimeZoneSidKey='Australia/Sydney', UserName='researcher@ltu.com.test');
        insert researcher;
        
        researcherContact.I_RS_Related_User__c = researcher.Id;
        Update researcherContact;
        
         
        
        //Conor Langan IBM, Bluewolf 11/11/2020/////////////////
        //Id domesticLeadRecordTypeId = I_ST_BatchScoring__c.getValues('I_ST_ContactScoring').I_ST_RecordType_SFIDs__c.split(',')[0];
        Id affiliationDomesticLeadRecordTypeId = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Lead').getRecordTypeId();
        Contact newDomesticLead = new Contact(FirstName = 'test_unique1994', LastName = 'unique_test1994', 
                                              Email = 'test_unique1994@unique.com', I_ST_Personal_Email__c = 'test_unique1994@unique.com', MobilePhone = '0447173488');
        //ContactTriggerHandler.runCTEAlways = true;
        insert newDomesticLead;
        
        
        Id educationInstitutionRecordTypeId = [Select Id From RecordType Where DeveloperName = 'I_ST_Educational_Institution'].Id;
        Account fosterOrganisation = new Account(Name = 'fosterParent', RecordTypeId = educationInstitutionRecordTypeId);
        insert fosterOrganisation;
    } 
    
	@IsTest
    public static void testRelatedUserClear(){
        User researcher = [SELECT Id, ContactId, IsActive, IsPortalEnabled FROM User WHERE UserName = 'researcher@ltu.com.test' LIMIT 1];
        Contact researcherContact = [SELECT Id, Name, I_RS_Related_User__c from Contact WHERE Id = :researcher.ContactId LIMIT 1 ];
        System.assert(researcherContact.I_RS_Related_User__c == researcher.Id,  'Contact\'s Related user is not equal to user id');
        
        Test.startTest();
        researcher.IsActive = False;
        researcher.IsPortalEnabled = False;
        update researcher;
        Test.stopTest();
        
        researcherContact = [SELECT Id, Name, I_RS_Related_User__c from Contact WHERE Id = :researcher.ContactId LIMIT 1 ];
        System.assert(researcherContact.I_RS_Related_User__c == null,  'Contact\'s Related user is not cleared');
    }
    
       //Teja Yenduri IBM, Bluewolf 11/09/2021/////////////////
	/*@isTest
    public static void testmarkCalculateContactScoreToTrue(){
       
        List<Contact> domesticLeadContact = [SELECT Id, Name,MobilePhone,I_ST_Calculate_Contact_Score__c from Contact WHERE email = 'test_unique1994@unique.com' LIMIT 1 ];        
        
        try{
			Contact updateContact = new Contact();
            updateContact.id= domesticLeadContact[0].Id;
			updateContact.MobilePhone = '0440901788';
			test.startTest();
            update updateContact;
			test.StopTest();
        }
        catch (Exception e) {
            System.debug('>>> ERROR ='+e);
        }   
       // system.assertEquals(false, domesticLeadContact[0].I_ST_Calculate_Contact_Score__c);
    }*/
    
    @isTest
    public static void testDeleteContact(){
        User researcher = [SELECT Id, ContactId, IsActive, IsPortalEnabled FROM User WHERE UserName = 'researcher@ltu.com.test' LIMIT 1];
        Contact researcherContact = [SELECT Id, Name, I_RS_Related_User__c from Contact WHERE Id = :researcher.ContactId LIMIT 1 ];
        // AccountContactRelation acr = [SELECT Id, AccountId, ContactId, IsDirect, IsActive, I_RS_Manual__c FROM AccountContactRelation WHERE ContactId=:researcherContact.id and AccountID =:researcherContact.accountid];
        
        try{
            delete researcherContact;
        }
        catch (Exception e) {
            System.debug('>>> ERROR ='+e);
        }       
    }
    
    @isTest
    public static void testAccountCleanupDeleteWithCase(){
        
        
        Contact newDomesticLead = [Select Id, AccountId From Contact Where I_ST_Personal_Email__c = 'test_unique1994@unique.com'];
        
        //Lead account should be created via flow automation and associated to domestic lead
        Id paternalParentId = [Select Id FROM Account WHERE Id = :newDomesticLead.AccountId].Id;
        System.assert(paternalParentId != null);
        
        //Associate a case to Lead Account
        Case newCase = new Case(Subject = 'Test', AccountId = paternalParentId);
        insert newCase;
        
        //Delete test
        Test.startTest();
        delete newDomesticLead;
        
        //Lead Account should not delete as it has a case associated
        Account paternalParentDeleted = [Select Id, IsDeleted FROM Account WHERE Id = :paternalParentId ALL ROWS];
        System.assertEquals(paternalParentDeleted.IsDeleted, false);
        
        Test.stopTest();
    }
    
    @isTest
    public static void testAccountCleanupReparent(){
        
        Contact newDomesticLead = [Select Id, AccountId From Contact Where I_ST_Personal_Email__c = 'test_unique1994@unique.com'];
        
        //Lead account should be created via flow automation and associated to domestic lead
        Id paternalParentId = [Select Id FROM Account WHERE Id = :newDomesticLead.AccountId].Id;
        System.assert(paternalParentId != null);
        
        //Reparent Test
        Test.startTest();
        newDomesticLead.AccountId = [Select Id FROM Account WHERE Name = 'fosterParent'].Id;
        
        update newDomesticLead;
        
        Account paternalParentDeleted = [Select Id, IsDeleted FROM Account WHERE Id = :paternalParentId ALL ROWS];
        System.assertEquals(paternalParentDeleted.IsDeleted, true);
        
        Test.stopTest();
    }

    @isTest

    public static void setAffliationsToInactiveTest(){

        Contact researcherContact = [SELECT Id, Name, I_RS_Related_User__c from Contact LIMIT 1 ];

        researcherContact.I_RS_Deceased__c = True;
        update researcherContact;

    }
    
    //Added by Teja IBM on 21 January 2022 for LTU360-995  to cover createLeadOrganization methodin ContactTriggerHelper
    
    @isTest
    public static void testcreateLeadOrganizationWithoutAccount(){
        List<Contact> lstContacts = I_ST_UnitTestUtilities.createTestContactRecords(10,false);
        
        Test.startTest();
        	//ContactTriggerHandler.runCTEAlways = true;
        	insert lstContacts;        
            Contact objContact = [SELECT Id,AccountId,Name from Contact where FirstName = 'TestFirst1' limit 1];
            System.AssertEquals(objContact.AccountId != null,true,'An Account is Inserted for Contact.');
        Test.stopTest();       
        
    }

    @isTest 
    public static void updateConfidentialfieldTest(){
        Test.startTest();
        Account acc = TestUtility.newEmptyLTUAccount('testAcc1');
        acc.I_RS_Confidential__c = True;
        Insert acc;

        Contact con = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            AccountId = acc.Id,
            Email = System.now().millisecond() + 'test@test.com'
        );
        Insert con;
        con.I_RS_Is_Organisation_Confidential__c = False;
        update con;

        Test.stopTest();
    }
    
	//Added by Vanita Walia for LTU360-2031 update contact name on affiliations
    
    @isTest
    public static void updateContactNameonAffiliation(){
        Test.startTest();
        
        List<Contact> con = [Select Id,FirstName, LastName from Contact where FirstName ='test_unique1994'];
        if(!con.isEmpty()){ 
        	// create affiliation record for newDomesticLead contact
			List<I_RM_Affiliation__c> listLeadAffiliations = I_ST_UnitTestUtilities.createAffiliationRecords(affiliationRecordTypeIds,con[0].Id);
        	insert listLeadAffiliations; 
        
        	// update firstname and lastname for contact
        	con[0].FirstName = 'UpdateFirstName';
        	con[0].LastName = 'UpdateLastName';
        	if(!con.isEmpty()){
           		update con[0];
        	}
        }
        
        List<I_RM_Affiliation__c> affList = [Select Id, L_PR_Contact_Name__c from I_RM_Affiliation__c where I_RM_Contact__c =: con[0].Id];
        system.assertEquals(affList[0].L_PR_Contact_Name__c, 'UpdateFirstName UpdateLastName', 'Affiliation are updated');
        
        Test.stopTest();       
        
    }
    
    @isTest
    public static void setSponsoredFieldValue_Test(){
        
        Test.startTest();

        Account acc1 = (Account) TestUtility.newSObjectInstance(
            new Map<String, String> {
                'Name' => 'Test Account',
                'RecordTypeId' => Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(GlobalConstants.ACCOUNT_RECORD_TYPE_NAME_LTU_ORG_UNIT).getRecordTypeId()
            },
            'Account'
        );
        insert acc1;

        Contact cont1 = (Contact) TestUtility.newSObjectInstance(
            new Map<String, String> {
                'FirstName' => 'Test',
                'LastName' => 'Contact',
                'AccountId' => acc1.Id,
                'Email' => System.now().millisecond() + 'test@test.com', 
                'I_RS_Citizenship__c' => 'Saudi Arabia'
            },
            'Contact'
        );
        insert cont1;        
        
        
        I_RM_Affiliation__c aff1 = (I_RM_Affiliation__c) TestUtility.newSObjectInstance(
            new Map<String, String> {
                'RecordTypeId' => affiliationIntLeadRecordTypeId,
                'I_RM_Contact__c' => cont1.Id,
                'I_RM_Role__c' => 'Student Lead (Int)',
                'I_RM_Email__c' => 'caseoftypeenquiry@ibm.com.invalid',
                'I_RM_Status__c' => 'Not Qualified',
                'I_RM_Mobile_Phone__c' => '+61415822666'
            },
            'I_RM_Affiliation__c'
        );        
        insert aff1;

        System.assertEquals(
            'Yes', 
            [SELECT I_IL_Sponsored__c FROM I_RM_Affiliation__c WHERE Id = :aff1.Id].I_IL_Sponsored__c,
            'Expected Yes as the Country of residence matches one of the sponsorship countries'
        );

        cont1.I_RS_Citizenship__c = 'United States of America (the)';
        update cont1;
        System.assertEquals(
            'No', 
            [SELECT I_IL_Sponsored__c FROM I_RM_Affiliation__c WHERE Id = :aff1.Id].I_IL_Sponsored__c,
            'Expected No as the Country of residence doesn\'t match one of the sponsorship countries'
        );

        Test.StopTest();        
    }
}