force-app/main/default/objects/Account/fields/I_RS_Part_of_La_Trobe__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Part_of_La_Trobe__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Part of La Trobe</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/I_RS_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Proposed</fullName>
                <isActive>false</isActive>
                <label>Proposed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Budget__c/Budget__c.object-meta.xml
<CustomObject>
    <description>This is the summarised budget header details that goes for approval &amp; is maintained in system for any further progress, tracking or finance integration</description>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget__c/fields/I_RS_Amount__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Amount__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Project_Proposal__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Project_Proposal__c</fullName>
    <label>Project Proposal</label>
    <referenceTo>Project_Proposal__c</referenceTo>
    <relationshipLabel>Budgets</relationshipLabel>
    <relationshipName>Budgets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Status__c</fullName>
    <inlineHelpText>Draft: I&apos;m working on it; Active: This is the actual budget for the project; Superseded: Previous active versions.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Superseded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/Budget_Line_Item__c.object-meta.xml
<CustomObject>
    <description>This will capture the calculated budget line details from Budget Calculator tool. Please note that Budget Calculator will be a custom developed tool built &amp; integrated with Salesforce. Later the calculated values will be stored in this object.</description>
    <label>Budget Line Item</label>
    <nameField>
        <displayFormat>BLI-{00000}</displayFormat>
        <label>Budget Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Amount__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total Amount across all 7 years. Exclusive of GST.</inlineHelpText>
    <label>Total Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Budget__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Budget__c</fullName>
    <label>Budget</label>
    <referenceTo>Budget__c</referenceTo>
    <relationshipLabel>Budget Line Items</relationshipLabel>
    <relationshipName>Budget_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Category__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Equipment</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Field Work</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Current La Trobe staff</fullName>
            </value>
            <value>
                <fullName>Future La Trobe staff</fullName>
            </value>
            <value>
                <fullName>Research Assistant</fullName>
            </value>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Non-La Trobe researcher</fullName>
            </value>
            <value>
                <fullName>Personnel</fullName>
            </value>
            <value>
                <fullName>HDR Stipends</fullName>
            </value>
            <value>
                <fullName>Teaching Relief</fullName>
            </value>
            <value>
                <fullName>Field Research</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Cash External</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_In_Kind__c.field-meta.xml
<CustomField>
    <fullName>I_RS_In_Kind__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Tick for In-Kind. Untick for In-Cash.</inlineHelpText>
    <label>In Kind</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Organisation__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Budget Line Items</relationshipLabel>
    <relationshipName>Budget_Line_Items_Org</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Organisation_Being_Funded__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Organisation_Being_Funded__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>This is the &apos;Provided To&apos; field on the Budget calculator. Refers to the Organisation receiving funds as part of this Line Item</inlineHelpText>
    <label>Organisation Being Funded</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Budget Line Items (Organisation Being Funded)</relationshipLabel>
    <relationshipName>Budget_Line_Items_Orgs_Being_Funded</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Part_of_La_Trobe__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Part_of_La_Trobe__c</fullName>
    <formula>I_RS_Organisation__r.I_RS_Part_of_La_Trobe__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Part of La Trobe</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TBD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Year_1_Base_Salary__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Year_1_Base_Salary__c</fullName>
    <label>Year 1 Base Salary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/Year_1_Cost__c.field-meta.xml
<CustomField>
    <fullName>Year_1_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total Amount for this Budget Item over Year 1</inlineHelpText>
    <label>Year 1 Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/Year_2_Cost__c.field-meta.xml
<CustomField>
    <fullName>Year_2_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Year 2 Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/Year_3_Cost__c.field-meta.xml
<CustomField>
    <fullName>Year_3_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Year 3 Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/Year_4_Cost__c.field-meta.xml
<CustomField>
    <fullName>Year_4_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Year 4 Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/Year_5_Cost__c.field-meta.xml
<CustomField>
    <fullName>Year_5_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Year 5 Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/Year_6_Cost__c.field-meta.xml
<CustomField>
    <fullName>Year_6_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Year 6 Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/Year_7_Cost__c.field-meta.xml
<CustomField>
    <fullName>Year_7_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Year 7 Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Junction_Linkage__c/Junction_Linkage__c.object-meta.xml
<CustomObject>
    <description>If there is a linkage opportunity, this object will hold relationship between organisation and the Research Opportunity (Funding Scheme / Opportunity / Collaboration / Sub-Contract/Share)</description>
    <label>Funding Details</label>
    <nameField>
        <label>Funding Details Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Junction_Linkage__c/fields/I_RS_Amount_Suggested__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Amount_Suggested__c</fullName>
    <description>Amount requested with the funding organisation</description>
    <label>Amount Suggested</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Junction_Linkage__c/fields/I_RS_Awarded_to__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Awarded_to__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Organisation that has been awarded the funds</inlineHelpText>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Funding Details</relationshipLabel>
    <relationshipName>Junction_Linkage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Junction_Linkage__c/fields/I_RS_Project_Proposal__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Project_Proposal__c</fullName>
    <label>Project Proposal</label>
    <referenceTo>Project_Proposal__c</referenceTo>
    <relationshipName>Junction_Linkage</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Junction_Linkage__c/fields/I_RS_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Cancelled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Junction_Linkage__c/fields/I_RS_Year_1_Suggested_Amount__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Year_1_Suggested_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Year 1 Suggested Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Junction_Linkage__c/fields/I_RS_Year_2_Suggested_Amount__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Year_2_Suggested_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Year 2 Suggested Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Junction_Linkage__c/fields/I_RS_Year_3_Suggested_Amount__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Year_3_Suggested_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Year 3 Suggested Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Junction_Linkage__c/fields/I_RS_Year_4_Suggested_Amount__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Year_4_Suggested_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Year 4 Suggested Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Junction_Linkage__c/fields/I_RS_Year_5_Suggested_Amount__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Year_5_Suggested_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Year 5 Suggested Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Junction_Linkage__c/fields/I_RS_Year_6_Suggested_Amount__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Year_6_Suggested_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Year 6 Suggested Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Junction_Linkage__c/fields/I_RS_Year_7_Suggested_Amount__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Year_7_Suggested_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Year 7 Suggested Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/BudgetToFundingDetailSync.cls
public class BudgetToFundingDetailSync {

    //Note: Assumption is only one Budget will be passed in at a time in a visual workflow, but it is technically 
    //possible to pass in a small number of them without hitting limits

    @InvocableMethod(label='Sync Budget to Funding Details' 
    description='Extracts Budget Line Items and aggregates data in Project Proposal\'s Funding Detail records')
    public static void budgetToFundingDetailSync(List<Id> budgetIds) {

        System.debug('budgetToFundingDetailSync');
        
        List<Junction_Linkage__c> fundingDetailsToInsert = new List<Junction_Linkage__c>();
        
        List<Budget__c> budgets = [SELECT Id, I_RS_Project_Proposal__c, 
            (SELECT Id, I_RS_Organisation__c,I_RS_Organisation_being_funded__c
             FROM Budget_Line_Items__r) FROM Budget__c WHERE Id IN :budgetIds];
        
        removeOldFundingDetailsRecords(budgets);

        for (Budget__c budget : budgets){
            fundingDetailsToInsert.addAll(createFundingDetailsForBudget(budget));
        }

        if (!fundingDetailsToInsert.isEmpty())
            insert fundingDetailsToInsert;

    }


    static void removeOldFundingDetailsRecords(List<Budget__c> budgets){

        Set<Id> projectProposalIds = GlobalUtility.getParentIds(budgets, 'I_RS_Project_Proposal__c');

        delete [SELECT Id FROM Junction_Linkage__c WHERE I_RS_Project_Proposal__c IN :projectProposalIds];

    }


    static List<Junction_Linkage__c> createFundingDetailsForBudget(Budget__c budget){

        List<Junction_Linkage__c> fundingDetailsToInsert = new List<Junction_Linkage__c>();

        fundingDetailsToInsert.addAll(
            createFundingDetailsForOrgs(
                budget, 
                'I_RS_Organisation__c',
                'I_RS_Organisation__r', 
                'Budget_Line_Items_Org__r'));

        fundingDetailsToInsert.addAll(
            createFundingDetailsForOrgs(
                budget, 
                'I_RS_Organisation_Being_Funded__c',
                'I_RS_Organisation_Being_Funded__r', 
                'Budget_Line_Items_Orgs_Being_Funded__r'));

        return fundingDetailsToInsert;

    }


    static List<Junction_Linkage__c> createFundingDetailsForOrgs(
                                        Budget__c budget, 
                                        String bliToOrgLookupFieldName,
                                        String bliToOrgRelationshipName, 
                                        String orgToBLIRelationship){

        List<Junction_Linkage__c> fundingDetailsToInsert = new List<Junction_Linkage__c>();
        
        Set<Id> budgetIds = new Set<Id>{budget.Id};
        Set<Id> allOrgIds = GlobalUtility.getParentIds(budget.Budget_Line_Items__r, bliToOrgLookupFieldName);
        
        List<Account> orgsAndBLIs = getOrgAndBLICombinations(orgToBLIRelationship, budgetIds, allOrgIds);
    
        for (Account org : orgsAndBLIs){
    
            List<Junction_Linkage__c> fundingDetailsToInsertForOrg = createFundingDetailsForOrg(org, orgToBLIRelationship, bliToOrgRelationshipName);
            fundingDetailsToInsert.addAll(fundingDetailsToInsertForOrg);

        }

        return fundingDetailsToInsert;

    }


    static List<Junction_Linkage__c> createFundingDetailsForOrg(Account parentOrg, 
                                                                String orgToBLIRelationshipName, 
                                                                String bliToOrgRelationshipName){

        List<Junction_Linkage__c> fundingDetailsToInsertForOrg = new List<Junction_Linkage__c>();

        Map<String, Junction_Linkage__c> temporaryFundingDetailsMap = new Map<String, Junction_Linkage__c>();
        
        for (Budget_Line_Item__c funderBudgetLineItem : (List<Budget_Line_Item__c>) parentOrg.getSObjects(orgToBLIRelationshipName)){

            Junction_Linkage__c fundingDetailForBLI;
            String fundingDetailBucketName = getBucketName(funderBudgetLineItem, bliToOrgRelationshipName);

            if (fundingDetailBucketName != null) {

                fundingDetailForBLI = temporaryFundingDetailsMap.get(fundingDetailBucketName);
                if (fundingDetailForBLI == null){
                    fundingDetailForBLI = createNewFundingDetail(funderBudgetLineItem, bliToOrgRelationshipName, fundingDetailBucketName);
                }
                assignVariablesBasedOnFundingDetailType(fundingDetailForBLI, funderBudgetLineItem, fundingDetailBucketName, bliToOrgRelationshipName);
                System.debug('fundingDetailForBLI '+fundingDetailForBLI);
                


                incrementFundingDetailBasedOnBLI(fundingDetailForBLI, funderBudgetLineItem);

                temporaryFundingDetailsMap.put(fundingDetailBucketName, fundingDetailForBLI);

                System.debug('temporaryFundingDetailsMap '+temporaryFundingDetailsMap);

            }

        }

        for (Junction_Linkage__c fundingDetailToInsert : temporaryFundingDetailsMap.values()){
            System.debug('fundingDetailToInsert '+fundingDetailToInsert);
            fundingDetailsToInsertForOrg.add(fundingDetailToInsert);
        }
        System.debug('fundingDetailsToInsertForOrg '+fundingDetailsToInsertForOrg);

        return fundingDetailsToInsertForOrg;

    }



    static List<Account> getOrgAndBLICombinations(String budgetChildRelationshipName, Set<Id> budgetIds, Set<Id> orgIds){

        System.debug('getOrgAndBLICombinations');

        String query = 
            'SELECT Id, Name, I_RS_Part_of_La_trobe__c, '+
                '(SELECT '+
                    'I_RS_Budget__c, Id, I_RS_In_Kind__c, I_RS_Category__c,'+
                    'I_RS_Year_1_Base_Salary__c, Year_1_Cost__c,'+
                    'Year_2_Cost__c,'+
                    'Year_3_Cost__c,'+
                    'Year_4_Cost__c,'+
                    'Year_5_Cost__c,'+
                    'Year_6_Cost__c,'+
                    'Year_7_Cost__c,'+
                    'I_RS_Amount__c,'+
                    'I_RS_Budget__r.I_RS_Project_Proposal__c,'+
                    'I_RS_Organisation__c, I_RS_Organisation__r.Name, I_RS_Organisation__r.I_RS_Part_Of_La_Trobe__c,'+
                    'I_RS_Organisation_Being_Funded__c, I_RS_Organisation_Being_Funded__r.Name,'+
                        'I_RS_Organisation_Being_Funded__r.I_RS_Part_Of_La_Trobe__c '+
                'FROM '+budgetChildRelationshipName+' WHERE I_RS_Budget__c IN :budgetIds) '+
                'FROM Account WHERE Id IN :orgIds';

        System.debug('query '+query);
        List<Account> orgAndBLICombination = (List<Account>) Database.query(query);
        System.debug('org '+orgAndBLICombination);
        for (Account org : orgAndBLICombination){
            System.debug('blis '+org.getSObjects(budgetChildRelationshipName));
        }
        return orgAndBLICombination;

    }


    static String getBucketName(Budget_Line_Item__c funderBudgetLineItem, String bliToOrgRelationshipName) {

        Account funder = (Account) funderBudgetLineItem.getSObject(bliToOrgRelationshipName);
        String fundingDetailBucketName = null;

        //Provided To
        if (bliToOrgRelationshipName == 'I_RS_Organisation_Being_Funded__r'){
            fundingDetailBucketName = 'Provided To';

        }
        //Funder
        else if (bliToOrgRelationshipName == 'I_RS_Organisation__r'){
            if (funder.I_RS_Part_of_La_Trobe__c){

                if (!funderBudgetLineItem.I_RS_In_Kind__c){

                    if (funderBudgetLineItem.I_RS_Category__c != 'Cash External'){
                        fundingDetailBucketName = 'La Trobe Internal Cash';
                    }
                    else {
                        fundingDetailBucketName = 'La Trobe External Cash';
                    }

                }
                else {

                    if (funderBudgetLineItem.I_RS_Category__c != 'Cash External'){
                        fundingDetailBucketName = 'La Trobe In-Kind';
                    }
                    else {
                        //Do Nothing?
                    }

                }

            }
            else {

                //if (!funderBudgetLineItem.I_RS_In_Kind__c){ 
                    fundingDetailBucketName = 'External';
                //}

            }
        }
        System.debug('fundingDetailBucketName '+fundingDetailBucketName);

        return fundingDetailBucketName;

    }

    

    //Could probably outsource most of these to field defaults?
    static Junction_Linkage__c createNewFundingDetail(Budget_Line_Item__c budgetLineItem, 
                                                    String bliToOrgRelationshipName, 
                                                    String fundingDetailBucketName){

        Junction_Linkage__c newFundingDetail = new Junction_Linkage__c(
            I_RS_Awarded_To__c = (Id) budgetLineItem.getSObject(bliToOrgRelationshipName).get('Id'),
            I_RS_Project_Proposal__c = budgetLineItem.I_RS_Budget__r.I_RS_Project_Proposal__c,
            I_RS_Status__c = 'Not Cancelled',
            I_RS_Year_1_Suggested_Amount__c = 0,
            I_RS_Year_2_Suggested_Amount__c = 0,
            I_RS_Year_3_Suggested_Amount__c = 0,
            I_RS_Year_4_Suggested_Amount__c = 0,
            I_RS_Year_5_Suggested_Amount__c = 0,
            I_RS_Year_6_Suggested_Amount__c = 0,
            I_RS_Year_7_Suggested_Amount__c = 0,
            I_RS_Amount_Suggested__c = 0
        );
        System.debug('newFundingDetail '+newFundingDetail);
        return newFundingDetail;

    }


    static void incrementFundingDetailBasedOnBLI(Junction_Linkage__c fundingDetailForBLI, 
                                                Budget_Line_Item__c funderBudgetLineItem){

        System.debug('incrementFundingDetailsBasedOnBLI');
        System.debug('fundingDetailForBLI '+fundingDetailForBLI);
        System.debug('funderBudgetLineItem '+funderBudgetLineItem);

        fundingDetailForBLI.I_RS_Year_1_Suggested_Amount__c += funderBudgetLineItem.Year_1_Cost__c;
        fundingDetailForBLI.I_RS_Year_2_Suggested_Amount__c += funderBudgetLineItem.Year_2_Cost__c;
        fundingDetailForBLI.I_RS_Year_3_Suggested_Amount__c += funderBudgetLineItem.Year_3_Cost__c;
        fundingDetailForBLI.I_RS_Year_4_Suggested_Amount__c += funderBudgetLineItem.Year_4_Cost__c;
        fundingDetailForBLI.I_RS_Year_5_Suggested_Amount__c += funderBudgetLineItem.Year_5_Cost__c;
        fundingDetailForBLI.I_RS_Year_6_Suggested_Amount__c += funderBudgetLineItem.Year_6_Cost__c;
        fundingDetailForBLI.I_RS_Year_7_Suggested_Amount__c += funderBudgetLineItem.Year_7_Cost__c;

        fundingDetailForBLI.I_RS_Amount_Suggested__c += funderBudgetLineItem.I_RS_Amount__c;

    }
    

    


    static Junction_Linkage__c assignVariablesBasedOnFundingDetailType(Junction_Linkage__c fundingDetail, 
                                                                        Budget_Line_Item__c budgetLineItem, 
                                                                        String bucketName, 
                                                                        String bliToOrgRelationshipName){

        System.debug('assignVariablesBasedOnFundingDetailType');

        String orgName = (String) budgetLineItem.getSObject(bliToOrgRelationshipName).get('Name');

         switch on (bucketName){
             when 'La Trobe Internal Cash' {
                fundingDetail.Name = orgName + ' Internal Cash';
                fundingDetail.I_RS_Relationship_Type__c = bucketName;
             }
             when 'La Trobe External Cash' {
                fundingDetail.Name = orgName + ' External Cash';
                fundingDetail.I_RS_Relationship_Type__c = bucketName;
             }
             when 'La Trobe In-Kind' {
                fundingDetail.Name = orgName + ' In-Kind';
                fundingDetail.I_RS_Relationship_Type__c = bucketName;
             }
             when 'Provided To' {
                 fundingDetail.Name = 'Provided To ' + orgName;
                 fundingDetail.I_RS_Relationship_Type__c = 'Other Organisation';
             }
             //In cash where Funder is external
             when else {
                 fundingDetail.Name = orgName;
                 fundingDetail.I_RS_Relationship_Type__c = 'Funding Body';
             }

         }
   
        System.debug('fundingDetail '+fundingDetail);
         return fundingDetail;

    }



    
}