force-app/main/default/objects/Account/fields/I_RS_Maximum_Allowed_On_Cost__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Maximum_Allowed_On_Cost__c</fullName>
    <defaultValue>0.3574</defaultValue>
    <label>Maximum Allowed On-Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Budget__c/Budget__c.object-meta.xml
<CustomObject>
    <description>This is the summarised budget header details that goes for approval &amp; is maintained in system for any further progress, tracking or finance integration</description>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget__c/fields/I_RS_Actual_Non_Salary_Overhead__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Actual_Non_Salary_Overhead__c</fullName>
    <inlineHelpText>The percentage applied to non-salary items to cover the La Trobe operating costs such as infrastructure, facilities and services.</inlineHelpText>
    <label>Actual Non-Salary Overhead</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Actual_Overhead__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Actual_Overhead__c</fullName>
    <inlineHelpText>The percentage overhead applied to researcher salary to cover La Trobe infrastructure, facilities and services.</inlineHelpText>
    <label>Actual Salary Overhead</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Actual_Profit__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Actual_Profit__c</fullName>
    <inlineHelpText>The percentage applied to researcher salary to be returned to the university/researcher.</inlineHelpText>
    <label>Actual Salary Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Actual_Rate_Type__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Actual_Rate_Type__c</fullName>
    <inlineHelpText>The type of funding being applied for to determine the appropriate overhead and profit rates.</inlineHelpText>
    <label>Actual Project Rate</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Research Collaboration</fullName>
            </value>
            <value>
                <fullName>Research Consultancy (Collaborative)</fullName>
            </value>
            <value>
                <fullName>Research Consultancy (Commercial)</fullName>
            </value>
            <value>
                <fullName>Non-Research Consultancy</fullName>
            </value>
            <value>
                <fullName>Grant</fullName>
            </value>
            <value>
                <fullName>Grant with Overheads</fullName>
            </value>
            <value>
                <fullName>Scholarship</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Daily_On_Costs__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Daily_On_Costs__c</fullName>
    <inlineHelpText>On-costs include payroll tax, workcover and superannuation</inlineHelpText>
    <label>Daily On-Costs</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Daily_Overheads__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Daily_Overheads__c</fullName>
    <inlineHelpText>Daily Overheads are indirect costs, for example legal, insurance, electricity costs, etc.</inlineHelpText>
    <label>Daily Overheads</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Daily_Profits__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Daily_Profits__c</fullName>
    <label>Daily Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Daily_Salary__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Daily_Salary__c</fullName>
    <inlineHelpText>Daily Charge Out Rate for the Funder</inlineHelpText>
    <label>Daily Salary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Lead_Chief_Investigator__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Lead_Chief_Investigator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Example Rate For</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Budgets</relationshipLabel>
    <relationshipName>Budgets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Maximum_Allowed_On_Cost__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Maximum_Allowed_On_Cost__c</fullName>
    <inlineHelpText>Maximum allowable on-cost rate set by Funder.</inlineHelpText>
    <label>Maximum Allowed On-Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Overhead__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Overhead__c</fullName>
    <inlineHelpText>Default salary based on the type of funding</inlineHelpText>
    <label>Default Salary Overhead</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Profit__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Profit__c</fullName>
    <inlineHelpText>Default salary margin based on the type of funding</inlineHelpText>
    <label>Default Salary Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_RS_Salary_Grade__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Salary_Grade__c</fullName>
    <label>Salary Grade (HR)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Level A 1</fullName>
            </value>
            <value>
                <fullName>Level A 2</fullName>
            </value>
            <value>
                <fullName>Level A 3</fullName>
            </value>
            <value>
                <fullName>Level A 4</fullName>
            </value>
            <value>
                <fullName>Level A 5</fullName>
            </value>
            <value>
                <fullName>Level A 6</fullName>
            </value>
            <value>
                <fullName>Level A 7</fullName>
            </value>
            <value>
                <fullName>Level A 8</fullName>
            </value>
            <value>
                <fullName>Level B 1</fullName>
            </value>
            <value>
                <fullName>Level B 2</fullName>
            </value>
            <value>
                <fullName>Level B 3</fullName>
            </value>
            <value>
                <fullName>Level B 4</fullName>
            </value>
            <value>
                <fullName>Level B 5</fullName>
            </value>
            <value>
                <fullName>Level B 6</fullName>
            </value>
            <value>
                <fullName>Level C 1</fullName>
            </value>
            <value>
                <fullName>Level C 2</fullName>
            </value>
            <value>
                <fullName>Level C 3</fullName>
            </value>
            <value>
                <fullName>Level C 4</fullName>
            </value>
            <value>
                <fullName>Level C 5</fullName>
            </value>
            <value>
                <fullName>Level C 6</fullName>
            </value>
            <value>
                <fullName>Level D 1</fullName>
            </value>
            <value>
                <fullName>Level D 2</fullName>
            </value>
            <value>
                <fullName>Level D 3</fullName>
            </value>
            <value>
                <fullName>Level D 4</fullName>
            </value>
            <value>
                <fullName>Level E 1</fullName>
            </value>
            <value>
                <fullName>HEO1-1</fullName>
            </value>
            <value>
                <fullName>HEO1-2</fullName>
            </value>
            <value>
                <fullName>HEO1-3</fullName>
            </value>
            <value>
                <fullName>HEO1-4</fullName>
            </value>
            <value>
                <fullName>HEO2-1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/On_Cost_Default_Values__c/fields/I_RS_Maximum_Allowed_On_Cost__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Maximum_Allowed_On_Cost__c</fullName>
    <label>Maximum Allowed On-Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Overheads_and_Profit_Default_Values__c/Overheads_and_Profit_Default_Values__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Overheads and Profit Default Values</description>
    <label>Overheads and Profit Default Values</label>
</CustomObject>

force-app/main/default/objects/Overheads_and_Profit_Default_Values__c/fields/I_RS_Non_Salary_Overhead__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Non_Salary_Overhead__c</fullName>
    <label>Non-Salary Overhead</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Overheads_and_Profit_Default_Values__c/fields/I_RS_Overhead__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Overhead__c</fullName>
    <label>Overhead %</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Overheads_and_Profit_Default_Values__c/fields/I_RS_Profit__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Profit__c</fullName>
    <label>Profit %</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Overheads_and_Profit_Default_Values__c/fields/I_RS_Rate_Type__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Rate_Type__c</fullName>
    <label>Rate Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Proposal__c/Project_Proposal__c.object-meta.xml
<CustomObject>
    <description>Project Proposal: An application for funding either through a grant request, a tender response, or a contract proposal.
Project: The work that is undertaken to satisfy a commitment made to a funding body or client.  The commitment is likely to be a contract (and possible variations) resulting from the acceptance of a project proposal.  This occurs after a grant, contract of philanthropic donation has been awarded.</description>
    <label>Project Proposal</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Proposal__c/fields/I_RS_Lead_Chief_Investigator__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Lead_Chief_Investigator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Chief Investigator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Project Proposals</relationshipLabel>
    <relationshipName>Project_Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Salary_Table__c/Salary_Table__c.object-meta.xml
<CustomObject>
    <label>Salary Table</label>
    <nameField>
        <label>Salary Grade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salary Table</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/BudgetRateHelperTest.cls
@isTest
public class BudgetRateHelperTest {

    public static testmethod void budgetRateHelperTest(){
        
        //LCI
        Account org = TestUtility.newEmptyExternalAccount('Test Account');
        insert org;
        
        //Contact contact = TestUtility.newContact(GlobalConstants.CONTACT_RECORD_TYPE_NAME_LTU_STAFF, org.Id);
        Contact contact = TestUtility.createContact(org.Id);
        contact.I_RS_Salary_Grade__c = 'TEST 1';
        insert contact;
        
        //CUSTOM SETTINGS
        insert new On_Cost_Default_Values__c(
            Name = 'La Trobe University',
            I_RS_Maximum_Allowed_On_Cost__c = 35.75
        );

        insert new Overheads_and_Profit_Default_Values__c(
            Name = 'Non-Research Consultancy',
            I_RS_Rate_Type__c = 'Non-Research Consultancy', 
            I_RS_Overhead__c = 10, 
            I_RS_Profit__c = 10, 
            I_RS_Non_Salary_Overhead__c = 10
        );
        
        Salary_Table__c salaryTable = TestUtility.newSalaryTable('TEST', 1, Date.today().Year() + '', 110000);
        insert salaryTable;
        
        //PROEJCT PROPOSAL AND BUDGET
        Project_Proposal__c projectProposal = TestUtility.newProjectProposal();
        projectProposal.I_RS_Lead_Chief_Investigator__c = contact.Id;
        insert projectProposal;
        
        
        Budget__c budget = TestUtility.newBudget(projectProposal.Id);
        insert budget;
        
        budget.I_RS_Actual_Rate_Type__c = 'Non-Research Consultancy';
        budget.I_RS_Actual_Overhead__c = 0;
        budget.I_RS_Actual_Profit__c = 0;
        budget.I_RS_Actual_Non_Salary_Overhead__c = 0;
        
        budget.I_RS_Maximum_Allowed_On_Cost__c = 35;
		budget.I_RS_Actual_Overhead__c = 0;
		budget.I_RS_Actual_Profit__c = 0; 
		budget.I_RS_Actual_Non_Salary_Overhead__c = 0;
        
        update budget;
        
        Budget__c[] budgetList = new List<Budget__c>{budget};
            
        
    
    
        //APPLY METHODS ON DATA - VERIFY RECORD HAS CHANGED
		budgetList = BudgetRateHelper.provideActualRatesBasedOnRateType(budgetList);
        
		budgetList = BudgetRateHelper.provideDailyChargeoutRates_Aura(budgetList);
        
        budget = budgetList[0];
        
        System.assert(budget.I_RS_Actual_Overhead__c > 0);
        System.assert(budget.I_RS_Actual_Profit__c > 0);
        System.assert(budget.I_RS_Actual_Non_Salary_Overhead__c > 0);
        
        System.assert(budget.I_RS_Daily_On_Costs__c > 0);
        System.assert(budget.I_RS_Daily_Overheads__c > 0);
        System.assert(budget.I_RS_Daily_Profits__c > 0);
        System.assert(budget.I_RS_Daily_Salary__c > 0);

        
        //NOW REMOVE SALARY TABLE - THIS WILL CAUSE DAILY FIELDS TO BECOME 0
        delete salaryTable;
        
        budgetList = BudgetRateHelper.provideDailyChargeoutRates_Aura(budgetList);
        
        budget = budgetList[0];
        
        System.assert(budget.I_RS_Daily_On_Costs__c == 0);
        System.assert(budget.I_RS_Daily_Overheads__c == 0);
        System.assert(budget.I_RS_Daily_Profits__c == 0);
        System.assert(budget.I_RS_Daily_Salary__c == 0);

        
    }
    
}