force-app/main/default/objects/Account/fields/I_RS_Type_of_Organisation__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Type_of_Organisation__c</fullName>
    <label>Organisation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SME (small to medium enterprise)</fullName>
            </value>
            <value>
                <fullName>Government – International</fullName>
            </value>
            <value>
                <fullName>Government – Federal</fullName>
            </value>
            <value>
                <fullName>Government – State</fullName>
            </value>
            <value>
                <fullName>Government – Local</fullName>
            </value>
            <value>
                <fullName>Large Corporate – Australian</fullName>
            </value>
            <value>
                <fullName>Large Corporate – Multinational</fullName>
            </value>
            <value>
                <fullName>Large Corporate</fullName>
            </value>
            <value>
                <fullName>Non-government organisation (NGO)</fullName>
            </value>
            <value>
                <fullName>Not for profit</fullName>
            </value>
            <value>
                <fullName>Publicly funded research organisation (PRFO)</fullName>
            </value>
            <value>
                <fullName>Cooperative Research Centre (CRC)</fullName>
            </value>
            <value>
                <fullName>Hospitals</fullName>
            </value>
            <value>
                <fullName>Grant bodies</fullName>
            </value>
            <value>
                <fullName>Trusts and Foundations</fullName>
            </value>
            <value>
                <fullName>Funds / Venture Capital</fullName>
            </value>
            <value>
                <fullName>Start-ups</fullName>
            </value>
            <value>
                <fullName>Schools &amp; Higher Education</fullName>
            </value>
            <value>
                <fullName>Business Organisation</fullName>
            </value>
            <value>
                <fullName>LTU Partners</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
                <isActive>false</isActive>
                <label>Government</label>
            </value>
            <value>
                <fullName>Private Company</fullName>
                <isActive>false</isActive>
                <label>Private Company</label>
            </value>
            <value>
                <fullName>Public Company</fullName>
                <isActive>false</isActive>
                <label>Public Company</label>
            </value>
            <value>
                <fullName>Unincorporated Centre/Institute</fullName>
                <isActive>false</isActive>
                <label>Unincorporated Centre/Institute</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/L_PR_Closed_Reason__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Closed_Reason__c</fullName>
    <description>Reason for closed</description>
    <label>Closed Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/L_PR_Domestic_International__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Domestic_International__c</fullName>
    <label>Domestic/International</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>Domestic &amp; International</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/I_RS_External_Organisation.recordType-meta.xml
<RecordType>
    <fullName>I_RS_External_Organisation</fullName>
    <active>true</active>
    <label>External Organisation</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/I_RS_La_Trobe_Organisation_Unit.recordType-meta.xml
<RecordType>
    <fullName>I_RS_La_Trobe_Organisation_Unit</fullName>
    <active>true</active>
    <label>La Trobe Organisation Unit</label>
</RecordType>

force-app/main/default/objects/L_PR_Idea__c/L_PR_Idea__c.object-meta.xml
<CustomObject>
    <description>Idea/ Lead object being used for PRM Application</description>
    <label>PRM Lead</label>
    <nameField>
        <label>Lead Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PRM Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/L_PR_Idea__c/fields/L_PR_Closed_Reason__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Closed_Reason__c</fullName>
    <description>Text field to describe why the Lead/Idea did not qualify/succeed</description>
    <label>Closed Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/L_PR_Idea__c/fields/L_PR_Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Lead_Status__c</fullName>
    <description>Indicates the progress of the Lead/Idea.</description>
    <label>Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Open – Contacted</fullName>
            </value>
            <value>
                <fullName>Open – Unqualified</fullName>
            </value>
            <value>
                <fullName>Open – Qualified</fullName>
            </value>
            <value>
                <fullName>Closed – Converted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/L_PR_Idea__c/fields/L_PR_Location__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Location__c</fullName>
    <description>Identifies Lead/Idea location</description>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/L_PR_Idea__c/fields/L_PR_Organisation__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is a reference to related External Organisation or Educational Institution.</description>
    <label>Organisation Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>I_RS_External_Organisation</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>I_ST_Educational_Institution</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PRM Leads</relationshipLabel>
    <relationshipName>PRM_Ideas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/L_PR_Idea__c/fields/L_PR_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Sub_Type__c</fullName>
    <description>Sub Type field provides further  categorisation/ classification list based on the type for this Lead/Idea</description>
    <label>Lead Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>L_PR_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>L_PR_Sub_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/L_PR_Idea__c/fields/L_PR_Type__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Type__c</fullName>
    <description>Type field provides a categorisation/ classification  list for this Lead/Idea.</description>
    <label>Lead Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>L_PR_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/L_PR_Idea_Organisation__c/L_PR_Idea_Organisation__c.object-meta.xml
<CustomObject>
    <description>Junction object to capture relationship between Lead/Idea and Organisations</description>
    <label>Lead Organisation</label>
    <nameField>
        <displayFormat>IO-{000000}</displayFormat>
        <label>PRM Lead Organisation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Organisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/L_PR_Idea_Organisation__c/fields/L_PR_Idea__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Idea__c</fullName>
    <label>PRM Lead</label>
    <referenceTo>L_PR_Idea__c</referenceTo>
    <relationshipLabel>Lead Organisations</relationshipLabel>
    <relationshipName>Lead_Organisations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/L_PR_Idea_Organisation__c/fields/L_PR_LeadStatus__c.field-meta.xml
<CustomField>
    <fullName>L_PR_LeadStatus__c</fullName>
    <label>Lead Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/L_PR_Idea_Organisation__c/fields/L_PR_Organisation__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Organisation__c</fullName>
    <label>Organisation</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <errorMessage>You can only select External Organisation, Educational Institution or La Trobe Organisation Unit</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>La Trobe Organisation Unit</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>External Organisation</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Educational Institution</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Lead Organisations</relationshipLabel>
    <relationshipName>Idea_Organisations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/L_PR_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Education and Students</fullName>
    </customValue>
    <customValue>
        <fullName>Infrastructure &amp; Resources</fullName>
    </customValue>
    <customValue>
        <fullName>Innovation Ecosystem</fullName>
    </customValue>
    <customValue>
        <fullName>Research and Innovation</fullName>
    </customValue>
    <description>This picklist value set provides a categorisation/ classification  list for this Lead/Idea and opportunity.</description>
    <masterLabel>L_PR_Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/L_PR_Idea_OrganisationTriggerHandlerTest.cls
@isTest
public class L_PR_Idea_OrganisationTriggerHandlerTest{

    public static Id acctEORecType = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('I_RS_External_Organisation').getRecordTypeId();
    public static Id acctLARecType = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('I_RS_La_Trobe_Organisation_Unit').getRecordTypeId();

    @TestSetup
    static void makeData(){
        
        Account acc = New Account();
        acc.Name = 'Test Acc1';
        acc.L_PR_Domestic_International__c = 'Domestic';
        acc.I_RS_Type_of_Organisation__c = 'Schools & Higher Education';
        acc.RecordTypeId = acctEORecType;
        insert acc;

        L_PR_Idea__c idea = New L_PR_Idea__c();
        idea.Name ='Test Lead1';
        idea.L_PR_Type__c = 'Research and Innovation';
        idea.L_PR_Sub_Type__c ='Access to equipment';
        idea.L_PR_Location__c = 'Domestic';
        idea.L_PR_Lead_Status__c = 'Open';
        idea.L_PR_Organisation__c = acc.Id;
        insert idea;
    }

    @isTest 
    public static void updateLeadStatusOnIdeaOrgJunction(){

        Test.startTest();
        Account[] acc = [Select Id, Name, L_PR_Domestic_International__c from Account ];
        acc[0].RecordTypeId = acctEORecType;
        update acc;
        L_PR_Idea__c[] idea = [Select Id, Name from L_PR_Idea__c];

        L_PR_Idea_Organisation__c ideaOrg = New L_PR_Idea_Organisation__c();
        ideaOrg.L_PR_Organisation__c = acc[0].Id;
        ideaOrg.L_PR_Idea__c = idea[0].Id;
        insert ideaOrg;

        L_PR_Idea_Organisation__c[] ideaOegJ = [Select Id, L_PR_LeadStatus__c from L_PR_Idea_Organisation__c];
        Test.stopTest();
        system.debug('@@@ideaOegJ'+ ideaOegJ);
        System.assertEquals('Open', ideaOegJ[0].L_PR_LeadStatus__c);
    }

    @isTest 
    public static void updateLeadStatusOnIdeaOrgJunction2(){

        Test.startTest();
        Account[] acc = [Select Id, Name, L_PR_Domestic_International__c from Account ];
        acc[0].RecordTypeId = acctEORecType;
        update acc;
        L_PR_Idea__c[] idea = [Select Id, Name from L_PR_Idea__c];

        L_PR_Idea_Organisation__c ideaOrg = New L_PR_Idea_Organisation__c();
        ideaOrg.L_PR_Organisation__c = acc[0].Id;
        ideaOrg.L_PR_Idea__c = idea[0].Id;
        insert ideaOrg;
        L_PR_Idea_Organisation__c[] ideaOegJ = [Select Id, L_PR_LeadStatus__c from L_PR_Idea_Organisation__c];
        system.debug('@@@222ideaOegJ'+ ideaOegJ[0].L_PR_LeadStatus__c);
        idea[0].L_PR_Lead_Status__c = 'Closed';
        idea[0].L_PR_Closed_Reason__c ='Test';
        update idea;

        L_PR_Idea_Organisation__c[] ideaOegJ2 = [Select Id, L_PR_LeadStatus__c from L_PR_Idea_Organisation__c];
        Test.stopTest();
        system.debug('@@@222ideaOegJ2'+ ideaOegJ2[0].L_PR_LeadStatus__c);
        System.assertEquals('Closed', ideaOegJ2[0].L_PR_LeadStatus__c);
    }
}