force-app/main/default/objects/Account/fields/I_RS_Maximum_Allowed_On_Cost__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Maximum_Allowed_On_Cost__c</fullName>
    <defaultValue>0.3574</defaultValue>
    <label>Maximum Allowed On-Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Budget__c/Budget__c.object-meta.xml
<CustomObject>
    <description>This is the summarised budget header details that goes for approval &amp; is maintained in system for any further progress, tracking or finance integration</description>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget__c/fields/I_RS_Actual_Non_Salary_Overhead__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Actual_Non_Salary_Overhead__c</fullName>
    <inlineHelpText>The percentage applied to non-salary items to cover the La Trobe operating costs such as infrastructure, facilities and services.</inlineHelpText>
    <label>Actual Non-Salary Overhead</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Actual_Overhead__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Actual_Overhead__c</fullName>
    <inlineHelpText>The percentage overhead applied to researcher salary to cover La Trobe infrastructure, facilities and services.</inlineHelpText>
    <label>Actual Salary Overhead</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Actual_Profit__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Actual_Profit__c</fullName>
    <inlineHelpText>The percentage applied to researcher salary to be returned to the university/researcher.</inlineHelpText>
    <label>Actual Salary Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Daily_Salary__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Daily_Salary__c</fullName>
    <inlineHelpText>Daily Charge Out Rate for the Funder</inlineHelpText>
    <label>Daily Salary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Lead_Chief_Investigator__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Lead_Chief_Investigator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Example Rate For</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Budgets</relationshipLabel>
    <relationshipName>Budgets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Maximum_Allowed_On_Cost__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Maximum_Allowed_On_Cost__c</fullName>
    <inlineHelpText>Maximum allowable on-cost rate set by Funder.</inlineHelpText>
    <label>Maximum Allowed On-Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/Budget_Line_Item__c.object-meta.xml
<CustomObject>
    <description>This will capture the calculated budget line details from Budget Calculator tool. Please note that Budget Calculator will be a custom developed tool built &amp; integrated with Salesforce. Later the calculated values will be stored in this object.</description>
    <label>Budget Line Item</label>
    <nameField>
        <displayFormat>BLI-{00000}</displayFormat>
        <label>Budget Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Category__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Equipment</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Field Work</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Current La Trobe staff</fullName>
            </value>
            <value>
                <fullName>Future La Trobe staff</fullName>
            </value>
            <value>
                <fullName>Research Assistant</fullName>
            </value>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Non-La Trobe researcher</fullName>
            </value>
            <value>
                <fullName>Personnel</fullName>
            </value>
            <value>
                <fullName>HDR Stipends</fullName>
            </value>
            <value>
                <fullName>Teaching Relief</fullName>
            </value>
            <value>
                <fullName>Field Research</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Cash External</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Contact__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Budget Line Items</relationshipLabel>
    <relationshipName>Budget_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Organisation__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Budget Line Items</relationshipLabel>
    <relationshipName>Budget_Line_Items_Org</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Salary_Grade__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Salary_Grade__c</fullName>
    <formula>IF(
TEXT(I_RS_Category__c) = &quot;Future La Trobe staff&quot; ||
TEXT(I_RS_Category__c) = &quot;Research Assistant&quot; ||
TEXT(I_RS_Category__c) = &quot;Student&quot;,

TEXT(I_RS_Sub_Category__c),

IF(
TEXT(I_RS_Category__c) = &quot;Current La Trobe staff&quot;,
I_RS_Contact__r.I_RS_Salary_Grade_Standard__c,

&quot;&quot;
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Salary Grade</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Sub_Category__c</fullName>
    <label>Sub-Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>I_RS_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Level A 1</fullName>
            </value>
            <value>
                <fullName>Level A 2</fullName>
            </value>
            <value>
                <fullName>Level A 3</fullName>
            </value>
            <value>
                <fullName>Level A 4</fullName>
            </value>
            <value>
                <fullName>Level A 5</fullName>
            </value>
            <value>
                <fullName>Level A 6</fullName>
            </value>
            <value>
                <fullName>Level A 7</fullName>
            </value>
            <value>
                <fullName>Level A 8</fullName>
            </value>
            <value>
                <fullName>Level B 1</fullName>
            </value>
            <value>
                <fullName>Level B 2</fullName>
            </value>
            <value>
                <fullName>Level B 3</fullName>
            </value>
            <value>
                <fullName>Level B 4</fullName>
            </value>
            <value>
                <fullName>Level B 5</fullName>
            </value>
            <value>
                <fullName>Level B 6</fullName>
            </value>
            <value>
                <fullName>Level C 1</fullName>
            </value>
            <value>
                <fullName>Level C 2</fullName>
            </value>
            <value>
                <fullName>Level C 3</fullName>
            </value>
            <value>
                <fullName>Level C 4</fullName>
            </value>
            <value>
                <fullName>Level C 5</fullName>
            </value>
            <value>
                <fullName>Level C 6</fullName>
            </value>
            <value>
                <fullName>Level D 1</fullName>
            </value>
            <value>
                <fullName>Level D 2</fullName>
            </value>
            <value>
                <fullName>Level D 3</fullName>
            </value>
            <value>
                <fullName>Level D 4</fullName>
            </value>
            <value>
                <fullName>Level E 1</fullName>
            </value>
            <value>
                <fullName>HEO1-1</fullName>
            </value>
            <value>
                <fullName>HEO1-2</fullName>
            </value>
            <value>
                <fullName>HEO1-3</fullName>
            </value>
            <value>
                <fullName>HEO1-4</fullName>
            </value>
            <value>
                <fullName>HEO2-1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/recordTypes/I_RS_Non_Salary.recordType-meta.xml
<RecordType>
    <fullName>I_RS_Non_Salary</fullName>
    <active>true</active>
    <label>Non-Salary</label>
</RecordType>

force-app/main/default/objects/Budget_Line_Item__c/recordTypes/I_RS_Salary.recordType-meta.xml
<RecordType>
    <fullName>I_RS_Salary</fullName>
    <active>true</active>
    <label>Salary</label>
</RecordType>

force-app/main/default/objects/Contact/fields/I_RS_Salary_Grade__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Salary_Grade__c</fullName>
    <label>Salary Grade (HR)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Level A 1</fullName>
            </value>
            <value>
                <fullName>Level A 2</fullName>
            </value>
            <value>
                <fullName>Level A 3</fullName>
            </value>
            <value>
                <fullName>Level A 4</fullName>
            </value>
            <value>
                <fullName>Level A 5</fullName>
            </value>
            <value>
                <fullName>Level A 6</fullName>
            </value>
            <value>
                <fullName>Level A 7</fullName>
            </value>
            <value>
                <fullName>Level A 8</fullName>
            </value>
            <value>
                <fullName>Level B 1</fullName>
            </value>
            <value>
                <fullName>Level B 2</fullName>
            </value>
            <value>
                <fullName>Level B 3</fullName>
            </value>
            <value>
                <fullName>Level B 4</fullName>
            </value>
            <value>
                <fullName>Level B 5</fullName>
            </value>
            <value>
                <fullName>Level B 6</fullName>
            </value>
            <value>
                <fullName>Level C 1</fullName>
            </value>
            <value>
                <fullName>Level C 2</fullName>
            </value>
            <value>
                <fullName>Level C 3</fullName>
            </value>
            <value>
                <fullName>Level C 4</fullName>
            </value>
            <value>
                <fullName>Level C 5</fullName>
            </value>
            <value>
                <fullName>Level C 6</fullName>
            </value>
            <value>
                <fullName>Level D 1</fullName>
            </value>
            <value>
                <fullName>Level D 2</fullName>
            </value>
            <value>
                <fullName>Level D 3</fullName>
            </value>
            <value>
                <fullName>Level D 4</fullName>
            </value>
            <value>
                <fullName>Level E 1</fullName>
            </value>
            <value>
                <fullName>HEO1-1</fullName>
            </value>
            <value>
                <fullName>HEO1-2</fullName>
            </value>
            <value>
                <fullName>HEO1-3</fullName>
            </value>
            <value>
                <fullName>HEO1-4</fullName>
            </value>
            <value>
                <fullName>HEO2-1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/On_Cost_Default_Values__c/fields/I_RS_Maximum_Allowed_On_Cost__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Maximum_Allowed_On_Cost__c</fullName>
    <label>Maximum Allowed On-Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Project_Proposal__c/Project_Proposal__c.object-meta.xml
<CustomObject>
    <description>Project Proposal: An application for funding either through a grant request, a tender response, or a contract proposal.
Project: The work that is undertaken to satisfy a commitment made to a funding body or client.  The commitment is likely to be a contract (and possible variations) resulting from the acceptance of a project proposal.  This occurs after a grant, contract of philanthropic donation has been awarded.</description>
    <label>Project Proposal</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Proposal__c/fields/I_RS_Account_Organisation__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Account_Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Organisation</description>
    <inlineHelpText>Search to find the Funder. If it does not already exist leave this blank and add the Funder&apos;s name to the Comments field.</inlineHelpText>
    <label>Funder</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Project Proposals</relationshipLabel>
    <relationshipName>Project_Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Proposal__c/fields/I_RS_Lead_Chief_Investigator__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Lead_Chief_Investigator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Chief Investigator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Project Proposals</relationshipLabel>
    <relationshipName>Project_Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BudgetCalculatorTest.cls
@isTest
public class BudgetCalculatorTest {
    
    public static testmethod void testBudgetCalculation() {

        TestUtility.insertGSTRate();

        insert new On_Cost_Default_Values__c(
            Name = 'La Trobe University',
            I_RS_Maximum_Allowed_On_Cost__c = 35.88
        );

        Account org = TestUtility.newEmptyExternalAccount('Org One');
        insert org;

        //Contact salaryPerson = TestUtility.newContact(GlobalConstants.CONTACT_RECORD_TYPE_NAME_LTU_STAFF, null);
        Contact salaryPerson = TestUtility.createContact(null);
        salaryPerson.I_RS_Salary_Grade__c = 'Level A 1';
        insert salaryPerson;

        List<Salary_Table__c> salaryTableList = new List<Salary_Table__c>();
        Integer todaysYear = Date.today().year();
        for (Integer index=1; index<=10; index++){
            String currentYear = (todaysYear + index - 1) + '';
            salaryTableList.add(TestUtility.newSalaryTable('Level A', index, currentYear, 100000 + (1000 * index) ));
        }
        insert salaryTableList;

        Project_Proposal__c projectProposal = TestUtility.newProjectProposal();
        projectProposal.I_RS_Account_Organisation__c = org.Id;
        projectProposal.I_RS_Lead_Chief_Investigator__c = salaryPerson.Id;
        insert projectProposal;

        //
        //BUDGET AND LINE ITEM INITIAL CALCULATIONS
        //
        //Insert Budget, apply daily chargeout rate calculation
        Budget__c budget = TestUtility.newBudget(projectProposal.Id);
        budget.I_RS_Actual_Overhead__c = 30;
        budget.I_RS_Actual_Profit__c = 30;
        budget.I_RS_Actual_Non_Salary_Overhead__c = 30;

        insert budget;

        BudgetRateHelper.provideDailyChargeoutRates(new List<Budget__c>{budget});
        update budget;

        budget = [SELECT Id, I_RS_Daily_Salary__c from Budget__c WHERE Id = :budget.Id];
        System.assert(budget.I_RS_Daily_Salary__c > 0);
        Decimal initialDailyBaseSalary = budget.I_RS_Daily_Salary__c;

        //Create Budget Line Items
        List<Budget_Line_Item__c> budgetLineItems = new List<Budget_Line_Item__c>{
            TestUtility.newBudgetLineItem(budget.Id, 'I_RS_Salary', 0),
            TestUtility.newBudgetLineItem(budget.Id, 'I_RS_Salary', 0),
            TestUtility.newBudgetLineItem(budget.Id, 'I_RS_Non_Salary', 0)
        };
        budgetLineItems[0].I_RS_Contact__c = salaryPerson.Id;
        budgetLineItems[0].I_RS_Organisation__c = org.Id;

        budgetLineItems[1].I_RS_Category__c = 'Future La Trobe Staff';
        budgetLineItems[1].I_RS_Sub_Category__c = 'Level A 1';
        budgetLineItems[1].I_RS_Contact__c = salaryPerson.Id;
        budgetLineItems[1].I_RS_Organisation__c = org.Id;

        budgetLineItems[2].I_RS_Category__c = 'Travel';
        budgetLineItems[2].I_RS_Organisation__c = org.Id;
        budgetLineItems[2].Unit_Price__c = 100;

        insert budgetLineItems;

        //
        //ACTUAL TEST
        //
        Test.startTest();

        new BudgetCalculator(budgetLineItems).recalculateAndSave();

        Test.stopTest();

        //Verify Salary Items
        List<Budget_Line_Item__c> salaryItems = [
            SELECT Id, I_RS_Amount__c FROM Budget_Line_Item__c 
            WHERE RecordType.DeveloperName = 'I_RS_Salary' ORDER BY I_RS_Category__c];

        System.debug('Salary Item 0 cost '+salaryItems[0].I_RS_Amount__c);
        System.debug('Salary Item 1 cost '+salaryItems[1].I_RS_Amount__c);

        System.assert(salaryItems[0].I_RS_Amount__c > 0);
        System.assert(salaryItems[1].I_RS_Amount__c > 0);

        //Assert more stuff here

        List<Budget_Line_Item__c> nonSalaryItems = [
            SELECT Id, I_RS_Amount__c FROM Budget_Line_Item__c 
            WHERE RecordType.DeveloperName = 'I_RS_Non_Salary' ORDER BY I_RS_Category__c];

        System.assert(nonSalaryItems[0].I_RS_Amount__c > 0);

    }

    public static testmethod void testMergeOrgs() {

        TestUtility.insertGSTRate();

        insert new On_Cost_Default_Values__c(
            Name = 'La Trobe University',
            I_RS_Maximum_Allowed_On_Cost__c = 35.88
        );

        List<Account> orgs = new List<Account>{
            TestUtility.newEmptyExternalAccount('Org One'),
            TestUtility.newEmptyExternalAccount('Org Two')
        };
        orgs[1].I_RS_Maximum_Allowed_On_Cost__c = 50;

        insert orgs;

        //Contact salaryPerson = TestUtility.newContact(GlobalConstants.CONTACT_RECORD_TYPE_NAME_LTU_STAFF, null);
        Contact salaryPerson = TestUtility.createContact(null);
        salaryPerson.I_RS_Salary_Grade__c = 'TEST 1';
        insert salaryPerson;

        List<Salary_Table__c> salaryTableList = new List<Salary_Table__c>();
        Integer todaysYear = Date.today().year();
        for (Integer index=1; index<=10; index++){
            String currentYear = (todaysYear + index - 1) + '';
            salaryTableList.add(TestUtility.newSalaryTable('TEST', index, currentYear, 100000 + (1000 * index) ));     
        }
        
        insert salaryTableList;

        Project_Proposal__c projectProposal = TestUtility.newProjectProposal();
        projectProposal.I_RS_Account_Organisation__c = orgs[0].Id;
        projectProposal.I_RS_Lead_Chief_Investigator__c = salaryPerson.Id;
        insert projectProposal;

        //Insert Budget, apply daily chargeout rate calculation
        Budget__c budget = TestUtility.newBudget(projectProposal.Id);
        budget.I_RS_Actual_Overhead__c = 30;
        budget.I_RS_Actual_Profit__c = 30;
        budget.I_RS_Actual_Non_Salary_Overhead__c = 30;

        insert budget;

        BudgetRateHelper.provideDailyChargeoutRates(new List<Budget__c>{budget});
        update budget;

        budget = [SELECT Id, I_RS_Total_Daily_Charge_Out_Rate_Formula__c from Budget__c WHERE Id = :budget.Id];
        System.assert(budget.I_RS_Total_Daily_Charge_Out_Rate_Formula__c > 0);
        Decimal initialDailyChargeoutRate = budget.I_RS_Total_Daily_Charge_Out_Rate_Formula__c;

        //Create Budget Line Items
        List<Budget_Line_Item__c> budgetLineItems = new List<Budget_Line_Item__c>{
            TestUtility.newBudgetLineItem(budget.Id, 'I_RS_Salary', 0),
            TestUtility.newBudgetLineItem(budget.Id, 'I_RS_Salary', 0)
        };
        budgetLineItems[0].I_RS_Contact__c = salaryPerson.Id;
        budgetLineItems[1].I_RS_Contact__c = salaryPerson.Id;

        budgetLineItems[0].I_RS_Organisation__c = orgs[0].Id;
        budgetLineItems[1].I_RS_Organisation__c = orgs[1].Id;

        insert budgetLineItems;


        Test.startTest();

        orgs[0].I_RS_Maximum_Allowed_On_Cost__c = orgs[1].I_RS_Maximum_Allowed_On_Cost__c;
        merge orgs[0] orgs[1];

        Test.stopTest();

        //Verify Budget chargeout rate has changed
        budget = [SELECT Id, I_RS_Maximum_Allowed_On_Cost__c from Budget__c WHERE Id = :budget.Id];
        System.assertequals(orgs[1].I_RS_Maximum_Allowed_On_Cost__c, budget.I_RS_Maximum_Allowed_On_Cost__c);

        //Verify Salary Items
        List<Budget_Line_Item__c> salaryItems = [
            SELECT Id, I_RS_Amount__c FROM Budget_Line_Item__c WHERE RecordType.DeveloperName = 'I_RS_Salary'];

        System.debug('Salary Item 0 cost '+salaryItems[0].I_RS_Amount__c);
        System.debug('Salary Item 1 cost '+salaryItems[1].I_RS_Amount__c);

        System.assert(salaryItems[0].I_RS_Amount__c > 0);
        System.assert(salaryItems[1].I_RS_Amount__c > 0);

        System.assertequals(salaryItems[0].I_RS_Amount__c, salaryItems[1].I_RS_Amount__c);

        //Verify Non-Salary Items
        List<Budget_Line_Item__c> nonSalaryItems = [
            SELECT Id, I_RS_Amount__c FROM Budget_Line_Item__c WHERE RecordType.Name = 'I_RS_Non_Salary'];


    }

    public static testmethod void testMergeContacts(){

        TestUtility.insertGSTRate();

        insert new On_Cost_Default_Values__c(
            Name = 'La Trobe University',
            I_RS_Maximum_Allowed_On_Cost__c = 35.88
        );

        Account org = TestUtility.newEmptyExternalAccount('Org One');
        insert org;

        List<Contact> salaryPersons = new List<Contact>{
            //TestUtility.newContact(GlobalConstants.CONTACT_RECORD_TYPE_NAME_LTU_STAFF, null),
            //TestUtility.newContact(GlobalConstants.CONTACT_RECORD_TYPE_NAME_LTU_STAFF, null)
            TestUtility.createContact(null),
            TestUtility.createContact(null)
        };
        salaryPersons[0].I_RS_Salary_Grade__c = 'TEST 1';
        salaryPersons[1].I_RS_Salary_Grade__c = 'JEST 1';
        insert salaryPersons;

        List<Salary_Table__c> salaryTableList = new List<Salary_Table__c>();
        Integer todaysYear = Date.today().year();
        for (Integer index=1; index<=10; index++){
            String currentYear = (todaysYear + index - 1) + '';
            salaryTableList.add(TestUtility.newSalaryTable('TEST', index, currentYear, 100000 + (1000 * index) ));     

            salaryTableList.add(TestUtility.newSalaryTable('JEST', index, currentYear, 200000 + (1000 * index) ));     
        }
        
        insert salaryTableList;

        Project_Proposal__c projectProposal = TestUtility.newProjectProposal();
        projectProposal.I_RS_Account_Organisation__c = org.Id;
        projectProposal.I_RS_Lead_Chief_Investigator__c = salaryPersons[0].Id;
        insert projectProposal;

        //
        //BUDGET AND LINE ITEM INITIAL CALCULATIONS
        //
        //Insert Budget, apply daily chargeout rate calculation
        Budget__c budget = TestUtility.newBudget(projectProposal.Id);
        budget.I_RS_Actual_Overhead__c = 30;
        budget.I_RS_Actual_Profit__c = 30;
        budget.I_RS_Actual_Non_Salary_Overhead__c = 30;

        insert budget;

        BudgetRateHelper.provideDailyChargeoutRates(new List<Budget__c>{budget});
        update budget;

        budget = [SELECT Id, I_RS_Daily_Salary__c from Budget__c WHERE Id = :budget.Id];
        System.assert(budget.I_RS_Daily_Salary__c > 0);
        Decimal initialDailyBaseSalary = budget.I_RS_Daily_Salary__c;

        //Create Budget Line Items
        List<Budget_Line_Item__c> budgetLineItems = new List<Budget_Line_Item__c>{
            TestUtility.newBudgetLineItem(budget.Id, 'I_RS_Salary', 0),
            TestUtility.newBudgetLineItem(budget.Id, 'I_RS_Salary', 0)
        };
        budgetLineItems[0].I_RS_Contact__c = salaryPersons[0].Id;
        budgetLineItems[1].I_RS_Contact__c = salaryPersons[1].Id;

        budgetLineItems[0].I_RS_Organisation__c = org.Id;
        budgetLineItems[1].I_RS_Organisation__c = org.Id;

        insert budgetLineItems;

        //
        //ACTUAL TEST
        //
        Test.startTest();

        salaryPersons[0].I_RS_Salary_Grade__c = salaryPersons[1].I_RS_Salary_Grade__c;
        merge salaryPersons[0] salaryPersons[1];

        Test.stopTest();

        //Verify Budget chargeout rate has changed
        budget = [SELECT Id, I_RS_Maximum_Allowed_On_Cost__c from Budget__c WHERE Id = :budget.Id];

        //Verify Salary Items
        List<Budget_Line_Item__c> salaryItems = [
            SELECT Id, I_RS_Amount__c FROM Budget_Line_Item__c WHERE RecordType.DeveloperName = 'I_RS_Salary'];

        System.debug('Salary Item 0 cost '+salaryItems[0].I_RS_Amount__c);
        System.debug('Salary Item 1 cost '+salaryItems[1].I_RS_Amount__c);

        System.assert(salaryItems[0].I_RS_Amount__c > 0);
        System.assert(salaryItems[1].I_RS_Amount__c > 0);

        System.assertequals(salaryItems[0].I_RS_Amount__c, salaryItems[1].I_RS_Amount__c);

    }
}