force-app/main/default/objects/Account/fields/I_RS_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Start_Date__c</fullName>
    <inlineHelpText>This represents the first engagement with La Trobe.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/I_RS_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Proposed</fullName>
                <isActive>false</isActive>
                <label>Proposed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/I_RS_Related_User__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Related_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Refers to the user record associated to the contact</description>
    <label>Related User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/I_RM_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Part of the remediation project to store different personas</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Contact__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Contact__c</fullName>
    <description>The person/contact who this Affiliation relates to</description>
    <inlineHelpText>The person this affiliation relates to</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Affiliations</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Email__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Email__c</fullName>
    <description>Depicts Personal Email</description>
    <inlineHelpText>The personal email for this person.</inlineHelpText>
    <label>Personal Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Mobile_Phone__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Mobile_Phone__c</fullName>
    <description>Depicts affiliation&apos;s Mobile Phone number</description>
    <label>Mobile Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Role__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Role__c</fullName>
    <description>This represents the role of the affiliation</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Domestic Lead</fullName>
                <label>Student Lead (Dom)</label>
            </value>
            <value>
                <fullName>Applicant</fullName>
                <label>Student Applicant (Dom)</label>
            </value>
            <value>
                <fullName>La Trobe Staff</fullName>
            </value>
            <value>
                <fullName>School Representative</fullName>
                <label>Secondary School Representative</label>
            </value>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>External Contact</fullName>
            </value>
            <value>
                <fullName>HDR Student</fullName>
                <label>Graduate Researcher</label>
            </value>
            <value>
                <fullName>Student Lead (Int)</fullName>
            </value>
            <value>
                <fullName>Nominated Affiliation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <description>Indicates the status of the Affiliation.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>I_RM_Role__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>I_ST_Contact_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_IL_Student_Lead_Int.recordType-meta.xml
<RecordType>
    <fullName>I_IL_Student_Lead_Int</fullName>
    <active>true</active>
    <description>New International Lead who can be a prospective student of La Trobe University</description>
    <label>Student Lead (Int)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_Applicant.recordType-meta.xml
<RecordType>
    <fullName>I_RM_Applicant</fullName>
    <active>true</active>
    <description>An individual who has applied to study at La Trobe University</description>
    <label>Student Applicant (Dom)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_La_Trobe_Staff.recordType-meta.xml
<RecordType>
    <fullName>I_RM_La_Trobe_Staff</fullName>
    <active>true</active>
    <description>La Trobe staff member</description>
    <label>La Trobe Staff</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_Lead.recordType-meta.xml
<RecordType>
    <fullName>I_RM_Lead</fullName>
    <active>true</active>
    <description>New Domestic Lead who is a prospective student of La Trobe University</description>
    <label>Student Lead (Dom)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/I_RM_Affiliation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Affiliation Settings</label>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Research_Opportunity__c/Research_Opportunity__c.object-meta.xml
<CustomObject>
    <label>Funding Opportunity</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Research_Opportunity__c/fields/I_RS_Private__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Private__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Tick this box to restrict visibility of this funding opportunity to specified researchers. This opportunity will not be searchable.</inlineHelpText>
    <label>Private</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Research_Opportunity__c/fields/I_RS_Proposal_to_be_Submitted_By__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Proposal_to_be_Submitted_By__c</fullName>
    <inlineHelpText>Whether Research Office or Researcher is to submit the proposal under the guidelines or specifications of the opportunity.</inlineHelpText>
    <label>Proposal to be Submitted By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Researcher</fullName>
            </value>
            <value>
                <fullName>Research Office</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Research_Opportunity__c/fields/I_RS_Research_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Research_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to maintain hierarchy and related research opportunities</description>
    <label>Funding Scheme</label>
    <referenceTo>Research_Opportunity__c</referenceTo>
    <relationshipLabel>Funding Opportunities</relationshipLabel>
    <relationshipName>Research_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Research_Opportunity__c/fields/I_RS_Source__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Source__c</fullName>
    <label>Source of opportunity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approach by industry</fullName>
            </value>
            <value>
                <fullName>Industry Engagement</fullName>
            </value>
            <value>
                <fullName>Panel</fullName>
            </value>
            <value>
                <fullName>Publicly available</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Grant connect</fullName>
            </value>
            <value>
                <fullName>Research Professional</fullName>
            </value>
            <value>
                <fullName>AAO</fullName>
                <label>Alumni and Advancement Office</label>
            </value>
            <value>
                <fullName>GRS</fullName>
                <label>Graduate Research School</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Research_Opportunity__c/fields/I_RS_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Research_Opportunity__c/fields/I_RS_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initial</fullName>
                <default>true</default>
                <label>Initial</label>
            </value>
            <value>
                <fullName>Drafted</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Internal Applications Closed</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Research_Opportunity__c/fields/I_RS_Submission_Date__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Submission_Date__c</fullName>
    <inlineHelpText>The Funder&apos;s due date for the proposal</inlineHelpText>
    <label>Submission Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Research_Opportunity_Team_Member__c/Research_Opportunity_Team_Member__c.object-meta.xml
<CustomObject>
    <label>Funding Opportunity Team Member</label>
    <nameField>
        <label>Funding Opportunity Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunity Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Research_Opportunity_Team_Member__c/fields/I_RS_Research_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Research_Opportunity__c</fullName>
    <label>Funding Opportunity</label>
    <referenceTo>Research_Opportunity__c</referenceTo>
    <relationshipLabel>Funding Opportunity Team Members</relationshipLabel>
    <relationshipName>Research_Opportunity_Team_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Research_Opportunity_Team_Member__c/fields/I_RS_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Research_Opportunity_Team_Member__c/fields/I_RS_Team_Member__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.I_RM_La_Trobe_Staff__c</field>
            <operation>greaterOrEqual</operation>
            <value>1</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Funding Opportunity Team Members</relationshipLabel>
    <relationshipName>Funding_Opportunity_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/I_ST_Contact_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Admitted</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And LOA</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Not Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Considered</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Made</fullName>
    </customValue>
    <customValue>
        <fullName>Await Academic Advice</fullName>
    </customValue>
    <customValue>
        <fullName>Await Applicant Comms</fullName>
    </customValue>
    <customValue>
        <fullName>Await Further Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Awaiting Interview</fullName>
    </customValue>
    <customValue>
        <fullName>Await Required Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Escalated</fullName>
    </customValue>
    <customValue>
        <fullName>Make A Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make Alternate Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make An Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Nearing Completion</fullName>
    </customValue>
    <customValue>
        <fullName>Not Processed</fullName>
    </customValue>
    <customValue>
        <fullName>Not Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Lapsed</fullName>
    </customValue>
    <customValue>
        <fullName>Other Preference Offered</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Results</fullName>
    </customValue>
    <customValue>
        <fullName>Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <description>Global value set is created for lead(contact) object ST -51</description>
    <masterLabel>I_ST_Contact_Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ResearchOppTeamMemberRecordAccessTest.cls
/**
 * Created by burnside on 2019-05-02.
 */
@isTest
public with sharing class ResearchOppTeamMemberRecordAccessTest {
    public static Id affiliationStaffRecordTypeId = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_La_Trobe_Staff').getRecordTypeId();
     
    

    static Database.DMLOptions allowDuplicates = TestUtility.getAllowDuplicatesDMLOption();
    
  @TestSetup
    static void setup(){

        String recTypeIdsForAffScoring = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Applicant').getRecordTypeId();
        recTypeIdsForAffScoring += ',' + Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Lead').getRecordTypeId();
        recTypeIdsForAffScoring += ',' + Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_IL_Student_Lead_Int').getRecordTypeId();
        TestUtility.createBatchScoringCustomSettings(recTypeIdsForAffScoring);
        
        ContactTriggerHandler.runHierarchySharing = false;
	    ContactTriggerHandler.runProjectTeamMemberSharing = false;
    	ContactTriggerHandler.runResearchPersonnelSharing = false;
        ContactTriggerHandler.runLeadAccountCleanup = false;
        ContactTriggerHandler.runBudget = false;
        ProjectProposalHandler.executeInTest = false;
        ContactTriggerHandler.createLeadAccount = false;

        UserRole portalRole = [SELECT Id FROM UserRole WHERE PortalType = 'None' Limit 1];
        Profile profile1;//'System Administrator'
        Profile portalProfile;//'LTU Partner Community Login User'
        for (Profile p: [SELECT Id, Name FROM Profile WHERE Name IN ('System Administrator', 'LTU Partner Community Login User') ]){
            if (p.Name == 'LTU Partner Community Login User'){
            	    portalProfile = p;
            }   
            if (p.Name == 'System Administrator'){
            	profile1 = p;    
            }
        }

        User portalAccountOwner1 = TestUtility.newUser('accountOwner', profile1.Id, portalRole.Id, null);
        insert(portalAccountOwner1);
		System.runAs ( portalAccountOwner1 ) {
			List<SObject> genericSObjectList = new List<SObject>();
     		
            I_RM_Affiliation_Settings__c objAffiliationSettings = I_ST_UnitTestUtilities.createAffiliationSettings();
            insert objAffiliationSettings;
    
            Account portalAccount = TestUtility.newEmptyExternalAccount('TestAccount');
            insert(portalAccount);

            Contact contact1 = TestUtility.newContact(portalAccount.Id);
            genericSObjectList.add(contact1);
            Contact contact2 = TestUtility.newContact(portalAccount.Id);
            genericSObjectList.add(contact2);
            Database.insert(genericSObjectList, allowDuplicates);
            genericSObjectList.clear();
            
             I_RM_Affiliation__c aff=new I_RM_Affiliation__c(RecordTypeID = affiliationStaffRecordTypeId,
                                                        I_RM_Contact__c=contact1.Id,
                                                        I_RM_Role__c='La Trobe Staff',I_RM_Email__c='caseoftypeenquiry@ibm.com',
                                                        I_RM_Status__c='Active',
                                                        I_RM_Mobile_Phone__c='0415822666');
             insert aff;

            I_RM_Affiliation__c aff2=new I_RM_Affiliation__c(RecordTypeID = affiliationStaffRecordTypeId,
            I_RM_Contact__c=contact2.Id,
            I_RM_Role__c='La Trobe Staff',I_RM_Email__c='caseoftypeenquiry@abc.com',
            I_RM_Status__c='Active',
            I_RM_Mobile_Phone__c='0415822667');
			genericSObjectList.add(aff2);
            insert genericSObjectList;
            genericSObjectList.clear();
            


            User portalUser1 = TestUtility.newUser('portalone', portalProfile.Id, null, contact1.Id);
            genericSObjectList.add(portalUser1);
            User portalUser2 = TestUtility.newUser('portaltwo', portalProfile.Id, null, contact2.Id);
            genericSObjectList.add(portalUser2);
            insert genericSObjectList;
            genericSObjectList.clear();

            contact1.I_RS_Related_User__c = portalUser1.Id;
            genericSObjectList.add(contact1);
            contact2.I_RS_Related_User__c = portalUser2.Id;
            genericSObjectList.add(contact2);
            Database.update(genericSObjectList, allowDuplicates);
            genericSObjectList.clear();

            Research_Opportunity__c researchOpportunity1 = TestUtility.newResearchOpportunity(true);
            genericSObjectList.add(researchOpportunity1);
            System.debug(researchOpportunity1);
            Research_Opportunity__c researchOpportunity2 = TestUtility.newResearchOpportunity(true);
            genericSObjectList.add(researchOpportunity2);
            insert genericSObjectList;
            genericSObjectList.clear();
            System.debug(researchOpportunity2);
        }
    }

    public static testMethod void researchOppTeamMemberRecordAccessTest(){
 
        String Username = 'accountOwner' + UserInfo.getOrganizationId() + '@test.com';
        User portalAccountOwner1 = [SELECT Id, profileId, portalRole, Username FROM User WHERE Username = :Username LIMIT 1];

        System.runAs ( portalAccountOwner1 ) {
            Account portalAccount = [SELECT Id, Name FROM Account WHERE Name = 'TestAccount' LIMIT 1];

            Contact contact1, contact2;
            for (Contact c: [Select Id, FirstName, LastName, AccountId, Email FROM Contact WHERE AccountId = :portalAccount.Id]) {
                if (contact1 == null) {
                    contact1 = c;
                }else if (contact2 == null) {
                    contact2 = c;
                }
            }
            
            I_RM_Affiliation__c aff, aff2;
            for(I_RM_Affiliation__c a: [SELECT Id, RecordTypeID, I_RM_Contact__c, I_RM_Role__c, I_RM_Status__c, I_RM_Mobile_Phone__c FROM I_RM_Affiliation__c WHERE I_RM_Contact__c IN (:contact1.Id, :contact2.Id)]){
                if (a.I_RM_Contact__c == contact1.Id) {
                    aff = a;
                } else if (a.I_RM_Contact__c == contact2.Id) {
                    aff2 = a;
                }    
            }
            
            

            User portalUser1, portalUser2;
            for (User u : [SELECT Id, Name, ContactId FROM User WHERE ContactId IN (:contact1.Id, :contact2.Id)]){
                if (u.ContactId == contact1.Id) {
                	portalUser1 = u;    
                }else if (u.ContactId == contact2.Id) {
                	portalUser2 = u;    
                }   
            }

            
            Research_Opportunity__c researchOpportunity1, researchOpportunity2;
            for (Research_Opportunity__c r : [SELECT Id, Name, I_RS_Status__c, I_RS_Source__c, I_RS_Proposal_to_be_Submitted_By__c, I_RS_Start_Date__c, I_RS_Private__c, I_RS_Submission_Date__c FROM Research_Opportunity__c]){
                if (researchOpportunity1 == null) {
                	researchOpportunity1 = r;    
                } else if (researchOpportunity2 == null) {
                	researchOpportunity2 = r;    
                }   
            }

            Test.startTest();


            //INSERT TEAM MEMBERS - SHOULD ALSO CREATE SHARING
            Research_Opportunity_Team_Member__c teamMember0 =
                    new Research_Opportunity_Team_Member__c(
                            I_RS_Team_Member__c = contact1.Id,
                            I_RS_Research_Opportunity__c = researchOpportunity1.Id,
                            I_RS_Status__c = GlobalConstants.RES_OPP_TEAM_MEMBER_STATUS_ACCEPTED
                    );
            insert teamMember0;
            Research_Opportunity_Team_Member__c teamMember1 =
                    new Research_Opportunity_Team_Member__c(
                            I_RS_Team_Member__c = contact1.Id,
                            I_RS_Research_Opportunity__c = researchOpportunity2.Id,
                            I_RS_Status__c = GlobalConstants.RES_OPP_TEAM_MEMBER_STATUS_ACCEPTED
                    );
            insert teamMember1;     

            Research_Opportunity_Team_Member__c teamMember2 =
                    new Research_Opportunity_Team_Member__c(
                            I_RS_Team_Member__c = contact2.Id,
                            I_RS_Research_Opportunity__c = researchOpportunity1.Id,
                            I_RS_Status__c = GlobalConstants.RES_OPP_TEAM_MEMBER_STATUS_ACCEPTED
                    );
            insert teamMember2;

            Research_Opportunity_Team_Member__c teamMember3 =
                    new Research_Opportunity_Team_Member__c(
                            I_RS_Team_Member__c = contact2.Id,
                            I_RS_Research_Opportunity__c = researchOpportunity2.Id,
                            I_RS_Status__c = GlobalConstants.RES_OPP_TEAM_MEMBER_STATUS_ACCEPTED
                    );
            insert teamMember3;

            Test.stopTest();

            System.assertEquals(4, [SELECT COUNT() FROM Research_Opportunity__Share WHERE RowCause = :Schema.Research_Opportunity__Share.rowCause.Research_Opportunity_Team_Member__c]);


            System.runAs(portalUser1) {
                System.assertEquals(researchOpportunity1.Id, [SELECT Id FROM Research_Opportunity__c][0].Id);
                System.assertEquals(researchOpportunity2.Id, [SELECT Id FROM Research_Opportunity__c][1].Id);

                System.assertEquals(4, [SELECT COUNT() FROM Research_Opportunity_Team_Member__c]);

            }

            System.runAs(portalUser2) {
                System.assertEquals(researchOpportunity1.Id, [SELECT Id FROM Research_Opportunity__c][0].Id);
                System.assertEquals(researchOpportunity2.Id, [SELECT Id FROM Research_Opportunity__c][1].Id);

                System.assertEquals(4, [SELECT COUNT() FROM Research_Opportunity_Team_Member__c]);

            }


            //DUMMY UPDATE MEMBERS - NO CHANGE SHOULD OCCUR
            update teamMember0;
            update teamMember1;
            update teamMember2;
            update teamMember3;

            System.assertEquals(4, [SELECT COUNT() FROM Research_Opportunity__Share WHERE RowCause = :Schema.Research_Opportunity__Share.rowCause.Research_Opportunity_Team_Member__c]);


            //CHANGE TEAM MEMBER STATUSES - SHARING SHOULD BE REMOVED

            teamMember0.I_RS_Status__c = GlobalConstants.RES_OPP_TEAM_MEMBER_STATUS_REJECTED;
            update teamMember0;
            teamMember3.I_RS_Status__c = GlobalConstants.RES_OPP_TEAM_MEMBER_STATUS_REJECTED;
            update teamMember3;


            System.assertEquals(2, [SELECT COUNT() FROM Research_Opportunity__Share WHERE RowCause = :Schema.Research_Opportunity__Share.rowCause.Research_Opportunity_Team_Member__c]);
            
            System.runAs(portalUser1) {
                System.debug('Run as internalUser1 - after rejecting');
                System.debug([select Id FROM Research_Opportunity__c]);

                System.assertEquals(researchOpportunity2.Id, [SELECT Id FROM Research_Opportunity__c].Id);

                System.assertEquals(2, [SELECT COUNT() FROM Research_Opportunity_Team_Member__c]);

            }

            System.runAs(portalUser2) {
                System.debug('Run as internalUser2 - after rejecting');

                System.assertEquals(researchOpportunity1.Id, [SELECT Id FROM Research_Opportunity__c].Id);

            }


            //DELETE TEAM MEMBER(S) - SHARES SHOULD BE REMOVED

            delete teamMember1;
            System.assertEquals(1, [SELECT COUNT() FROM Research_Opportunity__Share WHERE RowCause = :Schema.Research_Opportunity__Share.rowCause.Research_Opportunity_Team_Member__c]);


            System.runAs(portalUser1) {
                System.debug('Run as internalUser1 - after deleting');
                System.assert([SELECT Id FROM Research_Opportunity__c].isEmpty());

            }


            System.debug('SOQL Queries: ' + Limits.getQueries());
            System.debug('DML Rows: '+Limits.getDMLRows());

        }

    }


    public static testmethod void stressTest(){


        Integer fundingOppCount = 500;
        


        String Username = 'accountOwner' + UserInfo.getOrganizationId() + '@test.com';
        User portalAccountOwner1 = [SELECT Id, profileId, portalRole, Username FROM User WHERE Username = :Username LIMIT 1];

        System.runAs ( portalAccountOwner1 ) {
            Account portalAccount = [SELECT Id, Name FROM Account WHERE Name = 'TestAccount' LIMIT 1];

            Contact contact1, contact2;
            for (Contact c: [Select Id, FirstName, LastName, AccountId, Email FROM Contact WHERE AccountId = :portalAccount.Id]) {
                if (contact1 == null) {
                    contact1 = c;
                }else if (contact2 == null) {
                    contact2 = c;
                }
            }
            
            I_RM_Affiliation__c aff, aff2;
            for(I_RM_Affiliation__c a: [SELECT Id, RecordTypeID, I_RM_Contact__c, I_RM_Role__c, I_RM_Status__c, I_RM_Mobile_Phone__c FROM I_RM_Affiliation__c WHERE I_RM_Contact__c IN (:contact1.Id, :contact2.Id)]){
                if (a.I_RM_Contact__c == contact1.Id) {
                    aff = a;
                } else if (a.I_RM_Contact__c == contact2.Id) {
                    aff2 = a;
                }    
            }


            List<Research_Opportunity__c> researchOpportunityList = new List<Research_Opportunity__c>();
            for (Integer i=0; i<fundingOppCount; i++){
                researchOpportunityList.add(TestUtility.newResearchOpportunity(true));
            }
            insert researchOpportunityList;


            Test.startTest();

                List<Research_Opportunity_Team_Member__c> teamMembers = new List<Research_Opportunity_Team_Member__c>();
                for (Research_Opportunity__c researchOpportunity : researchOpportunityList){

                        teamMembers.add(
                            new Research_Opportunity_Team_Member__c(
                                    I_RS_Team_Member__c = contact1.Id,
                                    I_RS_Research_Opportunity__c = researchOpportunity.Id,
                                    I_RS_Status__c = GlobalConstants.RES_OPP_TEAM_MEMBER_STATUS_ACCEPTED
                            )
                        );

                        teamMembers.add(
                            new Research_Opportunity_Team_Member__c(
                                    I_RS_Team_Member__c = contact2.Id,
                                    I_RS_Research_Opportunity__c = researchOpportunity.Id,
                                    I_RS_Status__c = GlobalConstants.RES_OPP_TEAM_MEMBER_STATUS_ACCEPTED
                            )
                        );


                }

                insert teamMembers;

            Test.stopTest();

        }

    }


}