force-app/main/default/objects/Account/fields/I_RS_ABN__c.field-meta.xml
<CustomField>
    <fullName>I_RS_ABN__c</fullName>
    <label>ABN</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/I_RS_Funder_Id__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Funder_Id__c</fullName>
    <description>Funder Id captured from RP</description>
    <label>RP Funder Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/Funding_Opportunity_Staging__c.object-meta.xml
<CustomObject>
    <description>This object is to store funding opps coming from external system as a staging instance eg, Research Professional.</description>
    <label>Funding Opportunity Staging</label>
    <nameField>
        <label>Staging Funding Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_Funding_Opportunity_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Funding_Opportunity_Sync_Status__c</fullName>
    <description>Track progress in terms of syncing to live Funding Opportunity object</description>
    <label>Funding Opportunity Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Region Not Eligible</fullName>
            </value>
            <value>
                <fullName>No Matching Funder in PRIME</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_Primary_Funder_Id__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Primary_Funder_Id__c</fullName>
    <description>Funder Id captured from RP</description>
    <label>Primary Funder Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_PRIME_Ready__c.field-meta.xml
<CustomField>
    <fullName>I_RS_PRIME_Ready__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PRIME Ready</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/StagingFundingOppDupeDetectorController.cls
public class StagingFundingOppDupeDetectorController {

    @AuraEnabled
    public static List<Account> getPotentialDuplicateFunders(String searchTerm){
        
        System.debug('searchTerm '+searchTerm);
        
        List<Account> potentialDuplicates = [
            FIND :searchTerm
            RETURNING Account(Id, Name, I_RS_ABN__c, Website, Parent.Name WHERE I_RS_Funder_Id__c = NULL LIMIT 20)
        ][0];
        
       	System.debug('potentialDuplicates '+potentialDuplicates);
        
        return potentialDuplicates;
    }
    
    
    @InvocableMethod
    public static void markMatchingStagingOppsAsPRIMEReady(List<String> funderIdList){
        
        System.debug('markMatchingStagingOppsAsPRIMEReady');
        System.debug(funderIdList);
        
        Set<String> funderIdSet = new Set<String>(funderIdList);
        
        List<Funding_Opportunity_Staging__c> fundingOppsWithMatchingFunderId = [
            SELECT Id, Name, I_RS_Primary_Funder_Id__c from Funding_Opportunity_Staging__c WHERE 
            	I_RS_Primary_Funder_Id__c IN :funderIdSet AND
            	I_RS_Funding_Opportunity_Sync_Status__c = 'No Matching Funder in PRIME' AND 
            	I_RS_PRIME_Ready__c = false
        ];
        
        for (Funding_Opportunity_Staging__c fundingOpp : fundingOppsWithMatchingFunderId){
            fundingOpp.I_RS_PRIME_Ready__c = true;
            System.debug(fundingOpp);
        }
        
		update fundingOppsWithMatchingFunderId;
    }
    
}