force-app/main/default/objects/Account/fields/I_RS_Funder_Id__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Funder_Id__c</fullName>
    <description>Funder Id captured from RP</description>
    <label>RP Funder Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/Apex_Debug_Log__c.object-meta.xml
<CustomObject>
    <description>Captures results of non-user facing transactions such as Apex endpoints, callouts and asynchronous jobs</description>
    <label>Apex Debug Log</label>
    <nameField>
        <displayFormat>ADL-{00000000}</displayFormat>
        <label>Apex Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Funding_Opportunity_Staging__c/Funding_Opportunity_Staging__c.object-meta.xml
<CustomObject>
    <description>This object is to store funding opps coming from external system as a staging instance eg, Research Professional.</description>
    <label>Funding Opportunity Staging</label>
    <nameField>
        <label>Staging Funding Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_Funding_Opp_Sync_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Funding_Opp_Sync_Error_Message__c</fullName>
    <label>Funding Opportunity Sync Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_Funding_Opportunity_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Funding_Opportunity_Sync_Status__c</fullName>
    <description>Track progress in terms of syncing to live Funding Opportunity object</description>
    <label>Funding Opportunity Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Region Not Eligible</fullName>
            </value>
            <value>
                <fullName>No Matching Funder in PRIME</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_Primary_Funder_Id__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Primary_Funder_Id__c</fullName>
    <description>Funder Id captured from RP</description>
    <label>Primary Funder Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_Primary_Funder_Name__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Primary_Funder_Name__c</fullName>
    <description>Primary funder name from research professional</description>
    <label>Primary Funder Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_PRIME_Ready__c.field-meta.xml
<CustomField>
    <fullName>I_RS_PRIME_Ready__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PRIME Ready</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_Submission_Date__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Submission_Date__c</fullName>
    <label>Submission Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Research_Opportunity__c/Research_Opportunity__c.object-meta.xml
<CustomObject>
    <label>Funding Opportunity</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Research_Opportunity__c/fields/I_RS_Submission_Date__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Submission_Date__c</fullName>
    <inlineHelpText>The Funder&apos;s due date for the proposal</inlineHelpText>
    <label>Submission Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/FundingOppStagingToLiveSyncBatchTest.cls
@isTest
public class FundingOppStagingToLiveSyncBatchTest {
    
    static Integer recordCount = 200;
    
    public static testmethod void oneMatchingNewAccount(){
        
        Account funderOrg = TestUtility.newEmptyExternalAccount('Funder Org');
        funderOrg.I_RS_Funder_Id__c = 'TEST';
        insert funderOrg;

        List<Funding_Opportunity_Staging__c> stagingFundingOpportunities = new List<Funding_Opportunity_Staging__c>();
        for (Integer index=0; index<recordCount; index++){
            stagingFundingOpportunities.add(
                new Funding_Opportunity_Staging__c(
                    Name='Test Funding Opportunity',
                    I_RS_Primary_Funder_Id__c = 'TEST',
                    I_RS_Primary_Funder_Name__c = 'Test Org',
                    I_RS_Prime_Ready__c = true,
                    I_RS_Submission_Date__c = Date.today()
                )
            );
        }

        Test.startTest();
        insert stagingFundingOpportunities;
        Test.stopTest();
        
        stagingFundingOpportunities = [select Id, I_RS_Funding_Opportunity_Sync_Status__c , I_RS_Funding_Opp_Sync_Error_Message__c  FROM Funding_Opportunity_Staging__c];
        system.assertequals(recordCount, stagingFundingOpportunities.size());
        for (Funding_Opportunity_Staging__c fos : stagingFundingOpportunities){
            system.debug(fos);
            system.assertequals(null, fos.I_RS_Funding_Opp_Sync_Error_Message__c );
            System.assertequals('Successful', fos.I_RS_Funding_Opportunity_Sync_Status__c );
        }
        
        List<Research_Opportunity__c> fundingOpportunities = [select id, I_RS_Submission_Date__c from Research_Opportunity__c];
        System.assertequals(recordCount, fundingOpportunities.size());
        for (Research_Opportunity__c fo : fundingOpportunities){
            System.assertequals(Date.today(), fo.I_RS_Submission_Date__c );
        }
        
        System.assertequals(1, [select COUNT() FROM Account]);
    }
    
    
    
    public static testmethod void differentNewFunders(){
        
        List<Account> funderOrgs = new List<Account>();
        List<Funding_Opportunity_Staging__c> stagingFundingOpportunities = new List<Funding_Opportunity_Staging__c>();

        for (Integer index=0; index<recordCount; index++){

            Account funderOrg = TestUtility.newEmptyExternalAccount('Funder Org'+index);
            funderOrg.I_RS_Funder_Id__c = 'TEST'+index;
            funderOrgs.add(funderOrg);

            stagingFundingOpportunities.add(
                new Funding_Opportunity_Staging__c(
                    Name='Test Funding Opportunity',
                    I_RS_Primary_Funder_Id__c = 'TEST'+index,
                    I_RS_Primary_Funder_Name__c = 'Test Org'+index,
                    I_RS_Prime_Ready__c = true,
                    I_RS_Submission_Date__c = Date.today()
                )
            );
        }

        insert funderOrgs;

        Test.startTest();
        insert stagingFundingOpportunities;
        Test.stopTest();
        
        stagingFundingOpportunities = [select Id, I_RS_Funding_Opportunity_Sync_Status__c , I_RS_Funding_Opp_Sync_Error_Message__c  FROM Funding_Opportunity_Staging__c];
        system.assertequals(recordCount, stagingFundingOpportunities.size());
        for (Funding_Opportunity_Staging__c fos : stagingFundingOpportunities){
            system.debug(fos);
            system.assertequals(null, fos.I_RS_Funding_Opp_Sync_Error_Message__c );
            System.assertequals('Successful', fos.I_RS_Funding_Opportunity_Sync_Status__c );
        }
        
        List<Research_Opportunity__c> fundingOpportunities = [select id, I_RS_Submission_Date__c  from Research_Opportunity__c];
        System.assertequals(recordCount, fundingOpportunities.size());
        for (Research_Opportunity__c fo : fundingOpportunities){
            System.assertequals(Date.today(), fo.I_RS_Submission_Date__c );
        }
        
        System.assertequals(recordCount, [select COUNT() FROM Account]);
    }
    
    
    public static testmethod void oneMatchingExistingFunder(){
        
        Account funderOrg = TestUtility.newEmptyExternalAccount('Test Org');
        funderOrg.I_RS_Funder_Id__c = 'TEST';
        insert funderOrg;
        
        List<Funding_Opportunity_Staging__c> stagingFundingOpportunities = new List<Funding_Opportunity_Staging__c>();
        for (Integer index=0; index<recordCount; index++){
            stagingFundingOpportunities.add(
                new Funding_Opportunity_Staging__c(
                    Name='Test Funding Opportunity',
                    I_RS_Primary_Funder_Id__c = 'TEST',
                    I_RS_Primary_Funder_Name__c = 'Test Org',
                    I_RS_Submission_Date__c = Date.today(),
                    I_RS_Prime_Ready__c = true
                )
            );
        }
        Test.startTest();
        insert stagingFundingOpportunities;
        Test.stopTest();
        
        stagingFundingOpportunities = [select Id, I_RS_Funding_Opportunity_Sync_Status__c , I_RS_Funding_Opp_Sync_Error_Message__c  FROM Funding_Opportunity_Staging__c];
        for (Funding_Opportunity_Staging__c fos : stagingFundingOpportunities){
            system.debug(fos);
            system.assertequals(null, fos.I_RS_Funding_Opp_Sync_Error_Message__c );
            System.assertequals('Successful', fos.I_RS_Funding_Opportunity_Sync_Status__c );
        }
        
        List<Research_Opportunity__c> fundingOpportunities = [select id, I_RS_Submission_Date__c from Research_Opportunity__c];
        System.assertequals(recordCount, fundingOpportunities.size());
        for (Research_Opportunity__c fo : fundingOpportunities){
            System.assertequals(Date.today(), fo.I_RS_Submission_Date__c );
        }
        
        System.assertequals(1, [select COUNT() FROM Account]);
    }

    
    public static testmethod void differentExistingFunders(){
        
        List<Account> orgs = new List<Account>(); 
        List<Funding_Opportunity_Staging__c> stagingFundingOpportunities = new List<Funding_Opportunity_Staging__c>();
        for (Integer index=0; index<recordCount; index++){
            
            Account funderOrg = TestUtility.newEmptyExternalAccount('Test Org'+index);
            funderOrg.I_RS_Funder_Id__c = 'TEST'+index;
            orgs.add(funderOrg);
            
            stagingFundingOpportunities.add(
                new Funding_Opportunity_Staging__c(
                    Name='Test Funding Opportunity',
                    I_RS_Primary_Funder_Id__c = 'TEST'+index,
                    I_RS_Primary_Funder_Name__c = 'Test Org'+index,
                    I_RS_Prime_Ready__c = true,
                    I_RS_Submission_Date__c = Date.today()
                )
            );
        }
        insert orgs;

        Test.startTest();
        insert stagingFundingOpportunities;
        Test.stopTest();
        
        stagingFundingOpportunities = [select Id, I_RS_Funding_Opportunity_Sync_Status__c , I_RS_Funding_Opp_Sync_Error_Message__c  FROM Funding_Opportunity_Staging__c];
        system.assertequals(recordCount, stagingFundingOpportunities.size());
        for (Funding_Opportunity_Staging__c fos : stagingFundingOpportunities){
            system.debug(fos);
            system.assertequals(null, fos.I_RS_Funding_Opp_Sync_Error_Message__c );
            System.assertequals('Successful', fos.I_RS_Funding_Opportunity_Sync_Status__c );
        }
        
        List<Research_Opportunity__c> fundingOpportunities = [select id, I_RS_Submission_Date__c  from Research_Opportunity__c];
        System.assertequals(recordCount, fundingOpportunities.size());
        for (Research_Opportunity__c fo : fundingOpportunities){
            System.assertequals(Date.today(), fo.I_RS_Submission_Date__c );
        }
        
        System.assertequals(recordCount, [select COUNT() FROM Account]);
    }
    
    
    
    public static testmethod void propagateEditOnStagingToActual(){
        
        Account funderOrg = TestUtility.newEmptyExternalAccount('Funder Org');
        funderOrg.I_RS_Funder_Id__c = 'TEST';
        insert funderOrg;

        List<Funding_Opportunity_Staging__c> stagingFundingOpportunities = new List<Funding_Opportunity_Staging__c>();
        for (Integer index=0; index<recordCount; index++){
            
            stagingFundingOpportunities.add(
                new Funding_Opportunity_Staging__c(
                    Name='Test Funding Opportunity',
                    I_RS_Primary_Funder_Id__c = 'TEST',
                    I_RS_Primary_Funder_Name__c = 'Test Org',
                    I_RS_Prime_Ready__c = true,
                    I_RS_Submission_Date__c = Date.today()
                )
            );
        }
        insert stagingFundingOpportunities;
        
        Test.startTest();
        update stagingFundingOpportunities;
        Test.stopTest();
        
        System.assertEquals(recordCount, [SELECT COUNT() FROM Research_Opportunity__c]);
        
        for (Funding_Opportunity_Staging__c fos : stagingFundingOpportunities){
            fos.I_RS_Submission_Date__c = Date.today() + 1;
        }
        update stagingFundingOpportunities;
        
        
        List<Research_Opportunity__c> fundingOpportunities = [select id, I_RS_Submission_Date__c  from Research_Opportunity__c];
        System.assertequals(recordCount, fundingOpportunities.size());
        for (Research_Opportunity__c fo : fundingOpportunities){
            System.assertequals(Date.today() + 1, fo.I_RS_Submission_Date__c );
        }
        
    }
    

    public static testmethod void noMatchingFunder(){

        List<Funding_Opportunity_Staging__c> stagingFundingOpportunities = new List<Funding_Opportunity_Staging__c>();
        for (Integer index=0; index<recordCount; index++){
            
            stagingFundingOpportunities.add(
                new Funding_Opportunity_Staging__c(
                    Name='Test No Funder',
                    I_RS_Prime_Ready__c = true,
                    I_RS_Primary_Funder_Id__c = 'TEST'
                )
            );
        }
        Test.startTest();
        insert stagingFundingOpportunities;
        Test.stopTest();
        
        System.assertEquals(0, [SELECT COUNT() FROM Research_Opportunity__c]);
        System.assertEquals(0, [SELECT COUNT() FROM Apex_Debug_Log__c]);
        
        List<Funding_Opportunity_Staging__c> foss = 
            [select id, I_RS_Funding_Opportunity_Sync_Status__c, I_RS_Funding_Opp_Sync_Error_Message__c 
             from Funding_Opportunity_Staging__c];
        for (Funding_Opportunity_Staging__c fos : foss){
            System.assertEquals('No Matching Funder in PRIME', fos.I_RS_Funding_Opportunity_Sync_Status__c);
            System.assertEquals(null, fos.I_RS_Funding_Opp_Sync_Error_Message__c);
        }

    }
    
    
    public static testmethod void singleRowError(){
        
        //Error happens with a validation rule on Actual Funding Opporunity when Name = 'Error'

        Account funderOrg = TestUtility.newEmptyExternalAccount('Funder Org');
        funderOrg.I_RS_Funder_Id__c = 'TEST';
        insert funderOrg;

        List<Funding_Opportunity_Staging__c> stagingFundingOpportunities = new List<Funding_Opportunity_Staging__c>();
        for (Integer index=0; index<recordCount; index++){
            
            stagingFundingOpportunities.add(
                new Funding_Opportunity_Staging__c(
                    Name='Error',
                    I_RS_Primary_Funder_Id__c = 'TEST',
                    I_RS_Primary_Funder_Name__c = 'Test Org',
                    I_RS_Prime_Ready__c = true
                )
            );
        }
        Test.startTest();
        insert stagingFundingOpportunities;
        Test.stopTest();
        
        System.assertEquals(0, [SELECT COUNT() FROM Research_Opportunity__c]);
        System.assertequals(recordCount, [select COUNT() from Apex_Debug_Log__c]);

        List<Funding_Opportunity_Staging__c> foss = 
            [select id, I_RS_Funding_Opportunity_Sync_Status__c, I_RS_Funding_Opp_Sync_Error_Message__c 
             from Funding_Opportunity_Staging__c];
        for (Funding_Opportunity_Staging__c fos : foss){
            System.assertEquals('Failed', fos.I_RS_Funding_Opportunity_Sync_Status__c);
            System.assert(fos.I_RS_Funding_Opp_Sync_Error_Message__c != null);
        }
        
    }



    public static testmethod void totalBatchError(){

        //Assumption is a Funder Id or Name will be provided, so not having it is how we
        //test a total batch failure

        FundingOppStagingToLiveSync.throwError = true;

        Account funderOrg = TestUtility.newEmptyExternalAccount('Funder Org');
        funderOrg.I_RS_Funder_Id__c = 'TEST';
        insert funderOrg;
    
        List<Funding_Opportunity_Staging__c> stagingFundingOpportunities = new List<Funding_Opportunity_Staging__c>();
        for (Integer index=0; index<recordCount; index++){
            
            stagingFundingOpportunities.add(
                new Funding_Opportunity_Staging__c(
                    Name='Error',
                    I_RS_Prime_Ready__c = true,
                    I_RS_Primary_Funder_Id__c = 'TEST'
                )
            );
        }
        Test.startTest();
        insert stagingFundingOpportunities;
        Test.stopTest();
        
        System.assertEquals(0, [SELECT COUNT() FROM Research_Opportunity__c]);
        System.assertEquals(1, [SELECT COUNT() FROM Apex_Debug_Log__c]);
        
        List<Funding_Opportunity_Staging__c> foss = 
            [select id, I_RS_Funding_Opportunity_Sync_Status__c, I_RS_Funding_Opp_Sync_Error_Message__c 
             from Funding_Opportunity_Staging__c];
        for (Funding_Opportunity_Staging__c fos : foss){
            System.assertEquals('Failed', fos.I_RS_Funding_Opportunity_Sync_Status__c);
            System.assert(fos.I_RS_Funding_Opp_Sync_Error_Message__c != null);
        }


    }
    
    
}