force-app/main/default/objects/Account/fields/I_RS_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Proposed</fullName>
                <isActive>false</isActive>
                <label>Proposed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Classification_Code__c/Classification_Code__c.object-meta.xml
<CustomObject>
    <description>Describes the relationship between a Classification Master and various objects</description>
    <label>Classification Code</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Title</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classification Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification_Code__c/fields/I_RS_Percentage__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Percentage__c</fullName>
    <description>The amount of the project that is classified with the classification code</description>
    <label>Percentage</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Classification_Master__c/Classification_Master__c.object-meta.xml
<CustomObject>
    <label>Classification Master</label>
    <nameField>
        <label>Classification Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classification Masters</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/I_RS_Related_User__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Related_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Refers to the user record associated to the contact</description>
    <label>Related User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_ST_Personal_Email__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Personal_Email__c</fullName>
    <description>Created to allow user to store personal email</description>
    <externalId>true</externalId>
    <inlineHelpText>The personal email for this person.</inlineHelpText>
    <label>Student Lead Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/I_RM_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Part of the remediation project to store different personas</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Contact__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Contact__c</fullName>
    <description>The person/contact who this Affiliation relates to</description>
    <inlineHelpText>The person this affiliation relates to</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Affiliations</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Email__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Email__c</fullName>
    <description>Depicts Personal Email</description>
    <inlineHelpText>The personal email for this person.</inlineHelpText>
    <label>Personal Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Mobile_Phone__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Mobile_Phone__c</fullName>
    <description>Depicts affiliation&apos;s Mobile Phone number</description>
    <label>Mobile Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Role__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Role__c</fullName>
    <description>This represents the role of the affiliation</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Domestic Lead</fullName>
                <label>Student Lead (Dom)</label>
            </value>
            <value>
                <fullName>Applicant</fullName>
                <label>Student Applicant (Dom)</label>
            </value>
            <value>
                <fullName>La Trobe Staff</fullName>
            </value>
            <value>
                <fullName>School Representative</fullName>
                <label>Secondary School Representative</label>
            </value>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>External Contact</fullName>
            </value>
            <value>
                <fullName>HDR Student</fullName>
                <label>Graduate Researcher</label>
            </value>
            <value>
                <fullName>Student Lead (Int)</fullName>
            </value>
            <value>
                <fullName>Nominated Affiliation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <description>Indicates the status of the Affiliation.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>I_RM_Role__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>I_ST_Contact_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_IL_Student_Lead_Int.recordType-meta.xml
<RecordType>
    <fullName>I_IL_Student_Lead_Int</fullName>
    <active>true</active>
    <description>New International Lead who can be a prospective student of La Trobe University</description>
    <label>Student Lead (Int)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_Applicant.recordType-meta.xml
<RecordType>
    <fullName>I_RM_Applicant</fullName>
    <active>true</active>
    <description>An individual who has applied to study at La Trobe University</description>
    <label>Student Applicant (Dom)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_La_Trobe_Staff.recordType-meta.xml
<RecordType>
    <fullName>I_RM_La_Trobe_Staff</fullName>
    <active>true</active>
    <description>La Trobe staff member</description>
    <label>La Trobe Staff</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_Lead.recordType-meta.xml
<RecordType>
    <fullName>I_RM_Lead</fullName>
    <active>true</active>
    <description>New Domestic Lead who is a prospective student of La Trobe University</description>
    <label>Student Lead (Dom)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/I_RM_Affiliation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Affiliation Settings</label>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Proposal__c/Project_Proposal__c.object-meta.xml
<CustomObject>
    <description>Project Proposal: An application for funding either through a grant request, a tender response, or a contract proposal.
Project: The work that is undertaken to satisfy a commitment made to a funding body or client.  The commitment is likely to be a contract (and possible variations) resulting from the acceptance of a project proposal.  This occurs after a grant, contract of philanthropic donation has been awarded.</description>
    <label>Project Proposal</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Proposal__c/fields/I_RS_Approval_Flag__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Approval_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>this is an internal field (not to be visible for user) used to restrict user to manually sett status to &quot;Approvals&quot;</description>
    <label>Approval Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_Proposal__c/fields/I_RS_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PlaceHolder</fullName>
            </value>
            <value>
                <fullName>Create Proposal</fullName>
            </value>
            <value>
                <fullName>Proposal Review</fullName>
            </value>
            <value>
                <fullName>Recommended</fullName>
            </value>
            <value>
                <fullName>Dismissed</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Create EOI</fullName>
            </value>
            <value>
                <fullName>Drafting NOI</fullName>
            </value>
            <value>
                <fullName>Final draft</fullName>
            </value>
            <value>
                <fullName>Draft Proposal</fullName>
            </value>
            <value>
                <fullName>Provide Project Details</fullName>
            </value>
            <value>
                <fullName>Contract Instructions</fullName>
            </value>
            <value>
                <fullName>Review by Research Office</fullName>
            </value>
            <value>
                <fullName>Panel Review</fullName>
            </value>
            <value>
                <fullName>HoS NOI Validation</fullName>
            </value>
            <value>
                <fullName>Pitch Session</fullName>
            </value>
            <value>
                <fullName>Peer review draft</fullName>
            </value>
            <value>
                <fullName>Peer review draft complete</fullName>
            </value>
            <value>
                <fullName>Review Contract</fullName>
            </value>
            <value>
                <fullName>Draft contract</fullName>
            </value>
            <value>
                <fullName>Approvals</fullName>
            </value>
            <value>
                <fullName>Formalise Contract</fullName>
            </value>
            <value>
                <fullName>Submission to Client</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Ready for Submission to Funding Body</fullName>
            </value>
            <value>
                <fullName>Submission to Funding Body</fullName>
                <label>Funding Body Submission</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Rejoinders</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Proposal__c/recordTypes/I_RS_Proposal.recordType-meta.xml
<RecordType>
    <fullName>I_RS_Proposal</fullName>
    <active>true</active>
    <label>Proposal</label>
</RecordType>

force-app/main/default/objects/Research_Opportunity__c/Research_Opportunity__c.object-meta.xml
<CustomObject>
    <label>Funding Opportunity</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Research_Opportunity__c/fields/I_RS_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initial</fullName>
                <default>true</default>
                <label>Initial</label>
            </value>
            <value>
                <fullName>Drafted</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Internal Applications Closed</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Research_Opportunity_Team_Member__c/Research_Opportunity_Team_Member__c.object-meta.xml
<CustomObject>
    <label>Funding Opportunity Team Member</label>
    <nameField>
        <label>Funding Opportunity Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunity Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Research_Opportunity_Team_Member__c/fields/I_RS_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/I_ST_Contact_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Admitted</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And LOA</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Not Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Considered</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Made</fullName>
    </customValue>
    <customValue>
        <fullName>Await Academic Advice</fullName>
    </customValue>
    <customValue>
        <fullName>Await Applicant Comms</fullName>
    </customValue>
    <customValue>
        <fullName>Await Further Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Awaiting Interview</fullName>
    </customValue>
    <customValue>
        <fullName>Await Required Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Escalated</fullName>
    </customValue>
    <customValue>
        <fullName>Make A Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make Alternate Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make An Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Nearing Completion</fullName>
    </customValue>
    <customValue>
        <fullName>Not Processed</fullName>
    </customValue>
    <customValue>
        <fullName>Not Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Lapsed</fullName>
    </customValue>
    <customValue>
        <fullName>Other Preference Offered</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Results</fullName>
    </customValue>
    <customValue>
        <fullName>Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <description>Global value set is created for lead(contact) object ST -51</description>
    <masterLabel>I_ST_Contact_Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContentDocumentTriggerHelperTest.cls
//Test class for ContentDocument trigger
@IsTest
public class ContentDocumentTriggerHelperTest {
  public static Id affiliationStaffRecordTypeId = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_La_Trobe_Staff').getRecordTypeId();
    
    @testSetup static void setup() {

        String recTypeIdsForAffScoring = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Applicant').getRecordTypeId();
        recTypeIdsForAffScoring += ',' + Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Lead').getRecordTypeId();
        recTypeIdsForAffScoring += ',' + Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_IL_Student_Lead_Int').getRecordTypeId();
        TestUtility.createBatchScoringCustomSettings(recTypeIdsForAffScoring);
        
        Account testAcc = TestUtility.newEmptyExternalAccount('Test LTU Account');
        Insert testAcc;
        
        I_RM_Affiliation_Settings__c objAffiliationSettings = I_ST_UnitTestUtilities.createAffiliationSettings();
        insert objAffiliationSettings;
        
        Contact testContact = TestUtility.newContact(testAcc.Id);
        testContact.FirstName = 'Test Contact';
        testContact.LastName = 'LTU';
        insert testContact;
        
        //Contact  = [SELECT Id FROM Contact WHERE I_ST_Personal_Email__c='test_unique0012@unique.com'];
        I_RM_Affiliation__c aff=new I_RM_Affiliation__c(RecordTypeID = affiliationStaffRecordTypeId,
                                                        I_RM_Contact__c=testContact.Id,
                                                        I_RM_Role__c='La Trobe Staff',I_RM_Email__c='caseoftypeenquiry@ibm.com',
                                                        I_RM_Status__c='Active',
                                                        I_RM_Mobile_Phone__c='0415822666');
        insert aff;
    }
    
    private static Id getProjectPropsalRecTypeIdByDevName (String recordTypeAPIName) {
        return Schema.SObjectType.Project_Proposal__c.getRecordTypeInfosByDeveloperName().get(recordTypeAPIName).getRecordTypeId();
    }
    
    static testMethod void testDeleteFileErrorWhenParentLocked() {
        
        Profile profile1 = [SELECT Id FROM Profile WHERE name = 'LTU Partner Community Login User' Limit 1];
        
        Account queryTestAcc = [Select Id FROM Account Where Name = 'Test LTU Account'];
        
        Contact queryTestCon = [Select Id FROM Contact Where FirstName = 'Test Contact' AND LastName = 'LTU'];
        
        User testCommunityUser = TestUtility.newUser('test', profile1.Id, null, queryTestCon.Id);
        insert testCommunityUser;
        System.debug('-->testCommunityUser--> '+testCommunityUser);
        
        Network testCommunityNetwork = [Select Id From Network Where Name = 'PRIME Researcher Portal'];
        System.debug('testCommunityNetwork'+testCommunityNetwork);
        Test.startTest();
        //System.runAs(testCommunityUser){
        
        List<sObject> sObjectList = new List<sObject>();
        
        Project_Proposal__c projectProposalUnLocked = TestUtility.newProjectProposal();
        projectProposalUnLocked.Name = 'LockedProposal';
        projectProposalUnLocked.RecordTypeId = getProjectPropsalRecTypeIdByDevName('I_RS_Proposal');
        projectProposalUnLocked.I_RS_Status__c = 'Draft Proposal';
        projectProposalUnLocked.OwnerId = testCommunityUser.Id;
        
        sObjectList.add((Project_Proposal__c) projectProposalUnLocked);
        
        Blob testBlobFile1 = Blob.valueOf('Testing Content Version');
        
        //Insert test content version for the draft proposal
        ContentVersion testCv1 = new ContentVersion();
        testCV1.title = 'test content trigger error1';
        testCV1.PathOnClient ='test';
        testCV1.VersionData = testBlobFile1;
        testCV1.IsMajorVersion = true;
        testCV1.NetworkId = testCommunityNetwork.Id;
        
        sObjectList.add((ContentVersion) testCV1);
        
        Classification_Master__c testClassficationMaster = TestUtility.newClassificationMaster('TestCls001','2610','Type of Activity (TOA)',true);
        sObjectList.add((Classification_Master__c) testClassficationMaster);
        
        Insert sObjectList;
        System.debug('--> testClassficationMaster -->'+testClassficationMaster);
        
        Classification_Code__c testClassficationCode = TestUtility.newClassificationCode(testClassficationMaster.Id,null,projectProposalUnLocked.Id,null);
        testClassficationCode.I_RS_Percentage__c = 100;
        testClassficationCode.RecordTypeId = Schema.SObjectType.Classification_Code__c.getRecordTypeInfosByName().get('Type of Activity (TOA) codes').getRecordTypeId();
        Insert testClassficationCode;
        System.debug('--> testClassficationCode -->'+testClassficationCode.Id);
        System.debug('--> testClassficationCode -->'+testClassficationCode.I_RS_Percentage__c);
        
        
        List<ContentDocument> documents1 = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument Where Title = 'test content trigger error1'];
        System.debug('--> documents -->'+documents1);
        
        ContentDocumentLink testContentDoclink1 = new ContentDocumentLink();
        testContentDoclink1.LinkedEntityId = projectProposalUnLocked.Id;
        testContentDoclink1.ContentDocumentId = documents1[0].Id;
        testContentDoclink1.ShareType = 'I';
        
        Insert testContentDoclink1;
        
        Project_Proposal__c updatedProjectProposalToLock = new Project_Proposal__c(Id = projectProposalUnLocked.Id, I_RS_Status__c = 'Approvals', I_RS_Approval_Flag__c = true);
        Update updatedProjectProposalToLock;
        
        ContentDocument delConentDoc = [Select Id,Title FROM ContentDocument WHERE Title = 'test content trigger error1'];
        System.debug('--> documents 1-->'+delConentDoc);
        System.runAs(testCommunityUser){
            
            try {
                Delete delConentDoc;
            }
            catch (Exception e) {
                System.debug('--> Error Message--> '+e.getMessage());
                Boolean expectedExceptionThrown =  e.getMessage().contains('Project proposal is currently locked down until Research Office has approved') ? true : false;
                System.AssertEquals(expectedExceptionThrown, true);
            }
        }
        Test.stopTest();
    }
    
    static testMethod void testDeleteFileErrorForFundingOpportunity() {
        
        Test.startTest();
        Profile profile1 = [SELECT Id FROM Profile WHERE name = 'LTU Partner Community User' Limit 1];
        
        Account queryTestAcc = [Select Id FROM Account Where Name = 'Test LTU Account'];
        
        Contact queryTestCon = [Select Id FROM Contact Where FirstName = 'Test Contact' AND LastName = 'LTU'];
        
        User testCommunityUser = TestUtility.newUser('test', profile1.Id, null, queryTestCon.Id);
        insert testCommunityUser;
        
        queryTestCon.I_RS_Related_User__c = testCommunityUser.Id;
        update queryTestCon;
        System.debug('-->testCommunityUser--> '+testCommunityUser);
        System.debug('-->testCommunityUser.id--> '+testCommunityUser.id);
        
        
        Blob testBlobFile1 = Blob.valueOf('Testing Content Version');
        Research_Opportunity__c roRec = TestUtility.newResearchOpportunity(false);
        insert roRec;
        
        Research_Opportunity_Team_Member__c roTM = TestUtility.newFundingOpportunityTeamMember(roRec.Id, queryTestCon.Id, testCommunityUser.Id );
        insert roTM;
        System.debug('-->ROTM-->'+roTM);
        System.debug('--> RowCause for ROTM --> '+Schema.Research_Opportunity__Share.rowCause.Research_Opportunity_Team_Member__c);
        List<Research_Opportunity__Share> listROShare = [Select Id,UserOrGroupId,ParentId, RowCause
                                                         FROM Research_Opportunity__Share 
                                                         WHERE ParentId = :roRec.Id AND UserOrGroupId = :testCommunityUser.Id];
        System.debug('--> listROShare--> '+listROShare);
        
        /*System.debug('-->Funding Opp. Apex Sharing-->'+[Select Id,UserOrGroupId,ParentId 
        FROM Research_Opportunity__Share 
        WHERE ParentId = :roRec.Id AND RowCause = 'Research_Opportunity_Team_Member__c']);  */
        System.debug('-->RO Id-->'+roRec.Id);
        System.debug('-->ROTM Id-->'+roTM.Id);
        Network testCommunityNetwork = [Select Id From Network Where Name = 'PRIME Researcher Portal'];
        System.debug('testCommunityNetwork'+testCommunityNetwork);
        
        //Insert test content version for the draft proposal
        ContentVersion testCv1 = new ContentVersion();
        testCV1.title = 'test content trigger error1';
        testCV1.PathOnClient ='test';
        testCV1.VersionData = testBlobFile1;
        testCV1.IsMajorVersion = true;
        testCV1.NetworkId = testCommunityNetwork.Id;
        
        insert testCV1;
        
        
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument Where Title = 'test content trigger error1'];
        System.debug('--> documents -->'+documents);
        
        ContentDocumentLink testContentDoclink1 = new ContentDocumentLink();
        testContentDoclink1.LinkedEntityId = roRec.Id;
        testContentDoclink1.ContentDocumentId = documents[0].Id;
        testContentDoclink1.ShareType = 'I';
        testContentDoclink1.Visibility = 'AllUsers';
        
        Insert testContentDoclink1;
        
        System.debug('Document access: ' + [Select RecordId, HasReadAccess, HasEditAccess, HasDeleteAccess FROM UserRecordAccess WHERE UserId = :testCommunityUser.Id AND RecordId = :documents[0].Id ]);
        ContentDocument delConentDoc1 = [Select Id,Title FROM ContentDocument LIMIT 1];
        System.debug('--> documents befor -->'+delConentDoc1);
        
        
        System.runAs(testCommunityUser){
            
            try {
                //ContentDocument delConentDoc = [Select Id,Title FROM ContentDocument WHERE Title = 'test content trigger error1' LIMIT 1];
                ContentDocument delConentDoc = [Select Id FROM ContentDocument WHERE ID = :testContentDoclink1.ContentDocumentId LIMIT 1];
                System.debug('--> documents -->'+delConentDoc);
                delete delConentDoc;
            }
            catch (Exception e) {
                System.debug('--> Error Message--> '+e.getMessage());
                Boolean expectedExceptionThrown =  e.getMessage().contains(GlobalConstants.RESTRICT_DOCUMENT_UPLOAD_BY_RESEARCHER) ? true : false;
                System.AssertEquals(expectedExceptionThrown, true);
            }
        }
        Test.stopTest();
    }
}