force-app/main/default/objects/Account/fields/I_RS_Part_of_La_Trobe__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Part_of_La_Trobe__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Part of La Trobe</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Budget__c/Budget__c.object-meta.xml
<CustomObject>
    <description>This is the summarised budget header details that goes for approval &amp; is maintained in system for any further progress, tracking or finance integration</description>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget_Line_Item__c/Budget_Line_Item__c.object-meta.xml
<CustomObject>
    <description>This will capture the calculated budget line details from Budget Calculator tool. Please note that Budget Calculator will be a custom developed tool built &amp; integrated with Salesforce. Later the calculated values will be stored in this object.</description>
    <label>Budget Line Item</label>
    <nameField>
        <displayFormat>BLI-{00000}</displayFormat>
        <label>Budget Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_In_Kind__c.field-meta.xml
<CustomField>
    <fullName>I_RS_In_Kind__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Tick for In-Kind. Untick for In-Cash.</inlineHelpText>
    <label>In Kind</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Organisation__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Budget Line Items</relationshipLabel>
    <relationshipName>Budget_Line_Items_Org</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Part_of_La_Trobe__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Part_of_La_Trobe__c</fullName>
    <formula>I_RS_Organisation__r.I_RS_Part_of_La_Trobe__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Part of La Trobe</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/recordTypes/I_RS_Collaborator_SubContractor.recordType-meta.xml
<RecordType>
    <fullName>I_RS_Collaborator_SubContractor</fullName>
    <active>true</active>
    <label>Collaborator/SubContractor</label>
</RecordType>

force-app/main/default/objects/Budget_Line_Item__c/recordTypes/I_RS_Salary.recordType-meta.xml
<RecordType>
    <fullName>I_RS_Salary</fullName>
    <active>true</active>
    <label>Salary</label>
</RecordType>

force-app/main/default/objects/Junction_Linkage__c/Junction_Linkage__c.object-meta.xml
<CustomObject>
    <description>If there is a linkage opportunity, this object will hold relationship between organisation and the Research Opportunity (Funding Scheme / Opportunity / Collaboration / Sub-Contract/Share)</description>
    <label>Funding Details</label>
    <nameField>
        <label>Funding Details Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Junction_Linkage__c/fields/I_RS_Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Relationship_Type__c</fullName>
    <label>Relationship Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Funding Body</fullName>
            </value>
            <value>
                <fullName>Other Organisation</fullName>
            </value>
            <value>
                <fullName>La Trobe Internal Cash</fullName>
            </value>
            <value>
                <fullName>La Trobe External Cash</fullName>
            </value>
            <value>
                <fullName>La Trobe In-kind</fullName>
            </value>
            <value>
                <fullName>Administering Organisation</fullName>
                <isActive>false</isActive>
                <label>Administering Organisation</label>
            </value>
            <value>
                <fullName>Collaborator</fullName>
                <isActive>false</isActive>
                <label>Collaborator</label>
            </value>
            <value>
                <fullName>Internal</fullName>
                <isActive>false</isActive>
                <label>Internal</label>
            </value>
            <value>
                <fullName>La Trobe Contribution</fullName>
                <isActive>false</isActive>
                <label>La Trobe Contribution</label>
            </value>
            <value>
                <fullName>Sub-Contractor</fullName>
                <isActive>false</isActive>
                <label>Sub-Contractor</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Proposal__c/Project_Proposal__c.object-meta.xml
<CustomObject>
    <description>Project Proposal: An application for funding either through a grant request, a tender response, or a contract proposal.
Project: The work that is undertaken to satisfy a commitment made to a funding body or client.  The commitment is likely to be a contract (and possible variations) resulting from the acceptance of a project proposal.  This occurs after a grant, contract of philanthropic donation has been awarded.</description>
    <label>Project Proposal</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Proposal__c/fields/I_RS_Account_Organisation__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Account_Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Organisation</description>
    <inlineHelpText>Search to find the Funder. If it does not already exist leave this blank and add the Funder&apos;s name to the Comments field.</inlineHelpText>
    <label>Funder</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Project Proposals</relationshipLabel>
    <relationshipName>Project_Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BudgetToFundingDetailSyncTest.cls
@isTest
public with sharing class BudgetToFundingDetailSyncTest {
   
    public static testmethod void budgetToFundingDetailSyncTest(){

        Budget__c budget = [select Id from Budget__c];
        List<Id> budgetIdList = new List<Id>{budget.Id};

        //Get Orgs in seperate lists?
        List<Account> ltuOrgs = [select Id from Account where I_RS_Part_of_La_Trobe__c = true];
        List<Account> extOrgs = [select Id from Account where I_RS_Part_of_La_Trobe__c = false];

        //Get record type Ids
        
        
        //'I_RS_Collaborator_SubContractor'
        

        List<Budget_Line_Item__c> budgetLineItems = new List<Budget_Line_Item__c>();

        
        
        for (Account ltuOrg : ltuOrgs){

            List<Budget_Line_Item__c> budgetLineItemsForOrg = new List<Budget_Line_Item__c>();


            //Create some la trobe funder cash
            Budget_Line_Item__c ltuFunderInCash = 
                TestUtility.newBudgetLineItem(budget.Id, 'I_RS_Salary', 10000);
            ltuFunderInCash.I_RS_Organisation__c = ltuOrg.Id;

            //Add twice to test rollups
            budgetLineItemsForOrg.add(ltuFunderInCash);
            ltuFunderInCash = ltuFunderInCash.clone(false, false, false, false);
            budgetLineItemsForOrg.add(ltuFunderInCash);


            Budget_Line_Item__c ltuFunderInKind = 
                TestUtility.newBudgetLineItem(budget.Id, 'I_RS_Salary', 10000);
            ltuFunderInKind.I_RS_In_Kind__c = true;
            ltuFunderInKind.I_RS_Organisation__c = ltuOrg.Id;

            budgetLineItemsForOrg.add(ltuFunderInKind);
            ltuFunderInKind = ltuFunderInCash.clone(false, false, false, false);
            budgetLineItemsForOrg.add(ltuFunderInKind);


            insert budgetLineItemsForOrg;
            budgetLineItems.addAll(budgetLineItemsForOrg);
        }


        Test.startTest();
        
        BudgetToFundingDetailSync.budgetToFundingDetailSync(budgetIdList);

        Test.stopTest();

    }


    


    @TestSetup
    static void makeData(){
        
        Account LaTrobeUniversity = TestUtility.newEmptyLTUAccount('La Trobe University');
        insert LaTrobeUniversity;

        Project_Proposal__c projectProposal = TestUtility.newProjectProposal();
        //projectProposal.I_RS_Account_Organisation__c = LaTrobeUniversity.Id;
        insert projectProposal;

        
        /*Junction_Linkage__c preExistingFundingDetailDontDelete = TestUtility.newJunctionLinkage(projectOrg.Id, projectProposal.Id, null);
        preExistingFundingDetailDontDelete.Name = 'Do Not Delete';
        preExistingFundingDetailDontDelete.I_RS_Relationship_Type__c = 'Administering Organisation';*/

        Junction_Linkage__c preExistingFundingDetailToDelete = TestUtility.newJunctionLinkage(null/*LaTrobeUniversity.Id*/, projectProposal.Id, null);
        preExistingFundingDetailToDelete.Name = 'Delete';
        
        List<Junction_Linkage__c> preExistingFundingDetails = new List<Junction_Linkage__c>{
            //preExistingFundingDetailDontDelete,
            preExistingFundingDetailToDelete
        };
        insert preExistingFundingDetails;


        Budget__c budget = TestUtility.newBudget(projectProposal.Id);
        insert budget;

        


        List<Account> fundersAndProvidedToOrgs = new List<Account>();
        for (Integer i=0; i<5; i++){
            Account ltuOrg = TestUtility.newEmptyLTUAccount('LTU Org '+i);
            ltuOrg.ParentId = LaTrobeUniversity.Id;
            
            Account extOrg = TestUtility.newEmptyExternalAccount('Ext Org '+i);
            fundersAndProvidedToOrgs.add(ltuOrg);
            fundersAndProvidedToOrgs.add(extOrg);
        }
        insert fundersAndProvidedToOrgs;




        List<Budget_Line_Item__c> budgetLineItems = new List<Budget_Line_Item__c>();
        

    }

}