force-app/main/default/objects/Account/fields/I_RS_Funder_Id__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Funder_Id__c</fullName>
    <description>Funder Id captured from RP</description>
    <label>RP Funder Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/Funding_Opportunity_Staging__c.object-meta.xml
<CustomObject>
    <description>This object is to store funding opps coming from external system as a staging instance eg, Research Professional.</description>
    <label>Funding Opportunity Staging</label>
    <nameField>
        <label>Staging Funding Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_Primary_Funder_Id__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Primary_Funder_Id__c</fullName>
    <description>Funder Id captured from RP</description>
    <label>Primary Funder Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_Primary_Funder_Name__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Primary_Funder_Name__c</fullName>
    <description>Primary funder name from research professional</description>
    <label>Primary Funder Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_PRIME_Ready__c.field-meta.xml
<CustomField>
    <fullName>I_RS_PRIME_Ready__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PRIME Ready</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_RP_ID__c.field-meta.xml
<CustomField>
    <fullName>I_RS_RP_ID__c</fullName>
    <label>RP ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Research_Opportunity__c/Research_Opportunity__c.object-meta.xml
<CustomObject>
    <label>Funding Opportunity</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Research_Opportunity__c/fields/I_RS_Organisation__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Funder</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>La Trobe Organisation Unit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Funding Opportunities</relationshipLabel>
    <relationshipName>Research_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Research_Opportunity__c/fields/I_RS_RP_ID__c.field-meta.xml
<CustomField>
    <fullName>I_RS_RP_ID__c</fullName>
    <label>RP ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StagingFundingOppDupeDetectorTest.cls
@isTest
public class StagingFundingOppDupeDetectorTest {

    public static testmethod void getPotentialDuplicateFunders(){
        
        Account funderOrg = TestUtility.newEmptyExternalAccount('funderOrg');
        insert funderOrg;
        
        Test.setFixedSearchResults(new List<String>{(String) funderOrg.Id});
		
        System.assert(StagingFundingOppDupeDetectorController.getPotentialDuplicateFunders('funderOrg').size() > 0);
        
    }
    
    
    public static testmethod void markMatchingStagingOppsAsPRIMEReady(){
        
        List<Account> funderOrgs = new List<Account>{
            TestUtility.newEmptyExternalAccount('funderOrg1'),
            TestUtility.newEmptyExternalAccount('funderOrg2')
		};
        insert funderOrgs;
        
        List<Funding_Opportunity_Staging__c> stagingOpps = new List<Funding_Opportunity_Staging__c>();
        for (Integer i=0; i<100; i++){
            
            stagingOpps.addAll(new List<Funding_Opportunity_Staging__c>{
                new Funding_Opportunity_Staging__c(
                    I_RS_PRIME_Ready__c = true,
                    I_RS_RP_Id__c = 'RPID1'+i,
                    I_RS_Primary_Funder_Id__c = 'FUNDER1',
                    I_RS_Primary_Funder_Name__c = 'FUNDER1'
                ),
                new Funding_Opportunity_Staging__c(
                    I_RS_PRIME_Ready__c = true,
                    I_RS_RP_Id__c = 'RPID1'+i,
                    I_RS_Primary_Funder_Id__c = 'FUNDER2',
                    I_RS_Primary_Funder_Name__c = 'FUNDER2'
                )
            });
        }
        insert stagingOpps;
        
        System.assertequals(0, [SELECT COUNT() FROM Research_Opportunity__c]);
        
        funderOrgs[0].I_RS_Funder_Id__c = 'FUNDER1';
        funderOrgs[1].I_RS_Funder_Id__c = 'FUNDER2';
        update funderOrgs;
        
        StagingFundingOppDupeDetectorController.markMatchingStagingOppsAsPRIMEReady(new List<String>{'FUNDER1','FUNDER2'});
        
        System.assertequals(100, [SELECT COUNT() FROM Research_Opportunity__c WHERE I_RS_Organisation__c = :funderORgs[0].Id]);
        System.assertequals(100, [SELECT COUNT() FROM Research_Opportunity__c WHERE I_RS_Organisation__c = :funderORgs[1].Id]);
    }
    
}