force-app/main/default/objects/Account/fields/I_RS_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Proposed</fullName>
                <isActive>false</isActive>
                <label>Proposed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/Apex_Debug_Log__c.object-meta.xml
<CustomObject>
    <description>Captures results of non-user facing transactions such as Apex endpoints, callouts and asynchronous jobs</description>
    <label>Apex Debug Log</label>
    <nameField>
        <displayFormat>ADL-{00000000}</displayFormat>
        <label>Apex Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Apex_Class_Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Method_Name__c</fullName>
    <label>Apex Class Method Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <description>The invoking class that created the record</description>
    <label>Apex Class Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <description>If an exception occurs, this is the main message</description>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Exception_stack_trace__c.field-meta.xml
<CustomField>
    <fullName>Exception_stack_trace__c</fullName>
    <description>If an exception occurs, this is the stack trace</description>
    <label>Exception stack trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>A legally binding document that defines the obligations to which the contractual parties involved in conducting the research must adhere.</description>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/I_RS_Contract__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hierarchy or related contracts in case of renewal or amendments</description>
    <inlineHelpText>Select an existing Agreement if this request is for Variations or Subcontract/Collaboration requests.</inlineHelpText>
    <label>Parent Agreement</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Child Agreements</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/I_RS_Organisation__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Organisation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Include the main Organisation for the Agreement. For Researcher Portal users if the organisation is not available, please include details in the Reasons for Agreement or Variation above.</inlineHelpText>
    <label>Organisation Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>You can only select Educational Institution or External Organisation record types</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Educational Institution</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>External Organisation</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/I_RS_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Status__c</fullName>
    <inlineHelpText>“Executed” is when the Agreement/Variation has been signed and is active.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Initial</fullName>
            </value>
            <value>
                <fullName>Preparing Instructions</fullName>
            </value>
            <value>
                <fullName>Instructions</fullName>
            </value>
            <value>
                <fullName>Engage Legal to Draft Variation</fullName>
            </value>
            <value>
                <fullName>Update Variation</fullName>
            </value>
            <value>
                <fullName>Notify Appropriate Stakeholders</fullName>
            </value>
            <value>
                <fullName>Create Letter</fullName>
                <label>Create Variation</label>
            </value>
            <value>
                <fullName>Completing Template</fullName>
            </value>
            <value>
                <fullName>Engage Legal to Draft Contract</fullName>
            </value>
            <value>
                <fullName>Reviewing Draft</fullName>
            </value>
            <value>
                <fullName>Client Review</fullName>
                <label>Other Party Review</label>
            </value>
            <value>
                <fullName>Legal Review</fullName>
            </value>
            <value>
                <fullName>Update Contract</fullName>
            </value>
            <value>
                <fullName>Researcher Review</fullName>
            </value>
            <value>
                <fullName>With Other Party</fullName>
            </value>
            <value>
                <fullName>La Trobe Signature</fullName>
            </value>
            <value>
                <fullName>Send to Client</fullName>
                <label>Send to Other Party</label>
            </value>
            <value>
                <fullName>Client Countersign</fullName>
                <label>Other Party Countersign</label>
            </value>
            <value>
                <fullName>Receive Client Signed Copy</fullName>
                <label>Receive Other Party Signed Copy</label>
            </value>
            <value>
                <fullName>Receive Executed Copy</fullName>
            </value>
            <value>
                <fullName>Notify of Variation Outcome</fullName>
            </value>
            <value>
                <fullName>La Trobe Countersign</fullName>
            </value>
            <value>
                <fullName>La Trobe University Signature</fullName>
            </value>
            <value>
                <fullName>Send Signed Copy Back</fullName>
            </value>
            <value>
                <fullName>Submit to Research Office</fullName>
            </value>
            <value>
                <fullName>Return Signed Copy to Client</fullName>
                <label>Return Signed Copy to Other Party</label>
            </value>
            <value>
                <fullName>Executed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/fields/L_PR_isPrimary__c.field-meta.xml
<CustomField>
    <fullName>L_PR_isPrimary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isPrimary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Related_Contract__c/Related_Contract__c.object-meta.xml
<CustomObject>
    <label>Related Organisation</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Related Organisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Contract__c/fields/I_RS_Contract__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Contract__c</fullName>
    <label>Agreement</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Related Organisations</relationshipLabel>
    <relationshipName>Related_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Related_Contract__c/fields/I_RS_Organisation__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Agreements</relationshipLabel>
    <relationshipName>Related_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Contract__c/fields/L_PR_Agreement_Recordtype__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Agreement_Recordtype__c</fullName>
    <label>Agreement Record Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Related_Contract__c/fields/L_PR_Agreement_Status__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Agreement_Status__c</fullName>
    <label>Agreement Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_Matrix__c/Task_Matrix__c.object-meta.xml
<CustomObject>
    <description>This object holds list of standard set of tasks that will be used to create standard Tasks for Project Proposal object</description>
    <label>Task Matrix</label>
    <nameField>
        <displayFormat>TM-{00000}</displayFormat>
        <label>Task Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Matrices</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Matrix__c/fields/I_RS_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Object_Name__c</fullName>
    <description>Label/API Name of the Salesforce Object for which the &quot;tasks&quot; need to be created at the creation of project proposal or whenever the status of project proposal changes</description>
    <inlineHelpText>Label/API Name of the Salesforce Object for which the &quot;tasks&quot; need to be created at the creation of project proposal or whenever the status of project proposal changes</inlineHelpText>
    <label>Object Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Project_Proposal__c</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
                <default>true</default>
                <label>Opportunity</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Matrix__c/fields/L_PR_Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Agreement_Type__c</fullName>
    <label>Agreement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Articulation Agreement</fullName>
            </value>
            <value>
                <fullName>Clinical Education Agreements (health)</fullName>
            </value>
            <value>
                <fullName>Clinical Trial Site Agreement</fullName>
            </value>
            <value>
                <fullName>Commercialisation Agreement</fullName>
            </value>
            <value>
                <fullName>Commercialisation Licence</fullName>
            </value>
            <value>
                <fullName>Confidentiality agreements</fullName>
            </value>
            <value>
                <fullName>Consulting Services Agreement (Non-Research)</fullName>
            </value>
            <value>
                <fullName>Contractors Agreement (services to LTU)</fullName>
            </value>
            <value>
                <fullName>Courseware Licensing</fullName>
            </value>
            <value>
                <fullName>Data Transfer Agreement</fullName>
            </value>
            <value>
                <fullName>Grant Funding Agreement</fullName>
            </value>
            <value>
                <fullName>Honorary/Adjunct/Visitors Deed</fullName>
            </value>
            <value>
                <fullName>Hospital/Health Services Agreement</fullName>
            </value>
            <value>
                <fullName>Individual Student Agreement - Placements</fullName>
            </value>
            <value>
                <fullName>Industry PhD Agreement</fullName>
            </value>
            <value>
                <fullName>Intellectual Property Assignment Deed</fullName>
            </value>
            <value>
                <fullName>Lease Agreement</fullName>
            </value>
            <value>
                <fullName>Licence to Occupy</fullName>
            </value>
            <value>
                <fullName>Material Transfer Agreement (receiving)</fullName>
            </value>
            <value>
                <fullName>Material Transfer Agreement (supplying)</fullName>
            </value>
            <value>
                <fullName>Memorandum of Understanding (MOU)</fullName>
            </value>
            <value>
                <fullName>Mobility – Overseas Short Programs</fullName>
            </value>
            <value>
                <fullName>Mobility – Semester Exchange</fullName>
            </value>
            <value>
                <fullName>Mobility – Study Abroad</fullName>
            </value>
            <value>
                <fullName>Mobility – Study Abroad and Exchange</fullName>
            </value>
            <value>
                <fullName>Mobility – Third Party Provider</fullName>
            </value>
            <value>
                <fullName>NDA (non-disclosure)</fullName>
            </value>
            <value>
                <fullName>Overarching Agreement - Placements</fullName>
            </value>
            <value>
                <fullName>Rental Agreement</fullName>
            </value>
            <value>
                <fullName>Research Collaboration Agreement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContractTriggerHelper.cls
public with sharing class ContractTriggerHelper{


    //LTU360-2384 update the L_PR_Agreement_Status__c fild in Related_Contract__c when there is an update in Agreement I_RS_Status__c field
    public static void updateRelatedOrgStatus(Map<Id,String> agreementStatusMap){

        List<Related_Contract__c> agreementStatusToUpdate = new List<Related_Contract__c>();
        List<Apex_Debug_Log__c> errorLogs = new List<Apex_Debug_Log__c>();
        try{
            if(agreementStatusMap != null){
                for(Related_Contract__c relOrgAgr : [Select Id, I_RS_Contract__c, L_PR_Agreement_Status__c, I_RS_Organisation__c
                                                                           From Related_Contract__c Where I_RS_Contract__c IN : agreementStatusMap.keySet()]){
                                                                            
                    Related_Contract__c relOrg = new Related_Contract__c();
                    relOrg.Id = relOrgAgr.Id;
                    relOrg.L_PR_Agreement_Status__c = agreementStatusMap.get(relOrgAgr.I_RS_Contract__c);                                             
                    agreementStatusToUpdate.add(relOrg);
                }
            }

 
            if(!agreementStatusToUpdate.isEmpty()){
                update agreementStatusToUpdate;
            }

        }catch(Exception e){
            errorLogs.add(new Apex_Debug_Log__c(Apex_Class_Name__c = 'ContractTriggerHelper', Apex_Class_Method_Name__c = 'updateRelatedOrgStatus',
                Exception_message__c = 'exception while updating the L_PR_Agreement_Status__c in ContractTriggerHelper', Exception_Stack_Trace__c = e.getStackTraceString()));
                if (errorLogs != null && !errorLogs.isEmpty()){
                    insert errorLogs;
                 errorLogs.clear();
                }
        }

    }


    public static void createUpdateRelatedOrgs(Map<Id,Id> agrOrgMap, Map<Id,Id> removeAgrOrgMap, String orgType, Map<Id,Contract__c> mapOfAgreements){

        List<Related_Contract__c> relatedOrgs = new List<Related_Contract__c>();
        List<Apex_Debug_Log__c> errorLogs = new List<Apex_Debug_Log__c>();
        try{
            if(agrOrgMap != Null){
                  //check if the current Agreement organisation pair exist in Related organisation relationship records                      
                  List<Related_Contract__c> existingRelatedOrgs = [SELECT Id, I_RS_Contract__c,L_PR_isPrimary__c, I_RS_Organisation__c, L_PR_Agreement_Recordtype__c FROM Related_Contract__c
                                                                  where I_RS_Contract__c IN: agrOrgMap.keySet() AND I_RS_Organisation__c IN: agrOrgMap.values()];
                      if(!existingRelatedOrgs.isEmpty()){ 
                       // if Found, mark IsPrimary True for that record
                      		for(Related_Contract__c exLOrg : existingRelatedOrgs){
                                //  update existing opportunity organisation relationship
                                Related_Contract__c agrOrg = new Related_Contract__c();
                                agrOrg.Id = exLOrg.Id;
                            	agrOrg.L_PR_isPrimary__c = True; 
                            	relatedOrgs.add(agrOrg);
                            }
                        }
                        else{
                            // if no existing record found, create new record with agreement & organisation relationship and isPrimary true
                            for(Id agr : agrOrgMap.keySet()){
                             	//create agreement organisation relationship record
                                Related_Contract__c agrOrg = new Related_Contract__c();
                            	agrOrg.I_RS_Organisation__c = agrOrgMap.get(agr);
                            	agrOrg.I_RS_Contract__c = agr;
                            	agrOrg.L_PR_isPrimary__c = True;
                                agrOrg.L_PR_Agreement_Recordtype__c = getAgreementRecordTypeName(mapOfAgreements.get(agr).RecordTypeId);
                            	relatedOrgs.add(agrOrg);
                            }
                        }

                        // find all agreement organisation relationships where agreement is present and isPrimary ticked
                        // or any other agreement organisation relationship is present with isprimary true
                        for(Related_Contract__c ActivelOrgList : [SELECT Id, I_RS_Contract__c,I_RS_Organisation__c,I_RS_Organisation__r.recordType.Name, L_PR_isPrimary__c,L_PR_Agreement_Recordtype__c FROM Related_Contract__c
                                                                    WHERE (I_RS_Contract__c in: agrOrgMap.keySet() AND I_RS_Organisation__c NOT IN: agrOrgMap.values() AND L_PR_isPrimary__c = TRUE)
                                                                    OR (I_RS_Contract__c in: removeAgrOrgMap.keySet() AND I_RS_Organisation__c in: removeAgrOrgMap.values())]){
                        //  update existing lead organisation relationship
                            if(orgType =='External' && (ActivelOrgList.I_RS_Organisation__r.recordType.Name == 'External Organisation' || ActivelOrgList.I_RS_Organisation__r.recordType.Name == 'Educational Institution')){
                                Related_Contract__c agrOrg = new Related_Contract__c();
                                agrOrg.Id = ActivelOrgList.Id;
                                agrOrg.L_PR_IsPrimary__c = False; 
                                relatedOrgs.add(agrOrg);   
                            }
                            else if(orgType =='Internal' && ActivelOrgList.I_RS_Organisation__r.recordType.Name == 'La Trobe Organisation Unit'){
                                Related_Contract__c agrOrg = new Related_Contract__c();
                                agrOrg.Id = ActivelOrgList.Id;
                                agrOrg.L_PR_IsPrimary__c = False; 
                                relatedOrgs.add(agrOrg);   
                                }
                        }  
                    }
                    if(relatedOrgs != null){
                        upsert relatedOrgs;
                    }
        		}catch(exception e){
                    errorLogs.add(new Apex_Debug_Log__c(Apex_Class_Name__c = 'ContractTriggerHelper', Apex_Class_Method_Name__c = 'createUpdateRelatedOrgs',
                        Exception_message__c = 'exception while updating the isPrimary in ContractTriggerHelper', Exception_Stack_Trace__c = e.getStackTraceString()));
                        if (errorLogs != null && !errorLogs.isEmpty()){
                            insert errorLogs;
                         errorLogs.clear();
                        } 
                }                    
    }

    public static String getAgreementRecordTypeName(Id agreementId){

        return Schema.getGlobalDescribe().get('Contract__c').getDescribe().getRecordTypeInfosById().get(agreementId).getName();
    }
    
    // Method to update prm opportunity status to closed won
    public static void updateOppStatusClosedWon(Map<Id,Id> oppAggMap){
        List<Apex_Debug_Log__c> errorLogs = new List<Apex_Debug_Log__c>();
        try{
            List<Opportunity> oppList = new List<Opportunity>();
            for(Id oppId : oppAggMap.keyset()){
                Opportunity opp = new Opportunity(Id=oppId);
                opp.StageName ='Closed Won';
                opp.CloseDate = system.today();
                oppList.add(opp);
            }
            if(!oppList.isEmpty())
                update oppList;
			
        }catch(Exception ex){
            errorLogs.add(new Apex_Debug_Log__c(Apex_Class_Name__c = 'ContractTriggerHelper',Apex_Class_Method_Name__c = 'updateOppStatusClosedWonId',Exception_message__c = ex.getMessage(),Exception_Stack_Trace__c = ex.getStackTraceString()));
            		if (errorLogs != null && !errorLogs.isEmpty()){
               			insert errorLogs;
            			errorLogs.clear();
            		} 
        }
    }


    //LTU360-2659 Create agreement tasks from the Task Matrix

    public static void createTasksFromTaskMatrix(Map<Id,Contract__c> triggerMap){

        Map<Id, Task_Matrix__c> mapOfAllTaskMatrix = new Map<Id, Task_Matrix__c>();
        List<Task> taskListToCreate = new List<Task>();
        List<Apex_Debug_Log__c> errorLogs = new List<Apex_Debug_Log__c>();
        Map<Id,List<String>> agrTaskMap = new Map<Id,List<String>>();
        for(Task tsk : [SELECT Id, Subject, WhatId FROM Task WHERE WhatId IN : triggerMap.keySet()]){
            if(agrTaskMap.containsKey(tsk.WhatId)){
                agrTaskMap.get(tsk.WhatId).add(tsk.Subject);
            } else {
                agrTaskMap.put(tsk.WhatId, new List<String>{tsk.Subject});
            }
        }

        try{
            for(Task_Matrix__c taskMatrix: [SELECT Id, Name, L_PR_Agreement_Type__c, I_RS_Object_Name__c, I_RS_Record_Type__c, L_PR_Agreement_Stage__c, I_RS_Subject__c
            FROM Task_Matrix__c WHERE  I_RS_Object_Name__c ='Agreement' AND I_RS_Inactive__c= FALSE]){
                for(Id aggr: triggerMap.keySet()){
                    if(triggerMap.get(aggr).I_RS_Closure_Reason__c == null && taskMatrix.L_PR_Agreement_Stage__c == 'Terminated'){
                        Task newTask = new Task();
                    }
                    else if(( taskMatrix.L_PR_Agreement_Stage__c == 'Executed' && triggerMap.get(aggr).I_RS_Agreement_Type__c == taskMatrix.L_PR_Agreement_Type__c 
                    && triggerMap.get(aggr).I_RS_Closure_Reason__c == null)){
                        if(agrTaskMap.isEmpty() || (!agrTaskMap.isEmpty() && !agrTaskMap.get(aggr).contains(taskMatrix.I_RS_Subject__c))){
                            taskListToCreate.add(ContractTriggerHelper.createTask(taskMatrix.I_RS_Subject__c, aggr, triggerMap.get(aggr).OwnerId, taskMatrix.L_PR_Agreement_Stage__c));
                        }
                    }else if (triggerMap.get(aggr).I_RS_Closure_Reason__c != null && triggerMap.get(aggr).I_RS_Agreement_Type__c == taskMatrix.L_PR_Agreement_Type__c 
                    && triggerMap.get(aggr).I_RS_Closure_Reason__c == taskMatrix.L_PR_Agreement_Stage__c){
                        if(agrTaskMap.isEmpty() || (!agrTaskMap.isEmpty() && !agrTaskMap.get(aggr).contains(taskMatrix.I_RS_Subject__c))){
                            taskListToCreate.add(ContractTriggerHelper.createTask(taskMatrix.I_RS_Subject__c, aggr, triggerMap.get(aggr).OwnerId, taskMatrix.L_PR_Agreement_Stage__c));
                        }
                    }
                
                }
            }

            if(!taskListToCreate.isEmpty()){
                insert taskListToCreate;
            }
        }catch(Exception e){
            errorLogs.add(new Apex_Debug_Log__c(Apex_Class_Name__c = 'ContractTriggerHelper', Apex_Class_Method_Name__c = 'createTasksFromTaskMatrix',
                Exception_message__c = 'exception while creating the tasks for the agreement in ContractTriggerHelper', Exception_Stack_Trace__c = e.getStackTraceString()));
                if (errorLogs != null && !errorLogs.isEmpty()){
                    insert errorLogs;
                 errorLogs.clear();
                } 
        }

    }


    public static Task createTask(String taskSubject, Id agrId, String ownerId, String agrStage){
        Id taskAgreementRecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName().get('L_PR_Agreement_Task').getRecordTypeId();
        Task newTask = new Task();
        newTask.Subject = taskSubject;
        newTask.WhatId = agrId;
        newTask.Status = 'Not Started';
        newTask.RecordTypeId = taskAgreementRecordTypeId;
        newTask.OwnerId =  ownerId;
        newTask.L_PR_Stage__c = agrStage;
        return newTask;
    }

}