force-app/main/default/objects/Account/fields/I_RS_Maximum_Allowed_On_Cost__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Maximum_Allowed_On_Cost__c</fullName>
    <defaultValue>0.3574</defaultValue>
    <label>Maximum Allowed On-Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/I_RS_Part_of_La_Trobe__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Part_of_La_Trobe__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Part of La Trobe</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>La Trobe Division Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>College</fullName>
            </value>
            <value>
                <fullName>School</fullName>
            </value>
            <value>
                <fullName>Department</fullName>
            </value>
            <value>
                <fullName>Unit</fullName>
            </value>
            <value>
                <fullName>DVCR</fullName>
            </value>
            <value>
                <fullName>Research Centre/Institute</fullName>
            </value>
            <value>
                <fullName>Research Focus Area</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Budget__c/Budget__c.object-meta.xml
<CustomObject>
    <description>This is the summarised budget header details that goes for approval &amp; is maintained in system for any further progress, tracking or finance integration</description>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget__c/fields/I_RS_Actual_Profit__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Actual_Profit__c</fullName>
    <inlineHelpText>The percentage applied to researcher salary to be returned to the university/researcher.</inlineHelpText>
    <label>Actual Salary Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Maximum_Allowed_On_Cost__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Maximum_Allowed_On_Cost__c</fullName>
    <inlineHelpText>Maximum allowable on-cost rate set by Funder.</inlineHelpText>
    <label>Maximum Allowed On-Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Project_End_Date__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Project_End_Date__c</fullName>
    <formula>I_RS_Project_Proposal__r.I_RS_Project_End_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Project_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Project_Start_Date__c</fullName>
    <formula>I_RS_Project_Proposal__r.I_RS_Project_Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/Budget_Line_Item__c.object-meta.xml
<CustomObject>
    <description>This will capture the calculated budget line details from Budget Calculator tool. Please note that Budget Calculator will be a custom developed tool built &amp; integrated with Salesforce. Later the calculated values will be stored in this object.</description>
    <label>Budget Line Item</label>
    <nameField>
        <displayFormat>BLI-{00000}</displayFormat>
        <label>Budget Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Budget__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Budget__c</fullName>
    <label>Budget</label>
    <referenceTo>Budget__c</referenceTo>
    <relationshipLabel>Budget Line Items</relationshipLabel>
    <relationshipName>Budget_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Contact__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Budget Line Items</relationshipLabel>
    <relationshipName>Budget_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Organisation__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Budget Line Items</relationshipLabel>
    <relationshipName>Budget_Line_Items_Org</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Part_of_La_Trobe__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Part_of_La_Trobe__c</fullName>
    <formula>I_RS_Organisation__r.I_RS_Part_of_La_Trobe__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Part of La Trobe</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Salary_Grade__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Salary_Grade__c</fullName>
    <formula>IF(
TEXT(I_RS_Category__c) = &quot;Future La Trobe staff&quot; ||
TEXT(I_RS_Category__c) = &quot;Research Assistant&quot; ||
TEXT(I_RS_Category__c) = &quot;Student&quot;,

TEXT(I_RS_Sub_Category__c),

IF(
TEXT(I_RS_Category__c) = &quot;Current La Trobe staff&quot;,
I_RS_Contact__r.I_RS_Salary_Grade_Standard__c,

&quot;&quot;
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Salary Grade</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Unit_of_Time__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Unit_of_Time__c</fullName>
    <label>Unit of Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Years</fullName>
            </value>
            <value>
                <fullName>Months</fullName>
            </value>
            <value>
                <fullName>Weeks</fullName>
            </value>
            <value>
                <fullName>Days</fullName>
            </value>
            <value>
                <fullName>Hours</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/Year_1_Cost__c.field-meta.xml
<CustomField>
    <fullName>Year_1_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total Amount for this Budget Item over Year 1</inlineHelpText>
    <label>Year 1 Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/Year_1_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Year_1_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <description>For Salary Items, this is the number of time units. For Non-Salary, this is the Quantity of Items.</description>
    <inlineHelpText>For Salary Items, this is the number of time units. 

For Non-Salary, this is the Quantity of Items.</inlineHelpText>
    <label>Year 1 Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/Year_2_Cost__c.field-meta.xml
<CustomField>
    <fullName>Year_2_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Year 2 Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/Year_2_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Year_2_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Year 2 Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/Year_3_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Year_3_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Year 3 Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/Year_4_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Year_4_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Year 4 Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/Year_5_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Year_5_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Year 5 Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/Year_6_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Year_6_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Year 6 Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/Year_7_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Year_7_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Year 7 Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_RS_Salary_Grade__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Salary_Grade__c</fullName>
    <label>Salary Grade (HR)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Level A 1</fullName>
            </value>
            <value>
                <fullName>Level A 2</fullName>
            </value>
            <value>
                <fullName>Level A 3</fullName>
            </value>
            <value>
                <fullName>Level A 4</fullName>
            </value>
            <value>
                <fullName>Level A 5</fullName>
            </value>
            <value>
                <fullName>Level A 6</fullName>
            </value>
            <value>
                <fullName>Level A 7</fullName>
            </value>
            <value>
                <fullName>Level A 8</fullName>
            </value>
            <value>
                <fullName>Level B 1</fullName>
            </value>
            <value>
                <fullName>Level B 2</fullName>
            </value>
            <value>
                <fullName>Level B 3</fullName>
            </value>
            <value>
                <fullName>Level B 4</fullName>
            </value>
            <value>
                <fullName>Level B 5</fullName>
            </value>
            <value>
                <fullName>Level B 6</fullName>
            </value>
            <value>
                <fullName>Level C 1</fullName>
            </value>
            <value>
                <fullName>Level C 2</fullName>
            </value>
            <value>
                <fullName>Level C 3</fullName>
            </value>
            <value>
                <fullName>Level C 4</fullName>
            </value>
            <value>
                <fullName>Level C 5</fullName>
            </value>
            <value>
                <fullName>Level C 6</fullName>
            </value>
            <value>
                <fullName>Level D 1</fullName>
            </value>
            <value>
                <fullName>Level D 2</fullName>
            </value>
            <value>
                <fullName>Level D 3</fullName>
            </value>
            <value>
                <fullName>Level D 4</fullName>
            </value>
            <value>
                <fullName>Level E 1</fullName>
            </value>
            <value>
                <fullName>HEO1-1</fullName>
            </value>
            <value>
                <fullName>HEO1-2</fullName>
            </value>
            <value>
                <fullName>HEO1-3</fullName>
            </value>
            <value>
                <fullName>HEO1-4</fullName>
            </value>
            <value>
                <fullName>HEO2-1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/On_Cost_Default_Values__c/fields/I_RS_Maximum_Allowed_On_Cost__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Maximum_Allowed_On_Cost__c</fullName>
    <label>Maximum Allowed On-Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Project_Proposal__c/Project_Proposal__c.object-meta.xml
<CustomObject>
    <description>Project Proposal: An application for funding either through a grant request, a tender response, or a contract proposal.
Project: The work that is undertaken to satisfy a commitment made to a funding body or client.  The commitment is likely to be a contract (and possible variations) resulting from the acceptance of a project proposal.  This occurs after a grant, contract of philanthropic donation has been awarded.</description>
    <label>Project Proposal</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Proposal__c/fields/I_RS_Project_End_Date__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Project_End_Date__c</fullName>
    <inlineHelpText>The estimated expected project end date.</inlineHelpText>
    <label>Project End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project_Proposal__c/fields/I_RS_Project_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Project_Start_Date__c</fullName>
    <inlineHelpText>The expected project start date.</inlineHelpText>
    <label>Project Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BudgetCalculatorAuraTest.cls
@isTest
public class BudgetCalculatorAuraTest {
    
    public static testmethod void testQuery(){
        
        Project_Proposal__c pp = TestUtility.newProjectProposal();
        insert pp;
        
        Budget__c budget = TestUtility.newBudget(pp.Id);
        insert budget; 
        
        List<Budget_Line_Item__c> lineItems = new List<Budget_Line_Item__c>();
        for (Integer i=0; i<100; i++){
            lineItems.add(
                TestUtility.newBudgetLineItem(budget.Id)
            );
        }
        
        
        DataAccess.upsertRecords(lineItems, false);
        
        
        DataAccess.getSObjectListSOQL(
            new List<String>{'Name'},
            null, 
            'Budget_Line_Item__c', 
            'I_RS_Budget__c = \''+budget.Id+'\'',
            'Name',
            'ASC NULLS FIRST',
            100,
            0
        );
        
    }
    
    public static testmethod void testLookup(){
        
        Account account = TestUtility.newEmptyExternalAccount('Test Account');
        insert account;
        
        List<String> strList = new List<String>();
        List<LookupSearchResult> lookupSearchResults = 
            BudgetCalculatorAura.search(
            'Account', 
            'Test', 
            'Name',
            'Type__c',
            new List<String>{'I_RS_Part_of_La_Trobe__c'},
            'Name != NULL',
            'standard:icon'
            );
        System.assert(!lookupSearchResults.isEmpty());
        
    }
    
    
    public static testmethod void testSalaryCalculationYears(){
        
        Account org = TestUtility.newEmptyExternalAccount('Test Account');
        insert org;
        
        //Contact contact = TestUtility.newContact(GlobalConstants.CONTACT_RECORD_TYPE_NAME_LTU_STAFF, org.Id);
        Contact contact = TestUtility.createContact(org.Id);
        contact.I_RS_Salary_Grade__c = 'TEST 1';
        insert contact;
        
        insert new On_Cost_Default_Values__c(
            Name = 'La Trobe University',
            I_RS_Maximum_Allowed_On_Cost__c = 35.75
        );
        
        List<Salary_Table__c> salaryTableList = new List<Salary_Table__c>();
        Integer todaysYear = Date.today().year();
        for (Integer index=1; index<=10; index++){
            String currentYear = (todaysYear + index - 1) + '';
            salaryTableList.add(TestUtility.newSalaryTable('TEST', index, currentYear, 100000 + (1000 * index) ));     
        }
        
        insert salaryTableList;
        
        Project_Proposal__c pp = TestUtility.newProjectProposal();
        pp.I_RS_Project_Start_Date__c = Date.today();
        pp.I_RS_Project_End_Date__c = Date.today().addYears(7);
        insert pp;
        
        Budget__c budget = TestUtility.newBudget(pp.Id);
        budget.I_RS_Actual_Profit__c = 10;
        insert budget;
        
        List<Budget_Line_Item__c> budgetLineItems = new List<Budget_Line_Item__c>();
        budgetLineItems.add(new Budget_Line_Item__c(
            I_RS_Budget__c = budget.Id,
            I_RS_Organisation__c = org.Id,
            I_RS_Contact__c = contact.Id,
            I_RS_Unit_of_Time__c = 'Years',
            Year_1_Quantity__c = 1,
            Year_2_Quantity__c = 1,
            Year_3_Quantity__c = 1,
            Year_4_Quantity__c = 1,
            Year_5_Quantity__c = 1,
            Year_6_Quantity__c = 1,
            Year_7_Quantity__c = 1,
            Year_1_Cost__c = 0,
            Year_2_Cost__c = 0,
            Year_3_Cost__c = 0,
            Year_4_Cost__c = 0,
            Year_5_Cost__c = 0,
            Year_6_Cost__c = 0,
            Year_7_Cost__c = 0,
            I_RS_Amount__c = 0
        ));
        
        Test.startTest();
        EditableGridAutomationController.runAutomation('calculateSalaries', budgetLineItems);
        Test.stopTest();
        
    }
    
    public static testmethod void testSalaryCalculationMonths(){
        
        Account org = TestUtility.newEmptyExternalAccount('Test Account');
        insert org;
        
        //Contact contact = TestUtility.newContact(GlobalConstants.CONTACT_RECORD_TYPE_NAME_LTU_STAFF, org.Id);
        Contact contact = TestUtility.createContact(org.Id);
        contact.I_RS_Salary_Grade__c = 'TEST 1';
        insert contact;
        
        insert new On_Cost_Default_Values__c(
            Name = 'La Trobe University',
            I_RS_Maximum_Allowed_On_Cost__c = 35.75
        );
        
        List<Salary_Table__c> salaryTableList = new List<Salary_Table__c>();
        Integer todaysYear = Date.today().year();
  
        for (Integer index=1; index<=10; index++){
            String currentYear = (todaysYear + index - 1) + '';
            salaryTableList.add(TestUtility.newSalaryTable('TEST', index, currentYear, 100000 + (1000 * index) ));     
        }
        
        insert salaryTableList;
        
        Project_Proposal__c pp = TestUtility.newProjectProposal();
        pp.I_RS_Project_Start_Date__c = Date.today();
        pp.I_RS_Project_End_Date__c = Date.today().addYears(7);
        insert pp;
        
        Budget__c budget = TestUtility.newBudget(pp.Id);
        budget.I_RS_Actual_Profit__c = 10;
        insert budget;
        
        List<Budget_Line_Item__c> budgetLineItems = new List<Budget_Line_Item__c>();
        budgetLineItems.add(new Budget_Line_Item__c(
            I_RS_Budget__c = budget.Id,
            I_RS_Organisation__c = org.Id,
            I_RS_Contact__c = contact.Id,
            I_RS_Unit_of_Time__c = 'Months',
            Year_1_Quantity__c = 1,
            Year_2_Quantity__c = 1,
            Year_3_Quantity__c = 1,
            Year_4_Quantity__c = 1,
            Year_5_Quantity__c = 1,
            Year_6_Quantity__c = 1,
            Year_7_Quantity__c = 1,
            Year_1_Cost__c = 0,
            Year_2_Cost__c = 0,
            Year_3_Cost__c = 0,
            Year_4_Cost__c = 0,
            Year_5_Cost__c = 0,
            Year_6_Cost__c = 0,
            Year_7_Cost__c = 0,
            I_RS_Amount__c = 0
        ));
        
        Test.startTest();
        EditableGridAutomationController.runAutomation('calculateSalaries', budgetLineItems);
        Test.stopTest();
        
    }
    
    public static testmethod void testSalaryCalculationWeeks(){
        
        Account org = TestUtility.newEmptyExternalAccount('Test Account');
        insert org;
        
        //Contact contact = TestUtility.newContact(GlobalConstants.CONTACT_RECORD_TYPE_NAME_LTU_STAFF, org.Id);
        Contact contact = TestUtility.createContact(org.Id);
        contact.I_RS_Salary_Grade__c = 'TEST 1';
        insert contact;
        
        insert new On_Cost_Default_Values__c(
            Name = 'La Trobe University',
            I_RS_Maximum_Allowed_On_Cost__c = 35.75
        );
        
        List<Salary_Table__c> salaryTableList = new List<Salary_Table__c>();
        Integer todaysYear = Date.today().year();
        for (Integer index=1; index<=10; index++){
            String currentYear = (todaysYear + index - 1) + '';
            salaryTableList.add(TestUtility.newSalaryTable('TEST', index, currentYear, 100000 + (1000 * index) ));     
        }
        
        insert salaryTableList;
        
        Project_Proposal__c pp = TestUtility.newProjectProposal();
        pp.I_RS_Project_Start_Date__c = Date.today();
        pp.I_RS_Project_End_Date__c = Date.today().addYears(7);
        insert pp;
        
        Budget__c budget = TestUtility.newBudget(pp.Id);
        budget.I_RS_Actual_Overhead__c = 10;
        insert budget;
        
        List<Budget_Line_Item__c> budgetLineItems = new List<Budget_Line_Item__c>();
        budgetLineItems.add(new Budget_Line_Item__c(
            I_RS_Budget__c = budget.Id,
            I_RS_Organisation__c = org.Id,
            I_RS_Contact__c = contact.Id,
            I_RS_Unit_of_Time__c = 'Weeks',
            Year_1_Quantity__c = 1,
            Year_2_Quantity__c = 1,
            Year_3_Quantity__c = 1,
            Year_4_Quantity__c = 1,
            Year_5_Quantity__c = 1,
            Year_6_Quantity__c = 1,
            Year_7_Quantity__c = 1,
            Year_1_Cost__c = 0,
            Year_2_Cost__c = 0,
            Year_3_Cost__c = 0,
            Year_4_Cost__c = 0,
            Year_5_Cost__c = 0,
            Year_6_Cost__c = 0,
            Year_7_Cost__c = 0,
            I_RS_Amount__c = 0
        ));
        
        
        Test.startTest();
        EditableGridAutomationController.runAutomation('calculateSalaries', budgetLineItems);
        Test.stopTest();
        
    }
    
    public static testmethod void testSalaryCalculationDays(){
        
        Account org = TestUtility.newEmptyExternalAccount('Test Account');
        insert org;
        
        Contact contact = TestUtility.createContact(org.Id);
        contact.I_RS_Salary_Grade__c = 'TEST 1';
        insert contact;
        
        insert new On_Cost_Default_Values__c(
            Name = 'La Trobe University',
            I_RS_Maximum_Allowed_On_Cost__c = 35.75
        );
        
        List<Salary_Table__c> salaryTableList = new List<Salary_Table__c>();
        Integer todaysYear = Date.today().year();
        for (Integer index=1; index<=10; index++){
            String currentYear = (todaysYear + index - 1) + '';
            salaryTableList.add(TestUtility.newSalaryTable('TEST', index, currentYear, 100000 + (1000 * index) ));     
        }
        
        insert salaryTableList;
        
        Project_Proposal__c pp = TestUtility.newProjectProposal();
        pp.I_RS_Project_Start_Date__c = Date.today();
        pp.I_RS_Project_End_Date__c = Date.today().addYears(7);
        insert pp;
        
        Budget__c budget = TestUtility.newBudget(pp.Id);
        budget.I_RS_Actual_Profit__c = 10;
        budget.I_RS_Actual_Overhead__c = 10;
        insert budget;
        
        List<Budget_Line_Item__c> budgetLineItems = new List<Budget_Line_Item__c>();
        budgetLineItems.add(new Budget_Line_Item__c(
            I_RS_Budget__c = budget.Id,
            I_RS_Organisation__c = org.Id,
            I_RS_Contact__c = contact.Id,
            I_RS_Unit_of_Time__c = 'Days',
            Year_1_Quantity__c = 1,
            Year_2_Quantity__c = 1,
            Year_3_Quantity__c = 1,
            Year_4_Quantity__c = 1,
            Year_5_Quantity__c = 1,
            Year_6_Quantity__c = 1,
            Year_7_Quantity__c = 1,
            Year_1_Cost__c = 0,
            Year_2_Cost__c = 0,
            Year_3_Cost__c = 0,
            Year_4_Cost__c = 0,
            Year_5_Cost__c = 0,
            Year_6_Cost__c = 0,
            Year_7_Cost__c = 0,
            I_RS_Amount__c = 0
        ));
        
        Test.startTest();
        EditableGridAutomationController.runAutomation('calculateSalaries', budgetLineItems);
        Test.stopTest();
        
    }
    
    public static testmethod void testSalaryCalculationHours(){
        
        Account org = TestUtility.newEmptyExternalAccount('Test Account');
        org.I_RS_Maximum_Allowed_On_Cost__c = 30;
        insert org;
        
        //Contact contact = TestUtility.newContact(GlobalConstants.CONTACT_RECORD_TYPE_NAME_LTU_STAFF, org.Id);
        Contact contact = TestUtility.createContact(org.Id);
        contact.I_RS_Salary_Grade__c = 'TEST 1';
        insert contact;
        
        insert new On_Cost_Default_Values__c(
            Name = 'La Trobe University',
            I_RS_Maximum_Allowed_On_Cost__c = 35.75
        );
        
        List<Salary_Table__c> salaryTableList = new List<Salary_Table__c>();
        Integer todaysYear = Date.today().year();
        for (Integer index=1; index<=10; index++){
            String currentYear = (todaysYear + index - 1) + '';
            salaryTableList.add(TestUtility.newSalaryTable('TEST', index, currentYear, 100000 + (1000 * index) ));     
        }
        
        insert salaryTableList;
        
        Project_Proposal__c pp = TestUtility.newProjectProposal();
        pp.I_RS_Project_Start_Date__c = Date.today();
        pp.I_RS_Project_End_Date__c = Date.today().addYears(7);
        insert pp;
        
        Budget__c budget = TestUtility.newBudget(pp.Id);
        budget.I_RS_Actual_Profit__c = 10;
        insert budget;
        
        List<Budget_Line_Item__c> budgetLineItems = new List<Budget_Line_Item__c>();
        budgetLineItems.add(new Budget_Line_Item__c(
            I_RS_Budget__c = budget.Id,
            I_RS_Organisation__c = org.Id,
            I_RS_Contact__c = contact.Id,
            I_RS_Unit_of_Time__c = 'Hours',
            Year_1_Quantity__c = 1,
            Year_2_Quantity__c = 1,
            Year_3_Quantity__c = 1,
            Year_4_Quantity__c = 1,
            Year_5_Quantity__c = 1,
            Year_6_Quantity__c = 1,
            Year_7_Quantity__c = 1,
            Year_1_Cost__c = 0,
            Year_2_Cost__c = 0,
            Year_3_Cost__c = 0,
            Year_4_Cost__c = 0,
            Year_5_Cost__c = 0,
            Year_6_Cost__c = 0,
            Year_7_Cost__c = 0,
            I_RS_Amount__c = 0
        ));
        
        Test.startTest();
        EditableGridAutomationController.runAutomation('calculateSalaries', budgetLineItems);
        Test.stopTest();
        
    }
    

    public static testMethod void getTotalIncludingGST(){

        TestUtility.insertGSTRate();

        List<Budget_Line_Item__c> budgetLineItems = new List<Budget_Line_Item__c>();
        budgetLineItems.add(new Budget_Line_Item__c(I_RS_Amount__c = 1000));

        Budget_Line_Item__c budgetLineItemOutput = 
            (Budget_Line_Item__c) EditableGridAutomationController.runAutomation('applyGST', budgetLineItems)[0];

        System.assert(
            budgetLineItemOutput.I_RS_Cash_Amount_Inc_GST_Currency__c > budgetLineItems[0].I_RS_Amount__c,
            'Amount and Amount Incl. GST are the same'
        );
    }
    
    
    public static testmethod void testDelete(){
        
        Object_Metadata__c deletionBlockerCustomSetting = new Object_Metadata__c(
            Name = 'Budget_Line_Item__c',
            I_RS_Enable_Deletion_Blocker__c = true,
            I_RS_Deletion_Blocker_Check_Formula__c = 'I_RS_Line_Item_Permission_Delete__c',
            I_RS_Deletion_Blocker_Error_Message__c = 'Cant delete this'
        );
        insert deletionBlockerCustomSetting;
        
        Project_Proposal__c pp = TestUtility.newProjectProposal();
        insert pp;
        
        Budget__c budget = TestUtility.newBudget(pp.Id);
        insert budget;
        
        List<Budget_Line_Item__c> budgetLineItems = new List<Budget_Line_Item__c>();
        budgetLineItems.add(TestUtility.newBudgetLineItem(budget.Id));
        
        insert budgetLineItems;
        
        DataAccess.deleteRecords(budgetLineItems);
        
        System.assertequals(0, [select count() from Budget_Line_Item__c]);
        
    }
    
    
    public static testmethod void getBLIRecordTypesByDeveloperName(){
    
        DataAccess.getRecordTypeInfosByDeveloperName('Budget_Line_Item__c');
        
        
    }

}