force-app/main/default/objects/Account/fields/I_RS_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Proposed</fullName>
                <isActive>false</isActive>
                <label>Proposed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Proposal__c/Project_Proposal__c.object-meta.xml
<CustomObject>
    <description>Project Proposal: An application for funding either through a grant request, a tender response, or a contract proposal.
Project: The work that is undertaken to satisfy a commitment made to a funding body or client.  The commitment is likely to be a contract (and possible variations) resulting from the acceptance of a project proposal.  This occurs after a grant, contract of philanthropic donation has been awarded.</description>
    <label>Project Proposal</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Proposal__c/fields/I_RS_Approval_Flag__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Approval_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>this is an internal field (not to be visible for user) used to restrict user to manually sett status to &quot;Approvals&quot;</description>
    <label>Approval Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_Proposal__c/fields/I_RS_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PlaceHolder</fullName>
            </value>
            <value>
                <fullName>Create Proposal</fullName>
            </value>
            <value>
                <fullName>Proposal Review</fullName>
            </value>
            <value>
                <fullName>Recommended</fullName>
            </value>
            <value>
                <fullName>Dismissed</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Create EOI</fullName>
            </value>
            <value>
                <fullName>Drafting NOI</fullName>
            </value>
            <value>
                <fullName>Final draft</fullName>
            </value>
            <value>
                <fullName>Draft Proposal</fullName>
            </value>
            <value>
                <fullName>Provide Project Details</fullName>
            </value>
            <value>
                <fullName>Contract Instructions</fullName>
            </value>
            <value>
                <fullName>Review by Research Office</fullName>
            </value>
            <value>
                <fullName>Panel Review</fullName>
            </value>
            <value>
                <fullName>HoS NOI Validation</fullName>
            </value>
            <value>
                <fullName>Pitch Session</fullName>
            </value>
            <value>
                <fullName>Peer review draft</fullName>
            </value>
            <value>
                <fullName>Peer review draft complete</fullName>
            </value>
            <value>
                <fullName>Review Contract</fullName>
            </value>
            <value>
                <fullName>Draft contract</fullName>
            </value>
            <value>
                <fullName>Approvals</fullName>
            </value>
            <value>
                <fullName>Formalise Contract</fullName>
            </value>
            <value>
                <fullName>Submission to Client</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Ready for Submission to Funding Body</fullName>
            </value>
            <value>
                <fullName>Submission to Funding Body</fullName>
                <label>Funding Body Submission</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Rejoinders</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Proposal__c/fields/I_RS_Theme__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Theme__c</fullName>
    <description>https://eawebdev.atlassian.net/browse/T2-876</description>
    <inlineHelpText>Select which theme(s) this project aligns to.</inlineHelpText>
    <label>Theme Alignment</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No theme alignment</fullName>
                <default>true</default>
                <label>No theme alignment</label>
            </value>
            <value>
                <fullName>A healthy, safe and equitable life course for everyone</fullName>
            </value>
            <value>
                <fullName>The production of quality foods &amp; medicines</fullName>
            </value>
            <value>
                <fullName>The protection &amp; restoration of vulnerable ecosystems</fullName>
            </value>
            <value>
                <fullName>Understanding &amp; preventing disease</fullName>
            </value>
            <value>
                <fullName>More just and equitable societies</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Proposal__c/recordTypes/I_RS_Proposal.recordType-meta.xml
<RecordType>
    <fullName>I_RS_Proposal</fullName>
    <active>true</active>
    <label>Proposal</label>
</RecordType>

force-app/main/default/objects/Research_Opportunity__c/Research_Opportunity__c.object-meta.xml
<CustomObject>
    <label>Funding Opportunity</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Research_Opportunity__c/fields/I_RS_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initial</fullName>
                <default>true</default>
                <label>Initial</label>
            </value>
            <value>
                <fullName>Drafted</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Internal Applications Closed</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContentDocumentLinkTest.cls
/**
* Created by burnside on 2019-05-06.
*/
@IsTest
public with sharing class ContentDocumentLinkTest {
    
	@testSetup static void setup() {
        
        Account testAcc = TestUtility.newEmptyExternalAccount('Test LTU Account');
        Insert testAcc;
        
        //Contact testContact = TestUtility.newContact(GlobalConstants.CONTACT_RECORD_TYPE_NAME_LTU_STAFF, testAcc.Id);
        Contact testContact = TestUtility.createContact(testAcc.Id);
        testContact.FirstName = 'Test Contact';
        testContact.LastName = 'LTU';
        insert testContact;
    }
    
    static testMethod void contentDocumentLinkTest()
    {
        Project_Proposal__c projectProposal = TestUtility.newProjectProposal();
        projectProposal.I_RS_Theme__c = 'No theme alignment ';
        insert projectProposal;
        
        Blob beforeblob=Blob.valueOf('Unit Test Attachment Body');
        
        ContentVersion cv = new ContentVersion();
        cv.title = 'test content trigger';
        cv.PathOnClient ='test';
        cv.VersionData =beforeblob;
        insert cv;
        
        ContentVersion testContent = [SELECT Id, ContentDocumentId FROM ContentVersion where Id = :cv.Id];
        
        
        ContentDocumentLink contentlink=new ContentDocumentLink();
        contentlink.LinkedEntityId=projectProposal.Id;
        contentlink.ContentDocumentId=testcontent.ContentDocumentId;
        contentlink.ShareType = 'I';
        
        insert contentlink;
        
        update contentlink;
        
        System.assertequals('AllUsers', [select Visibility from ContentDocumentLink where Id = :contentLink.Id].Visibility);
    }
    
    private static Id getProjectPropsalRecTypeIdByDevName (String recordTypeAPIName) {
        return Schema.SObjectType.Project_Proposal__c.getRecordTypeInfosByDeveloperName().get(recordTypeAPIName).getRecordTypeId();
    }
    
    //This method tests the upload of new file against a locked proposal
    static testMethod void testNewFileUploadErrorWhenParentLocked2() {
        
        Account queryTestAcc = [Select Id FROM Account Where Name = 'Test LTU Account'];
        
        Contact queryTestCon = [Select Id FROM Contact Where FirstName = 'Test Contact' AND LastName = 'LTU'];
        Profile profile1 = [SELECT Id FROM Profile WHERE name = 'LTU Partner Community Login User' Limit 1];
        User testCommunityUser = TestUtility.newUser('test', profile1.Id, null, queryTestCon.Id);
        System.debug('-->testCommunityUser--> '+testCommunityUser);  
        Network testCommunityNetwork = [Select Id From Network Where Name = 'PRIME Researcher Portal'];
        System.debug('testCommunityNetwork'+testCommunityNetwork);
        
        Test.startTest();
        System.runAs(testCommunityUser){
            
            Project_Proposal__c projectProposalLockedForReview = TestUtility.newProjectProposal();
            projectProposalLockedForReview.Name = 'LockedProposal';
            projectProposalLockedForReview.RecordTypeId = getProjectPropsalRecTypeIdByDevName('I_RS_Proposal');
            projectProposalLockedForReview.I_RS_Status__c = 'Review By Research Office';
            
            Project_Proposal__c projectProposalLockedForApprovals = TestUtility.newProjectProposal();
            projectProposalLockedForApprovals.Name = 'LockedProposal';
            projectProposalLockedForApprovals.RecordTypeId = getProjectPropsalRecTypeIdByDevName('I_RS_Proposal');
            projectProposalLockedForApprovals.I_RS_Status__c = 'Approvals';
            projectProposalLockedForApprovals.I_RS_Approval_Flag__c = true;
            
            List<SObject> soList = new List<sObject>();
            soList.add((sObject) projectProposalLockedForReview);
            soList.add((sObject) projectProposalLockedForApprovals);
            
            //Insert soList;
            
            Blob testBlobFile1 = Blob.valueOf('Testing Content Version1');
            
            //Insert test content version for the draft proposal
            ContentVersion testCv1 = new ContentVersion();
            testCV1.title = 'test content trigger error1';
            testCV1.PathOnClient ='test';
            testCV1.VersionData = testBlobFile1;
            testCV1.IsMajorVersion = true;
            testCV1.NetworkId = testCommunityNetwork.Id;
            soList.add((ContentVersion) testCV1);
            
            // statements to be executed by this test user.
            Blob testBlobFile2 = Blob.valueOf('Testing Content Version2');
            
            ContentVersion testCv2 = new ContentVersion();
            testCv2.title = 'test content trigger error2';
            testCv2.PathOnClient ='test';
            testCv2.VersionData = testBlobFile2;
            testCv2.IsMajorVersion = true;
            testCv2.NetworkId = testCommunityNetwork.Id;
            
            soList.add((ContentVersion) testCV2);
            
            //Insert project proposal and content versions
            Insert soList;
            
            List<SObject> soList1 = new List<sObject>();
            
            List<ContentDocument> documents1 = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument Where Title = 'test content trigger error1'];
            System.debug('--> documents -->'+documents1);
            
            ContentDocumentLink testContentDoclink1 = new ContentDocumentLink();
            testContentDoclink1.LinkedEntityId = projectProposalLockedForReview.Id;
            testContentDoclink1.ContentDocumentId = documents1[0].Id;
            testContentDoclink1.ShareType = 'I';
            
            soList1.add((ContentDocumentLink) testContentDoclink1);
            
            List<ContentDocument> documents2 = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument Where Title = 'test content trigger error2'];
            System.debug('--> documents -->'+documents2);
            
            ContentDocumentLink testContentDoclink2 = new ContentDocumentLink();
            testContentDoclink2.LinkedEntityId = projectProposalLockedForApprovals.Id;
            testContentDoclink2.ContentDocumentId = documents2[0].Id;
            testContentDoclink2.ShareType = 'I';
            
            soList1.add((ContentDocumentLink) testContentDoclink2);
            
            try {
                //Insert content document links
                Insert soList1;
            }
            catch(Exception e) {
                System.debug('--> Error Message--> '+e.getMessage());
                Boolean expectedExceptionThrown =  e.getMessage().contains('Project proposal is currently locked down until Research Office has approved') ? true : false;
                System.AssertEquals(expectedExceptionThrown, true);
            }
            
        }
        Test.stopTest();
    }
    
    
    //This method tests the upload of new file against a locked proposal
    static testMethod void testNewFileUploadErrorWithFundingOpportunity() {
        
        Account queryTestAcc = [Select Id FROM Account Where Name = 'Test LTU Account'];
        
        Contact queryTestCon = [Select Id FROM Contact Where FirstName = 'Test Contact' AND LastName = 'LTU'];
        
        Profile profile1 = [SELECT Id FROM Profile WHERE name = 'LTU Partner Community User' Limit 1];
        
        User testCommunityUser = TestUtility.newUser('test', profile1.Id, null, queryTestCon.Id);
        System.debug('-->testCommunityUser--> '+testCommunityUser);  
        
        Network testCommunityNetwork = [Select Id From Network Where Name = 'PRIME Researcher Portal'];
        System.debug('testCommunityNetwork'+testCommunityNetwork);
        
        Research_Opportunity__c roRec = TestUtility.newResearchOpportunity(false);
        insert roRec;
        
        Test.startTest();
        System.runAs(testCommunityUser){
            Blob testBlobFile1 = Blob.valueOf('Testing Content Version1');
            
            //Insert test content version for the draft proposal
            ContentVersion testCv1 = new ContentVersion();
            testCV1.title = 'test content trigger error1';
            testCV1.PathOnClient ='test';
            testCV1.VersionData = testBlobFile1;
            testCV1.IsMajorVersion = true;
            testCV1.NetworkId = testCommunityNetwork.Id;
            
            //Insert content versions
            Insert testCV1;
            
            List<SObject> soList1 = new List<sObject>();
            
            List<ContentDocument> documents1 = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument Where Title = 'test content trigger error1'];
            System.debug('--> documents -->'+documents1);
            
            ContentDocumentLink testContentDoclink1 = new ContentDocumentLink();
            testContentDoclink1.LinkedEntityId = roRec.Id;
            testContentDoclink1.ContentDocumentId = documents1[0].Id;
            testContentDoclink1.ShareType = 'I';
            
            soList1.add((ContentDocumentLink) testContentDoclink1);
            
            
            try {
                 //Insert content document links
                Insert soList1;
            }
            catch(Exception e) {
                System.debug('--> Error Message--> '+e.getMessage());
                Boolean expectedExceptionThrown =  e.getMessage().contains(GlobalConstants.RESTRICT_DOCUMENT_UPLOAD_BY_RESEARCHER) ? true : false;
                System.AssertEquals(expectedExceptionThrown, true);
            }
            
        }
        Test.stopTest();
    }
    
}