force-app/main/default/objects/Account/fields/I_RS_End_Date__c.field-meta.xml
<CustomField>
    <fullName>I_RS_End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/I_RS_Include_GST_In_Budgeting__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Include_GST_In_Budgeting__c</fullName>
    <defaultValue>true</defaultValue>
    <description>When using Budget Calculator, apply GST to Non-Salary Items that are linked to this Organisation</description>
    <label>Include GST In Budgeting</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/I_RS_Maximum_Allowed_On_Cost__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Maximum_Allowed_On_Cost__c</fullName>
    <defaultValue>0.3574</defaultValue>
    <label>Maximum Allowed On-Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/I_RS_Part_of_La_Trobe__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Part_of_La_Trobe__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Part of La Trobe</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/I_RS_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Proposed</fullName>
                <isActive>false</isActive>
                <label>Proposed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/L_PR_Portfolio__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Portfolio__c</fullName>
    <label>Portfolio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>L_PR_Country_Portfolio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/Apex_Debug_Log__c.object-meta.xml
<CustomObject>
    <description>Captures results of non-user facing transactions such as Apex endpoints, callouts and asynchronous jobs</description>
    <label>Apex Debug Log</label>
    <nameField>
        <displayFormat>ADL-{00000000}</displayFormat>
        <label>Apex Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Apex_Class_Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Method_Name__c</fullName>
    <label>Apex Class Method Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <description>The invoking class that created the record</description>
    <label>Apex Class Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <description>If an exception occurs, this is the main message</description>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <label>Log Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/L_PR_Country_Reference__c/L_PR_Country_Reference__c.object-meta.xml
<CustomObject>
    <label>Country Reference</label>
    <nameField>
        <label>Country</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country References</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/L_PR_Country_Reference__c/fields/L_PR_Country_Alias__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Country_Alias__c</fullName>
    <label>Country Alias</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/L_PR_Country_Reference__c/fields/L_PR_Portfolio__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Portfolio__c</fullName>
    <label>Portfolio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>L_PR_Country_Portfolio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/L_PR_Country_Portfolio.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Australia (Onshore)</fullName>
    </customValue>
    <customValue>
        <fullName>Europe</fullName>
    </customValue>
    <customValue>
        <fullName>Greater China</fullName>
    </customValue>
    <customValue>
        <fullName>Latin America</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East</fullName>
    </customValue>
    <customValue>
        <fullName>North Africa</fullName>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
    </customValue>
    <customValue>
        <fullName>Pacific Islands</fullName>
    </customValue>
    <customValue>
        <fullName>South Asia</fullName>
    </customValue>
    <customValue>
        <fullName>South East Asia (Japan &amp; Korea)</fullName>
    </customValue>
    <customValue>
        <fullName>Sub-Saharan Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Vietnam</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <masterLabel>Country Portfolio</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AccountTriggerHelper.cls
public without sharing class AccountTriggerHelper {
    
    public static void handleBudgetRelatedFieldChanges(List<Account> accountsAfterDML, 
        Map<Id, Account> accountsBeforeDML){

            System.debug('handleBudgetRelatedFieldChanges');

            Set<Id> orgIdsToRecalculateBudgetsFor = new Set<Id>();

            for (Account accountAfterDML : accountsAfterDML){

                System.debug('Organisation changed?');

                Account accountBeforeDML = accountsBeforeDML.get(accountAfterDML.Id);
                
                Boolean partOfLaTrobeChanged = 
                    accountBeforeDML.I_RS_Part_Of_La_Trobe__c != accountAfterDML.I_RS_Part_Of_La_Trobe__c;
                System.debug('partOfLaTrobeChanged '+partOfLaTrobeChanged);

                Boolean maxOnCostChanged = 
                    accountBeforeDML.I_RS_Maximum_allowed_on_cost__c != accountAfterDML.I_RS_Maximum_allowed_on_cost__c;
                System.debug('maxOnCostChanged '+maxOnCostChanged);

                Boolean applyGSTChanged = 
                    accountBeforeDML.I_RS_Include_GST_In_Budgeting__c != accountAfterDML.I_RS_Include_GST_In_Budgeting__c;
                System.debug('applyGSTChanged '+applyGSTChanged);

                if (partOfLaTrobeChanged || maxOnCostChanged || applyGSTChanged){
                    orgIdsToRecalculateBudgetsFor.add(accountAfterDML.Id);
                }
                    
            }

            System.debug(orgIdsToRecalculateBudgetsFor);

            if (!orgIdsToRecalculateBudgetsFor.isEmpty()){
                System.enqueueJob(new RecordMergeBudgetHandler(orgIdsToRecalculateBudgetsFor, 'Account'));
            }

    }

    //LTU360-1640
    public static void updateEndDate(List<Account> accList, Map<Id, Account> oldAccMap){

        for(Account acc : accList){
            if(((oldAccMap != null && oldAccMap.get(acc.Id).I_RS_Status__c != 'Closed') && acc.I_RS_Status__c == 'Closed') 
            || (oldAccMap == null && acc.I_RS_Status__c == 'Closed')){
                acc.I_RS_End_Date__c = System.today();
            }
        }
    }

    // LTU360-2508
    public static void updatePortfolio(List<Account> listOfUpdatedAccountCountries){

        Map<String, String> countryReferencesMap = New Map<String, String>();

        try{
            for(L_PR_Country_Reference__c cr : [SELECT Id, Name, L_PR_Country_Alias__c, L_PR_Portfolio__c FROM L_PR_Country_Reference__c]){
                countryReferencesMap.put(cr.L_PR_Country_Alias__c, cr.L_PR_Portfolio__c);
            }
            system.debug('$$$countryReferencesMap'+countryReferencesMap);
            Map<Account, List<String>> accountIdandPortfolioMap = New Map<Account, List<String>>();
            List<String> countryRefsList = New List<String>();
        
            for(Account acc : listOfUpdatedAccountCountries){
                for(String cr : countryReferencesMap.keySet()){
                    if(cr != null){
                        if(cr.equalsIgnoreCase(acc.ShippingCountry)){
                            countryRefsList.add(countryReferencesMap.get(cr));
                            break;
                        }else if(cr.containsIgnoreCase(acc.ShippingCountry)){
                            countryRefsList.add(countryReferencesMap.get(cr));
                      }
                    }

                accountIdandPortfolioMap.put(acc,countryRefsList);
                }
                system.debug('$$$accountIdandPortfolioMap'+accountIdandPortfolioMap);
            }

            for(Account acc : accountIdandPortfolioMap.keySet()){

                List<String> listOfPortfolio = accountIdandPortfolioMap.get(acc);
                system.debug('$$$listOfPortfolio'+listOfPortfolio);
                system.debug('$$$listOfPortfolio.size()'+listOfPortfolio.size());
                if(listOfPortfolio != null){
                    if(listOfPortfolio.size() == 1){
                        acc.L_PR_Portfolio__c = listOfPortfolio[0];
                    }else{
                        acc.L_PR_Portfolio__c = null;
                    }
                }
            }
        }Catch(Exception e){
            Apex_Debug_Log__c debugLog = new Apex_Debug_Log__c();
            debugLog.Apex_Class_Name__c = 'AccountTriggerHelper';
            debugLog.Apex_Class_Method_Name__c = 'updatePortfolio';
            debugLog.Exception_message__c = e.getMessage();
            debugLog.Log_Type__c = 'Error';
            Insert debugLog;
        }
    }
}