force-app/main/default/objects/Account/fields/I_RS_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Proposed</fullName>
                <isActive>false</isActive>
                <label>Proposed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/Apex_Debug_Log__c.object-meta.xml
<CustomObject>
    <description>Captures results of non-user facing transactions such as Apex endpoints, callouts and asynchronous jobs</description>
    <label>Apex Debug Log</label>
    <nameField>
        <displayFormat>ADL-{00000000}</displayFormat>
        <label>Apex Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <description>The invoking class that created the record</description>
    <label>Apex Class Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <label>Log Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Transaction_Description__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Description__c</fullName>
    <description>Within the Apex Class and Method Name, give additional details on where/why this logging is happening. For example, two logs could happen in the same method - one is &apos;Save record&apos; and another is &apos;Schedule Batch&apos;.</description>
    <label>Transaction Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/L_PR_AccountStatusfieldUpdateBatch.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* L_PR_AccountStatusfieldUpdateBatch
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Kishore Reddy Basani
* @version        1.0
* @created        05-08-2022
* @Description	  This batch class is to update the status field of the Organisation to active if it is NULL or Proposed
* ─────────────────────────────────────────────────────────────────────────────────────────────────
*/

public  without sharing class L_PR_AccountStatusfieldUpdateBatch implements Database.Batchable<sObject>, Database.Stateful{

    Integer numberOfRecordsUpdated = 0;
    public Database.QueryLocator start(Database.BatchableContext bc){

        String strQuery = 'SELECT Id, Name, I_RS_Status__c from account where I_RS_Status__c= \'Proposed\' OR I_RS_Status__c = null';
        return database.getQueryLocator(strQuery);
    }

    public void execute(Database.BatchableContext bc, List<Account> accountList) {

        List<Account> accountListToBeUpdated = New List<Account>();

        for(Account acc : accountList){
            Account acct = New Account();
            if(acc.I_RS_Status__c == 'Proposed' || acc.I_RS_Status__c == null){
                acct.Id = acc.Id;
                acct.I_RS_Status__c = 'Active';
                numberOfRecordsUpdated++;
            }
            accountListToBeUpdated.add(acct);
        }

        if(!accountListToBeUpdated.isEmpty()){
            update accountListToBeUpdated;
        }
    }

    public void finish(Database.BatchableContext bc){
        Apex_Debug_Log__c debugLog = new Apex_Debug_Log__c();
        debugLog.Apex_Class_Name__c = 'L_PR_AccountStatusfieldUpdateBatch';
        debugLog.Transaction_Description__c = 'Number of account status records updated::' +numberOfRecordsUpdated + ' On the Date ::' + System.today();
        debugLog.Log_Type__c = 'Info';
        debugLog.Log_Type__c = 'Batch';
        insert debugLog;
    }

}