force-app/main/default/objects/Account/fields/I_RS_Part_of_La_Trobe__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Part_of_La_Trobe__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Part of La Trobe</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/I_RS_SAP_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>I_RS_SAP_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Ensure this number is 10 digits; include the leading zeroes</inlineHelpText>
    <label>Finance Customer Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment_of_Examiner__c/Appointment_of_Examiner__c.object-meta.xml
<CustomObject>
    <label>Appointment of Examiner</label>
    <nameField>
        <displayFormat>AOE-{00000}</displayFormat>
        <label>Form ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointment of Examiners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment_of_Examiner__c/fields/I_RS_BGR_Approver__c.field-meta.xml
<CustomField>
    <fullName>I_RS_BGR_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Chair of the Board of Graduate Research or delegate who can approve on behalf of the BGR</inlineHelpText>
    <label>BGR Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Appointment_of_Examiners_BGR_Approver</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment_of_Examiner__c/fields/I_RS_Graduate_Research_Examination__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Graduate_Research_Examination__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Link to the candidate’s examination record</inlineHelpText>
    <label>Graduate Research Examination ID</label>
    <referenceTo>Graduate_Research_Examination__c</referenceTo>
    <relationshipLabel>Appointment of Examiners</relationshipLabel>
    <relationshipName>Appointment_of_Examiners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment_of_Examiner__c/fields/I_RS_Potential_conflicts_of_interest_1st__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Potential_conflicts_of_interest_1st__c</fullName>
    <inlineHelpText>For details of what constitutes a potential or perceived COI, see Part D of the Graduate Research Examinations Procedure</inlineHelpText>
    <label>Any conflicts of interest? (Pick Yes/No)</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment_of_Examiner__c/fields/I_RS_Potential_conflicts_of_interest_2nd__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Potential_conflicts_of_interest_2nd__c</fullName>
    <inlineHelpText>For details of what constitutes a potential or perceived COI, see Part D of the Graduate Research Examinations Procedure</inlineHelpText>
    <label>Any conflicts of interest? (Pick Yes/No)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment_of_Examiner__c/fields/I_RS_Potential_conflicts_of_interest_3rd__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Potential_conflicts_of_interest_3rd__c</fullName>
    <inlineHelpText>For details of what constitutes a potential or perceived COI, see Part D of the Graduate Research Examinations Procedure</inlineHelpText>
    <label>Any conflicts of interest? (Pick Yes/No)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment_of_Examiner__c/fields/I_RS_Principal_supervisor__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Principal_supervisor__c</fullName>
    <formula>I_RS_Graduate_Research_Examination__r.I_RS_Principal_Supervisor__r.I_RS_Full_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Principal supervisor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment_of_Examiner__c/fields/I_RS_SDGR_Approver__c.field-meta.xml
<CustomField>
    <fullName>I_RS_SDGR_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Normally the Director of Graduate Research for the candidate’s school, unless they have a conflict, in which case will usually be the Head of School.</inlineHelpText>
    <label>SDGR Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Appointment_of_Examiners_SDGR_Approver</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment_of_Examiner__c/fields/I_RS_Student__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Kept in sync with the student lookup on the GRE. Used for email alerts that fire from this object.</description>
    <label>Student</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointment of Examiners (Student)</relationshipLabel>
    <relationshipName>Appointment_of_Examiners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_RS_Related_User__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Related_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Refers to the user record associated to the contact</description>
    <label>Related User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Graduate_Research_Examination__c/Graduate_Research_Examination__c.object-meta.xml
<CustomObject>
    <label>Graduate Research Examination</label>
    <nameField>
        <displayFormat>GRE-{00000}</displayFormat>
        <label>Record Title</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Graduate Research Examinations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Graduate_Research_Examination__c/fields/I_RS_Alternate_Supervisor__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Alternate_Supervisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Co-supervisor who has been nominated to act as approver if the principal supervisor is unavailable</inlineHelpText>
    <label>Alternate Supervisor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Graduate Research Examinations (Co-Supervisor)</relationshipLabel>
    <relationshipName>Co_Supervisor_Thesis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Graduate_Research_Examination__c/fields/I_RS_BGR_Approver__c.field-meta.xml
<CustomField>
    <fullName>I_RS_BGR_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Chair of the Board of Graduate Research or delegate who can approve on behalf of the BGR</inlineHelpText>
    <label>BGR Approver</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.I_RS_Related_User__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Graduate Research Examinations (BGR Approver)</relationshipLabel>
    <relationshipName>BGR_Approver_Thesis_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Graduate_Research_Examination__c/fields/I_RS_Board_of_Graduate_Research__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Board_of_Graduate_Research__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Board of Graduate Research member with delegated responsibility to approve on behalf of the Board, normally the Chair</inlineHelpText>
    <label>Board of Graduate Research</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Graduate Research Examinations (Board of Graduate Research)</relationshipLabel>
    <relationshipName>Board_of_Graduate_Research_Thesis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Graduate_Research_Examination__c/fields/I_RS_Director_of_Graduate_Research__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Director_of_Graduate_Research__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Director of Graduate Research for the candidate&apos;s school, unless they have a conflict, in which case will be an alternative, usually the Head of School</inlineHelpText>
    <label>Director of Graduate Research</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Graduate Research Examinations (Director of Graduate Research)</relationshipLabel>
    <relationshipName>Director_of_Graduate_Research_Thesis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Graduate_Research_Examination__c/fields/I_RS_Principal_Supervisor__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Principal_Supervisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Principal Supervisor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Graduate Research Examinations (Principal Supervisor)</relationshipLabel>
    <relationshipName>Principal_Supervisor_Thesis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Graduate_Research_Examination__c/fields/I_RS_SDGR_Approver__c.field-meta.xml
<CustomField>
    <fullName>I_RS_SDGR_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Normally the Director of Graduate Research for the candidate’s school, unless they have a conflict, in which case will usually be the Head of School</inlineHelpText>
    <label>SDGR Approver</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.I_RS_Related_User__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Graduate Research Examinations (SDGR Approver)</relationshipLabel>
    <relationshipName>SDGR_Approver_Thesis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Graduate_Research_Examination__c/fields/I_RS_Student__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Graduate Research Examinations</relationshipLabel>
    <relationshipName>Graduate_Research_Examinations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Graduate_Research_Examination__c/fields/I_RS_Substitute_Board_Graduate_Research__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Substitute_Board_Graduate_Research__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Deputy Chair or other member of the Board of Graduate Research with delegated responsibility for approvals on behalf of the BGR</inlineHelpText>
    <label>Alternate Board of Graduate Research</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Graduate Research Examinations (Substitute Board of Graduate Research)</relationshipLabel>
    <relationshipName>Substitute_Board_Thesis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Graduate_Research_Examination__c/fields/I_RS_Substitute_DirectorGraduateResearch__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Substitute_DirectorGraduateResearch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Nominated delegate who can approve on behalf of the School Director of Graduate Research if they are unavailable, usually the Head of School</inlineHelpText>
    <label>Alternate Director of Graduate Research</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Graduate Research Examinations (Substitute Director of Graduate Research)</relationshipLabel>
    <relationshipName>Substitute_Director_Thesis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Graduate_Research_Examination__c/fields/I_RS_Supervisor_Approver__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Supervisor_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Name of the supervisor acting as the approver for examinations forms, normally the principal supervisor unless unavailable</inlineHelpText>
    <label>Supervisor Approver</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.I_RS_Related_User__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Graduate Research Examinations (Supervisor Approver)</relationshipLabel>
    <relationshipName>Supervisor_Approver_Thesis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ThesisApexShareTest.cls
@isTest
public class ThesisApexShareTest {
	@testSetup
    static void setup() {
        AccountContactRelationHandler.runHierarchySharing = false;
        AccountContactRelationHandler.runPositionHistory = false;
        ContactTriggerHandler.runHierarchySharing = false;
	    ContactTriggerHandler.runProjectTeamMemberSharing = false;

        List<Contact> updateList = new List<Contact>();
        Profile researcherProfile = [SELECT Id FROM Profile WHERE Name='LTU Partner Community Login User'  LIMIT 1];
        
        //Create Account
        Account tstAccount = new Account(Name = 'La Trobe University',
        I_RS_Part_of_La_Trobe__c = true,
        I_RS_SAP_Customer_Number__c = '1234567890');
        insert tstAccount;
        tstAccount.IsPartner = True;
        update tstAccount;
        
        Contact StudentContact = new Contact(FirstName = 'Student', LastName = 'Reseracher', email = 'Student@test.edu.com');
        StudentContact.AccountId = tstAccount.Id;
        insert StudentContact;
        User StudentUser = new User(Alias = 'student', Email=StudentContact.Email, 
            EmailEncodingKey='UTF-8', LastName=StudentContact.LastName, LanguageLocaleKey='en_US', 
            LocaleSidKey='en_AU', ProfileId = researcherProfile.Id, ContactId = StudentContact.Id,
            TimeZoneSidKey='Australia/Sydney', UserName=StudentContact.Email);
        Insert StudentUser;
        StudentContact.I_RS_Related_User__c = StudentUser.Id;
        updateList.add(StudentContact);
        
        Contact PrincipalSupervisorContact = new Contact(FirstName = 'Principal', LastName = 'Supervisor', email = 'PrincipalSupervisor@test.edu.com');
        PrincipalSupervisorContact.AccountId = tstAccount.Id;
        insert PrincipalSupervisorContact;
        User PrincipalSupervisorUser = new User(Alias = 'PS', Email=PrincipalSupervisorContact.Email, 
            EmailEncodingKey='UTF-8', LastName=PrincipalSupervisorContact.LastName, LanguageLocaleKey='en_US', 
            LocaleSidKey='en_AU', ProfileId = researcherProfile.Id, ContactId = PrincipalSupervisorContact.Id,
            TimeZoneSidKey='Australia/Sydney', UserName=PrincipalSupervisorContact.Email);
        Insert PrincipalSupervisorUser;
        PrincipalSupervisorContact.I_RS_Related_User__c = PrincipalSupervisorUser.Id;
        updateList.add(PrincipalSupervisorContact);
        
        Contact AlternateSupervisorContact = new Contact(FirstName = 'Alternate', LastName = 'Supervisor', email = 'AlternateSupervisor@test.edu.com');
        AlternateSupervisorContact.AccountId = tstAccount.Id;
        insert AlternateSupervisorContact;
        User AlternateSupervisorUser = new User(Alias = 'As', Email=AlternateSupervisorContact.Email, 
            EmailEncodingKey='UTF-8', LastName=AlternateSupervisorContact.LastName, LanguageLocaleKey='en_US', 
            LocaleSidKey='en_AU', ProfileId = researcherProfile.Id, ContactId = AlternateSupervisorContact.Id,
            TimeZoneSidKey='Australia/Sydney', UserName=AlternateSupervisorContact.Email);
        Insert AlternateSupervisorUser;
        AlternateSupervisorContact.I_RS_Related_User__c = AlternateSupervisorUser.Id;
        updateList.add(AlternateSupervisorContact);
        
        Contact DGRContact = new Contact(FirstName = 'DGR', LastName = 'DGR', email = 'DGR@test.edu.com');
        DGRContact.AccountId = tstAccount.Id;
        insert DGRContact;
       User DGRUser = new User(Alias = 'dgr', Email=DGRContact.Email, 
            EmailEncodingKey='UTF-8', LastName=DGRContact.LastName, LanguageLocaleKey='en_US', 
            LocaleSidKey='en_AU', ProfileId = researcherProfile.Id, ContactId = DGRContact.Id,
            TimeZoneSidKey='Australia/Sydney', UserName=DGRContact.Email);
        Insert DGRUser;
        DGRContact.I_RS_Related_User__c = DGRUser.Id;
        updateList.add(DGRContact);
      
        Contact SubDGRContact = new Contact(FirstName = 'SubDGR', LastName = 'DGR', email = 'SubDGR@test.edu.com');
        SubDGRContact.AccountId = tstAccount.Id;
        insert SubDGRContact;
        User SubDGRUser = new User(Alias = 'sdgr', Email=SubDGRContact.Email, 
            EmailEncodingKey='UTF-8', LastName=SubDGRContact.LastName, LanguageLocaleKey='en_US', 
            LocaleSidKey='en_AU', ProfileId = researcherProfile.Id, ContactId = SubDGRContact.Id,
            TimeZoneSidKey='Australia/Sydney', UserName=SubDGRContact.Email);
        Insert SubDGRUser;
        SubDGRContact.I_RS_Related_User__c = SubDGRUser.Id;
        updateList.add(SubDGRContact);
        
        Contact BGRContact = new Contact(FirstName = 'BGR', LastName = 'BGR', email = 'BGR@test.edu.com');
        BGRContact.AccountId = tstAccount.Id;
        insert BGRContact;
        User BGRUser = new User(Alias = 'bgr', Email=BGRContact.Email, 
            EmailEncodingKey='UTF-8', LastName=BGRContact.LastName, LanguageLocaleKey='en_US', 
            LocaleSidKey='en_AU', ProfileId = researcherProfile.Id, ContactId = BGRContact.Id,
            TimeZoneSidKey='Australia/Sydney', UserName=BGRContact.Email);
        Insert BGRUser;
        BGRContact.I_RS_Related_User__c = BGRUser.Id;
        updateList.add(BGRContact);
      
        Contact SubBGRContact = new Contact(FirstName = 'SubBGR', LastName = 'BGR', email = 'SubBGR@test.edu.com');
        SubBGRContact.AccountId = tstAccount.Id;
        insert SubBGRContact;
        User SubBGRUser = new User(Alias = 'bbgr', Email=SubBGRContact.Email, 
            EmailEncodingKey='UTF-8', LastName=SubBGRContact.LastName, LanguageLocaleKey='en_US', 
            LocaleSidKey='en_AU', ProfileId = researcherProfile.Id, ContactId = SubBGRContact.Id,
            TimeZoneSidKey='Australia/Sydney', UserName=SubBGRContact.Email);
        Insert SubBGRUser;
        SubBGRContact.I_RS_Related_User__c = SubBGRUser.Id;
        updateList.add(SubBGRContact);
        
        update updateList;
               
        
    }
    
    @isTest
    public static void testInsertSharing(){
        Test.startTest();
        Contact StudentContact;
        Contact PrincipalSupervisorContact;
        Contact AlternateSupervisorContact;
        Contact DGRContact;
        Contact SubDGRContact;
        Contact BGRContact;
        Contact SubBGRContact;
		
        for (Contact c:[SELECT Id, FirstName, I_RS_Related_User__c FROM Contact]) {
            if (c.FirstName == 'Student') {
        		StudentContact = c;
            } else if (c.FirstName == 'Principal') {
        		PrincipalSupervisorContact = c;
            } else if (c.FirstName == 'Alternate') {
        		AlternateSupervisorContact = c;
            } else if (c.FirstName == 'DGR') {
        		DGRContact = c;
            } else if (c.FirstName == 'SubDGR') {
        		SubDGRContact = c;
            } else if (c.FirstName == 'BGR') {
        		BGRContact = c;
            } else if (c.FirstName == 'SubBGR') {
        		SubBGRContact = c;
            }
        }

        Graduate_Research_Examination__c gre = new Graduate_Research_Examination__c();
        gre.OwnerId = StudentContact.I_RS_Related_User__c;
        gre.I_RS_Student__c = StudentContact.Id;
        gre.I_RS_Principal_Supervisor__c = PrincipalSupervisorContact.Id;
        gre.I_RS_Alternate_Supervisor__c = AlternateSupervisorContact.Id;
        gre.I_RS_Director_of_Graduate_Research__c = DGRContact.Id;
        gre.I_RS_Substitute_DirectorGraduateResearch__c = SubDGRContact.Id;
        gre.I_RS_Substitute_Board_Graduate_Research__c = BGRContact.Id;
        gre.I_RS_Board_of_Graduate_Research__c = SubBGRContact.Id;
        gre.I_RS_Supervisor_Approver__c = AlternateSupervisorContact.Id;
        gre.I_RS_SDGR_Approver__c = SubDGRContact.Id;
        gre.I_RS_BGR_Approver__c = SubBGRContact.Id;
        insert gre;
        Appointment_of_Examiner__c aoe = new Appointment_of_Examiner__c(I_RS_Graduate_Research_Examination__c = gre.id);
        aoe.OwnerId = PrincipalSupervisorContact.I_RS_Related_User__c;
        aoe.I_RS_Potential_conflicts_of_interest_1st__c='Yes';
        aoe.I_RS_Potential_conflicts_of_interest_2nd__c='Yes';
        aoe.I_RS_Potential_conflicts_of_interest_3rd__c='Yes';
        insert aoe;
        
        List<String> greRowCauses = new List<String>();
        greRowCauses.add(Schema.Graduate_Research_Examination__share.rowCause.Alternate_Supervisor__c);
        greRowCauses.add(Schema.Graduate_Research_Examination__share.rowCause.DGR__c);
        greRowCauses.add(Schema.Graduate_Research_Examination__share.rowCause.DGS__c);
        greRowCauses.add(Schema.Graduate_Research_Examination__share.rowCause.Principal_Supervisor__c);
        greRowCauses.add(Schema.Graduate_Research_Examination__share.rowCause.SDGR__c);
        greRowCauses.add(Schema.Graduate_Research_Examination__share.rowCause.SDGS__c);
        greRowCauses.add(Schema.Graduate_Research_Examination__share.rowCause.Student__c);
        
        List<Graduate_Research_Examination__share> greShares = [SELECT Id FROM Graduate_Research_Examination__share WHERE RowCause IN :greRowCauses ];
        List<Appointment_of_Examiner__share> aoeShares = [SELECT Id FROM Appointment_of_Examiner__share WHERE RowCause IN :greRowCauses ];
        
        System.assertEquals(7, greShares.size(), 'GRE shares mismatch');
        System.assertEquals(6, aoeShares.size(), 'AOE shares mismatch');
        Test.stopTest();
        
    }
    
    @isTest
    public static void testUpdateSharing(){
        Test.startTest();
        Contact StudentContact;
        Contact PrincipalSupervisorContact;
        Contact AlternateSupervisorContact;
        Contact DGRContact;
        Contact SubDGRContact;
        Contact BGRContact;
        Contact SubBGRContact;
		
        for (Contact c:[SELECT Id, FirstName, I_RS_Related_User__c FROM Contact]) {
            if (c.FirstName == 'Student') {
        		StudentContact = c;
            } else if (c.FirstName == 'Principal') {
        		PrincipalSupervisorContact = c;
            } else if (c.FirstName == 'Alternate') {
        		AlternateSupervisorContact = c;
            } else if (c.FirstName == 'DGR') {
        		DGRContact = c;
            } else if (c.FirstName == 'SubDGR') {
        		SubDGRContact = c;
            } else if (c.FirstName == 'BGR') {
        		BGRContact = c;
            } else if (c.FirstName == 'SubBGR') {
        		SubBGRContact = c;
            }
        }

        Graduate_Research_Examination__c gre = new Graduate_Research_Examination__c();
        gre.OwnerId = StudentContact.I_RS_Related_User__c;
        gre.I_RS_Supervisor_Approver__c = AlternateSupervisorContact.Id;
        gre.I_RS_SDGR_Approver__c = SubDGRContact.Id;
        gre.I_RS_BGR_Approver__c = SubBGRContact.Id;
        insert gre;
        
        Appointment_of_Examiner__c aoe = new Appointment_of_Examiner__c();
        aoe.I_RS_Graduate_Research_Examination__c = gre.id;
        aoe.OwnerId = PrincipalSupervisorContact.I_RS_Related_User__c;
        aoe.I_RS_Potential_conflicts_of_interest_1st__c='Yes';
        aoe.I_RS_Potential_conflicts_of_interest_2nd__c='Yes';
        aoe.I_RS_Potential_conflicts_of_interest_3rd__c='Yes';
        insert aoe;

        gre.I_RS_Student__c = StudentContact.Id;
        gre.I_RS_Principal_Supervisor__c = PrincipalSupervisorContact.Id;
        gre.I_RS_Alternate_Supervisor__c = AlternateSupervisorContact.Id;
        gre.I_RS_Director_of_Graduate_Research__c = DGRContact.Id;
        gre.I_RS_Substitute_DirectorGraduateResearch__c = SubDGRContact.Id;
        gre.I_RS_Substitute_Board_Graduate_Research__c = BGRContact.Id;
        gre.I_RS_Board_of_Graduate_Research__c = SubBGRContact.Id;
        gre.I_RS_Supervisor_Approver__c = AlternateSupervisorContact.Id;
        gre.I_RS_SDGR_Approver__c = SubDGRContact.Id;
        gre.I_RS_BGR_Approver__c = SubBGRContact.Id;
        update gre;
        
        aoe.I_RS_Graduate_Research_Examination__c = gre.id;
        update aoe;
        
               
        List<String> greRowCauses = new List<String>();
        greRowCauses.add(Schema.Graduate_Research_Examination__share.rowCause.Alternate_Supervisor__c);
        greRowCauses.add(Schema.Graduate_Research_Examination__share.rowCause.DGR__c);
        greRowCauses.add(Schema.Graduate_Research_Examination__share.rowCause.DGS__c);
        greRowCauses.add(Schema.Graduate_Research_Examination__share.rowCause.Principal_Supervisor__c);
        greRowCauses.add(Schema.Graduate_Research_Examination__share.rowCause.SDGR__c);
        greRowCauses.add(Schema.Graduate_Research_Examination__share.rowCause.SDGS__c);
        greRowCauses.add(Schema.Graduate_Research_Examination__share.rowCause.Student__c);
        
        List<Graduate_Research_Examination__share> greShares = [SELECT Id FROM Graduate_Research_Examination__share WHERE RowCause IN :greRowCauses ];
        List<Appointment_of_Examiner__share> aoeShares = [SELECT Id FROM Appointment_of_Examiner__share WHERE RowCause IN :greRowCauses ];
        
        System.assertEquals(7, greShares.size(), 'GRE shares mismatch');
        System.assertEquals(6, aoeShares.size(), 'AOE shares mismatch');
        
        //clear one field
        gre.I_RS_Board_of_Graduate_Research__c = null;
        gre.I_RS_SDGR_Approver__c = null;
        update gre;

        greShares = [SELECT Id FROM Graduate_Research_Examination__share WHERE RowCause IN :greRowCauses ];
        aoeShares = [SELECT Id FROM Appointment_of_Examiner__share WHERE RowCause IN :greRowCauses ];
        
        System.assertEquals(6, greShares.size(), 'GRE shares mismatch');
        System.assertEquals(5, aoeShares.size(), 'GRE shares mismatch');
        
        Test.stopTest();

        /*gre.I_RS_SDGR_Approver__c = SubDGRContact.Id;
        update gre;

        aoe.I_RS_Graduate_Research_Examination__c = null;
        update aoe;
        aoeShares = [SELECT Id FROM Appointment_of_Examiner__share WHERE RowCause IN :greRowCauses ];
        System.assertEquals(0, aoeShares.size(), 'AOE shares mismatch');
        
        delete gre;
        delete aoe;
        greShares = [SELECT Id FROM Graduate_Research_Examination__share WHERE RowCause IN :greRowCauses ];
        aoeShares = [SELECT Id FROM Appointment_of_Examiner__share WHERE RowCause IN :greRowCauses ];
        
        System.assertEquals(0, greShares.size(), 'GRE shares mismatch');
        System.assertEquals(0, aoeShares.size(), 'GRE shares mismatch');*/
        
    }
    @isTest
    public static void testUpdateSharing2(){
        Test.startTest();
        Contact StudentContact;
        Contact PrincipalSupervisorContact;
        Contact AlternateSupervisorContact;
        Contact DGRContact;
        Contact SubDGRContact;
        Contact BGRContact;
        Contact SubBGRContact;
		
        for (Contact c:[SELECT Id, FirstName, I_RS_Related_User__c FROM Contact]) {
            if (c.FirstName == 'Student') {
        		StudentContact = c;
            } else if (c.FirstName == 'Principal') {
        		PrincipalSupervisorContact = c;
            } else if (c.FirstName == 'Alternate') {
        		AlternateSupervisorContact = c;
            } else if (c.FirstName == 'DGR') {
        		DGRContact = c;
            } else if (c.FirstName == 'SubDGR') {
        		SubDGRContact = c;
            } else if (c.FirstName == 'BGR') {
        		BGRContact = c;
            } else if (c.FirstName == 'SubBGR') {
        		SubBGRContact = c;
            }
        }

        Graduate_Research_Examination__c gre = new Graduate_Research_Examination__c();
        gre.OwnerId = StudentContact.I_RS_Related_User__c;
        gre.I_RS_Student__c = StudentContact.Id;
        gre.I_RS_Principal_Supervisor__c = PrincipalSupervisorContact.Id;
        gre.I_RS_Alternate_Supervisor__c = AlternateSupervisorContact.Id;
        gre.I_RS_Director_of_Graduate_Research__c = DGRContact.Id;
        gre.I_RS_Substitute_DirectorGraduateResearch__c = SubDGRContact.Id;
        gre.I_RS_Substitute_Board_Graduate_Research__c = BGRContact.Id;
        gre.I_RS_Board_of_Graduate_Research__c = SubBGRContact.Id;
        gre.I_RS_Supervisor_Approver__c = AlternateSupervisorContact.Id;
        gre.I_RS_SDGR_Approver__c = SubDGRContact.Id;
        gre.I_RS_BGR_Approver__c = SubBGRContact.Id;
        insert gre;
        
        Appointment_of_Examiner__c aoe = new Appointment_of_Examiner__c();
        aoe.I_RS_Graduate_Research_Examination__c = gre.id;
        aoe.OwnerId = PrincipalSupervisorContact.I_RS_Related_User__c;
        aoe.I_RS_Graduate_Research_Examination__c = gre.id;
        aoe.I_RS_Potential_conflicts_of_interest_1st__c='Yes';
        aoe.I_RS_Potential_conflicts_of_interest_2nd__c='Yes';
        aoe.I_RS_Potential_conflicts_of_interest_3rd__c='Yes';
        insert aoe;

        List<String> greRowCauses = new List<String>();
        greRowCauses.add(Schema.Graduate_Research_Examination__share.rowCause.Alternate_Supervisor__c);
        greRowCauses.add(Schema.Graduate_Research_Examination__share.rowCause.DGR__c);
        greRowCauses.add(Schema.Graduate_Research_Examination__share.rowCause.DGS__c);
        greRowCauses.add(Schema.Graduate_Research_Examination__share.rowCause.Principal_Supervisor__c);
        greRowCauses.add(Schema.Graduate_Research_Examination__share.rowCause.SDGR__c);
        greRowCauses.add(Schema.Graduate_Research_Examination__share.rowCause.SDGS__c);
        greRowCauses.add(Schema.Graduate_Research_Examination__share.rowCause.Student__c);
        
        aoe.I_RS_Graduate_Research_Examination__c = null;
        update aoe;
        List<Appointment_of_Examiner__share> aoeShares = [SELECT Id FROM Appointment_of_Examiner__share WHERE RowCause IN :greRowCauses ];
        System.assertEquals(0, aoeShares.size(), 'AOE shares mismatch');
        
        delete gre;
        delete aoe;
        List<Graduate_Research_Examination__share> greShares = [SELECT Id FROM Graduate_Research_Examination__share WHERE RowCause IN :greRowCauses ];
        aoeShares = [SELECT Id FROM Appointment_of_Examiner__share WHERE RowCause IN :greRowCauses ];
        
        System.assertEquals(0, greShares.size(), 'GRE shares mismatch');
        System.assertEquals(0, aoeShares.size(), 'GRE shares mismatch');
        Test.stopTest();
        
    }
}