force-app/main/default/objects/Account/fields/I_RS_Confidential__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Confidential__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hidden from Researcher Portal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/I_ST_Lead_Account.recordType-meta.xml
<RecordType>
    <fullName>I_ST_Lead_Account</fullName>
    <active>true</active>
    <description>An administrative account for Leads that are not associated with an Account.</description>
    <label>Lead Account</label>
</RecordType>

force-app/main/default/objects/Case/fields/I_RM_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Affiliation</description>
    <label>Affiliation</label>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/IST.recordType-meta.xml
<RecordType>
    <fullName>IST</fullName>
    <active>true</active>
    <businessProcess>PRIME</businessProcess>
    <description>Record type for IST Support</description>
    <label>IST</label>
</RecordType>

force-app/main/default/objects/Contact/fields/I_RS_Citizenship__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Citizenship__c</fullName>
    <label>Country of Citizenship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>I_RM_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/I_RS_Confidential__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Confidential__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Tick to prevent Contact from appearing in the Prime Researcher Portal</inlineHelpText>
    <label>Hidden from Researcher Portal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_RS_Deceased__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Deceased__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deceased</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_RS_Is_Organisation_Confidential__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Is_Organisation_Confidential__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Organisation Confidential?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_RS_Related_User__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Related_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Refers to the user record associated to the contact</description>
    <label>Related User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_RS_Salary_Grade__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Salary_Grade__c</fullName>
    <label>Salary Grade (HR)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Level A 1</fullName>
            </value>
            <value>
                <fullName>Level A 2</fullName>
            </value>
            <value>
                <fullName>Level A 3</fullName>
            </value>
            <value>
                <fullName>Level A 4</fullName>
            </value>
            <value>
                <fullName>Level A 5</fullName>
            </value>
            <value>
                <fullName>Level A 6</fullName>
            </value>
            <value>
                <fullName>Level A 7</fullName>
            </value>
            <value>
                <fullName>Level A 8</fullName>
            </value>
            <value>
                <fullName>Level B 1</fullName>
            </value>
            <value>
                <fullName>Level B 2</fullName>
            </value>
            <value>
                <fullName>Level B 3</fullName>
            </value>
            <value>
                <fullName>Level B 4</fullName>
            </value>
            <value>
                <fullName>Level B 5</fullName>
            </value>
            <value>
                <fullName>Level B 6</fullName>
            </value>
            <value>
                <fullName>Level C 1</fullName>
            </value>
            <value>
                <fullName>Level C 2</fullName>
            </value>
            <value>
                <fullName>Level C 3</fullName>
            </value>
            <value>
                <fullName>Level C 4</fullName>
            </value>
            <value>
                <fullName>Level C 5</fullName>
            </value>
            <value>
                <fullName>Level C 6</fullName>
            </value>
            <value>
                <fullName>Level D 1</fullName>
            </value>
            <value>
                <fullName>Level D 2</fullName>
            </value>
            <value>
                <fullName>Level D 3</fullName>
            </value>
            <value>
                <fullName>Level D 4</fullName>
            </value>
            <value>
                <fullName>Level E 1</fullName>
            </value>
            <value>
                <fullName>HEO1-1</fullName>
            </value>
            <value>
                <fullName>HEO1-2</fullName>
            </value>
            <value>
                <fullName>HEO1-3</fullName>
            </value>
            <value>
                <fullName>HEO1-4</fullName>
            </value>
            <value>
                <fullName>HEO2-1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/I_ST_Calculate_Contact_Score__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Calculate_Contact_Score__c</fullName>
    <defaultValue>false</defaultValue>
    <label>I ST Calculate Contact Score</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/I_RM_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Part of the remediation project to store different personas</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_IL_Intended_Funding_Source__c.field-meta.xml
<CustomField>
    <fullName>I_IL_Intended_Funding_Source__c</fullName>
    <description>Depicts candidate’s education funding source</description>
    <label>Intended Funding Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Self-funded</fullName>
            </value>
            <value>
                <fullName>Family-funded</fullName>
            </value>
            <value>
                <fullName>Coursework Scholarship</fullName>
            </value>
            <value>
                <fullName>Graduate Research Scholarship</fullName>
            </value>
            <value>
                <fullName>Graduate Research External Sponsorship</fullName>
            </value>
            <value>
                <fullName>Coursework External Sponsorship</fullName>
            </value>
            <value>
                <fullName>Bank Loan</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Coursework External Scholarship</fullName>
                <isActive>false</isActive>
                <label>Coursework External Scholarship</label>
            </value>
            <value>
                <fullName>Graduate Research External Scholarship</fullName>
                <isActive>false</isActive>
                <label>Graduate Research External Scholarship</label>
            </value>
            <value>
                <fullName>Research External Scholarship/Sponsorship</fullName>
                <isActive>false</isActive>
                <label>Research External Scholarship/Sponsorship</label>
            </value>
            <value>
                <fullName>Scholarship</fullName>
                <isActive>false</isActive>
                <label>Scholarship</label>
            </value>
            <value>
                <fullName>Sponsored by University</fullName>
                <isActive>false</isActive>
                <label>Sponsored by University</label>
            </value>
            <value>
                <fullName>Sponsored by company or organisation</fullName>
                <isActive>false</isActive>
                <label>Sponsored by company or organisation</label>
            </value>
            <value>
                <fullName>Sponsored by government</fullName>
                <isActive>false</isActive>
                <label>Sponsored by government</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_IL_Sponsored__c.field-meta.xml
<CustomField>
    <fullName>I_IL_Sponsored__c</fullName>
    <description>Depicts whether a candidate is sponsored</description>
    <label>Sponsored</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Account__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to organisation</description>
    <label>Organisation</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>I_RS_External_Organisation</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>I_RS_La_Trobe_Organisation_Unit</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>I_ST_Educational_Institution</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliations</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Active__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Active__c</fullName>
    <description>Used in matching rule to ensure inactive records aren&apos;t used in duplicate checks</description>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>True</fullName>
                <default>true</default>
                <label>True</label>
            </value>
            <value>
                <fullName>False</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Contact__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Contact__c</fullName>
    <description>The person/contact who this Affiliation relates to</description>
    <inlineHelpText>The person this affiliation relates to</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Affiliations</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_EndDate__c.field-meta.xml
<CustomField>
    <fullName>I_RM_EndDate__c</fullName>
    <description>Depicts Affiliations End Date.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <description>Indicates the status of the Affiliation.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>I_RM_Role__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>I_ST_Contact_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/L_PR_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Contact_Name__c</fullName>
    <label>Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_ST_Lead_Scoring__mdt/I_ST_Lead_Scoring__mdt.object-meta.xml
<CustomObject>
    <description>Key Value pairs which are used to calulate a Lead&apos;s score</description>
    <label>Lead Scoring</label>
    <pluralLabel>Lead Scoring</pluralLabel>
</CustomObject>

force-app/main/default/objects/I_ST_Lead_Scoring__mdt/fields/I_ST_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Field_API_Name__c</fullName>
    <label>Field API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/I_RM_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Åland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Argentinian Antarctic Territory</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Australian Antarctic Territory</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas (the)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia (Plurinational State of)</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/I_ST_Contact_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Admitted</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And LOA</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Not Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Considered</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Made</fullName>
    </customValue>
    <customValue>
        <fullName>Await Academic Advice</fullName>
    </customValue>
    <customValue>
        <fullName>Await Applicant Comms</fullName>
    </customValue>
    <customValue>
        <fullName>Await Further Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Awaiting Interview</fullName>
    </customValue>
    <customValue>
        <fullName>Await Required Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Escalated</fullName>
    </customValue>
    <customValue>
        <fullName>Make A Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make Alternate Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make An Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Nearing Completion</fullName>
    </customValue>
    <customValue>
        <fullName>Not Processed</fullName>
    </customValue>
    <customValue>
        <fullName>Not Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Lapsed</fullName>
    </customValue>
    <customValue>
        <fullName>Other Preference Offered</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Results</fullName>
    </customValue>
    <customValue>
        <fullName>Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <description>Global value set is created for lead(contact) object ST -51</description>
    <masterLabel>I_ST_Contact_Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContactTriggerHelper.cls
/*
* @Modified by Vanita - 02/03/2022 - As part of remediation commented CTE call
*/
public class ContactTriggerHelper {
    
    @InvocableMethod(label='Clear Contact Related User' description='Cleares the "Related User" field of Contact.')
    public static void ClearContactRelatedUser(List<Id> ContactIds) {
        ClearContactRelatedUserFuture(ContactIds);
    }
    
    @future
    public static void ClearContactRelatedUserFuture(List<Id> ContactIds) {
        List<Contact> Contacts = new List<Contact>();
        for (Id i: ContactIds) {
            Contact c = new Contact(Id = i, I_RS_Related_User__c = null);
            Contacts.add(c);
        }
        update Contacts;
    }
    
    
    public static void handleBudgetRelatedFieldChanges(List<Contact> contactsAfterDML, Map<Id, contact> contactsBeforeDML){
        
        System.debug('handleBudgetRelatedFieldChanges');
        
        Set<Id> contactIdsToRecalculateBudgetsFor = new Set<Id>();
        
        for (contact contactAfterDML : contactsAfterDML){
            
            System.debug('contact changed?');
            
            contact contactBeforeDML = contactsBeforeDML.get(contactAfterDML.Id);
            
            Boolean salaryGradeChanged = 
                contactBeforeDML.I_RS_Salary_Grade__c != contactAfterDML.I_RS_Salary_Grade__c;
            System.debug('salaryGradeChanged '+salaryGradeChanged);
            
            if (salaryGradeChanged){
                contactIdsToRecalculateBudgetsFor.add(contactAfterDML.Id);
            }
            
        }
        
        System.debug(contactIdsToRecalculateBudgetsFor);
        
        if (!contactIdsToRecalculateBudgetsFor.isEmpty()){
            System.enqueueJob(new RecordMergeBudgetHandler(contactIdsToRecalculateBudgetsFor, 'contact'));
        }
        
    }
    
    public static void cleanVilomahAccounts(List<Contact> contactsOld, String updateOrDelete, Map<Id, Contact> contactsAfterDML){
        
        //Collect Ids of isolated Account candidates (Trigger.Old)
        Set<Id> deleteAccountCandidates = new Set<Id>();
        for(Contact con : contactsOld){
            if( con.AccountId != null){ 
                if(updateOrDelete == 'Delete'){
                    deleteAccountCandidates.add(con.AccountId);
                } else if(updateOrDelete == 'Update' && con.AccountId != contactsAfterDML.get(con.Id).AccountId){
                    deleteAccountCandidates.add(con.AccountId);
                } 
            }
        }
        
        //Filter only Lead Account record type without Contacts
        Set<Id> deleteAccountIds = new Set<Id>();
        for(Account acct : [Select Id, (Select Id FROM Contacts LIMIT 1) FROM Account WHERE RecordType.DeveloperName = 'I_ST_Lead_Account' AND Id IN :deleteAccountCandidates]){
            if(acct.Contacts.size() == 0){
                deleteAccountIds.add(acct.Id);
            }
        }
        
        if(deleteAccountIds.isEmpty()){
            return;
        }
        
        List<Case> caseWithDeleteAccounts = new List<Case>([Select Id, AccountID FROM Case WHERE AccountId IN :deleteAccountIds]);
        Set<Id> deleteAccountIdsWithCase = new Set<Id>();
        for(Case c : caseWithDeleteAccounts){
            deleteAccountIdsWithCase.add(c.AccountID);
        }
        
        //Do not try and delete accounts with cases still attached
        deleteAccountIds.removeAll(deleteAccountIdsWithCase);
        
        List<AccountContactRelation> indirectRelations = new List<AccountContactRelation>([Select Id, AccountID FROM AccountContactRelation WHERE IsDirect = false AND AccountID IN :deleteAccountIds]);
        
        Database.DeleteResult[] drListACR = Database.delete(indirectRelations, false);        
                
        Database.DeleteResult[] drList = Database.delete(new List<Id>(deleteAccountIds), false);
    }

    //Added by JTan IBM on 27 Jan 2021 for IST-256 - starts
    // @Modified by Vanita - 02/03/2022 - As part of remediation commented CTE call
    /*public static void runContactTransitionEngine(List<Contact> triggerOld, List<Contact> triggerNew) {
        I_ST_CTE_ContactTransitionEngine cte = new I_ST_CTE_ContactTransitionEngine(triggerOld, triggerNew);
        cte.run();
    }*/ 
    
    //Added by Teja IBM on 30 August 2021 for LTU360-68 - starts
    /*** Setting CalculateContact Score to true**/
   /* public static void markCalculateContactScoreToTrue(List<Contact> newContacts,
                                                       map<Id,contact> oldContacts,
                                                       boolean isInsertContact){
                                                           boolean isFieldChanged = isInsertContact;
                                                           List<Contact> listUpdateContacts = new List<Contact>();
                                                           List<String> objectFields = fetchAllChangedField();
                                                           for(contact contactRecord: newContacts){
                                                               for(string contactField: objectFields){
                                                                   if(contactRecord.get(contactField) != oldContacts.get(contactRecord.id).get(contactField)){
                                                                       isFieldChanged = true;
                                                                       break;
                                                                   }
                                                               }
                                                               if(isFieldChanged){
                                                                   //system.debug('Is calling.');
                                                                   contact contactToUpdate = new contact(Id=contactRecord.Id,I_ST_Calculate_Contact_Score__c=true);
                                                                   listUpdateContacts.add(contactToUpdate);
                                                                   isFieldChanged = false;
                                                               }
                                                           }
                                                           Database.update(listUpdateContacts,false);
                                                           ContactTriggerHandler.runmarkCalculateContactScoreToTrue=true;
                                                       }
    
    //Method to get all contact field from custom metadataType
    public static List<string> fetchAllChangedField(){
        List<string> contactFields = new List<string>();
        //for(I_ST_Lead_Scoring__mdt leadScoreRecord : [SELECT I_ST_Field_API_Name__c FROM I_ST_Lead_Scoring__mdt WHERE I_ST_Object__c = 'Contact']){
        for(I_ST_Lead_Scoring__mdt leadScoreRecord : I_ST_Lead_Scoring__mdt.getAll().values()){
            if(leadScoreRecord.I_ST_Object__c == 'Contact') {
                string contactFieldName = '';
                if(leadScoreRecord.I_ST_Field_API_Name__c != ''){
                    contactFieldName = leadScoreRecord.I_ST_Field_API_Name__c;
                    contactFields.add(contactFieldName);
                }   
            }            
        }
        return contactFields;
    }*/
    
     //Added by Teja IBM on 21 January 2022 for LTU360-995 
    //Create ' Admin Account' whenever contact inserts.
    public static void createLeadOrganization(Map<Id,Contact> mapNewContact){        
        Map<Id,Account> mapContactVSAccount = new Map<Id,Account>();
        //List<Account> lstExistingAccount = new List<Account>();
        List<Account> lstNewLeadAccount = new List<Account>();
        Set<String> setContactName = new Set<String>();
       
        //Verify Account duplication if no duplicates create new account.
        for(Contact existingContact: mapNewContact.values()){
            if (existingContact.AccountId == null) {
                Account objOrganization = new Account();
                Database.DMLOptions dbDML = new Database.DMLOptions(); 
                dbDML.DuplicateRuleHeader.allowSave = true;
                dbDML.DuplicateRuleHeader.runAsCurrentUser = false;
                String contactName = existingContact.FirstName +' '+ existingContact.LastName;
           
                    objOrganization.Name = contactName;
                    objOrganization.RecordTypeId = AdminAccountRecordType;	
            		objOrganization.setOptions(dbDML);
                    mapContactVSAccount.put(existingContact.id,objOrganization);                
            }
               
        }
        //Create Account and link to contact.
        linkNewLeadAccountToContact(mapContactVSAccount);        
    }
    //Create Account and update contact.
    public static void linkNewLeadAccountToContact(Map<Id,Account> mapContactVSAccount){
        Map<String,Id> mapNewAccount = new Map<String,Id>();
        List<Account> lstnewLeadAccount = new List<Account>();
        List<Account> lstNewAccount = new List<Account>();
        List<Contact> lstUpdateContact = new List<Contact>();
        set<String> accountName = new set<String>();
        
        
        //Get Account Name
        for(Account newLeadAccount :mapContactVSAccount.values()){            
            lstnewLeadAccount.add(newLeadAccount);
            accountName.add(newLeadAccount.Name);
        }       
        //Insert Lead Account
        if(!lstnewLeadAccount.isEmpty()){
            // Adding this code to bypass Account Duplicate Rules
            Database.DMLOptions dbDML = new Database.DMLOptions(); 
            dbDML.DuplicateRuleHeader.allowSave = true;           
            List<Database.SaveResult> sr = Database.insert(lstnewLeadAccount, dbDML);
			
        }
        //Get account details
        for(Account objAccount : [SELECT Id,Name FROM Account WHERE Name =: accountName WITH SECURITY_ENFORCED]){
            mapNewAccount.put(objAccount.Name,objAccount.Id);
        }
        //Get latest contact details
        for(Contact objContact : [SELECT Id,FirstName,LastName,AccountId FROM Contact WHERE Id =:mapContactVSAccount.keySet()]){
            Contact objUpdateContact = objContact;
            String contactName = objContact.FirstName +' '+ objContact.LastName;
            //link account to contact
            objUpdateContact.AccountId = mapNewAccount.get(contactName);
            lstUpdateContact.add(objUpdateContact);
        }
        //update contact.
        if(!lstUpdateContact.isEmpty()){
            ContactTriggerHandler.runResearchPersonnelSharing = false;
            ContactTriggerHandler.runDirectManagerSharing = false;
            ContactTriggerHandler.runHierarchySharing = false;
            ContactTriggerHandler.runLeadAccountCleanup = false;
            hasFired();
            if(schema.SObjectType.contact.isUpdateable()){
                // Adding this code to bypass Contact Duplicate Rules
                Database.DMLOptions dbDML = new Database.DMLOptions(); 
            	dbDML.DuplicateRuleHeader.allowSave = true;
            	dbDML.DuplicateRuleHeader.runAsCurrentUser = false;
            	Database.SaveResult[] sr = Database.update(lstUpdateContact, dbDML);
            
            }
        } 
    }
    public static Id AdminAccountRecordType = [SELECT Id FROM recordType WHERE developername =: GlobalConstants.ACCOUNT_RECORD_TYPE_NAME_Admin_Account AND sObjectType = 'Account' LIMIT 1].id;
    private static Boolean hasFired = false;
    
    public static Boolean hasFired() {
        return hasFired;
    }
    
    public static void setFired() {
        hasFired = true;
    }
    
    public static void setNotFired() {
        hasFired = false;
    }
    //Added by JTan IBM on 27 Jan 2021 for IST-256 - ends



    //LTU360-1247 Set Affiliations to Inactive if Contact is Deceased
    //LTU360-2031 Populate contact name on affiliation if first name or last name changes 
    public static void setAffliationsToInactive(Map<Id,Contact> oldContactMap, List<Contact> contactList){		
        List<Id> updatedContactIds = new List<Id>();
        Map<Id,String> contactNameMap = new Map<Id,String>();
        for(Contact con : contactList){
            if(oldContactMap.get(con.Id).I_RS_Deceased__c != True && con.I_RS_Deceased__c == True){
                updatedContactIds.add(con.Id);
            }
            // filter out the contacts where name is changed           
            if(oldContactMap.get(con.Id).FirstName != con.FirstName || oldContactMap.get(con.Id).LastName != con.LastName){
                String name = con.FirstName + ' ' + con.LastName;
                contactNameMap.put(con.Id,name.trim());
            }
        }

        List<I_RM_Affiliation__c> affliationsToUpdate = New List<I_RM_Affiliation__c>();
        if(updatedContactIds.size() > 0){
        	for(Contact cont :[SELECT Id, Name, (SELECT Id, I_RM_Status__c, I_RM_EndDate__c from Affiliations__r WHERE I_RM_Status__c !='Inactive') 
        			FROM Contact WHERE Id IN : updatedContactIds WITH SECURITY_ENFORCED]){

            	for(I_RM_Affiliation__c affli : cont.Affiliations__r){
                	I_RM_Affiliation__c affliationRec = new I_RM_Affiliation__c();
                	affliationRec.I_RM_Status__c = 'Inactive';
                	affliationRec.I_RM_EndDate__c = System.today();
                	affliationRec.Id = affli.Id;
                	affliationsToUpdate.add(affliationRec);
            	}
        	}
        }
     // find all affiliations related to contact where name is changed and update those affiliations
        if(!contactNameMap.isEmpty()){
            //find all affiliations related to current contact
            for(I_RM_Affiliation__c relatedAff : [Select Id, L_PR_Contact_Name__c, I_RM_Contact__c from I_RM_Affiliation__c where I_RM_Contact__c in: contactNameMap.keyset()]){
               
                if(contactNameMap.get(relatedAff.I_RM_Contact__c) != Null && relatedAff.L_PR_Contact_Name__c!= contactNameMap.get(relatedAff.I_RM_Contact__c) ){
                    I_RM_Affiliation__c aff = new I_RM_Affiliation__c();
                	aff.Id = relatedAff.Id;
                    aff.L_PR_Contact_Name__c = contactNameMap.get(relatedAff.I_RM_Contact__c);
                	affliationsToUpdate.add(aff);
                }
            }            
        }
        if(!affliationsToUpdate.isEmpty()){
            update affliationsToUpdate;
        }

    }

    //LTU-360-1123
    public static void updateConfidentialfield(List<Contact> contactList){
        ContactTriggerHandler.firstRun = false;
        Set<Id> accountIds = New Set<Id>();
        for(Contact con : contactList){
            accountIds.add(con.AccountId);
        }
        Map<Id, Boolean> accountIdConfidentialValue = new Map<Id, Boolean>();
        for(Account acc : [Select Id, I_RS_Confidential__c From Account where Id IN : accountIds]){
            accountIdConfidentialValue.put(acc.Id, acc.I_RS_Confidential__c);
        }
        Boolean accountConfidential;
        for(Contact con : contactList){
            if(con.AccountId != null){
            accountConfidential = accountIdConfidentialValue.size() > 0 ? accountIdConfidentialValue.get(con.AccountId) : null;
            	if(accountConfidential !=null && accountConfidential != con.I_RS_Is_Organisation_Confidential__c){
                    con.I_RS_Is_Organisation_Confidential__c = accountConfidential;
            	}
            }
        }
    }

    /**
     * @description LTU360-2807 - Set the sponsored field based on 
     *                            Contact attributes in before insert/update context
     * @param newContactMap - map of new trigger items
     * @param oldContactMap - map of old trigger items
    */
    public static void updateSponsoredFieldOnAffiliations(
        Map<Id, Contact> oldContactMap,
        Map<Id, Contact> newContactMap
    ) {
        //set of Ids that need affiliations to be updated
        Set<Id> contactIdSet = new Set<Id>();

        for(Id conId : newContactMap.keySet()) {
            if( oldContactMap.isEmpty() || 
                ( newContactMap.get(conId).I_RS_Citizenship__c != oldContactMap.get(conId).I_RS_Citizenship__c )
            ) {
                contactIdSet.add(conId);
            }
        }

        if(!contactIdSet.isEmpty()) {

            List<I_RM_Affiliation__c> affList = new List<I_RM_Affiliation__c>(
                [SELECT Id, I_IL_Sponsored__c, I_IL_Intended_Funding_Source__c, I_RM_Contact__c 
                 FROM I_RM_Affiliation__c                   
                 WHERE I_RM_Contact__c IN :contactIdSet 
                 AND RecordTypeId = :GlobalConstants.AFFILIATION_RECORD_TYPE_ID_INT_LEAD 
                 AND I_RM_Active__c = :'True'
                ]
            );

            if(!affList.isEmpty()) {
                affList = I_RM_AffiliationTriggerHelper.setSponsoredFieldValue( 
                    affList,
                    new Map<Id, I_RM_Affiliation__c>()
                );
                Database.update(affList);
            }
        }
        
    }
}