force-app/main/default/objects/Account/fields/I_RS_End_Date__c.field-meta.xml
<CustomField>
    <fullName>I_RS_End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/I_RS_SAP_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>I_RS_SAP_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Ensure this number is 10 digits; include the leading zeroes</inlineHelpText>
    <label>Finance Customer Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/I_RS_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Start_Date__c</fullName>
    <inlineHelpText>This represents the first engagement with La Trobe.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/I_RS_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Proposed</fullName>
                <isActive>false</isActive>
                <label>Proposed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>La Trobe Division Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>College</fullName>
            </value>
            <value>
                <fullName>School</fullName>
            </value>
            <value>
                <fullName>Department</fullName>
            </value>
            <value>
                <fullName>Unit</fullName>
            </value>
            <value>
                <fullName>DVCR</fullName>
            </value>
            <value>
                <fullName>Research Centre/Institute</fullName>
            </value>
            <value>
                <fullName>Research Focus Area</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/I_RS_Related_User__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Related_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Refers to the user record associated to the contact</description>
    <label>Related User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ethics_Request__c/Ethics_Request__c.object-meta.xml
<CustomObject>
    <label>Ethics Request</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ethics Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ethics_Request__c/fields/I_RS_Ethics_Application_Number__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Ethics_Application_Number__c</fullName>
    <inlineHelpText>This number is populated by the Research Office.</inlineHelpText>
    <label>Ethics Application Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Ethics_Request__c/fields/I_RS_Ethics_Application_Review_Outcome__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Ethics_Application_Review_Outcome__c</fullName>
    <inlineHelpText>Committee’s decision. Populated by the Research Office.</inlineHelpText>
    <label>Ethics Application Review Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Applicable</fullName>
                <default>true</default>
                <label>Not Applicable</label>
            </value>
            <value>
                <fullName>Not Ready for Committee Review</fullName>
            </value>
            <value>
                <fullName>Subject to</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Outcome Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Closed-off</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Noted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ethics_Request__c/fields/I_RS_Ethics_Application_Title__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Ethics_Application_Title__c</fullName>
    <inlineHelpText>Write a title for your research  project.</inlineHelpText>
    <label>Ethics Application Title</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Ethics_Request__c/fields/I_RS_Meeting_Comments__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Meeting_Comments__c</fullName>
    <inlineHelpText>The list of actions that need to be addressed before the research is approved. Populated by the Research Office.</inlineHelpText>
    <label>Actions for researchers</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Ethics_Request__c/fields/I_RS_Meeting_Date__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Meeting_Date__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The date the ethics request will be reviewed by the Committee. Populated  by the Research Office.</inlineHelpText>
    <label>Meeting Date</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3) OR (4 AND 5 AND 6) OR (7 AND 8 AND 9)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Animal Ethics Application, SOP/Phenotype Report, Externally Approved Application</value>
        </filterItems>
        <filterItems>
            <field>Meeting_Date__c.Type__c</field>
            <operation>equals</operation>
            <value>Animal Ethics Application</value>
        </filterItems>
        <filterItems>
            <field>Meeting_Date__c.I_RS_Expired__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Human Ethics Application, Externally Approved Application</value>
        </filterItems>
        <filterItems>
            <field>Meeting_Date__c.Type__c</field>
            <operation>equals</operation>
            <value>Human Ethics Application</value>
        </filterItems>
        <filterItems>
            <field>Meeting_Date__c.I_RS_Expired__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Institutional Biosafety Committee, Externally Approved Application</value>
        </filterItems>
        <filterItems>
            <field>Meeting_Date__c.Type__c</field>
            <operation>equals</operation>
            <value>IBC Ethics Application</value>
        </filterItems>
        <filterItems>
            <field>Meeting_Date__c.I_RS_Expired__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Meeting_Date__c</referenceTo>
    <relationshipLabel>New Applications</relationshipLabel>
    <relationshipName>Ethics_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ethics_Request__c/fields/I_RS_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Status__c</fullName>
    <inlineHelpText>This is the status that corresponds with the ethics request status at the top of the page. If this status is ‘draft’ this means the researcher has an action to complete. Populated by the Research Office.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>I_RS_Ethics_Application_Review_Outcome__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Review by Research Office</fullName>
            </value>
            <value>
                <fullName>Assigned for Review</fullName>
            </value>
            <value>
                <fullName>Outcome Communicated</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Decided</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meeting_Date__c/Meeting_Date__c.object-meta.xml
<CustomObject>
    <description>Master list of all available meeting dates of Ethics Applicaitions</description>
    <label>Meeting Date</label>
    <nameField>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting_Date__c/fields/I_RS_Committee__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Committee__c</fullName>
    <label>Committee</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AEC</fullName>
            </value>
            <value>
                <fullName>AEC Executive</fullName>
            </value>
            <value>
                <fullName>IBC</fullName>
            </value>
            <value>
                <fullName>IBC Executive Incidents</fullName>
            </value>
            <value>
                <fullName>HREC A</fullName>
            </value>
            <value>
                <fullName>HREC B</fullName>
            </value>
            <value>
                <fullName>HREC Executive</fullName>
            </value>
            <value>
                <fullName>Low Risk</fullName>
            </value>
            <value>
                <fullName>Low Risk Executive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meeting_Date__c/fields/I_RS_Meeting_Closing_Date__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Meeting_Closing_Date__c</fullName>
    <label>Meeting Closing Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Meeting_Date__c/fields/I_RS_Meeting_Date__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Meeting_Date__c</fullName>
    <label>Meeting Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Meeting_Date__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Meeting Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Animal Ethics Application</fullName>
            </value>
            <value>
                <fullName>Human Ethics Application</fullName>
            </value>
            <value>
                <fullName>Biosafety Ethics Application</fullName>
                <label>IBC Ethics Application</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Research_Personnel__c/Research_Personnel__c.object-meta.xml
<CustomObject>
    <description>Formerly known as Ethics Request Member and Research Personnel</description>
    <label>Ethics Research Personnel</label>
    <nameField>
        <displayFormat>RP-{00000}</displayFormat>
        <label>Title</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ethics Research Personnel</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Research_Personnel__c/fields/I_RS_Contact_Researcher__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Contact_Researcher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related researcher</description>
    <label>Contact/Researcher</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Ethics_Request_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Research_Personnel__c/fields/I_RS_Ethics_Request__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Ethics_Request__c</fullName>
    <description>Related ethics request</description>
    <label>Ethics Request</label>
    <referenceTo>Ethics_Request__c</referenceTo>
    <relationshipLabel>Ethics Research Personnel</relationshipLabel>
    <relationshipName>Ethics_Request_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Research_Personnel__c/fields/I_RS_Role__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Principal Investigator</fullName>
            </value>
            <value>
                <fullName>Co-Investigator</fullName>
            </value>
            <value>
                <fullName>Co-ordinating Principal Investigator (Multiple Sites Only)</fullName>
            </value>
            <value>
                <fullName>Student Investigator</fullName>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
                <isActive>false</isActive>
                <label>Project Manager</label>
            </value>
            <value>
                <fullName>TBD</fullName>
                <isActive>false</isActive>
                <label>TBD</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Research_Personnel__c/fields/I_RS_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Start_Date__c</fullName>
    <label>Date Added</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ResearchPersonnelTest.cls
@isTest
public with sharing class ResearchPersonnelTest {
    @TestSetup
    static void setup() {
        AccountContactRelationHandler.runHierarchySharing = false;
        AccountContactRelationHandler.runPositionHistory = false;
        ContactTriggerHandler.runHierarchySharing = false;
	    ContactTriggerHandler.runProjectTeamMemberSharing = false;

        Profile researcherProfile = [SELECT Id FROM Profile WHERE Name='LTU Partner Community User'];

        //Create Account
        Map<integer, Account> accounts = new Map<integer, Account>();
        Account a = TestUtility.newEmptyLTUAccount(System.Label.Top_Org_Name_LaTrobe);
        a.I_RS_SAP_Customer_Number__c = '0000000000';
        insert a;
        a.IsPartner = True;
        update a;

        List<Contact> contactList = new List<Contact>();
        Contact researcher1 = new Contact(FirstName = 'sushant', LastName = 'verma', email = 'sushant@verma.test.com.au', AccountId = a.Id);
        Contact researcher2 = new Contact(FirstName = 'lachlan', LastName = 'burnside', email = 'lachlan@burnside.test.com.au', AccountId = a.Id);
        Contact researcher3 = new Contact(FirstName = 'anusha', LastName = 'cataram', email = 'anusha@cataram.test.com.au', AccountId = a.Id);
       /* insert researcher1;
        insert researcher2;
        insert researcher3;*/
        contactList.add(researcher1);
        contactList.add(researcher2);
        contactList.add(researcher3);
        insert contactList;

        User rUser1 = new User(Alias = 'Name1', Email='sushant@verma.test.com.au', 
                                  EmailEncodingKey='UTF-8', LastName='Researcher', LanguageLocaleKey='en_US', 
                                  LocaleSidKey='en_AU', ProfileId = researcherProfile.Id, ContactId = researcher1.Id,
                                  TimeZoneSidKey='Australia/Sydney', UserName='sushant@verma.test.com.au');
        insert rUser1;
        system.debug('User1 : ' + rUser1);
        
        User rUser2 = new User(Alias = 'Name2', Email='lachlan@burnside.test.com.au', 
                                  EmailEncodingKey='UTF-8', LastName='Researcher', LanguageLocaleKey='en_US', 
                                  LocaleSidKey='en_AU', ProfileId = researcherProfile.Id, ContactId = researcher2.Id,
                                  TimeZoneSidKey='Australia/Sydney', UserName='lachlan@burnside.test.com.au');
        insert rUser2;
        system.debug('User2 : ' + rUser2);
        
        researcher1.I_RS_Related_User__c = rUser1.Id;
        update researcher1;
        system.debug('researcher1 1: ' + researcher1);

        researcher2.I_RS_Related_User__c = rUser2.Id;
        update researcher2;
        system.debug('researcher1 2: ' + researcher1);

        Meeting_Date__c md = new Meeting_Date__c(Name = 'test meeting date', Type__c = 'Animal Ethics Application', 
                                                 I_RS_Committee__c = 'HREC A', I_RS_Meeting_Date__c = System.today(), I_RS_Meeting_Closing_Date__c = System.today() + 2);
        insert md;
        
        Ethics_Request__c er = new Ethics_Request__c(I_RS_Ethics_Application_Title__c = 'Test Ethics application title',
                                                    Name = 'TestName', I_RS_Ethics_Application_Number__c = '123456' , 
                                                     I_RS_Status__c = 'Draft', I_RS_Meeting_Date__c = md.Id,
                                                    I_RS_Meeting_Comments__c = 'Test', I_RS_Ethics_Application_Review_Outcome__c = 'Deferred');
        insert er;
        system.debug('Ethics Request: ' + er);
        
        System.debug('one!!!');
        
        Research_Personnel__c rp1 = new Research_Personnel__c (I_RS_Contact_Researcher__c = researcher1.id, I_RS_Role__c = 'Principal Investigator',
                                                              I_RS_Ethics_Request__c = er.id, I_RS_Start_Date__c = System.today() - 10);
        
        Research_Personnel__c rp2 = new Research_Personnel__c (I_RS_Contact_Researcher__c = researcher2.id, I_RS_Role__c = 'Co-Investigator',
                                                              I_RS_Ethics_Request__c = er.id, I_RS_Start_Date__c = System.today() - 10, I_RS_End_Date__c = System.today());
        Research_Personnel__c rp3 = new Research_Personnel__c (I_RS_Contact_Researcher__c = researcher3.id, I_RS_Role__c = 'Co-Investigator',
                                                              I_RS_Ethics_Request__c = er.id, I_RS_Start_Date__c = System.today() - 10);
        System.debug('two!!!');
        insert rp1;
        System.debug('three!!!');
        insert rp2;
        insert rp3;
    }
    
    @isTest
    public static void validateRP_Active_Inactive() {

        System.debug('four!!!');

        String rowCause = Schema.Ethics_Request__Share.rowCause.Ethics_Team_Member__c;
        
        Research_Personnel__c rp1 = [SELECT Id, Name, I_RS_Start_Date__c, I_RS_End_Date__c FROM Research_Personnel__c WHERE I_RS_Role__c = 'Principal Investigator' LIMIT 1];
        Research_Personnel__c rp2 = [SELECT Id, Name, I_RS_Start_Date__c, I_RS_End_Date__c FROM Research_Personnel__c WHERE I_RS_End_Date__c != null LIMIT 1];
    	List<Ethics_Request__share> erShares = [SELECT Id FROM Ethics_Request__share WHERE RowCause = :rowCause];
        System.assertEquals(1, erShares.size(), 'There should be one RP which is principle investigator');
        
        Test.startTest();

        rp1.I_RS_End_Date__c = System.today();
        rp2.I_RS_End_Date__c = null;
        System.debug('five!!!');
        update rp1;
        update rp2;
        System.debug('six!!!');
        
        Test.stopTest();
        
    	erShares = [SELECT Id FROM Ethics_Request__share WHERE RowCause = :rowCause];
        System.assertEquals(1, erShares.size(), 'There should be one RP which is Co-Investigator');
    }

    @isTest
    public static void validate_user_Inactive() {
        String rowCause = Schema.Ethics_Request__Share.rowCause.Ethics_Team_Member__c;
        Test.startTest();
        Contact c1 = [SELECT Id, I_RS_Related_User__c FROM Contact WHERE FirstName = 'sushant' LIMIT 1];
        c1.I_RS_Related_User__c = null;
        
        update c1;
        Test.stopTest();
    	List<Ethics_Request__share> erShares  = [SELECT Id FROM Ethics_Request__share WHERE RowCause = :rowCause];
        System.assertEquals(0, erShares.size(), 'There should be no RP which is principle investigator');
        
    }
    
    @isTest
    public static void validate_user_Active() {
        String rowCause = Schema.Ethics_Request__Share.rowCause.Ethics_Team_Member__c;
        
    	List<Ethics_Request__share> erShares  = [SELECT Id FROM Ethics_Request__share WHERE RowCause = :rowCause];
        System.assertEquals(1, erShares.size(), 'There should be no RP which is principle investigator');

        Test.startTest();
        Profile researcherProfile = [SELECT Id FROM Profile WHERE Name='LTU Partner Community User'];
        Contact researcher3 = [SELECT Id, I_RS_Related_User__c FROM Contact WHERE FirstName = 'anusha' LIMIT 1];
        User rUser3 = new User(Alias = 'Name3', Email='anusha@cataram.test.com.au', 
                                  EmailEncodingKey='UTF-8', LastName='Researcher', LanguageLocaleKey='en_US', 
                                  LocaleSidKey='en_AU', ProfileId = researcherProfile.Id, ContactId = researcher3.Id,
                                  TimeZoneSidKey='Australia/Sydney', UserName='anusha@cataram.test.com.au');
        insert rUser3;
        system.debug('User3 : ' + rUser3);
        
        Test.stopTest();
        
    	erShares  = [SELECT Id FROM Ethics_Request__share WHERE RowCause = :rowCause];
        system.debug('erShares : ' + erShares);
        System.assertEquals(2, erShares.size(), 'There should be no RP which is principle investigator');
        
    }

    @isTest
    public static void validate_Research_Personnel_Delete() {
        String rowCause = Schema.Ethics_Request__Share.rowCause.Ethics_Team_Member__c;
        Test.startTest();
        Research_Personnel__c rp1 = [SELECT Id, Name, I_RS_Start_Date__c, I_RS_End_Date__c FROM Research_Personnel__c WHERE I_RS_Role__c = 'Principal Investigator' LIMIT 1];
		delete rp1;
        Test.stopTest();
        
    	List<Ethics_Request__share> erShares  = [SELECT Id FROM Ethics_Request__share WHERE RowCause = :rowCause];
        system.debug('erShares : ' + erShares);
        System.assertEquals(0, erShares.size(), 'There should be no RP which is principle investigator');
    }
    
}