force-app/main/default/objects/Account/fields/L_PR_Closed_Reason__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Closed_Reason__c</fullName>
    <description>Reason for closed</description>
    <label>Closed Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_RS_Related_User__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Related_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Refers to the user record associated to the contact</description>
    <label>Related User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/I_RM_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Part of the remediation project to store different personas</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Role__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Role__c</fullName>
    <description>This represents the role of the affiliation</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Domestic Lead</fullName>
                <label>Student Lead (Dom)</label>
            </value>
            <value>
                <fullName>Applicant</fullName>
                <label>Student Applicant (Dom)</label>
            </value>
            <value>
                <fullName>La Trobe Staff</fullName>
            </value>
            <value>
                <fullName>School Representative</fullName>
                <label>Secondary School Representative</label>
            </value>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>External Contact</fullName>
            </value>
            <value>
                <fullName>HDR Student</fullName>
                <label>Graduate Researcher</label>
            </value>
            <value>
                <fullName>Student Lead (Int)</fullName>
            </value>
            <value>
                <fullName>Nominated Affiliation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <description>Indicates the status of the Affiliation.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>I_RM_Role__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>I_ST_Contact_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_IL_Student_Lead_Int.recordType-meta.xml
<RecordType>
    <fullName>I_IL_Student_Lead_Int</fullName>
    <active>true</active>
    <description>New International Lead who can be a prospective student of La Trobe University</description>
    <label>Student Lead (Int)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_Applicant.recordType-meta.xml
<RecordType>
    <fullName>I_RM_Applicant</fullName>
    <active>true</active>
    <description>An individual who has applied to study at La Trobe University</description>
    <label>Student Applicant (Dom)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_La_Trobe_Staff.recordType-meta.xml
<RecordType>
    <fullName>I_RM_La_Trobe_Staff</fullName>
    <active>true</active>
    <description>La Trobe staff member</description>
    <label>La Trobe Staff</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_Lead.recordType-meta.xml
<RecordType>
    <fullName>I_RM_Lead</fullName>
    <active>true</active>
    <description>New Domestic Lead who is a prospective student of La Trobe University</description>
    <label>Student Lead (Dom)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/I_RM_Affiliation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Affiliation Settings</label>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/L_PR_Idea__c/L_PR_Idea__c.object-meta.xml
<CustomObject>
    <description>Idea/ Lead object being used for PRM Application</description>
    <label>PRM Lead</label>
    <nameField>
        <label>Lead Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PRM Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/L_PR_Idea__c/fields/L_PR_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Affiliations</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>I_RM_Affiliation__c.I_RM_Role__c</field>
            <operation>equals</operation>
            <value>La Trobe Staff, Secondary School Representative, External Contact</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>PRM Ideas</relationshipLabel>
    <relationshipName>PRM_Ideas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/L_PR_Idea__c/fields/L_PR_Closed_Reason__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Closed_Reason__c</fullName>
    <description>Text field to describe why the Lead/Idea did not qualify/succeed</description>
    <label>Closed Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/L_PR_Idea__c/fields/L_PR_La_Trobe_Organisation_Unit__c.field-meta.xml
<CustomField>
    <fullName>L_PR_La_Trobe_Organisation_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>La Trobe Organisation Unit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>La Trobe Organisation Unit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PRM Leads (La Trobe Organisation Unit)</relationshipLabel>
    <relationshipName>PRM_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/L_PR_Idea__c/fields/L_PR_Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Lead_Status__c</fullName>
    <description>Indicates the progress of the Lead/Idea.</description>
    <label>Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Open – Contacted</fullName>
            </value>
            <value>
                <fullName>Open – Unqualified</fullName>
            </value>
            <value>
                <fullName>Open – Qualified</fullName>
            </value>
            <value>
                <fullName>Closed – Converted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/L_PR_Idea__c/fields/L_PR_Location__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Location__c</fullName>
    <description>Identifies Lead/Idea location</description>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/L_PR_Idea__c/fields/L_PR_Location_Country__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Location_Country__c</fullName>
    <description>Identifies Lead/Idea Country based on the Lead/Idea Location.</description>
    <label>Location Country</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>L_PR_Location__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>I_RM_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/L_PR_Idea__c/fields/L_PR_Organisation__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is a reference to related External Organisation or Educational Institution.</description>
    <label>Organisation Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>I_RS_External_Organisation</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>I_ST_Educational_Institution</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PRM Leads</relationshipLabel>
    <relationshipName>PRM_Ideas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/L_PR_Idea__c/fields/L_PR_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Sub_Type__c</fullName>
    <description>Sub Type field provides further  categorisation/ classification list based on the type for this Lead/Idea</description>
    <label>Lead Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>L_PR_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>L_PR_Sub_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/L_PR_Idea__c/fields/L_PR_Type__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Type__c</fullName>
    <description>Type field provides a categorisation/ classification  list for this Lead/Idea.</description>
    <label>Lead Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>L_PR_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/L_PR_Idea_Affiliation__c/L_PR_Idea_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Junction object to capture Lead/Idea and affiliation relationship records</description>
    <label>Lead Affiliation</label>
    <nameField>
        <displayFormat>IA-{000000}</displayFormat>
        <label>Lead Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/L_PR_Idea_Affiliation__c/fields/L_PR_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Affiliation__c</fullName>
    <label>Affiliation</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>I_RM_Affiliation__c.I_RM_Role__c</field>
            <operation>equals</operation>
            <value>La Trobe Staff, Secondary School Representative, External Contact</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>PRM Leads</relationshipLabel>
    <relationshipName>PRM_Leads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/L_PR_Idea_Affiliation__c/fields/L_PR_Idea__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Idea__c</fullName>
    <label>PRM Lead</label>
    <referenceTo>L_PR_Idea__c</referenceTo>
    <relationshipLabel>Affiliations</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/L_PR_Idea_Organisation__c/L_PR_Idea_Organisation__c.object-meta.xml
<CustomObject>
    <description>Junction object to capture relationship between Lead/Idea and Organisations</description>
    <label>Lead Organisation</label>
    <nameField>
        <displayFormat>IO-{000000}</displayFormat>
        <label>PRM Lead Organisation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Organisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/L_PR_Idea_Organisation__c/fields/L_PR_Idea__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Idea__c</fullName>
    <label>PRM Lead</label>
    <referenceTo>L_PR_Idea__c</referenceTo>
    <relationshipLabel>Lead Organisations</relationshipLabel>
    <relationshipName>Lead_Organisations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/L_PR_Idea_Organisation__c/fields/L_PR_IsPrimary__c.field-meta.xml
<CustomField>
    <fullName>L_PR_IsPrimary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsPrimary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/L_PR_Idea_Organisation__c/fields/L_PR_Organisation__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Organisation__c</fullName>
    <label>Organisation</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <errorMessage>You can only select External Organisation, Educational Institution or La Trobe Organisation Unit</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>La Trobe Organisation Unit</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>External Organisation</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Educational Institution</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Lead Organisations</relationshipLabel>
    <relationshipName>Idea_Organisations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/I_RM_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Åland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Argentinian Antarctic Territory</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Australian Antarctic Territory</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas (the)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia (Plurinational State of)</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/I_ST_Contact_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Admitted</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And LOA</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Not Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Considered</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Made</fullName>
    </customValue>
    <customValue>
        <fullName>Await Academic Advice</fullName>
    </customValue>
    <customValue>
        <fullName>Await Applicant Comms</fullName>
    </customValue>
    <customValue>
        <fullName>Await Further Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Awaiting Interview</fullName>
    </customValue>
    <customValue>
        <fullName>Await Required Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Escalated</fullName>
    </customValue>
    <customValue>
        <fullName>Make A Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make Alternate Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make An Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Nearing Completion</fullName>
    </customValue>
    <customValue>
        <fullName>Not Processed</fullName>
    </customValue>
    <customValue>
        <fullName>Not Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Lapsed</fullName>
    </customValue>
    <customValue>
        <fullName>Other Preference Offered</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Results</fullName>
    </customValue>
    <customValue>
        <fullName>Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <description>Global value set is created for lead(contact) object ST -51</description>
    <masterLabel>I_ST_Contact_Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/L_PR_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Education and Students</fullName>
    </customValue>
    <customValue>
        <fullName>Infrastructure &amp; Resources</fullName>
    </customValue>
    <customValue>
        <fullName>Innovation Ecosystem</fullName>
    </customValue>
    <customValue>
        <fullName>Research and Innovation</fullName>
    </customValue>
    <description>This picklist value set provides a categorisation/ classification  list for this Lead/Idea and opportunity.</description>
    <masterLabel>L_PR_Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/L_PR_LeadTriggerHelperTest.cls
/**
* @author  Vanita Walia
* @date    15/0/2022
* @description : This is a test class to cover leadTriggerHandler & LeadTriggerHelper methods
*/
@isTest
public class L_PR_LeadTriggerHelperTest {
	public static Id affiliationStaffRecordTypeId = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_La_Trobe_Staff').getRecordTypeId();
    
    @TestSetup
    static void setup() {

        String recTypeIdsForAffScoring = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Applicant').getRecordTypeId();
        recTypeIdsForAffScoring += ',' + Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Lead').getRecordTypeId();
        recTypeIdsForAffScoring += ',' + Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_IL_Student_Lead_Int').getRecordTypeId();
        TestUtility.createBatchScoringCustomSettings(recTypeIdsForAffScoring);
        
        //affiliation setting required for creating affiliations
        I_RM_Affiliation_Settings__c objAffiliationSettings = I_ST_UnitTestUtilities.createAffiliationSettings();
        insert objAffiliationSettings;
        
        //create External organisation
        Account tstAccount = TestUtility.newEmptyExternalAccount('test External Organisation');
        insert tstAccount;      
        
       Profile PrmProfile = [SELECT Id FROM Profile WHERE Name='PRM User'];
       
        //Create PRM User
        User prmUser;
        prmUser = new User(Alias = 'prmUser', Email='prmusertest@ltu.com.test', 
            EmailEncodingKey='UTF-8', FirstName='Test PRM', LastName='user', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_AU', ProfileId = PrmProfile.Id, TimeZoneSidKey='Australia/Sydney', UserName='prmusertest@ltu.com.test');
        insert prmUser;
		
        //Create Contacts and populate related User
        List<Contact> conList = new List<Contact>();
        for(integer i=0; i<=10; i++){
            Contact newContact = I_ST_UnitTestUtilities.createContactForScore('test_PRMFirstName'+i,
                                                                                  'test_PRMLastName'+i,
                                                                                  'test_PRM'+i+'@invalid.com',
                                                                                  'test_PRM'+i+'@invalid.com',                                                                                 
                                                                                  '3000');
            newContact.AccountId = tstAccount.Id;
            newContact.I_RS_Related_User__c = prmUser.Id;
            conList.add(newContact);
        }
        insert conList;
        
        //Create staff affiliations
        List<I_RM_Affiliation__c> lstAffiliations = new List<I_RM_Affiliation__c>();
        for(Integer j=0; j<conList.size(); j++) {
            for(I_RM_Affiliation__c aff : I_ST_UnitTestUtilities.createAffiliationRecords(affiliationStaffRecordTypeId,conList[j].Id)){
                aff.I_RM_Role__c = 'La Trobe Staff';
                aff.I_RM_Status__c ='';
                lstAffiliations.add(aff);
            }            
        }        
        insert lstAffiliations;        
    }
    
    /*  @author 		Vanita Walia
     * @date  			15/08/2022
     * @description 	this method will test PRM Lead creation with affiliation
     */
	@isTest
    public static void createPRMLeadwithAffiliation(){
        Test.startTest();
        //Search for staff affiliation
        List<I_RM_Affiliation__c> aff = [Select Id from I_RM_Affiliation__c where I_RM_Role__c = 'La Trobe Staff'];
        
        // Create PRM Lead
        L_PR_Idea__c prmLead = new L_PR_Idea__c(Name='Test PRM Lead', L_PR_Affiliation__c = aff[0].Id, L_PR_Type__c ='Research and Innovation',
                                               L_PR_Sub_Type__c ='Access to equipment', L_PR_Location__c='Domestic', L_PR_Location_Country__c ='Australia');
        insert prmLead;
        
        List<L_PR_Idea_Affiliation__c> leadAffList =[Select Id, L_PR_Idea__c,L_PR_Affiliation__c, L_PR_IsPrimary__c from L_PR_Idea_Affiliation__c where L_PR_Idea__c=:prmLead.Id AND L_PR_Affiliation__c =:aff[0].Id];
        
        system.assertEquals(leadAffList[0].L_PR_IsPrimary__c,True );
        
        // Updating the affiliation record on PRM Lead
        prmLead.L_PR_Affiliation__c = aff[1].Id;
        update prmLead;
        // again update the affiliation record to 1st one
        prmLead.L_PR_Affiliation__c = aff[0].Id;
        update prmLead;
        Test.stopTest();
    }
    
    /*  @author 		Vanita Walia
     * @date  			15/08/2022
     * @description 	this method will test PRM Lead creation with organisation 
     */
	@isTest
    public static void createPRMLeadwithOrganisation(){
        Test.startTest();
        // Search for External Org
        Account extOrg =[Select Id from Account where Name='test External Organisation'];
        
        //Search for staff affiliation
        List<I_RM_Affiliation__c> aff = [Select Id from I_RM_Affiliation__c where I_RM_Role__c = 'La Trobe Staff'];
        
        //Create La Trobe Organisation Units
        List<Account> ltuOrgs = new List<Account>();
        for(Integer i=0;i<5;i++){
            Account acc =TestUtility.newEmptyLTUAccount('LTU Test Account'+i);
            ltuOrgs.add(acc);
        }
        insert ltuOrgs;
        
        // Create PRM Lead
        L_PR_Idea__c prmLead = new L_PR_Idea__c(Name='Test PRM Lead', L_PR_Organisation__c = extOrg.Id, L_PR_Type__c ='Research and Innovation',
                                               L_PR_Sub_Type__c ='Access to equipment', L_PR_Location__c='Domestic', L_PR_Location_Country__c ='Australia',
                                               L_PR_La_Trobe_Organisation_Unit__c = ltuOrgs[0].Id, L_PR_Affiliation__c = aff[0].Id);
        insert prmLead;
        
        List<L_PR_Idea_Organisation__c> leadOrgList =[Select Id, L_PR_Idea__c,L_PR_Organisation__c, L_PR_IsPrimary__c from L_PR_Idea_Organisation__c
                                                                  where L_PR_Idea__c =: prmLead.Id AND L_PR_organisation__c =: extOrg.Id];
        system.Assert(leadOrgList.size()>0,'True');
            
        // Updating the affiliation record on PRM Lead
        prmLead.L_PR_La_Trobe_Organisation_Unit__c = ltuOrgs[1].Id;        
        update prmLead;
        // again update the affiliation record to 1st one
        prmLead.L_PR_La_Trobe_Organisation_Unit__c = ltuOrgs[0].Id;
        prmLead.L_PR_Lead_Status__c ='Closed';
        prmLead.L_PR_Closed_Reason__c ='test closed';
        update prmLead;
        Test.stopTest();
    }
}