force-app/main/default/objects/Account/fields/L_PR_Closed_Reason__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Closed_Reason__c</fullName>
    <description>Reason for closed</description>
    <label>Closed Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_RS_Related_User__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Related_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Refers to the user record associated to the contact</description>
    <label>Related User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/I_RM_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Part of the remediation project to store different personas</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Role__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Role__c</fullName>
    <description>This represents the role of the affiliation</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Domestic Lead</fullName>
                <label>Student Lead (Dom)</label>
            </value>
            <value>
                <fullName>Applicant</fullName>
                <label>Student Applicant (Dom)</label>
            </value>
            <value>
                <fullName>La Trobe Staff</fullName>
            </value>
            <value>
                <fullName>School Representative</fullName>
                <label>Secondary School Representative</label>
            </value>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>External Contact</fullName>
            </value>
            <value>
                <fullName>HDR Student</fullName>
                <label>Graduate Researcher</label>
            </value>
            <value>
                <fullName>Student Lead (Int)</fullName>
            </value>
            <value>
                <fullName>Nominated Affiliation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <description>Indicates the status of the Affiliation.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>I_RM_Role__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>I_ST_Contact_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_IL_Student_Lead_Int.recordType-meta.xml
<RecordType>
    <fullName>I_IL_Student_Lead_Int</fullName>
    <active>true</active>
    <description>New International Lead who can be a prospective student of La Trobe University</description>
    <label>Student Lead (Int)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_Applicant.recordType-meta.xml
<RecordType>
    <fullName>I_RM_Applicant</fullName>
    <active>true</active>
    <description>An individual who has applied to study at La Trobe University</description>
    <label>Student Applicant (Dom)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_La_Trobe_Staff.recordType-meta.xml
<RecordType>
    <fullName>I_RM_La_Trobe_Staff</fullName>
    <active>true</active>
    <description>La Trobe staff member</description>
    <label>La Trobe Staff</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_Lead.recordType-meta.xml
<RecordType>
    <fullName>I_RM_Lead</fullName>
    <active>true</active>
    <description>New Domestic Lead who is a prospective student of La Trobe University</description>
    <label>Student Lead (Dom)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/I_RM_Affiliation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Affiliation Settings</label>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/L_PR_External_Org_Opportunity_Relation__c/L_PR_External_Org_Opportunity_Relation__c.object-meta.xml
<CustomObject>
    <label>Organisation Opportunity Relationship</label>
    <nameField>
        <displayFormat>OOR-{000000}</displayFormat>
        <label>Organisation Opportunity Relationship</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organisation Opportunity Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/L_PR_External_Org_Opportunity_Relation__c/fields/L_PR_Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Opportunity_Name__c</fullName>
    <label>Opportunity Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PRM_Opportunity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Organisation Opportunity Relationships</relationshipLabel>
    <relationshipName>External_Org_Opportunity_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/L_PR_External_Org_Opportunity_Relation__c/fields/L_PR_Organisation_Name__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Organisation_Name__c</fullName>
    <label>Organisation Name</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>I_ST_Educational_Institution</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>I_RS_External_Organisation</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>I_RS_La_Trobe_Organisation_Unit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Organisation Opportunity Relationships</relationshipLabel>
    <relationshipName>External_Org_Opportunity_Relationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/L_PR_Idea__c/L_PR_Idea__c.object-meta.xml
<CustomObject>
    <description>Idea/ Lead object being used for PRM Application</description>
    <label>PRM Lead</label>
    <nameField>
        <label>Lead Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PRM Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/L_PR_Idea__c/fields/L_PR_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Affiliations</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>I_RM_Affiliation__c.I_RM_Role__c</field>
            <operation>equals</operation>
            <value>La Trobe Staff, Secondary School Representative, External Contact</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>PRM Ideas</relationshipLabel>
    <relationshipName>PRM_Ideas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/L_PR_Idea__c/fields/L_PR_Closed_Reason__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Closed_Reason__c</fullName>
    <description>Text field to describe why the Lead/Idea did not qualify/succeed</description>
    <label>Closed Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/L_PR_Idea__c/fields/L_PR_La_Trobe_Organisation_Unit__c.field-meta.xml
<CustomField>
    <fullName>L_PR_La_Trobe_Organisation_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>La Trobe Organisation Unit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>La Trobe Organisation Unit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PRM Leads (La Trobe Organisation Unit)</relationshipLabel>
    <relationshipName>PRM_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/L_PR_Idea__c/fields/L_PR_Location__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Location__c</fullName>
    <description>Identifies Lead/Idea location</description>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/L_PR_Idea__c/fields/L_PR_Location_Country__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Location_Country__c</fullName>
    <description>Identifies Lead/Idea Country based on the Lead/Idea Location.</description>
    <label>Location Country</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>L_PR_Location__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>I_RM_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/L_PR_Idea__c/fields/L_PR_Organisation__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is a reference to related External Organisation or Educational Institution.</description>
    <label>Organisation Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>I_RS_External_Organisation</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>I_ST_Educational_Institution</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PRM Leads</relationshipLabel>
    <relationshipName>PRM_Ideas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/L_PR_Idea__c/fields/L_PR_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Sub_Type__c</fullName>
    <description>Sub Type field provides further  categorisation/ classification list based on the type for this Lead/Idea</description>
    <label>Lead Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>L_PR_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>L_PR_Sub_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/L_PR_Idea__c/fields/L_PR_Type__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Type__c</fullName>
    <description>Type field provides a categorisation/ classification  list for this Lead/Idea.</description>
    <label>Lead Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>L_PR_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/L_PR_Closed_Reason__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Closed_Reason__c</fullName>
    <description>Reason for closed lost opportunity</description>
    <label>Closed Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/L_PR_Idea__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Idea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to the related Lead</description>
    <label>Lead Title</label>
    <referenceTo>L_PR_Idea__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/L_PR_La_Trobe_Org_Unit__c.field-meta.xml
<CustomField>
    <fullName>L_PR_La_Trobe_Org_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>La Trobe Organisation Unit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>I_RS_La_Trobe_Organisation_Unit</value>
        </filterItems>
        <filterItems>
            <field>Account.I_RS_Status__c</field>
            <operation>notEqual</operation>
            <value>Closed</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/L_PR_Location__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Location__c</fullName>
    <description>Identies the location associated with opportunity</description>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/L_PR_Location_Country__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Location_Country__c</fullName>
    <description>Identifies the country associated with location</description>
    <label>Location Country</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>L_PR_Location__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>I_RM_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/L_PR_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Sub_Type__c</fullName>
    <description>Provides a way of  further classifying/categorising this opportunity</description>
    <label>Opportunity Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>L_PR_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>L_PR_Sub_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/L_PR_Type__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Type__c</fullName>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>L_PR_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/I_RM_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Åland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Argentinian Antarctic Territory</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Australian Antarctic Territory</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas (the)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia (Plurinational State of)</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/I_ST_Contact_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Admitted</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And LOA</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Not Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Considered</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Made</fullName>
    </customValue>
    <customValue>
        <fullName>Await Academic Advice</fullName>
    </customValue>
    <customValue>
        <fullName>Await Applicant Comms</fullName>
    </customValue>
    <customValue>
        <fullName>Await Further Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Awaiting Interview</fullName>
    </customValue>
    <customValue>
        <fullName>Await Required Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Escalated</fullName>
    </customValue>
    <customValue>
        <fullName>Make A Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make Alternate Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make An Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Nearing Completion</fullName>
    </customValue>
    <customValue>
        <fullName>Not Processed</fullName>
    </customValue>
    <customValue>
        <fullName>Not Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Lapsed</fullName>
    </customValue>
    <customValue>
        <fullName>Other Preference Offered</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Results</fullName>
    </customValue>
    <customValue>
        <fullName>Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <description>Global value set is created for lead(contact) object ST -51</description>
    <masterLabel>I_ST_Contact_Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/L_PR_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Education and Students</fullName>
    </customValue>
    <customValue>
        <fullName>Infrastructure &amp; Resources</fullName>
    </customValue>
    <customValue>
        <fullName>Innovation Ecosystem</fullName>
    </customValue>
    <customValue>
        <fullName>Research and Innovation</fullName>
    </customValue>
    <description>This picklist value set provides a categorisation/ classification  list for this Lead/Idea and opportunity.</description>
    <masterLabel>L_PR_Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/L_PR_OpportunityTriggerHandlerTest.cls
/**
* @author  Vanita Walia
* @date    15/09/2022
* @description : This is a test class to cover OpportunityTriggerHandler & OpportunityTriggerHelper methods
*/
@isTest
public class L_PR_OpportunityTriggerHandlerTest {
    public static Id affiliationStaffRecordTypeId = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_La_Trobe_Staff').getRecordTypeId();
    
     @TestSetup
    static void setup(){

        String recTypeIdsForAffScoring = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Applicant').getRecordTypeId();
        recTypeIdsForAffScoring += ',' + Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Lead').getRecordTypeId();
        recTypeIdsForAffScoring += ',' + Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_IL_Student_Lead_Int').getRecordTypeId();
        TestUtility.createBatchScoringCustomSettings(recTypeIdsForAffScoring);
        
         //affiliation setting required for creating affiliations
        I_RM_Affiliation_Settings__c objAffiliationSettings = I_ST_UnitTestUtilities.createAffiliationSettings();
        insert objAffiliationSettings;        
		
        //create External organisation
        Account tstAccount = TestUtility.newEmptyExternalAccount('test External Organisation');
        insert tstAccount;
        
        Profile PrmProfile = [SELECT Id FROM Profile WHERE Name='PRM User'];
       
        //Create PRM User
        User prmUser;
        prmUser = new User(Alias = 'prmUser', Email='prmusertest@ltu.com.test', 
            		EmailEncodingKey='UTF-8', FirstName='Test PRM', LastName='user', LanguageLocaleKey='en_US', 
            		LocaleSidKey='en_AU', ProfileId = PrmProfile.Id, TimeZoneSidKey='Australia/Sydney', UserName='prmusertest@ltu.com.test');
        insert prmUser;
		
        //Create Contacts and populate related User
        List<Contact> conList = new List<Contact>();
        for(integer i=0; i<=10; i++){
            Contact newContact = I_ST_UnitTestUtilities.createContactForScore('test_PRMFirstName'+i,
                                                                                  'test_PRMLastName'+i,
                                                                                  'test_PRM'+i+'@invalid.com',
                                                                                  'test_PRM'+i+'@invalid.com',                                                                                 
                                                                                  '3000');
            newContact.AccountId = tstAccount.Id;
            newContact.I_RS_Related_User__c = prmUser.Id;
            conList.add(newContact);
        }
        insert conList;
        
        //Create staff affiliations
        List<I_RM_Affiliation__c> lstAffiliations = new List<I_RM_Affiliation__c>();
        for(Integer j=0; j<conList.size(); j++) {
            for(I_RM_Affiliation__c aff : I_ST_UnitTestUtilities.createAffiliationRecords(affiliationStaffRecordTypeId,conList[j].Id)){
                aff.I_RM_Role__c = 'La Trobe Staff';
                aff.I_RM_Status__c ='';
                lstAffiliations.add(aff);
            }            
        }        
        insert lstAffiliations;     
        
        //Create La Trobe Organisation Unit       
        Account ltuOrg =TestUtility.newEmptyLTUAccount('LTU Test Account');           
        insert ltuOrg;
        
    	// Create PRM Lead
        L_PR_Idea__c prmLead = new L_PR_Idea__c(Name='Test PRM Lead', L_PR_Affiliation__c = lstAffiliations[0].Id, L_PR_Type__c ='Research and Innovation',
                                               L_PR_Sub_Type__c ='Access to equipment', L_PR_Location__c='Domestic', L_PR_Location_Country__c ='Australia',
                                               L_PR_Organisation__c = tstAccount.Id,L_PR_La_Trobe_Organisation_Unit__c = ltuOrg.Id);
        insert prmLead;
        
		//create opportunity
        Opportunity testOpp = new Opportunity();
        testOpp.AccountId = tstAccount.Id;
        testOpp.L_PR_La_Trobe_Org_Unit__c = ltuOrg.Id;
        testOpp.L_PR_Idea__c = prmLead.Id;
        testOpp.L_PR_Type__c = 'Education and Students';
        testOpp.L_PR_Sub_Type__c = 'Third Party Teaching';
        testOpp.L_PR_Location__c = 'Domestic';
        testOpp.L_PR_Location_Country__c = 'Australia';
        testOpp.CloseDate = System.today() +30;
        testOpp.StageName = 'Prospecting';
        testOpp.Name ='TestOpp1';
        Insert testOpp;
        
      /* L_PR_External_Org_Opportunity_Relation__c extOrg = new L_PR_External_Org_Opportunity_Relation__c();
        extOrg.L_PR_Opportunity_Name__c = testOpp.Id;
        extOrg.L_PR_Organisation_Name__c = tstAccount.Id;
        insert extOrg;*/
        
    }

    @isTest
    public static void testupdateExtOrgOpptStageField(){

        Test.startTest();

        List<Opportunity> oppList = [Select Id,AccountId, StageName from Opportunity Limit 1];

        oppList[0].StageName = 'Development';
        update oppList[0];

        List<Opportunity> updatedOppList = [Select Id,AccountId, StageName from Opportunity Limit 1];

        system.assertEquals('Development', updatedOppList[0].StageName);
    }

     /*  @author 		Vanita Walia
     * @date  			15/09/2022
     * @description 	this method will test updating organisation details on opportunity & opportunity closed Notification 
     */
	@isTest
    public static void testOppClosedNotification(){

        Test.startTest();

        Opportunity testOpp = [Select Id,AccountId, StageName from Opportunity where Name='TestOpp1'];

        testOpp.StageName = 'Closed Lost';
        testOpp.L_PR_Closed_Reason__c = 'Closed Opportunity';
        update testOpp;
        
        Opportunity updatedOpp = [Select Id,AccountId, StageName from Opportunity where Name='TestOpp1'];
        system.assertEquals('Closed Lost', updatedOpp.StageName);        
        Test.stopTest();

    }
    /*  @author 		Vanita Walia
     * @date  			15/09/2022
     * @description 	this method will test updating organisation details on opportunity 
     */
	@isTest
    public static void testOppupdateExternalOrgs(){

        Test.startTest();
        //create External organisation
        Account tstAccount = TestUtility.newEmptyExternalAccount('test org');
        insert tstAccount;
        
        //Create La Trobe Organisation Unit       
        Account ltuOrg =TestUtility.newEmptyLTUAccount('LaTrobeOrg');           
        insert ltuOrg;
        
	// update opportunity with new organisations
        Opportunity testOpp = [Select Id,AccountId, StageName from Opportunity where Name='TestOpp1'];
        testOpp.AccountId = tstAccount.Id;
        testOpp.L_PR_La_Trobe_Org_Unit__c = ltuOrg.Id;
        update testOpp;
        List<L_PR_External_Org_Opportunity_Relation__c> extOrg = new List<L_PR_External_Org_Opportunity_Relation__c>();
        extOrg =[Select Id,L_PR_Opportunity_Name__c,L_PR_Organisation_Name__c, L_PR_IsPrimary__c
                                                           from L_PR_External_Org_Opportunity_Relation__c where L_PR_Opportunity_Name__c =: testOpp.Id and 
                                                          L_PR_Organisation_Name__c =:tstAccount.Id limit 1];
        
           //system.assertEquals(extOrg[0].L_PR_IsPrimary__c, True);       
        //Remove account details from opportunity
        testOpp.L_PR_La_Trobe_Org_Unit__c = Null;
        update testOpp;
        List<L_PR_External_Org_Opportunity_Relation__c> internalOrg =[Select Id,L_PR_Opportunity_Name__c,L_PR_Organisation_Name__c, L_PR_IsPrimary__c
                                                           from L_PR_External_Org_Opportunity_Relation__c where L_PR_Opportunity_Name__c =: testOpp.Id and 
                                                          L_PR_Organisation_Name__c =:ltuOrg.Id];
        
           //system.assertEquals(internalOrg.size(), 1);       
        
        Test.stopTest();

    }
    
     /*  @author 		Vanita Walia
     * @date  			29/09/2022
     * @description 	this method will test exception handling
     */
	@isTest
    public static void testupdateLeadStatusClosedConverted_Exception(){

        Test.startTest();
       Map<Id,Id> testMap = new Map<Id,Id>();
        testMap.put('a3T5P0000008qzFUAQ','a3T5P0000008qzFUAQ');
        try{
        	L_PR_OpportunityTriggerHelper.updateLeadStatusClosedConverted(testMap);            
        }catch(exception e){
             System.debug ('Exception'+e);
        }
        
        Test.stopTest();
    }  
    
    /*  @author 		Vanita Walia
     * @date  			29/09/2022
     * @description 	this method will test exception handling
     */
	@isTest
    public static void testcreateCustomSFNotification_Exception(){

        Test.startTest();
        Opportunity testOpp = [Select Id,AccountId, StageName from Opportunity where Name='TestOpp1'];
       Map<Id, Set<String>> oppStaffMap = new Map<Id, Set<String>>();
        Set<String> staffIds = new  Set<String>();
        staffIds.add('test');
        oppStaffMap.put(testOpp.Id,staffIds);
        try{
        	L_PR_OpportunityTriggerHelper.createCustomSFNotification(oppStaffMap);            
        }catch(exception e){
             System.debug ('Exception'+e);
        }
        
        Test.stopTest();
    }  
}