force-app/main/default/objects/I_RM_Affiliation__c/I_RM_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Part of the remediation project to store different personas</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Score__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Score__c</fullName>
    <description>This Fields shows the calculated score of an affiliation based on key attributes being populated</description>
    <label>Affiliation Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_Lead.recordType-meta.xml
<RecordType>
    <fullName>I_RM_Lead</fullName>
    <active>true</active>
    <description>New Domestic Lead who is a prospective student of La Trobe University</description>
    <label>Student Lead (Dom)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/I_RM_Affiliation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Affiliation Settings</label>
</CustomObject>

force-app/main/default/objects/I_ST_BatchScoring__c/I_ST_BatchScoring__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>I_ST_BatchScoring</label>
</CustomObject>

force-app/main/default/objects/I_ST_BatchScoring__c/fields/I_ST_BatchSize__c.field-meta.xml
<CustomField>
    <fullName>I_ST_BatchSize__c</fullName>
    <description>This is the batch size to control the Lead/Activity scoring jobs for IST</description>
    <label>I_ST_BatchSize</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/I_ST_BatchScoring__c/fields/I_ST_Last_N_Hour__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Last_N_Hour__c</fullName>
    <description>Used for Activity Scoring batch to run batch and pick records modified &apos;N&apos; hours before current time</description>
    <label>I_ST_Last_N_Hour</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/I_ST_BatchScoring__c/fields/I_ST_RecordType_SFIDs__c.field-meta.xml
<CustomField>
    <fullName>I_ST_RecordType_SFIDs__c</fullName>
    <description>Provide comma separated RecordTypeIds of Case object which is to be considered for Activity Scoring. To get the record type Ids =&gt; Navigate to Setup -&gt; Object Manager -&gt; Case -&gt; RecordTypes -&gt; Select the record type -&gt; copy the 18 digit Id from the URL</description>
    <label>I_ST_RecordType_SFIDs</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/I_RM_AffiliationScoring_Batch_Test.cls
/* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* I_ST_AffiliationScoring_Batch2Test
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Teja Yenduri   <tyenduri@au1.ibm.com>
* @version        1.0
* @created        2022-02-18
  @JIRA           LTU360-867
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* @changes
* v1.0           Teja Yenduri
* 2022-02-18      Created
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/
@isTest
public class I_RM_AffiliationScoring_Batch_Test {
    
    //If test class fails for the SOQL 101 governining limit OR Apex CPU Limit Exceeded, please reduce this contactBatchFrequency and run test again
    //This contactBatchFrequency tells how may contact records can be updated in 1 transaction
    private static Integer contactsToCreateUpdate = 20;
    @TestSetup
    static void setup(){        
        String affiliationRecordTypIds = I_ST_UnitTestUtilities.recordTypeIds(GlobalConstants.AFFILIATION_OBJECT_API_NAME,GlobalConstants.AFFILIATION_RECORD_TYPE_NAME_LEAD);
        String caseRecordTypeIds = I_ST_UnitTestUtilities.recordTypeIds(GlobalConstants.CASE_OBJECT_API_NAME,GlobalConstants.CASE_RECORD_TYPE_API_NAME_ENQUIRY);  
        String interactionRecordTypeIds = I_ST_UnitTestUtilities.recordTypeIds(GlobalConstants.INTERACTION_OBJECT_API_NAME,GlobalConstants.INTERACTION_RECORD_TYPE_API_NAME_LEAD_INTERACTION);
        
        List<I_ST_BatchScoring__c> listBatchScoringSetting = I_ST_UnitTestUtilities.createBatchScoringCustomSetting(affiliationRecordTypIds,20,caseRecordTypeIds,20,interactionRecordTypeIds,20);           
        insert listBatchScoringSetting;
        
        I_RM_Affiliation_Settings__c objAffiliationSettings = I_ST_UnitTestUtilities.createAffiliationSettings();
        insert objAffiliationSettings;
        
        List<Contact> contactsToInsert = new List<contact>();
        //Id domesticLeadRecordTypeId =  listBatchScoringSetting[0].I_ST_RecordType_SFIDs__c.split(',')[0];
         //Id contactDomesticLeadRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('I_ST_Domestic_Lead').getRecordTypeId();
         Id affiliationDomesticLeadRecordTypeId = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Lead').getRecordTypeId();
        
        for(integer i = 0; i < contactsToCreateUpdate; i++){
            Contact newDomesticLead = I_ST_UnitTestUtilities.createContactForScore('test_unique'+i,
                                                                          'unique_test'+i, 
                                                                          'test_unique'+i+'@unique.com',
                                                                          'test_unique'+i+'@unique.com',                                                                         
                                                                          '3029');
                                                                          
            contactsToInsert.add(newDomesticLead);
        }
        insert contactsToInsert;
        
        List<I_RM_Affiliation__c> testAffiliation = I_ST_UnitTestUtilities.createAffiliationRecords(affiliationDomesticLeadRecordTypeId,contactsToInsert[0].Id);
        insert testAffiliation;
         system.debug('testAffiliation'+testAffiliation);
    }
    
    //IST - Test method to test the execution of batch class - I_ST_AffiliationScoring_Batch - Positive Test
    @isTest
    public static void testCalculateAffiliationScoreBatch(){
        
        List<I_RM_Affiliation__c> contactAfterInsert = new List<I_RM_Affiliation__c>();
        contactAfterInsert = [SELECT Id,I_RM_Score__c 
                              FROM  I_RM_Affiliation__c
                             ];       
        
        System.assertEquals(0,contactAfterInsert[0].I_RM_Score__c);
        
        I_ST_BatchScoring__c batchScoringSettingAffiliation = I_ST_BatchScoring__c.getValues(GlobalConstants.I_RM_AFFILIATIONSCORING);
        Integer lastNHours = (Integer)batchScoringSettingAffiliation.I_ST_Last_N_Hour__c;
        Integer batchSize = (Integer)batchScoringSettingAffiliation.I_ST_BatchSize__c;
        Set<Id> newrecordTypeIds = GlobalUtility.convertCommaSeparatedStringsToSetIds(batchScoringSettingAffiliation.I_ST_RecordType_SFIDs__c);
        
        Test.startTest();           
            I_RM_AffiliationScoring_Batch leadScoringBatch = new I_RM_AffiliationScoring_Batch(GlobalConstants.AFFILIATION_OBJECT_API_NAME,newrecordTypeIds,lastNHours);
            Database.executeBatch(leadScoringBatch,batchSize);
        Test.stopTest();
        
        List<I_RM_Affiliation__c> affiliationAfterBatchUpdate = new List<I_RM_Affiliation__c>();
        affiliationAfterBatchUpdate = [SELECT Id,I_RM_Score__c
                                   FROM I_RM_Affiliation__c 
                                   ];
        //Assert on Score calculated based on metadata mapping in Lead Scoring metadata. Hence asserting increment in score NOT actual score calculated as it keeps on changing
        system.assert(Integer.valueOf(affiliationAfterBatchUpdate[0].I_RM_Score__c)>0);  
    }
    
    //IST - Test method to test the scheduler - I_ST_AffiliationScoring_Batch_Scheduler2 
    @isTest
    public static void testCalculateAffiliationScoreScheduler2(){
        
        I_ST_BatchScoring__c batchScoringSettingAffiliation = I_ST_BatchScoring__c.getValues(GlobalConstants.I_RM_AFFILIATIONSCORING);
        Integer lastNHours = (Integer)batchScoringSettingAffiliation.I_ST_Last_N_Hour__c;
        Set<Id> newrecordTypeIds = GlobalUtility.convertCommaSeparatedStringsToSetIds(batchScoringSettingAffiliation.I_ST_RecordType_SFIDs__c);
        
        String jobId = '';
        Test.startTest();           
            jobId  = I_RM_AffiliationScoring_Batch_Scheduler.scheduleActivityScoring();
        Test.stopTest();
      
        System.assert(String.isNotBlank(jobId));
    }
    
}