force-app/main/default/objects/I_RM_Affiliation__c/I_RM_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Part of the remediation project to store different personas</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Contact__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Contact__c</fullName>
    <description>The person/contact who this Affiliation relates to</description>
    <inlineHelpText>The person this affiliation relates to</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Affiliations</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Role__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Role__c</fullName>
    <description>This represents the role of the affiliation</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Domestic Lead</fullName>
                <label>Student Lead (Dom)</label>
            </value>
            <value>
                <fullName>Applicant</fullName>
                <label>Student Applicant (Dom)</label>
            </value>
            <value>
                <fullName>La Trobe Staff</fullName>
            </value>
            <value>
                <fullName>School Representative</fullName>
                <label>Secondary School Representative</label>
            </value>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>External Contact</fullName>
            </value>
            <value>
                <fullName>HDR Student</fullName>
                <label>Graduate Researcher</label>
            </value>
            <value>
                <fullName>Student Lead (Int)</fullName>
            </value>
            <value>
                <fullName>Nominated Affiliation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/L_PR_Idea__c/L_PR_Idea__c.object-meta.xml
<CustomObject>
    <description>Idea/ Lead object being used for PRM Application</description>
    <label>PRM Lead</label>
    <nameField>
        <label>Lead Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PRM Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/L_PR_Idea__c/fields/L_PR_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Affiliations</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>I_RM_Affiliation__c.I_RM_Role__c</field>
            <operation>equals</operation>
            <value>La Trobe Staff, Secondary School Representative, External Contact</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>PRM Ideas</relationshipLabel>
    <relationshipName>PRM_Ideas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/L_PR_Idea__c/fields/L_PR_Closed_Reason__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Closed_Reason__c</fullName>
    <description>Text field to describe why the Lead/Idea did not qualify/succeed</description>
    <label>Closed Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/L_PR_Idea__c/fields/L_PR_La_Trobe_Organisation_Unit__c.field-meta.xml
<CustomField>
    <fullName>L_PR_La_Trobe_Organisation_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>La Trobe Organisation Unit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>La Trobe Organisation Unit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PRM Leads (La Trobe Organisation Unit)</relationshipLabel>
    <relationshipName>PRM_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/L_PR_Idea__c/fields/L_PR_Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Lead_Status__c</fullName>
    <description>Indicates the progress of the Lead/Idea.</description>
    <label>Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Open – Contacted</fullName>
            </value>
            <value>
                <fullName>Open – Unqualified</fullName>
            </value>
            <value>
                <fullName>Open – Qualified</fullName>
            </value>
            <value>
                <fullName>Closed – Converted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/L_PR_Idea__c/fields/L_PR_Organisation__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is a reference to related External Organisation or Educational Institution.</description>
    <label>Organisation Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>I_RS_External_Organisation</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>I_ST_Educational_Institution</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PRM Leads</relationshipLabel>
    <relationshipName>PRM_Ideas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/L_PR_Idea_Affiliation__c/L_PR_Idea_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Junction object to capture Lead/Idea and affiliation relationship records</description>
    <label>Lead Affiliation</label>
    <nameField>
        <displayFormat>IA-{000000}</displayFormat>
        <label>Lead Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/L_PR_Idea_Affiliation__c/fields/L_PR_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Affiliation__c</fullName>
    <label>Affiliation</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>I_RM_Affiliation__c.I_RM_Role__c</field>
            <operation>equals</operation>
            <value>La Trobe Staff, Secondary School Representative, External Contact</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>PRM Leads</relationshipLabel>
    <relationshipName>PRM_Leads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/L_PR_Idea_Affiliation__c/fields/L_PR_Idea__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Idea__c</fullName>
    <label>PRM Lead</label>
    <referenceTo>L_PR_Idea__c</referenceTo>
    <relationshipLabel>Affiliations</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/L_PR_LeadTriggerHandler.cls
/**
* @author  Vanita Walia
* @date    12/07/2022
* @description : This class is used for filtering the PRM leads and calling helper methods
*/

public class L_PR_LeadTriggerHandler {
	public static void execute() {        
        
        try{       
        	if(Trigger.isAfter) {
            	if(Trigger.isInsert || Trigger.isUpdate) {
                	//variable declaration
                 	map<Id,L_PR_Idea__c> mapOldLead = (map<Id,L_PR_Idea__c>)Trigger.oldMap;
        			Map<Id,Id> lAffMap = new Map<Id,Id>();
        			Map<Id,Id> removelAffMap = new Map<Id,Id>();
                    set<Id> leadIdSet = new Set<Id>();
                    Set<String> staffIds = new Set<String>();
                    Map<Id, Set<String>> leadStaffMap = new Map<Id, Set<String>>();
                    Map<Id,String> leadStatusMap = new Map<Id,String>();
                    Map<Id,Id> leadOrgMap = new Map<Id,Id>();
        			Map<Id,Id> removeLeadOrgMap = new Map<Id,Id>();
                     Map<Id,Id> leadInternalOrgMap = new Map<Id,Id>();
        			Map<Id,Id> removeLeadInternalOrgMap = new Map<Id,Id>();
                                   		    
                    for(L_PR_Idea__c lead : (List<L_PR_Idea__c>)Trigger.new){                        
                        // check if affiliation is not blank or value is updated
                        if(lead.L_PR_Affiliation__c != Null && (Trigger.isInsert || (Trigger.isUpdate && lead.L_PR_Affiliation__c != mapOldLead.get(lead.Id).L_PR_Affiliation__c))){                           
                            lAffMap.put(lead.Id,lead.L_PR_Affiliation__c);                               
                        }
                        else if(Trigger.isUpdate && lead.L_PR_Affiliation__c == Null && lead.L_PR_Affiliation__c != mapOldLead.get(lead.Id).L_PR_Affiliation__c){ 
                            //remove the record from list
                            removelAffMap.put(lead.Id,mapOldLead.get(lead.Id).L_PR_Affiliation__c);
                        }
                        
                        // check if the lead status is closed & closed reason is not null
                        if(Trigger.isUpdate && lead.L_PR_Lead_Status__c == 'Closed' && lead.L_PR_Closed_Reason__c != Null){
                            // collect the LeadIds
                            leadIdSet.add(lead.Id);
                        }
                        
                        // check if status is updated (to update on lead organisation field)
                        if(lead.L_PR_Lead_Status__c != Null && Trigger.isUpdate && lead.L_PR_Lead_Status__c != mapOldLead.get(lead.Id).L_PR_Lead_Status__c){
                            leadStatusMap.put(lead.Id,lead.L_PR_Lead_Status__c);
                        }
                        // check if organisation is not blank or value is updated
                        if(lead.L_PR_Organisation__c != Null  && (Trigger.isInsert || (Trigger.isUpdate && lead.L_PR_Organisation__c != mapOldLead.get(lead.Id).L_PR_Organisation__c))){                           
                            leadOrgMap.put(lead.Id,lead.L_PR_Organisation__c);                               
                        }
                        else if(Trigger.isUpdate && lead.L_PR_Organisation__c == Null && lead.L_PR_Organisation__c != mapOldLead.get(lead.Id).L_PR_Organisation__c){ 
                            //remove the record from list
                            removeLeadOrgMap.put(lead.Id,mapOldLead.get(lead.Id).L_PR_Organisation__c);
                        }
                        
                        // check if La trobe organisation unit is not blank or value is updated
                        if(lead.L_PR_La_Trobe_Organisation_Unit__c != Null && (Trigger.isInsert || (Trigger.isUpdate && lead.L_PR_La_Trobe_Organisation_Unit__c != mapOldLead.get(lead.Id).L_PR_La_Trobe_Organisation_Unit__c))){                           
                            leadInternalOrgMap.put(lead.Id,lead.L_PR_La_Trobe_Organisation_Unit__c);                               
                        }
                        else if(Trigger.isUpdate && lead.L_PR_La_Trobe_Organisation_Unit__c == Null && lead.L_PR_La_Trobe_Organisation_Unit__c != mapOldLead.get(lead.Id).L_PR_La_Trobe_Organisation_Unit__c){ 
                            //remove the record from list
                            removeLeadInternalOrgMap.put(lead.Id,mapOldLead.get(lead.Id).L_PR_La_Trobe_Organisation_Unit__c);
                        }
                        
                    }
                    // call helper method to create or update lead affiliation record & isPrimary checkbox
                    if(!lAffMap.isEmpty() || !removelAffMap.isEmpty()){                    	
                    	L_PR_LeadTriggerHelper.createUpdateLeadAffiliations(lAffMap,removelAffMap);
                    }
                    
                    // call helper method to create or update lead organisation record & isPrimary checkbox
                    if(!leadOrgMap.isEmpty() || !removeLeadOrgMap.isEmpty()){                    	
                    	L_PR_LeadTriggerHelper.createUpdateLeadOrganisations(leadOrgMap,removeLeadOrgMap);
                    }
                    
                     // call helper method to create or update lead organisation record & isPrimary checkbox for la trobe organisation unit
                    if(!leadInternalOrgMap.isEmpty() || !removeLeadInternalOrgMap.isEmpty()){                    	
                    	L_PR_LeadTriggerHelper.createUpdateLeadOrganisations(leadInternalOrgMap,removeLeadInternalOrgMap);
                    }
                    
                    //call helper method to update status on related lead organisation records when leadc status changes
                    if(!leadStatusMap.isEmpty())
                        L_PR_LeadTriggerHelper.updateLeadOrganisatioStatus(leadStatusMap);
                    
                    // Send Salesforce notification to staff affiliation users
                    if(!leadIdSet.isEmpty()){
                        for(L_PR_Idea_Affiliation__c leadAff : [Select Id, L_PR_Affiliation__c, L_PR_Idea__c,L_PR_Affiliation__r.I_RM_Role__c,
                                                                		L_PR_Affiliation__r.I_RM_Contact__c, L_PR_Affiliation__r.I_RM_Contact__r.I_RS_Related_User__c
                                                                  		from L_PR_Idea_Affiliation__c where L_PR_Idea__c in:leadIdSet
                                                                  		AND L_PR_Affiliation__r.I_RM_Contact__r.I_RS_Related_User__c != Null
                                       									AND L_PR_Affiliation__r.I_RM_Role__c ='La Trobe Staff']){
                             
                             system.debug('userid' +leadAff.L_PR_Affiliation__r.I_RM_Contact__r.I_RS_Related_User__c);
                             if(!leadStaffMap.isEmpty() && leadStaffMap.get(leadAff.L_PR_Idea__c) != Null){
                             	leadStaffMap.get(leadAff.L_PR_Idea__c).add(leadAff.L_PR_Affiliation__r.I_RM_Contact__r.I_RS_Related_User__c);                                                 
                             }
                             else{
                                 leadStaffMap.put(leadAff.L_PR_Idea__c, new Set<String>{leadAff.L_PR_Affiliation__r.I_RM_Contact__r.I_RS_Related_User__c});                                               
                             }
							 staffIds.add(leadAff.L_PR_Affiliation__r.I_RM_Contact__r.I_RS_Related_User__c);
                         }
                    }
                    if(!leadStaffMap.isEmpty()){
                        L_PR_LeadTriggerHelper.createCustomSFNotification(leadStaffMap);
                    }
    			}
			}
        }catch(exception e){
            system.debug('exception' + e);   
        }
    }
}