force-app/main/default/objects/Project_Proposal__c/Project_Proposal__c.object-meta.xml
<CustomObject>
    <description>Project Proposal: An application for funding either through a grant request, a tender response, or a contract proposal.
Project: The work that is undertaken to satisfy a commitment made to a funding body or client.  The commitment is likely to be a contract (and possible variations) resulting from the acceptance of a project proposal.  This occurs after a grant, contract of philanthropic donation has been awarded.</description>
    <label>Project Proposal</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Proposal__c/fields/I_RS_Allow_Updates_on_Approval__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Allow_Updates_on_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When &quot;checked&quot; the record will be locked after submitted for approval.</description>
    <label>Allow Updates on Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_Proposal__c/fields/I_RS_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PlaceHolder</fullName>
            </value>
            <value>
                <fullName>Create Proposal</fullName>
            </value>
            <value>
                <fullName>Proposal Review</fullName>
            </value>
            <value>
                <fullName>Recommended</fullName>
            </value>
            <value>
                <fullName>Dismissed</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Create EOI</fullName>
            </value>
            <value>
                <fullName>Drafting NOI</fullName>
            </value>
            <value>
                <fullName>Final draft</fullName>
            </value>
            <value>
                <fullName>Draft Proposal</fullName>
            </value>
            <value>
                <fullName>Provide Project Details</fullName>
            </value>
            <value>
                <fullName>Contract Instructions</fullName>
            </value>
            <value>
                <fullName>Review by Research Office</fullName>
            </value>
            <value>
                <fullName>Panel Review</fullName>
            </value>
            <value>
                <fullName>HoS NOI Validation</fullName>
            </value>
            <value>
                <fullName>Pitch Session</fullName>
            </value>
            <value>
                <fullName>Peer review draft</fullName>
            </value>
            <value>
                <fullName>Peer review draft complete</fullName>
            </value>
            <value>
                <fullName>Review Contract</fullName>
            </value>
            <value>
                <fullName>Draft contract</fullName>
            </value>
            <value>
                <fullName>Approvals</fullName>
            </value>
            <value>
                <fullName>Formalise Contract</fullName>
            </value>
            <value>
                <fullName>Submission to Client</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Ready for Submission to Funding Body</fullName>
            </value>
            <value>
                <fullName>Submission to Funding Body</fullName>
                <label>Funding Body Submission</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Rejoinders</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Proposal__c/recordTypes/Placeholder.recordType-meta.xml
<RecordType>
    <fullName>Placeholder</fullName>
    <active>true</active>
    <label>Placeholder</label>
</RecordType>

force-app/main/default/classes/ProjectProposalLockUnlockQueueable.cls
public class ProjectProposalLockUnlockQueueable implements Queueable {
    private static final String APPROVALS = 'Approvals';
    private static final String REVIEW_BY_RESEARCH_OFFICE = 'Review by Research Office';
    private static final set<String> projectProposalLockedStatuses = ProjectProposalHelper.getLockedProposalStatuses();
    
    private List<Id> ppIds;
    private Map<Id, Project_Proposal__c> oldPPMap;
    
    public ProjectProposalLockUnlockQueueable(Set<Id> Ids){
        ppIds = new List<Id>();
        ppIds.addAll(Ids);
    }
    
    public void execute(QueueableContext queCont) {
        List<Id> lockList = new List<Id>();
        List<Id> unlockList = new List<Id>();
        
        Map<Id, boolean> ppLockSuggestedMap = new Map<Id, boolean>();
        
        //Making an assumption any record (which is not Recommendation and Placeholder) that whos status is "approval" should be either locked or unlocked based on I_RS_Allow_Updates_on_Approval__c
        for (Project_Proposal__c pp: [SELECT Id, I_RS_Status__c, I_RS_Allow_Updates_on_Approval__c FROM Project_Proposal__c WHERE Id in : ppIds ]){
            system.debug('ProjectProposalLockUnlockQueueable 1 status: ' + pp.I_RS_Status__c);
            if ((pp != null) && (pp.I_RS_Status__c != null) && (projectProposalLockedStatuses.contains(pp.I_RS_Status__c.toLowerCase()))) {
                system.debug('ProjectProposalLockUnlockQueueable 7');
                if (pp.I_RS_Allow_Updates_on_Approval__c){
                    system.debug('ProjectProposalLockUnlockQueueable 8');
                    unlockList.add(pp.Id);    
                } else {
                    system.debug('ProjectProposalLockUnlockQueueable 9');
                    lockList.add(pp.Id);    
                }                 
            }else {
                system.debug('ProjectProposalLockUnlockQueueable 10');
                unlockList.add(pp.Id);    
            }            
        }
        
        System.debug('lockList: ' +lockList);
        System.debug('unlockList: ' +unlockList);
        if (lockList.size() > 0) {
            Approval.lock(lockList);
        }
        if (unlockList.size() > 0) {
            Approval.unlock(unlockList);
        }
        
    }
}