force-app/main/default/objects/Project_Proposal__c/Project_Proposal__c.object-meta.xml
<CustomObject>
    <description>Project Proposal: An application for funding either through a grant request, a tender response, or a contract proposal.
Project: The work that is undertaken to satisfy a commitment made to a funding body or client.  The commitment is likely to be a contract (and possible variations) resulting from the acceptance of a project proposal.  This occurs after a grant, contract of philanthropic donation has been awarded.</description>
    <label>Project Proposal</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Proposal__c/fields/I_RS_Theme__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Theme__c</fullName>
    <description>https://eawebdev.atlassian.net/browse/T2-876</description>
    <inlineHelpText>Select which theme(s) this project aligns to.</inlineHelpText>
    <label>Theme Alignment</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No theme alignment</fullName>
                <default>true</default>
                <label>No theme alignment</label>
            </value>
            <value>
                <fullName>A healthy, safe and equitable life course for everyone</fullName>
            </value>
            <value>
                <fullName>The production of quality foods &amp; medicines</fullName>
            </value>
            <value>
                <fullName>The protection &amp; restoration of vulnerable ecosystems</fullName>
            </value>
            <value>
                <fullName>Understanding &amp; preventing disease</fullName>
            </value>
            <value>
                <fullName>More just and equitable societies</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task/recordTypes/Ethics.recordType-meta.xml
<RecordType>
    <fullName>Ethics</fullName>
    <active>true</active>
    <label>Ethics</label>
</RecordType>

force-app/main/default/classes/TaskToOutlookTest.cls
@isTest
public class TaskToOutlookTest {

    static public Boolean forceCalloutFail = false; 
    

    
    public static testmethod void calloutTest_Insert_Success(){
        doAThing('insert', false, 'Insert Successful');
    }
    
    public static testmethod void calloutTest_Insert_Failure(){
        doAThing('insert', true, 'Insert Failed');      
    }
    
    public static testmethod void calloutTest_Delete_Success(){
        doAThing('delete', false, 'Delete Successful');
    }
    
    public static testmethod void calloutTest_Delete_Failure(){
        doAThing('delete', true, 'Delete Failed');      
    }

    public static void doAThing(String operationType, Boolean forceCalloutFail, String expectedSyncStatus){
        
        Test.setMock(HttpCalloutMock.class, new TaskToOutlookCalloutMock());
		TaskToOutlookTest.forceCalloutFail = forceCalloutFail;
        
        Project_Proposal__c pp = TestUtility.newProjectProposal();
        pp.I_RS_Theme__c = 'No theme alignment ';
        insert pp;
        
        Task taskToCallout = TestUtility.newTask(pp.Id);
        insert taskToCallout;
        
        Task processedTask;
        
        Test.startTest();
       	processedTask = new TaskToOutlookCalendarCallout(taskToCallout, operationType).execute();
        Test.stopTest();
        
        update processedTask;
        
        System.assert((processedTask.I_RS_Task_to_Outlook_Sync_Error_Message__c != null) == forceCalloutFail);
        System.assertequals(expectedSyncStatus, processedTask.I_RS_Task_to_Outlook_Sync_Status__c);
        
    }
    
    
    
    
    public static testmethod void batchHandlerTest(){
        
        Test.setMock(HttpCalloutMock.class, new TaskToOutlookCalloutMock());
        TaskToOutlookTest.forceCalloutFail = false;

        
        Profile portalProfile = [SELECT Id FROM Profile WHERE Name = 'LTU Partner Community User' Limit 1];
        
		Account portalAccount = TestUtility.newEmptyExternalAccount('TestAccount');
		insert portalAccount;

        Contact portalContact = TestUtility.newContact(portalAccount.Id);
        insert portalContact;
        
        User portalUser = TestUtility.newUser('outlook', portalProfile.Id, null, portalContact.Id);
        insert(portalUser);
        
        Project_Proposal__c pp = TestUtility.newProjectProposal();
        pp.I_RS_Theme__c = 'No theme alignment ';
        insert pp;
        
        Task taskToCallout = TestUtility.newTask(pp.Id);
        taskToCallout.OwnerId = portalUser.Id;
        taskToCallout.RecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Ethics').getRecordTypeId();
        taskToCallout.I_RS_Task_to_Outlook_Sync_Status__c = 'Insert Pending';
        insert taskToCallout;
        
		Test.startTest();
        
        Database.executeBatch(new TaskToOutlookCalendarBatchHandler('insert'), 1);
        
        Test.stopTest();
        
          //System.assertequals('Insert Successful', [select I_RS_Task_to_Outlook_Sync_Status__c from Task].I_RS_Task_to_Outlook_Sync_Status__c);
        
    }
    
    public static testmethod void schedulerTest(){
        
        String scheduleExpression = '0 0 23 * * ?'; 
        
        TaskToOutlookCalendarBatchScheduler schedulableInstance = new TaskToOutlookCalendarBatchScheduler('insert', 1);
        
        Test.startTest();
            
		System.schedule('Task To Outlook Insert', scheduleExpression, schedulableInstance);
        
        Test.stopTest(); 
    
    } 
    
    
}