force-app/main/default/objects/Budget__c/Budget__c.object-meta.xml
<CustomObject>
    <description>This is the summarised budget header details that goes for approval &amp; is maintained in system for any further progress, tracking or finance integration</description>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget__c/fields/I_RS_Amount__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Amount__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/Budget_Line_Item__c.object-meta.xml
<CustomObject>
    <description>This will capture the calculated budget line details from Budget Calculator tool. Please note that Budget Calculator will be a custom developed tool built &amp; integrated with Salesforce. Later the calculated values will be stored in this object.</description>
    <label>Budget Line Item</label>
    <nameField>
        <displayFormat>BLI-{00000}</displayFormat>
        <label>Budget Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Category__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Equipment</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Field Work</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Current La Trobe staff</fullName>
            </value>
            <value>
                <fullName>Future La Trobe staff</fullName>
            </value>
            <value>
                <fullName>Research Assistant</fullName>
            </value>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Non-La Trobe researcher</fullName>
            </value>
            <value>
                <fullName>Personnel</fullName>
            </value>
            <value>
                <fullName>HDR Stipends</fullName>
            </value>
            <value>
                <fullName>Teaching Relief</fullName>
            </value>
            <value>
                <fullName>Field Research</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Cash External</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Contact__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Budget Line Items</relationshipLabel>
    <relationshipName>Budget_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Organisation__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Budget Line Items</relationshipLabel>
    <relationshipName>Budget_Line_Items_Org</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Sub_Category__c</fullName>
    <label>Sub-Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>I_RS_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Level A 1</fullName>
            </value>
            <value>
                <fullName>Level A 2</fullName>
            </value>
            <value>
                <fullName>Level A 3</fullName>
            </value>
            <value>
                <fullName>Level A 4</fullName>
            </value>
            <value>
                <fullName>Level A 5</fullName>
            </value>
            <value>
                <fullName>Level A 6</fullName>
            </value>
            <value>
                <fullName>Level A 7</fullName>
            </value>
            <value>
                <fullName>Level A 8</fullName>
            </value>
            <value>
                <fullName>Level B 1</fullName>
            </value>
            <value>
                <fullName>Level B 2</fullName>
            </value>
            <value>
                <fullName>Level B 3</fullName>
            </value>
            <value>
                <fullName>Level B 4</fullName>
            </value>
            <value>
                <fullName>Level B 5</fullName>
            </value>
            <value>
                <fullName>Level B 6</fullName>
            </value>
            <value>
                <fullName>Level C 1</fullName>
            </value>
            <value>
                <fullName>Level C 2</fullName>
            </value>
            <value>
                <fullName>Level C 3</fullName>
            </value>
            <value>
                <fullName>Level C 4</fullName>
            </value>
            <value>
                <fullName>Level C 5</fullName>
            </value>
            <value>
                <fullName>Level C 6</fullName>
            </value>
            <value>
                <fullName>Level D 1</fullName>
            </value>
            <value>
                <fullName>Level D 2</fullName>
            </value>
            <value>
                <fullName>Level D 3</fullName>
            </value>
            <value>
                <fullName>Level D 4</fullName>
            </value>
            <value>
                <fullName>Level E 1</fullName>
            </value>
            <value>
                <fullName>HEO1-1</fullName>
            </value>
            <value>
                <fullName>HEO1-2</fullName>
            </value>
            <value>
                <fullName>HEO1-3</fullName>
            </value>
            <value>
                <fullName>HEO1-4</fullName>
            </value>
            <value>
                <fullName>HEO2-1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Unit_of_Time__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Unit_of_Time__c</fullName>
    <label>Unit of Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Years</fullName>
            </value>
            <value>
                <fullName>Months</fullName>
            </value>
            <value>
                <fullName>Weeks</fullName>
            </value>
            <value>
                <fullName>Days</fullName>
            </value>
            <value>
                <fullName>Hours</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Year_1_Base_Salary__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Year_1_Base_Salary__c</fullName>
    <label>Year 1 Base Salary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Year_2_Base_Salary__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Year_2_Base_Salary__c</fullName>
    <label>Year 2 Base Salary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Year_3_Base_Salary__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Year_3_Base_Salary__c</fullName>
    <label>Year 3 Base Salary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Year_4_Base_Salary__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Year_4_Base_Salary__c</fullName>
    <label>Year 4 Base Salary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Year_5_Base_Salary__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Year_5_Base_Salary__c</fullName>
    <label>Year 5 Base Salary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Year_6_Base_Salary__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Year_6_Base_Salary__c</fullName>
    <label>Year 6 Base Salary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/I_RS_Year_7_Base_Salary__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Year_7_Base_Salary__c</fullName>
    <label>Year 7 Base Salary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/Year_1_Cost__c.field-meta.xml
<CustomField>
    <fullName>Year_1_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total Amount for this Budget Item over Year 1</inlineHelpText>
    <label>Year 1 Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/Year_1_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Year_1_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <description>For Salary Items, this is the number of time units. For Non-Salary, this is the Quantity of Items.</description>
    <inlineHelpText>For Salary Items, this is the number of time units. 

For Non-Salary, this is the Quantity of Items.</inlineHelpText>
    <label>Year 1 Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/Year_2_Cost__c.field-meta.xml
<CustomField>
    <fullName>Year_2_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Year 2 Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/Year_2_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Year_2_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Year 2 Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/Year_3_Cost__c.field-meta.xml
<CustomField>
    <fullName>Year_3_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Year 3 Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/Year_3_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Year_3_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Year 3 Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/Year_4_Cost__c.field-meta.xml
<CustomField>
    <fullName>Year_4_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Year 4 Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/Year_4_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Year_4_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Year 4 Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/Year_5_Cost__c.field-meta.xml
<CustomField>
    <fullName>Year_5_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Year 5 Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/Year_5_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Year_5_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Year 5 Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/Year_6_Cost__c.field-meta.xml
<CustomField>
    <fullName>Year_6_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Year 6 Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/Year_6_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Year_6_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Year 6 Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/Year_7_Cost__c.field-meta.xml
<CustomField>
    <fullName>Year_7_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Year 7 Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/fields/Year_7_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Year_7_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Year 7 Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Budget_Line_Item__c/recordTypes/I_RS_Non_Salary.recordType-meta.xml
<RecordType>
    <fullName>I_RS_Non_Salary</fullName>
    <active>true</active>
    <label>Non-Salary</label>
</RecordType>

force-app/main/default/objects/Budget_Line_Item__c/recordTypes/I_RS_Salary.recordType-meta.xml
<RecordType>
    <fullName>I_RS_Salary</fullName>
    <active>true</active>
    <label>Salary</label>
</RecordType>

force-app/main/default/classes/BudgetCalculator.cls
public without sharing class BudgetCalculator {
    
    //Boolean returnOutputFieldsOnly = false;

    //BLI data
    List<Budget_Line_Item__c> bliInput;

    List<Budget_Line_Item__c> blisSalaryWithCalc = new List<Budget_Line_Item__c>();
    //List<Budget_Line_Item__c> blisSalaryWithoutCalc;

    //List<Budget_Line_Item__c> blisCollabSubcontractor;
    List<Budget_Line_Item__c> blisNonSalary = new List<Budget_Line_Item__c>();

    //Parent data
    public Map<Id, Budget__c> budgets;
    public Map<Id, Contact> contacts;
    public Map<Id, Account> funders;

    //Metadata
    Map<String, Schema.RecordTypeInfo> recordTypes = Schema.SObjectType.Budget_Line_Item__c.getRecordTypeInfosByDeveloperName();
    Map<ID, Schema.RecordTypeInfo> recordTypesById = Schema.SObjectType.Budget_Line_Item__c.getRecordTypeInfosById();
    public List<Map<String, String>> yearColumnBundles = new List<Map<String, String>>{
        new Map<String, String>{
            'quantityField' => 'Year_1_Quantity__c',
            'baseSalaryField' => 'I_RS_Year_1_Base_Salary__c',
            'costField' => 'Year_1_Cost__c'
        },
        new Map<String, String>{
            'quantityField' => 'Year_2_Quantity__c',
            'baseSalaryField' => 'I_RS_Year_2_Base_Salary__c',
            'costField' => 'Year_2_Cost__c'
        },
        new Map<String, String>{
            'quantityField' => 'Year_3_Quantity__c',
            'baseSalaryField' => 'I_RS_Year_3_Base_Salary__c',
            'costField' => 'Year_3_Cost__c'
        },
        new Map<String, String>{
            'quantityField' => 'Year_4_Quantity__c',
            'baseSalaryField' => 'I_RS_Year_4_Base_Salary__c',
            'costField' => 'Year_4_Cost__c'
        },
        new Map<String, String>{
            'quantityField' => 'Year_5_Quantity__c',
            'baseSalaryField' => 'I_RS_Year_5_Base_Salary__c',
            'costField' => 'Year_5_Cost__c'
        },
        new Map<String, String>{
            'quantityField' => 'Year_6_Quantity__c',
            'baseSalaryField' => 'I_RS_Year_6_Base_Salary__c',
            'costField' => 'Year_6_Cost__c'
        },
        new Map<String, String>{
            'quantityField' => 'Year_7_Quantity__c',
            'baseSalaryField' => 'I_RS_Year_7_Base_Salary__c',
            'costField' => 'Year_7_Cost__c'
        }
    };
        
    public List<Apex_Debug_Log__c> apexDebugLogs = new List<Apex_Debug_Log__c>();
        

    public BudgetCalculator(List<Budget_Line_Item__c> bliInput){

        System.debug('BudgetCalcaultor '+bliInput);

        this.bliInput = bliInput;

        funders = getFunders(bliInput);
        budgets = getBudgets(bliInput);
        
        for (Budget_Line_Item__c bli : bliInput){

            resetAmountFields(bli);

            System.debug('recordTypeId '+bli.recordtypeId);
            String bliRecordTypeName = recordTypesById.get(bli.recordTypeId).getDeveloperName();
            System.debug('recordtypeName '+bliRecordTypeName);
            switch on bliRecordTypeName {
                when 'I_RS_Salary' {
                    if (
                        bli.I_RS_Category__c != NULL &&    
                        bli.I_RS_Category__c != 'Non-La Trobe Researcher' &&
                        (
                            (bli.I_RS_Category__c == 'Current La Trobe staff' && bli.I_RS_Contact__c != NULL) || 
                         	(bli.I_RS_Category__c != 'Current La Trobe staff' && bli.I_RS_Sub_Category__c != NULL)
                        ) &&
                        bli.I_RS_Organisation__c != NULL &&
                        bli.I_RS_Unit_of_Time__c != NULL
                    ){

                        blisSalaryWithCalc.add(bli);
                        
                        /*else 
                            blisSalaryWithoutCalc.add(bli);*/
                    }
                }
                when 'I_RS_Non_Salary' {blisNonSalary.add(bli);}
            }
        }
        if (!blisSalaryWithCalc.isEmpty()){
            contacts = getContacts(bliInput);
        }

    }

    //Currently only works for existing BLIs
    public void recalculateAndSave(){

        calculate();

        System.debug(bliInput[0].I_RS_Amount__c);

        System.debug('Saving...');

        List<Database.SaveResult> updateResults = Database.update(bliInput, false);
        GlobalUtility.constructErrorLogsForDMLErrors(
            updateResults, bliInput, 'BudgetCalculator', 'recalculateAndSave');

    }

    public void calculate(){

        System.debug('calculate');

        if (!blisSalaryWithCalc.isEmpty()){
            calculateSalaryWithSalaryTable();
        }
        if (!blisNonSalary.isEmpty()){
            calculateNonSalary();
        }

        if (!apexDebugLogs.isEmpty()){
            insert apexDebugLogs;
        }

    }



    void calculateSalaryWithSalaryTable(){

        System.debug('run salary calculation');

        BudgetCalculatorSalary.calculateSalaries(this, blisSalaryWithCalc);

        for (Budget_Line_Item__c bli : blisSalaryWithCalc){
            if (funderIsEligibleForGST(bli) == true && isInKind(bli) == false){
                applyGST(bli);
            }
        }

    }

    /*void calculateSalaryTableWithSumming(){

    }*/


    void calculateNonSalary(){

        for (Budget_Line_Item__c bli : blisNonSalary){
            calculateYearCostsByAmountAndQty(bli);

            if (bli.I_RS_Category__c != 'Adjustment' && !isInKind(bli) && 
                bli.I_RS_Organisation__c != null && hasExternalFunder(bli)){
                applyNonSalaryOverhead(bli);
            }

            calculateTotalCostByTallyingYearCosts(bli);

            if (funderIsEligibleForGST(bli) == true && isInKind(bli) == false){
                applyGST(bli);
            }
            else {
                bli.I_RS_Cash_Amount_Inc_GST_Currency__c = bli.I_RS_Amount__c;
            }
        }
        

    }



    void applyNonSalaryOverhead(Budget_Line_Item__c bli){
        Budget__c budget = budgets.get(bli.I_RS_Budget__c);

        Decimal nonSalaryOverhead = (Decimal) budget.I_RS_Actual_Non_Salary_Overhead__c;

        if (nonSalaryOverhead != null){
            for (Map<String, String> bundle : yearColumnBundles){
                String yearCostField = bundle.get('costField');
                Decimal yearCost = (Decimal) bli.get(yearCostField);
    
                bli.put(yearCostField, yearCost * ((nonSalaryOverhead / 100) + 1));
            }
        }
        else {
            recordFailedRow(
                'Non-Salary Budget Line Item cannot be recalculated '+
                'as Budget is missing Actual Non-Salary Overhead',
                'Error', bli);
        }
    }


    Boolean funderIsEligibleForGST(Budget_Line_Item__c bli){
        System.debug('funderIsEligibleForGST');
        if (bli.I_RS_Organisation__c != null){
            Account funder = funders.get(bli.I_RS_Organisation__c);
            System.debug('funder '+funder);

            return !funder.I_RS_Part_of_La_Trobe__c && funder.I_RS_Include_GST_In_Budgeting__c;
        }
        return null;
    }

    Boolean hasExternalFunder(Budget_Line_Item__c bli){
        System.debug('hasExternalFunder');
        if (bli.I_RS_Organisation__c != null){
            Account funder = funders.get(bli.I_RS_Organisation__c);
            System.debug('funder '+funder);

            return !funder.I_RS_Part_of_La_Trobe__c;
        }
        return false;
    }

    Boolean isInKind(Budget_Line_Item__c bli){
        return bli.I_RS_In_Kind__c;
    }


    void applyGST(Budget_Line_Item__c bli){

        Decimal gstAmount = GST__c.getOrgDefaults().I_RS_Current_Rate__c;
        bli.I_RS_Cash_Amount_Inc_GST_Currency__c = 
            bli.I_RS_Amount__c * ((gstAmount / 100) + 1);

    }

    void calculateYearCostsByAmountAndQty(Budget_Line_Item__c bli){
    
        for (Map<String, String> bundle : yearColumnBundles){

            String yearQtyField = bundle.get('quantityField');
            Decimal yearQty = (Decimal) bli.get(yearQtyField);

            String yearCostField = bundle.get('costField');

            if (bli.Unit_Price__c != null && yearQty != null){
                
                Decimal yearCost = yearQty * bli.Unit_Price__c;
                bli.put(yearCostField, yearCost); 
            }
            else {
                bli.put(yearCostField, 0); 
            }

        }

    }

    void calculateTotalCostByTallyingYearCosts(Budget_Line_Item__c bli){

        Decimal totalCost = 0;
        for (Map<String, String> bundle : yearColumnBundles){

            String yearCostField = bundle.get('costField');
            Decimal yearCost = (Decimal) bli.get(yearCostField);

            if (yearCost != null)
                totalCost += yearCost;
            else {
                totalCost += 0;
            }

        }
        bli.I_RS_Amount__c = totalCost;

    }


    Map<Id, Budget__c> getBudgets(List<Budget_Line_Item__c> budgetLineItems){
        Set<Id> budgetIds = GlobalUtility.getParentIds(budgetLineItems, 'I_RS_Budget__c');
        List<Budget__c> budgets = [SELECT Id, I_RS_Year_1_Starts__c, I_RS_Project_End_Date__c, 
        I_RS_Project_Proposal__r.I_RS_Project_Duration_In_Years__c, I_RS_Actual_Overhead__c,
            I_RS_Actual_Profit__c, I_RS_Actual_Non_Salary_Overhead__c FROM Budget__c WHERE Id IN :budgetIds];
        System.debug('budgets '+budgets);
        
        return new Map<Id, Budget__c>(budgets);
    }


    Map<Id, Contact> getContacts(List<Budget_Line_Item__c> budgetLineItems){
        Set<Id> contactIds = GlobalUtility.getParentIds(budgetLineItems, 'I_RS_Contact__c');
        List<Contact> contacts = [SELECT Id, I_RS_Salary_Grade__c
                FROM Contact WHERE Id IN :contactIds];
        System.debug('contacts '+contacts);
        
        return new Map<Id, Contact>(contacts);
    }

    Map<Id, Account> getFunders(List<Budget_Line_Item__c> budgetLineItems){

        Set<Id> funderIds = GlobalUtility.getParentIds(budgetLineItems, 'I_RS_Organisation__c');
        List<Account> funders = [SELECT Id, I_RS_Maximum_Allowed_On_Cost__c, 
            I_RS_Part_of_La_Trobe__c, I_RS_Include_GST_In_Budgeting__c FROM Account WHERE Id IN :funderIds]; 

        System.debug('Funders '+funders);

        return new Map<Id, Account>(funders);

    }

    
    public void recordFailedRow(String message, String logType, SObject failedRow){
        apexDebugLogs.add(
            new Apex_Debug_Log__c(
                Log_Type__c = logType,
                Apex_Class_Name__c = 'BudgetCalculatorSalary',
                Apex_Class_Method_Name__c = 'calculateSalaries',
                Exception_message__c = message,
                Request_Data__c = JSON.serializePretty(failedRow),
                Related_To_Id__c = (String) failedRow.get('Id')
        	)
        );
    }


    void resetAmountFields(Budget_Line_Item__c bli){

        bli.I_RS_Amount__c = 0;
        bli.I_RS_Year_1_Base_Salary__c = 0;
        bli.I_RS_Year_2_Base_Salary__c = 0;
        bli.I_RS_Year_3_Base_Salary__c = 0;
        bli.I_RS_Year_4_Base_Salary__c = 0;
        bli.I_RS_Year_5_Base_Salary__c = 0;
        bli.I_RS_Year_6_Base_Salary__c = 0;
        bli.I_RS_Year_7_Base_Salary__c = 0;
        bli.Year_1_Cost__c = 0;
        bli.Year_2_Cost__c = 0;
        bli.Year_3_Cost__c = 0;
        bli.Year_4_Cost__c = 0;
        bli.Year_5_Cost__c = 0;
        bli.Year_6_Cost__c = 0;
        bli.Year_7_Cost__c = 0;
        bli.I_RS_Short_Fall__c = 0;
    
    }


}