force-app/main/default/objects/Budget__c/Budget__c.object-meta.xml
<CustomObject>
    <description>This is the summarised budget header details that goes for approval &amp; is maintained in system for any further progress, tracking or finance integration</description>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget__c/fields/I_RS_Actual_Non_Salary_Overhead__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Actual_Non_Salary_Overhead__c</fullName>
    <inlineHelpText>The percentage applied to non-salary items to cover the La Trobe operating costs such as infrastructure, facilities and services.</inlineHelpText>
    <label>Actual Non-Salary Overhead</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Actual_Overhead__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Actual_Overhead__c</fullName>
    <inlineHelpText>The percentage overhead applied to researcher salary to cover La Trobe infrastructure, facilities and services.</inlineHelpText>
    <label>Actual Salary Overhead</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Actual_Profit__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Actual_Profit__c</fullName>
    <inlineHelpText>The percentage applied to researcher salary to be returned to the university/researcher.</inlineHelpText>
    <label>Actual Salary Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Actual_Rate_Type__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Actual_Rate_Type__c</fullName>
    <inlineHelpText>The type of funding being applied for to determine the appropriate overhead and profit rates.</inlineHelpText>
    <label>Actual Project Rate</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Research Collaboration</fullName>
            </value>
            <value>
                <fullName>Research Consultancy (Collaborative)</fullName>
            </value>
            <value>
                <fullName>Research Consultancy (Commercial)</fullName>
            </value>
            <value>
                <fullName>Non-Research Consultancy</fullName>
            </value>
            <value>
                <fullName>Grant</fullName>
            </value>
            <value>
                <fullName>Grant with Overheads</fullName>
            </value>
            <value>
                <fullName>Scholarship</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Base_Salary__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Base_Salary__c</fullName>
    <inlineHelpText>Lead Chief&apos;s Investigator&apos;s Base Salary</inlineHelpText>
    <label>Base Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Daily_On_Costs__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Daily_On_Costs__c</fullName>
    <inlineHelpText>On-costs include payroll tax, workcover and superannuation</inlineHelpText>
    <label>Daily On-Costs</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Daily_Overheads__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Daily_Overheads__c</fullName>
    <inlineHelpText>Daily Overheads are indirect costs, for example legal, insurance, electricity costs, etc.</inlineHelpText>
    <label>Daily Overheads</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Daily_Profits__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Daily_Profits__c</fullName>
    <label>Daily Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Daily_Salary__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Daily_Salary__c</fullName>
    <inlineHelpText>Daily Charge Out Rate for the Funder</inlineHelpText>
    <label>Daily Salary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Lead_Chief_Investigator__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Lead_Chief_Investigator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Example Rate For</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Budgets</relationshipLabel>
    <relationshipName>Budgets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Maximum_Allowed_On_Cost__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Maximum_Allowed_On_Cost__c</fullName>
    <inlineHelpText>Maximum allowable on-cost rate set by Funder.</inlineHelpText>
    <label>Maximum Allowed On-Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Overhead__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Overhead__c</fullName>
    <inlineHelpText>Default salary based on the type of funding</inlineHelpText>
    <label>Default Salary Overhead</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Profit__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Profit__c</fullName>
    <inlineHelpText>Default salary margin based on the type of funding</inlineHelpText>
    <label>Default Salary Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Project_Proposal__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Project_Proposal__c</fullName>
    <label>Project Proposal</label>
    <referenceTo>Project_Proposal__c</referenceTo>
    <relationshipLabel>Budgets</relationshipLabel>
    <relationshipName>Budgets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Year_1_Starts__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Year_1_Starts__c</fullName>
    <formula>YEAR( I_RS_Project_Proposal__r.I_RS_Project_Start_Date__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year 1 Starts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/I_RS_Year__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Year__c</fullName>
    <description>We need to break down the income by year for reporting purposes (Date Year Only)</description>
    <label>Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_RS_Salary_Grade__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Salary_Grade__c</fullName>
    <label>Salary Grade (HR)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Level A 1</fullName>
            </value>
            <value>
                <fullName>Level A 2</fullName>
            </value>
            <value>
                <fullName>Level A 3</fullName>
            </value>
            <value>
                <fullName>Level A 4</fullName>
            </value>
            <value>
                <fullName>Level A 5</fullName>
            </value>
            <value>
                <fullName>Level A 6</fullName>
            </value>
            <value>
                <fullName>Level A 7</fullName>
            </value>
            <value>
                <fullName>Level A 8</fullName>
            </value>
            <value>
                <fullName>Level B 1</fullName>
            </value>
            <value>
                <fullName>Level B 2</fullName>
            </value>
            <value>
                <fullName>Level B 3</fullName>
            </value>
            <value>
                <fullName>Level B 4</fullName>
            </value>
            <value>
                <fullName>Level B 5</fullName>
            </value>
            <value>
                <fullName>Level B 6</fullName>
            </value>
            <value>
                <fullName>Level C 1</fullName>
            </value>
            <value>
                <fullName>Level C 2</fullName>
            </value>
            <value>
                <fullName>Level C 3</fullName>
            </value>
            <value>
                <fullName>Level C 4</fullName>
            </value>
            <value>
                <fullName>Level C 5</fullName>
            </value>
            <value>
                <fullName>Level C 6</fullName>
            </value>
            <value>
                <fullName>Level D 1</fullName>
            </value>
            <value>
                <fullName>Level D 2</fullName>
            </value>
            <value>
                <fullName>Level D 3</fullName>
            </value>
            <value>
                <fullName>Level D 4</fullName>
            </value>
            <value>
                <fullName>Level E 1</fullName>
            </value>
            <value>
                <fullName>HEO1-1</fullName>
            </value>
            <value>
                <fullName>HEO1-2</fullName>
            </value>
            <value>
                <fullName>HEO1-3</fullName>
            </value>
            <value>
                <fullName>HEO1-4</fullName>
            </value>
            <value>
                <fullName>HEO2-1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/On_Cost_Default_Values__c/fields/I_RS_Maximum_Allowed_On_Cost__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Maximum_Allowed_On_Cost__c</fullName>
    <label>Maximum Allowed On-Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Overheads_and_Profit_Default_Values__c/Overheads_and_Profit_Default_Values__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Overheads and Profit Default Values</description>
    <label>Overheads and Profit Default Values</label>
</CustomObject>

force-app/main/default/objects/Overheads_and_Profit_Default_Values__c/fields/I_RS_Non_Salary_Overhead__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Non_Salary_Overhead__c</fullName>
    <label>Non-Salary Overhead</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Overheads_and_Profit_Default_Values__c/fields/I_RS_Overhead__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Overhead__c</fullName>
    <label>Overhead %</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Overheads_and_Profit_Default_Values__c/fields/I_RS_Profit__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Profit__c</fullName>
    <label>Profit %</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Overheads_and_Profit_Default_Values__c/fields/I_RS_Rate_Type__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Rate_Type__c</fullName>
    <label>Rate Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Proposal__c/Project_Proposal__c.object-meta.xml
<CustomObject>
    <description>Project Proposal: An application for funding either through a grant request, a tender response, or a contract proposal.
Project: The work that is undertaken to satisfy a commitment made to a funding body or client.  The commitment is likely to be a contract (and possible variations) resulting from the acceptance of a project proposal.  This occurs after a grant, contract of philanthropic donation has been awarded.</description>
    <label>Project Proposal</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Proposal__c/fields/I_RS_Lead_Chief_Investigator__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Lead_Chief_Investigator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Chief Investigator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Project Proposals</relationshipLabel>
    <relationshipName>Project_Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Salary_Table__c/Salary_Table__c.object-meta.xml
<CustomObject>
    <label>Salary Table</label>
    <nameField>
        <label>Salary Grade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salary Table</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Salary_Table__c/fields/I_RS_HR_System_Group_ID__c.field-meta.xml
<CustomField>
    <fullName>I_RS_HR_System_Group_ID__c</fullName>
    <description>How a particular grade and group combination, e.g. HEO1-1, is represented in the HR System. Used when matching Salary Table entries to Contacts, i.e. when collecting base salary for Current La Trobe Staff Budget Line Items</description>
    <label>HR System Group Identifier</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Salary_Table__c/fields/I_RS_Salary__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Salary__c</fullName>
    <label>Salary</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/BudgetRateHelper.cls
public class BudgetRateHelper {

    public static Integer yearlyToDailyRateDivider = 235;
    
    
    public static Map<String, Overheads_and_Profit_Default_Values__c> getDefaultRateValueMap(){
        
        Map<String, Overheads_and_Profit_Default_Values__c> defaultRateValueMap = 
            new Map<String, Overheads_and_Profit_Default_Values__c>();
          
        for (Overheads_and_Profit_Default_Values__c defaultValue : [
            select Id, 
            	I_RS_Rate_Type__c, 
            	I_RS_Overhead__c, 
            	I_RS_Profit__c, 
            I_RS_Non_Salary_Overhead__c
            from Overheads_and_Profit_Default_Values__c]){
         
            defaultRateValueMap.put(defaultValue.I_RS_Rate_Type__c, defaultValue);
        }
        
        return defaultRateValueMap;
    }

    
    
  
    public static List<Budget__c> provideActualRatesBasedOnRateType(Budget__c[] budgetsToProcess){
        
        Map<String, Overheads_and_Profit_Default_Values__c> defaultRateValueMap =
            getDefaultRateValueMap();

            
        for (Budget__c budget : budgetsToProcess){
            
            String rateType = budget.I_RS_Actual_Rate_Type__c;
            if (rateType != null){
            	Overheads_and_Profit_Default_Values__c defaultValue = defaultRateValueMap.get(rateType);

				System.debug(defaultValue);
                
                //if (defaultValue != null){
                    budget.I_RS_Actual_Overhead__c = defaultValue.I_RS_Overhead__c;
                    budget.I_RS_Actual_Profit__c = defaultValue.I_RS_Profit__c;
                    budget.I_RS_Actual_Non_Salary_Overhead__c = defaultValue.I_RS_Non_Salary_Overhead__c;
                //}
            }
            
            system.debug(budget);
        }
        
        return budgetsToProcess;
    }

    @AuraEnabled
    public static List<Budget__c> provideActualRatesBasedOnRateType_Aura(List<Budget__c> budgetsToProcess) {
        System.debug('provideActualRatesBasedOnRateType_Aura');
        
        return provideActualRatesBasedOnRateType(budgetsToProcess);
    }   
    
    @InvocableMethod(label='Assign Budget Rate Values' description='Assign Rate values to Budget based on Actual Rate Type')  
    public static List<Budget__c> provideActualRatesBasedOnRateType_Flow(List<Budget__c> budgetsToProcess) {
        System.debug('provideActualRatesBasedOnRateType_Flow');
        
        return provideActualRatesBasedOnRateType(budgetsToProcess);
    }   
    
    
    
    
    
    public static List<Budget__c> provideDailyChargeoutRates(List<Budget__c> budgetsToProcess){
        
		Map<Id, Budget__c> budgetMap = new Map<Id, Budget__c>(budgetsToProcess);
        Set<Id> budgetIds = budgetMap.keySet();
        
		List<Budget__c> budgetListInclParentData = [
            select Id, 
            I_RS_Year_1_Starts__c,
            I_RS_Project_Proposal__r.I_RS_Lead_Chief_Investigator__r.I_RS_Salary_Grade__c
            from Budget__c where Id in :budgetIds
        ];

        On_Cost_Default_Values__c ltuMaxOnCost = On_Cost_Default_Values__c.getInstance('La Trobe University');
        
        Map<String, Salary_Table__c> salaryTableMap = getSalaryTableMapForBudgetLCIs(budgetListInclParentData);
        
        for (Budget__c budget : budgetListInclParentData){
            
            String salaryGradeName = budget.I_RS_Project_Proposal__r.I_RS_Lead_Chief_Investigator__r.I_RS_Salary_Grade__c;
            Decimal budgetStartYear = budget.I_RS_Year_1_Starts__c;

            String salaryTableMapKey = salaryGradeName+'|'+budgetStartYear;
            
            Salary_Table__c matchingSalaryTable = salaryTableMap.get(salaryTableMapKey);
            
            Budget__c budgetToProcess = budgetMap.get(budget.Id);
            
            if (matchingSalaryTable != null){
                
                Decimal year1BaseSalary = matchingSalaryTable.I_RS_Salary__c;
                
                Decimal onCostPercentage = ltuMaxOnCost.I_RS_Maximum_Allowed_On_Cost__c / 100;
                
                Decimal overheadPercentage = 
                    (budgetToProcess.I_RS_Actual_Overhead__c != null ? 
                     	budgetToProcess.I_RS_Actual_Overhead__c / 100 :
                    	0);
                
                Decimal profitPercentage = 
                    (budgetToProcess.I_RS_Actual_Profit__c != null ? 
                     	budgetToProcess.I_RS_Actual_Profit__c / 100 :
                    	0);
                
                Decimal nonSalaryOverheadPercentage = 
                    (budgetToProcess.I_RS_Actual_Non_Salary_Overhead__c != null ? 
                     	budgetToProcess.I_RS_Actual_Non_Salary_Overhead__c / 100 :
                    	0);
                
                System.debug('overheadPercentage '+overheadPercentage);
                
                Decimal onCostAmountYearly = year1BaseSalary * onCostPercentage;
                Decimal overheadAmountYearly = (year1BaseSalary + onCostAmountYearly) * overheadPercentage ;
                Decimal profitAmountYearly = (year1BaseSalary + onCostAmountYearly) * profitPercentage;
                Decimal nonSalaryOverheadAmountYearly = year1BaseSalary * nonSalaryOverheadPercentage;

                System.debug('onCostAmountYearly '+onCostAmountYearly);
                System.debug('overheadAmountYearly '+overheadAmountYearly);
                System.debug('profitAmountYearly '+profitAmountYearly);
                System.debug('nonSalaryOverheadAmountYearly '+nonSalaryOverheadAmountYearly);
                
				budgetToProcess.I_RS_Base_Salary__c = year1BaseSalary;
                
                budgetToProcess.I_RS_Daily_On_Costs__c = (onCostAmountYearly / yearlyToDailyRateDivider).setScale(2);
                budgetToProcess.I_RS_Daily_Overheads__c = (overheadAmountYearly / yearlyToDailyRateDivider).setScale(2);
                budgetToProcess.I_RS_Daily_Profits__c = (profitAmountYearly/ yearlyToDailyRateDivider).setScale(2);
                budgetToProcess.I_RS_Daily_Salary__c = (year1BaseSalary / yearlyToDailyRateDivider).setScale(2);

            }
            else {
                budgetToProcess.I_RS_Daily_On_Costs__c = 0;
                budgetToProcess.I_RS_Daily_Overheads__c = 0;
                budgetToProcess.I_RS_Daily_Profits__c = 0;
                budgetToProcess.I_RS_Daily_Salary__c = 0;   
            }
            
            System.debug('budgetToProcess '+budgetToProcess);
            
        }
        
        return budgetsToProcess;
        
    }
    
    @AuraEnabled
    public static List<Budget__c> provideDailyChargeoutRates_Aura(List<Budget__c> budgetsToProcess){
        System.debug('provideDailyChargeoutRates_Aura');
        return provideDailyChargeoutRates(budgetsToProcess);
    }
    
	/*@InvocableMethod(label='Assign Budget Daily Chargeout Rate Values' description='Calculate Budget Daily Chargeout Rate fields')  
    public static List<Budget__c> provideDailyChargeoutRates_Flow(List<Budget__c> budgetsToProcess){
        System.debug('provideDailyChargeoutRates_Flow');
        return provideDailyChargeoutRates(budgetsToProcess);
    }    */
    
    
    static Map<String, Salary_Table__c> getSalaryTableMapForBudgetLCIs(Budget__c[] budgets){
        
        Map<String, Salary_Table__c> salaryTableUniqueMap = new Map<String, Salary_Table__c>();
        
        Set<String> salaryGradeCodes = new Set<String>();
        for (Budget__c budget : budgets){
            String salaryGrade = budget.I_RS_Project_Proposal__r.I_RS_Lead_Chief_Investigator__r.I_RS_Salary_Grade__c;
            if (salaryGrade != null)
                salaryGradeCodes.add(salaryGrade);
        }
        System.debug(salaryGradeCodes);
        
        List<Salary_Table__c> salaryTableList = [SELECT Id, Name, I_RS_HR_System_Group_ID__c, I_RS_Year__c, I_RS_Salary__c FROM Salary_Table__c WHERE
                                                I_RS_HR_System_Group_ID__c IN :salaryGradeCodes];
        System.debug(salaryTableList);
        
        for (Salary_Table__c salaryTableRecord : salaryTableList){
            
            salaryTableUniqueMap.put(
                salaryTableRecord.I_RS_HR_System_Group_ID__c+'|'+salaryTableRecord.I_RS_Year__c,
                //salaryTableRecord.Name+'|'+salaryTableRecord.I_RS_Year__c,
                salaryTableRecord);
            
        }
        
        return salaryTableUniqueMap;
        
    }
    
}