force-app/main/default/objects/I_RS_Editable_Grid_Screen_Config__mdt/I_RS_Editable_Grid_Screen_Config__mdt.object-meta.xml
<CustomObject>
    <description>Configurations for the editable-grid single-screen functionality.</description>
    <label>Editable Grid Screen Config</label>
    <pluralLabel>Editable Grid Screen Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/I_RS_Editable_Grid_Screen_Config__mdt/fields/I_RS_Not_Soft_Deleted_Filter__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Not_Soft_Deleted_Filter__c</fullName>
    <description>We also wish to exclude soft-deleted items from the results, using the provided filter</description>
    <inlineHelpText>We also wish to exclude soft-deleted items from the results, using the provided filter</inlineHelpText>
    <label>&apos;Not-Soft-Deleted&apos; Filter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_RS_Editable_Grid_Screen_Config__mdt/fields/I_RS_Object_to_aggregate__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Object_to_aggregate__c</fullName>
    <description>The specific Code object being aggregated</description>
    <inlineHelpText>The specific Code object being aggregated</inlineHelpText>
    <label>Object to aggregate</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Classification_Code__c</fullName>
                <default>true</default>
                <label>Classification_Code__c</label>
            </value>
            <value>
                <fullName>Research_Output_Classification_Code__c</fullName>
            </value>
            <value>
                <fullName>ERA_Classification_Code__c</fullName>
            </value>
            <value>
                <fullName>Researcher_Classification_Code__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RS_Editable_Grid_Screen_Config__mdt/fields/I_RS_Parent_Lookup_Reference__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Parent_Lookup_Reference__c</fullName>
    <description>The non-Classification Master object the code looks up to, i.e. Project Proposal, so we can only show results under that particular parent record</description>
    <inlineHelpText>The non-Classification Master object the code looks up to, i.e. Project Proposal, so we can only show results under that particular parent record</inlineHelpText>
    <label>Parent Lookup Reference</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_RS_Editable_Grid_Screen_Config__mdt/fields/I_RS_Parent_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Parent_Object_Name__c</fullName>
    <label>Parent Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_RS_Editable_Grid_Screen_Config__mdt/fields/I_RS_Parent_Record_Display_Fields__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Parent_Record_Display_Fields__c</fullName>
    <label>Parent Record Display Fields</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_RS_Editable_Grid_Screen_Config__mdt/fields/I_RS_Parent_Record_Widget_Header__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Parent_Record_Widget_Header__c</fullName>
    <label>Parent Record Widget Header</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_RS_Editable_Grid_Screen_Config__mdt/fields/I_RS_PRIME_Back_Office_Page_Name__c.field-meta.xml
<CustomField>
    <fullName>I_RS_PRIME_Back_Office_Page_Name__c</fullName>
    <description>The Lightning App Page used by admins and back-office</description>
    <inlineHelpText>The Lightning App Page used by admins and back-office</inlineHelpText>
    <label>PRIME Back Office Page Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_RS_Editable_Grid_Screen_Config__mdt/fields/I_RS_PRIME_Researcher_Page_Name__c.field-meta.xml
<CustomField>
    <fullName>I_RS_PRIME_Researcher_Page_Name__c</fullName>
    <description>The Lightning Community page used by PRIME researchers</description>
    <inlineHelpText>The Lightning Community page used by PRIME researchers</inlineHelpText>
    <label>PRIME Researcher Portal Page Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_RS_Editable_Grid_Screen_Config__mdt/fields/I_RS_Researcher_Portal_if_applicable__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Researcher_Portal_if_applicable__c</fullName>
    <description>As there multiple portals available to non-back-office users, we may need to pre-decide which one to navigate to if clicking on any clickable links</description>
    <inlineHelpText>As there multiple portals available to non-back-office users, we may need to pre-decide which one to navigate to if clicking on any clickable links</inlineHelpText>
    <label>Researcher Portal (if applicable)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PRIME Researcher</fullName>
                <default>true</default>
                <label>PRIME Researcher</label>
            </value>
            <value>
                <fullName>PRIME ERA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RS_Research_Code_Grouping_Row__mdt/I_RS_Research_Code_Grouping_Row__mdt.object-meta.xml
<CustomObject>
    <description>For implementations of ERA Code groupings (e.g. SEO Codes for Projects, FOR Codes for researchers etc.), store key configuration details</description>
    <label>Research Code Grouping Row</label>
    <pluralLabel>Research Code Grouping Rows</pluralLabel>
</CustomObject>

force-app/main/default/objects/I_RS_Research_Code_Grouping_Row__mdt/fields/I_RS_Editable_Grid_Screen_Config__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Editable_Grid_Screen_Config__c</fullName>
    <description>Shared configuration settings for this entry, or group of entries</description>
    <label>Editable Grid Screen Config</label>
    <referenceTo>I_RS_Editable_Grid_Screen_Config__mdt</referenceTo>
    <relationshipLabel>Research Code Grouping Rows</relationshipLabel>
    <relationshipName>Research_Code_Grouping_Rows</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/I_RS_Research_Code_Grouping_Row__mdt/fields/I_RS_Grid_Config_File_Name__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Grid_Config_File_Name__c</fullName>
    <description>Name of static resource which has all grid configuration information</description>
    <inlineHelpText>Name of static resource which has all grid configuration information</inlineHelpText>
    <label>Grid Config File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_RS_Research_Code_Grouping_Row__mdt/fields/I_RS_Grouping_Label__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Grouping_Label__c</fullName>
    <description>How the grouping should be labelled on the UI</description>
    <inlineHelpText>How the grouping should be labelled on the UI</inlineHelpText>
    <label>Grouping Label</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_RS_Research_Code_Grouping_Row__mdt/fields/I_RS_Grouping_Name__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Grouping_Name__c</fullName>
    <description>When aggregating and validating the codes, they belong to distinct Classification Master groups. This field captures the settings for them.</description>
    <inlineHelpText>When aggregating and validating the codes, they belong to distinct Classification Master groups. This field captures the settings for them.</inlineHelpText>
    <label>Grouping Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fields of Research (FOR)</fullName>
                <default>true</default>
                <label>Fields of Research (FOR)</label>
            </value>
            <value>
                <fullName>Fields of Research - 2008 (FOR - 08)</fullName>
            </value>
            <value>
                <fullName>Socio-economic Objective (SEO)</fullName>
            </value>
            <value>
                <fullName>Socio-economic Objective - 2008 (SEO - 08)</fullName>
            </value>
            <value>
                <fullName>Type of Activity (TOA)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RS_Research_Code_Grouping_Row__mdt/fields/I_RS_Hide_in_breakdown_list_if_empty__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Hide_in_breakdown_list_if_empty__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When using the &apos;breakdown&apos; UI component that aggregates code data by grouping, you can opt to hide rows where no records are found. For example, historical data that is less important than the other codes.</description>
    <inlineHelpText>When using the &apos;breakdown&apos; UI component that aggregates code data by grouping, you can opt to hide rows where no records are found. For example, historical data that is less important than the other codes.</inlineHelpText>
    <label>Hide in breakdown list if empty</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/URL_Variable__c/URL_Variable__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>URL Variable</label>
</CustomObject>

force-app/main/default/objects/URL_Variable__c/fields/I_RS_ERA_Portal_Base_URL__c.field-meta.xml
<CustomField>
    <fullName>I_RS_ERA_Portal_Base_URL__c</fullName>
    <description>Base portal for ERA Portal</description>
    <label>ERA Portal Base URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/URL_Variable__c/fields/I_RS_Internal_Base_URL__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Internal_Base_URL__c</fullName>
    <label>Internal Base URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/URL_Variable__c/fields/I_RS_Researcher_Portal_Base_URL__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Researcher_Portal_Base_URL__c</fullName>
    <description>Base URL of the PRIME Researcher Portal. Used for hyperlinking.</description>
    <label>Researcher Portal Base URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/User/fields/I_RS_Is_Researcher_User__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Is_Researcher_User__c</fullName>
    <formula>IF(Profile.Name = &quot;LTU Partner Community User&quot; ||
Profile.Name = &quot;LTU Partner Community Login User&quot;, &quot;1&quot;, &quot;0&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Researcher User?</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ResearchCodeGridSummaryController.cls
public without sharing class ResearchCodeGridSummaryController {

    @AuraEnabled 
    public static List<ERACodeGrouping> getSummaryData(Id parentId, String pageConfigName){
        
        List<ERACodeGrouping> outputData = new List<ERACodeGrouping>();
        
		I_RS_Editable_Grid_Screen_Config__mdt gridConfig = [
          SELECT
            I_RS_Object_to_aggregate__c,
            I_RS_Parent_Object_Name__c,
			I_RS_Parent_Lookup_Reference__c,
			I_RS_Not_Soft_Deleted_Filter__c,
			I_RS_PRIME_Back_Office_Page_Name__c,
			I_RS_PRIME_Researcher_Page_Name__c,
            I_RS_Parent_Record_Widget_Header__c,
            I_RS_Parent_Record_Display_Fields__c,
            I_RS_Researcher_Portal_if_applicable__c,
            (
                SELECT 
                Label, 
                I_RS_Grid_Config_File_Name__c, 
                I_RS_Grouping_Name__c, 
                I_RS_Grouping_Label__c,
                I_RS_Hide_in_breakdown_list_if_empty__c 
                FROM Research_Code_Grouping_Rows__r 
                ORDER BY I_RS_Grouping_Label__c
            )
            FROM I_RS_Editable_Grid_Screen_Config__mdt
            WHERE DeveloperName = :pageConfigName
            
        ];
        
        DescribeSObjectResult schemaType = Schema.describeSObjects(new String[]{gridConfig.I_RS_Object_to_aggregate__c})[0];
        if (!schemaType.isAccessible()){
            return NULL;
        }

        //Get common variables
        System.debug('gridConfig '+gridConfig);
        List<I_RS_Research_Code_Grouping_Row__mdt> codeGroupConfigList = 
            (List<I_RS_Research_Code_Grouping_Row__mdt>) gridConfig.getSObjects('Research_Code_Grouping_Rows__r');
        
        //Instantate row-by-row payload to send back
        Map<String, ERACodeGrouping> temporaryOutputData = new Map<String, ERACodeGrouping>();
        for (I_RS_Research_Code_Grouping_Row__mdt codeGroupConfig : codeGroupConfigList){
            temporaryOutputData.put(
            	codeGroupConfig.I_RS_Grouping_Name__c,
                new ERACodeGrouping(
                	codeGroupConfig.I_RS_Grouping_Label__c,
                    codeGroupConfig.I_RS_Grid_Config_File_Name__c,
                    codeGroupConfig.I_RS_Hide_in_breakdown_list_if_empty__c
                )
            );
        }
		System.debug('temporaryOutputData '+temporaryOutputData);
        
		//Construct SOQL query then execute it to populate metrics in result rowa
        String childObject = gridConfig.I_RS_Object_to_aggregate__c;
        String parentLookupReference = gridConfig.I_RS_Parent_Lookup_Reference__c;
        String notDisabledFilter = gridConfig.I_RS_Not_Soft_Deleted_Filter__c;
		String codeQuery = 'SELECT Id, I_RS_Classification_Master__r.I_RS_Type__c FROM '+childObject+
            ' WHERE I_RS_Classification_Master__c != NULL AND '+parentLookupReference+' = \''+parentId+'\' AND '+notDisabledFilter;
            
        System.debug('codeQuery '+codeQuery);
        List<SObject> codeRecords = Database.query(codeQuery);
        
        for (SObject codeRecord : codeRecords){
			System.debug('Code record '+codeRecord);
            String codeType = (String) codeRecord.getSObject('I_RS_Classification_Master__r').get('I_RS_Type__c');
        	ERACodeGrouping codeGroup = temporaryOutputData.get(codeType);
            System.debug('codeGroup '+codeGroup);
            if (codeGroup != null){
                codeGroup.activeCodeCount++;
            }
        }
            
        outputData.addAll(temporaryOutputData.values());
            
        //Construct URL
        String url = getGridPageBaseURL(parentId, gridConfig);

        url += '&c__recordWidgetObjectAPIName='+gridConfig.I_RS_Parent_Object_Name__c;
        url += '&c__recordWidgetFields='+gridConfig.I_RS_Parent_Record_Display_Fields__c;
        url += '&c__recordWidgetCardTitle='+gridConfig.I_RS_Parent_Record_Widget_Header__c;
        
        //Loop through output data and either finalise the clickthrough URL, or remove the row if aplicable 
        for (Integer i=0; i<outputData.size();){
        	ERACodeGrouping row = outputData[i];
            if (row.hideIfEmpty && row.activeCodeCount == 0){
                outputData.remove(i);
            }
            else {
        		row.separateTabURL = url+ '&c__configFile='+row.configFileName;
                i++;
            }
        }
            
        return outputData;
        
    }
    
    
    static String getGridPageBaseURL(Id parentId, I_RS_Editable_Grid_Screen_Config__mdt gridConfig){

        String userTypeCode = [select I_RS_Is_Researcher_User__c from User WHERE Id = :UserInfo.getUserId()].I_RS_Is_Researcher_User__c;
        URL_Variable__c baseURL = URL_Variable__c.getOrgDefaults();
        
        switch on userTypeCode {
        	when '1' {
                if (gridConfig.I_RS_Researcher_Portal_if_applicable__c == 'PRIME Researcher'){
                    return baseURL.I_RS_Researcher_Portal_Base_URL__c+'/'+
                        gridConfig.I_RS_PRIME_Researcher_Page_Name__c+'?c__recordId='+parentId;
                }
                else if (gridConfig.I_RS_Researcher_Portal_if_applicable__c == 'PRIME ERA'){
                    return baseURL.I_RS_ERA_Portal_Base_URL__c+'/'+
                        gridConfig.I_RS_PRIME_Researcher_Page_Name__c+'?c__recordId='+parentId;
                }
                return null;
        	}
            when '0' {
                return baseURL.I_RS_Internal_Base_URL__c+'/lightning/n/'+
                    gridConfig.I_RS_PRIME_Back_Office_Page_Name__c+'?c__recordId='+parentId;
            }
            when else {
                return null;
            }
        }
       	
    }
    
    
    public class ERACodeGrouping{
        
		@AuraEnabled public String categoryLabel;
        @AuraEnabled public Integer activeCodeCount;
        @AuraEnabled public String configFileName;
        
        @AuraEnabled public String separateTabURL;
        
        Boolean hideIfEmpty;
        
        ERACodeGrouping(String categoryLabel, String configFileName, Boolean hideIfEmpty){
            this.categoryLabel = categoryLabel;
            this.configFileName = configFileName;
            this.activeCodeCount = 0;
            this.hideIfEmpty = hideIfEmpty;
        }
        
    }
    
}