force-app/main/default/objects/Apex_Debug_Log__c/Apex_Debug_Log__c.object-meta.xml
<CustomObject>
    <description>Captures results of non-user facing transactions such as Apex endpoints, callouts and asynchronous jobs</description>
    <label>Apex Debug Log</label>
    <nameField>
        <displayFormat>ADL-{00000000}</displayFormat>
        <label>Apex Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Apex_Class_Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Method_Name__c</fullName>
    <label>Apex Class Method Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <description>The invoking class that created the record</description>
    <label>Apex Class Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <description>If an exception occurs, this is the main message</description>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Exception_stack_trace__c.field-meta.xml
<CustomField>
    <fullName>Exception_stack_trace__c</fullName>
    <description>If an exception occurs, this is the stack trace</description>
    <label>Exception stack trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_RM_Applicant__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Applicant__c</fullName>
    <description>This field fetches the number of active &quot;Applicant&quot; affiliation records linked to the contact</description>
    <label>Applicant</label>
    <summaryFilterItems>
        <field>I_RM_Affiliation__c.I_RM_Role__c</field>
        <operation>equals</operation>
        <value>Applicant</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>I_RM_Affiliation__c.I_RM_EndDate__c</field>
        <operation>equals</operation>
        <value></value>
    </summaryFilterItems>
    <summaryForeignKey>I_RM_Affiliation__c.I_RM_Contact__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_RM_Applicant_Email__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Applicant_Email__c</fullName>
    <description>Technical Field. Email address of the applicant. It is copied from Personal email on applicant via a trigger</description>
    <label>Applicant Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_RM_Examiner_Email__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Examiner_Email__c</fullName>
    <description>LTU360-1395 - This field captures external emails of related affiliations to be used in Quick Action for sending email to examiners for Examiner Interaction.</description>
    <label>Examiner Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_RS_Deceased__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Deceased__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deceased</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_ST_Personal_Email__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Personal_Email__c</fullName>
    <description>Created to allow user to store personal email</description>
    <externalId>true</externalId>
    <inlineHelpText>The personal email for this person.</inlineHelpText>
    <label>Student Lead Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_ST_Student_Email__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Student_Email__c</fullName>
    <description>Created to allow student to store their email address</description>
    <externalId>true</externalId>
    <inlineHelpText>The student email for this person.</inlineHelpText>
    <label>Student Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/I_RM_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Part of the remediation project to store different personas</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_IL_Sponsored__c.field-meta.xml
<CustomField>
    <fullName>I_IL_Sponsored__c</fullName>
    <description>Depicts whether a candidate is sponsored</description>
    <label>Sponsored</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Applicant_Id__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Applicant_Id__c</fullName>
    <description>Applicant Identifier</description>
    <label>Applicant Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Calculate_Affiliation_Score__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Calculate_Affiliation_Score__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Technical Field. Depicts if batch process needs to recalculate the affiliation&apos;s Lead Score.</description>
    <label>Calculate Affiliation Score</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Contact__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Contact__c</fullName>
    <description>The person/contact who this Affiliation relates to</description>
    <inlineHelpText>The person this affiliation relates to</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Affiliations</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Data_Source__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Data_Source__c</fullName>
    <description>Technical Field. Global picklist to represent the original source of the record</description>
    <label>Data Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Data_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Email__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Email__c</fullName>
    <description>Depicts Personal Email</description>
    <inlineHelpText>The personal email for this person.</inlineHelpText>
    <label>Personal Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_EndDate__c.field-meta.xml
<CustomField>
    <fullName>I_RM_EndDate__c</fullName>
    <description>Depicts Affiliations End Date.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Enquirer_Type__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Enquirer_Type__c</fullName>
    <description>Depicts how best to describe the Enquirer, Applicable for Student Lead (Dom),Student Applicant (Dom) and Secondary School Rep</description>
    <inlineHelpText>This is the Enquirer Type</inlineHelpText>
    <label>What best describes you?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>I_ST_Enquirer_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_External_Id__c.field-meta.xml
<CustomField>
    <fullName>I_RM_External_Id__c</fullName>
    <description>This field is used as unique id from source system(s)</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Lead_Source_Category__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Lead_Source_Category__c</fullName>
    <description>Depicts the source of the Affiliation</description>
    <label>Source Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>I_ST_Lead_Source_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Lead_Source_sub_category__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Lead_Source_sub_category__c</fullName>
    <description>Depicts the sub source of the Affiliation</description>
    <label>Source Sub Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>I_RM_Lead_Source_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>I_ST_Lead_Source_sub_category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Mobile_Phone__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Mobile_Phone__c</fullName>
    <description>Depicts affiliation&apos;s Mobile Phone number</description>
    <label>Mobile Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Role__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Role__c</fullName>
    <description>This represents the role of the affiliation</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Domestic Lead</fullName>
                <label>Student Lead (Dom)</label>
            </value>
            <value>
                <fullName>Applicant</fullName>
                <label>Student Applicant (Dom)</label>
            </value>
            <value>
                <fullName>La Trobe Staff</fullName>
            </value>
            <value>
                <fullName>School Representative</fullName>
                <label>Secondary School Representative</label>
            </value>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>External Contact</fullName>
            </value>
            <value>
                <fullName>HDR Student</fullName>
                <label>Graduate Researcher</label>
            </value>
            <value>
                <fullName>Student Lead (Int)</fullName>
            </value>
            <value>
                <fullName>Nominated Affiliation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_StartDate__c.field-meta.xml
<CustomField>
    <fullName>I_RM_StartDate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Depicts Affiliations Start Date</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <description>Indicates the status of the Affiliation.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>I_RM_Role__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>I_ST_Contact_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Student_Email__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Student_Email__c</fullName>
    <description>Depicts Students Email address</description>
    <inlineHelpText>The student email for this person.</inlineHelpText>
    <label>Student Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Work_Email__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Work_Email__c</fullName>
    <description>Depicts Work Email address</description>
    <inlineHelpText>Note: Graduate researchers, this is their institutional email (or staff email if they are also staff)</inlineHelpText>
    <label>Work Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_Lead.recordType-meta.xml
<RecordType>
    <fullName>I_RM_Lead</fullName>
    <active>true</active>
    <description>New Domestic Lead who is a prospective student of La Trobe University</description>
    <label>Student Lead (Dom)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/I_RM_Affiliation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Affiliation Settings</label>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_ST_Lead_Scoring__mdt/I_ST_Lead_Scoring__mdt.object-meta.xml
<CustomObject>
    <description>Key Value pairs which are used to calulate a Lead&apos;s score</description>
    <label>Lead Scoring</label>
    <pluralLabel>Lead Scoring</pluralLabel>
</CustomObject>

force-app/main/default/objects/I_ST_Lead_Scoring__mdt/fields/I_ST_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Field_API_Name__c</fullName>
    <label>Field API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/I_RM_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Affiliation</description>
    <label>Affiliation</label>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Data_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Data Migration</fullName>
    </customValue>
    <customValue>
        <fullName>Admin Created</fullName>
    </customValue>
    <customValue>
        <fullName>HR Integration</fullName>
    </customValue>
    <customValue>
        <fullName>Self Nominated</fullName>
    </customValue>
    <customValue>
        <fullName>Finance Integration</fullName>
    </customValue>
    <customValue>
        <fullName>RP Integration</fullName>
    </customValue>
    <customValue>
        <fullName>SIS Integration</fullName>
    </customValue>
    <customValue>
        <fullName>MyPub Integration</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Integration</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
    </customValue>
    <customValue>
        <fullName>SFDC001</fullName>
    </customValue>
    <customValue>
        <fullName>SFDC009</fullName>
    </customValue>
    <customValue>
        <fullName>SFDC010</fullName>
    </customValue>
    <customValue>
        <fullName>SFDC012</fullName>
    </customValue>
    <customValue>
        <fullName>Remediation</fullName>
    </customValue>
    <customValue>
        <fullName>QSES</fullName>
    </customValue>
    <customValue>
        <fullName>Zoho</fullName>
    </customValue>
    <customValue>
        <fullName>Integration</fullName>
        <isActive>false</isActive>
        <label>Integration</label>
    </customValue>
    <customValue>
        <fullName>System</fullName>
        <isActive>false</isActive>
        <label>System</label>
    </customValue>
    <masterLabel>Data Source</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/I_ST_Contact_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Admitted</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And LOA</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Not Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Considered</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Made</fullName>
    </customValue>
    <customValue>
        <fullName>Await Academic Advice</fullName>
    </customValue>
    <customValue>
        <fullName>Await Applicant Comms</fullName>
    </customValue>
    <customValue>
        <fullName>Await Further Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Awaiting Interview</fullName>
    </customValue>
    <customValue>
        <fullName>Await Required Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Escalated</fullName>
    </customValue>
    <customValue>
        <fullName>Make A Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make Alternate Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make An Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Nearing Completion</fullName>
    </customValue>
    <customValue>
        <fullName>Not Processed</fullName>
    </customValue>
    <customValue>
        <fullName>Not Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Lapsed</fullName>
    </customValue>
    <customValue>
        <fullName>Other Preference Offered</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Results</fullName>
    </customValue>
    <customValue>
        <fullName>Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <description>Global value set is created for lead(contact) object ST -51</description>
    <masterLabel>I_ST_Contact_Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/I_ST_Enquirer_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Year 9</fullName>
    </customValue>
    <customValue>
        <fullName>Year 10</fullName>
    </customValue>
    <customValue>
        <fullName>Year 11</fullName>
    </customValue>
    <customValue>
        <fullName>Year 12</fullName>
    </customValue>
    <customValue>
        <fullName>Recent school leaver (18-20)</fullName>
    </customValue>
    <customValue>
        <fullName>Mature age (21+)</fullName>
    </customValue>
    <customValue>
        <fullName>Industry qualified or experienced</fullName>
    </customValue>
    <customValue>
        <fullName>Direct applicant</fullName>
    </customValue>
    <customValue>
        <fullName>University graduate (other uni)</fullName>
    </customValue>
    <customValue>
        <fullName>University graduate (LTU)</fullName>
    </customValue>
    <customValue>
        <fullName>International (outside Australia)</fullName>
    </customValue>
    <customValue>
        <fullName>International (inside Australia)</fullName>
    </customValue>
    <customValue>
        <fullName>TAFE graduate</fullName>
    </customValue>
    <customValue>
        <fullName>Current students (LTU) - UG</fullName>
    </customValue>
    <customValue>
        <fullName>Current students (LTU) - PG</fullName>
    </customValue>
    <customValue>
        <fullName>Current students (other uni) - UG</fullName>
    </customValue>
    <customValue>
        <fullName>Current students (other uni) - PG</fullName>
    </customValue>
    <customValue>
        <fullName>Current student (other) - TAFE</fullName>
    </customValue>
    <customValue>
        <fullName>Current student (LTU) - Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Parent</fullName>
    </customValue>
    <customValue>
        <fullName>Careers advisor / Careers counsellor</fullName>
    </customValue>
    <customValue>
        <fullName>Teacher</fullName>
    </customValue>
    <customValue>
        <fullName>Principal</fullName>
    </customValue>
    <customValue>
        <fullName>International agent</fullName>
    </customValue>
    <customValue>
        <fullName>Business Owner / Contact</fullName>
    </customValue>
    <customValue>
        <fullName>Industry partner</fullName>
    </customValue>
    <customValue>
        <fullName>Industry association</fullName>
    </customValue>
    <customValue>
        <fullName>Accrediting Body</fullName>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <customValue>
        <fullName>Staff</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <description>Created for IST-43</description>
    <masterLabel>I_ST_Enquirer_Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/I_ST_Lead_Source_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Consultation</fullName>
    </customValue>
    <customValue>
        <fullName>Email</fullName>
    </customValue>
    <customValue>
        <fullName>Event</fullName>
    </customValue>
    <customValue>
        <fullName>Live Chat</fullName>
    </customValue>
    <customValue>
        <fullName>Loaded from list</fullName>
    </customValue>
    <customValue>
        <fullName>Other system</fullName>
    </customValue>
    <customValue>
        <fullName>Phone Call</fullName>
    </customValue>
    <customValue>
        <fullName>Physical</fullName>
    </customValue>
    <customValue>
        <fullName>Schools/account</fullName>
    </customValue>
    <customValue>
        <fullName>Social Media</fullName>
    </customValue>
    <customValue>
        <fullName>VTAC preference list</fullName>
    </customValue>
    <customValue>
        <fullName>Web Form</fullName>
    </customValue>
    <customValue>
        <fullName>Webinar</fullName>
    </customValue>
    <customValue>
        <fullName>Migrated</fullName>
    </customValue>
    <customValue>
        <fullName>Subscription Sites</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>QSES</fullName>
    </customValue>
    <customValue>
        <fullName>Student Ambassador</fullName>
    </customValue>
    <description>Created for IST-45</description>
    <masterLabel>I_ST_Lead_Source_Category</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/I_ST_Lead_Source_sub_category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Activity Booking form</fullName>
    </customValue>
    <customValue>
        <fullName>Agency</fullName>
    </customValue>
    <customValue>
        <fullName>Ask a Question form</fullName>
    </customValue>
    <customValue>
        <fullName>Aspire Keep in touch</fullName>
    </customValue>
    <customValue>
        <fullName>Campaign</fullName>
    </customValue>
    <customValue>
        <fullName>Contact Card</fullName>
    </customValue>
    <customValue>
        <fullName>Event Registration</fullName>
    </customValue>
    <customValue>
        <fullName>FAQ Form</fullName>
    </customValue>
    <customValue>
        <fullName>FlexiDirect</fullName>
    </customValue>
    <customValue>
        <fullName>In Person</fullName>
    </customValue>
    <customValue>
        <fullName>Keep in touch form</fullName>
    </customValue>
    <customValue>
        <fullName>Aspire Keep In Touch - Early Entry</fullName>
    </customValue>
    <customValue>
        <fullName>Aspire Keep In Touch - Community</fullName>
    </customValue>
    <customValue>
        <fullName>Aspire Keep In Touch - Early Uni Study</fullName>
    </customValue>
    <customValue>
        <fullName>Aspire Keep In Touch - Achieve Plus</fullName>
    </customValue>
    <customValue>
        <fullName>Interest Page</fullName>
    </customValue>
    <customValue>
        <fullName>Year 11 Early Entry form</fullName>
    </customValue>
    <customValue>
        <fullName>Preferences Checklist</fullName>
    </customValue>
    <customValue>
        <fullName>Migrated</fullName>
    </customValue>
    <customValue>
        <fullName>NGV Event</fullName>
    </customValue>
    <customValue>
        <fullName>Open Day</fullName>
    </customValue>
    <customValue>
        <fullName>Other form</fullName>
    </customValue>
    <customValue>
        <fullName>Other Marketing Activation</fullName>
    </customValue>
    <customValue>
        <fullName>Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Postgraduate</fullName>
    </customValue>
    <customValue>
        <fullName>Public Lecture</fullName>
    </customValue>
    <customValue>
        <fullName>School Publication Order Form</fullName>
    </customValue>
    <customValue>
        <fullName>SIS</fullName>
    </customValue>
    <customValue>
        <fullName>Stay Connected Form</fullName>
    </customValue>
    <customValue>
        <fullName>Undergraduate</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <description>Created for IST-45</description>
    <masterLabel>I_ST_Lead_Source_sub_category</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/I_RM_AffiliationTriggerHelper.cls
/**
─────────────────────────────────────────────────────────────────────────────────────────────────┐
* I_RM_AffiliationTriggerHelper
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* @author Teja Yenduri
* @date 2022-02-18
* 

* * @description : markCalculateAffiliationScoreToTrue method is used to set I_RM_Calculate_Affiliation_Score__c to true
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/
public without sharing class I_RM_AffiliationTriggerHelper {
    public static boolean createLeadFirtRun = true;
    
    //set of strings that require email on affilition to be copied over to related contact's personal email
    public static final Set<String> AFFLIATIONROLENAMESET = new Set<String> {
        'Student Lead (Int)',
        'Domestic Lead'
    };
    /*** Setting CalculateContact Score to true**/
    public static void markCalculateAffiliationScoreToTrue(List<I_RM_Affiliation__c> newAffiliations,
                                                           map<Id,I_RM_Affiliation__c> oldAffiliations,
                                                           boolean isInsertAffiliation){
                                                               boolean isFieldChanged = isInsertAffiliation;
                                                               List<I_RM_Affiliation__c> listUpdateAffiliations = new List<I_RM_Affiliation__c>();
                                                               List<String> objectFields = fetchAllChangedField();
                                                               for(I_RM_Affiliation__c AffiliationRecord: newAffiliations){
                                                                   for(string affiliationField: objectFields){
                                                                       if(AffiliationRecord.get(affiliationField) != oldAffiliations.get(AffiliationRecord.id).get(affiliationField)){
                                                                           isFieldChanged = true;
                                                                           break;
                                                                       }
                                                                   }
                                                                   if(isFieldChanged){                                                                  
                                                                       I_RM_Affiliation__c affiliationToUpdate = new I_RM_Affiliation__c(Id=AffiliationRecord.Id,I_RM_Calculate_Affiliation_Score__c=true);
                                                                       listUpdateAffiliations.add(affiliationToUpdate);
                                                                       isFieldChanged = false;
                                                                   }
                                                               }
                                                               I_RM_AffiliationTriggerHandler.makeAffiliationQualified = false;
                                                               Database.update(listUpdateAffiliations,false);
                                                               I_RM_AffiliationTriggerHandler.runmarkCalculateAffiliationScoreToTrue=true;
                                                               //I_RM_AffiliationTriggerHandler.makeAffiliationQualified = true;
                                                               
                                                               
                                                           }
    
    
    //Method to get all contact field from custom metadataType
    public static List<string> fetchAllChangedField(){
        List<string> affiliationFields = new List<string>();       
        for(I_ST_Lead_Scoring__mdt leadScoreRecord : I_ST_Lead_Scoring__mdt.getAll().values()){
            if(leadScoreRecord.I_ST_Object__c == 'I_RM_Affiliation__c') {
                string affiliationFieldName = '';
                if(leadScoreRecord.I_ST_Field_API_Name__c != ''){
                    affiliationFieldName = leadScoreRecord.I_ST_Field_API_Name__c;
                    affiliationFields.add(affiliationFieldName);
                }   
            }            
        }        
        return affiliationFields;
    }    
    
  /* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
* @author Teja Yenduri
* @date 2022-02-18
    
 LTU360-1231,LTU360-1230: Updating status to Qualified for Active and In active domestic lead affiliations
                           based on applicant status

* ─────────────────────────────────────────────────────────────────────────────────────────────────┘*/

    public static void filterAffiliations(Set<Id> affiContactIds,List<I_RM_Affiliation__c> lstAffiliations, List<String> inactiveStatus){//Only Inactive Affiliations
        
        Map<Id,Integer> mapConIdVSInActivaffiCount = new Map<Id,Integer>();
        Map<Id,Integer> mapConIdVSActivaffiCount = new Map<Id,Integer>();
        Map<Id,Integer> mapConIdVSInactivApplicantCount = new Map<Id,Integer>();
        Id domesticLeadRecordTypeId = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get(GlobalConstants.AFFILIATION_RECORD_TYPE_NAME_LEAD).getrecordTypeId();
        Id applicantRecordtypeId =   Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get(GlobalConstants.AFFILIATION_RECORD_TYPE_NAME_APPLICANT).getrecordTypeId();
       // List<String> inactiveStatus = inactiveStatuses;
        if(!affiContactIds.isEmpty()){
            List<AggregateResult> lstInactiveAggregateResult = [SELECT count(Id)cnt,I_RM_Contact__c
                                                                FROM I_RM_Affiliation__c 
                                                                WHERE I_RM_Contact__c IN: affiContactIds 
                                                                AND RecordTypeId =: domesticLeadRecordTypeId
                                                                AND I_RM_Role__c = 'Domestic Lead'
                                                                AND I_RM_Status__c  IN: inactiveStatus
                                                                GROUP BY I_RM_Contact__c
                                                               ];
            
            for(AggregateResult arr: lstInactiveAggregateResult){
                Integer intCount = (Integer)arr.get('cnt');                   
                Id contactId = (Id)arr.get('I_RM_Contact__c'); 
                mapConIdVSInActivaffiCount.put(contactId,intCount); //conID,1                   
            }
            
            List<AggregateResult> lstActiveAggregateResult = [SELECT count(Id)cnt,I_RM_Contact__c 
                                                              FROM I_RM_Affiliation__c 
                                                              WHERE I_RM_Contact__c IN: affiContactIds //contactIDs 
                                                              AND RecordTypeId =: domesticLeadRecordTypeId
                                                              AND I_RM_Role__c = 'Domestic Lead'
                                                              AND I_RM_Status__c NOT IN: inactiveStatus
                                                              GROUP BY I_RM_Contact__c                
                                                             ];            
           
            for(AggregateResult arr: lstActiveAggregateResult){
                Integer intCount = (Integer)arr.get('cnt');                   
                Id contactId = (Id)arr.get('I_RM_Contact__c'); //conID,1 Or conID,0
                mapConIdVSActivaffiCount.put(contactId,intCount);                    
            }
            
            
            List<AggregateResult> lstInactiveApplicantAggregateResult =[SELECT count(Id)cnt,I_RM_Contact__c 
                                                              FROM I_RM_Affiliation__c 
                                                              WHERE I_RM_Contact__c IN: affiContactIds //contactIDs 
                                                              //AND RecordTypeId =: applicantRecordtypeId
                                                              AND I_RM_Role__c IN  ('Applicant','HDR Student','Student')
                                                              AND (I_RM_EndDate__c = null
                                                              OR I_RM_Status__c NOT IN: inactiveStatus)
                                                              GROUP BY I_RM_Contact__c];
            
            
            if(lstInactiveApplicantAggregateResult.size() == 0){
                for(Id contactId : affiContactIds){
                    mapConIdVSInactivApplicantCount.put(contactId,0);
                }
            }
            else{
                for(AggregateResult arr: lstInactiveApplicantAggregateResult){
                    Integer intCount = (Integer)arr.get('cnt');                   
                    Id contactId = (Id)arr.get('I_RM_Contact__c'); //conID,1 Or conID,0
                    mapConIdVSInactivApplicantCount.put(contactId,intCount);                    
                }
            }
            //for loop on currently updated / inserted affiliation
            List<Id> lstContactForAllAffiliation = new List<Id>();
            List<Id> lstContactForActiveAffiliation = new List<Id>();
            for(I_RM_Affiliation__c newAffiliation :lstAffiliations){
                if(mapConIdVSInActivaffiCount.get(newAffiliation.I_RM_Contact__c) > 0 
                   && ( mapConIdVSActivaffiCount.isEmpty() || mapConIdVSActivaffiCount.get(newAffiliation.I_RM_Contact__c) == 0)
                  && mapConIdVSInactivApplicantCount.get(newAffiliation.I_RM_Contact__c) == 0){
                   
                    lstContactForAllAffiliation.add(newAffiliation.I_RM_Contact__c);
                }
                else if(mapConIdVSActivaffiCount.get(newAffiliation.I_RM_Contact__c) > 0  
                        && mapConIdVSInactivApplicantCount.get(newAffiliation.I_RM_Contact__c) == 0){
                  
                    lstContactForActiveAffiliation.add(newAffiliation.I_RM_Contact__c);                        
                    
                }
                else if(mapConIdVSInActivaffiCount.get(newAffiliation.I_RM_Contact__c) == 0
                        && mapConIdVSInactivApplicantCount.get(newAffiliation.I_RM_Contact__c) == 0){
                    
                }
                else if(mapConIdVSInActivaffiCount.get(newAffiliation.I_RM_Contact__c) > 0 
                        && mapConIdVSActivaffiCount.get(newAffiliation.I_RM_Contact__c) > 0
                       && mapConIdVSInactivApplicantCount.get(newAffiliation.I_RM_Contact__c) == 0){
                    
                }
            }
            
            
           
            if(!lstContactForAllAffiliation.isEmpty()){   
                
                inactiveDomesticLeadAffiliationUpdate(lstContactForAllAffiliation);
            }
            if(!lstContactForActiveAffiliation.isEmpty()){
                
                activeDomesticLeadAffiliationUpdate(lstContactForActiveAffiliation, inactiveStatus);
            }
        }        
    }
    public static void inactiveDomesticLeadAffiliationUpdate(List<Id> lstContactId){//contact found all or any one domestic lead affiliation inactive
       
        Map<Id,I_RM_Affiliation__c> mapConIdVSaffiliation = new Map<Id,I_RM_Affiliation__c>();
        List<I_RM_Affiliation__c> lstAffiliationsToupdate = new List<I_RM_Affiliation__c>();
        List<I_RM_Affiliation__c> lstLatestAffiliation = [SELECT Id,createddate,I_RM_Contact__c,I_RM_Role__c,I_RM_Status__c FROM I_RM_Affiliation__c 
                                                          WHERE I_RM_Role__c = 'Domestic Lead'
                                                          AND I_RM_Contact__c IN:lstContactId ORDER BY Createddate desc];//ConId1,Affiliation1,ContID1,Affiliation2
        
        
        for(I_RM_Affiliation__c objInstance: lstLatestAffiliation){
            if(!mapConIdVSaffiliation.containsKey(objInstance.I_RM_Contact__c)){            
            	mapConIdVSaffiliation.put(objInstance.I_RM_Contact__c,objInstance);
            }                       
        }
        lstAffiliationsToupdate.addAll(mapConIdVSaffiliation.values());
       updateLeadAffiliation(lstAffiliationsToupdate);        
    }
    public static void activeDomesticLeadAffiliationUpdate(List<Id> lstContactId, List<String> inactiveStatus){
        
        //List<String> inactiveStatus = [SELECT I_RM_Status__c FROM I_RM_Affiliation_Settings__c WHERE Name =:GlobalConstants.I_RM_AFFILIATION_SETTINGS].I_RM_Status__c.split(',');
        inactiveStatus.add('Qualified');
        List<I_RM_Affiliation__c> lstactiveAffiliations = [SELECT  Id,createddate,I_RM_Contact__c,I_RM_Role__c,I_RM_Status__c FROM I_RM_Affiliation__c 
                                                           WHERE I_RM_Contact__c IN: lstContactId
                                                           AND I_RM_Role__c = 'Domestic Lead' 
                                                           AND  I_RM_Status__c NOT IN: inactiveStatus];//1 or more records with not qualified status.
      
        if(!lstactiveAffiliations.isEmpty()){
            updateLeadAffiliation(lstactiveAffiliations);
        }
    }
    public static void updateLeadAffiliation(List<I_RM_Affiliation__c> lstAffiliationsToupdate){
        List<I_RM_Affiliation__c> lstAffiToUpdate = new List<I_RM_Affiliation__c>(); 
        
        for(I_RM_Affiliation__c objupdateAffi:lstAffiliationsToupdate){
            I_RM_Affiliation__c objNewAffiliation = new I_RM_Affiliation__c(Id = objupdateAffi.Id);            
            objNewAffiliation.I_RM_Status__c = 'Qualified'; 
            lstAffiToUpdate.add(objNewAffiliation);
            
        }         
        
        if(!lstAffiToUpdate.isEmpty() && schema.SObjectType.I_RM_Affiliation__c.isCreateable() && schema.SObjectType.I_RM_Affiliation__c.isUpdateable()){
         //   I_RM_AffiliationTriggerHandler.makeAffiliationQualified = false;
            upsert lstAffiToUpdate;
            I_RM_AffiliationTriggerHandler.makeAffiliationQualified = true;            
        }
        
    }
    
 /* LTU360-1229*/
 public static void createLeadAffliations(List<I_RM_Affiliation__c> inactiveAffliationsList, List<String> inactiveStatus, String afflType){

    List<Apex_Debug_Log__c> errorLogs = new List<Apex_Debug_Log__c>();
    Set<Id> inactiveAffliationsIdList = new Set<Id>();
    Set<Id> contactIds = New Set<Id>();
    for(I_RM_Affiliation__c affl : inactiveAffliationsList){
        inactiveAffliationsIdList.add(affl.Id);
        contactIds.add(affl.I_RM_Contact__c);
    }
    
    if(inactiveAffliationsIdList.size() > 0){
        Id applicantRecordtypeId =   Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get(GlobalConstants.AFFILIATION_RECORD_TYPE_NAME_APPLICANT).getrecordTypeId();
        List<AggregateResult> lstInactiveApplicantAggregateResult = New List<AggregateResult>();
        lstInactiveApplicantAggregateResult =[SELECT count(Id)cnt,I_RM_Contact__c 
                                                            FROM I_RM_Affiliation__c 
                                                            WHERE I_RM_Contact__c IN: contactIds //contactIDs 
                                                            //AND RecordTypeId =: applicantRecordtypeId
                                                            AND I_RM_Role__c IN  ('Applicant','HDR Student','Student')
                                                            AND (I_RM_EndDate__c = null
                                                            OR I_RM_Status__c NOT IN: inactiveStatus)
                                                            GROUP BY I_RM_Contact__c];
                                                                                                          
        if(lstInactiveApplicantAggregateResult.size() == 0){
            Set<Id> contactIdsWithoutLeads = New Set<Id>();
            if(afflType == 'Applicant'){
                for(Contact con: [SELECT ID, name,I_RM_Applicant__c FROM contact WHERE ID NOT IN (SELECT I_RM_Contact__c FROM I_RM_Affiliation__c WHERE I_RM_Role__c = 'Domestic Lead' AND I_RM_Contact__c IN: contactIds) AND ID IN: contactIds]){
                    contactIdsWithoutLeads.add(con.id);
                }
            }else if(afflType == 'Student' || afflType == 'HDR Student'){
                for(Contact con: [SELECT ID, name,I_RM_Applicant__c FROM contact WHERE ID NOT IN (SELECT I_RM_Contact__c FROM I_RM_Affiliation__c WHERE I_RM_Role__c = 'Domestic Lead' AND I_RM_Status__c Not IN:inactiveStatus AND I_RM_Contact__c IN: contactIds) AND ID IN: contactIds]){
                    contactIdsWithoutLeads.add(con.id);
                }
            }
            if(contactIdsWithoutLeads.size() > 0){
                List<I_RM_Affiliation__c> afflList = new List<I_RM_Affiliation__c>();
                String fieldsNames = '';

                for (Schema.SObjectField sObjectField : Schema.getGlobalDescribe().get('I_RM_Affiliation__c').getDescribe().fields.getMap().values()) {
                    fieldsNames += sObjectField.getDescribe().getName() + ',';
                }
                fieldsNames = fieldsNames.removeEnd(',');
                afflList = Database.query('SELECT ' + fieldsNames + ' ' + ' from I_RM_Affiliation__c WHERE Id IN : inactiveAffliationsIdList AND I_RM_Contact__r.I_RS_Deceased__c = False');
                Id devRecordTypeId = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Lead').getrecordTypeId();
                List<I_RM_Affiliation__c> newLeadAfflsList = New List<I_RM_Affiliation__c>();

                for(I_RM_Affiliation__c affls : afflList){
                    if(affls.I_RM_Email__c != null || affls.I_RM_Mobile_Phone__c != null){
                        if(contactIdsWithoutLeads.contains(affls.I_RM_Contact__c)){
                            I_RM_Affiliation__c afflsRec = new I_RM_Affiliation__c();
                            afflsRec = affls.clone(false, true, false, false);
                            afflsRec.I_RM_Status__c = 'Qualified';
                            afflsRec.I_RM_Role__c = 'Domestic Lead';
                            afflsRec.I_RM_External_Id__c = null;
                            afflsRec.I_RM_Applicant_Id__c = null;
                            afflsRec.I_RM_EndDate__c = null;
                            afflsRec.I_RM_Email__c = affls.I_RM_Email__c;
                            afflsRec.I_RM_Data_Source__c = 'Salesforce';
                            afflsRec.I_RM_StartDate__c = System.today();
                            afflsRec.RecordTypeId = devRecordTypeId;
                            afflsRec.I_RM_Lead_Source_Category__c = 'Other system';
                            if(afflType == 'Student' || afflType == 'HDR Student' ){
                                afflsRec.I_RM_Lead_Source_sub_category__c = 'SIS';
                                afflsRec.I_RM_Enquirer_Type__c = 'Other';
                            }else if(afflType == 'Applicant'){
                                afflsRec.I_RM_Lead_Source_sub_category__c = 'FlexiDirect';
                            }
                            newLeadAfflsList.add(afflsRec);
                        }
                    }else{
                        errorLogs.add(new Apex_Debug_Log__c(
                        Apex_Class_Name__c = 'I_RM_AffiliationTriggerHelper',
                        Apex_Class_Method_Name__c = 'createLeadAffliations',
                        Exception_message__c = 'affiliation email or mobile phone is blank',
                        Exception_Stack_Trace__c = null));
                    }
                }
                if(!newLeadAfflsList.isEmpty()){
                   // I_RM_AffiliationTriggerHandler.makeAffiliationQualified = true;
                    Insert newLeadAfflsList;
                }
                if (!errorLogs.isEmpty() && errorLogs != Null)
                    insert errorLogs;  
                }
            }
        }
    }

    
     public static void updateContactEmailfields(List<I_RM_Affiliation__c> listOfAffliations, Map<Id,I_RM_Affiliation__c> oldAffliations){
        Map<Id,Contact> contactsToBeUpdated = New Map<Id,Contact>();
        for(I_RM_Affiliation__c affls :(List<I_RM_Affiliation__c>) listOfAffliations){
            I_RM_Affiliation__c oldAfl;
            oldAfl = Trigger.oldMap != null ? (I_RM_Affiliation__c)Trigger.oldMap.get(affls.Id) : null;
            String workEmail;
            String studentEmail;
            String email;
            if(oldAfl != null){
                workEmail = oldAfl.I_RM_Work_Email__c;
                studentEmail = oldAfl.I_RM_Student_Email__c;
                email = oldAfl.I_RM_Email__c;
            }else{
                workEmail = null;
                studentEmail = null;
                email = null; 
            }
            Contact cont = New Contact();
            if((affls.I_RM_Work_Email__c != null && affls.I_RM_Work_Email__c != workEmail) && (affls.I_RM_Role__c == 'La Trobe Staff' || affls.I_RM_Role__c == 'HDR Student')){
                cont.Email = affls.I_RM_Work_Email__c;
            }
            if((affls.I_RM_Student_Email__c != null && affls.I_RM_Student_Email__c != studentEmail) && (affls.I_RM_Role__c == 'Student' || affls.I_RM_Role__c == 'HDR Student')){
                cont.I_ST_Student_Email__c = affls.I_RM_Student_Email__c;
            }
            if(affls.I_RM_Email__c != null && affls.I_RM_Email__c != email) {
                if(affls.I_RM_Role__c == 'Applicant'){
                    cont.I_RM_Applicant_Email__c = affls.I_RM_Email__c;
                }else if(AFFLIATIONROLENAMESET.contains(affls.I_RM_Role__c)){
                    cont.I_ST_Personal_Email__c = affls.I_RM_Email__c;
                }
            }
            cont.Id = affls.I_RM_Contact__c;
            contactsToBeUpdated.put(cont.id,cont);
        }
        if(!contactsToBeUpdated.isEmpty()){
            update contactsToBeUpdated.values();
        }
    }
    
    /*LTU360-1232  */
    public static void updateActiveAffiliation(List<I_RM_Affiliation__c> afflist, List<String> csvaluelist){//Applicant Active only
      //  List<String> csvaluelist = [SELECT I_RM_Status__c FROM I_RM_Affiliation_Settings__c WHERE Name =:GlobalConstants.I_RM_AFFILIATION_SETTINGS].I_RM_Status__c.split(',');
        Set<ID> CnctID = new Set<ID>();
        List<I_RM_Affiliation__c> updateAffRecord=new List<I_RM_Affiliation__c>();
        for(I_RM_Affiliation__c a : afflist){
            CnctID.add(a.I_RM_Contact__c);
        }
        for(I_RM_Affiliation__c af:[SELECT Id,I_RM_Status__c,I_RM_EndDate__c from I_RM_Affiliation__c WHERE I_RM_Contact__c IN: CnctID AND I_RM_Role__c = 'Domestic Lead' AND I_RM_Status__c !='Inactive']){
           af.I_RM_Status__c='Inactive';
           af.I_RM_EndDate__c =system.today();
            updateAffRecord.add(af);
        }
        if(updateAffRecord.size()>0 && schema.SObjectType.I_RM_Affiliation__c.isUpdateable()){
           // I_RM_AffiliationTriggerHandler.makeAffiliationQualified = false; //true          
            update updateAffRecord;
            I_RM_AffiliationTriggerHandler.makeLeadInactive = true;
        }
    }     

    /*
    *@author Rahul Kumar
    *@date 23/03/2022
    *@description - LTU360-1251 : Method to Update Active Applicant record when Student becomes Admitted And Enrolled 
    */
  /*  public static void updateActiveApplicant(List<I_RM_Affiliation__c> afflist, List<String> csvaluelist){
      //  List<String> csvaluelist = [SELECT I_RM_Status__c FROM I_RM_Affiliation_Settings__c WHERE Name =:GlobalConstants.I_RM_AFFILIATION_SETTINGS].I_RM_Status__c.split(',');
        Set<ID> CnctID = new Set<ID>();
        List<I_RM_Affiliation__c> updateAffRecord=new List<I_RM_Affiliation__c>();
        for(I_RM_Affiliation__c a : afflist){
            CnctID.add(a.I_RM_Contact__c);
        }
        for(I_RM_Affiliation__c af:[SELECT Id,I_RM_Status__c from I_RM_Affiliation__c WHERE I_RM_Contact__c IN: CnctID AND I_RM_Role__c = 'Applicant' AND I_RM_Status__c !='Inactive']){
            af.I_RM_Status__c='Inactive';
            updateAffRecord.add(af);
        }
        if(updateAffRecord.size()>0 && schema.SObjectType.I_RM_Affiliation__c.isUpdateable()){
            update updateAffRecord;
            I_RM_AffiliationTriggerHandler.makeApplicantInactive = true;
        }
    }*/

    //LTU360-1407
    public static void updateContactExternalEmal(List<I_RM_Affiliation__c> listOfAffliations, List<String> inactiveStatus){

        List<Id> contactIds = New List<Id>();
        Map<Id, List<I_RM_Affiliation__c>> mapOfContactIdAndListOfAffls = New Map<Id, List<I_RM_Affiliation__c>>();

        for(I_RM_Affiliation__c affls:listOfAffliations){
            contactIds.add(affls.I_RM_Contact__c);
        }

        List<I_RM_Affiliation__c> afflList = New List<I_RM_Affiliation__c>();

        afflList = [Select Id, I_RM_Work_Email__c, I_RM_Contact__c From I_RM_Affiliation__c Where I_RM_Contact__c IN: contactIds AND I_RM_Role__c = 'External Contact' AND I_RM_Status__c NOT IN: inactiveStatus];

        if(afflList.size() > 0){
            for(I_RM_Affiliation__c affl : afflList){

                    if(!mapOfContactIdAndListOfAffls.isEmpty() && mapOfContactIdAndListOfAffls.containsKey(affl.I_RM_Contact__c))
                    mapOfContactIdAndListOfAffls.get(affl.I_RM_Contact__c).add(affl);
                    else
                    mapOfContactIdAndListOfAffls.put(affl.I_RM_Contact__c,new List<I_RM_Affiliation__c>{affl});
            }
        }
        List<Contact> contactsToUpdate = New List<Contact>();
        if(mapOfContactIdAndListOfAffls.size() > 0){
            List<I_RM_Affiliation__c> affslList = New List<I_RM_Affiliation__c>();
            for(Id conactId : mapOfContactIdAndListOfAffls.keySet()){
                affslList = mapOfContactIdAndListOfAffls.get(conactId);
                if(affslList.size() > 0){
                    Contact cnt = New Contact();
                    cnt.I_RM_Examiner_Email__c = concatinateEmails(affslList);
                    cnt.Id = conactId;
                    contactsToUpdate.add(cnt);
                }
            }
        }
        if(contactsToUpdate.size() >0){
            update contactsToUpdate;
        }
    }

    public static String concatinateEmails(List<I_RM_Affiliation__c> listOfAffliations){

        String emails;
        for(I_RM_Affiliation__c aff : listOfAffliations){
            if(aff.I_RM_Work_Email__c !=null && aff.I_RM_Work_Email__c!= ''){
                if(emails != null){
                    emails = emails + aff.I_RM_Work_Email__c+';';
                }                
                if(emails == null){
                    emails = aff.I_RM_Work_Email__c+';';
                }
            }
        }
        emails = emails.removeEnd(';');
        return emails;
    }

    /**
     * @description LTU360-2246 - Set the sponsored field based on 
     *                            Contact attributes in before insert/update context
     * @param triggerNewList - List of new items in trigger
     * @param triggerOldMap - map of old trigger items
    */
    public static List<I_RM_Affiliation__c> setSponsoredFieldValue( 
        List<I_RM_Affiliation__c> triggerNewList,
        Map<Id, I_RM_Affiliation__c> triggerOldMap
    ) {
        if( !GlobalConstants.INTENDEDFUNDINGSRCSET.isEmpty() && 
            !GlobalConstants.COUNTRYOFCITIZENSHIPSET.isEmpty()
        ) {
            List<I_RM_Affiliation__c> affListToUpdate = new List<I_RM_Affiliation__c>();
            Set<Id> contactIdSet = new Set<Id>();
            //create a map of affilitions that require an update on sponsored field
            for( I_RM_Affiliation__c aff : triggerNewList ) 
            {
                if( 
                    triggerOldMap.isEmpty() ||
                    ( aff.I_IL_Sponsored__c == triggerOldMap.get(aff.Id).I_IL_Sponsored__c && 
                    aff.I_IL_Intended_Funding_Source__c != triggerOldMap.get(aff.Id).I_IL_Intended_Funding_Source__c
                    )
                ) {
                    affListToUpdate.add(aff);
                    contactIdSet.add(aff.I_RM_Contact__c);
                }
            }
            if(!contactIdSet.isEmpty() && 
            Schema.SObjectType.Contact.Fields.I_RS_Citizenship__c.isAccessible()) 
            {            
                Map<Id, Contact> contactMap = new Map<Id, Contact>(
                    [SELECT Id, I_RS_Citizenship__c  
                    FROM Contact 
                    WHERE Id IN :contactIdSet 
                    WITH SECURITY_ENFORCED
                    ]
                );
                Contact con;
                for( I_RM_Affiliation__c aff : affListToUpdate ) {
                    con = contactMap.get(aff.I_RM_Contact__c);
                    if( ( String.isBlank(aff.I_IL_Intended_Funding_Source__c) ||
                          GlobalConstants.INTENDEDFUNDINGSRCSET.contains(aff.I_IL_Intended_Funding_Source__c)
                        ) && 
                        GlobalConstants.COUNTRYOFCITIZENSHIPSET.contains(con.I_RS_Citizenship__c)
                    ) {
                        aff.I_IL_Sponsored__c = 'Yes';
                    }
                    else {
                        aff.I_IL_Sponsored__c = 'No';
                    }
                }
            }
            return affListToUpdate;
        }
        return null;
    }
}