force-app/main/default/objects/Apex_Debug_Log__c/Apex_Debug_Log__c.object-meta.xml
<CustomObject>
    <description>Captures results of non-user facing transactions such as Apex endpoints, callouts and asynchronous jobs</description>
    <label>Apex Debug Log</label>
    <nameField>
        <displayFormat>ADL-{00000000}</displayFormat>
        <label>Apex Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Apex_Class_Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Method_Name__c</fullName>
    <label>Apex Class Method Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <description>The invoking class that created the record</description>
    <label>Apex Class Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <description>If an exception occurs, this is the main message</description>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Exception_stack_trace__c.field-meta.xml
<CustomField>
    <fullName>Exception_stack_trace__c</fullName>
    <description>If an exception occurs, this is the stack trace</description>
    <label>Exception stack trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/I_RM_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Part of the remediation project to store different personas</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <description>Indicates the status of the Affiliation.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>I_RM_Role__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>I_ST_Contact_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/I_RM_Affiliation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Affiliation Settings</label>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_ST_Application__c/I_ST_Application__c.object-meta.xml
<CustomObject>
    <description>Custom object to show under Related list of contact as part of IST-240</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_ST_Application__c/fields/I_RM_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Facilitate relationship with the Affiliation object</description>
    <label>Affiliation</label>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/I_ST_Application__c/fields/I_ST_Application_Census_Date__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Application_Census_Date__c</fullName>
    <formula>I_ST_Course_Availability__r.I_ST_Application_Census_Date__c</formula>
    <label>Application Census Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/I_ST_Application__c/fields/I_ST_Application_Lapsed__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Application_Lapsed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Added for IST-457</description>
    <label>Application Lapsed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/I_ST_Application__c/fields/I_ST_Application_Status__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Application_Status__c</fullName>
    <description>for IST-164</description>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alternate offer considered</fullName>
            </value>
            <value>
                <fullName>Alternate Offer Declined</fullName>
            </value>
            <value>
                <fullName>Alternate offer made</fullName>
            </value>
            <value>
                <fullName>Application in error</fullName>
            </value>
            <value>
                <fullName>Application Withdrawn</fullName>
            </value>
            <value>
                <fullName>Await academic advice</fullName>
            </value>
            <value>
                <fullName>Await applicant comms</fullName>
            </value>
            <value>
                <fullName>Await further doco</fullName>
            </value>
            <value>
                <fullName>Awaiting interview</fullName>
            </value>
            <value>
                <fullName>Await required doco</fullName>
            </value>
            <value>
                <fullName>Conditional offer</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Make a conditional offer</fullName>
            </value>
            <value>
                <fullName>Make alternate offer</fullName>
            </value>
            <value>
                <fullName>Make an offer</fullName>
            </value>
            <value>
                <fullName>Not processed</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Offer Rescinded</fullName>
            </value>
            <value>
                <fullName>Other Preference offered</fullName>
            </value>
            <value>
                <fullName>Pending results</fullName>
            </value>
            <value>
                <fullName>Rejected &amp; Referred</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
            <value>
                <fullName>Unsuccessful, not notified</fullName>
            </value>
            <value>
                <fullName>Withdrawn preference</fullName>
            </value>
            <value>
                <fullName>Admitted And Not Enrolled</fullName>
            </value>
            <value>
                <fullName>Admitted And Enrolled</fullName>
            </value>
            <value>
                <fullName>Offer Admitted</fullName>
            </value>
            <value>
                <fullName>Offer Accepted</fullName>
            </value>
            <value>
                <fullName>Offer</fullName>
            </value>
            <value>
                <fullName>Offer Deferred</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/I_RM_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Affiliation</description>
    <label>Affiliation</label>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/I_ST_Contact_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Admitted</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And LOA</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Not Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Considered</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Made</fullName>
    </customValue>
    <customValue>
        <fullName>Await Academic Advice</fullName>
    </customValue>
    <customValue>
        <fullName>Await Applicant Comms</fullName>
    </customValue>
    <customValue>
        <fullName>Await Further Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Awaiting Interview</fullName>
    </customValue>
    <customValue>
        <fullName>Await Required Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Escalated</fullName>
    </customValue>
    <customValue>
        <fullName>Make A Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make Alternate Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make An Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Nearing Completion</fullName>
    </customValue>
    <customValue>
        <fullName>Not Processed</fullName>
    </customValue>
    <customValue>
        <fullName>Not Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Lapsed</fullName>
    </customValue>
    <customValue>
        <fullName>Other Preference Offered</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Results</fullName>
    </customValue>
    <customValue>
        <fullName>Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <description>Global value set is created for lead(contact) object ST -51</description>
    <masterLabel>I_ST_Contact_Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/I_ST_ApplicationTriggerHandler.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* I_ST_Application__c Trigger Handler Class
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Vanita Walia
* @version        2.0
* @created        17/03/2022
* @description    Handler class to filter the records based on trigger events and call the helper methods for action 
*/
public with sharing class I_ST_ApplicationTriggerHandler {
    // Boolean variable to avoid recursion so that helper method only execute once
    public static Boolean FirstRun = false;        
    public static List<Apex_Debug_Log__c> errorLogs = new List<Apex_Debug_Log__c>();
    
    public static void execute() {
        //variable initialization
        map<Id,I_ST_Application__c> mapOldApplication = (map<Id,I_ST_Application__c>)Trigger.oldMap;
        Map<Id, List<I_ST_Application__c>> affAppListMap = new Map<Id, List<I_ST_Application__c>>();
        List<String> InactiveStatus = new List<String>();
        Set<Id> affiliationIds = new Set<Id>();
        DateTime todayDate = System.today();               
                
        if(Trigger.isAfter) {
            // By Vanita Walia as part of LTU360-1324 
                if(Trigger.isInsert || Trigger.isUpdate) {
                try{
                    if(!FirstRun){
                        // Find the application with affiliation where status is changed or lapsed value is updated 
                        // and store the affiliation Ids in set 
                		for(I_ST_Application__c app : (List<I_ST_Application__c>)Trigger.new){
                    		if(app.I_RM_Affiliation__c != Null && (Trigger.isInsert  ||  (Trigger.isUpdate 
                                && (app.I_ST_Application_Status__c != mapOldApplication.get(app.Id).I_ST_Application_Status__c
                                || app.I_ST_Application_Lapsed__c != mapOldApplication.get(app.Id).I_ST_Application_Lapsed__c)))){
                        			affiliationIds.add(app.I_RM_Affiliation__c);  
                        	}
                		}
                   
                		
                		// find all the applications with same affiliation as of current record	
                		if(!affiliationIds.isEmpty()){
                            //fetch the inactive status values for application from the custom settings
        					InactiveStatus = [SELECT I_RM_Status__c FROM I_RM_Affiliation_Settings__c WHERE Name =:GlobalConstants.I_RM_INACTIVE_APPLICATION_SETTINGS].I_RM_Status__c.split(';');
        					 
                            
                			List<I_ST_Application__c> appList = [Select Id,I_RM_Affiliation__c,I_ST_Application_Status__c from I_ST_Application__c
                        		                           			where I_RM_Affiliation__c in:affiliationIds
                            		                       			AND I_ST_Application_Lapsed__c = False
                                		                   			AND I_ST_Application_Status__c NOT IN: InactiveStatus
                                    		                		AND (I_ST_Application_Census_Date__c >=: todayDate 
                                        		            		OR I_ST_Application_Census_Date__c = NULL) ORDER BY I_ST_Application_Status__c DESC];
                                            		       			
                			
                			if(appList.size()>0){
                    			for(I_ST_Application__c exApp : appList){
                            		// If any application related to affiliation record found put them in map
                        			
                            			if(!affAppListMap.isEmpty() && affAppListMap.containsKey(exApp.I_RM_Affiliation__c))
                                			affAppListMap.get(exApp.I_RM_Affiliation__c).add(exApp);
                            			else
                            				affAppListMap.put(exApp.I_RM_Affiliation__c,new List<I_ST_Application__c>{exApp});
                            	 		
                                    // remove the affiliation Id from the set where application is not the current record
                                     	affiliationIds.remove(exApp.I_RM_Affiliation__c);
                        			
                    			}
                			}
                    		
                    		// Perform the action on remaining affiliations where no other application found meeting criteria
                    		if(!affiliationIds.isEmpty() && !System.isBatch()){ 
                        		// Call helper class method to update affiliation status to Inactive
                    			I_ST_ApplicationTriggerHelper.updateAffiliationToInactive(affiliationIds);
                			}
                            
                            if(!affAppListMap.isEmpty() && !System.isBatch()){
                                I_ST_ApplicationTriggerHelper.updateAffiliationStatus(affAppListMap);
                            }
            			}                        
        			}
                }
                catch(Exception ex){
                   
                   	errorLogs.add(new Apex_Debug_Log__c(Apex_Class_Name__c = 'I_ST_ApplicationTriggerHandler',Apex_Class_Method_Name__c = 'execute Method',Exception_message__c = ex.getMessage(),Exception_Stack_Trace__c = ex.getStackTraceString()));
               	}
               	finally {
           			if (!errorLogs.isEmpty() && errorLogs != Null)
               			insert errorLogs;            		
        		}
    		}
        }	   
	}
}