force-app/main/default/objects/Apex_Debug_Log__c/Apex_Debug_Log__c.object-meta.xml
<CustomObject>
    <description>Captures results of non-user facing transactions such as Apex endpoints, callouts and asynchronous jobs</description>
    <label>Apex Debug Log</label>
    <nameField>
        <displayFormat>ADL-{00000000}</displayFormat>
        <label>Apex Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Apex_Class_Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Method_Name__c</fullName>
    <label>Apex Class Method Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <description>The invoking class that created the record</description>
    <label>Apex Class Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <description>If an exception occurs, this is the main message</description>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Exception_stack_trace__c.field-meta.xml
<CustomField>
    <fullName>Exception_stack_trace__c</fullName>
    <description>If an exception occurs, this is the stack trace</description>
    <label>Exception stack trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/I_RM_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Part of the remediation project to store different personas</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Contact__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Contact__c</fullName>
    <description>The person/contact who this Affiliation relates to</description>
    <inlineHelpText>The person this affiliation relates to</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Affiliations</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Role__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Role__c</fullName>
    <description>This represents the role of the affiliation</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Domestic Lead</fullName>
                <label>Student Lead (Dom)</label>
            </value>
            <value>
                <fullName>Applicant</fullName>
                <label>Student Applicant (Dom)</label>
            </value>
            <value>
                <fullName>La Trobe Staff</fullName>
            </value>
            <value>
                <fullName>School Representative</fullName>
                <label>Secondary School Representative</label>
            </value>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>External Contact</fullName>
            </value>
            <value>
                <fullName>HDR Student</fullName>
                <label>Graduate Researcher</label>
            </value>
            <value>
                <fullName>Student Lead (Int)</fullName>
            </value>
            <value>
                <fullName>Nominated Affiliation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/L_PR_Idea__c/L_PR_Idea__c.object-meta.xml
<CustomObject>
    <description>Idea/ Lead object being used for PRM Application</description>
    <label>PRM Lead</label>
    <nameField>
        <label>Lead Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PRM Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/L_PR_Idea__c/fields/L_PR_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Affiliations</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>I_RM_Affiliation__c.I_RM_Role__c</field>
            <operation>equals</operation>
            <value>La Trobe Staff, Secondary School Representative, External Contact</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>PRM Ideas</relationshipLabel>
    <relationshipName>PRM_Ideas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/L_PR_Idea__c/fields/L_PR_Closed_Reason__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Closed_Reason__c</fullName>
    <description>Text field to describe why the Lead/Idea did not qualify/succeed</description>
    <label>Closed Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/L_PR_Opportunity_Affiliation_Relation__c/L_PR_Opportunity_Affiliation_Relation__c.object-meta.xml
<CustomObject>
    <description>Opportunity Affiliation Relationship</description>
    <label>Opportunity Affiliation Relationship</label>
    <nameField>
        <displayFormat>OA-{00000}</displayFormat>
        <label>Opportunity Affiliation Relationship Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Affiliation Relationship</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/L_PR_Opportunity_Affiliation_Relation__c/fields/L_PR_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Affiliation__c</fullName>
    <label>Affiliation</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>You can only select La Trobe Staff or External Contact Affiliation</errorMessage>
        <filterItems>
            <field>I_RM_Affiliation__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>La Trobe Staff</value>
        </filterItems>
        <filterItems>
            <field>I_RM_Affiliation__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>External Contact</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>Opportunity Affiliation Relationship</relationshipLabel>
    <relationshipName>Opportunity_Affiliation_Relationship</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/L_PR_Opportunity_Affiliation_Relation__c/fields/L_PR_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Opportunity__c</fullName>
    <label>Opportunity Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You can only select PRM Opportunity</errorMessage>
        <filterItems>
            <field>Opportunity.RecordType.Name</field>
            <operation>equals</operation>
            <value>PRM Opportunity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Affiliation Relationship</relationshipLabel>
    <relationshipName>Opportunity_Affiliation_Relationship</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/L_PR_Closed_Reason__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Closed_Reason__c</fullName>
    <description>Reason for closed lost opportunity</description>
    <label>Closed Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/L_PR_Idea__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Idea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to the related Lead</description>
    <label>Lead Title</label>
    <referenceTo>L_PR_Idea__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/L_PR_La_Trobe_Org_Unit__c.field-meta.xml
<CustomField>
    <fullName>L_PR_La_Trobe_Org_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>La Trobe Organisation Unit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>I_RS_La_Trobe_Organisation_Unit</value>
        </filterItems>
        <filterItems>
            <field>Account.I_RS_Status__c</field>
            <operation>notEqual</operation>
            <value>Closed</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/PRM_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>PRM_Opportunity</fullName>
    <active>true</active>
    <businessProcess>PRM Opportunity Process</businessProcess>
    <label>PRM Opportunity</label>
</RecordType>

force-app/main/default/classes/L_PR_OpportunityTriggerHandler.cls
/**
* @author  Vanita Walia
* @date    01/09/2022
* @description : This class is used for filtering the opportunity records and calling helper methods
*/
public without sharing class L_PR_OpportunityTriggerHandler{
    public static void execute() {        
        List<Apex_Debug_Log__c> errorLogs = new List<Apex_Debug_Log__c>() ;
        try{   
            if(Trigger.isBefore) {
                if(Trigger.isInsert || Trigger.isUpdate) {
                    map<Id,Opportunity> mapOldOpp = (map<Id,Opportunity>)Trigger.oldMap; 
                    Id prmOppRecordType =[select Id from RecordType where SobjectType ='Opportunity' and DeveloperName='PRM_Opportunity'].Id;
             
                    for(Opportunity opp : (List<Opportunity>)Trigger.new){                        
                        if(opp.RecordTypeId ==prmOppRecordType){ 
                            if(opp.StageName != Null && (Trigger.isInsert || (Trigger.isUpdate && opp.StageName != mapOldOpp.get(opp.Id).StageName)) 
                               && (opp.StageName == 'Closed Won' || opp.StageName == 'Closed Lost')){
                                   opp.CloseDate = system.today();
                               }
                        }
                    }
                }
            }
                 
        	if(Trigger.isAfter) {
            	if(Trigger.isInsert || Trigger.isUpdate) {
                	//variable declaration
                 	map<Id,Opportunity> mapOldOpp = (map<Id,Opportunity>)Trigger.oldMap;        			
                    set<Id> oppIdSet = new Set<Id>();
                    Set<String> staffIds = new Set<String>();
                    Map<Id, Set<String>> oppStaffMap = new Map<Id, Set<String>>();
                    Map<Id,String> oppStatusMap = new Map<Id,String>();
                    Map<Id,Id> oppOrgMap = new Map<Id,Id>();
        			Map<Id,Id> removeOppOrgMap = new Map<Id,Id>();
                     Map<Id,Id> oppInternalOrgMap = new Map<Id,Id>();
        			Map<Id,Id> removeOppInternalOrgMap = new Map<Id,Id>();
                    Map<Id,Id> leadOppMap = new Map<Id,Id>();
                    Id prmOppRecordType =[select Id from RecordType where SobjectType ='Opportunity' and DeveloperName='PRM_Opportunity'].Id;
             
                    for(Opportunity opp : (List<Opportunity>)Trigger.new){                        
                        if(opp.RecordTypeId ==prmOppRecordType){                      
                                    
                        	// check if the opportunity status is closed lost & closed reason is not null
                        	if(Trigger.isUpdate && opp.StageName == 'Closed Lost' && opp.L_PR_Closed_Reason__c != Null ){
                            	// collect the opportunityIds
                            	oppIdSet.add(opp.Id);
                        	}
                        
                        	// check if status is updated (to update on opportunity organisation field)
                        	if(opp.StageName != Null && Trigger.isUpdate && opp.StageName != mapOldOpp.get(opp.Id).StageName){
                            	oppStatusMap.put(opp.Id,opp.StageName);
                        	}
                        	// check if organisation is not blank or value is updated
                        	if(opp.AccountId != Null  && (Trigger.isInsert || (Trigger.isUpdate && opp.AccountId != mapOldOpp.get(opp.Id).AccountId))){                           
                            	oppOrgMap.put(opp.Id,opp.AccountId);                               
                        	}
                        	else if(Trigger.isUpdate && opp.AccountId == Null && opp.AccountId != mapOldOpp.get(opp.Id).AccountId){ 
                            	//remove the record from list
                            	removeOppOrgMap.put(opp.Id,mapOldOpp.get(opp.Id).AccountId);
                        	}
                        
                        	// check if La trobe organisation unit is not blank or value is updated
                        	if(opp.L_PR_La_Trobe_Org_Unit__c != Null && (Trigger.isInsert || (Trigger.isUpdate && opp.L_PR_La_Trobe_Org_Unit__c != mapOldOpp.get(opp.Id).L_PR_La_Trobe_Org_Unit__c))){                           
                            	oppInternalOrgMap.put(opp.Id,opp.L_PR_La_Trobe_Org_Unit__c);                               
                        	}
                        	else if(Trigger.isUpdate && opp.L_PR_La_Trobe_Org_Unit__c == Null && opp.L_PR_La_Trobe_Org_Unit__c != mapOldOpp.get(opp.Id).L_PR_La_Trobe_Org_Unit__c){ 
                            	//remove the record from list
                            	removeOppInternalOrgMap.put(opp.Id,mapOldOpp.get(opp.Id).L_PR_La_Trobe_Org_Unit__c);
                        	}
                            
                            //check if opportunity is converted from lead
                            if(Trigger.isInsert && opp.L_PR_Idea__c != Null){
                                leadOppMap.put(opp.L_PR_Idea__c,opp.Id);                                    
                            }
                        } 
                    }                    
                    //call helper methods to copy related records from PRM Lead to opportunity
                    if(!leadOppMap.isEmpty()){
                        L_PR_OpportunityTriggerHelper.copyOrgDataFromLead(leadOppMap);
                        L_PR_OpportunityTriggerHelper.copyAffiliationDataFromLead(leadOppMap);
                        L_PR_OpportunityTriggerHelper.moveActivityDataFromLead(leadOppMap);
                        L_PR_OpportunityTriggerHelper.moveNotesNFilesDataFromLead(leadOppMap);
                        L_PR_OpportunityTriggerHelper.updateLeadStatusClosedConverted(leadOppMap);
                    }
                    
                    // call helper method to create or update opportunity organisation record & isPrimary checkbox
                    if(!oppOrgMap.isEmpty() || !removeOppOrgMap.isEmpty()){                    	
                    	L_PR_OpportunityTriggerHelper.createUpdateOppOrganisations(oppOrgMap,removeOppOrgMap,'External Org');
                    }
                    
                     // call helper method to create or update opportunity organisation record & isPrimary checkbox for la trobe organisation unit
                    if(!oppInternalOrgMap.isEmpty() || !removeOppInternalOrgMap.isEmpty()){                    	
                    	L_PR_OpportunityTriggerHelper.createUpdateOppOrganisations(oppInternalOrgMap,removeOppInternalOrgMap,'La Trobe Org');
                    }
                    
                    //call helper method to update status on related opportunity organisation records when opportunity status changes
                    if(!oppStatusMap.isEmpty())
                        L_PR_OpportunityTriggerHelper.updateExtOrgOpptStageField(oppStatusMap);
                    
                    // Send Salesforce notification to staff affiliation users
                      if(!oppIdSet.isEmpty()){
                      for(L_PR_Opportunity_Affiliation_Relation__c oppAff : [Select Id, L_PR_Affiliation__c, L_PR_Opportunity__c,L_PR_Affiliation__r.I_RM_Role__c,
                                                                		L_PR_Affiliation__r.I_RM_Contact__c, L_PR_Affiliation__r.I_RM_Contact__r.I_RS_Related_User__c
                                                                  		from L_PR_Opportunity_Affiliation_Relation__c where L_PR_Opportunity__c in:oppIdSet
                                                                  		AND L_PR_Affiliation__r.I_RM_Contact__r.I_RS_Related_User__c != Null
                                       									AND L_PR_Affiliation__r.I_RM_Role__c ='La Trobe Staff']){
                             
                            if(!oppStaffMap.isEmpty() && oppStaffMap.get(oppAff.L_PR_Opportunity__c) != Null){
                             	oppStaffMap.get(oppAff.L_PR_Opportunity__c).add(oppAff.L_PR_Affiliation__r.I_RM_Contact__r.I_RS_Related_User__c);                                                 
                             }
                             else{
                                 oppStaffMap.put(oppAff.L_PR_Opportunity__c, new Set<String>{oppAff.L_PR_Affiliation__r.I_RM_Contact__r.I_RS_Related_User__c});                                               
                             }
							 staffIds.add(oppAff.L_PR_Affiliation__r.I_RM_Contact__r.I_RS_Related_User__c);
                         }
                    }
                    if(!oppStaffMap.isEmpty()){
                        L_PR_OpportunityTriggerHelper.createCustomSFNotification(oppStaffMap);
                    }                    
                   
    			}
			}
        }catch(exception ex){
            errorLogs.add(new Apex_Debug_Log__c(Apex_Class_Name__c = 'L_PR_OpportunityTriggerHandler',Apex_Class_Method_Name__c = 'execute method',Exception_message__c = ex.getMessage(),Exception_Stack_Trace__c = ex.getStackTraceString()));
            		if (errorLogs != null && !errorLogs.isEmpty()){
               			insert errorLogs;
            			errorLogs.clear();
            		} 
        }
        }
}