force-app/main/default/objects/Apex_Debug_Log__c/Apex_Debug_Log__c.object-meta.xml
<CustomObject>
    <description>Captures results of non-user facing transactions such as Apex endpoints, callouts and asynchronous jobs</description>
    <label>Apex Debug Log</label>
    <nameField>
        <displayFormat>ADL-{00000000}</displayFormat>
        <label>Apex Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Apex_Class_Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Method_Name__c</fullName>
    <label>Apex Class Method Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <description>The invoking class that created the record</description>
    <label>Apex Class Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <description>If an exception occurs, this is the main message</description>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Exception_stack_trace__c.field-meta.xml
<CustomField>
    <fullName>Exception_stack_trace__c</fullName>
    <description>If an exception occurs, this is the stack trace</description>
    <label>Exception stack trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>A legally binding document that defines the obligations to which the contractual parties involved in conducting the research must adhere.</description>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/I_RS_Contract__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hierarchy or related contracts in case of renewal or amendments</description>
    <inlineHelpText>Select an existing Agreement if this request is for Variations or Subcontract/Collaboration requests.</inlineHelpText>
    <label>Parent Agreement</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Child Agreements</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/I_RS_Organisation__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Organisation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Include the main Organisation for the Agreement. For Researcher Portal users if the organisation is not available, please include details in the Reasons for Agreement or Variation above.</inlineHelpText>
    <label>Organisation Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>You can only select Educational Institution or External Organisation record types</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Educational Institution</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>External Organisation</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/I_RS_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Status__c</fullName>
    <inlineHelpText>“Executed” is when the Agreement/Variation has been signed and is active.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Initial</fullName>
            </value>
            <value>
                <fullName>Preparing Instructions</fullName>
            </value>
            <value>
                <fullName>Instructions</fullName>
            </value>
            <value>
                <fullName>Engage Legal to Draft Variation</fullName>
            </value>
            <value>
                <fullName>Update Variation</fullName>
            </value>
            <value>
                <fullName>Notify Appropriate Stakeholders</fullName>
            </value>
            <value>
                <fullName>Create Letter</fullName>
                <label>Create Variation</label>
            </value>
            <value>
                <fullName>Completing Template</fullName>
            </value>
            <value>
                <fullName>Engage Legal to Draft Contract</fullName>
            </value>
            <value>
                <fullName>Reviewing Draft</fullName>
            </value>
            <value>
                <fullName>Client Review</fullName>
                <label>Other Party Review</label>
            </value>
            <value>
                <fullName>Legal Review</fullName>
            </value>
            <value>
                <fullName>Update Contract</fullName>
            </value>
            <value>
                <fullName>Researcher Review</fullName>
            </value>
            <value>
                <fullName>With Other Party</fullName>
            </value>
            <value>
                <fullName>La Trobe Signature</fullName>
            </value>
            <value>
                <fullName>Send to Client</fullName>
                <label>Send to Other Party</label>
            </value>
            <value>
                <fullName>Client Countersign</fullName>
                <label>Other Party Countersign</label>
            </value>
            <value>
                <fullName>Receive Client Signed Copy</fullName>
                <label>Receive Other Party Signed Copy</label>
            </value>
            <value>
                <fullName>Receive Executed Copy</fullName>
            </value>
            <value>
                <fullName>Notify of Variation Outcome</fullName>
            </value>
            <value>
                <fullName>La Trobe Countersign</fullName>
            </value>
            <value>
                <fullName>La Trobe University Signature</fullName>
            </value>
            <value>
                <fullName>Send Signed Copy Back</fullName>
            </value>
            <value>
                <fullName>Submit to Research Office</fullName>
            </value>
            <value>
                <fullName>Return Signed Copy to Client</fullName>
                <label>Return Signed Copy to Other Party</label>
            </value>
            <value>
                <fullName>Executed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Related_Contract__c/Related_Contract__c.object-meta.xml
<CustomObject>
    <label>Related Organisation</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Related Organisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Contract__c/fields/I_RS_Contract__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Contract__c</fullName>
    <label>Agreement</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Related Organisations</relationshipLabel>
    <relationshipName>Related_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Related_Contract__c/fields/I_RS_Organisation__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Agreements</relationshipLabel>
    <relationshipName>Related_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Contract__c/fields/L_PR_Agreement_Recordtype__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Agreement_Recordtype__c</fullName>
    <label>Agreement Record Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Related_Contract__c/fields/L_PR_Agreement_Status__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Agreement_Status__c</fullName>
    <label>Agreement Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RelatedContractTriggerHandler.cls
/**
 * Handler class for the Related_ContractTrigger trigger
 */

public without sharing class RelatedContractTriggerHandler{

    public static void execute(){

        //LTU360-2384
        List<Related_Contract__c> listOfRelOrgToUpdate = new List<Related_Contract__c>();        
        List<Apex_Debug_Log__c> errorLogs = new List<Apex_Debug_Log__c>();
        
        if(Trigger.isAfter){
            if(Trigger.isInsert || Trigger.isUpdate){
                try{
                    List<Related_Contract__c> listOfRelOrgs = [SELECT Id, L_PR_Agreement_Status__c, I_RS_Contract__r.I_RS_Status__c, I_RS_Contract__c, I_RS_Organisation__c,
                    L_PR_Agreement_Recordtype__c FROM Related_Contract__c Where Id IN : Trigger.New];
                    map<Id,Related_Contract__c> mapOldRelOrgs = (map<Id,Related_Contract__c>)Trigger.oldMap;
                    for(Related_Contract__c eorg : listOfRelOrgs){
                        Related_Contract__c relOrg = new Related_Contract__c();
                        if(eorg.I_RS_Contract__r.I_RS_Status__c != null && (Trigger.isInsert || (Trigger.isUpdate && eorg.I_RS_Contract__r.I_RS_Status__c != mapOldRelOrgs.get(eorg.id).L_PR_Agreement_Status__c))) {
                            relOrg.L_PR_Agreement_Status__c = eorg.I_RS_Contract__r.I_RS_Status__c;
                            relOrg.Id = eorg.Id;
                            listOfRelOrgToUpdate.add(relOrg);
                        }
                    }
                    if(!listOfRelOrgToUpdate.isEmpty()){
                        update listOfRelOrgToUpdate;
                    }
                }catch(Exception e){
                    errorLogs.add(new Apex_Debug_Log__c(Apex_Class_Name__c = 'RelatedContractTriggerHandler', Apex_Class_Method_Name__c = 'RelatedContractTriggerHandler',
                        Exception_message__c = 'Exception while updating the L_PR_Agreement_Status__c field in Related_Contract__c', Exception_Stack_Trace__c = e.getStackTraceString()));
                }
            }
        }

    }
}