force-app/main/default/objects/Apex_Debug_Log__c/Apex_Debug_Log__c.object-meta.xml
<CustomObject>
    <description>Captures results of non-user facing transactions such as Apex endpoints, callouts and asynchronous jobs</description>
    <label>Apex Debug Log</label>
    <nameField>
        <displayFormat>ADL-{00000000}</displayFormat>
        <label>Apex Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Apex_Class_Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Method_Name__c</fullName>
    <label>Apex Class Method Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <description>The invoking class that created the record</description>
    <label>Apex Class Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <description>If an exception occurs, this is the main message</description>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Exception_stack_trace__c.field-meta.xml
<CustomField>
    <fullName>Exception_stack_trace__c</fullName>
    <description>If an exception occurs, this is the stack trace</description>
    <label>Exception stack trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/L_PR_External_Org_Opportunity_Relation__c/L_PR_External_Org_Opportunity_Relation__c.object-meta.xml
<CustomObject>
    <label>Organisation Opportunity Relationship</label>
    <nameField>
        <displayFormat>OOR-{000000}</displayFormat>
        <label>Organisation Opportunity Relationship</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organisation Opportunity Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/L_PR_External_Org_Opportunity_Relation__c/fields/L_PR_Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Opportunity_Name__c</fullName>
    <label>Opportunity Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PRM_Opportunity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Organisation Opportunity Relationships</relationshipLabel>
    <relationshipName>External_Org_Opportunity_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/L_PR_External_Org_Opportunity_Relation__c/fields/L_PR_OpportunityStage__c.field-meta.xml
<CustomField>
    <fullName>L_PR_OpportunityStage__c</fullName>
    <label>Opportunity Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/L_PR_External_Org_Opportunity_Relation__c/fields/L_PR_Organisation_Name__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Organisation_Name__c</fullName>
    <label>Organisation Name</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>I_ST_Educational_Institution</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>I_RS_External_Organisation</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>I_RS_La_Trobe_Organisation_Unit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Organisation Opportunity Relationships</relationshipLabel>
    <relationshipName>External_Org_Opportunity_Relationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/L_PR_External_Org_Opportunity_Relation__c/fields/L_PR_Organisation_Type__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Organisation_Type__c</fullName>
    <formula>L_PR_Organisation_Name__r.RecordType.Name</formula>
    <label>Organisation Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/L_PR_Idea__c/L_PR_Idea__c.object-meta.xml
<CustomObject>
    <description>Idea/ Lead object being used for PRM Application</description>
    <label>PRM Lead</label>
    <nameField>
        <label>Lead Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PRM Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/L_PR_Idea__c/fields/L_PR_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Affiliations</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>I_RM_Affiliation__c.I_RM_Role__c</field>
            <operation>equals</operation>
            <value>La Trobe Staff, Secondary School Representative, External Contact</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>PRM Ideas</relationshipLabel>
    <relationshipName>PRM_Ideas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/L_PR_Idea__c/fields/L_PR_Closed_Reason__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Closed_Reason__c</fullName>
    <description>Text field to describe why the Lead/Idea did not qualify/succeed</description>
    <label>Closed Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/L_PR_Idea__c/fields/L_PR_Organisation__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is a reference to related External Organisation or Educational Institution.</description>
    <label>Organisation Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>I_RS_External_Organisation</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>I_ST_Educational_Institution</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PRM Leads</relationshipLabel>
    <relationshipName>PRM_Ideas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/L_PR_Idea_Affiliation__c/L_PR_Idea_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Junction object to capture Lead/Idea and affiliation relationship records</description>
    <label>Lead Affiliation</label>
    <nameField>
        <displayFormat>IA-{000000}</displayFormat>
        <label>Lead Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/L_PR_Idea_Affiliation__c/fields/L_PR_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Affiliation__c</fullName>
    <label>Affiliation</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>I_RM_Affiliation__c.I_RM_Role__c</field>
            <operation>equals</operation>
            <value>La Trobe Staff, Secondary School Representative, External Contact</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>PRM Leads</relationshipLabel>
    <relationshipName>PRM_Leads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/L_PR_Idea_Affiliation__c/fields/L_PR_Idea__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Idea__c</fullName>
    <label>PRM Lead</label>
    <referenceTo>L_PR_Idea__c</referenceTo>
    <relationshipLabel>Affiliations</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/L_PR_Idea_Organisation__c/L_PR_Idea_Organisation__c.object-meta.xml
<CustomObject>
    <description>Junction object to capture relationship between Lead/Idea and Organisations</description>
    <label>Lead Organisation</label>
    <nameField>
        <displayFormat>IO-{000000}</displayFormat>
        <label>PRM Lead Organisation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Organisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/L_PR_Idea_Organisation__c/fields/L_PR_Idea__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Idea__c</fullName>
    <label>PRM Lead</label>
    <referenceTo>L_PR_Idea__c</referenceTo>
    <relationshipLabel>Lead Organisations</relationshipLabel>
    <relationshipName>Lead_Organisations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/L_PR_Idea_Organisation__c/fields/L_PR_IsPrimary__c.field-meta.xml
<CustomField>
    <fullName>L_PR_IsPrimary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsPrimary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/L_PR_Idea_Organisation__c/fields/L_PR_Organisation__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Organisation__c</fullName>
    <label>Organisation</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <errorMessage>You can only select External Organisation, Educational Institution or La Trobe Organisation Unit</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>La Trobe Organisation Unit</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>External Organisation</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Educational Institution</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Lead Organisations</relationshipLabel>
    <relationshipName>Idea_Organisations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/L_PR_Idea_Organisation__c/fields/L_PR_Organisation_Type__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Organisation_Type__c</fullName>
    <formula>L_PR_Organisation__r.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Organisation Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/L_PR_Opportunity_Affiliation_Relation__c/L_PR_Opportunity_Affiliation_Relation__c.object-meta.xml
<CustomObject>
    <description>Opportunity Affiliation Relationship</description>
    <label>Opportunity Affiliation Relationship</label>
    <nameField>
        <displayFormat>OA-{00000}</displayFormat>
        <label>Opportunity Affiliation Relationship Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Affiliation Relationship</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/L_PR_Opportunity_Affiliation_Relation__c/fields/L_PR_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Affiliation__c</fullName>
    <label>Affiliation</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>You can only select La Trobe Staff or External Contact Affiliation</errorMessage>
        <filterItems>
            <field>I_RM_Affiliation__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>La Trobe Staff</value>
        </filterItems>
        <filterItems>
            <field>I_RM_Affiliation__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>External Contact</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>Opportunity Affiliation Relationship</relationshipLabel>
    <relationshipName>Opportunity_Affiliation_Relationship</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/L_PR_Opportunity_Affiliation_Relation__c/fields/L_PR_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Opportunity__c</fullName>
    <label>Opportunity Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You can only select PRM Opportunity</errorMessage>
        <filterItems>
            <field>Opportunity.RecordType.Name</field>
            <operation>equals</operation>
            <value>PRM Opportunity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Affiliation Relationship</relationshipLabel>
    <relationshipName>Opportunity_Affiliation_Relationship</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/L_PR_Closed_Reason__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Closed_Reason__c</fullName>
    <description>Reason for closed lost opportunity</description>
    <label>Closed Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/L_PR_Idea__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Idea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to the related Lead</description>
    <label>Lead Title</label>
    <referenceTo>L_PR_Idea__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/L_PR_OpportunityTriggerHelper.cls
/**
* @author  Vanita Walia
* @date    01/09/2022
* @description : This class contains helper methods related to opportunity
*/
public with sharing class L_PR_OpportunityTriggerHelper {
    static List<Apex_Debug_Log__c> errorLogs = new List<Apex_Debug_Log__c>() ;
    
     // Method to create or update opportunity organisation record & IsPrimary checkbox field 
    public static void createUpdateOppOrganisations(Map<Id,Id> lOrgMap,Map<Id,Id> removelOrgMap, String orgType){
        List<L_PR_External_Org_Opportunity_Relation__c> oppOrgList = new List<L_PR_External_Org_Opportunity_Relation__c>();
        try{
            if(lOrgMap != Null){
                  //check if the current opportunity organisation pair exist in opportunity organisation relationship records                      
                  List<L_PR_External_Org_Opportunity_Relation__c> ExistlOrgList = [Select Id, L_PR_Opportunity_Name__c,L_PR_Organisation_Name__c, L_PR_IsPrimary__c from L_PR_External_Org_Opportunity_Relation__c
                                                                  where L_PR_Opportunity_Name__c in: lOrgMap.keySet() AND L_PR_Organisation_Name__c in: lOrgMap.values()];
                      if(!ExistlOrgList.isEmpty()){
                       // if Found, mark IsPrimary True for that record
                      		for(L_PR_External_Org_Opportunity_Relation__c exLOrg : ExistlOrgList){
                                //  update existing opportunity organisation relationship
                           		L_PR_External_Org_Opportunity_Relation__c oppOrg = new L_PR_External_Org_Opportunity_Relation__c();
                                oppOrg.Id = exLOrg.Id;
                            	oppOrg.L_PR_IsPrimary__c = True; 
                            	oppOrgList.add(oppOrg);
                            }
                        }
                        else{
                            // if no existing record found, create new record with opportunity & organisation relationship and isPrimary true
                            for(Id opp : lOrgMap.keySet()){
                             	//create Lead organisation relationship record
                            	L_PR_External_Org_Opportunity_Relation__c oppOrg = new L_PR_External_Org_Opportunity_Relation__c();
                            	oppOrg.L_PR_Organisation_Name__c = lOrgMap.get(opp);
                            	oppOrg.L_PR_Opportunity_Name__c = opp;
                            	oppOrg.L_PR_IsPrimary__c = True;
                            	oppOrgList.add(oppOrg);
                            }
                        }
                        // find all opportunity organisation relationships where opportunity is present and isPrimary ticked
                        // or any other opportunity organisation relationship is present with isprimary true
                        for(L_PR_External_Org_Opportunity_Relation__c ActivelOrgList : [Select Id, L_PR_Opportunity_Name__c,L_PR_Organisation_Name__c, L_PR_IsPrimary__c,L_PR_Organisation_Type__c from L_PR_External_Org_Opportunity_Relation__c
                                                                      where (L_PR_Opportunity_Name__c in: lOrgMap.keySet() AND L_PR_Organisation_Name__c NOT IN: lOrgMap.values() AND L_PR_IsPrimary__c = TRUE)
                                                                    		OR (L_PR_Opportunity_Name__c in: removelOrgMap.keySet() AND L_PR_Organisation_Name__c in: removelOrgMap.values())]){
                                //  update existing lead organisation relationship
                                if(orgType =='External Org' && (ActivelOrgList.L_PR_Organisation_Type__c == 'External Organisation' || ActivelOrgList.L_PR_Organisation_Type__c == 'Educational Institution')){
                           			L_PR_External_Org_Opportunity_Relation__c oppOrg = new L_PR_External_Org_Opportunity_Relation__c();
                                	oppOrg.Id = ActivelOrgList.Id;
                            		oppOrg.L_PR_IsPrimary__c = False; 
                            		oppOrgList.add(oppOrg);   
                                }
                                else if(orgType =='La Trobe Org' && ActivelOrgList.L_PR_Organisation_Type__c == 'La Trobe Organisation Unit'){
                           			L_PR_External_Org_Opportunity_Relation__c oppOrg = new L_PR_External_Org_Opportunity_Relation__c();
                                	oppOrg.Id = ActivelOrgList.Id;
                            		oppOrg.L_PR_IsPrimary__c = False; 
                            		oppOrgList.add(oppOrg);   
                                }
                        	}  
                    }
                   
                    if(oppOrgList != Null){
                        upsert oppOrgList;
                    }
        		}catch(exception ex){                    
            		errorLogs.add(new Apex_Debug_Log__c(Apex_Class_Name__c = 'L_PR_OpportunityTriggerHelper',Apex_Class_Method_Name__c = 'createUpdateOppOrganisations',Exception_message__c = ex.getMessage(),Exception_Stack_Trace__c = ex.getStackTraceString()));
            		if (errorLogs != null && !errorLogs.isEmpty()){
               			insert errorLogs;
            			errorLogs.clear();
            		} 
                }                    
    }
    
    
     // Method to create salesforce notification for staff affiliation users
    public static void createCustomSFNotification(Map<Id, Set<String>> oppStaffMap){
        
        try{
            if(!oppStaffMap.isEmpty()){
                // Get the Id for our custom notification type
        		CustomNotificationType notificationType = [SELECT Id, DeveloperName FROM CustomNotificationType WHERE DeveloperName='Lead_Notification'];
                
                for(Opportunity opp: [Select Id,Name, L_PR_Closed_Reason__c from Opportunity where Id IN:oppStaffMap.keyset()]){
                    // Create a new custom notification
        			Messaging.CustomNotification notification = new Messaging.CustomNotification();

        			// Set the contents for the notification
        			String title = opp.Name;
       				String bodyContent = opp.L_PR_Closed_Reason__c;
        			notification.setTitle(title);
        			notification.setBody(bodyContent);

        			// Set the notification type and target
        			notification.setNotificationTypeId(notificationType.Id);
        			notification.setTargetId(opp.Id);
                    // Actually send the notification
            		notification.send(oppStaffMap.get(opp.Id));
                }
            }
        }catch(exception ex){
            errorLogs.add(new Apex_Debug_Log__c(Apex_Class_Name__c = 'L_PR_OpportunityTriggerHelper',Apex_Class_Method_Name__c = 'createCustomSFNotification',Exception_message__c = ex.getMessage(),Exception_Stack_Trace__c = ex.getStackTraceString()));
            		if (errorLogs != null && !errorLogs.isEmpty()){
               			insert errorLogs;
            			errorLogs.clear();
            		} 
                }
    }
    
    // Method to update opportunity organisation record on status update 
    public static void updateExtOrgOpptStageField(Map<Id,String> opptStageMap){

        List<L_PR_External_Org_Opportunity_Relation__c> extOrgOptsToUpdate = new List<L_PR_External_Org_Opportunity_Relation__c>();
        
        try{
            if(opptStageMap != null){
                for(L_PR_External_Org_Opportunity_Relation__c extOrgOpp : [Select Id, L_PR_IsPrimary__c, L_PR_Opportunity_Name__c, L_PR_OpportunityStage__c, L_PR_Organisation_Name__c
                                                                           From L_PR_External_Org_Opportunity_Relation__c Where L_PR_Opportunity_Name__c IN : opptStageMap.keySet()]){
                                                                            
                    L_PR_External_Org_Opportunity_Relation__c extOrg = new L_PR_External_Org_Opportunity_Relation__c();
                    extOrg.Id = extOrgOpp.Id;
                    extOrg.L_PR_OpportunityStage__c = opptStageMap.get(extOrgOpp.L_PR_Opportunity_Name__c);                                             
                    extOrgOptsToUpdate.add(extOrg);
                }
            }

            if(!extOrgOptsToUpdate.isEmpty()){
                update extOrgOptsToUpdate;
            }

        }catch(Exception ex){
            errorLogs.add(new Apex_Debug_Log__c(Apex_Class_Name__c = 'L_PR_OpportunityTriggerHelper',Apex_Class_Method_Name__c = 'updateExtOrgOpptStageField',Exception_message__c = ex.getMessage(),Exception_Stack_Trace__c = ex.getStackTraceString()));
            		if (errorLogs != null && !errorLogs.isEmpty()){
               			insert errorLogs;
            			errorLogs.clear();
            		} 
        }
    }
    
     // Method to copy prm lead organisation records to opportunity organisation relationships 
    public static void copyOrgDataFromLead(Map<Id,Id> leadOppMap){
        try{
			//copy related records from lead Organisations to Opportunity Organisation Relationships
			List<L_PR_External_Org_Opportunity_Relation__c> oppOrgList = new List<L_PR_External_Org_Opportunity_Relation__c>();
			
            for(L_PR_Idea_Organisation__c leadOrg : [Select Id,L_PR_Organisation__c,L_PR_IsPrimary__c,L_PR_Idea__c
                                                    	from L_PR_Idea_Organisation__c 
                                                    where L_PR_Idea__c in:leadOppMap.keyset()]) {
                 //create new opportunity organisation relationship record
                 L_PR_External_Org_Opportunity_Relation__c oppOrg = new L_PR_External_Org_Opportunity_Relation__c();
                 oppOrg.L_PR_Organisation_Name__c = leadOrg.L_PR_Organisation__c;
                 oppOrg.L_PR_IsPrimary__c = leadOrg.L_PR_IsPrimary__c;
                 oppOrg.L_PR_Opportunity_Name__c = leadOppMap.get(leadOrg.L_PR_Idea__c);
				oppOrgList.add(oppOrg);                                                        
             }
            
            if(!oppOrgList.isEmpty()){
                insert oppOrgList;
            }
        }catch(Exception ex){
            errorLogs.add(new Apex_Debug_Log__c(Apex_Class_Name__c = 'L_PR_OpportunityTriggerHelper',Apex_Class_Method_Name__c = 'copyOrgDataFromLead',Exception_message__c = ex.getMessage(),Exception_Stack_Trace__c = ex.getStackTraceString()));
            		if (errorLogs != null && !errorLogs.isEmpty()){
               			insert errorLogs;
            			errorLogs.clear();
            		} 
        }
    }
    
     // Method to copy prm lead Affiliation records to opportunity affiliation relationships 
    public static void copyAffiliationDataFromLead(Map<Id,Id> leadOppMap){
        try{
			//copy related records from lead Organisations to Opportunity Organisation Relationships
			List<L_PR_Opportunity_Affiliation_Relation__c> oppAffList = new List<L_PR_Opportunity_Affiliation_Relation__c>();
			
            for(L_PR_Idea_Affiliation__c leadAff : [Select Id,L_PR_Affiliation__c,L_PR_Idea__c
                                                    	from L_PR_Idea_Affiliation__c 
                                                    where L_PR_Idea__c in:leadOppMap.keyset()]) {
                 //create new opportunity affiliation relationship record
                 L_PR_Opportunity_Affiliation_Relation__c oppAff = new L_PR_Opportunity_Affiliation_Relation__c();
                 oppAff.L_PR_Affiliation__c = leadAff.L_PR_Affiliation__c;
                 oppAff.L_PR_Opportunity__c = leadOppMap.get(leadAff.L_PR_Idea__c);
				oppAffList.add(oppAff);                                                        
             }
            
            if(!oppAffList.isEmpty()){
                insert oppAffList;
            }
        }catch(Exception ex){
             errorLogs.add(new Apex_Debug_Log__c(Apex_Class_Name__c = 'L_PR_OpportunityTriggerHelper',Apex_Class_Method_Name__c = 'copyAffiliationDataFromLead',Exception_message__c = ex.getMessage(),Exception_Stack_Trace__c = ex.getStackTraceString()));
            		if (errorLogs != null && !errorLogs.isEmpty()){
               			insert errorLogs;
            			errorLogs.clear();
            		} 
        }
    }
     // Method to move tasks/emails/calls related to prm lead to opportunity 
    public static void moveActivityDataFromLead(Map<Id,Id> leadOppMap){
        try{
			//move related activity records from prm lead to Opportunity
			List<Task> tskList = new List<Task>();
			For(Task ts : [Select Id, ActivityDate, WhatId, WhoId,TaskSubtype from Task where whatId=:leadOppMap.keyset()]){
				ts.whatId = leadOppMap.get(ts.whatId);
    			tskList.add(ts);
			}            
            if(!tskList.isEmpty()){
                update tskList;
            }
        }catch(Exception ex){
            errorLogs.add(new Apex_Debug_Log__c(Apex_Class_Name__c = 'L_PR_OpportunityTriggerHelper',Apex_Class_Method_Name__c = 'moveActivityDataFromLead',Exception_message__c = ex.getMessage(),Exception_Stack_Trace__c = ex.getStackTraceString()));
            		if (errorLogs != null && !errorLogs.isEmpty()){
               			insert errorLogs;
            			errorLogs.clear();
            		} 
        }
    }
    
    // Method to move tasks/emails/calls related to prm lead to opportunity 
    public static void moveNotesNFilesDataFromLead(Map<Id,Id> leadOppMap){
        try{
			//move related notes & files records from prm lead to Opportunity
			List<ContentDocumentLink> cnList = new List<ContentDocumentLink>();
			List<ContentDocumentLink> cnDList = new List<ContentDocumentLink>();
			for(ContentDocumentLink conLinks : [select Id, LinkedEntityId,ContentDocumentId,
                                    ContentDocument.LatestPublishedVersion.Title,
                                    ContentDocument.LatestPublishedVersion.VersionData,
                                    ShareType, Visibility
                                    from ContentDocumentLink where LinkedEntityId IN :leadOppMap.keyset()]){
   				
    			ContentDocumentLink cdl = new ContentDocumentLink();
				cdl.ContentDocumentId = conLinks.ContentDocumentId; 
				cdl.LinkedEntityId = leadOppMap.get(conLinks.LinkedEntityId);
				cdl.ShareType = conLinks.ShareType;
				cdl.Visibility = conLinks.Visibility;
    			cnList.add(cdl);
    			cnDList.add(conLinks); 	
			}
        	if(!cnList.isEmpty())
				insert cnList;
            if(!cnDList.isEmpty())
				delete cnDList;

			
        }catch(Exception ex){
            errorLogs.add(new Apex_Debug_Log__c(Apex_Class_Name__c = 'L_PR_OpportunityTriggerHelper',Apex_Class_Method_Name__c = 'moveNotesNFilesDataFromLead',Exception_message__c = ex.getMessage(),Exception_Stack_Trace__c = ex.getStackTraceString()));
            		if (errorLogs != null && !errorLogs.isEmpty()){
               			insert errorLogs;
            			errorLogs.clear();
            		} 
        }
    }
    // Method to update prm lead status to closed converted 
    public static void updateLeadStatusClosedConverted(Map<Id,Id> leadOppMap){
        try{
            List<L_PR_Idea__c> prmLeads = new List<L_PR_Idea__c>();
            for(Id prmLeadId : leadOppMap.keyset()){
                L_PR_Idea__c prmLead = new L_PR_Idea__c(Id=prmLeadId);
                prmLead.L_PR_Lead_Status__c ='Closed – Converted';
                prmLead.L_PR_Converted_Date__c = System.Today();
                prmLeads.add(prmLead);
            }
            if(!prmLeads.isEmpty())
                update prmLeads;
			
        }catch(Exception ex){
            errorLogs.add(new Apex_Debug_Log__c(Apex_Class_Name__c = 'L_PR_OpportunityTriggerHelper',Apex_Class_Method_Name__c = 'updateLeadStatusClosedConverted',Exception_message__c = ex.getMessage(),Exception_Stack_Trace__c = ex.getStackTraceString()));
            		if (errorLogs != null && !errorLogs.isEmpty()){
               			insert errorLogs;
            			errorLogs.clear();
            		} 
        }
    }
}