force-app/main/default/objects/Apex_Debug_Log__c/Apex_Debug_Log__c.object-meta.xml
<CustomObject>
    <description>Captures results of non-user facing transactions such as Apex endpoints, callouts and asynchronous jobs</description>
    <label>Apex Debug Log</label>
    <nameField>
        <displayFormat>ADL-{00000000}</displayFormat>
        <label>Apex Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Apex_Class_Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Method_Name__c</fullName>
    <label>Apex Class Method Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <description>The invoking class that created the record</description>
    <label>Apex Class Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <description>If an exception occurs, this is the main message</description>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <label>Log Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Related_To_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Id__c</fullName>
    <description>An optional record to relate this Activity to</description>
    <label>Related To Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Request_Data__c.field-meta.xml
<CustomField>
    <fullName>Request_Data__c</fullName>
    <description>The data used in the transaction. For Apex Services, this could be the data sent from an external service. For a callout, this could be the data being sent. For a batch, this could be the batch of records.</description>
    <label>Request Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/I_RM_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Affiliation</description>
    <label>Affiliation</label>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/I_ST_Incremental_Score__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Incremental_Score__c</fullName>
    <label>Incremental Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/I_ST_Prior_Incremental_Score__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Prior_Incremental_Score__c</fullName>
    <description>Stores the prior incremental score when the score changes</description>
    <label>Prior Incremental Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/I_ST_Score_Calculated__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Score_Calculated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>I ST Score Calculated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/I_RM_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Part of the remediation project to store different personas</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Calculate_Affiliation_Score__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Calculate_Affiliation_Score__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Technical Field. Depicts if batch process needs to recalculate the affiliation&apos;s Lead Score.</description>
    <label>Calculate Affiliation Score</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/I_ST_Lead_Scoring__mdt/I_ST_Lead_Scoring__mdt.object-meta.xml
<CustomObject>
    <description>Key Value pairs which are used to calulate a Lead&apos;s score</description>
    <label>Lead Scoring</label>
    <pluralLabel>Lead Scoring</pluralLabel>
</CustomObject>

force-app/main/default/objects/I_ST_Lead_Scoring__mdt/fields/I_ST_Operator__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Operator__c</fullName>
    <label>Operator</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_ST_Lead_Scoring__mdt/fields/I_ST_Score__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Score__c</fullName>
    <label>Score</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/System_Switch__c/System_Switch__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This custom setting is used to disable/enable triggers</description>
    <label>System Switch</label>
</CustomObject>

force-app/main/default/objects/System_Switch__c/fields/I_RS_DisableTriggers__c.field-meta.xml
<CustomField>
    <fullName>I_RS_DisableTriggers__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox controls all the triggers enable/disable criteria. If checked, all the triggers for the object available will be disabled</description>
    <label>Disable Triggers</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/System_Switch__c/fields/I_RS_ObjectTriggersToBeDisabled__c.field-meta.xml
<CustomField>
    <fullName>I_RS_ObjectTriggersToBeDisabled__c</fullName>
    <description>This field stores the API names of the object for which the trigger needs to be disabled or enabled</description>
    <label>ObjectTriggersToBeDisabled</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/I_RS_Is_Researcher_User__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Is_Researcher_User__c</fullName>
    <formula>IF(Profile.Name = &quot;LTU Partner Community User&quot; ||
Profile.Name = &quot;LTU Partner Community Login User&quot;, &quot;1&quot;, &quot;0&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Researcher User?</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GlobalUtility.cls
//This is a utility class for common resuable code components 
public class GlobalUtility {
    
    static {
        //any pre logic
    }
    
    private static User currentUser;
    
    public static boolean currentUserIsResearcher(){
        if ((currentUser == null) || (Test.isRunningTest())){
            currentUser = [SELECT Id, Name, I_RS_Is_Researcher_User__c FROM User WHERE Id = :UserInfo.getUserId()];    
        }
        return (currentUser.I_RS_Is_Researcher_User__c == '1');
    }
    
    public static Id getIdValueOf(String strVal){        
        if ((strVal == null) || (strVal.trim() == '')) {
            return null;
        } else {
            return Id.valueOf(strVal);
        }
    }
    
    /**
* @description       This method is used to identify which objects have been marked for skip trigger
* @param             String 
* @return            Boolean
* @throws            NA
*/
    public static Boolean isTriggerDisabled(String objType){
        Boolean isDisabled = false;
        if(String.isNotBlank(objType)){
            System_Switch__c custSettings = System_Switch__c.getInstance();
            if(custSettings != null){
                String objsDisabled = custSettings.I_RS_ObjectTriggersToBeDisabled__c != null ?
                    custSettings.I_RS_ObjectTriggersToBeDisabled__c.trim() : null ;
                if(String.isNotBlank(objsDisabled)){
                    Set<String> objSet = new Set<String>();
                    objSet.addAll(trimStringList(objsDisabled.split(GlobalConstants.COMMA)));
                    System.debug('** objSet ==>'+objSet);
                    if(objSet.contains(objType) && custSettings.I_RS_DisableTriggers__c){
                        isDisabled = true;
                    }
                }
            }
        }
        System.debug('** Triggers Disabled ==>'+isDisabled);
        return isDisabled;
    }
    
    /**
* @description       This method is used to trim content of list
* @param             strList - List<String> 
* @return            List<String>
* @throws            NA
*/
    public static List<String> trimStringList(List<String> strList){
        List<String> retList = new List<String>();
        for(String str : strList){
            retList.add(str.trim());
        }
        System.debug('** retList ==>'+retList);
        return retList;
    }
    
    
    /**
* @description       This method is used to return fields in any field set
* @param             fieldSetName - String,  objectName - String
* @return            List<Schema.FieldSetMember>
* @throws            NA
*/
    public static List<Schema.FieldSetMember> getFieldSet(String fieldSetName, String ObjectName)
    {
        Map<String, Schema.SObjectType> GlobalDescribeMap = Schema.getGlobalDescribe();
        Schema.SObjectType SObjectTypeObj = GlobalDescribeMap.get(ObjectName);
        Schema.DescribeSObjectResult DescribeSObjectResultObj = SObjectTypeObj.getDescribe();
        
        Schema.FieldSet fieldSetObj = DescribeSObjectResultObj.FieldSets.getMap().get(fieldSetName);
        
        return fieldSetObj.getFields(); 
    }
    
    
    public static Map<Id, SObject> getParentRecordMap(String objectType, String fields, Set<Id> idsToQuery){
        
        String query = 'SELECT ' + fields + ' FROM ' + objectType + ' WHERE Id IN :idsToQuery';
        List<SObject> parentObjectList = Database.query(query);
        
        Map<Id, SObject> parentObjectMap = new Map<Id, SObject>(parentObjectList);
        
        return parentObjectMap;
        
    }
    
    
    public static Set<Id> getParentIdsInSet(List<SObject> childRecords, String parentFieldName){
        
        Set<Id> parentIds = new Set<Id>();
        for (SObject childRecord : childRecords){
            Id parentId = (Id) childRecord.get(parentFieldName);
            if (parentId != null)
                parentIds.add(parentId);
        }
        
        return parentIds;
        
    }
    
    
    
    
    /**
* @description       This method is used to return lookup field values on child records
* @param             childRecordList - List,  parentFieldName - String
* @return            Set<Id>
* @throws            NA
*/
    public static Set<Id> getParentIds(List<SObject> childRecordList, 
                                       String parentFieldName){
                                           
                                           Set<Id> parentIds = new Set<Id>();
                                           for (SObject childRecord : childRecordList){
                                               Id parentId = (Id) childRecord.get(parentFieldName);
                                               if (parentId != null)
                                                   parentIds.add(parentId);
                                           }
                                           
                                           return parentIds;
                                           
                                       } 
    
    
    public static List<Apex_Debug_Log__c> constructErrorLogsForDMLErrors(List<Object> dmlResults, 
                                                                         List<SObject> recordsBeingSaved, 
                                                                         String apexClassName, 
                                                      String apexMethodName)
    {
                                                                             System.debug('constructErrorLogsForDMLErrors');
                                                                             
                                                                             List<Apex_Debug_Log__c> errorLogs = new List<Apex_Debug_Log__c>();
                                                                             
                                                                             for (Integer index=0; index<dmlResults.size(); index++){
                                                                                 
                                                                                 Object saveResult = dmlResults[index];
                                                                                 
                                                                                 try {
                                                                                     System.debug('saveResult '+saveResult);
                                                                                     
                                                                                     Boolean isSuccess;
                                                                                     List<Database.Error> errors;
                                                                                     Id recordSaveId = (Id) recordsBeingSaved[index].get('Id');
                                                                                     
                                                                                     if (saveResult instanceOf Database.SaveResult){
                                                                                         isSuccess = ((Database.SaveResult) saveResult).isSuccess();
                                                                                         errors = ((Database.SaveResult) saveResult).getErrors();
                                                                                     }
                                                                                     else if (saveResult instanceOf Database.UpsertResult){
                                                                                         isSuccess = ((Database.UpsertResult) saveResult).isSuccess();
                                                                                         errors = ((Database.UpsertResult) saveResult).getErrors();
                                                                                     }
                                                                                     else if (saveResult instanceOf Database.DeleteResult){
                                                                                         isSuccess = ((Database.DeleteResult) saveResult).isSuccess();
                                                                                         errors = ((Database.DeleteResult) saveResult).getErrors();
                                                                                     }
                                                                                     
                                                                                     if (!isSuccess){
                                                                                         
                                                                                         SObject failedRecord = recordsBeingSaved[index];
                                                                                         
                                                                                         List<String> errorMessages = new List<String>();
                                                                                         for (Database.Error errorResult : errors){
                                                                                             errorMessages.add(errorResult.getMessage());
                                                                                         }
                                                                                         
                                                                                         errorLogs.add(
                                                                                             new Apex_Debug_Log__c(
                                                                                                 Log_Type__c = 'Error',
                                                                                                 Apex_Class_Name__c = apexClassName,
                                                                                                 Apex_Class_Method_Name__c = apexMethodName,
                                                                                                 Exception_message__c = String.join(errorMessages, ' | '),
                                                                                                 Request_Data__c = JSON.serializePretty(failedRecord),
                                                                                                 Related_To_Id__c = recordSaveId
                                                                                             )
                                                                                         );
                                                                                         
                                                                                     }
                                                                                 }
                                                                                 catch (Exception e){
                                                                                     System.debug('Error when constructing Apex logs');
                                                                                     System.debug(e.getMessage());
                                                                                     System.debug(e.getStackTraceString());
                                                                                     System.debug(saveResult);
                                                                                 }
                                                                             }
                                                                             return errorLogs;
                                                                         }
    
    
    public static String getDateString(Date dateInput){
        if (dateInput != null){
            return dateInput.day() + '/' + dateInput.month() + '/' + dateInput.year();
        }
        return '';
    }
    
    
    public static Boolean currentContextIsAsync(){
        return System.isQueueable() || System.isFuture() || System.isBatch();
    }
    
    //This function converts the comma separated String of IDs ONLY to Set<Id>
    public static Set<Id> convertCommaSeparatedStringsToSetIds(String commaseparatedString) {
        
        Set<String> stringOfIds = new Set<String>();
        //Use the utility method to convert the List into Set<String> split by comma
        stringOfIds.addAll(GlobalUtility.trimStringList((List<String>)commaseparatedString.split(GlobalConstants.COMMA)));
        //convert Set<String> to Set<Id> for valid Ids passed
        Set<Id> idSet = new Set<Id>( (List<Id>)new List<String>( stringOfIds ) );
        return idSet;
    }
    
    /**
* @methodName        calculateScoreonObjectFields
* @description       Returns list of record with Incremental score calculated 
* @param             Map<String, List<I_ST_Lead_Scoring__mdt>> mapExtractPicklistFields,List<sObject> lstObjectFields,String sObjectIncrementScorefield
* @return            List<sObject>    
*/
    //public static List<sObject> calculateScoreonObjectFields(map<String,List<I_ST_Lead_Scoring__mdt>> mapExtractPicklistFields,List<sObject> lstObjectFields,String sObjectIncrementScorefield,String sObjectName){
        public static List<sObject> calculateScoreonObjectFields(map<String,List<I_ST_Lead_Scoring__mdt>> mapExtractPicklistFields,List<sObject> lstObjectFields,String sObjectIncrementScorefield,String sObjectName,Map<Id,sObject> oldMap){
        system.debug('Size: '+ mapExtractPicklistFields.size() +' mapExtractPicklistFields: '+mapExtractPicklistFields);
        system.debug('Size: '+ lstObjectFields.size() +' lstObjectFields: '+lstObjectFields);
        system.debug(' sObjectIncrementScorefield: '+sObjectIncrementScorefield);
        system.debug(' sObjectName: '+sObjectName);
        
        List<sObject> lstUpdatedRecord = new List<sObject>();
        if(!lstObjectFields.isEmpty()){
            for(sObject sObjectRecord : lstObjectFields){ 
                Integer finalLeadScore = 0;                  
                for(String fieldName : mapExtractPicklistFields.keyset()){
                    for(I_ST_Lead_Scoring__mdt leadScoring : mapExtractPicklistFields.get(fieldName)){
                        
                        if(leadScoring.I_ST_Operator__c.tolowercase() == ('EQUALS').tolowercase()){ 
                            if(leadScoring.Label == sObjectRecord.get(fieldName)){
                                if(leadScoring.I_ST_Score__c != null){
                                    finalLeadScore += Integer.valueOf(leadScoring.I_ST_Score__c); 
                                }
                            }
                        }
                        
                        else if(leadScoring.I_ST_Operator__c.tolowercase() == ('ISTRUE').tolowercase()){
                            if(String.valueof(sObjectRecord.get(fieldName)).tolowercase() == ('True').tolowercase()){
                                if(leadScoring.I_ST_Score__c != null){
                                    finalLeadScore += Integer.valueOf(leadScoring.I_ST_Score__c);   
                                }
                            }
                        }
                        else if(leadScoring.I_ST_Operator__c.tolowercase() == ('ISPOPULATED').tolowercase()){
                            if(!String.IsBlank(String.valueof(sObjectRecord.get(fieldName)))){
                                if(leadScoring.I_ST_Score__c != null){
                                    finalLeadScore += Integer.valueOf(leadScoring.I_ST_Score__c);   
                                }
                            }
                        }
                        else if(leadScoring.I_ST_Operator__c.tolowercase() == ('VALIDPOSTCODE').tolowercase()){
                            if(!String.IsBlank(String.valueof(sObjectRecord.get(fieldName)))){
                                if(String.valueof(sObjectRecord.get(fieldName)).length() < 5){
                                    if(leadScoring.I_ST_Score__c != null){
                                        finalLeadScore += Integer.valueOf(leadScoring.I_ST_Score__c);   
                                    }
                                } 
                            }
                        }
                    }
                }
                sObjectRecord.put(sObjectIncrementScorefield,finalLeadScore);
                
               if(sObjectName.equalsIgnoreCase('I_RM_Affiliation__c')){
                    sObjectRecord.put('I_RM_Calculate_Affiliation_Score__c',false);
                }
                if(sObjectName.equalsIgnoreCase('Case')){
                    Map<Id,Case> caseOldMap = (Map<Id,Case>)oldMap;
                    //If the finalScore on Case record changes, update the Prior score value to the Prior_Incremental_Score__c field which is used in the Activity Scoring batch
                    //Also, update I_ST_Score_Calculated__c = false so that the updated record is picked up by the batch again
                    if(caseOldMap!= null && (finalLeadScore != caseOldMap.get(sObjectRecord.Id).I_ST_Incremental_Score__c)) {
                        sObjectRecord.put('I_ST_Prior_Incremental_Score__c',caseOldMap.get(sObjectRecord.Id).I_ST_Incremental_Score__c); 
                        sObjectRecord.put('I_ST_Score_Calculated__c',false);
                    }
                }
                lstUpdatedRecord.add(sObjectRecord);
            }
        }
        system.debug('lstUpdatedRecord :'+lstUpdatedRecord);
        return lstUpdatedRecord;        
    }
    
}