force-app/main/default/objects/Apex_Debug_Log__c/Apex_Debug_Log__c.object-meta.xml
<CustomObject>
    <description>Captures results of non-user facing transactions such as Apex endpoints, callouts and asynchronous jobs</description>
    <label>Apex Debug Log</label>
    <nameField>
        <displayFormat>ADL-{00000000}</displayFormat>
        <label>Apex Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/I_RM_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Part of the remediation project to store different personas</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Contact__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Contact__c</fullName>
    <description>The person/contact who this Affiliation relates to</description>
    <inlineHelpText>The person this affiliation relates to</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Affiliations</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Country__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Country__c</fullName>
    <description>Country of the Work/Home address</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>I_RM_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Data_Source__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Data_Source__c</fullName>
    <description>Technical Field. Global picklist to represent the original source of the record</description>
    <label>Data Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Data_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Email__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Email__c</fullName>
    <description>Depicts Personal Email</description>
    <inlineHelpText>The personal email for this person.</inlineHelpText>
    <label>Personal Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Mailing_Country__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Mailing_Country__c</fullName>
    <description>Mailing Address Country</description>
    <label>Mailing Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>I_RM_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Mailing_Postcode__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Mailing_Postcode__c</fullName>
    <description>Mailing Address Postcode</description>
    <label>Mailing Postcode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Mailing_State__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Mailing_State__c</fullName>
    <description>Mailing Address State</description>
    <label>Mailing State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Mailing_Street__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Mailing_Street__c</fullName>
    <description>Mailing Address Street</description>
    <label>Mailing Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Mailing_Suburb__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Mailing_Suburb__c</fullName>
    <description>Mailing Address Suburb</description>
    <label>Mailing City/Suburb</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Mobile_Phone__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Mobile_Phone__c</fullName>
    <description>Depicts affiliation&apos;s Mobile Phone number</description>
    <label>Mobile Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Other_Phone__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Other_Phone__c</fullName>
    <description>Depicts affiliation&apos;s Work Phone number</description>
    <label>Work Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Phone__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Phone__c</fullName>
    <description>Depicts affiliation&apos;s Home Phone number</description>
    <label>Home Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Postcode__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Postcode__c</fullName>
    <description>Post Code of work / home address.</description>
    <label>Postcode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Role__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Role__c</fullName>
    <description>This represents the role of the affiliation</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Domestic Lead</fullName>
                <label>Student Lead (Dom)</label>
            </value>
            <value>
                <fullName>Applicant</fullName>
                <label>Student Applicant (Dom)</label>
            </value>
            <value>
                <fullName>La Trobe Staff</fullName>
            </value>
            <value>
                <fullName>School Representative</fullName>
                <label>Secondary School Representative</label>
            </value>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>External Contact</fullName>
            </value>
            <value>
                <fullName>HDR Student</fullName>
                <label>Graduate Researcher</label>
            </value>
            <value>
                <fullName>Student Lead (Int)</fullName>
            </value>
            <value>
                <fullName>Nominated Affiliation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_StartDate__c.field-meta.xml
<CustomField>
    <fullName>I_RM_StartDate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Depicts Affiliations Start Date</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_State__c.field-meta.xml
<CustomField>
    <fullName>I_RM_State__c</fullName>
    <description>State of the Work/Home address</description>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <description>Indicates the status of the Affiliation.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>I_RM_Role__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>I_ST_Contact_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Street__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Street__c</fullName>
    <description>Street of the Work/Home address</description>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Suburb__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Suburb__c</fullName>
    <description>Suburb of the Work/Home address</description>
    <label>City/Suburb</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_Alumni.recordType-meta.xml
<RecordType>
    <fullName>I_RM_Alumni</fullName>
    <active>true</active>
    <description>An individual who has graduated from La Trobe University</description>
    <label>Alumni</label>
</RecordType>

force-app/main/default/objects/I_ST_Student_Course__c/I_ST_Student_Course__c.object-meta.xml
<CustomObject>
    <description>Junction object between Student (Contact) and Course (Course Availability)</description>
    <label>Student Course</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>Student Course Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_ST_Student_Course__c/fields/I_RM_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Affiliation</description>
    <label>Affiliation</label>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>Student Courses</relationshipLabel>
    <relationshipName>Student_Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/I_ST_Student_Course__c/fields/I_ST_Student__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Student__c</fullName>
    <description>Student lookup as per IST-43,IST-168</description>
    <label>Student</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Courses</relationshipLabel>
    <relationshipName>Student_Courses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Data_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Data Migration</fullName>
    </customValue>
    <customValue>
        <fullName>Admin Created</fullName>
    </customValue>
    <customValue>
        <fullName>HR Integration</fullName>
    </customValue>
    <customValue>
        <fullName>Self Nominated</fullName>
    </customValue>
    <customValue>
        <fullName>Finance Integration</fullName>
    </customValue>
    <customValue>
        <fullName>RP Integration</fullName>
    </customValue>
    <customValue>
        <fullName>SIS Integration</fullName>
    </customValue>
    <customValue>
        <fullName>MyPub Integration</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Integration</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
    </customValue>
    <customValue>
        <fullName>SFDC001</fullName>
    </customValue>
    <customValue>
        <fullName>SFDC009</fullName>
    </customValue>
    <customValue>
        <fullName>SFDC010</fullName>
    </customValue>
    <customValue>
        <fullName>SFDC012</fullName>
    </customValue>
    <customValue>
        <fullName>Remediation</fullName>
    </customValue>
    <customValue>
        <fullName>QSES</fullName>
    </customValue>
    <customValue>
        <fullName>Zoho</fullName>
    </customValue>
    <customValue>
        <fullName>Integration</fullName>
        <isActive>false</isActive>
        <label>Integration</label>
    </customValue>
    <customValue>
        <fullName>System</fullName>
        <isActive>false</isActive>
        <label>System</label>
    </customValue>
    <masterLabel>Data Source</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/I_RM_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Åland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Argentinian Antarctic Territory</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Australian Antarctic Territory</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas (the)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia (Plurinational State of)</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/I_ST_Contact_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Admitted</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And LOA</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Not Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Considered</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Made</fullName>
    </customValue>
    <customValue>
        <fullName>Await Academic Advice</fullName>
    </customValue>
    <customValue>
        <fullName>Await Applicant Comms</fullName>
    </customValue>
    <customValue>
        <fullName>Await Further Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Awaiting Interview</fullName>
    </customValue>
    <customValue>
        <fullName>Await Required Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Escalated</fullName>
    </customValue>
    <customValue>
        <fullName>Make A Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make Alternate Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make An Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Nearing Completion</fullName>
    </customValue>
    <customValue>
        <fullName>Not Processed</fullName>
    </customValue>
    <customValue>
        <fullName>Not Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Lapsed</fullName>
    </customValue>
    <customValue>
        <fullName>Other Preference Offered</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Results</fullName>
    </customValue>
    <customValue>
        <fullName>Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <description>Global value set is created for lead(contact) object ST -51</description>
    <masterLabel>I_ST_Contact_Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/I_ST_Student_CourseTriggerHelper.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* I_ST_Student_Course__c Trigger Helper
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Rahul Kumar
* @version        1.0
* @created        2021-03-23
* Description     LTU360-1314 Create alumini affiliation based on student course enrolment "Stage and Status"
* @Modified by Vanita Walia on 06/04/2022 - update the code to resolve defect LTU360-1448 
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/
public with sharing class I_ST_Student_CourseTriggerHelper {
    
    public static List<Apex_Debug_Log__c> errorLogs = new List<Apex_Debug_Log__c>();
    
    public static void createAlumni(List<I_ST_Student_Course__c> StudentCourselist){
        //variable initialization
    	set<ID> studentIdSet =new set<ID>(); //set of contacts related to student courses
        set<Id> affSet = new Set<Id>();
        List<I_RM_Affiliation__c> newAlumni = new List<I_RM_Affiliation__c>();
    
        Id alumniRecordId = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Alumni').getrecordTypeId(); 
      	
      //fetch the contact Ids & affiliation Ids from studentCourse list and add it to respective sets
       for(I_ST_Student_Course__c course : StudentCourselist){
       		studentIdSet.add(course.I_ST_Student__c);
            affSet.add(course.I_RM_Affiliation__c);
      }
        
        
      // Check if the contact has any active alumni
        List<I_RM_Affiliation__c> availableAff =[select ID from I_RM_Affiliation__c where I_RM_Contact__c IN:studentIdSet AND I_RM_Role__c = 'Alumni' AND I_RM_Status__c = 'Active'];
      
        if(availableAff.isEmpty()){      	
          	for(I_RM_Affiliation__c studentAff : [select ID, I_RM_Contact__c, I_RM_Email__c, I_RM_Mobile_Phone__c, I_RM_Phone__c, I_RM_Other_Phone__c, I_RM_Street__c, I_RM_Suburb__c,
                                                  	  I_RM_State__c, I_RM_Postcode__c, I_RM_Country__c, I_RM_Mailing_Street__c, I_RM_Mailing_Suburb__c, I_RM_Mailing_State__c,
                                               		  I_RM_Mailing_Postcode__c, I_RM_Mailing_Country__c 
                                               		  from I_RM_Affiliation__c where I_RM_Contact__c IN: studentIdSet AND Id IN:affSet]){
				
                  //create new alumni affiliation with details from student affiliation
                  I_RM_Affiliation__c alumniAff = new I_RM_Affiliation__c();
                  alumniAff.RecordTypeId = alumniRecordId;
                  alumniAff.I_RM_Contact__c = studentAff.I_RM_Contact__c;
                  alumniAff.I_RM_Role__c = 'Alumni';
                  alumniAff.I_RM_StartDate__c = system.today();
                  alumniAff.I_RM_Status__c = 'Active';
                  alumniAff.I_RM_Email__c = studentAff.I_RM_Email__c;
                  alumniAff.I_RM_Mobile_Phone__c = studentAff.I_RM_Mobile_Phone__c;
                  alumniAff.I_RM_Phone__c = studentAff.I_RM_Phone__c;
                  alumniAff.I_RM_Other_Phone__c = studentAff.I_RM_Other_Phone__c;
                  alumniAff.I_RM_Street__c = studentAff.I_RM_Street__c;
                  alumniAff.I_RM_Suburb__c = studentAff.I_RM_Suburb__c;
                  alumniAff.I_RM_State__c = studentAff.I_RM_State__c;
                  alumniAff.I_RM_Postcode__c = studentAff.I_RM_Postcode__c;
                  alumniAff.I_RM_Country__c = studentAff.I_RM_Country__c;
                  alumniAff.I_RM_Mailing_Street__c = studentAff.I_RM_Mailing_Street__c;
                  alumniAff.I_RM_Mailing_Suburb__c = studentAff.I_RM_Mailing_Suburb__c;
                  alumniAff.I_RM_Mailing_State__c = studentAff.I_RM_Mailing_State__c;
                  alumniAff.I_RM_Mailing_Postcode__c = studentAff.I_RM_Mailing_Postcode__c;
                  alumniAff.I_RM_Mailing_Country__c = studentAff.I_RM_Mailing_Country__c;
                  alumniAff.I_RM_Data_Source__c = 'Salesforce'; 
              newAlumni.add(alumniAff);
          }
      }
        // Insert the alumni affiliation records and if any dml error comes add it to errorlogs
                if(newAlumni.size() >0 && schema.SObjectType.I_RM_Affiliation__c.isAccessible() && schema.SObjectType.I_RM_Affiliation__c.isCreateable()){                    
                	I_ST_Student_CourseTriggerHandler.hasFired = True; // Set hasFired to True to avoid recursion               	
                	List<Database.saveResult> saveResults = Database.Insert(newAlumni, false);
                   
                    errorLogs.addAll(GlobalUtility.constructErrorLogsForDMLErrors(saveResults, newAlumni, 'I_ST_Student_CourseTriggerHelper', 'createAlumni'));
                    insert errorLogs;  
        			errorLogs.clear();
        		}
  }
}