force-app/main/default/objects/Apex_Debug_Log__c/Apex_Debug_Log__c.object-meta.xml
<CustomObject>
    <description>Captures results of non-user facing transactions such as Apex endpoints, callouts and asynchronous jobs</description>
    <label>Apex Debug Log</label>
    <nameField>
        <displayFormat>ADL-{00000000}</displayFormat>
        <label>Apex Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Apex_Class_Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Method_Name__c</fullName>
    <label>Apex Class Method Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <description>The invoking class that created the record</description>
    <label>Apex Class Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <description>If an exception occurs, this is the main message</description>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <label>Log Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Logged_In_Salesforce_User__c.field-meta.xml
<CustomField>
    <fullName>Logged_In_Salesforce_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Logged In Salesforce User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Apex Debug Logs</relationshipLabel>
    <relationshipName>Apex_Debug_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Request_Data__c.field-meta.xml
<CustomField>
    <fullName>Request_Data__c</fullName>
    <description>The data used in the transaction. For Apex Services, this could be the data sent from an external service. For a callout, this could be the data being sent. For a batch, this could be the batch of records.</description>
    <label>Request Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/Funding_Opportunity_Staging__c.object-meta.xml
<CustomObject>
    <description>This object is to store funding opps coming from external system as a staging instance eg, Research Professional.</description>
    <label>Funding Opportunity Staging</label>
    <nameField>
        <label>Staging Funding Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/Deadline_Forecast__c.field-meta.xml
<CustomField>
    <fullName>Deadline_Forecast__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Received from Research Professional</description>
    <label>Deadline Forecast</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>Unique Id for the Research Opportunity from Research Professional. Unique Opportunity Id + Deadline</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_Bullet__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Bullet__c</fullName>
    <label>Bullet</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_Date_Added__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Date_Added__c</fullName>
    <label>Date Added</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_Deadline_Info__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Deadline_Info__c</fullName>
    <label>Deadline Info</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_Description__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_Discipline__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Discipline__c</fullName>
    <label>Discipline</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_Eligibility_Hosts__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Eligibility_Hosts__c</fullName>
    <label>Eligibility Hosts</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_Eligibility_Region_Code__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Eligibility_Region_Code__c</fullName>
    <description>All eligibility region codes for the funding opportunity from Research Professional</description>
    <label>Eligibility Region Code</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_Eligibility_Regions__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Eligibility_Regions__c</fullName>
    <description>All eligibility regions for the funding opportunity from Research Professional</description>
    <label>Eligibility Regions</label>
    <length>20000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Full_Name__c</fullName>
    <label>Full Name</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_Funders_Full_Webpage__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Funders_Full_Webpage__c</fullName>
    <label>Funders Full Webpage</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_Funders_Webpage__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Funders_Webpage__c</fullName>
    <label>Funders Webpage</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_Funding_Category__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Funding_Category__c</fullName>
    <label>Funding Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_Funding_Opportunity_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Funding_Opportunity_Sync_Status__c</fullName>
    <description>Track progress in terms of syncing to live Funding Opportunity object</description>
    <label>Funding Opportunity Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Region Not Eligible</fullName>
            </value>
            <value>
                <fullName>No Matching Funder in PRIME</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_Locale__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Locale__c</fullName>
    <label>Locale</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_Primary_Funder_Id__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Primary_Funder_Id__c</fullName>
    <description>Funder Id captured from RP</description>
    <label>Primary Funder Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_Primary_Funder_Name__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Primary_Funder_Name__c</fullName>
    <description>Primary funder name from research professional</description>
    <label>Primary Funder Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_Primary_Funder_Region__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Primary_Funder_Region__c</fullName>
    <description>Funder region received from Research professional</description>
    <label>Primary Funder Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_Primary_Funder_Region_Code__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Primary_Funder_Region_Code__c</fullName>
    <description>Funder region code received from Research Professional</description>
    <label>Primary Funder Region Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_PRIME_Ready__c.field-meta.xml
<CustomField>
    <fullName>I_RS_PRIME_Ready__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PRIME Ready</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_Purpose__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Purpose__c</fullName>
    <label>Purpose</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_Research_Professional_Webpage__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Research_Professional_Webpage__c</fullName>
    <label>Research Professional Webpage</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_RP_ID__c.field-meta.xml
<CustomField>
    <fullName>I_RS_RP_ID__c</fullName>
    <label>RP ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/fields/I_RS_Submission_Date__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Submission_Date__c</fullName>
    <label>Submission Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ResearchProfessionalServiceProcess.cls
public with sharing class ResearchProfessionalServiceProcess {
    
    public static Map<String,Account> mapAccoutWithIds;
    public static Map<String,Account> mapAccountWithName;
    
    
    public static Boolean opportunityStagingRecordProcess(ResearchProfessionalWrapper objRPWrapper, String eligiblityRegions){
        
        List<Funding_Opportunity_Staging__c> lstFundOppStg = new List<Funding_Opportunity_Staging__c>();
        
        String eligibleSeparator = (Label.RP_Eligibility_Separator != null)? Label.RP_Eligibility_Separator : '|';
        //getAccounts();
        if(objRPWrapper != null && objRPWrapper.records.size()  > 0){
            
            try{
                
                Funding_Opportunity_Staging__c objOppStg;
                for( ResearchProfessionalWrapper.Records recs : objRPWrapper.records){
                     objOppStg = new Funding_Opportunity_Staging__c();
                    //Get Opportunity staging name field length and trucate the Opportunity name according to maximum text length.
                    Schema.DescribeFieldResult F = Funding_Opportunity_Staging__c.Name.getDescribe();
					Integer namelength = F.getLength();
                    
                    objOppStg.External_Id__c = String.valueOf(recs.id);
                    objOppStg.I_RS_RP_ID__c = String.valueOf(recs.id);
                    if(recs.name != null && recs.name.length() <= namelength)
                    	objOppStg.Name = recs.name;
                    else
                        objOppStg.Name = recs.name.substring(0, namelength);
                    objOppStg.I_RS_Full_Name__c = recs.name;
                    objOppStg.I_RS_Bullet__c = recs.bullet;
                    objOppStg.I_RS_Description__c  = recs.description;
                    objOppStg.I_RS_Locale__c = recs.locale;
                    if(recs.added != null){
                       objOppStg.I_RS_Date_Added__c =  Date.valueOf(recs.added);
                    }
                    objOppStg.I_RS_Deadline_Info__c = recs.deadlineInfo;
                    if(recs.webpage != null && recs.webpage.length() > 255)
                    	objOppStg.I_RS_Funders_Webpage__c  = recs.webpage.substring(0, 255);
                    else
                        objOppStg.I_RS_Funders_Webpage__c  = recs.webpage;
                    objOppStg.I_RS_Funders_Full_Webpage__c  = recs.webpage;
                    objOppStg.I_RS_Funding_Category__c = recs.australianFundingCategory;
                    if(recs.researchProfessionalWebpage != null && recs.researchProfessionalWebpage.length() > 255)
                    	objOppStg.I_RS_Research_Professional_Webpage__c = recs.researchProfessionalWebpage.substring(0, 255);
                    else
                        objOppStg.I_RS_Research_Professional_Webpage__c = recs.researchProfessionalWebpage;
                    
                    objOppStg.I_RS_Research_Professional_Webpage__c = recs.researchProfessionalWebpage;
                    // Check primary funder account in SFDC and map with Opportunity staging record. Else Create new Account and attach with Opportunity staging record. 
                    if(recs.primaryFunder != null){
                        
                        if(!String.isEmpty(String.valueOf(recs.primaryFunder.id)))
                            objOppStg.I_RS_Primary_Funder_Id__c = String.valueOf(recs.primaryFunder.id);
                        if(!String.isEmpty(recs.primaryFunder.name))
                            objOppStg.I_RS_Primary_Funder_Name__c = recs.primaryFunder.name;
                        if(recs.primaryFunder.region != null){
                            if(!String.isEmpty(recs.primaryFunder.region.name))
                                objOppStg.I_RS_Primary_Funder_Region__c = recs.primaryFunder.region.name;
                            if(!String.isEmpty(recs.primaryFunder.region.regionCode))
                                objOppStg.I_RS_Primary_Funder_Region_Code__c = recs.primaryFunder.region.regionCode;
                        }
                    }
                    //Check for disciplines info and add with '\r\n' separated values.
                    if(recs.disciplines != null && !recs.disciplines.isEmpty() && recs.disciplines.size() > 0 ){
                        for(ResearchProfessionalWrapper.Disciplines discp : recs.disciplines){
                            if(String.isEmpty(objOppStg.I_RS_Discipline__c))
                                objOppStg.I_RS_Discipline__c = discp.label;
                            else
                                objOppStg.I_RS_Discipline__c = objOppStg.I_RS_Discipline__c + '\r\n' + discp.label;
                        }
                    }
                    //Check for purpose info and add with '\r\n' separated values.
                    if(recs.purpose != null && recs.purpose.size() > 0 ){
                        for(ResearchProfessionalWrapper.Purpose purp : recs.purpose){
                            if(String.isEmpty(objOppStg.I_RS_Purpose__c))
                                objOppStg.I_RS_Purpose__c = purp.name;
                            else
                                objOppStg.I_RS_Purpose__c = objOppStg.I_RS_Purpose__c + '\r\n' + purp.name;
                        }
                    }
                    //Check for eligibility info and add with '|' separated values.
                    if(recs.eligibility != null && !recs.eligibility.isEmpty() && recs.eligibility.size() > 0 ){
                        
                        for(ResearchProfessionalWrapper.Eligibility eligible : recs.eligibility){
                            
                            // Add eligibility Host information under Eligible child record.
                            if(!eligible.hosts.isEmpty() && eligible.hosts.size() >0){
                                for(String strHost : eligible.hosts){
                                    if(String.isEmpty(objOppStg.I_RS_Eligibility_Hosts__c))
                                        objOppStg.I_RS_Eligibility_Hosts__c = strHost;
                                    else
                                        objOppStg.I_RS_Eligibility_Hosts__c = objOppStg.I_RS_Eligibility_Hosts__c+ eligibleSeparator + strHost;
                                
                                }
                            }
                       
                            // Add eligibility Region information under parent Opportunity staging record.
                            if(!eligible.regions.isEmpty() && eligible.regions.size() >0){
                                for(ResearchProfessionalWrapper.Region rgion : eligible.regions){
                                    if(String.isEmpty(objOppStg.I_RS_Eligibility_Region_Code__c))
                                        objOppStg.I_RS_Eligibility_Region_Code__c = rgion.regionCode;
                                    else
                                        objOppStg.I_RS_Eligibility_Region_Code__c = (objOppStg.I_RS_Eligibility_Region_Code__c + eligibleSeparator + rgion.regionCode).left(255);
                                    
                                    if(String.isEmpty(objOppStg.I_RS_Eligibility_Regions__c))
                                        objOppStg.I_RS_Eligibility_Regions__c = rgion.name;
                                    else
                                        objOppStg.I_RS_Eligibility_Regions__c = objOppStg.I_RS_Eligibility_Regions__c + eligibleSeparator + rgion.name;
                                    

                                    if (!objOppStg.I_RS_PRIME_Ready__c){

                                        if (!String.isEmpty(rgion.name) && !String.isEmpty(eligiblityRegions) && 
                                            eligiblityRegions.containsIgnoreCase(rgion.name)) {
                                            objOppStg.I_RS_PRIME_Ready__c = true;
                                        }
                                        else { 
                                            objOppStg.I_RS_Funding_Opportunity_Sync_Status__c = 'Region Not Eligible';
                                        }

                                    }
                                    
                                }
                            }
                           
                        }
                     }
                    
                    if(recs.deadlines != null && !recs.deadlines.isEmpty() && recs.deadlines.size() > 0){
                        Funding_Opportunity_Staging__c objFOpp;
                        for(integer i =0; i < recs.deadlines.size() ; i++ ){
                            objFOpp = new Funding_Opportunity_Staging__c();
                            objFOpp = objOppStg.clone();
                            objFOpp.External_Id__c = String.valueOf(recs.id) + '_' + recs.deadlines[i].deadline;
                            //objFOpp.I_RS_Submission_Date__c = Date.parse(recs.deadlines[i].deadline);
                            System.debug('--> Deadline date is: '+ recs.deadlines[i].deadline);
                            objFOpp.I_RS_Submission_Date__c = (!String.isEmpty(recs.deadlines[i].deadline)) ? Date.valueOf(recs.deadlines[i].deadline) : null;
                            objFOpp.Deadline_Forecast__c = recs.deadlines[i].unconfirmed;
                            lstFundOppStg.add(objFOpp);
                        }
                    }
                }
                // Upsert Research Professional Funding Opportunity records into SFDC's Funding Opportunity Staging object.
                Schema.SObjectField extField = Funding_Opportunity_Staging__c.Fields.External_Id__c;
                List<Apex_Debug_Log__c> errorLogs = new List<Apex_Debug_Log__c>();
                try{
                    Database.UpsertResult [] results = Database.upsert(lstFundOppStg,extField,false);
                    Set<String> OppStagingIds = new Set<String>();
                    // On Successfull Upsert of Funding Opportunity staging records, Set the Parent Id into respective eligibility child records .
                    for(Integer index = 0, size = results.size(); index < size; index++) {
                        if(results[index].isSuccess()) {
                         }
                        else{
                            List<String> errorMessages = new List<String>();
                            for(Database.Error err : results[index].getErrors()) {
                                errorMessages.add(err.getMessage());
                            }
                            errorLogs.add(
                                new Apex_Debug_Log__c(
                                    Apex_Class_Name__c = 'ResearchProfessionalServiceProcess',
                                    Apex_Class_Method_Name__c = 'opportunityStagingRecordProcess',
                                    Exception_Message__c = String.join(errorMessages, '; '),
                                    Log_Type__c = 'Error',
                                    Logged_In_Salesforce_User__c = UserInfo.getUserId(),
                                    Request_Data__c = JSON.serialize(lstFundOppStg[index]).left(100000)
                                )
                            );
                        }
                    }
                    if (!errorLogs.isEmpty()){
                        insert errorLogs;
                    }

                }
                catch(DmlException e){
                    System.debug('Error in upserting funding opportunity staging records - ' + e.getMessage());
                }
            }
            catch(exception ex){
                System.debug(ex.getMessage());
            }
            
        }
        return true;
    }
  
    
}