force-app/main/default/objects/Apex_Debug_Log__c/Apex_Debug_Log__c.object-meta.xml
<CustomObject>
    <description>Captures results of non-user facing transactions such as Apex endpoints, callouts and asynchronous jobs</description>
    <label>Apex Debug Log</label>
    <nameField>
        <displayFormat>ADL-{00000000}</displayFormat>
        <label>Apex Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Apex_Class_Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Method_Name__c</fullName>
    <label>Apex Class Method Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <description>The invoking class that created the record</description>
    <label>Apex Class Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <description>If an exception occurs, this is the main message</description>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Exception_stack_trace__c.field-meta.xml
<CustomField>
    <fullName>Exception_stack_trace__c</fullName>
    <description>If an exception occurs, this is the stack trace</description>
    <label>Exception stack trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <label>Log Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Logged_In_Salesforce_User__c.field-meta.xml
<CustomField>
    <fullName>Logged_In_Salesforce_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Logged In Salesforce User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Apex Debug Logs</relationshipLabel>
    <relationshipName>Apex_Debug_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Related_To_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Id__c</fullName>
    <description>An optional record to relate this Activity to</description>
    <label>Related To Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Request_Data__c.field-meta.xml
<CustomField>
    <fullName>Request_Data__c</fullName>
    <description>The data used in the transaction. For Apex Services, this could be the data sent from an external service. For a callout, this could be the data being sent. For a batch, this could be the batch of records.</description>
    <label>Request Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Response_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Response_Status_Code__c</fullName>
    <description>For a web call, this is the status. Would commonly be 200 for a success and 400 for a failure.</description>
    <label>Response Status Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Transaction_Description__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Description__c</fullName>
    <description>Within the Apex Class and Method Name, give additional details on where/why this logging is happening. For example, two logs could happen in the same method - one is &apos;Save record&apos; and another is &apos;Schedule Batch&apos;.</description>
    <label>Transaction Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>Used to distinguish the system context of this transaction</description>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apex REST Service</fullName>
            </value>
            <value>
                <fullName>Apex SOAP Service</fullName>
            </value>
            <value>
                <fullName>REST Callout</fullName>
            </value>
            <value>
                <fullName>SOAP Callout</fullName>
            </value>
            <value>
                <fullName>Batch</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Queueable/Future</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LoggerTest.cls
@isTest
public class LoggerTest {

    public static testmethod void positiveCase_AllData(){ 

        Account acc = TestUtility.newEmptyExternalAccount('Test account');
        insert acc;

        Test.startTest();
        
        Logger.log( 

            new Map<String, Object>{
                Logger.LOG_TYPE => Logger.LOG_TYPE_VALUE_ERROR,
                Logger.TRANSACTION_TYPE => Logger.TRANSACTION_TYPE_VALUE_SERVICE_REST,
                    
                Logger.RELATED_TO_ID => acc.id,
 
                Logger.CLASS_NAME => 'ClassName',
                Logger.CLASS_METHOD_NAME => 'MethodName',
                    
                Logger.TRANSACTION_DESCRIPTION => 'Some notes about the transaction go here - equivalent to a comment',

                Logger.EXCEPTION_MESSAGE => 'Error in class',
                Logger.EXCEPTION_STACK_TRACE => 'Line 9, row 1 million',

                Logger.REQUEST_DATA => 'Request Body',
                    
                Logger.RESPONSE_STATUS_CODE => 500

            });

        Test.stopTest();
        
        Apex_Debug_Log__c a = getLog();

        System.assert(a.Transaction_Type__c != null);
        System.assert(a.Log_Type__c != null);
        
        System.assert(a.Related_To_Id__c != null);

        System.assert(a.Apex_Class_Name__c != null);
        System.assert(a.Apex_Class_Method_Name__c != null);
        
        System.assert(a.Transaction_Description__c != null);

        System.assert(a.Exception_Message__c != null);
        System.assert(a.Exception_Stack_Trace__c != null);

        System.assert(a.Request_Data__c != null);

        System.assert(a.Response_Status_Code__c != null);
        
        System.assert(a.Logged_In_Salesforce_User__c != null);

    }



    public static testmethod void negativeCase_Empty(){
        Logger.log(new Map<String, Object>{});

        System.assertequals(1, [select count() from Apex_Debug_Log__c]);
    }
    
    
    public static testmethod void negativeCase_InvalidData(){
        
        String classNameTooLong = '12345678901234567890123456789012345678901234567890';
        
        Logger.log(

            new Map<String, Object>{
                Logger.CLASS_NAME => classNameTooLong
            }
        );
        
        System.assertequals(0, [select count() from Apex_Debug_Log__c]);
    }

    public static testmethod void testAttachments(){

        //Create long-ass strings (>200k chars)
        String longAssString = '';
        for (Integer i=1; i<=10000; i++){
            longAssString += '01234567890123456789';
        }
        
        Logger.log( 

            new Map<String, Object>{
                Logger.REQUEST_DATA => longAssString,
                Logger.RESPONSE_BODY => longAssString
            });
        
        //Check attachment file has been created
        Apex_Debug_Log__c a = [select Id from Apex_Debug_Log__c];
        
		System.assert([select Id from FeedItem].size() > 0, 'Creating attachment failed');        
        
    }
    
    static Apex_Debug_Log__c getLog(){
        return [select Id,
            Transaction_Type__c, Log_Type__c,
            Related_To_Id__c,
            Apex_Class_Name__c, Apex_Class_Method_Name__c,
            Transaction_Description__c,
			Exception_Message__c, Exception_Stack_Trace__c,
            Request_Data__c, Response_Status_Code__c,
			Logged_In_Salesforce_User__c
        	from Apex_Debug_Log__c][0];
    }
    
}