force-app/main/default/objects/Apex_Debug_Log__c/Apex_Debug_Log__c.object-meta.xml
<CustomObject>
    <description>Captures results of non-user facing transactions such as Apex endpoints, callouts and asynchronous jobs</description>
    <label>Apex Debug Log</label>
    <nameField>
        <displayFormat>ADL-{00000000}</displayFormat>
        <label>Apex Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Apex_Class_Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Method_Name__c</fullName>
    <label>Apex Class Method Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <description>The invoking class that created the record</description>
    <label>Apex Class Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <description>If an exception occurs, this is the main message</description>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <label>Log Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/I_RM_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Affiliation</description>
    <label>Affiliation</label>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/I_ST_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Contact_First_Name__c</fullName>
    <description>To get the first name from webforms and to create new contact if the contact doesn&apos;t exist</description>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/I_ST_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Contact_Last_Name__c</fullName>
    <description>To get the last name from webforms and to create new contact if the contact doesn&apos;t exist</description>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/I_ST_Position_Title__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Position_Title__c</fullName>
    <description>Created for IST 188</description>
    <label>Position Title</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/I_ST_Proposed_Activity_End_Datetime__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Proposed_Activity_End_Datetime__c</fullName>
    <description>Added for Activity booking web form</description>
    <label>Proposed Activity End Date and Time</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/I_ST_Proposed_Activity_Start_Datetime__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Proposed_Activity_Start_Datetime__c</fullName>
    <description>Proposed activity booking date and time provided by the requester</description>
    <label>Proposed Activity Start Date and Time</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/I_ST_Proposed_End_Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Proposed_End_Date_and_Time__c</fullName>
    <description>created for IST 308</description>
    <label>End Date and Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/I_ST_Proposed_Start_Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Proposed_Start_Date_and_Time__c</fullName>
    <description>created for IST 308</description>
    <label>Start Date and Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/I_ST_Residency_Citizenship_Status__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Residency_Citizenship_Status__c</fullName>
    <label>Residency / Citizenship Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Australian Citizen</fullName>
            </value>
            <value>
                <fullName>New Zealand Citizen</fullName>
            </value>
            <value>
                <fullName>Permanent Resident Of Australia</fullName>
            </value>
            <value>
                <fullName>Overseas Student Residing Overseas</fullName>
            </value>
            <value>
                <fullName>International Student Or Temporary Entry Visa Holder</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/I_ST_School_or_Educational_body__c.field-meta.xml
<CustomField>
    <fullName>I_ST_School_or_Educational_body__c</fullName>
    <label>School Or Educational Body</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/I_ST_Activity_Booking.recordType-meta.xml
<RecordType>
    <fullName>I_ST_Activity_Booking</fullName>
    <active>true</active>
    <businessProcess>IST Activity Booking</businessProcess>
    <description>Inbound Case received from Educational Institutes/Organisations for Tour/Event etc.</description>
    <label>Activity Booking</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/I_ST_Enquiry.recordType-meta.xml
<RecordType>
    <fullName>I_ST_Enquiry</fullName>
    <active>true</active>
    <businessProcess>IST ENQUIRY</businessProcess>
    <description>Inbound Case for SACE Team received via Phone/Email/Chat etc.</description>
    <label>Enquiry</label>
</RecordType>

force-app/main/default/objects/Contact/fields/I_RS_Residency_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Residency_Status__c</fullName>
    <inlineHelpText>International Student Lead is a candidate that is NOT an Australian citizen/New Zealand citizen/ Permanent Resident of Australia / Permanent humanitarian visa holder.</inlineHelpText>
    <label>Residency / Citizenship Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Australian Citizen</fullName>
            </value>
            <value>
                <fullName>New Zealand Citizen</fullName>
            </value>
            <value>
                <fullName>Permanent resident of Australia</fullName>
                <label>Permanent Resident Of Australia</label>
            </value>
            <value>
                <fullName>Permanent Humanitarian Visa Holder</fullName>
            </value>
            <value>
                <fullName>International Student or temporary entry visa holder</fullName>
                <label>International Student Or Temporary Entry Visa Holder</label>
            </value>
            <value>
                <fullName>Overseas Student Residing Overseas</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/I_ST_Personal_Email__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Personal_Email__c</fullName>
    <description>Created to allow user to store personal email</description>
    <externalId>true</externalId>
    <inlineHelpText>The personal email for this person.</inlineHelpText>
    <label>Student Lead Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/I_RM_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Part of the remediation project to store different personas</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Contact__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Contact__c</fullName>
    <description>The person/contact who this Affiliation relates to</description>
    <inlineHelpText>The person this affiliation relates to</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Affiliations</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Email__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Email__c</fullName>
    <description>Depicts Personal Email</description>
    <inlineHelpText>The personal email for this person.</inlineHelpText>
    <label>Personal Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Mobile_Phone__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Mobile_Phone__c</fullName>
    <description>Depicts affiliation&apos;s Mobile Phone number</description>
    <label>Mobile Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Other_Phone__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Other_Phone__c</fullName>
    <description>Depicts affiliation&apos;s Work Phone number</description>
    <label>Work Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Phone__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Phone__c</fullName>
    <description>Depicts affiliation&apos;s Home Phone number</description>
    <label>Home Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Role__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Role__c</fullName>
    <description>This represents the role of the affiliation</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Domestic Lead</fullName>
                <label>Student Lead (Dom)</label>
            </value>
            <value>
                <fullName>Applicant</fullName>
                <label>Student Applicant (Dom)</label>
            </value>
            <value>
                <fullName>La Trobe Staff</fullName>
            </value>
            <value>
                <fullName>School Representative</fullName>
                <label>Secondary School Representative</label>
            </value>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>External Contact</fullName>
            </value>
            <value>
                <fullName>HDR Student</fullName>
                <label>Graduate Researcher</label>
            </value>
            <value>
                <fullName>Student Lead (Int)</fullName>
            </value>
            <value>
                <fullName>Nominated Affiliation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <description>Indicates the status of the Affiliation.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>I_RM_Role__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>I_ST_Contact_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Student_Email__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Student_Email__c</fullName>
    <description>Depicts Students Email address</description>
    <inlineHelpText>The student email for this person.</inlineHelpText>
    <label>Student Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Work_Email__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Work_Email__c</fullName>
    <description>Depicts Work Email address</description>
    <inlineHelpText>Note: Graduate researchers, this is their institutional email (or staff email if they are also staff)</inlineHelpText>
    <label>Work Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_External_Contact.recordType-meta.xml
<RecordType>
    <fullName>I_RM_External_Contact</fullName>
    <active>true</active>
    <description>A Person external to La Trobe (i.e. partner)</description>
    <label>External Contact</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_Lead.recordType-meta.xml
<RecordType>
    <fullName>I_RM_Lead</fullName>
    <active>true</active>
    <description>New Domestic Lead who is a prospective student of La Trobe University</description>
    <label>Student Lead (Dom)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/I_RM_Affiliation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Affiliation Settings</label>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/I_RM_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Affiliation</description>
    <label>Affiliation</label>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Organisation_Alias__c/Organisation_Alias__c.object-meta.xml
<CustomObject>
    <label>Organisation Alias</label>
    <nameField>
        <displayFormat>A-{00}</displayFormat>
        <label>Organisation Alias Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organisation Aliases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Organisation_Alias__c/fields/I_RS_Organisation__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Organisation__c</fullName>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Organisation Aliases</relationshipLabel>
    <relationshipName>Organisation_Aliases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Organisation_Alias__c/fields/I_RS_Organisation_Name_Long__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Organisation_Name_Long__c</fullName>
    <externalId>true</externalId>
    <label>Organisation Name Long</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/I_ST_Contact_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Admitted</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And LOA</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Not Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Considered</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Made</fullName>
    </customValue>
    <customValue>
        <fullName>Await Academic Advice</fullName>
    </customValue>
    <customValue>
        <fullName>Await Applicant Comms</fullName>
    </customValue>
    <customValue>
        <fullName>Await Further Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Awaiting Interview</fullName>
    </customValue>
    <customValue>
        <fullName>Await Required Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Escalated</fullName>
    </customValue>
    <customValue>
        <fullName>Make A Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make Alternate Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make An Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Nearing Completion</fullName>
    </customValue>
    <customValue>
        <fullName>Not Processed</fullName>
    </customValue>
    <customValue>
        <fullName>Not Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Lapsed</fullName>
    </customValue>
    <customValue>
        <fullName>Other Preference Offered</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Results</fullName>
    </customValue>
    <customValue>
        <fullName>Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <description>Global value set is created for lead(contact) object ST -51</description>
    <masterLabel>I_ST_Contact_Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/I_ST_CaseTriggerHelper.cls
/**
─────────────────────────────────────────────────────────────────────────────────────────────────┐
* I_ST_CaseTriggerHelper
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* @author Teja Yenduri
* @date 2022-02-18
* 

* LTU360-886   createLeadAffiliation method is used to copy Attributes to the Domestic Lead Affiliation if an enquiry is raised.
* @description : This class is used For Case trigger helper methods
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/

public  without sharing class I_ST_CaseTriggerHelper {
    public static Id caseEnquiryId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('I_ST_Enquiry').getrecordTypeId();
    public static ID leadRecordID = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Lead').getrecordTypeId();
    public static Id caseActivityBooking = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('I_ST_Activity_Booking').getrecordTypeId();
    public static Id CASE_INT_ENQUIRY_RECTYPE_ID = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(GlobalConstants.CASE_RECORD_TYPE_NAME_INT_ENQUIRY).getRecordTypeId();
    public static Id AFFILIATION_INT_LEAD_RECTYPE_ID = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get(GlobalConstants.AFFILIATION_RECORD_TYPE_NAME_INT_LEAD).getRecordTypeId();
    public static List<Id> IDS_THAT_REQUIRE_CONTACT_UPSERT = new List<Id>{
        caseEnquiryId,
        caseActivityBooking,
        CASE_INT_ENQUIRY_RECTYPE_ID
    };
    public static List<Id> IDS_THAT_REQUIRE_AFFILIATION_UPSERT = new List<Id>{
        caseEnquiryId,
        CASE_INT_ENQUIRY_RECTYPE_ID
    };
    public static Id AffiliationExternalContact = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_External_Contact').getrecordTypeId();
    public static List<String> inactiveStatus = [SELECT I_RM_Status__c FROM I_RM_Affiliation_Settings__c WHERE Name =:GlobalConstants.I_RM_AFFILIATION_SETTINGS].I_RM_Status__c.split(',');    
    public static string APPLICANT='Applicant';
    public static string DOMESTICLEAD='Domestic Lead';
    public static string INTERNATIONAL_LEAD_ROLE = 'Student Lead (Int)';
    public static string SCHOOLREPRESENTATIVE='School Representative';
    public static List<String> ROLES_THAT_REQUIRE_AFFILIATION_UPSERT = new List<String>{
        APPLICANT,
        DOMESTICLEAD,
        INTERNATIONAL_LEAD_ROLE
    };

    public static void updateContactOnCase(List<Case> caseList){
        Set<String> keysToMatch = new Set<String>();
        Set<String> emailKeysToMatch = new Set<String>();
        Set<String> phoneKeysToMatch = new Set<String>();
        Map<String,Case> caseMapToContact= new Map<String,Case>();
        
        
        
        for(case caseDetail:caseList){
            //if suppliedemail is not null match the affiliation email with the case supplied email and link matching contact to case.
            //query on affiliation with email find matching affiliation.contactId. 
            //if contact id is exists link to currect case.
            //if not than create contact and link to case.
            String firstName, lastName, keyStr;
            firstName = caseDetail.I_ST_Contact_First_Name__c;
            lastName = caseDetail.I_ST_Contact_Last_Name__c; 
            if( IDS_THAT_REQUIRE_CONTACT_UPSERT.contains(caseDetail.RecordTypeId) && 
                caseDetail.ContactId == null
            ){
                if(caseDetail.SuppliedEmail!=null){
                    caseMapToContact.put(caseDetail.SuppliedEmail,caseDetail);
                    emailKeysToMatch.add(caseDetail.SuppliedEmail);
                    keysToMatch.add(caseDetail.SuppliedEmail);
                }else if(caseDetail.SuppliedPhone!=null){
                    keyStr = (!String.isBlank(firstName)) ? (caseDetail.SuppliedPhone + firstName)
                                                          : caseDetail.SuppliedPhone;
                    keyStr = (!String.isBlank(lastName)) ? (keyStr + lastName)
                                                         : keyStr;
                    caseMapToContact.put(keyStr,caseDetail); //added SuppliedPhone as key insted of keyStr
                    phoneKeysToMatch.add(caseDetail.SuppliedPhone);
                    keysToMatch.add(caseDetail.SuppliedPhone);
                }
                
            }
            if(caseDetail.RecordTypeId == caseActivityBooking){
                    if(caseDetail.I_ST_Proposed_Activity_Start_Datetime__c!=NULL) {
                        caseDetail.I_ST_Proposed_Start_Date_and_Time__c=datetime.valueOf(caseDetail.I_ST_Proposed_Activity_Start_Datetime__c);
                    }
                    if(caseDetail.I_ST_Proposed_Activity_End_Datetime__c!=NULL) {
                        caseDetail.I_ST_Proposed_End_Date_and_Time__c=datetime.valueOf(caseDetail.I_ST_Proposed_Activity_End_Datetime__c);
                    }
                    
                    
                }
        }
        if(!emailKeysToMatch.isEmpty()) {

            keysToMatch.addAll(emailKeysToMatch);

        }

        if(!phoneKeysToMatch.isEmpty()) {

            keysToMatch.addAll(phoneKeysToMatch);

        }
        
        //First get the affilations, populate the ContactID from the affiliation to Case
        //<----->
        
        map<string,string> caseContactMap=new  map<string,string>();
        Map<String,Case> caseCreateContactMap=new Map<String,Case>();
        
        List<I_RM_Affiliation__c> affliationList = new List<I_RM_Affiliation__c>();

        if(!emailKeysToMatch.isEmpty() && !phoneKeysToMatch.isEmpty()) {

            affliationList = [SELECT I_RM_Contact__c,I_RM_Contact__r.id,I_RM_Mobile_Phone__c,I_RM_Contact__r.Name, CreatedDate,

                                     I_RM_Email__c,I_RM_Work_Email__c,I_RM_Student_Email__c,I_RM_Contact__r.FirstName,I_RM_Contact__r.LastName,

                                     I_RM_Phone__c,I_RM_Other_Phone__c, I_RM_Role__c, I_RM_Status__c, RecordTypeId

                              FROM I_RM_Affiliation__c

                              WHERE (I_RM_Email__c IN : emailKeysToMatch OR

                                     I_RM_Student_Email__c IN : emailKeysToMatch OR

                                     I_RM_Work_Email__c IN : emailKeysToMatch OR

                                     I_RM_Mobile_Phone__c IN : phoneKeysToMatch OR

                                     I_RM_Phone__c IN : phoneKeysToMatch OR

                                     I_RM_Other_Phone__c IN : phoneKeysToMatch

                                    )

                              ORDER BY CreatedDate DESC];    

        }
        else if(!emailKeysToMatch.isEmpty()) {

            affliationList = [SELECT I_RM_Contact__c,I_RM_Contact__r.id,I_RM_Mobile_Phone__c,I_RM_Contact__r.Name, CreatedDate,

                                     I_RM_Email__c,I_RM_Work_Email__c,I_RM_Student_Email__c,I_RM_Contact__r.FirstName,I_RM_Contact__r.LastName,

                                     I_RM_Phone__c,I_RM_Other_Phone__c, I_RM_Role__c, I_RM_Status__c, RecordTypeId

                              FROM I_RM_Affiliation__c

                              WHERE (I_RM_Email__c IN : emailKeysToMatch OR

                                     I_RM_Student_Email__c IN : emailKeysToMatch OR

                                     I_RM_Work_Email__c IN : emailKeysToMatch

                                    )

                              ORDER BY CreatedDate DESC];    

        }
        else if(!phoneKeysToMatch.isEmpty()) {

            affliationList = [SELECT I_RM_Contact__c,I_RM_Contact__r.id,I_RM_Mobile_Phone__c,I_RM_Contact__r.Name, CreatedDate,

                                     I_RM_Email__c,I_RM_Work_Email__c,I_RM_Student_Email__c,I_RM_Contact__r.FirstName,I_RM_Contact__r.LastName,

                                     I_RM_Phone__c,I_RM_Other_Phone__c, I_RM_Role__c, I_RM_Status__c, RecordTypeId

                              FROM I_RM_Affiliation__c

                              WHERE (I_RM_Mobile_Phone__c IN : phoneKeysToMatch OR

                                     I_RM_Phone__c IN : phoneKeysToMatch OR

                                     I_RM_Other_Phone__c IN : phoneKeysToMatch

                                    )

                              ORDER BY CreatedDate DESC];    

        }

      
        for(case cse:caseList){   
            if(((cse.I_ST_Contact_First_Name__c != NULL && cse.I_ST_Contact_Last_Name__c !=NULL && cse.SuppliedPhone != NULL)
                || (cse.SuppliedName != NULL && cse.SuppliedPhone != NULL)) || cse.SuppliedEmail != NULL){
                    for(I_RM_Affiliation__c aff:affliationList){
                        String phoneKeyStr = aff.I_RM_Phone__c + aff.I_RM_Contact__r.FirstName + aff.I_RM_Contact__r.LastName;
                        String mobileKeyStr = aff.I_RM_Mobile_Phone__c + aff.I_RM_Contact__r.FirstName + aff.I_RM_Contact__r.LastName;                                        
                        String OtherphoneKeyStr = aff.I_RM_Other_Phone__c + aff.I_RM_Contact__r.FirstName + aff.I_RM_Contact__r.LastName; 
                        if ((caseMapToContact.containskey(aff.I_RM_Email__c)) || (caseMapToContact.containskey(aff.I_RM_Student_Email__c))|| 
                            (caseMapToContact.containskey(aff.I_RM_Work_Email__c)) || (caseMapToContact.containskey(phoneKeyStr)) || 
                            (caseMapToContact.containskey(mobileKeyStr)) || (caseMapToContact.containskey(OtherphoneKeyStr))){
                                
                                if(caseContactMap.get(cse.Id)==null){
                                    caseContactMap.put(cse.Id, aff.I_RM_Contact__c);  
                                }
                                
                            }
                        
                    }
                    
                }
        }
        if(caseContactMap.isEmpty() && affliationList.size()==0 && keysToMatch.size()>0 ){
            for(case cse:caseList){
                if(caseCreateContactMap.get(cse.id)==null)
                    caseCreateContactMap.put(cse.id,cse);
            }
        }
        map<string,case> contactCaseMapToUpdate=new  map<string,case>();
        if(!caseContactMap.isEmpty()){
            for(case cse:caseList){
                cse.ContactId=caseContactMap.get(cse.Id);
                if(cse.I_ST_Residency_Citizenship_Status__c!=null || cse.SuppliedEmail!=null){
                    contactCaseMapToUpdate.put( cse.ContactId, cse);
                    
                }
                
                
            }
            if(contactCaseMapToUpdate!=null){
                updateContact(contactCaseMapToUpdate);
            }
        }
        if(caseContactMap.isEmpty() && !caseCreateContactMap.isEmpty()){
            map<string,string> caseContactIDMap=getContactList(caseCreateContactMap);
            if(!caseContactIDMap.isEmpty()){
                for(case cse:caseList){
                    if(caseCreateContactMap.get(cse.Id)!=null && caseContactIDMap.get(cse.Id)!=null){
                        
                        cse.ContactId=caseContactIDMap.get(cse.Id);
                        
                    }
                }
            }
            
        }
    }
    
    private static void updateContact(map<string,case> contactCaseMapToUpdate){
        List<contact> contactList=new  List<contact>();
        for(contact contactDetail:[SELECT I_ST_Personal_Email__c,I_RS_Residency_Status__c FROM contact WHERE  Id=:contactCaseMapToUpdate.keyset()]){
            contactDetail.I_ST_Personal_Email__c=contactCaseMapToUpdate.get(contactDetail.Id).SuppliedEmail;
            contactDetail.I_RS_Residency_Status__c=contactCaseMapToUpdate.get(contactDetail.Id).I_ST_Residency_Citizenship_Status__c;
            contactList.add(contactDetail);
        }
        if(contactList.size()>0){
            update contactList;
        }
    }
    private static map<string,string> getContactList( Map<String,Case> caseCreateContactMap){
        list<Contact> contactList=new list<Contact>();
        List<Case> caseErrorList=new List<Case>();
        map<string,string> newContactKeyStrMap=new map<string,string>();
        for(string caseID: caseCreateContactMap.keySet()){
            if(caseCreateContactMap.get(caseID).Origin =='Email' && caseCreateContactMap.get(caseID).suppliedName!=null){
               
                Contact con = new Contact();
                con.FirstName = caseCreateContactMap.get(caseID).suppliedName.SubStringBefore(' ');
                con.LastName = caseCreateContactMap.get(caseID).suppliedName.SubStringAfter(' ');
                con.Title = caseCreateContactMap.get(caseID).I_ST_Position_Title__c;
                con.I_ST_Personal_Email__c = caseCreateContactMap.get(caseID).SuppliedEmail;
                con.MobilePhone = caseCreateContactMap.get(caseID).SuppliedPhone;
                con.I_RS_Residency_Status__c = caseCreateContactMap.get(caseID).I_ST_Residency_Citizenship_Status__c;
                String keyStr = caseCreateContactMap.get(caseID).SuppliedEmail;
                if (String.isBlank(keyStr)){
                    keyStr = caseCreateContactMap.get(caseID).SuppliedPhone + con.FirstName +  con.LastName;    
                }
                newContactKeyStrMap.put(keyStr,caseID); 
                contactList.add(con);
            }else if(caseCreateContactMap.get(caseID).Origin !='Email' && caseCreateContactMap.get(caseID).I_ST_Contact_First_Name__c!=null && caseCreateContactMap.get(caseID).I_ST_Contact_Last_Name__c!=null){
              
                Contact con = new Contact();
                con.FirstName = caseCreateContactMap.get(caseID).I_ST_Contact_First_Name__c;
                con.LastName = caseCreateContactMap.get(caseID).I_ST_Contact_Last_Name__c;
                con.Title = caseCreateContactMap.get(caseID).I_ST_Position_Title__c;
                con.I_ST_Personal_Email__c = caseCreateContactMap.get(caseID).SuppliedEmail;
                con.MobilePhone = caseCreateContactMap.get(caseID).SuppliedPhone;
                con.I_RS_Residency_Status__c = caseCreateContactMap.get(caseID).I_ST_Residency_Citizenship_Status__c;
                String keyStr = caseCreateContactMap.get(caseID).SuppliedEmail;
                if (String.isBlank(keyStr)){
                    keyStr = caseCreateContactMap.get(caseID).SuppliedPhone + con.FirstName  + con.LastName;    
                }
                newContactKeyStrMap.put(keyStr,caseID); 
                contactList.add(con);
            }
            else if(caseCreateContactMap.get(caseID).Origin !='Email' && caseCreateContactMap.get(caseID).Origin != 'Chat' && caseCreateContactMap.get(caseID).I_ST_Contact_First_Name__c==null && caseCreateContactMap.get(caseID).I_ST_Contact_Last_Name__c==null){
                
                caseErrorList.add(caseCreateContactMap.get(caseID));
            }
        }
        if(caseErrorList.size()>0){
            List<Apex_Debug_Log__c> insertDebugStatement = new List<Apex_Debug_Log__c>();
            for(case caseDetail:caseErrorList){
                Apex_Debug_Log__c debugLog2 = new Apex_Debug_Log__c();
                debugLog2.Apex_Class_Name__c = 'I_ST_CaseTriggerHelper';
                debugLog2.Apex_Class_Method_Name__c = 'updateContactOnCase';
                debugLog2.Exception_message__c = 'FirstName and LastName Not Available To Create Contact::' + caseDetail.Subject;
                debugLog2.Log_Type__c = 'Error';
                insertDebugStatement.add(debugLog2);
            }
            if(insertDebugStatement.size()>0){
                insert insertDebugStatement;
            }
        }
        map<string,string> caseContactIDMap=new map<string,string>();
        set<string> contactSetID=new set<string>();
         
        if(contactList.size()>0){
            
            try{                
                List<Database.upsertResult> uResults = Database.upsert(contactList,false);                
                for(Database.upsertResult result:uResults) {
                    if (result.isSuccess() && result.isCreated()) 
                        contactSetID.add(result.getId());
                }
            }
            catch(dmlException ex){
                Apex_Debug_Log__c debugLog2 = new Apex_Debug_Log__c();
                debugLog2.Apex_Class_Name__c = 'I_ST_CaseTriggerHelper';
                debugLog2.Apex_Class_Method_Name__c = 'updateContactOnCase';
                debugLog2.Exception_message__c = ex.getMessage();
                debugLog2.Log_Type__c = 'Error';
                insert debugLog2;
            }
            
        }  
        for(contact contactDetail:[SELECT I_ST_Personal_Email__c,MobilePhone,FirstName,LastName FROM Contact where id=:contactSetID]){
            string emailStr = contactDetail.I_ST_Personal_Email__c;
            if (String.isBlank(emailStr)){
                emailStr = contactDetail.MobilePhone + contactDetail.FirstName + contactDetail.LastName;    
            }
            caseContactIDMap.put(newContactKeyStrMap.get(emailStr), contactDetail.Id);
        }
        if(caseContactIDMap!=null){
            return caseContactIDMap;
        }else {
            return null;
        }
    }

    public static void updateAffiliation(List<Case> caseList) {
        List<String> orgNames = new List<String>();
        for(case caseDetail:caseList){
            orgNames.add(caseDetail.I_ST_School_or_Educational_body__c);
        }
        
        Map<String, Organisation_Alias__c> accountAliasIdMap = new Map<String, Organisation_Alias__c>();
        for(Organisation_Alias__c acc: [SELECT I_RS_Organisation__c,Name,I_RS_Organisation__r.Name,I_RS_Organisation_Name_Long__c 
                                        FROM Organisation_Alias__c 
                                        WHERE I_RS_Organisation_Name_Long__c IN : orgNames]){
                                            accountAliasIdMap.put(acc.I_RS_Organisation_Name_Long__c.toLowerCase(), acc);//ARC to arc as a key. 
                                           
                                        }
        I_ST_Anonymous_Edu_Inst__c DefaultAcc = I_ST_Anonymous_Edu_Inst__c.getInstance();
        Id defaultOrgId = null;
        
        if (accountAliasIdMap.isEmpty()){
            defaultOrgId =DefaultAcc.I_ST_Default_School_Name__c;
        }
        
        Set<String> contactIdSet=new Set<String>();
        set<string> roleSet=new set<string>();
        set<string> accountSet=new set<string>();
        for(Case caseDetail:caseList){
            if(caseDetail.I_RM_Affiliation__c==null){
                if(caseDetail.ContactId!=null){
                    contactIdSet.add(caseDetail.ContactId);
                    if(caseDetail.RecordTypeId == caseEnquiryId){
                        
                        roleSet.add(APPLICANT);
                        roleSet.add(DOMESTICLEAD);
                    }
                    else if(caseDetail.RecordTypeId == CASE_INT_ENQUIRY_RECTYPE_ID){
                        roleSet.add(INTERNATIONAL_LEAD_ROLE);
                    }
                    else if(caseDetail.RecordTypeId == caseActivityBooking){ 
                         
                        if (caseDetail.AccountId != null){
                            accountSet.add(caseDetail.AccountId);
                        }
                        else if (caseDetail.I_ST_School_or_Educational_body__c!=null && accountAliasIdMap.get(caseDetail.I_ST_School_or_Educational_body__c.toLowerCase()) <> null){
                            caseDetail.AccountId = accountAliasIdMap.get(caseDetail.I_ST_School_or_Educational_body__c.toLowerCase()).I_RS_Organisation__c;
                            accountSet.add(caseDetail.AccountId);
                        }
                        else {
                            caseDetail.AccountId = defaultOrgId;
                            accountSet.add(caseDetail.AccountId);
                        }
                        roleSet.add(SCHOOLREPRESENTATIVE);
                    }
                }
            }
        }
        map<id,I_RM_Affiliation__c> affilationMap=new map<id,I_RM_Affiliation__c>();
       
        for(I_RM_Affiliation__c   affiliation: [SELECT I_RM_Contact__c,I_RM_Contact__r.id,I_RM_Mobile_Phone__c,I_RM_Contact__r.Name, CreatedDate,
                                                I_RM_Email__c,I_RM_Work_Email__c,I_RM_Student_Email__c,I_RM_Contact__r.FirstName,I_RM_Contact__r.LastName,
                                                I_RM_Account__c, I_RM_Phone__c,I_RM_Other_Phone__c, I_RM_Role__c, I_RM_Status__c, RecordTypeId                          
                                                FROM I_RM_Affiliation__c WHERE I_RM_Contact__c = :contactIdSet 
                                                AND I_RM_Role__c IN:roleSet ORDER BY CreatedDate DESC]){
                                                    if( ROLES_THAT_REQUIRE_AFFILIATION_UPSERT.contains(affiliation.I_RM_Role__c)
                                                        && !affilationMap.containsKey(affiliation.I_RM_Contact__c) 
                                                        && !inactiveStatus.contains(affiliation.I_RM_Status__c)) 
                                                    {
                                                         affilationMap.put(affiliation.I_RM_Contact__c,affiliation);
                                                    }else if (!affilationMap.containsKey(affiliation.I_RM_Contact__c) && affiliation.I_RM_Role__c=='School Representative' && accountSet.contains(affiliation.I_RM_Account__c) && !inactiveStatus.contains(affiliation.I_RM_Status__c)){
                                                        affilationMap.put(affiliation.I_RM_Contact__c,affiliation);
                                                    }
                                                }
        
        Map<Id,Case> mapCases=new  Map<Id,Case>();
        Map<Id,Case> mapUpdateCases=new  Map<Id,Case>();
        
        for(Case caseDetail:caseList){
            
            if(caseDetail.I_RM_Affiliation__c==null && (caseDetail.RecordTypeId == caseActivityBooking)){
                if(!affilationMap.isEmpty() && 
                   affilationMap.get(caseDetail.ContactId)!=null && 
                   caseDetail.ContactId==affilationMap.get(caseDetail.ContactId).I_RM_Contact__c && 
                   caseDetail.AccountId ==affilationMap.get(caseDetail.ContactId).I_RM_Account__c && 
                   affilationMap.get(caseDetail.ContactId).I_RM_Role__c == 'School Representative' ){
                       
                       caseDetail.I_RM_Affiliation__c=affilationMap.get(caseDetail.ContactId).Id;
                   }else{
                       mapCases.put(caseDetail.id,caseDetail);
                   }  
            }else if(IDS_THAT_REQUIRE_AFFILIATION_UPSERT.contains(caseDetail.RecordTypeId)){                
              
                if(!affilationMap.isEmpty() && caseDetail.I_RM_Affiliation__c==null 
                   && affilationMap.get(caseDetail.ContactId)!=null &&                   
                   caseDetail.ContactId == affilationMap.get(caseDetail.ContactId).I_RM_Contact__c && 
                   ROLES_THAT_REQUIRE_AFFILIATION_UPSERT.contains(affilationMap.get(caseDetail.ContactId).I_RM_Role__c) 
                   ) {
                        caseDetail.I_RM_Affiliation__c = affilationMap.get(caseDetail.ContactId).Id;
                        mapUpdateCases.put(caseDetail.Id, caseDetail);
                    }else if (caseDetail.I_RM_Affiliation__c!=null){
                        mapUpdateCases.put(caseDetail.Id, caseDetail);
                    }else{
                       mapCases.put(caseDetail.id,caseDetail);
                   } 
            }          
                    
        }
        
        if(!mapCases.isEmpty()){
            createAffiliationForCase(caseList);
        }
        if(!mapUpdateCases.isEmpty()){
            updateAffiliationFieldsAssociatedToCase(mapUpdateCases);
        }
        
    }
    public static void updateAffiliationFieldsAssociatedToCase(Map<Id,Case> mapCases){
        set<Id> affId = new set<Id>(); 
        List<I_RM_Affiliation__c> affList = new List<I_RM_Affiliation__c>(); 
        for (Case cse: mapCases.values()){
            affId.add(cse.I_RM_Affiliation__c);    
        }
        Map<Id, I_RM_Affiliation__c> affliationMap = new Map<Id, I_RM_Affiliation__c>(
            [SELECT Id,Name,RecordTypeId,I_RM_Contact__c,I_RM_Email__c,I_RM_Mobile_Phone__c,I_RM_Role__c, I_RM_Course_Availability__c, I_RM_Course_Parent__c, I_RM_Status__c,I_RM_StartDate__c FROM I_RM_Affiliation__c WHERE Id in : affId]
        );
        
        for (Case cse: mapCases.values()){
            I_RM_Affiliation__c Aff = affliationMap.get(cse.I_RM_Affiliation__c);
            
            if  ( IDS_THAT_REQUIRE_AFFILIATION_UPSERT.contains(cse.RecordTypeId) && 
                  (Aff <> NULL) && 
                  ROLES_THAT_REQUIRE_AFFILIATION_UPSERT.contains(Aff.I_RM_Role__c)
                )  
            {  
                updateAffilationFieldsFromCase(Aff,cse);
                affList.add(Aff);
            }
            
        }       
        if (affList.size() >0){
            try{
                upsert affList;
            }
            catch(dmlException ex){
                Apex_Debug_Log__c debugLog3 = new Apex_Debug_Log__c();
                debugLog3.Apex_Class_Name__c = 'I_ST_CaseTriggerHelper';
                debugLog3.Apex_Class_Method_Name__c = 'updateAffiliationFieldsAssociatedToCase';
                debugLog3.Exception_message__c = ex.getMessage();
                debugLog3.Log_Type__c = 'Error';
                insert debugLog3;
            }            
        }else{
            createAffiliationForCase(mapCases.values());
        }
    }
    private static void updateAffilationFieldsFromCase(I_RM_Affiliation__c aff, Case cse){
        Map<Id,Case> oldMap = (Map<Id,Case>)trigger.oldMap;        
        case oldCase = oldMap != null ? oldMap.get(cse.Id) : null;
        if((oldCase != null && oldCase.ContactId != cse.ContactId && cse.ContactId != null && Aff.I_RM_Contact__c == null) 
           || (oldCase == null && cse.ContactId != null && Aff.I_RM_Contact__c == null)) {Aff.I_RM_Contact__c = cse.ContactId;}  
         
        if((oldcase != null && oldCase.I_ST_Study_Interest__c != cse.I_ST_Study_Interest__c && cse.I_ST_Study_Interest__c != null && cse.I_ST_Study_Interest__c != '')
            || (oldcase == null && cse.I_ST_Study_Interest__c != null && cse.I_ST_Study_Interest__c != '')){Aff.I_RM_Study_Interest__c = cse.I_ST_Study_Interest__c;Aff.I_RM_Career_Area__c = cse.I_ST_Career_Area__c;}
        
        if((oldcase != null && oldCase.I_ST_Campus_Interest__c != cse.I_ST_Campus_Interest__c && cse.I_ST_Campus_Interest__c != null && cse.I_ST_Campus_Interest__c != '')
            || (oldcase == null && cse.I_ST_Campus_Interest__c != null && cse.I_ST_Campus_Interest__c != '')){Aff.I_RM_Campus_Interest__c = cse.I_ST_Campus_Interest__c;}       
       
        if((oldcase != null && oldCase.I_ST_Study_Level__c != cse.I_ST_Study_Level__c && cse.I_ST_Study_Level__c != null && cse.I_ST_Study_Level__c != '')
            || (oldcase == null && cse.I_ST_Study_Level__c != null && cse.I_ST_Study_Level__c != '')){Aff.I_RM_Study_Level__c = cse.I_ST_Study_Level__c;}
       
        if((oldcase != null && oldCase.I_ST_Timeframe_To_Study__c != cse.I_ST_Timeframe_To_Study__c && cse.I_ST_Timeframe_To_Study__c != null && cse.I_ST_Timeframe_To_Study__c != '')
            || (oldcase == null && cse.I_ST_Timeframe_To_Study__c != null && cse.I_ST_Timeframe_To_Study__c != '')){Aff.I_RM_Time_Frame_to_Study__c = cse.I_ST_Timeframe_To_Study__c;}
        
        if((oldcase != null && oldCase.I_ST_Course_Availability__c != cse.I_ST_Course_Availability__c && cse.I_ST_Course_Availability__c != null)
            || (oldcase == null && cse.I_ST_Course_Availability__c != null)){Aff.I_RM_Course_Availability__c = cse.I_ST_Course_Availability__c;}
        
       
        if((oldcase != null && oldCase.I_ST_Course_Name__c != cse.I_ST_Course_Name__c && cse.I_ST_Course_Name__c != null)
            || (oldcase == null && cse.I_ST_Course_Name__c != null)){Aff.I_RM_Course_Parent__c = cse.I_ST_Course_Name__c;}
        
        if((oldcase != null && oldCase.SuppliedEmail != cse.SuppliedEmail && String.isNotBlank(cse.SuppliedEmail))
            || (oldcase == null && String.isNotBlank(cse.SuppliedEmail))){Aff.I_RM_Email__c = cse.SuppliedEmail;}
            
        if((oldcase != null && oldCase.SuppliedPhone != cse.SuppliedPhone && String.isNotBlank(cse.SuppliedPhone))
            || (oldcase == null && String.isNotBlank(cse.SuppliedPhone))){Aff.I_RM_Mobile_Phone__c = cse.SuppliedPhone;}
       
        if((oldCase != null && oldCase.I_ST_Postcode__c != cse.I_ST_Postcode__c && cse.I_ST_Postcode__c != '' && cse.I_ST_Postcode__c != null) 
           || (oldCase == null && cse.I_ST_Postcode__c != null && cse.I_ST_Postcode__c != '')){Aff.I_RM_Postcode__c = cse.I_ST_Postcode__c;}
        
        if((oldCase != null && oldCase.I_ST_Enquirer_Type__c != cse.I_ST_Enquirer_Type__c && cse.I_ST_Enquirer_Type__c != null) 
           || (oldCase == null && cse.I_ST_Enquirer_Type__c != null && cse.I_ST_Enquirer_Type__c != '')){Aff.I_RM_Enquirer_Type__c = cse.I_ST_Enquirer_Type__c;}
        
    }
    private static void createAffiliationForCase(List<Case> caseList){
        List<I_RM_Affiliation__c> affList = new List<I_RM_Affiliation__c>();
        for(case cse : caseList){
            id recTypeId;
            string leadSource;
            string affRole;
            string leadsourceSubCatagory = null; 
            
            if( cse.RecordTypeId == caseEnquiryId ) 
            {
                recTypeId = leadRecordID;
                affRole = DOMESTICLEAD;
            }
            else if ( cse.RecordTypeId == CASE_INT_ENQUIRY_RECTYPE_ID ) 
            {
                recTypeId = AFFILIATION_INT_LEAD_RECTYPE_ID;
                affRole = INTERNATIONAL_LEAD_ROLE;
            }
            else {
                recTypeId = AffiliationExternalContact;
                affRole = 'School Representative';
            }
            

            switch on cse.Origin {
                when 'Email' {
                    leadSource = 'Email';
                }
                when 'Web' {
                    leadSource = 'Web Form';
                    leadsourceSubCatagory = 'Ask a Question form';
                }
                when else {
                    leadSource = 'Live Chat';
                }
            }

            I_RM_Affiliation__c Aff = new I_RM_Affiliation__c(I_RM_Contact__c = cse.ContactID,
                                                              I_RM_Account__c = cse.AccountId,                                                             
                                                              I_RM_Enquirer_Type__c = cse.I_ST_Enquirer_Type__c,
                                                              I_RM_Lead_Source_Category__c = leadSource,
                                                              I_RM_Lead_Source_sub_category__c = leadsourceSubCatagory,
                                                              I_RM_Position_Title__c = cse.I_ST_Position_Title__c,
                                                              I_RM_Mobile_Phone__c = cse.SuppliedPhone,
                                                              RecordTypeId = recTypeId ,
                                                              I_RM_Role__c = affRole,
                                                              I_RM_Postcode__c = cse.I_ST_Postcode__c);
            
            if( IDS_THAT_REQUIRE_AFFILIATION_UPSERT.contains(cse.RecordTypeId) ){
                Aff.I_RM_Email__c = cse.SuppliedEmail;
                updateAffilationFieldsFromCase(Aff, cse);
            }else if(cse.RecordTypeId == caseActivityBooking){
                Aff.I_RM_Work_Email__c = cse.SuppliedEmail;
            }
            
            
            affList.add(Aff);
        }
        set<string> affliateSetID=new  set<string>();
        
        if(affList.size()>0){
            try{
                Database.SaveResult[] srList = Database.insert(affList, false);               
                for (Database.SaveResult sr : srList) {
                    if (sr.isSuccess()) {
                        affliateSetID.add(sr.id);
                    }
                }
                
            }catch(exception ex){
                Apex_Debug_Log__c debugLog = new Apex_Debug_Log__c();
                debugLog.Apex_Class_Name__c = 'I_ST_CaseTriggerHelper';
                debugLog.Apex_Class_Method_Name__c = 'createAffiliationForCase';
                debugLog.Exception_message__c = ex.getMessage();
                debugLog.Log_Type__c = 'Error';
                Insert debugLog;
            } 
        }
        List<I_RM_Affiliation__c> lstAffiliation = [SELECT I_RM_Contact__c FROM I_RM_Affiliation__c WHERE id=:affliateSetID ];
        for(Case cse : caseList){
            for(I_RM_Affiliation__c aff : lstAffiliation){
                if(aff.I_RM_Contact__c == cse.ContactId){
                    cse.I_RM_Affiliation__c = aff.Id;
                }
            }
        }
    }
    
    //check if the Case records record type Id is valid for Scoring
    private static Boolean isValidISTScoringCaseRecordTypeId(Id recordTypeId) {
        Boolean validRecordType = false;
        String strRecordDevName = Schema.SObjectType.Case.getRecordTypeInfosById().get(recordTypeId).getDeveloperName();
        if(GlobalConstants.CASE_RECORD_TYPE_API_NAME_ENQUIRY == strRecordDevName) {
            validRecordType = true;
        }
        return validRecordType;
    }
    
    public static void calculateCaseScoring(){
        
        List<Case> newCaseList = new List<Case>();
        Set<Id> recordTypeIds = new Set<Id>(); 
        String caseIncrementField = GlobalConstants.CASE_INCREMENTAL_SCORE_FIELD;
        List<Apex_Debug_Log__c> insertDebugStatement = new List<Apex_Debug_Log__c>();
        for(Case newCase: (List<Case>)Trigger.New){
            
            if(isValidISTScoringCaseRecordTypeId(newCase.RecordTypeId)) {
                newCaseList.add(newCase);
                recordTypeIds.add(newCase.RecordTypeId);
            } 
        }
        if(newCaseList.size() > 0) {
            if(Trigger.isAfter && Trigger.isInsert){
                calculateIncrementalScoreOnCase(GlobalConstants.CASE_OBJECT_API_NAME,caseIncrementField,recordTypeIds,newCaseList,null);
            }
            if(Trigger.isAfter && Trigger.isUpdate){
                calculateIncrementalScoreOnCase(GlobalConstants.CASE_OBJECT_API_NAME,caseIncrementField,recordTypeIds,newCaseList,(Map<ID,Case>) Trigger.oldMap);
            }            
        }        
    }
    public static void calculateIncrementalScoreOnCase(String sobjectName, String caseIncrementField, Set<Id> recordTypeIds,List<Case> cases, Map<ID,Case> oldMap){
        I_ST_IncrementalScoreContactRelObject.calcIncrementalScoreContactRelObject(sobjectName,caseIncrementField,recordTypeIds,cases, oldMap);   
    }
    
    
}