force-app/main/default/objects/Apex_Debug_Log__c/Apex_Debug_Log__c.object-meta.xml
<CustomObject>
    <description>Captures results of non-user facing transactions such as Apex endpoints, callouts and asynchronous jobs</description>
    <label>Apex Debug Log</label>
    <nameField>
        <displayFormat>ADL-{00000000}</displayFormat>
        <label>Apex Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <description>The invoking class that created the record</description>
    <label>Apex Class Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <description>If an exception occurs, this is the main message</description>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <label>Log Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Transaction_Description__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Description__c</fullName>
    <description>Within the Apex Class and Method Name, give additional details on where/why this logging is happening. For example, two logs could happen in the same method - one is &apos;Save record&apos; and another is &apos;Schedule Batch&apos;.</description>
    <label>Transaction Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/I_RM_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Part of the remediation project to store different personas</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <description>Indicates the status of the Affiliation.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>I_RM_Role__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>I_ST_Contact_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/I_RM_Affiliation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Affiliation Settings</label>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_ST_Application__c/I_ST_Application__c.object-meta.xml
<CustomObject>
    <description>Custom object to show under Related list of contact as part of IST-240</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_ST_Application__c/fields/I_RM_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Facilitate relationship with the Affiliation object</description>
    <label>Affiliation</label>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/I_ST_Application__c/fields/I_ST_Application_Census_Date__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Application_Census_Date__c</fullName>
    <formula>I_ST_Course_Availability__r.I_ST_Application_Census_Date__c</formula>
    <label>Application Census Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/I_ST_Application__c/fields/I_ST_Application_Lapsed__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Application_Lapsed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Added for IST-457</description>
    <label>Application Lapsed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/I_ST_Application__c/fields/I_ST_Application_Status__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Application_Status__c</fullName>
    <description>for IST-164</description>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alternate offer considered</fullName>
            </value>
            <value>
                <fullName>Alternate Offer Declined</fullName>
            </value>
            <value>
                <fullName>Alternate offer made</fullName>
            </value>
            <value>
                <fullName>Application in error</fullName>
            </value>
            <value>
                <fullName>Application Withdrawn</fullName>
            </value>
            <value>
                <fullName>Await academic advice</fullName>
            </value>
            <value>
                <fullName>Await applicant comms</fullName>
            </value>
            <value>
                <fullName>Await further doco</fullName>
            </value>
            <value>
                <fullName>Awaiting interview</fullName>
            </value>
            <value>
                <fullName>Await required doco</fullName>
            </value>
            <value>
                <fullName>Conditional offer</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Make a conditional offer</fullName>
            </value>
            <value>
                <fullName>Make alternate offer</fullName>
            </value>
            <value>
                <fullName>Make an offer</fullName>
            </value>
            <value>
                <fullName>Not processed</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Offer Rescinded</fullName>
            </value>
            <value>
                <fullName>Other Preference offered</fullName>
            </value>
            <value>
                <fullName>Pending results</fullName>
            </value>
            <value>
                <fullName>Rejected &amp; Referred</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
            <value>
                <fullName>Unsuccessful, not notified</fullName>
            </value>
            <value>
                <fullName>Withdrawn preference</fullName>
            </value>
            <value>
                <fullName>Admitted And Not Enrolled</fullName>
            </value>
            <value>
                <fullName>Admitted And Enrolled</fullName>
            </value>
            <value>
                <fullName>Offer Admitted</fullName>
            </value>
            <value>
                <fullName>Offer Accepted</fullName>
            </value>
            <value>
                <fullName>Offer</fullName>
            </value>
            <value>
                <fullName>Offer Deferred</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/I_ST_Contact_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Admitted</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And LOA</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Not Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Considered</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Made</fullName>
    </customValue>
    <customValue>
        <fullName>Await Academic Advice</fullName>
    </customValue>
    <customValue>
        <fullName>Await Applicant Comms</fullName>
    </customValue>
    <customValue>
        <fullName>Await Further Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Awaiting Interview</fullName>
    </customValue>
    <customValue>
        <fullName>Await Required Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Escalated</fullName>
    </customValue>
    <customValue>
        <fullName>Make A Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make Alternate Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make An Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Nearing Completion</fullName>
    </customValue>
    <customValue>
        <fullName>Not Processed</fullName>
    </customValue>
    <customValue>
        <fullName>Not Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Lapsed</fullName>
    </customValue>
    <customValue>
        <fullName>Other Preference Offered</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Results</fullName>
    </customValue>
    <customValue>
        <fullName>Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <description>Global value set is created for lead(contact) object ST -51</description>
    <masterLabel>I_ST_Contact_Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/I_RM_ApplicantAffStatusUpdateBatch.cls
/* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* I_RM_ApplicantAffStatusUpdateBatch
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Teja Yenduri   <tyenduri@au1.ibm.com>
* @version        1.0
* @created        2022-02-18
  @JIRA           LTU360-867
  @Description	  This class is used to update status field of Affiliation
   @Params	  	  <sObjectName>: Object API Name, <recordTypeIds>: Set of RecordTypeIds for Score Calculation, lastNumberOfHours: Run batch past N Hours
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* @changes
* v1.0           Teja Yenduri
* 2022-03-16      Created
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/
global class I_RM_ApplicantAffStatusUpdateBatch implements Database.Batchable<sObject>,Database.Stateful {
    
    Integer numberOfRecordsProcessed = 0;
    public List<String> inactiveStatus = [SELECT I_RM_Status__c FROM I_RM_Affiliation_Settings__c WHERE Name =:GlobalConstants.I_RM_INACTIVE_APPLICATION_SETTINGS].I_RM_Status__c.split(';');
    Public List<String> inactiveStatusaff = [SELECT I_RM_Status__c FROM I_RM_Affiliation_Settings__c WHERE Name =:GlobalConstants.I_RM_AFFILIATION_SETTINGS].I_RM_Status__c.split(',');
    public List<I_RM_Affiliation__c> lstAffiliations = new List<I_RM_Affiliation__c>();   
    DateTime todayDate = System.today();
     
    
    global Database.QueryLocator start(Database.BatchableContext bc) {       
       
       string strQuery = '';
       I_RM_Affiliation_Settings__c affiliationSettingBatch = I_RM_Affiliation_Settings__c.getValues('I_RM_ApplicantAffiliationStatusBatch');
        if(affiliationSettingBatch.Value__c =='onetime'){
       
         strQuery = 'SELECT Id,I_RM_Affiliation__c,I_ST_Application_Status__c FROM I_ST_Application__c Where I_RM_Affiliation__c != Null AND I_RM_Affiliation__r.I_RM_Status__c NOT IN: inactiveStatusaff';
        }
        else if(affiliationSettingBatch.Value__c =='daily'){
            
        strQuery ='SELECT Id,I_RM_Affiliation__c,I_ST_Application_Status__c, I_RM_Affiliation__r.I_RM_Status__c FROM I_ST_Application__c ';
        strQuery +=  'WHERE I_RM_Affiliation__r.I_RM_Status__c NOT IN: inactiveStatusaff ';
        strQuery +=  'AND I_RM_Affiliation__c != Null ';  
        strQuery += 'AND I_ST_Application_Lapsed__c = FALSE ';
        strQuery += 'AND (I_ST_Application_Census_Date__c <: todayDate '; 
        strQuery += 'AND I_ST_Application_Census_Date__c != NULL)';
        }
        else{
            Apex_Debug_Log__c errorLogs = new Apex_Debug_Log__c();errorLogs.Apex_Class_Name__c = 'I_RM_ApplicantAffStatusUpdateBatch';errorLogs.Log_Type__c = 'Error';errorLogs.Exception_message__c='Please set correct value in affiliationSettingBatch custom setting record I_RM_Affiliation_Settings__c';
            Insert errorLogs;return null;            
        }
        return database.getQueryLocator(strQuery);
    }
    global void execute(Database.BatchableContext BC, List<I_ST_Application__c> lstProcessAffiliations){
        
      set<Id> uniqueAffiliationIds = new set<Id>();
      Map<Id, List<I_ST_Application__c>> mapAffIdVSApplications = new Map<Id, List<I_ST_Application__c>>();   
      for(I_ST_Application__c objApplication : [SELECT Id,I_RM_Affiliation__c,I_ST_Application_Status__c FROM I_ST_Application__c
                                                     Where I_RM_Affiliation__c != Null
                                               		AND ID  IN : lstProcessAffiliations]){
            if(objApplication.I_RM_Affiliation__c != null){
                uniqueAffiliationIds.add(objApplication.I_RM_Affiliation__c);                
               
            }
        } 
            
      
                                for(I_ST_Application__c exApp : [Select Id,I_RM_Affiliation__c,I_ST_Application_Status__c from I_ST_Application__c
                        		                           			where I_RM_Affiliation__c in:uniqueAffiliationIds
                            		                       			AND I_ST_Application_Lapsed__c = False
                                		                   			AND I_ST_Application_Status__c NOT IN: inactiveStatus
                                    		                		AND (I_ST_Application_Census_Date__c >=: todayDate 
                                        		            		OR I_ST_Application_Census_Date__c = NULL )]){
                                    
                                    // If any application related to affiliation record found put them in map
                                        if(!mapAffIdVSApplications.isEmpty() && mapAffIdVSApplications.containsKey(exApp.I_RM_Affiliation__c)){
                                             mapAffIdVSApplications.get(exApp.I_RM_Affiliation__c).add(exApp);
                                        }                                           
                                        else{
                                            mapAffIdVSApplications.put(exApp.I_RM_Affiliation__c,new List<I_ST_Application__c>{exApp});
                                        }
                                        // remove the affiliation Id from the set 
                                        uniqueAffiliationIds.remove(exApp.I_RM_Affiliation__c);   
                                }
                     
                if(!uniqueAffiliationIds.isEmpty()){ 
            // Call helper class method to update affiliation status to Inactive
            I_ST_ApplicationTriggerHelper.updateAffiliationToInactive(uniqueAffiliationIds);
            
        }
                             
        if(!mapAffIdVSApplications.isEmpty()){
            I_ST_ApplicationTriggerHelper.updateAffiliationStatus(mapAffIdVSApplications);
        }
        numberOfRecordsProcessed = numberOfRecordsProcessed + uniqueAffiliationIds.size() + mapAffIdVSApplications.size();
    }
    
    global void finish(Database.BatchableContext BC){
        
        Apex_Debug_Log__c errorLogs = new Apex_Debug_Log__c();
                        errorLogs.Apex_Class_Name__c = 'I_RM_ApplicantAffStatusUpdateBatch';
                        errorLogs.Transaction_Description__c = numberOfRecordsProcessed + 'Processed' + 'on' + system.today();
                        errorLogs.Log_Type__c = 'Info';
        Insert errorLogs;
       
    }
}