force-app/main/default/objects/Apex_Debug_Log__c/Apex_Debug_Log__c.object-meta.xml
<CustomObject>
    <description>Captures results of non-user facing transactions such as Apex endpoints, callouts and asynchronous jobs</description>
    <label>Apex Debug Log</label>
    <nameField>
        <displayFormat>ADL-{00000000}</displayFormat>
        <label>Apex Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Apex_Class_Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Method_Name__c</fullName>
    <label>Apex Class Method Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <description>The invoking class that created the record</description>
    <label>Apex Class Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Callout_Endpoint_URL__c.field-meta.xml
<CustomField>
    <fullName>Callout_Endpoint_URL__c</fullName>
    <label>Callout Endpoint URL</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <description>If an exception occurs, this is the main message</description>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Exception_stack_trace__c.field-meta.xml
<CustomField>
    <fullName>Exception_stack_trace__c</fullName>
    <description>If an exception occurs, this is the stack trace</description>
    <label>Exception stack trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <label>Log Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Response_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Response_Status_Code__c</fullName>
    <description>For a web call, this is the status. Would commonly be 200 for a success and 400 for a failure.</description>
    <label>Response Status Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>Used to distinguish the system context of this transaction</description>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apex REST Service</fullName>
            </value>
            <value>
                <fullName>Apex SOAP Service</fullName>
            </value>
            <value>
                <fullName>REST Callout</fullName>
            </value>
            <value>
                <fullName>SOAP Callout</fullName>
            </value>
            <value>
                <fullName>Batch</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Queueable/Future</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funding_Opportunity_Staging__c/Funding_Opportunity_Staging__c.object-meta.xml
<CustomObject>
    <description>This object is to store funding opps coming from external system as a staging instance eg, Research Professional.</description>
    <label>Funding Opportunity Staging</label>
    <nameField>
        <label>Staging Funding Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Research_Professional_Settings__c/Research_Professional_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains API information to connect with research Professional System.</description>
    <label>Research Professional Settings</label>
</CustomObject>

force-app/main/default/objects/Research_Professional_Settings__c/fields/Api_Key__c.field-meta.xml
<CustomField>
    <fullName>Api_Key__c</fullName>
    <label>Api_Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Research_Professional_Settings__c/fields/API_Password__c.field-meta.xml
<CustomField>
    <fullName>API_Password__c</fullName>
    <label>API_Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Research_Professional_Settings__c/fields/Api_Url__c.field-meta.xml
<CustomField>
    <fullName>Api_Url__c</fullName>
    <label>Api_Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Research_Professional_Settings__c/fields/Batch_Delay__c.field-meta.xml
<CustomField>
    <fullName>Batch_Delay__c</fullName>
    <description>Delay in milli seconds</description>
    <label>Batch Delay</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Research_Professional_Settings__c/fields/Batch_Delay_Upon_Failure__c.field-meta.xml
<CustomField>
    <fullName>Batch_Delay_Upon_Failure__c</fullName>
    <description>If the callout to Research Professional fails, how long to wait before retrying the batch (NOTE: it will retry the same pagination number, even if the data on Research Professional has changed)</description>
    <label>Batch Delay Upon Failure</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Research_Professional_Settings__c/fields/Batch_Delay_Upon_Failure_Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Batch_Delay_Upon_Failure_Multiplier__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Optionally, you can multiplicatively increase the Batch Delay Upon Failure with every time a specific batch fails. E.g. if 2, the delay would increase from 10 minutes to 20, 40 etc. Alternatively, leave it at 1.</description>
    <inlineHelpText>Optionally, you can multiplicatively increase the Batch Delay Upon Failure with every time a specific batch fails. E.g. if 2, the delay would increase from 10 minutes to 20, 40 etc. Alternatively, leave it at 1.</inlineHelpText>
    <label>Batch Delay Upon Failure Multiplier</label>
    <precision>11</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Research_Professional_Settings__c/fields/Eligibility_Regions__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Regions__c</fullName>
    <description>This field holds the comma separated regions names to make the criteria for marking Prime Ready to True</description>
    <inlineHelpText>Comma separated regions to make it available for Researchers</inlineHelpText>
    <label>Eligibility Regions</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Research_Professional_Settings__c/fields/Maximum_Number_of_Batch_Retries__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Number_of_Batch_Retries__c</fullName>
    <defaultValue>0</defaultValue>
    <description>If a callout to Research Professional fails, how many times do we wish to re-attempt the same callout before aborting the load</description>
    <label>Maximum Number of Batch Retries</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ResearchProfessionalServiceProcessTest.cls
@isTest
private class ResearchProfessionalServiceProcessTest  {
    @testSetup static void TestData(){
        
        Research_Professional_Settings__c setting = new Research_Professional_Settings__c();
        setting.Name = 'RP_API_details';
        setting.Batch_Delay__c = 100;
        setting.Batch_Delay_Upon_Failure__c = 1;
        setting.Batch_Delay_Upon_Failure_Multiplier__c = 2;
        setting.Maximum_Number_of_Batch_Retries__c = 3;
        setting.Eligibility_Regions__c = 'Australia';
        setting.Api_Key__c = 'abcd';
        setting.API_Password__c = 'test';
        setting.Api_Url__c = 'https://demo-api.researchprofessional.com/funding/v1/fops/search?query=social%20sciences,physical%20sciences%20and%20engineering,bio%2Fmedical,arts%20and%20humanities';
        Insert setting;
    }
    
    static testMethod void testSuccessfulCallout() {
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('RP_Sample_JSONResponse');
        mock.setStatusCode(200);
        mock.setStatus('OK');
        mock.setHeader('Content-Type', 'application/json');
        Test.setMock(HttpCalloutMock.class, mock); 
        
        Test.startTest();
        //Fire Service manually
        System.enqueueJob(new ResearchProfessionalService(9));
        Test.stopTest();
        
        List<Funding_Opportunity_Staging__c> lstFundOppStg = [SELECT Id FROM Funding_Opportunity_Staging__c LIMIT 1000];
        System.debug('Staging opportunities -' + lstFundOppStg);
        System.assertEquals(36,lstFundOppStg.size());


    }
    
    
    static testMethod void testFailedCallout() {
		RPfailedCalloutMock mock = new RPfailedCalloutMock();
        Test.setMock(HttpCalloutMock.class, mock); 
        
        Test.startTest();
        //Fire Service manually
        System.enqueueJob(new ResearchProfessionalService(9, 1));
        Test.stopTest();
        
		Apex_Debug_Log__c errorLog = 
			[select Apex_Class_Name__c, Apex_Class_Method_Name__c,
             	Callout_Endpoint_URL__c,
             	Response_Status_Code__c,
             	Log_Type__c,
             	Transaction_Type__c,
             	Exception_Message__c
			FROM Apex_Debug_Log__c];
		
        System.assertequals('ResearchProfessionalService', errorLog.Apex_Class_Name__c);
    	System.assertequals('execute', errorLog.Apex_Class_Method_Name__c);
        System.assert(errorLog.Callout_Endpoint_URL__c.contains('research'));
        System.assertequals('Error', errorLog.Log_Type__c);
        System.assertequals('REST Callout', errorLog.Transaction_Type__c);
        System.assertequals('404', errorLog.Response_Status_Code__c);
        System.assertequals('Resource not found', errorLog.Exception_Message__c);
            
        CronTrigger delayedRetryJob =[SELECT Id,
                                      CronJobDetail.Name,
                                      CronJobDetail.Id,
                                      State
                                      FROM CronTrigger 
                                      where CronJobDetail.Name LIKE 'RP-PRD-DAILY-IMPORT-RESUME-FROM-PAGE-9-RETRY-2%'
                                      AND State !='COMPLETE'];
        System.assert(delayedRetryJob != null);
        
    }
    
    
    
    static testMethod void testCalloutException() {
		RPCalloutExceptionMock mock = new RPCalloutExceptionMock();
        Test.setMock(HttpCalloutMock.class, mock); 
        
        Test.startTest();
        //Fire Service manually
        System.enqueueJob(new ResearchProfessionalService(9, 1));
        Test.stopTest();
        
		Apex_Debug_Log__c errorLog = 
			[select Apex_Class_Name__c, Apex_Class_Method_Name__c,
             	Callout_Endpoint_URL__c,
             	Response_Status_Code__c,
             	Log_Type__c,
             	Transaction_Type__c,
             	Exception_Message__c,
	             Exception_stack_trace__c
			FROM Apex_Debug_Log__c];
		
        System.assertequals('ResearchProfessionalService', errorLog.Apex_Class_Name__c);
    	System.assertequals('execute', errorLog.Apex_Class_Method_Name__c);
        System.assert(errorLog.Callout_Endpoint_URL__c.contains('research'));
        System.assertequals('Error', errorLog.Log_Type__c);
        System.assertequals('REST Callout', errorLog.Transaction_Type__c);
        System.assertequals('0', errorLog.Response_Status_Code__c);
        System.assertequals('Callout Exception', errorLog.Exception_Message__c);
        System.assert(errorLog.Exception_stack_trace__c != null);
        
        CronTrigger delayedRetryJob =[SELECT Id,
                                      CronJobDetail.Name,
                                      CronJobDetail.Id,
                                      State
                                      FROM CronTrigger 
                                      where CronJobDetail.Name LIKE 'RP-PRD-DAILY-IMPORT-RESUME-FROM-PAGE-9-RETRY-2%'
                                      AND State !='COMPLETE'];
        System.assert(delayedRetryJob != null);
            
    }
    
    
    
    //Mock classes
    
    public class RPfailedCalloutMock implements HttpCalloutMock {
       
		public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setBody('Resource not found');
            res.setStatusCode(404);
            res.setHeader('Content-Type', 'application/json');
            return res;
        }
    }
    
    public class RPCalloutExceptionMock implements HttpCalloutMock {
        
        public HTTPResponse respond(HTTPRequest req) {
            CalloutException e = (CalloutException)CalloutException.class.newInstance();
            e.setMessage('Callout Exception');
            throw e;
        }
        
    }

}