force-app/main/default/objects/Apex_Debug_Log__c/Apex_Debug_Log__c.object-meta.xml
<CustomObject>
    <description>Captures results of non-user facing transactions such as Apex endpoints, callouts and asynchronous jobs</description>
    <label>Apex Debug Log</label>
    <nameField>
        <displayFormat>ADL-{00000000}</displayFormat>
        <label>Apex Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Fixer_Job_Setting__c/Data_Fixer_Job_Setting__c.object-meta.xml
<CustomObject>
    <description>Configuration setting for the on-demand or schedulable data-fix jobs.</description>
    <label>Data Fixer Job Setting</label>
    <nameField>
        <label>Data Fixer Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Fixer Job Setting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Fixer_Job_Setting__c/fields/I_RS_Active__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Only active jobs will run. Uncheck this to take a job offline.</description>
    <inlineHelpText>Only active jobs will run. Uncheck this to take a job offline.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Data_Fixer_Job_Setting__c/fields/I_RS_New_Field_Values__c.field-meta.xml
<CustomField>
    <fullName>I_RS_New_Field_Values__c</fullName>
    <inlineHelpText>Use JSON array syntax, (e.g. [{},{}]. Only string values allowed.

Required keys are fieldName, dataType and newValue.

Valid dataType options: text, number, date, time and boolean.

Only valid date is &quot;TODAY&quot;. Only valid time is &quot;NOW&quot;.</inlineHelpText>
    <label>New Field Values</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Data_Fixer_Job_Setting__c/fields/I_RS_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Object_Name__c</fullName>
    <description>Object being modified</description>
    <label>Object Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Fixer_Job_Setting__c/fields/I_RS_Record_Filter__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Record_Filter__c</fullName>
    <inlineHelpText>Use SOQL filter syntax. Only records meeting the criteria will be processed. Relative date expressions will be based on the time the job runs, not the time the job is enqueued/scheduled.</inlineHelpText>
    <label>Record Filter</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Data_Fixer_Job_Setting__c/fields/I_RS_Unique_Identifier__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Unique_Identifier__c</fullName>
    <description>The unique key to supply to the data jobs. This means you are able to change the standard Name field on-demand without breaking the dependency.</description>
    <label>Unique Identifier</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BatchDataFixer.cls
public without sharing class BatchDataFixer implements Database.Batchable<SObject> {
    
    String jobConfigName;
    Boolean isActive;
    String objectAPIName;
    String filter;
    List<DataFixerNewFieldValue> newFieldValues;

    public BatchDataFixer(String jobConfigName) {

        Data_Fixer_Job_Setting__c jobConfig = [
            SELECT Id, I_RS_Object_Name__c, I_RS_Record_Filter__c, I_RS_New_Field_Values__c, I_RS_Active__c 
            FROM Data_Fixer_Job_Setting__c 
            WHERE I_RS_Unique_Identifier__c = :jobConfigName
        ];

        isActive = jobConfig.I_RS_Active__c;

        objectAPIName = jobConfig.I_RS_Object_Name__c;
        filter = jobConfig.I_RS_Record_Filter__c.replaceAll('"','\'');
        newFieldValues = (List<DataFixerNewFieldValue>) 
                JSON.deserialize(jobConfig.I_RS_New_Field_Values__c, List<DataFixerNewFieldValue>.class);

    }

    public Database.QueryLocator start(Database.BatchableContext BC){

        String query = 'SELECT Id FROM '+objectAPIName+
            ' WHERE '+filter;
        System.debug('query '+query);
        
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<SObject> records){

        if (isActive){
            for (SObject record : records){
                for (DataFixerNewFieldValue field : newFieldValues){

                    String fieldName = field.fieldName;
                    System.debug('fieldName '+fieldName);
                    System.debug('dataType '+field.dataType);

                    switch on field.dataType {
                        when 'text' {
                            record.put(fieldName, field.newValue);
                        }
                        when 'number' {
                            record.put(fieldName, Decimal.valueOf(field.newValue));
                        }
                        when 'date' {
                            switch on field.newValue.toUpperCase() {
                                when 'TODAY' {
                                    record.put(fieldName, Date.today());
                                }
                                //Add other dymamic options here
                            }
                        }
                        when 'time' {
                            switch on field.newValue.toUpperCase() {
                                when 'NOW' {
                                    record.put(fieldName, System.now());
                                }
                                //Add other dymamic options here
                            }
                        }
                        when 'boolean' {
                            switch on field.newValue.toLowerCase() {
                                when 'true' {
                                    record.put(fieldName, true);
                                }
                                when 'false' {
                                    record.put(fieldName, false);
                                }
                            }
                        }
                    }
                    System.debug('newValue '+record.get(fieldName));
                }
                System.debug('record '+record);
            }
            List<Database.SaveResult> updateResults = Database.update(records, false);

            List<Apex_Debug_Log__c> errorLogs = GlobalUtility.constructErrorLogsForDMLErrors(
                updateResults, records, 'BatchDataFixer', jobConfigName);

            if (!errorLogs.isEmpty()){
                Database.insert(errorLogs, false);
            }

        }

    }

    public void finish(Database.BatchableContext BC){

    }


    class DataFixerNewFieldValue {
        String fieldName;
        String dataType;
        String newValue;

        /*DataFixerNewFieldValue(String fieldName, String dataType, String newValue){
            this.fieldName = fieldName;
            this.dataType = dataType;
            this.newValue = newValue;
        }*/

    }

}