force-app/main/default/objects/Apex_Debug_Log__c/Apex_Debug_Log__c.object-meta.xml
<CustomObject>
    <description>Captures results of non-user facing transactions such as Apex endpoints, callouts and asynchronous jobs</description>
    <label>Apex Debug Log</label>
    <nameField>
        <displayFormat>ADL-{00000000}</displayFormat>
        <label>Apex Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Apex_Class_Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Method_Name__c</fullName>
    <label>Apex Class Method Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <description>The invoking class that created the record</description>
    <label>Apex Class Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <description>If an exception occurs, this is the main message</description>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Exception_stack_trace__c.field-meta.xml
<CustomField>
    <fullName>Exception_stack_trace__c</fullName>
    <description>If an exception occurs, this is the stack trace</description>
    <label>Exception stack trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/I_RM_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Part of the remediation project to store different personas</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_EndDate__c.field-meta.xml
<CustomField>
    <fullName>I_RM_EndDate__c</fullName>
    <description>Depicts Affiliations End Date.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <description>Indicates the status of the Affiliation.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>I_RM_Role__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>I_ST_Contact_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Applicant_Status_Derivation__mdt/I_RM_Applicant_Status_Derivation__mdt.object-meta.xml
<CustomObject>
    <description>Used for deriving active Applicant statuses based on Application status of related Applications as per LTU360-1327</description>
    <label>Applicant Status Derivation</label>
    <pluralLabel>Applicant Status Derivations</pluralLabel>
</CustomObject>

force-app/main/default/objects/I_RM_Applicant_Status_Derivation__mdt/fields/Applicant_Affiliation_Status__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Affiliation_Status__c</fullName>
    <label>Applicant Affiliation Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_RM_Applicant_Status_Derivation__mdt/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <label>Application Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_ST_Application__c/I_ST_Application__c.object-meta.xml
<CustomObject>
    <description>Custom object to show under Related list of contact as part of IST-240</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_ST_Application__c/fields/I_RM_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Facilitate relationship with the Affiliation object</description>
    <label>Affiliation</label>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/I_ST_Application__c/fields/I_ST_Application_Status__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Application_Status__c</fullName>
    <description>for IST-164</description>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alternate offer considered</fullName>
            </value>
            <value>
                <fullName>Alternate Offer Declined</fullName>
            </value>
            <value>
                <fullName>Alternate offer made</fullName>
            </value>
            <value>
                <fullName>Application in error</fullName>
            </value>
            <value>
                <fullName>Application Withdrawn</fullName>
            </value>
            <value>
                <fullName>Await academic advice</fullName>
            </value>
            <value>
                <fullName>Await applicant comms</fullName>
            </value>
            <value>
                <fullName>Await further doco</fullName>
            </value>
            <value>
                <fullName>Awaiting interview</fullName>
            </value>
            <value>
                <fullName>Await required doco</fullName>
            </value>
            <value>
                <fullName>Conditional offer</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Make a conditional offer</fullName>
            </value>
            <value>
                <fullName>Make alternate offer</fullName>
            </value>
            <value>
                <fullName>Make an offer</fullName>
            </value>
            <value>
                <fullName>Not processed</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Offer Rescinded</fullName>
            </value>
            <value>
                <fullName>Other Preference offered</fullName>
            </value>
            <value>
                <fullName>Pending results</fullName>
            </value>
            <value>
                <fullName>Rejected &amp; Referred</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
            <value>
                <fullName>Unsuccessful, not notified</fullName>
            </value>
            <value>
                <fullName>Withdrawn preference</fullName>
            </value>
            <value>
                <fullName>Admitted And Not Enrolled</fullName>
            </value>
            <value>
                <fullName>Admitted And Enrolled</fullName>
            </value>
            <value>
                <fullName>Offer Admitted</fullName>
            </value>
            <value>
                <fullName>Offer Accepted</fullName>
            </value>
            <value>
                <fullName>Offer</fullName>
            </value>
            <value>
                <fullName>Offer Deferred</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/I_RM_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Affiliation</description>
    <label>Affiliation</label>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/I_ST_Contact_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Admitted</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And LOA</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Not Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Considered</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Made</fullName>
    </customValue>
    <customValue>
        <fullName>Await Academic Advice</fullName>
    </customValue>
    <customValue>
        <fullName>Await Applicant Comms</fullName>
    </customValue>
    <customValue>
        <fullName>Await Further Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Awaiting Interview</fullName>
    </customValue>
    <customValue>
        <fullName>Await Required Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Escalated</fullName>
    </customValue>
    <customValue>
        <fullName>Make A Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make Alternate Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make An Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Nearing Completion</fullName>
    </customValue>
    <customValue>
        <fullName>Not Processed</fullName>
    </customValue>
    <customValue>
        <fullName>Not Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Lapsed</fullName>
    </customValue>
    <customValue>
        <fullName>Other Preference Offered</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Results</fullName>
    </customValue>
    <customValue>
        <fullName>Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown status</fullName>
    </customValue>
    <description>Global value set is created for lead(contact) object ST -51</description>
    <masterLabel>I_ST_Contact_Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/I_ST_ApplicationTriggerHelper.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* I_ST_Application__c Trigger Helper
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Vanita Walia
* @version        2.0
* @created        17/03/2022
*/
public with sharing class I_ST_ApplicationTriggerHelper {
    static List<Apex_Debug_Log__c> errorLogs = new List<Apex_Debug_Log__c>() ;
    
    /* @author        Vanita Walia	
	* @created        17/03/2022
	* @description	  Method to update the affiliation records status to Inactive and Set their End Date to Today. 
	*				  This methid accept Set of Affiliation Ids as input. Its part of LTU360-1324 
	*/
    public static void updateAffiliationToInactive(Set<Id> affIds){
       
        List<I_RM_Affiliation__c> affListUpdate = new  List<I_RM_Affiliation__c>();
        try{	
        	if(!affIds.isEmpty()){
            	
                // Set affiliation status as Inactive and end date as today
            	for(Id affiliation : affIds){
                	I_RM_Affiliation__c updateAff = new I_RM_Affiliation__c();
                	updateAff.Id = affiliation;
                	updateAff.I_RM_Status__c = 'Inactive';
                	updateAff.I_RM_EndDate__c = System.today();
                	affListUpdate.add(updateAff);
            	}
            	
            	// update the affiliation records and if any dml error comes add it to errorlogs
                if(affListUpdate.size() >0 && schema.SObjectType.I_RM_Affiliation__c.isUpdateable()){                    
                	I_ST_ApplicationTriggerHandler.FirstRun = True; // Set FirstRun to True to avoid recursion               	
                	List<Database.saveResult> updateResults = Database.Update(affListUpdate, false);
                   
                    errorLogs.addAll(GlobalUtility.constructErrorLogsForDMLErrors(updateResults, affListUpdate, 'I_ST_ApplicationTriggerHelper', 'updateAffiliationToInactive'));
                    insert errorLogs;  
        			errorLogs.clear();
        		}
            }
    	}
        catch(Exception ex){
            system.debug('exception' + ex);
            errorLogs.add(new Apex_Debug_Log__c(Apex_Class_Name__c = 'I_ST_ApplicationTriggerHelper',Apex_Class_Method_Name__c = 'updateAffiliationToInactive',Exception_message__c = ex.getMessage(),Exception_Stack_Trace__c = ex.getStackTraceString()));
            if (errorLogs != null && !errorLogs.isEmpty()){
               insert errorLogs;
            	errorLogs.clear();
            }
		}        
    }
    
    public static void updateAffiliationStatus(Map<Id, List<I_ST_Application__c>> affAppListMap){
       
        List<I_RM_Applicant_Status_Derivation__mdt> appStatusMtd = [Select Application_Status__c,Applicant_Affiliation_Status__c, Active__c, Priority__c From I_RM_Applicant_Status_Derivation__mdt order by Priority__c asc];

        List<I_ST_Application__c> appList = New List<I_ST_Application__c>();
        List<I_RM_Affiliation__c> allAffListUpdate = new  List<I_RM_Affiliation__c>();
        try{
            for(Id afflId : affAppListMap.keyset()){
                appList = affAppListMap.get(afflId);
                if(appList.size() >0){
                    allAffListUpdate.addAll(updateStatus(afflId, appList, appStatusMtd));
                }
            }
            if(!allAffListUpdate.isEmpty()){
                update allAffListUpdate;
            }
        }
        catch(Exception ex){
            errorLogs.add(new Apex_Debug_Log__c(Apex_Class_Name__c = 'I_ST_ApplicationTriggerHelper',Apex_Class_Method_Name__c = 'updateAffiliationStatus',Exception_message__c = ex.getMessage(),Exception_Stack_Trace__c = ex.getStackTraceString()));
            if (errorLogs != null && !errorLogs.isEmpty()){
        		insert errorLogs;
                errorLogs.clear();
            }
		}   
    }

    public static List<I_RM_Affiliation__c> updateStatus(Id afflId, List<I_ST_Application__c> appList, List<I_RM_Applicant_Status_Derivation__mdt> appStatusMtd){
        List<I_RM_Affiliation__c> affListUpdate = new  List<I_RM_Affiliation__c>();
                   
        Boolean exitForLook = false;
        Integer count = 0;
        for(I_RM_Applicant_Status_Derivation__mdt mdt : appStatusMtd){
            count++;
           
            for(I_ST_Application__c appl : appList){
                
                if(appl.I_ST_Application_Status__c == mdt.Application_Status__c){
                    I_RM_Affiliation__c updateAff = new I_RM_Affiliation__c();
                    updateAff.Id = afflId;
                    updateAff.I_RM_Status__c = mdt.Applicant_Affiliation_Status__c;
                    affListUpdate.add(updateAff);
                    exitForLook = true;
                    break;
                }else if(count >= appStatusMtd.size()){                 
                    I_RM_Affiliation__c updateAff = new I_RM_Affiliation__c();
                    updateAff.Id = afflId;
                    updateAff.I_RM_Status__c = 'Unknown status';
                    affListUpdate.add(updateAff);
                    exitForLook = true;
                    break;
                }
            }
            if(exitForLook){
                break;
            }
        }
        return affListUpdate;
    }
}