force-app/main/default/objects/Apex_Debug_Log__c/Apex_Debug_Log__c.object-meta.xml
<CustomObject>
    <description>Captures results of non-user facing transactions such as Apex endpoints, callouts and asynchronous jobs</description>
    <label>Apex Debug Log</label>
    <nameField>
        <displayFormat>ADL-{00000000}</displayFormat>
        <label>Apex Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <description>The invoking class that created the record</description>
    <label>Apex Class Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <description>If an exception occurs, this is the main message</description>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <label>Log Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Transaction_Description__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Description__c</fullName>
    <description>Within the Apex Class and Method Name, give additional details on where/why this logging is happening. For example, two logs could happen in the same method - one is &apos;Save record&apos; and another is &apos;Schedule Batch&apos;.</description>
    <label>Transaction Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>Used to distinguish the system context of this transaction</description>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apex REST Service</fullName>
            </value>
            <value>
                <fullName>Apex SOAP Service</fullName>
            </value>
            <value>
                <fullName>REST Callout</fullName>
            </value>
            <value>
                <fullName>SOAP Callout</fullName>
            </value>
            <value>
                <fullName>Batch</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Queueable/Future</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/I_RM_No_Of_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>I_RM_No_Of_Affiliation__c</fullName>
    <description>Number of Associated Affiliations to the Contact</description>
    <label>No. of Affiliations</label>
    <summaryForeignKey>I_RM_Affiliation__c.I_RM_Contact__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/I_RM_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Part of the remediation project to store different personas</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Contact__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Contact__c</fullName>
    <description>The person/contact who this Affiliation relates to</description>
    <inlineHelpText>The person this affiliation relates to</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Affiliations</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/I_RM_Affiliation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Affiliation Settings</label>
</CustomObject>

force-app/main/default/classes/I_RM_VilomaContactDeletionBatch.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* I_RM_VilomaContactDeletionBatch
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Kishore Reddy Basani
* @version        1.0
* @created        2022-04-28
* @Description	  This class is for to delete the contacts which does not have any related affliations
* ─────────────────────────────────────────────────────────────────────────────────────────────────
*/

global with sharing class  I_RM_VilomaContactDeletionBatch implements Database.Batchable<sObject>,Database.Stateful {
    Integer numberOfRecordsDeleted = 0;
    global Database.QueryLocator start(Database.BatchableContext bc){
        String numberOfDays = [SELECT Value__c FROM I_RM_Affiliation_Settings__c WHERE Name ='I_RM_No_of_days' limit 1].Value__c;
        Date daysToDelete = System.today() - Integer.valueOf(numberOfDays);
        String strQuery = 'SELECT Id, Name, I_RM_No_Of_Affiliation__c FROM Contact WHERE I_RM_No_Of_Affiliation__c = 0 AND CreatedDate <: daysToDelete';
        return database.getQueryLocator(strQuery);
    }

    global void execute(Database.BatchableContext BC, List<Contact> contactList) {

        List<Contact> contactsWOAffliations = new List<Contact>();
        List<Contact> contactsWOAffliationsAndPusers = new List<Contact>();
        List<User> lUsers = new List<User>();
        List<Contact> listOfContacts = [select id, (select id, I_RM_Contact__c from Affiliations__r) from Contact where id IN : contactList AND Id NOT IN (SELECT ContactId FROM Case WHERE ContactId IN : contactList)];
        for(Contact c: [select id, (select id, I_RM_Contact__c from Affiliations__r) from Contact where id IN : contactList AND Id NOT IN (SELECT ContactId FROM Case WHERE ContactId IN : contactList)]){
            if( c.Affiliations__r.size() == 0){
                contactsWOAffliations.add(c);
            }
        }
        if(contactsWOAffliations.size() > 0){
            contactsWOAffliationsAndPusers = [Select Id from Contact Where Id IN : contactsWOAffliations AND Id NOT IN (SELECT ContactId FROM User WHERE Profile.Name = 'LTU Partner Community User' AND ContactId IN :contactsWOAffliations)];
                    if(!contactsWOAffliationsAndPusers.isEmpty()){
                        try{
                            delete contactsWOAffliationsAndPusers;
                            numberOfRecordsDeleted = contactsWOAffliationsAndPusers.size();
                        }catch(Exception e){
                            Apex_Debug_Log__c debugLog = new Apex_Debug_Log__c();
                            debugLog.Apex_Class_Name__c = 'I_RM_VilomaContactDeletionBatch';
                            debugLog.Exception_Message__c = e.getMessage();
                            debugLog.Log_Type__c = 'Error';
                            debugLog.Transaction_Type__c = 'Scheduled';
                            insert debugLog;
                        }
                    }
        }
    }

    
    global void finish(Database.BatchableContext BC) {
        Apex_Debug_Log__c debugLog = new Apex_Debug_Log__c();
        debugLog.Apex_Class_Name__c = 'I_RM_VilomaContactDeletionBatch';
        debugLog.Transaction_Description__c = 'Number of contact records deleted ::' +numberOfRecordsDeleted + ' On the Date ::' + System.today();
        debugLog.Log_Type__c = 'Info';
        debugLog.Log_Type__c = 'Scheduled';
        insert debugLog;
    }
}