force-app/main/default/objects/Apex_Debug_Log__c/Apex_Debug_Log__c.object-meta.xml
<CustomObject>
    <description>Captures results of non-user facing transactions such as Apex endpoints, callouts and asynchronous jobs</description>
    <label>Apex Debug Log</label>
    <nameField>
        <displayFormat>ADL-{00000000}</displayFormat>
        <label>Apex Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Apex_Class_Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Method_Name__c</fullName>
    <label>Apex Class Method Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <description>The invoking class that created the record</description>
    <label>Apex Class Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <description>If an exception occurs, this is the main message</description>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Exception_stack_trace__c.field-meta.xml
<CustomField>
    <fullName>Exception_stack_trace__c</fullName>
    <description>If an exception occurs, this is the stack trace</description>
    <label>Exception stack trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/L_PR_External_Org_Opportunity_Relation__c/L_PR_External_Org_Opportunity_Relation__c.object-meta.xml
<CustomObject>
    <label>Organisation Opportunity Relationship</label>
    <nameField>
        <displayFormat>OOR-{000000}</displayFormat>
        <label>Organisation Opportunity Relationship</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organisation Opportunity Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/L_PR_External_Org_Opportunity_Relation__c/fields/L_PR_Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Opportunity_Name__c</fullName>
    <label>Opportunity Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PRM_Opportunity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Organisation Opportunity Relationships</relationshipLabel>
    <relationshipName>External_Org_Opportunity_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/L_PR_External_Org_Opportunity_Relation__c/fields/L_PR_OpportunityStage__c.field-meta.xml
<CustomField>
    <fullName>L_PR_OpportunityStage__c</fullName>
    <label>Opportunity Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/L_PR_External_Org_Opportunity_Relation__c/fields/L_PR_Organisation_Name__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Organisation_Name__c</fullName>
    <label>Organisation Name</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>I_ST_Educational_Institution</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>I_RS_External_Organisation</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>I_RS_La_Trobe_Organisation_Unit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Organisation Opportunity Relationships</relationshipLabel>
    <relationshipName>External_Org_Opportunity_Relationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/L_PR_Ext_Org_Oppt_RelationTriggerHandler.cls
public without sharing class L_PR_Ext_Org_Oppt_RelationTriggerHandler{

    public static void execute(){
        List<L_PR_External_Org_Opportunity_Relation__c> listOfExtOrgToUpdate = New List<L_PR_External_Org_Opportunity_Relation__c>();                       
        List<Apex_Debug_Log__c> errorLogs = new List<Apex_Debug_Log__c>();
        if(Trigger.isAfter){
            if(Trigger.isInsert || Trigger.isUpdate){
                try{
                    List<L_PR_External_Org_Opportunity_Relation__c> listOfExtOrgs = [Select Id, L_PR_IsPrimary__c, L_PR_Opportunity_Name__r.StageName, L_PR_OpportunityStage__c, L_PR_Organisation_Name__c
                    From L_PR_External_Org_Opportunity_Relation__c Where Id IN : Trigger.New];
                    map<Id,L_PR_External_Org_Opportunity_Relation__c> mapOldExtOrgs = (map<Id,L_PR_External_Org_Opportunity_Relation__c>)Trigger.oldMap;
                    for(L_PR_External_Org_Opportunity_Relation__c eorg : listOfExtOrgs){
                        L_PR_External_Org_Opportunity_Relation__c extOrg = New L_PR_External_Org_Opportunity_Relation__c();
                        if(eorg.L_PR_Opportunity_Name__r.StageName != null && (Trigger.isInsert || (Trigger.isUpdate && eorg.L_PR_Opportunity_Name__r.StageName != mapOldExtOrgs.get(eorg.id).L_PR_OpportunityStage__c))) {
                            extOrg.L_PR_OpportunityStage__c = eorg.L_PR_Opportunity_Name__r.StageName;
                            extOrg.Id = eorg.Id;
                            listOfExtOrgToUpdate.add(extOrg);
                        }
                    }
                    if(!listOfExtOrgToUpdate.isEmpty()){
                        update listOfExtOrgToUpdate;
                    }
                }catch(Exception e){
                    errorLogs.add(new Apex_Debug_Log__c(
                        Apex_Class_Name__c = 'L_PR_Ext_Org_Oppt_RelationTriggerHandler',
                        Apex_Class_Method_Name__c = 'L_PR_Ext_Org_Oppt_RelationTriggerHandler',
                        Exception_message__c = 'Exception while updating the L_PR_OpportunityStage__c field in L_PR_External_Org_Opportunity_Relation__c',
                        Exception_Stack_Trace__c = e.getStackTraceString()));
                }
            }
        }

    }
}