force-app/main/default/objects/Apex_Debug_Log__c/Apex_Debug_Log__c.object-meta.xml
<CustomObject>
    <description>Captures results of non-user facing transactions such as Apex endpoints, callouts and asynchronous jobs</description>
    <label>Apex Debug Log</label>
    <nameField>
        <displayFormat>ADL-{00000000}</displayFormat>
        <label>Apex Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/I_RM_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Part of the remediation project to store different personas</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Calculate_Affiliation_Score__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Calculate_Affiliation_Score__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Technical Field. Depicts if batch process needs to recalculate the affiliation&apos;s Lead Score.</description>
    <label>Calculate Affiliation Score</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Score__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Score__c</fullName>
    <description>This Fields shows the calculated score of an affiliation based on key attributes being populated</description>
    <label>Affiliation Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <description>Indicates the status of the Affiliation.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>I_RM_Role__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>I_ST_Contact_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/I_RM_Affiliation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Affiliation Settings</label>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_ST_BatchScoring__c/I_ST_BatchScoring__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>I_ST_BatchScoring</label>
</CustomObject>

force-app/main/default/objects/I_ST_BatchScoring__c/fields/I_ST_BatchSize__c.field-meta.xml
<CustomField>
    <fullName>I_ST_BatchSize__c</fullName>
    <description>This is the batch size to control the Lead/Activity scoring jobs for IST</description>
    <label>I_ST_BatchSize</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/I_ST_BatchScoring__c/fields/I_ST_Last_N_Hour__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Last_N_Hour__c</fullName>
    <description>Used for Activity Scoring batch to run batch and pick records modified &apos;N&apos; hours before current time</description>
    <label>I_ST_Last_N_Hour</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/I_ST_BatchScoring__c/fields/I_ST_RecordType_SFIDs__c.field-meta.xml
<CustomField>
    <fullName>I_ST_RecordType_SFIDs__c</fullName>
    <description>Provide comma separated RecordTypeIds of Case object which is to be considered for Activity Scoring. To get the record type Ids =&gt; Navigate to Setup -&gt; Object Manager -&gt; Case -&gt; RecordTypes -&gt; Select the record type -&gt; copy the 18 digit Id from the URL</description>
    <label>I_ST_RecordType_SFIDs</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_ST_Lead_Scoring__mdt/I_ST_Lead_Scoring__mdt.object-meta.xml
<CustomObject>
    <description>Key Value pairs which are used to calulate a Lead&apos;s score</description>
    <label>Lead Scoring</label>
    <pluralLabel>Lead Scoring</pluralLabel>
</CustomObject>

force-app/main/default/objects/I_ST_Lead_Scoring__mdt/fields/I_ST_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Field_API_Name__c</fullName>
    <label>Field API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/I_RM_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Affiliation</description>
    <label>Affiliation</label>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/I_ST_Contact_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Admitted</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And LOA</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Not Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Considered</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Made</fullName>
    </customValue>
    <customValue>
        <fullName>Await Academic Advice</fullName>
    </customValue>
    <customValue>
        <fullName>Await Applicant Comms</fullName>
    </customValue>
    <customValue>
        <fullName>Await Further Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Awaiting Interview</fullName>
    </customValue>
    <customValue>
        <fullName>Await Required Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Escalated</fullName>
    </customValue>
    <customValue>
        <fullName>Make A Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make Alternate Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make An Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Nearing Completion</fullName>
    </customValue>
    <customValue>
        <fullName>Not Processed</fullName>
    </customValue>
    <customValue>
        <fullName>Not Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Lapsed</fullName>
    </customValue>
    <customValue>
        <fullName>Other Preference Offered</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Results</fullName>
    </customValue>
    <customValue>
        <fullName>Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <description>Global value set is created for lead(contact) object ST -51</description>
    <masterLabel>I_ST_Contact_Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/I_RM_AffiliationScoring_Batch.cls
/* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* I_ST_AffiliationScoring_Batch
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Teja Yenduri   <tyenduri@au1.ibm.com>
* @version        1.0
* @created        2022-02-18
  @JIRA           LTU360-867
  @Description	  This class is used to calculate Contact Score on Affiliation
   @Params	  	  <sObjectName>: Object API Name, <recordTypeIds>: Set of RecordTypeIds for Score Calculation, lastNumberOfHours: Run batch past N Hours
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* @changes
* v1.0           Teja Yenduri
* 2022-02-18      Created
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/
global class I_RM_AffiliationScoring_Batch implements Database.Batchable<sObject>,Database.Stateful {
    
    private Map<String, List<I_ST_Lead_Scoring__mdt>> mapExtractPicklistFields;
    private String sObjectName;
    private Set<Id> setRecordTypeId;
    private Integer lastNumberOfHours;
    private List<String> inactiveStatus;
    
    public I_RM_AffiliationScoring_Batch(String sObjectName, Set<Id> recordTypeIds, Integer lastNumberOfHours){
        this.sObjectName = sObjectName; 
        setRecordTypeId = recordTypeIds; 
        inactiveStatus = [SELECT I_RM_Status__c FROM I_RM_Affiliation_Settings__c WHERE Name =:GlobalConstants.I_RM_AFFILIATION_SETTINGS].I_RM_Status__c.split(',');
        this.lastNumberOfHours = (lastNumberOfHours > 0) ? lastNumberOfHours : 6;  
        mapExtractPicklistFields = new Map<String, List<I_ST_Lead_Scoring__mdt>>();
        for(I_ST_Lead_Scoring__mdt leadScoringMappingRec: I_ST_Lead_Scoring__mdt.getAll().values()) {
            if((leadScoringMappingRec.I_ST_Active__c) && leadScoringMappingRec.I_ST_Object__c == sObjectName) {
                if(mapExtractPicklistFields.containsKey(leadScoringMappingRec.I_ST_Field_API_Name__c)) {
                    List<I_ST_Lead_Scoring__mdt> listMetadata = mapExtractPicklistFields.get(leadScoringMappingRec.I_ST_Field_API_Name__c);
                    listMetadata.add(leadScoringMappingRec);
                    mapExtractPicklistFields.put(leadScoringMappingRec.I_ST_Field_API_Name__c, listMetadata);
                } else {
                    mapExtractPicklistFields.put(leadScoringMappingRec.I_ST_Field_API_Name__c, new List<I_ST_Lead_Scoring__mdt> { leadScoringMappingRec });
                }
            }
        }
    }
    
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        
        Datetime currentTime = System.now();
        Datetime durationPastHoursCurrentTime = System.now().addHours(-lastNumberOfHours);
        
        List<String> allFields =  new List<String>();
        if(mapExtractPicklistFields!= null && mapExtractPicklistFields.size() > 0) {
            for(String fieldAPIName : mapExtractPicklistFields.keySet()){
                allFields.add(fieldAPIName);
            }
        }
        
        String affiliationFields = String.join(allFields,', ');
        String strRecordTypeIDs = String.join((Iterable<String>)setRecordTypeId, ', ');
        String strInactiveStatus = String.join(inactiveStatus,', ');
        String strQuery = 'SELECT Id,' + affiliationFields + ' FROM I_RM_Affiliation__c ';
       
        strQuery += ' WHERE LastModifiedDate >: durationPastHoursCurrentTime AND LastModifiedDate <=: currentTime';
        if(setRecordTypeId !=null && !setRecordTypeId.isEmpty()) {
                strQuery += ' AND RecordTypeId ' + ' IN : setRecordTypeId ';                
            }
        strQuery += ' AND I_RM_Calculate_Affiliation_Score__c = TRUE ';
        strQuery += ' AND I_RM_Status__c ' + 'NOT IN : inactiveStatus';
        strQuery += ' WITH SECURITY_ENFORCED ORDER BY Id DESC';        
        
        return database.getQueryLocator(strQuery);
    }
    
    global void execute(Database.BatchableContext BC, List<I_RM_Affiliation__c>  affiliations) {
        List<I_RM_Affiliation__c> updateToAffiliation = GlobalUtility.calculateScoreonObjectFields(mapExtractPicklistFields, affiliations, 'I_RM_Score__c', 'I_RM_Affiliation__c',null);
        if(updateToAffiliation.size() > 0){         
            List<Apex_Debug_Log__c> errorLogs = new List<Apex_Debug_Log__c>();
            try{
                //Do not call trigger method for setting the Calculate Score on affiliation
                I_RM_AffiliationTriggerHandler.runmarkCalculateAffiliationScoreToTrue = True;
                Database.SaveResult[] results = Database.update(updateToAffiliation,false);
                errorLogs = GlobalUtility.constructErrorLogsForDMLErrors(results,updateToAffiliation,'I_RM_AffiliationScoring_Batch','execute'); 
            }
            catch(DmlException e){
                System.debug('Error in contact scoring records - ' + e.getMessage());
            }
        }
    }
    global void finish(Database.BatchableContext BC){
        
        I_ST_BatchScoring__c batchScoringCustomSetting = [SELECT Id,I_ST_Last_N_Hour__c,I_ST_RecordType_SFIDs__c,I_ST_BatchSize__c 
                                                          FROM I_ST_BatchScoring__c 
                                                          WHERE Name =: GlobalConstants.I_ST_CASESCORING LIMIT 1];
        
        Integer lastNHours = (Integer)batchScoringCustomSetting.I_ST_Last_N_Hour__c;
        
        Set<Id> recordTypeIds = GlobalUtility.convertCommaSeparatedStringsToSetIds(I_ST_BatchScoring__c.getValues(GlobalConstants.I_ST_CASESCORING).I_ST_RecordType_SFIDs__c);        
        
        Integer batchSize = integer.valueOf(batchScoringCustomSetting.I_ST_BatchSize__c);
        I_ST_ActivityScoring_Batch activityScoringBatch = new I_ST_ActivityScoring_Batch(GlobalConstants.CASE_OBJECT_API_NAME,recordTypeIds,lastNHours);
        Database.executeBatch(activityScoringBatch,Integer.valueOf(batchSize));
        
    }
}