force-app/main/default/objects/Apex_Debug_Log__c/Apex_Debug_Log__c.object-meta.xml
<CustomObject>
    <description>Captures results of non-user facing transactions such as Apex endpoints, callouts and asynchronous jobs</description>
    <label>Apex Debug Log</label>
    <nameField>
        <displayFormat>ADL-{00000000}</displayFormat>
        <label>Apex Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <description>The invoking class that created the record</description>
    <label>Apex Class Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <label>Log Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Transaction_Description__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Description__c</fullName>
    <description>Within the Apex Class and Method Name, give additional details on where/why this logging is happening. For example, two logs could happen in the same method - one is &apos;Save record&apos; and another is &apos;Schedule Batch&apos;.</description>
    <label>Transaction Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/I_RM_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Part of the remediation project to store different personas</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Affiliation_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Affiliation_Contact_Name__c</fullName>
    <formula>I_RM_Contact__r.I_RS_Full_Name__c</formula>
    <label>Affiliation Contact Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Contact__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Contact__c</fullName>
    <description>The person/contact who this Affiliation relates to</description>
    <inlineHelpText>The person this affiliation relates to</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Affiliations</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/L_PR_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Contact_Name__c</fullName>
    <label>Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/L_PR_AffPopulateContactNameBatch.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* L_PR_AffPopulateContactNameBatch
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Vanita Walia
* @version        1.0
* @created        08-09-2022
* @Description	  This batch class is to populate the contact name on affiliations
* ─────────────────────────────────────────────────────────────────────────────────────────────────
*/

public  without sharing class L_PR_AffPopulateContactNameBatch implements Database.Batchable<sObject>, Database.Stateful{

    Integer numberOfRecordsUpdated = 0;
    public Database.QueryLocator start(Database.BatchableContext bc){

        String strQuery = 'SELECT Id, I_RM_Contact__c, I_RM_Affiliation_Contact_Name__c, L_PR_Contact_Name__c from I_RM_Affiliation__c where L_PR_Contact_Name__c = null';
        return database.getQueryLocator(strQuery);
    }

    public void execute(Database.BatchableContext bc, List<I_RM_Affiliation__c> affList) {

        List<I_RM_Affiliation__c> affListToBeUpdated = New List<I_RM_Affiliation__c>();

        for(I_RM_Affiliation__c aff : affList){
            I_RM_Affiliation__c newAff = New I_RM_Affiliation__c();
            if(aff.I_RM_Contact__c != Null && aff.I_RM_Affiliation_Contact_Name__c !='' && aff.L_PR_Contact_Name__c == null){
                newAff.Id = aff.Id;
                newAff.L_PR_Contact_Name__c = aff.I_RM_Affiliation_Contact_Name__c;
                numberOfRecordsUpdated++;
            }
            affListToBeUpdated.add(newAff);
        }

        if(!affListToBeUpdated.isEmpty()){
            update affListToBeUpdated;
        }
    }

    public void finish(Database.BatchableContext bc){
        Apex_Debug_Log__c debugLog = new Apex_Debug_Log__c();
        debugLog.Apex_Class_Name__c = 'L_PR_AffPopulateContactNameBatch';
        debugLog.Transaction_Description__c = 'Number of affiliation records updated::' +numberOfRecordsUpdated + ' On the Date ::' + System.today();
        debugLog.Log_Type__c = 'Info';
        debugLog.Log_Type__c = 'Batch';
        insert debugLog;
    }

}