force-app/main/default/objects/Apex_Debug_Log__c/Apex_Debug_Log__c.object-meta.xml
<CustomObject>
    <description>Captures results of non-user facing transactions such as Apex endpoints, callouts and asynchronous jobs</description>
    <label>Apex Debug Log</label>
    <nameField>
        <displayFormat>ADL-{00000000}</displayFormat>
        <label>Apex Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <description>If an exception occurs, this is the main message</description>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Data_Fixer_Job_Setting__c/Data_Fixer_Job_Setting__c.object-meta.xml
<CustomObject>
    <description>Configuration setting for the on-demand or schedulable data-fix jobs.</description>
    <label>Data Fixer Job Setting</label>
    <nameField>
        <label>Data Fixer Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Fixer Job Setting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Fixer_Job_Setting__c/fields/I_RS_New_Field_Values__c.field-meta.xml
<CustomField>
    <fullName>I_RS_New_Field_Values__c</fullName>
    <inlineHelpText>Use JSON array syntax, (e.g. [{},{}]. Only string values allowed.

Required keys are fieldName, dataType and newValue.

Valid dataType options: text, number, date, time and boolean.

Only valid date is &quot;TODAY&quot;. Only valid time is &quot;NOW&quot;.</inlineHelpText>
    <label>New Field Values</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Data_Fixer_Job_Setting__c/fields/I_RS_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Object_Name__c</fullName>
    <description>Object being modified</description>
    <label>Object Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Fixer_Job_Setting__c/fields/I_RS_Record_Filter__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Record_Filter__c</fullName>
    <inlineHelpText>Use SOQL filter syntax. Only records meeting the criteria will be processed. Relative date expressions will be based on the time the job runs, not the time the job is enqueued/scheduled.</inlineHelpText>
    <label>Record Filter</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Data_Fixer_Job_Setting__c/fields/I_RS_Unique_Identifier__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Unique_Identifier__c</fullName>
    <description>The unique key to supply to the data jobs. This means you are able to change the standard Name field on-demand without breaking the dependency.</description>
    <label>Unique Identifier</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BatchDataFixerTest.cls
@isTest
public with sharing class BatchDataFixerTest {

    @TestSetup
    static void makeData(){
        //
        Data_Fixer_Job_Setting__c jobConfig = new Data_Fixer_Job_Setting__c(
            Name = 'Set Task fields',
            I_RS_Unique_Identifier__c = 'SetTaskFields',
            I_RS_Object_Name__c = 'Task',
            I_RS_Record_Filter__c = 'Subject = "Task To Update"'
        );
        
        List<Map<String, String>> newFieldValues = 
            new List<Map<String, String>>{
                new Map<String, String>{
                    'fieldName' => 'Description',
                    'dataType' => 'text',
                    'newValue' => 'Description goes here'
                },  
                /*new Map<String, String>{
                    'fieldName' => 'I_RS_Milestone_Amount__c',
                    'dataType' => 'number',
                    'newValue' => '10'
                },*/
                new Map<String, String>{
                    'fieldName' => 'ActivityDate',
                    'dataType' => 'date',
                    'newValue' => 'TODAY'
                }/*,
                new Map<String, String>{
                    'fieldName' => 'IsVisibleInSelfService',
                    'dataType' => 'boolean',
                    'newValue' => 'false'
                }*/
            };
        jobConfig.I_RS_New_Field_Values__c = JSON.serialize(newFieldValues);
        System.debug(jobConfig.I_RS_New_Field_Values__c);

        insert jobConfig;

        Task taskToUpdate = TestUtility.newTask(null);
        taskToUpdate.Subject = 'Task to Update';
        taskToUpdate.ActivityDate = Date.today()+7;
        insert taskToUpdate;

        Task taskToIgnore = TestUtility.newTask(null);
        taskToIgnore.ActivityDate = Date.today()+1;
        insert taskToIgnore;
    }

    public static testmethod void validBatch() {

        //Kick off immediate batch based on config - make case-insensitive
        Test.startTest();

        Database.executeBatch(new BatchDataFixer('SetTaskFields'));

        Test.stopTest();

        List<Apex_Debug_Log__c> errorLogs = [select Id, Exception_Message__c
        from Apex_Debug_Log__c];
        for (Apex_Debug_Log__c errorLog : errorLogs){
            System.debug(errorLog);
        }
        System.assertequals(0, errorLogs.size());

        Task updatedTask = [SELECT Description, I_RS_Milestone_Amount__c, ActivityDate,
                IsVisibleInSelfService FROM Task
                WHERE ActivityDate = TODAY];
        System.assertequals('Description goes here' , updatedTask.Description);
        //System.assertequals(10 , updatedTask.I_RS_Milestone_Amount__c);
        System.assertequals(Date.today(), updatedTask.ActivityDate);
        //System.assertequals(false , updatedTask.IsVisibleInSelfService);

    }

    public static testmethod void validSchedule(){

        String scheduleExpression = '0 0 0 * * ?'; 
        BatchDataFixerScheduler schedulableInstance = new BatchDataFixerScheduler('SetTaskFields', 10);
        
        Test.startTest();
            
		System.schedule('Regular data fixer', scheduleExpression, schedulableInstance);
        
        Test.stopTest(); 

    }

    //Invalid scenarios will simply manifest as exceptions,
    //It is up to the admins to properly configure the fields 


}