force-app/main/default/objects/Apex_Debug_Log__c/Apex_Debug_Log__c.object-meta.xml
<CustomObject>
    <description>Captures results of non-user facing transactions such as Apex endpoints, callouts and asynchronous jobs</description>
    <label>Apex Debug Log</label>
    <nameField>
        <displayFormat>ADL-{00000000}</displayFormat>
        <label>Apex Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Apex_Class_Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Method_Name__c</fullName>
    <label>Apex Class Method Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Debug_Log__c/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <description>The invoking class that created the record</description>
    <label>Apex Class Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_RS_Is_Organisation_Confidential__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Is_Organisation_Confidential__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Organisation Confidential?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CourseAvailability__c/CourseAvailability__c.object-meta.xml
<CustomObject>
    <label>Course Availability</label>
    <nameField>
        <displayFormat>AID-CA-{0000}</displayFormat>
        <label>Course Availability ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Availabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CourseInstance__c/CourseInstance__c.object-meta.xml
<CustomObject>
    <description>Location specific details of a course</description>
    <label>Course Instance</label>
    <nameField>
        <displayFormat>AID-CI-{0000}</displayFormat>
        <label>Course Instance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Instance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CourseParent__c/CourseParent__c.object-meta.xml
<CustomObject>
    <label>Course Parent</label>
    <nameField>
        <label>Course Parent ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Parent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/I_RM_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Part of the remediation project to store different personas</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <description>Indicates the status of the Affiliation.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>I_RM_Role__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>I_ST_Contact_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_IL_Student_Lead_Int.recordType-meta.xml
<RecordType>
    <fullName>I_IL_Student_Lead_Int</fullName>
    <active>true</active>
    <description>New International Lead who can be a prospective student of La Trobe University</description>
    <label>Student Lead (Int)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_Applicant.recordType-meta.xml
<RecordType>
    <fullName>I_RM_Applicant</fullName>
    <active>true</active>
    <description>An individual who has applied to study at La Trobe University</description>
    <label>Student Applicant (Dom)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_Lead.recordType-meta.xml
<RecordType>
    <fullName>I_RM_Lead</fullName>
    <active>true</active>
    <description>New Domestic Lead who is a prospective student of La Trobe University</description>
    <label>Student Lead (Dom)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/I_RM_Affiliation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Affiliation Settings</label>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_ST_Application__c/I_ST_Application__c.object-meta.xml
<CustomObject>
    <description>Custom object to show under Related list of contact as part of IST-240</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_ST_Application__c/fields/I_RM_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Facilitate relationship with the Affiliation object</description>
    <label>Affiliation</label>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/I_ST_Application__c/fields/I_ST_Application_Lapsed__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Application_Lapsed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Added for IST-457</description>
    <label>Application Lapsed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/I_ST_Application__c/fields/I_ST_Application_Status__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Application_Status__c</fullName>
    <description>for IST-164</description>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alternate offer considered</fullName>
            </value>
            <value>
                <fullName>Alternate Offer Declined</fullName>
            </value>
            <value>
                <fullName>Alternate offer made</fullName>
            </value>
            <value>
                <fullName>Application in error</fullName>
            </value>
            <value>
                <fullName>Application Withdrawn</fullName>
            </value>
            <value>
                <fullName>Await academic advice</fullName>
            </value>
            <value>
                <fullName>Await applicant comms</fullName>
            </value>
            <value>
                <fullName>Await further doco</fullName>
            </value>
            <value>
                <fullName>Awaiting interview</fullName>
            </value>
            <value>
                <fullName>Await required doco</fullName>
            </value>
            <value>
                <fullName>Conditional offer</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Make a conditional offer</fullName>
            </value>
            <value>
                <fullName>Make alternate offer</fullName>
            </value>
            <value>
                <fullName>Make an offer</fullName>
            </value>
            <value>
                <fullName>Not processed</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Offer Rescinded</fullName>
            </value>
            <value>
                <fullName>Other Preference offered</fullName>
            </value>
            <value>
                <fullName>Pending results</fullName>
            </value>
            <value>
                <fullName>Rejected &amp; Referred</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
            <value>
                <fullName>Unsuccessful, not notified</fullName>
            </value>
            <value>
                <fullName>Withdrawn preference</fullName>
            </value>
            <value>
                <fullName>Admitted And Not Enrolled</fullName>
            </value>
            <value>
                <fullName>Admitted And Enrolled</fullName>
            </value>
            <value>
                <fullName>Offer Admitted</fullName>
            </value>
            <value>
                <fullName>Offer Accepted</fullName>
            </value>
            <value>
                <fullName>Offer</fullName>
            </value>
            <value>
                <fullName>Offer Deferred</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/I_ST_Contact_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Admitted</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And LOA</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Not Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Considered</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Made</fullName>
    </customValue>
    <customValue>
        <fullName>Await Academic Advice</fullName>
    </customValue>
    <customValue>
        <fullName>Await Applicant Comms</fullName>
    </customValue>
    <customValue>
        <fullName>Await Further Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Awaiting Interview</fullName>
    </customValue>
    <customValue>
        <fullName>Await Required Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Escalated</fullName>
    </customValue>
    <customValue>
        <fullName>Make A Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make Alternate Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make An Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Nearing Completion</fullName>
    </customValue>
    <customValue>
        <fullName>Not Processed</fullName>
    </customValue>
    <customValue>
        <fullName>Not Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Lapsed</fullName>
    </customValue>
    <customValue>
        <fullName>Other Preference Offered</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Results</fullName>
    </customValue>
    <customValue>
        <fullName>Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown status</fullName>
    </customValue>
    <customValue>
        <fullName>Offered</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrawn</fullName>
        <isActive>false</isActive>
        <label>Withdrawn</label>
    </customValue>
    <description>Global value set is created for lead(contact) object ST -51</description>
    <masterLabel>I_ST_Contact_Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/I_ST_ApplicationTriggerHandlerTest.cls
@isTest
public class I_ST_ApplicationTriggerHandlerTest{

    @TestSetup
    static void makeData(){

        String recTypeIdsForAffScoring = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Applicant').getRecordTypeId();
        recTypeIdsForAffScoring += ',' + Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Lead').getRecordTypeId();
        recTypeIdsForAffScoring += ',' + Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_IL_Student_Lead_Int').getRecordTypeId();
        TestUtility.createBatchScoringCustomSettings(recTypeIdsForAffScoring);
        
       // create inactive affiliation status custom setting record
        I_RM_Affiliation_Settings__c objAffiliationSettings = new I_RM_Affiliation_Settings__c(Name = 'I_RM_Inactive_Status',I_RM_Status__c = 'Inactive');
        insert objAffiliationSettings;
        // create inactive application status custom setting record
        I_RM_Affiliation_Settings__c objApplicationSettings = new I_RM_Affiliation_Settings__c(Name = 'I_RM_Inactive_Application_Status',I_RM_Status__c = 'Alternate Offer Declined;Withdrawn;Unoffered;');
        insert objApplicationSettings;  
        //create courseParent record, courseInstance record and courseAvailability record which is mandatory for creating application
        CourseParent__c courseParent =  I_ST_UnitTestUtilities.createCourseParent();
        insert courseParent;
        CourseInstance__c courseInstance = I_ST_UnitTestUtilities.createCourseInstance(courseParent.Id);
        insert courseInstance;
        CourseAvailability__c courseAvailability = I_ST_UnitTestUtilities.createCourseAvailability(courseInstance.Id);
        insert courseAvailability;
        // Fetch the applicant affiliation recordtype Id
        Id affiliationApplicantRecordTypeId = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Applicant').getRecordTypeId(); 
       
        //create test contact
        Contact con = I_ST_UnitTestUtilities.createContactForScore('testuser1','lastname1','testuser1@test.com','testuser1@test.com','3000');
        con.I_RS_Is_Organisation_Confidential__c = false;
        insert con;
        //create applicant affiliation
        List<I_RM_Affiliation__c> applicantAff = I_ST_UnitTestUtilities.createApplicantAffiliationRecords(affiliationApplicantRecordTypeId,con.Id);
        insert applicantAff;
    }


    @isTest
    public static void updateAffiliationStatusTest(){

        Test.startTest();
        Contact cont =[Select Id from Contact];
        List<I_RM_Affiliation__c> lstAffiliation = [Select Id from I_RM_Affiliation__c];
        CourseAvailability__c courseAvailability = [Select Id from CourseAvailability__c];
        I_ST_Application__c createApplication1 = I_ST_UnitTestUtilities.createApplication(cont.Id, courseAvailability.Id);
        createApplication1.I_RM_Affiliation__c = lstAffiliation[0].Id;
        createApplication1.I_ST_Application_Status__c = 'Await required doco';
        insert createApplication1;
        I_ST_Application__c createApplication2 = I_ST_UnitTestUtilities.createApplication(cont.Id, courseAvailability.Id);
        createApplication2.I_RM_Affiliation__c = lstAffiliation[0].Id;
        createApplication2.I_ST_Application_Status__c = 'Conditional offer';
        insert createApplication2;
        I_ST_Application__c createApplication3 = I_ST_UnitTestUtilities.createApplication(cont.Id, courseAvailability.Id);
        createApplication3.I_RM_Affiliation__c = lstAffiliation[0].Id;
        createApplication3.I_ST_Application_Status__c = 'Offered';
        insert createApplication3;
        List<I_RM_Affiliation__c> updatedAffl = [Select Id, I_RM_Status__c from I_RM_Affiliation__c where Id =: lstAffiliation[0].Id];
        System.assertEquals('Offer', updatedAffl[0].I_RM_Status__c);
        
        Test.stopTest();

    }
    
    @isTest
    public static void updateAffiliationStatusUnknownStatusTest(){
        
        Test.startTest();
        Contact cont =[Select Id from Contact];
        List<I_RM_Affiliation__c> lstAffiliation = [Select Id from I_RM_Affiliation__c];
        CourseAvailability__c courseAvailability = [Select Id from CourseAvailability__c];
        I_ST_Application__c createApplication1 = I_ST_UnitTestUtilities.createApplication(cont.Id, courseAvailability.Id);
        createApplication1.I_RM_Affiliation__c = lstAffiliation[0].Id;
        insert createApplication1;
        I_ST_Application__c createApplication2 = I_ST_UnitTestUtilities.createApplication(cont.Id, courseAvailability.Id);
        createApplication2.I_RM_Affiliation__c = lstAffiliation[0].Id;
        insert createApplication2;
        I_ST_Application__c createApplication3 = I_ST_UnitTestUtilities.createApplication(cont.Id, courseAvailability.Id);
        createApplication3.I_RM_Affiliation__c = lstAffiliation[0].Id;
        insert createApplication3;
        List<I_RM_Affiliation__c> updatedAffl = [Select Id, I_RM_Status__c from I_RM_Affiliation__c where Id =: lstAffiliation[0].Id];
        System.assertEquals('Unknown status', updatedAffl[0].I_RM_Status__c);
        Test.stopTest();

    }
    
    @isTest
    public static void updateAffiliationStatusCatchTest(){
        
        Test.startTest();
        Map<Id, List<I_ST_Application__c>> affAppListMap = new Map<Id, List<I_ST_Application__c>>();
        List<I_ST_Application__c> listApp = New List<I_ST_Application__c>();
        Contact cont =[Select Id from Contact];
        List<I_RM_Affiliation__c> lstAffiliation = [Select Id from I_RM_Affiliation__c];
        CourseAvailability__c courseAvailability = [Select Id from CourseAvailability__c];
        I_ST_Application__c createApplication1 = I_ST_UnitTestUtilities.createApplication(cont.Id, courseAvailability.Id);
        createApplication1.I_RM_Affiliation__c = lstAffiliation[0].Id;
        listApp.add(createApplication1);
        
        affAppListMap.put(cont.id, listApp);
        try{
        	I_ST_ApplicationTriggerHelper.updateAffiliationStatus(affAppListMap);
        }catch(Exception e){
             System.debug ('Exception'+e);
        }
        
                Test.stopTest();
    }
    
    /*  @author 		Vanita Walia
     * @date  			23/03/2022
     * @description 	LTU360-1324 : Method to test updateaffiliationtoInactive method
     */
	@isTest
    public static void updateAffiliationtoInactiveTest(){
        Test.startTest();
        
        Contact con =[Select Id from Contact];
        List<I_RM_Affiliation__c> applicantAff = [Select Id from I_RM_Affiliation__c];
        
	CourseAvailability__c courseAvailability = [Select Id from CourseAvailability__c];

        I_ST_Application__c app1 = I_ST_UnitTestUtilities.createApplication(con.Id, courseAvailability.Id);
        app1.I_RM_Affiliation__c = applicantAff[0].Id;
        app1.I_ST_Application_Status__c = 'Withdrawn';
        insert app1;
        
        I_ST_Application__c app2 = I_ST_UnitTestUtilities.createApplication(con.Id, courseAvailability.Id);
        app2.I_RM_Affiliation__c = applicantAff[0].Id;
        app2.I_ST_Application_Lapsed__c = false;
        insert app2;
        
        app2.I_ST_Application_Lapsed__c = true;
        I_ST_ApplicationTriggerHandler.FirstRun = false;
        update app2;
        
        List<I_RM_Affiliation__c> updatedAffl = [Select Id, I_RM_Status__c from I_RM_Affiliation__c where Id =: applicantAff[0].Id];
        System.assertEquals('Inactive', updatedAffl[0].I_RM_Status__c);

    }
    
    /*  @author 		Vanita Walia
     * @date  			30/03/2022
     * @description 	LTU360-1324 : Method to cover catch block of applicationtrigger handler class
     */
	@isTest
    public static void updateAffiliationtoInactive_CatchTest1(){
		Test.startTest();
        
        Contact con =[Select Id from Contact];
        List<I_RM_Affiliation__c> applicantAff = [Select Id from I_RM_Affiliation__c];
       
        CourseAvailability__c courseAvailability = [Select Id from CourseAvailability__c];
        
		//delete the custom setting record so that it cause exception in handler class
        I_RM_Affiliation_Settings__c af = [Select Id from I_RM_Affiliation_Settings__c where Name='I_RM_Inactive_Application_Status'];
        delete af;
        try{
        	I_ST_Application__c app1 = I_ST_UnitTestUtilities.createApplication(con.Id,courseAvailability.Id);
        	app1.I_RM_Affiliation__c = applicantAff[0].Id;
        	app1.I_ST_Application_Status__c = 'Withdrawn';
        	insert app1;
        }
        Catch(exception e){
            System.debug ('Exception'+e);
        }
       test.stopTest();
       
        Apex_Debug_Log__c err = [SELECT Id,Apex_Class_Method_Name__c FROM Apex_Debug_Log__c WHERE Apex_Class_Name__c = 'I_ST_ApplicationTriggerHandler' AND Apex_Class_Method_Name__c = 'execute Method' Limit 1];       
        system.assertNotEquals('', err.Apex_Class_Method_Name__c);
        
    }
    /*  @author 		Vanita Walia
     * @date  			30/03/2022
     * @description 	LTU360-1324 : Method to do code coverage for catch block in application trigger helper class
     */
	@isTest
    public static void updateAffiliationtoInactive_CatchTest2(){
		test.startTest();
        try{
           I_ST_ApplicationTriggerHelper.updateAffiliationToInactive(Null);
        }
        Catch(Exception e){
            System.debug ('Exception'+e);
        }
        test.stopTest();
        Apex_Debug_Log__c err = [SELECT Id,Apex_Class_Method_Name__c FROM Apex_Debug_Log__c WHERE Apex_Class_Name__c = 'I_ST_ApplicationTriggerHelper' AND Apex_Class_Method_Name__c = 'updateAffiliationToInactive' Limit 1];       
        system.assertNotEquals('', err.Apex_Class_Method_Name__c);
    }
    
}