force-app/main/default/objects/Ethics_Post_Approval__c/Ethics_Post_Approval__c.object-meta.xml
<CustomObject>
    <label>Ethics Post Approval</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ethics Post Approvals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ethics_Post_Approval__c/fields/I_RS_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Status__c</fullName>
    <inlineHelpText>This is the status corresponds with the ethics request status at the top of the page. If this status is ‘draft’ this means the researcher has an action to complete. Populated by the Research Office.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>I_RS_Review_Outcome__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Review by Research Office</fullName>
            </value>
            <value>
                <fullName>Assigned for Review</fullName>
            </value>
            <value>
                <fullName>Outcome Communicated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ethics_Request__c/Ethics_Request__c.object-meta.xml
<CustomObject>
    <label>Ethics Request</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ethics Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ethics_Request__c/fields/I_RS_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Status__c</fullName>
    <inlineHelpText>This is the status that corresponds with the ethics request status at the top of the page. If this status is ‘draft’ this means the researcher has an action to complete. Populated by the Research Office.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>I_RS_Ethics_Application_Review_Outcome__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Review by Research Office</fullName>
            </value>
            <value>
                <fullName>Assigned for Review</fullName>
            </value>
            <value>
                <fullName>Outcome Communicated</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Decided</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Proposal__c/Project_Proposal__c.object-meta.xml
<CustomObject>
    <description>Project Proposal: An application for funding either through a grant request, a tender response, or a contract proposal.
Project: The work that is undertaken to satisfy a commitment made to a funding body or client.  The commitment is likely to be a contract (and possible variations) resulting from the acceptance of a project proposal.  This occurs after a grant, contract of philanthropic donation has been awarded.</description>
    <label>Project Proposal</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Proposal__c/fields/I_RS_Allow_Updates_on_Approval__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Allow_Updates_on_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When &quot;checked&quot; the record will be locked after submitted for approval.</description>
    <label>Allow Updates on Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_Proposal__c/fields/I_RS_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PlaceHolder</fullName>
            </value>
            <value>
                <fullName>Create Proposal</fullName>
            </value>
            <value>
                <fullName>Proposal Review</fullName>
            </value>
            <value>
                <fullName>Recommended</fullName>
            </value>
            <value>
                <fullName>Dismissed</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Create EOI</fullName>
            </value>
            <value>
                <fullName>Drafting NOI</fullName>
            </value>
            <value>
                <fullName>Final draft</fullName>
            </value>
            <value>
                <fullName>Draft Proposal</fullName>
            </value>
            <value>
                <fullName>Provide Project Details</fullName>
            </value>
            <value>
                <fullName>Contract Instructions</fullName>
            </value>
            <value>
                <fullName>Review by Research Office</fullName>
            </value>
            <value>
                <fullName>Panel Review</fullName>
            </value>
            <value>
                <fullName>HoS NOI Validation</fullName>
            </value>
            <value>
                <fullName>Pitch Session</fullName>
            </value>
            <value>
                <fullName>Peer review draft</fullName>
            </value>
            <value>
                <fullName>Peer review draft complete</fullName>
            </value>
            <value>
                <fullName>Review Contract</fullName>
            </value>
            <value>
                <fullName>Draft contract</fullName>
            </value>
            <value>
                <fullName>Approvals</fullName>
            </value>
            <value>
                <fullName>Formalise Contract</fullName>
            </value>
            <value>
                <fullName>Submission to Client</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Ready for Submission to Funding Body</fullName>
            </value>
            <value>
                <fullName>Submission to Funding Body</fullName>
                <label>Funding Body Submission</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Rejoinders</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Research_Opportunity__c/Research_Opportunity__c.object-meta.xml
<CustomObject>
    <label>Funding Opportunity</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Research_Opportunity__c/fields/I_RS_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initial</fullName>
                <default>true</default>
                <label>Initial</label>
            </value>
            <value>
                <fullName>Drafted</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Internal Applications Closed</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContentVersionTriggerHelper.cls
//Trigger helper for ContentVersion
public class ContentVersionTriggerHelper {
        private static String projPropKeyPrefix = Project_Proposal__c.sObjectType.getDescribe().getKeyPrefix();
        private static String roKeyPrefix = Research_Opportunity__c.sObjectType.getDescribe().getKeyPrefix();
        private static String erKeyPrefix = Ethics_Request__c.sObjectType.getDescribe().getKeyPrefix();
        private static String epaKeyPrefix = Ethics_Post_Approval__c.sObjectType.getDescribe().getKeyPrefix();
    
    private static Set<String> erPermittedStatus = new Set<String>{'Draft'};
    private static Set<String> epaPermittedStatus = new Set<String>{'Draft'};
        
    
    public static void disableContentVersionUpload(List<ContentVersion> contentVersionList) {
        
        Map<Id,Id> contentVersionIdVsLinkedEntityId = new Map<Id,Id>();
        Map<Id,Id> ethicsCVIdVsLinkedEntityId = new Map<Id,Id>();
        Map<Id,Id> ethicsPostApprovalCVIdVsLinkedEntityId = new Map<Id,Id>();
        
        Set<Id> projectProposalIds = new Set<Id>();
        Map<Id, ContentVersion> roContentVersionMap = new Map<Id, ContentVersion>();
        List<ContentVersion> erContentVersionMap = new List<ContentVersion>();
        List<ContentVersion> epaContentVersionMap = new List<ContentVersion>();
        
        boolean erCVAdded = false;
        boolean epaCVAdded = false;
        for(ContentVersion cv: contentVersionList)
        {
            if(cv.ContentDocumentId != null)
            {
        		erCVAdded = false;
        		epaCVAdded = false;
                List<ContentDocumentLink> cdlList = [SELECT ContentDocumentId, LinkedEntityId FROM ContentDocumentLink WHERE ContentDocumentId =: cv.ContentDocumentId];
                for(ContentDocumentLink cdlnk: cdlList) {
                    if(String.valueOf(cdlnk.LinkedEntityId).left(3) == projPropKeyPrefix) {
                        contentVersionIdVsLinkedEntityId.put(cv.Id, cdlnk.LinkedEntityId);
                        projectProposalIds.add(cdlnk.LinkedEntityId);
                    }
                    
                    if (String.valueOf(cdlnk.LinkedEntityId).left(3) == roKeyPrefix) {
                        if (!roContentVersionMap.containsKey(cv.Id)){
                            roContentVersionMap.put(cv.Id, cv);
                        }    
                    }
                    
                    if ((String.valueOf(cdlnk.LinkedEntityId).left(3) == erKeyPrefix) ) {
                        if (!erCVAdded) {
                            erCVAdded = true;
                        	erContentVersionMap.add(cv);
                        }
                        if (cv.ContentDocumentId == cdlnk.ContentDocumentId){
                            ethicsCVIdVsLinkedEntityId.put(cdlnk.ContentDocumentId, cdlnk.LinkedEntityId);
                        }
                    }

                    if ((String.valueOf(cdlnk.LinkedEntityId).left(3) == epaKeyPrefix) ) {
                        if (!epaCVAdded) {
                            epaCVAdded = true;
                        	epaContentVersionMap.add(cv);
                        }
                        if (cv.ContentDocumentId == cdlnk.ContentDocumentId){
                            ethicsPostApprovalCVIdVsLinkedEntityId.put(cdlnk.ContentDocumentId, cdlnk.LinkedEntityId);
                        }
                    }
                }
            }
        }
        
        if (projectProposalIds.size() > 0){
        	handleProjectProposalDocument(projectProposalIds, contentVersionIdVsLinkedEntityId, contentVersionList);    
        }
        
        if(roContentVersionMap.size() > 0) {
        	handleResearchOpportunityDocument(roContentVersionMap.values());    
        }
        
        if(erContentVersionMap.size() > 0) {
        	handleEthicsRequestDocument(erContentVersionMap, ethicsCVIdVsLinkedEntityId);    
        }
        
        if(epaContentVersionMap.size() > 0) {
        	handleEthicsPostApprovalDocument(epaContentVersionMap, ethicsPostApprovalCVIdVsLinkedEntityId);    
        }
    }
    
    private static void handleProjectProposalDocument(Set<Id> projectProposalIds, Map<Id,Id> contentVersionIdVsLinkedEntityId, List<ContentVersion> contentVersionList){
        Set <Id> projectProposalsLockedForReview = new Set <Id>();
        
        if(projectProposalIds != null && projectProposalIds.size()>0) {
            for(Project_Proposal__c projProp : [SELECT I_RS_Allow_Updates_on_Approval__c, I_RS_Status__c FROM Project_Proposal__c WHERE Id IN :projectProposalIds] ) {
                if(!projProp.I_RS_Allow_Updates_on_Approval__c
                   && (GlobalConstants.PROJECT_PROPOSAL_STATUS_REVIEW_BY_RESEARCH_OFFICE.EqualsIgnoreCase(projProp.I_RS_Status__c)
                       || GlobalConstants.PROJECT_PROPOSAL_STATUS_APPROVALS.EqualsIgnoreCase(projProp.I_RS_Status__c))) {
                           projectProposalsLockedForReview.add(projProp.Id);
                       }
            }
            for(ContentVersion conVersion : contentVersionList){
                if(contentVersionIdVsLinkedEntityId.get(conVersion.Id) != null 
                   && projectProposalsLockedForReview.contains(contentVersionIdVsLinkedEntityId.get(conVersion.Id))) {
                       conVersion.addError(GlobalConstants.ADDED_ERROR_ATTACHMENT_UPLOAD_PROECT_IN_REVIEW);
                   }
            }
        }
    }  
    
    private static void handleResearchOpportunityDocument(List<ContentVersion> contentVersionList){
        if (GlobalUtility.currentUserIsResearcher()) {
            for(ContentVersion conVersion : contentVersionList){
                conVersion.addError(GlobalConstants.RESTRICT_DOCUMENT_UPLOAD_BY_RESEARCHER);
            }
        }
    }    

    private static void handleEthicsRequestDocument(List<ContentVersion> contentVersionList,Map<Id,Id> ethicsCVIdVsLinkedEntityId){
        if (GlobalUtility.currentUserIsResearcher()) {
            Map<Id, Ethics_request__c> erMap = new Map<Id, Ethics_request__c> ([SELECT Id, I_RS_Status__c 
                                                                               FROM Ethics_request__C 
                                                                               WHERE Id IN :ethicsCVIdVsLinkedEntityId.values()]);
            set<Id> cDocIds = new set<Id>();
            for (ContentVersion conVersion : contentVersionList){
            	cDocIds.add(conVersion.ContentDocumentId);    
            }
            Map<Id, ContentDocument> cDocList = new Map<Id, ContentDocument>([SELECT Id, OwnerId 
                                                                              FROM ContentDocument 
                                                                              WHERE Id IN :cDocIds]);
                
            for(ContentVersion conVersion : contentVersionList){
                Id erId = ethicsCVIdVsLinkedEntityId.get(conVersion.ContentDocumentId); 
                Ethics_request__c er = erMap.get(erId); 
                if ( (!erPermittedStatus.contains(er.I_RS_Status__c)) &&
                     (cDocList.get(conVersion.ContentDocumentId).OwnerId != conVersion.OwnerId)){
                	conVersion.addError(GlobalConstants.RESTRICT_DOCUMENT_UPLOAD_BY_RESEARCHER);
                }
            }
        }
    }    
    private static void handleEthicsPostApprovalDocument(List<ContentVersion> contentVersionList,Map<Id,Id> ethicsPostApprovalCVIdVsLinkedEntityId){
        if (GlobalUtility.currentUserIsResearcher()) {
            Map<Id, Ethics_Post_Approval__C> epaMap = new Map<Id, Ethics_Post_Approval__C> ([SELECT Id, I_RS_Status__c 
                                                                               FROM Ethics_Post_Approval__C 
                                                                               WHERE Id IN :ethicsPostApprovalCVIdVsLinkedEntityId.values()]);
            set<Id> cDocIds = new set<Id>();
            for (ContentVersion conVersion : contentVersionList){
            	cDocIds.add(conVersion.ContentDocumentId);    
            }
            Map<Id, ContentDocument> cDocList = new Map<Id, ContentDocument>([SELECT Id, OwnerId 
                                                                              FROM ContentDocument 
                                                                              WHERE Id IN :cDocIds]);
                
            for(ContentVersion conVersion : contentVersionList){
                Id epaId = ethicsPostApprovalCVIdVsLinkedEntityId.get(conVersion.ContentDocumentId); 
                Ethics_Post_Approval__C er = epaMap.get(epaId); 
                if ( (!epaPermittedStatus.contains(er.I_RS_Status__c)) &&
                     (cDocList.get(conVersion.ContentDocumentId).OwnerId != conVersion.OwnerId)){
                	conVersion.addError(GlobalConstants.RESTRICT_DOCUMENT_UPLOAD_BY_RESEARCHER);
                }
            }
        }
    }    
}