force-app/main/default/objects/Contact/fields/I_RS_Related_User__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Related_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Refers to the user record associated to the contact</description>
    <label>Related User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_ST_Incremental_Score__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Incremental_Score__c</fullName>
    <label>Activity Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/I_RM_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Part of the remediation project to store different personas</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_Lead.recordType-meta.xml
<RecordType>
    <fullName>I_RM_Lead</fullName>
    <active>true</active>
    <description>New Domestic Lead who is a prospective student of La Trobe University</description>
    <label>Student Lead (Dom)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/I_RM_Affiliation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Affiliation Settings</label>
</CustomObject>

force-app/main/default/objects/I_ST_BatchScoring__c/I_ST_BatchScoring__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>I_ST_BatchScoring</label>
</CustomObject>

force-app/main/default/objects/I_ST_BatchScoring__c/fields/I_ST_RecordType_SFIDs__c.field-meta.xml
<CustomField>
    <fullName>I_ST_RecordType_SFIDs__c</fullName>
    <description>Provide comma separated RecordTypeIds of Case object which is to be considered for Activity Scoring. To get the record type Ids =&gt; Navigate to Setup -&gt; Object Manager -&gt; Case -&gt; RecordTypes -&gt; Select the record type -&gt; copy the 18 digit Id from the URL</description>
    <label>I_ST_RecordType_SFIDs</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_ST_Interaction__c/I_ST_Interaction__c.object-meta.xml
<CustomObject>
    <description>For Lead Forms, tracks interactions(forms) filled out by the Lead (domestic)</description>
    <label>Interaction</label>
    <nameField>
        <displayFormat>INT-{DD}{MM}{YY}-{0000}</displayFormat>
        <label>Interaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_ST_Interaction__c/fields/I_RM_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Affiliation__c</fullName>
    <description>Facilitate relationship with the Affiliation object</description>
    <label>Affiliation</label>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>Interactions</relationshipLabel>
    <relationshipName>Interactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/I_ST_Interaction__c/fields/I_ST_Contact__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Added for LTU360-16, To track Associated Contact of domestic Lead Forms.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Interactions</relationshipLabel>
    <relationshipName>Interactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/I_ST_Interaction__c/fields/I_ST_Email__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Email__c</fullName>
    <description>Added for LTU360-16, To track  Email of domestic Lead Forms.</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/I_ST_Interaction__c/fields/I_ST_FirstName__c.field-meta.xml
<CustomField>
    <fullName>I_ST_FirstName__c</fullName>
    <description>Added for LTU360-16, To track First Name of domestic Lead Forms.</description>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_ST_Interaction__c/fields/I_ST_Incremental_Score__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Incremental_Score__c</fullName>
    <label>Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/I_ST_Interaction__c/fields/I_ST_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Last_Name__c</fullName>
    <description>Added for LTU360-16, To track Last Name of domestic Lead Forms.</description>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_ST_Interaction__c/fields/I_ST_Mobile__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Mobile__c</fullName>
    <description>Added for LTU360-16, To track Mobile of domestic Lead Forms.</description>
    <label>Mobile Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/I_ST_Interaction__c/fields/I_ST_Source_Category__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Source_Category__c</fullName>
    <description>Added for LTU360-16, To track Source Category of domestic Lead Forms.</description>
    <label>Source Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_ST_Interaction__c/fields/I_ST_Source_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Source_Sub_Category__c</fullName>
    <description>Added for LTU360-16, To track Source Sub Category of domestic Lead Forms.</description>
    <label>Source Sub Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/I_ST_InteractionTriggerHandlerTest.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* I_ST_InteractionTriggerHandlerTest
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Teja Yenduri   <tyenduri@au1.ibm.com>
* @version        1.0
* @created        2021-09-07
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* @changes
* v1.0           Teja Yenduri
* 2021-09-07      Created
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/
@isTest
public class I_ST_InteractionTriggerHandlerTest {
    @TestSetup
    static void setup() {
        
         string affiliationRecordTypeIds = I_ST_UnitTestUtilities.recordTypeIds(GlobalConstants.AFFILIATION_OBJECT_API_NAME,GlobalConstants.AFFILIATION_RECORD_TYPE_NAME_LEAD);
        String interactionRecordTypeIds = I_ST_UnitTestUtilities.recordTypeIds(GlobalConstants.INTERACTION_OBJECT_API_NAME,GlobalConstants.INTERACTION_RECORD_TYPE_API_NAME_LEAD_INTERACTION);
        Integer NumberOfInteractions = 50;
        
        List<I_ST_BatchScoring__c> listBatchScoringSetting = I_ST_UnitTestUtilities.createBatchScoringCustomSetting(affiliationRecordTypeIds,20,null,null,interactionRecordTypeIds,20);           
        insert listBatchScoringSetting;
        
        I_RM_Affiliation_Settings__c objAffiliationSettings = I_ST_UnitTestUtilities.createAffiliationSettings();
        insert objAffiliationSettings;
        
        
        Id interactionRecordTypeId =  I_ST_BatchScoring__c.getValues('I_ST_InteractionScoring').I_ST_RecordType_SFIDs__c.split(',')[0];
        
        I_ST_InteractionTriggerHandler.setNotFired();
        //Id contactDomesticLeadRecordTypeId =  I_ST_BatchScoring__c.getValues('I_ST_ContactScoring').I_ST_RecordType_SFIDs__c.split(',')[0];
        Id affiliationDomesticLeadRecordTypeId = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Lead').getRecordTypeId();
        List<Contact> contactsforTest = new List<Contact>();
        
        for(Integer i =0; i<10; i++){
            Contact newDomesticLead = I_ST_UnitTestUtilities.createContactForScore(
                                                                                   'test_unique001'+i,
                                                                                   'unique_test001'+i,
                                                                                   'test_unique001'+i+'@unique.com',
                                                                                   'test_unique001'+i+'@unique.com',                                                                                  
                                                                                   '3029');
                                                                                          
            contactsforTest.add(newDomesticLead);
        }
        Insert contactsforTest;
        
         I_RM_Affiliation__c testAffiliation= I_ST_UnitTestUtilities.createAffiliationRecords(affiliationDomesticLeadRecordTypeId,contactsforTest[0].Id)[0];
        insert testAffiliation;
        
        //Insert batch of Interactions
        List<I_ST_Interaction__c> interactionsforTest = new List<I_ST_Interaction__c>();
        for(Integer j=0; j<contactsforTest.size(); j++) {
            I_ST_Interaction__c newinteraction =  I_ST_UnitTestUtilities.newListOfContactRelatedInteractions(interactionRecordTypeId,contactsforTest[j],'FirstTest'+j,'LastTest'+j,'039948757',
                                                                                                             'testInteractionEmail'+j+'@test.com','Web','Keep in touch form',testAffiliation);
             newinteraction.I_RM_Affiliation__c= testAffiliation.Id;
            interactionsforTest.add(newinteraction);
        }
        Insert interactionsforTest;
        
    }
    
    //Test incremental score on update interaction
    @isTest
    public static void testUpdateInteraction(){
        
        Test.startTest();    	
           Contact domesticContact = [SELECT Id, Name, I_RS_Related_User__c FROM Contact WHERE email = 'test_unique0011@unique.com' LIMIT 1];
           List<I_ST_Interaction__c> interactionToProcess = [SELECT id,I_ST_FirstName__c,I_ST_Last_Name__c,I_ST_Mobile__c,
                                                          I_ST_Email__c, I_ST_Source_Category__c,I_ST_Source_Sub_Category__c,
                                                          I_ST_Contact__c,I_ST_Incremental_Score__c FROM I_ST_Interaction__c WHERE I_ST_Contact__c =: domesticContact.Id];             
        
          I_ST_Interaction__c interactionToUpdate = new I_ST_Interaction__c();
          interactionToUpdate.id = interactionToProcess[0].id;        
          interactionToUpdate.I_ST_Mobile__c = '0390480757';
          I_ST_InteractionTriggerHandler.setNotFired();
          update interactionToUpdate;
          I_ST_InteractionTriggerHandler.hasFired();
        Test.stopTest();
        
        system.assertEquals(5,interactionToProcess[0].I_ST_Incremental_Score__c);
    }
    
}