force-app/main/default/objects/Contact/fields/I_RS_Related_User__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Related_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Refers to the user record associated to the contact</description>
    <label>Related User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Research_Personnel__c/Research_Personnel__c.object-meta.xml
<CustomObject>
    <description>Formerly known as Ethics Request Member and Research Personnel</description>
    <label>Ethics Research Personnel</label>
    <nameField>
        <displayFormat>RP-{00000}</displayFormat>
        <label>Title</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ethics Research Personnel</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Research_Personnel__c/fields/I_RS_Contact_Researcher__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Contact_Researcher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related researcher</description>
    <label>Contact/Researcher</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Ethics_Request_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Research_Personnel__c/fields/I_RS_Ethics_Request__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Ethics_Request__c</fullName>
    <description>Related ethics request</description>
    <label>Ethics Request</label>
    <referenceTo>Ethics_Request__c</referenceTo>
    <relationshipLabel>Ethics Research Personnel</relationshipLabel>
    <relationshipName>Ethics_Request_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ResearchPersonnelTriggerHelper.cls
public class ResearchPersonnelTriggerHelper {
    public static void updateRPSharesWithNewUserId(Map<Id, Contact> oldMap, Map<Id, Contact> newMap){
        List<Id> newCs= new List<Id>();
        List<Id> delCs= new List<Id>();
        for (Contact c: newMap.values()) {
            if ((c.I_RS_Related_User__c != null) && (c.I_RS_Related_User__c != oldMap.get(c.Id).I_Rs_Related_User__c)) {
                newCs.add(c.Id);
            }
            if ((c.I_RS_Related_User__c == null) && (c.I_RS_Related_User__c != oldMap.get(c.Id).I_Rs_Related_User__c)) {
                delCs.add(oldMap.get(c.Id).I_Rs_Related_User__c);
            }
        }
        
        if (newCs.size() > 0){
        	List<Ethics_Request__share> grantList = new List<Ethics_Request__share>();
            for (Research_Personnel__c rp: [SELECT Id, I_RS_Ethics_Request__c, I_RS_End_Date__c, I_RS_Contact_Researcher__c FROM Research_Personnel__c WHERE I_RS_Contact_Researcher__c in :newCs]) {
                System.debug('Research_Personnel__c rp: '+ rp);
                if (rp.I_RS_End_Date__c == null)  {
                    Ethics_Request__share erShare = new Ethics_Request__share();
                    erShare.ParentId = rp.I_RS_Ethics_Request__c;
                    erShare.UserOrGroupId = newMap.get(rp.I_RS_Contact_Researcher__c).I_Rs_Related_User__c;
                    erShare.RowCause = Schema.Ethics_Request__Share.rowCause.Ethics_Team_Member__c;                        
                    erShare.AccessLevel = GlobalConstants.ETHICS_TEAM_MEMBER_SHARING_ACCESS;
                    grantList.add(erShare);
                }
            }
            if (grantList.size() > 0) {
                insert grantList;
            }
        }
        
        if (delCs.size() > 0) {
        	List<Ethics_Request__share> revokeList = [SELECT Id FROM Ethics_Request__share WHERE UserOrGroupId in :delCs AND RowCause = :Schema.Ethics_Request__Share.rowCause.Ethics_Team_Member__c];
            if (revokeList.size() > 0 ){
                delete revokeList;
            }
            
        } 

    }

}