force-app/main/default/objects/Contact/fields/I_RS_Deceased__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Deceased__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deceased</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_ST_Sanctioned_Student__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Sanctioned_Student__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sanctioned Student</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/I_RM_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Part of the remediation project to store different personas</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Contact__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Contact__c</fullName>
    <description>The person/contact who this Affiliation relates to</description>
    <inlineHelpText>The person this affiliation relates to</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Affiliations</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Enquirer_Type__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Enquirer_Type__c</fullName>
    <description>Depicts how best to describe the Enquirer, Applicable for Student Lead (Dom),Student Applicant (Dom) and Secondary School Rep</description>
    <inlineHelpText>This is the Enquirer Type</inlineHelpText>
    <label>What best describes you?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>I_ST_Enquirer_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Role__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Role__c</fullName>
    <description>This represents the role of the affiliation</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Domestic Lead</fullName>
                <label>Student Lead (Dom)</label>
            </value>
            <value>
                <fullName>Applicant</fullName>
                <label>Student Applicant (Dom)</label>
            </value>
            <value>
                <fullName>La Trobe Staff</fullName>
            </value>
            <value>
                <fullName>School Representative</fullName>
                <label>Secondary School Representative</label>
            </value>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>External Contact</fullName>
            </value>
            <value>
                <fullName>HDR Student</fullName>
                <label>Graduate Researcher</label>
            </value>
            <value>
                <fullName>Student Lead (Int)</fullName>
            </value>
            <value>
                <fullName>Nominated Affiliation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <description>Indicates the status of the Affiliation.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>I_RM_Role__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>I_ST_Contact_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Time_Frame_to_Study__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Time_Frame_to_Study__c</fullName>
    <description>Student Lead (Dom) Affiliation&apos;s time trame to study.</description>
    <label>Time Frame to Study</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>I_ST_Time_Frame_to_Study</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_ST_Scheduled_Information_Rollover__mdt/I_ST_Scheduled_Information_Rollover__mdt.object-meta.xml
<CustomObject>
    <label>Lead Information Rollover</label>
    <pluralLabel>Lead Information Rollover</pluralLabel>
</CustomObject>

force-app/main/default/objects/I_ST_Scheduled_Information_Rollover__mdt/fields/I_ST_Active__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/I_ST_Scheduled_Information_Rollover__mdt/fields/I_ST_From__c.field-meta.xml
<CustomField>
    <fullName>I_ST_From__c</fullName>
    <label>From</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_ST_Scheduled_Information_Rollover__mdt/fields/I_ST_To__c.field-meta.xml
<CustomField>
    <fullName>I_ST_To__c</fullName>
    <label>To</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/I_ST_Contact_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Admitted</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And LOA</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Not Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Considered</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Made</fullName>
    </customValue>
    <customValue>
        <fullName>Await Academic Advice</fullName>
    </customValue>
    <customValue>
        <fullName>Await Applicant Comms</fullName>
    </customValue>
    <customValue>
        <fullName>Await Further Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Awaiting Interview</fullName>
    </customValue>
    <customValue>
        <fullName>Await Required Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Escalated</fullName>
    </customValue>
    <customValue>
        <fullName>Make A Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make Alternate Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make An Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Nearing Completion</fullName>
    </customValue>
    <customValue>
        <fullName>Not Processed</fullName>
    </customValue>
    <customValue>
        <fullName>Not Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Lapsed</fullName>
    </customValue>
    <customValue>
        <fullName>Other Preference Offered</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Results</fullName>
    </customValue>
    <customValue>
        <fullName>Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <description>Global value set is created for lead(contact) object ST -51</description>
    <masterLabel>I_ST_Contact_Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/I_ST_Enquirer_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Year 9</fullName>
    </customValue>
    <customValue>
        <fullName>Year 10</fullName>
    </customValue>
    <customValue>
        <fullName>Year 11</fullName>
    </customValue>
    <customValue>
        <fullName>Year 12</fullName>
    </customValue>
    <customValue>
        <fullName>Recent school leaver (18-20)</fullName>
    </customValue>
    <customValue>
        <fullName>Mature age (21+)</fullName>
    </customValue>
    <customValue>
        <fullName>Industry qualified or experienced</fullName>
    </customValue>
    <customValue>
        <fullName>Direct applicant</fullName>
    </customValue>
    <customValue>
        <fullName>University graduate (other uni)</fullName>
    </customValue>
    <customValue>
        <fullName>University graduate (LTU)</fullName>
    </customValue>
    <customValue>
        <fullName>International (outside Australia)</fullName>
    </customValue>
    <customValue>
        <fullName>International (inside Australia)</fullName>
    </customValue>
    <customValue>
        <fullName>TAFE graduate</fullName>
    </customValue>
    <customValue>
        <fullName>Current students (LTU) - UG</fullName>
    </customValue>
    <customValue>
        <fullName>Current students (LTU) - PG</fullName>
    </customValue>
    <customValue>
        <fullName>Current students (other uni) - UG</fullName>
    </customValue>
    <customValue>
        <fullName>Current students (other uni) - PG</fullName>
    </customValue>
    <customValue>
        <fullName>Current student (other) - TAFE</fullName>
    </customValue>
    <customValue>
        <fullName>Current student (LTU) - Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Parent</fullName>
    </customValue>
    <customValue>
        <fullName>Careers advisor / Careers counsellor</fullName>
    </customValue>
    <customValue>
        <fullName>Teacher</fullName>
    </customValue>
    <customValue>
        <fullName>Principal</fullName>
    </customValue>
    <customValue>
        <fullName>International agent</fullName>
    </customValue>
    <customValue>
        <fullName>Business Owner / Contact</fullName>
    </customValue>
    <customValue>
        <fullName>Industry partner</fullName>
    </customValue>
    <customValue>
        <fullName>Industry association</fullName>
    </customValue>
    <customValue>
        <fullName>Accrediting Body</fullName>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <customValue>
        <fullName>Staff</fullName>
    </customValue>
    <description>Created for IST-43</description>
    <masterLabel>I_ST_Enquirer_Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/I_ST_Time_Frame_to_Study.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1-3 months</fullName>
    </customValue>
    <customValue>
        <fullName>3-6 months</fullName>
    </customValue>
    <customValue>
        <fullName>6-12 months</fullName>
    </customValue>
    <customValue>
        <fullName>1-2 years</fullName>
    </customValue>
    <customValue>
        <fullName>2-3 years</fullName>
    </customValue>
    <customValue>
        <fullName>3+ years</fullName>
    </customValue>
    <customValue>
        <fullName>Unsure</fullName>
    </customValue>
    <customValue>
        <fullName>12+ months</fullName>
        <isActive>false</isActive>
        <label>12+ months</label>
    </customValue>
    <description>Created for IST 43</description>
    <masterLabel>I_ST_Time_Frame_to_Study</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/I_ST_InformationRolloverBatch.cls
public with sharing class I_ST_InformationRolloverBatch implements Database.Batchable<sobject>{
    public final List<I_ST_Scheduled_Information_Rollover__mdt> rolloverMappings;
    public final Map<String, Set<String>> mappingMap;
    public final Map<String, String> rolloverMap;
    public I_ST_InformationRolloverBatch(){
        mappingMap = new Map<String, Set<String>>();
        rolloverMap = new Map<String, String>();
        rolloverMappings = [SELECT I_ST_Field_API_Name__c, I_ST_From__c, I_ST_To__c FROM I_ST_Scheduled_Information_Rollover__mdt WHERE I_ST_Active__c = True];
        for(I_ST_Scheduled_Information_Rollover__mdt rolloverMapping: rolloverMappings){
            rolloverMap.put(rolloverMapping.I_ST_From__c, rolloverMapping.I_ST_To__c);
            if(!mappingMap.containsKey(rolloverMapping.I_ST_Field_API_Name__c)){
                mappingMap.put(rolloverMapping.I_ST_Field_API_Name__c, new Set<String>{rolloverMapping.I_ST_From__c});
            } else{
                mappingMap.get(rolloverMapping.I_ST_Field_API_Name__c).add(rolloverMapping.I_ST_From__c);
            }
        }
    }
    public Database.Querylocator start (Database.BatchableContext BC) {
        String query = 'SELECT Name, ' + String.join(new List<String>(mappingMap.keySet()),', ') + ' FROM I_RM_Affiliation__c';       
        query += ' WHERE I_RM_Contact__r.I_RS_Deceased__c = FALSE';
        query += ' AND I_RM_Contact__r.I_ST_Sanctioned_Student__c = FALSE';
        query += ' AND I_RM_Status__c != \'Inactive\'' ;
        query += ' AND (I_RM_Time_Frame_to_Study__c != null';
        query += ' OR I_RM_Enquirer_Type__c != null)';
        query += ' AND I_RM_Role__c IN (\'Applicant\', \'Domestic Lead\')';
                 
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext BC, List<I_RM_Affiliation__c> rolloverContacts) {
        String contactFieldValue;
       for(I_RM_Affiliation__c rolloverContact: rolloverContacts){
            //mappingMap not kept from global setting
            for(String mappedField: mappingMap.keySet()){
                contactFieldValue = (String) rolloverContact.get(mappedField);
                if(contactFieldValue != null && rolloverMap.keySet().contains(contactFieldValue)){
                    rolloverContact.put(mappedField, rolloverMap.get(contactFieldValue));
                }
                 
            }
          
        }
        
        Database.SaveResult[] uList = Database.update(rolloverContacts, false); 
        
    }  
    public void finish(Database.BatchableContext bc){
    } 
}