force-app/main/default/objects/Contact/fields/I_RS_Active__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/I_RS_Manager__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User who will inherit access to this individuals Project and Funding Opportunity data</description>
    <label>Manager User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Subordinates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Team_Member__c/Project_Team_Member__c.object-meta.xml
<CustomObject>
    <label>Project Team Member</label>
    <nameField>
        <displayFormat>PTM-{00000}</displayFormat>
        <label>Title</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Team_Member__c/fields/I_RS_Active__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Those who are active will have Apex sharing for all Project Proposal and related records</description>
    <inlineHelpText>When ticked the individual named on this record can view this project and related items if they are a PRIME user.</inlineHelpText>
    <label>Visibility of Project</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_Team_Member__c/fields/I_RS_Project_Proposal__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Project_Proposal__c</fullName>
    <description>Related to project proposal</description>
    <label>Project Proposal</label>
    <referenceTo>Project_Proposal__c</referenceTo>
    <relationshipLabel>Project Team Members</relationshipLabel>
    <relationshipName>Team_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Team_Member__c/fields/I_RS_Project_Team_Member__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Project_Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Team Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects/Proposals</relationshipLabel>
    <relationshipName>Project_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Team_Member__c/fields/I_RS_Role__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Project_Team_Member_Role</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContactManagerPTMAccess.cls
public without sharing class ContactManagerPTMAccess implements System.Queueable {
    
    public static Boolean recalculationEnabled = true;

    Set<Id> contactIdsToRecalculateSharingFor;
    

    public static void checkThenExecute(List<Contact> contactsAfterDML, Map<Id, Contact> contactsBeforeDML){

        Set<Id> teamMemberContactIds = new Set<Id>();
        for (Contact contactAfterDML : contactsAfterDML){
            Contact contactBeforeDML = contactsBeforeDML.get(contactAfterDML.Id);

            String previousManagerId = contactBeforeDML.I_RS_Manager__c;
            String currentManagerId = contactAfterDML.I_RS_Manager__c;

            if (previousManagerId != currentManagerId){
                teamMemberContactIds.add(contactAfterDML.Id);
            }
        }

        if (!teamMemberContactIds.isEmpty()){
            ContactManagerPTMAccess access = 
                new ContactManagerPTMAccess(teamMemberContactIds);

            if (!GlobalUtility.currentContextIsAsync()){
                System.enqueueJob(access);
            }
            else {
                access.run();
            }
        }

    }


    public ContactManagerPTMAccess(Set<Id> contactIdsToRecalculateSharingFor){
        this.contactIdsToRecalculateSharingFor = contactIdsToRecalculateSharingFor;
    }


    public void execute(System.QueueableContext qc){
        run();
    }

    void run(){

        List<Project_Team_Member__c> reducedPTMList = [
            SELECT Id, I_RS_Project_Team_Member__c, I_RS_Project_Proposal__c FROM Project_Team_Member__c
        	WHERE I_RS_Project_Team_Member__c IN :contactIdsToRecalculateSharingFor
            AND I_RS_Active__c = TRUE
            AND (I_RS_Role__c != 'Approver' AND I_RS_Role__c != 'Research Centre Member')
        ];
        
        ProjectTeamMemberAccess4.runForTeamMembers(reducedPTMList, 'All', false, false);

    }
}