force-app/main/default/objects/Contact/fields/I_RS_Is_Organisation_Confidential__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Is_Organisation_Confidential__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Organisation Confidential?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CourseAvailability__c/CourseAvailability__c.object-meta.xml
<CustomObject>
    <label>Course Availability</label>
    <nameField>
        <displayFormat>AID-CA-{0000}</displayFormat>
        <label>Course Availability ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Availabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CourseAvailability__c/fields/I_ST_Application_Census_Date__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Application_Census_Date__c</fullName>
    <description>Added for IST-338</description>
    <label>Application Census Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CourseAvailability__c/fields/L_AD_CourseInstance__c.field-meta.xml
<CustomField>
    <fullName>L_AD_CourseInstance__c</fullName>
    <label>Course Instance</label>
    <referenceTo>CourseInstance__c</referenceTo>
    <relationshipLabel>Course Availability</relationshipLabel>
    <relationshipName>Course_Availability</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CourseInstance__c/CourseInstance__c.object-meta.xml
<CustomObject>
    <description>Location specific details of a course</description>
    <label>Course Instance</label>
    <nameField>
        <displayFormat>AID-CI-{0000}</displayFormat>
        <label>Course Instance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Instance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CourseInstance__c/fields/I_ST_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>I_ST_ExternalId__c</fullName>
    <description>Concatenation of Course Parent Code, Course Parent Version Number, Course Parent Version Year, Course Instance Code, Course Instance Version Number and Course Instance Version Year</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CourseInstance__c/fields/L_AD_CourseParent__c.field-meta.xml
<CustomField>
    <fullName>L_AD_CourseParent__c</fullName>
    <label>Course Parent ID</label>
    <referenceTo>CourseParent__c</referenceTo>
    <relationshipLabel>Course Instance</relationshipLabel>
    <relationshipName>Course_Instance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CourseParent__c/CourseParent__c.object-meta.xml
<CustomObject>
    <label>Course Parent</label>
    <nameField>
        <label>Course Parent ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Parent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CourseParent__c/fields/I_ST_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>I_ST_ExternalId__c</fullName>
    <description>Concatenation of Course Parent Code, Course Parent Version Number and Course Parent Version Year</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/I_RM_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Part of the remediation project to store different personas</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Contact__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Contact__c</fullName>
    <description>The person/contact who this Affiliation relates to</description>
    <inlineHelpText>The person this affiliation relates to</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Affiliations</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Enquirer_Type__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Enquirer_Type__c</fullName>
    <description>Depicts how best to describe the Enquirer, Applicable for Student Lead (Dom),Student Applicant (Dom) and Secondary School Rep</description>
    <inlineHelpText>This is the Enquirer Type</inlineHelpText>
    <label>What best describes you?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>I_ST_Enquirer_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Incremental_Score__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Incremental_Score__c</fullName>
    <description>This field is used for automated Contact scoring</description>
    <label>Activity Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Mobile_Phone__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Mobile_Phone__c</fullName>
    <description>Depicts affiliation&apos;s Mobile Phone number</description>
    <label>Mobile Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Role__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Role__c</fullName>
    <description>This represents the role of the affiliation</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Domestic Lead</fullName>
                <label>Student Lead (Dom)</label>
            </value>
            <value>
                <fullName>Applicant</fullName>
                <label>Student Applicant (Dom)</label>
            </value>
            <value>
                <fullName>La Trobe Staff</fullName>
            </value>
            <value>
                <fullName>School Representative</fullName>
                <label>Secondary School Representative</label>
            </value>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>External Contact</fullName>
            </value>
            <value>
                <fullName>HDR Student</fullName>
                <label>Graduate Researcher</label>
            </value>
            <value>
                <fullName>Student Lead (Int)</fullName>
            </value>
            <value>
                <fullName>Nominated Affiliation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Score__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Score__c</fullName>
    <description>This Fields shows the calculated score of an affiliation based on key attributes being populated</description>
    <label>Affiliation Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <description>Indicates the status of the Affiliation.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>I_RM_Role__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>I_ST_Contact_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Time_Frame_to_Study__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Time_Frame_to_Study__c</fullName>
    <description>Student Lead (Dom) Affiliation&apos;s time trame to study.</description>
    <label>Time Frame to Study</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>I_ST_Time_Frame_to_Study</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_IL_Student_Lead_Int.recordType-meta.xml
<RecordType>
    <fullName>I_IL_Student_Lead_Int</fullName>
    <active>true</active>
    <description>New International Lead who can be a prospective student of La Trobe University</description>
    <label>Student Lead (Int)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_Applicant.recordType-meta.xml
<RecordType>
    <fullName>I_RM_Applicant</fullName>
    <active>true</active>
    <description>An individual who has applied to study at La Trobe University</description>
    <label>Student Applicant (Dom)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_Lead.recordType-meta.xml
<RecordType>
    <fullName>I_RM_Lead</fullName>
    <active>true</active>
    <description>New Domestic Lead who is a prospective student of La Trobe University</description>
    <label>Student Lead (Dom)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/I_RM_Affiliation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Affiliation Settings</label>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_ST_Application__c/I_ST_Application__c.object-meta.xml
<CustomObject>
    <description>Custom object to show under Related list of contact as part of IST-240</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_ST_Application__c/fields/I_RM_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Facilitate relationship with the Affiliation object</description>
    <label>Affiliation</label>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/I_ST_Application__c/fields/I_ST_Application_Census_Date__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Application_Census_Date__c</fullName>
    <formula>I_ST_Course_Availability__r.I_ST_Application_Census_Date__c</formula>
    <label>Application Census Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/I_ST_Application__c/fields/I_ST_Application_Lapsed__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Application_Lapsed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Added for IST-457</description>
    <label>Application Lapsed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/I_ST_Application__c/fields/I_ST_Application_Status__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Application_Status__c</fullName>
    <description>for IST-164</description>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alternate offer considered</fullName>
            </value>
            <value>
                <fullName>Alternate Offer Declined</fullName>
            </value>
            <value>
                <fullName>Alternate offer made</fullName>
            </value>
            <value>
                <fullName>Application in error</fullName>
            </value>
            <value>
                <fullName>Application Withdrawn</fullName>
            </value>
            <value>
                <fullName>Await academic advice</fullName>
            </value>
            <value>
                <fullName>Await applicant comms</fullName>
            </value>
            <value>
                <fullName>Await further doco</fullName>
            </value>
            <value>
                <fullName>Awaiting interview</fullName>
            </value>
            <value>
                <fullName>Await required doco</fullName>
            </value>
            <value>
                <fullName>Conditional offer</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Make a conditional offer</fullName>
            </value>
            <value>
                <fullName>Make alternate offer</fullName>
            </value>
            <value>
                <fullName>Make an offer</fullName>
            </value>
            <value>
                <fullName>Not processed</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Offer Rescinded</fullName>
            </value>
            <value>
                <fullName>Other Preference offered</fullName>
            </value>
            <value>
                <fullName>Pending results</fullName>
            </value>
            <value>
                <fullName>Rejected &amp; Referred</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
            <value>
                <fullName>Unsuccessful, not notified</fullName>
            </value>
            <value>
                <fullName>Withdrawn preference</fullName>
            </value>
            <value>
                <fullName>Admitted And Not Enrolled</fullName>
            </value>
            <value>
                <fullName>Admitted And Enrolled</fullName>
            </value>
            <value>
                <fullName>Offer Admitted</fullName>
            </value>
            <value>
                <fullName>Offer Accepted</fullName>
            </value>
            <value>
                <fullName>Offer</fullName>
            </value>
            <value>
                <fullName>Offer Deferred</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_ST_Application__c/fields/I_ST_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>I_ST_ExternalId__c</fullName>
    <description>Unique foreign key for integration with value of the concatenation of Contact Id and Course Availability Code</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/I_ST_Contact_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Admitted</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And LOA</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Not Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Considered</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Made</fullName>
    </customValue>
    <customValue>
        <fullName>Await Academic Advice</fullName>
    </customValue>
    <customValue>
        <fullName>Await Applicant Comms</fullName>
    </customValue>
    <customValue>
        <fullName>Await Further Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Awaiting Interview</fullName>
    </customValue>
    <customValue>
        <fullName>Await Required Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Escalated</fullName>
    </customValue>
    <customValue>
        <fullName>Make A Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make Alternate Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make An Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Nearing Completion</fullName>
    </customValue>
    <customValue>
        <fullName>Not Processed</fullName>
    </customValue>
    <customValue>
        <fullName>Not Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Lapsed</fullName>
    </customValue>
    <customValue>
        <fullName>Other Preference Offered</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Results</fullName>
    </customValue>
    <customValue>
        <fullName>Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrawn</fullName>
        <isActive>false</isActive>
        <label>Withdrawn</label>
    </customValue>
    <description>Global value set is created for lead(contact) object ST -51</description>
    <masterLabel>I_ST_Contact_Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/I_ST_Enquirer_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Year 9</fullName>
    </customValue>
    <customValue>
        <fullName>Year 10</fullName>
    </customValue>
    <customValue>
        <fullName>Year 11</fullName>
    </customValue>
    <customValue>
        <fullName>Year 12</fullName>
    </customValue>
    <customValue>
        <fullName>Recent school leaver (18-20)</fullName>
    </customValue>
    <customValue>
        <fullName>Mature age (21+)</fullName>
    </customValue>
    <customValue>
        <fullName>Industry qualified or experienced</fullName>
    </customValue>
    <customValue>
        <fullName>Direct applicant</fullName>
    </customValue>
    <customValue>
        <fullName>University graduate (other uni)</fullName>
    </customValue>
    <customValue>
        <fullName>University graduate (LTU)</fullName>
    </customValue>
    <customValue>
        <fullName>International (outside Australia)</fullName>
    </customValue>
    <customValue>
        <fullName>International (inside Australia)</fullName>
    </customValue>
    <customValue>
        <fullName>TAFE graduate</fullName>
    </customValue>
    <customValue>
        <fullName>Current students (LTU) - UG</fullName>
    </customValue>
    <customValue>
        <fullName>Current students (LTU) - PG</fullName>
    </customValue>
    <customValue>
        <fullName>Current students (other uni) - UG</fullName>
    </customValue>
    <customValue>
        <fullName>Current students (other uni) - PG</fullName>
    </customValue>
    <customValue>
        <fullName>Current student (other) - TAFE</fullName>
    </customValue>
    <customValue>
        <fullName>Current student (LTU) - Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Parent</fullName>
    </customValue>
    <customValue>
        <fullName>Careers advisor / Careers counsellor</fullName>
    </customValue>
    <customValue>
        <fullName>Teacher</fullName>
    </customValue>
    <customValue>
        <fullName>Principal</fullName>
    </customValue>
    <customValue>
        <fullName>International agent</fullName>
    </customValue>
    <customValue>
        <fullName>Business Owner / Contact</fullName>
    </customValue>
    <customValue>
        <fullName>Industry partner</fullName>
    </customValue>
    <customValue>
        <fullName>Industry association</fullName>
    </customValue>
    <customValue>
        <fullName>Accrediting Body</fullName>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <customValue>
        <fullName>Staff</fullName>
    </customValue>
    <description>Created for IST-43</description>
    <masterLabel>I_ST_Enquirer_Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/I_ST_Time_Frame_to_Study.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1-3 months</fullName>
    </customValue>
    <customValue>
        <fullName>3-6 months</fullName>
    </customValue>
    <customValue>
        <fullName>6-12 months</fullName>
    </customValue>
    <customValue>
        <fullName>1-2 years</fullName>
    </customValue>
    <customValue>
        <fullName>2-3 years</fullName>
    </customValue>
    <customValue>
        <fullName>3+ years</fullName>
    </customValue>
    <customValue>
        <fullName>Unsure</fullName>
    </customValue>
    <customValue>
        <fullName>12+ months</fullName>
        <isActive>false</isActive>
        <label>12+ months</label>
    </customValue>
    <description>Created for IST 43</description>
    <masterLabel>I_ST_Time_Frame_to_Study</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/I_RM_ApplicantAffStatusUpdateBatchTest.cls
/* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* I_RM_ApplicantAffStatusUpdateBatch
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Teja Yenduri   <tyenduri@au1.ibm.com>
* @version        1.0
* @created        2022-02-18
  @JIRA           LTU360-867
  @Description	  This class is used to update status field of Affiliation
   @Params	  	  <sObjectName>: Object API Name, <recordTypeIds>: Set of RecordTypeIds for Score Calculation, lastNumberOfHours: Run batch past N Hours
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* @changes
* v1.0           Teja Yenduri
* 2022-03-16      Created
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/
@isTest
public class I_RM_ApplicantAffStatusUpdateBatchTest {
    @TestSetup
    static void makeData(){

        String recTypeIdsForAffScoring = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Applicant').getRecordTypeId();
        recTypeIdsForAffScoring += ',' + Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Lead').getRecordTypeId();
        recTypeIdsForAffScoring += ',' + Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_IL_Student_Lead_Int').getRecordTypeId();
        TestUtility.createBatchScoringCustomSettings(recTypeIdsForAffScoring);
        
        I_RM_Affiliation_Settings__c objAffiliationSettings = new I_RM_Affiliation_Settings__c(Name = 'I_RM_Inactive_Status',
        I_RM_Status__c = 'Inactive');
        insert objAffiliationSettings;
        I_RM_Affiliation_Settings__c objApplicationSettings = new I_RM_Affiliation_Settings__c(Name = 'I_RM_Inactive_Application_Status',
        I_RM_Status__c = 'Alternate Offer Declined;Withdrawn;Unoffered;');                                                                                                       
        insert objApplicationSettings;
        I_RM_Affiliation_Settings__c objApplicantAffiliationBatchSettings = new I_RM_Affiliation_Settings__c( Name= 'I_RM_ApplicantAffiliationStatusBatch',
        Value__c ='oneTime'); 
        insert objApplicantAffiliationBatchSettings;
    }
    
    @isTest
    public static void testAffiliationStatus(){
         
       
        Id affiliationApplicantRecordTypeId = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Applicant').getRecordTypeId(); 
        Account tstAccount = TestUtility.newEmptyExternalAccount('testAccount001');
        insert tstAccount;
        
        Contact cont = I_ST_UnitTestUtilities.createContactForScore('test_unique0001',
        'unique_test0001',
        'test_unique0001@unique.com',
        'test_unique0001@unique.com',        
        '3029');
        cont.I_RS_Is_Organisation_Confidential__c = false;
        insert cont;
        
        
        I_RM_Affiliation__c newAffiliation = new I_RM_Affiliation__c(I_RM_Contact__c = cont.Id,
                                                                  recordTypeId = affiliationApplicantRecordTypeId,
                                                                  I_RM_Enquirer_Type__c ='Year 11',
                                                                  I_RM_Time_Frame_to_Study__c= '3-6 months',
                                                                  I_RM_Incremental_Score__c = 0,
                                                                  I_RM_Mobile_Phone__c = '0415822665',
                                                                  I_RM_Role__c ='Applicant',
                                                                  I_RM_Status__c  ='Not Processed',   
                                                                  I_RM_Score__c = 0   
                                                                 );
        insert newAffiliation;

        CourseParent__c courseParent =  new CourseParent__c(
            I_ST_ExternalId__c = '009833'
        );
        insert courseParent;

        CourseInstance__c courseInstance =  new CourseInstance__c(
            I_ST_ExternalId__c = '009833',
            L_AD_CourseParent__c = courseParent.Id
        );
        insert courseInstance;

        CourseAvailability__c courseAvailability = new CourseAvailability__c(
            I_ST_ExternalId__c = '009833',
            L_AD_CourseInstance__c = courseInstance.Id,
            I_ST_Application_Census_Date__c = system.today() + 1
        );
        insert courseAvailability;
        
          CourseAvailability__c courseAvailability2 = new CourseAvailability__c(
            I_ST_ExternalId__c = '009823',
            L_AD_CourseInstance__c = courseInstance.Id,
            I_ST_Application_Census_Date__c = system.today() - 1
        );
        insert courseAvailability2;

        List<I_ST_Application__c> listApp = New List<I_ST_Application__c>();

        I_ST_Application__c createApplication1 = I_ST_UnitTestUtilities.createApplication(cont.Id, courseAvailability2.Id);
        createApplication1.I_RM_Affiliation__c = newAffiliation.Id;
        createApplication1.I_ST_Application_Lapsed__c = false;
        createApplication1.I_ST_Application_Status__c = 'Await required doco';
        listApp.add(createApplication1);

        I_ST_Application__c createApplication2 = I_ST_UnitTestUtilities.createApplication(cont.Id, courseAvailability.Id);
        createApplication2.I_RM_Affiliation__c = newAffiliation.Id;
        createApplication2.I_ST_Application_Lapsed__c = false;
        createApplication2.I_ST_Application_Status__c = 'Conditional offer';
        listApp.add(createApplication2);
        
		insert listApp;
     
        
        Test.startTest();
        I_RM_ApplicantAffStatusUpdateBatch b = new I_RM_ApplicantAffStatusUpdateBatch();        
        database.executebatch(b,20);
        Test.stopTest();
        
        List<I_RM_Affiliation__c> updatedAffl = [Select Id, I_RM_Status__c from I_RM_Affiliation__c where Id =: newAffiliation.id];
        System.assertEquals('Conditional Offer', updatedAffl[0].I_RM_Status__c);

    }
    
    
    @isTest
    public static void testAffiliationStatusToInactive(){
         
       
        Id affiliationApplicantRecordTypeId = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Applicant').getRecordTypeId(); 
        Account tstAccount = TestUtility.newEmptyExternalAccount('testAccount002');
        insert tstAccount;
        
        Contact cont = I_ST_UnitTestUtilities.createContactForScore('test_unique0002',
        'unique_test0002',
        'test_unique0002@unique.com',
        'test_unique0002@unique.com',        
        '3029');
        cont.I_RS_Is_Organisation_Confidential__c = false;
        insert cont;
        
        
        I_RM_Affiliation__c newAffiliation = new I_RM_Affiliation__c(I_RM_Contact__c = cont.Id,
                                                                  recordTypeId = affiliationApplicantRecordTypeId,
                                                                  I_RM_Enquirer_Type__c ='Year 11',
                                                                  I_RM_Time_Frame_to_Study__c= '3-6 months',
                                                                  I_RM_Incremental_Score__c = 0,
                                                                  I_RM_Mobile_Phone__c = '0415822665',
                                                                  I_RM_Role__c ='Applicant',
                                                                  I_RM_Status__c  ='Not Processed',   
                                                                  I_RM_Score__c = 0   
                                                                 );
        insert newAffiliation;

        CourseParent__c courseParent =  new CourseParent__c(
            I_ST_ExternalId__c = '009823'
        );
        insert courseParent;

        CourseInstance__c courseInstance =  new CourseInstance__c(
            I_ST_ExternalId__c = '009823',
            L_AD_CourseParent__c = courseParent.Id
        );
        insert courseInstance;

        CourseAvailability__c courseAvailability = new CourseAvailability__c(
            I_ST_ExternalId__c = '009823',
            L_AD_CourseInstance__c = courseInstance.Id,
            I_ST_Application_Census_Date__c = system.today() - 1
        );
        insert courseAvailability;
        
        CourseAvailability__c courseAvailability2 = new CourseAvailability__c(
            I_ST_ExternalId__c = '009820',
            L_AD_CourseInstance__c = courseInstance.Id,
            I_ST_Application_Census_Date__c = system.today() + 1
        );
        insert courseAvailability2;

        I_ST_Application__c createApplication1 = new I_ST_Application__c(
            Name = 'TestA4',
            I_ST_ExternalId__c = '009822',
            I_ST_Course_Availability__c = courseAvailability2.Id,
            I_ST_Contact__c = cont.Id,
            I_RM_Affiliation__c = newAffiliation.id,
            I_ST_Application_Status__c ='Withdrawn'
        );
       
        insert createApplication1;
        
        
        I_ST_Application__c createApplication2 = new I_ST_Application__c(
            Name = 'TestA5',
            I_ST_ExternalId__c = '009823',
            I_ST_Course_Availability__c = courseAvailability.Id,
            I_ST_Contact__c = cont.Id,
            I_RM_Affiliation__c = newAffiliation.id
        );
        
        insert createApplication2;  
       
        
        
        Test.startTest();
        I_RM_ApplicantAffStatusUpdateBatch b = new I_RM_ApplicantAffStatusUpdateBatch();        
        database.executebatch(b,20);
        Test.stopTest();
        
        List<I_RM_Affiliation__c> updatedAffl = [Select Id, I_RM_Status__c from I_RM_Affiliation__c where Id =: newAffiliation.id];
        System.assertEquals('Inactive', updatedAffl[0].I_RM_Status__c);

    }
    
    @isTest
    public static void testForSceduler(){
        String hour = String.valueOf(Datetime.now().hour());
        String min = String.valueOf(Datetime.now().minute() ); 
        String ss = String.valueOf(Datetime.now().second());
        
        //parse to cron expression
        String nextFireTime = ss + ' ' + min + ' ' + hour + ' * * ?';
        test.startTest();
        I_RM_ApplicantAffStatusUpdateScheduler SC = new I_RM_ApplicantAffStatusUpdateScheduler(20); 
        Id jobId  =   system.schedule('TEST I_RM_ApplicantAffStatusUpdateBatch', nextFireTime , SC);
        test.stopTest();
        // Get the information from the CronTrigger API object
     	CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered,NextFireTime FROM CronTrigger WHERE id = :jobId];
        System.assertEquals(nextFireTime,ct.CronExpression);
    }

}