force-app/main/default/objects/Contact/fields/I_ST_Personal_Email__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Personal_Email__c</fullName>
    <description>Created to allow user to store personal email</description>
    <externalId>true</externalId>
    <inlineHelpText>The personal email for this person.</inlineHelpText>
    <label>Student Lead Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/CourseAvailability__c/CourseAvailability__c.object-meta.xml
<CustomObject>
    <label>Course Availability</label>
    <nameField>
        <displayFormat>AID-CA-{0000}</displayFormat>
        <label>Course Availability ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Availabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CourseAvailability__c/fields/L_AD_CourseInstance__c.field-meta.xml
<CustomField>
    <fullName>L_AD_CourseInstance__c</fullName>
    <label>Course Instance</label>
    <referenceTo>CourseInstance__c</referenceTo>
    <relationshipLabel>Course Availability</relationshipLabel>
    <relationshipName>Course_Availability</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CourseInstance__c/CourseInstance__c.object-meta.xml
<CustomObject>
    <description>Location specific details of a course</description>
    <label>Course Instance</label>
    <nameField>
        <displayFormat>AID-CI-{0000}</displayFormat>
        <label>Course Instance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Instance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CourseInstance__c/fields/I_ST_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>I_ST_ExternalId__c</fullName>
    <description>Concatenation of Course Parent Code, Course Parent Version Number, Course Parent Version Year, Course Instance Code, Course Instance Version Number and Course Instance Version Year</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CourseInstance__c/fields/L_AD_CourseParent__c.field-meta.xml
<CustomField>
    <fullName>L_AD_CourseParent__c</fullName>
    <label>Course Parent ID</label>
    <referenceTo>CourseParent__c</referenceTo>
    <relationshipLabel>Course Instance</relationshipLabel>
    <relationshipName>Course_Instance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CourseParent__c/CourseParent__c.object-meta.xml
<CustomObject>
    <label>Course Parent</label>
    <nameField>
        <label>Course Parent ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Parent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CourseParent__c/fields/I_ST_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>I_ST_ExternalId__c</fullName>
    <description>Concatenation of Course Parent Code, Course Parent Version Number and Course Parent Version Year</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CourseParent__c/fields/L_AD_Course_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>L_AD_Course_Type_Name__c</fullName>
    <description>Course Type Name</description>
    <label>Course Type Name</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/I_RM_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Part of the remediation project to store different personas</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Contact__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Contact__c</fullName>
    <description>The person/contact who this Affiliation relates to</description>
    <inlineHelpText>The person this affiliation relates to</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Affiliations</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Country__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Country__c</fullName>
    <description>Country of the Work/Home address</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>I_RM_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Email__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Email__c</fullName>
    <description>Depicts Personal Email</description>
    <inlineHelpText>The personal email for this person.</inlineHelpText>
    <label>Personal Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Mailing_Country__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Mailing_Country__c</fullName>
    <description>Mailing Address Country</description>
    <label>Mailing Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>I_RM_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Mailing_Postcode__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Mailing_Postcode__c</fullName>
    <description>Mailing Address Postcode</description>
    <label>Mailing Postcode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Mailing_State__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Mailing_State__c</fullName>
    <description>Mailing Address State</description>
    <label>Mailing State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Mailing_Street__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Mailing_Street__c</fullName>
    <description>Mailing Address Street</description>
    <label>Mailing Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Mailing_Suburb__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Mailing_Suburb__c</fullName>
    <description>Mailing Address Suburb</description>
    <label>Mailing City/Suburb</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Mobile_Phone__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Mobile_Phone__c</fullName>
    <description>Depicts affiliation&apos;s Mobile Phone number</description>
    <label>Mobile Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Other_Phone__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Other_Phone__c</fullName>
    <description>Depicts affiliation&apos;s Work Phone number</description>
    <label>Work Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Phone__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Phone__c</fullName>
    <description>Depicts affiliation&apos;s Home Phone number</description>
    <label>Home Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Postcode__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Postcode__c</fullName>
    <description>Post Code of work / home address.</description>
    <label>Postcode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Role__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Role__c</fullName>
    <description>This represents the role of the affiliation</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Domestic Lead</fullName>
                <label>Student Lead (Dom)</label>
            </value>
            <value>
                <fullName>Applicant</fullName>
                <label>Student Applicant (Dom)</label>
            </value>
            <value>
                <fullName>La Trobe Staff</fullName>
            </value>
            <value>
                <fullName>School Representative</fullName>
                <label>Secondary School Representative</label>
            </value>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>External Contact</fullName>
            </value>
            <value>
                <fullName>HDR Student</fullName>
                <label>Graduate Researcher</label>
            </value>
            <value>
                <fullName>Student Lead (Int)</fullName>
            </value>
            <value>
                <fullName>Nominated Affiliation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_State__c.field-meta.xml
<CustomField>
    <fullName>I_RM_State__c</fullName>
    <description>State of the Work/Home address</description>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <description>Indicates the status of the Affiliation.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>I_RM_Role__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>I_ST_Contact_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Street__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Street__c</fullName>
    <description>Street of the Work/Home address</description>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Suburb__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Suburb__c</fullName>
    <description>Suburb of the Work/Home address</description>
    <label>City/Suburb</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_IL_Student_Lead_Int.recordType-meta.xml
<RecordType>
    <fullName>I_IL_Student_Lead_Int</fullName>
    <active>true</active>
    <description>New International Lead who can be a prospective student of La Trobe University</description>
    <label>Student Lead (Int)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_Applicant.recordType-meta.xml
<RecordType>
    <fullName>I_RM_Applicant</fullName>
    <active>true</active>
    <description>An individual who has applied to study at La Trobe University</description>
    <label>Student Applicant (Dom)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_Lead.recordType-meta.xml
<RecordType>
    <fullName>I_RM_Lead</fullName>
    <active>true</active>
    <description>New Domestic Lead who is a prospective student of La Trobe University</description>
    <label>Student Lead (Dom)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_Student.recordType-meta.xml
<RecordType>
    <fullName>I_RM_Student</fullName>
    <active>true</active>
    <description>Persons who are currently a student of La Trobe</description>
    <label>Student</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/I_RM_Affiliation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Affiliation Settings</label>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/fields/I_RM_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_ST_Student_Course__c/I_ST_Student_Course__c.object-meta.xml
<CustomObject>
    <description>Junction object between Student (Contact) and Course (Course Availability)</description>
    <label>Student Course</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>Student Course Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_ST_Student_Course__c/fields/I_RM_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Affiliation</description>
    <label>Affiliation</label>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>Student Courses</relationshipLabel>
    <relationshipName>Student_Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/I_ST_Student_Course__c/fields/I_ST_Course_Admission_Stage_Code__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Course_Admission_Stage_Code__c</fullName>
    <description>IST-168</description>
    <label>Course Admission Stage Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_ST_Student_Course__c/fields/I_ST_Course_Admission_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Course_Admission_Status_Code__c</fullName>
    <description>for IST-168</description>
    <label>Course Admission Status Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_ST_Student_Course__c/fields/I_ST_CourseAvailability__c.field-meta.xml
<CustomField>
    <fullName>I_ST_CourseAvailability__c</fullName>
    <description>Course availability linkage as per IST-43,IST-168</description>
    <label>Course Availability</label>
    <referenceTo>CourseAvailability__c</referenceTo>
    <relationshipLabel>Student Courses</relationshipLabel>
    <relationshipName>Student_Courses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/I_ST_Student_Course__c/fields/I_ST_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>I_ST_ExternalId__c</fullName>
    <description>Unique foreign key for integration with value of the concatenation of Contact Id and Course Availability Code</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/I_ST_Student_Course__c/fields/I_ST_Student__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Student__c</fullName>
    <description>Student lookup as per IST-43,IST-168</description>
    <label>Student</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Courses</relationshipLabel>
    <relationshipName>Student_Courses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/I_RM_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Åland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Argentinian Antarctic Territory</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Australian Antarctic Territory</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas (the)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia (Plurinational State of)</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/I_ST_Contact_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Admitted</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And LOA</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted And Not Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Considered</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Offer Made</fullName>
    </customValue>
    <customValue>
        <fullName>Await Academic Advice</fullName>
    </customValue>
    <customValue>
        <fullName>Await Applicant Comms</fullName>
    </customValue>
    <customValue>
        <fullName>Await Further Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Awaiting Interview</fullName>
    </customValue>
    <customValue>
        <fullName>Await Required Doco</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Escalated</fullName>
    </customValue>
    <customValue>
        <fullName>Make A Conditional Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make Alternate Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Make An Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Nearing Completion</fullName>
    </customValue>
    <customValue>
        <fullName>Not Processed</fullName>
    </customValue>
    <customValue>
        <fullName>Not Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Lapsed</fullName>
    </customValue>
    <customValue>
        <fullName>Other Preference Offered</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Results</fullName>
    </customValue>
    <customValue>
        <fullName>Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <description>Global value set is created for lead(contact) object ST -51</description>
    <masterLabel>I_ST_Contact_Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/I_ST_Student_CourseTriggerHelperTest.cls
@isTest
public class I_ST_Student_CourseTriggerHelperTest {

    @testSetup static void setup() {
        
        String recTypeIdsForAffScoring = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Applicant').getRecordTypeId();
        recTypeIdsForAffScoring += ',' + Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Lead').getRecordTypeId();
        recTypeIdsForAffScoring += ',' + Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_IL_Student_Lead_Int').getRecordTypeId();
        TestUtility.createBatchScoringCustomSettings(recTypeIdsForAffScoring);
    }
    
    @isTest
    public static void testAluminiAffiliation1(){
        Test.startTest();
      
        I_RM_Affiliation_Settings__c objAffiliationSettings = I_ST_UnitTestUtilities.createAffiliationSettings();
        insert objAffiliationSettings;
        
         I_RM_Affiliation_Settings__c objAffiliationSettings1 = I_ST_UnitTestUtilities.createEarlyEntryCourses();
        insert objAffiliationSettings1;
        
            Contact con=new Contact(FirstName='Contact',LastName='ForAlumini',I_ST_Personal_Email__c='contactforalumini@invalid.com');
        	insert con;
        	        I_RM_Affiliation__c student=new I_RM_Affiliation__c(RecordTypeID=Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Student').getrecordTypeId(),
            					I_RM_Contact__c=con.Id,I_RM_Phone__c='0412345678',
                                I_RM_Role__c='Student',I_RM_Email__c='alumini@invalid.com',
                                I_RM_Status__c='Admitted And Enrolled',I_RM_Street__c='invalid',I_RM_Suburb__c='invalid',I_RM_Mailing_Suburb__c='invalid',I_RM_Mailing_Postcode__c='3000',I_RM_Mailing_Country__c='Australia',
                                I_RM_Mailing_State__c='Melbourne',I_RM_State__c='Melbourne',I_RM_Postcode__c='3000',I_RM_Country__c='Australia',I_RM_Mailing_Street__c='invalid',I_RM_Mobile_Phone__c='0412345670',I_RM_Other_Phone__c='0412345672');
            insert student;
        CourseParent__c parentInstance = new CourseParent__c(I_ST_ExternalId__c='123456',L_AD_Course_Type_Name__c ='Test'); 
        	insert parentInstance;
        CourseInstance__c addInstance = new CourseInstance__c(L_AD_CourseParent__c=parentInstance.ID,I_ST_ExternalId__c='123458');
        	insert addInstance;
        CourseAvailability__c availableCourse = new CourseAvailability__c(L_AD_CourseInstance__c=addInstance.ID,I_ST_ExternalId__c='123876');
        	insert availableCourse;
        I_ST_Student_Course__c studentCourse = new I_ST_Student_Course__c(I_ST_Student__c=con.ID,I_RM_Affiliation__c=student.Id,I_ST_ExternalId__c='123872',I_ST_CourseAvailability__c=availableCourse.ID,I_ST_Course_Admission_Stage_Code__c='COMP',I_ST_Course_Admission_Status_Code__c='PASS');
    		insert studentCourse;
     
        List<contact> verifyContact=[select ID,I_RM_Alumni__c from contact where I_ST_Personal_Email__c='contactforalumini@invalid.com'];
       contact objUpdatedContact = verifyContact[0];
        system.assertEquals(1,objUpdatedContact.I_RM_Alumni__c,'Alumini Affiliation Created for inserted Student Course');
     Test.stopTest();
    }
    
    @isTest
    public static void testAluminiAffiliation2(){
        Test.startTest();
     
        I_RM_Affiliation_Settings__c objAffiliationSettings = I_ST_UnitTestUtilities.createAffiliationSettings();
        insert objAffiliationSettings;
        
         I_RM_Affiliation_Settings__c objAffiliationSettings1 = I_ST_UnitTestUtilities.createEarlyEntryCourses();
        insert objAffiliationSettings1;
            Contact con=new Contact(FirstName='Contact',LastName='ForAlumini',I_ST_Personal_Email__c='contactforalumini@invalid.com');
        	insert con;
        	        I_RM_Affiliation__c student=new I_RM_Affiliation__c(RecordTypeID=Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Student').getrecordTypeId(),
            					I_RM_Contact__c=con.Id,I_RM_Phone__c='0412345678',
                                I_RM_Role__c='Student',I_RM_Email__c='alumini@invalid.com',
                                I_RM_Status__c='Admitted And Enrolled',I_RM_Street__c='invalid',I_RM_Suburb__c='invalid',I_RM_Mailing_Suburb__c='invalid',I_RM_Mailing_Postcode__c='3000',I_RM_Mailing_Country__c='Australia',
                                I_RM_Mailing_State__c='Melbourne',I_RM_State__c='Melbourne',I_RM_Postcode__c='3000',I_RM_Country__c='Australia',I_RM_Mailing_Street__c='invalid',I_RM_Mobile_Phone__c='0412345670',I_RM_Other_Phone__c='0412345672');
            insert student;
        CourseParent__c parentInstance = new CourseParent__c(I_ST_ExternalId__c='123456',L_AD_Course_Type_Name__c ='Test'); 
        	insert parentInstance;
        CourseInstance__c addInstance = new CourseInstance__c(L_AD_CourseParent__c=parentInstance.ID,I_ST_ExternalId__c='123458');
        	insert addInstance;
        CourseAvailability__c availableCourse = new CourseAvailability__c(L_AD_CourseInstance__c=addInstance.ID,I_ST_ExternalId__c='123876');
        	insert availableCourse;
        I_ST_Student_Course__c studentCourse = new I_ST_Student_Course__c(I_ST_Student__c=con.ID,I_RM_Affiliation__c=student.Id,I_ST_ExternalId__c='123872',I_ST_CourseAvailability__c=availableCourse.ID,I_ST_Course_Admission_Stage_Code__c='abc',I_ST_Course_Admission_Status_Code__c='xyz');
    		insert studentCourse;
        studentCourse.I_ST_Course_Admission_Stage_Code__c='COMP';
            studentCourse.I_ST_Course_Admission_Status_Code__c='PASS';
        update studentCourse;
   
        List<contact> verifyContact=[select ID,I_RM_Alumni__c from contact where I_ST_Personal_Email__c='contactforalumini@invalid.com'];
       contact objUpdatedContact = verifyContact[0];
        system.assertEquals(1,objUpdatedContact.I_RM_Alumni__c,'Alumini Affiliation Created for inserted Student Course');
     Test.stopTest();
    }

}