force-app/main/default/objects/Contact/fields/I_ST_Personal_Email__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Personal_Email__c</fullName>
    <description>Created to allow user to store personal email</description>
    <externalId>true</externalId>
    <inlineHelpText>The personal email for this person.</inlineHelpText>
    <label>Student Lead Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/I_RM_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Part of the remediation project to store different personas</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Contact__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Contact__c</fullName>
    <description>The person/contact who this Affiliation relates to</description>
    <inlineHelpText>The person this affiliation relates to</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Affiliations</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Enquirer_Type__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Enquirer_Type__c</fullName>
    <description>Depicts how best to describe the Enquirer, Applicable for Student Lead (Dom),Student Applicant (Dom) and Secondary School Rep</description>
    <inlineHelpText>This is the Enquirer Type</inlineHelpText>
    <label>What best describes you?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>I_ST_Enquirer_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Time_Frame_to_Study__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Time_Frame_to_Study__c</fullName>
    <description>Student Lead (Dom) Affiliation&apos;s time trame to study.</description>
    <label>Time Frame to Study</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>I_ST_Time_Frame_to_Study</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_IL_Student_Lead_Int.recordType-meta.xml
<RecordType>
    <fullName>I_IL_Student_Lead_Int</fullName>
    <active>true</active>
    <description>New International Lead who can be a prospective student of La Trobe University</description>
    <label>Student Lead (Int)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_Applicant.recordType-meta.xml
<RecordType>
    <fullName>I_RM_Applicant</fullName>
    <active>true</active>
    <description>An individual who has applied to study at La Trobe University</description>
    <label>Student Applicant (Dom)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_Lead.recordType-meta.xml
<RecordType>
    <fullName>I_RM_Lead</fullName>
    <active>true</active>
    <description>New Domestic Lead who is a prospective student of La Trobe University</description>
    <label>Student Lead (Dom)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/I_RM_Affiliation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Affiliation Settings</label>
</CustomObject>

force-app/main/default/globalValueSets/I_ST_Enquirer_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Year 9</fullName>
    </customValue>
    <customValue>
        <fullName>Year 10</fullName>
    </customValue>
    <customValue>
        <fullName>Year 11</fullName>
    </customValue>
    <customValue>
        <fullName>Year 12</fullName>
    </customValue>
    <customValue>
        <fullName>Recent school leaver (18-20)</fullName>
    </customValue>
    <customValue>
        <fullName>Mature age (21+)</fullName>
    </customValue>
    <customValue>
        <fullName>Industry qualified or experienced</fullName>
    </customValue>
    <customValue>
        <fullName>Direct applicant</fullName>
    </customValue>
    <customValue>
        <fullName>University graduate (other uni)</fullName>
    </customValue>
    <customValue>
        <fullName>University graduate (LTU)</fullName>
    </customValue>
    <customValue>
        <fullName>International (outside Australia)</fullName>
    </customValue>
    <customValue>
        <fullName>International (inside Australia)</fullName>
    </customValue>
    <customValue>
        <fullName>TAFE graduate</fullName>
    </customValue>
    <customValue>
        <fullName>Current students (LTU) - UG</fullName>
    </customValue>
    <customValue>
        <fullName>Current students (LTU) - PG</fullName>
    </customValue>
    <customValue>
        <fullName>Current students (other uni) - UG</fullName>
    </customValue>
    <customValue>
        <fullName>Current students (other uni) - PG</fullName>
    </customValue>
    <customValue>
        <fullName>Current student (other) - TAFE</fullName>
    </customValue>
    <customValue>
        <fullName>Current student (LTU) - Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Parent</fullName>
    </customValue>
    <customValue>
        <fullName>Careers advisor / Careers counsellor</fullName>
    </customValue>
    <customValue>
        <fullName>Teacher</fullName>
    </customValue>
    <customValue>
        <fullName>Principal</fullName>
    </customValue>
    <customValue>
        <fullName>International agent</fullName>
    </customValue>
    <customValue>
        <fullName>Business Owner / Contact</fullName>
    </customValue>
    <customValue>
        <fullName>Industry partner</fullName>
    </customValue>
    <customValue>
        <fullName>Industry association</fullName>
    </customValue>
    <customValue>
        <fullName>Accrediting Body</fullName>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <customValue>
        <fullName>Staff</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <description>Created for IST-43</description>
    <masterLabel>I_ST_Enquirer_Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/I_ST_Time_Frame_to_Study.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1-3 months</fullName>
    </customValue>
    <customValue>
        <fullName>3-6 months</fullName>
    </customValue>
    <customValue>
        <fullName>6-12 months</fullName>
    </customValue>
    <customValue>
        <fullName>1-2 years</fullName>
    </customValue>
    <customValue>
        <fullName>2-3 years</fullName>
    </customValue>
    <customValue>
        <fullName>3+ years</fullName>
    </customValue>
    <customValue>
        <fullName>Unsure</fullName>
    </customValue>
    <customValue>
        <fullName>12+ months</fullName>
        <isActive>false</isActive>
        <label>12+ months</label>
    </customValue>
    <description>Created for IST 43</description>
    <masterLabel>I_ST_Time_Frame_to_Study</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/I_ST_InformationRolloverTest.cls
@isTest

public class I_ST_InformationRolloverTest {

    @testSetup static void setup() {

        String recTypeIdsForAffScoring = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Applicant').getRecordTypeId();
        recTypeIdsForAffScoring += ',' + Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Lead').getRecordTypeId();
        recTypeIdsForAffScoring += ',' + Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_IL_Student_Lead_Int').getRecordTypeId();
        TestUtility.createBatchScoringCustomSettings(recTypeIdsForAffScoring);
        

        Integer remainder;

        List<I_RM_Affiliation__c> lstAffiliation= new List<I_RM_Affiliation__c>();

        List<Contact> cnt=new List<Contact>();

        ID conid;

        Id recTypeId = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Applicant').getrecordTypeId();

    	Id recTypeIdLead = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Lead').getrecordTypeId();

        contact c=new contact();

        for(Integer i=0;i<1;i++){

                    c.FirstName = 'Test';
                    c.LastName = 'Tset';
                    c.Email = c.FirstName + '@' + c.LastName + '.com';
                    c.I_ST_Personal_Email__c = c.Email;
                    c.MobilePhone = '04473' + String.valueOf(i).leftPad(5, '0');
                   // c.RecordTypeId = '0124a0000004NL9AAM';
                    cnt.add(c);
        }
        insert cnt;

      //  list<string> parentaccount=new list<string>([select id from contact where name='Test Tset']);

        for(contact ct :([select id from contact where name='Test tset'])){
            conid=ct.id;
        }

        I_RM_Affiliation_Settings__c objAffiliationSettings = I_ST_UnitTestUtilities.createAffiliationSettings();
        insert objAffiliationSettings;


        for(Integer i=0 ;i <1;i++){
            

            I_RM_Affiliation__c con = new I_RM_Affiliation__c();
            remainder = math.mod(i,3);           

            con.I_RM_Contact__c = conid;

            con.RecordTypeId = recTypeId;           

            if(remainder == 0){

                //Values should be rolled over

                con.I_RM_Enquirer_Type__c = 'Year 10';

                con.I_RM_Time_Frame_to_Study__c = '3+ years';

            } else if(remainder == 1){

                //Only Enquirer Type should be rolled over

                con.I_RM_Enquirer_Type__c = 'Year 10';

                con.I_RM_Time_Frame_to_Study__c = null;

            } else{

                //Values should be not considered

                con.I_RM_Enquirer_Type__c = 'Other';

                con.I_RM_Time_Frame_to_Study__c = 'Unsure';

            }

            lstAffiliation.add(con);

        }

        insert lstAffiliation;        

    }

    static testMethod void testInformationRolloverBatch() {

        Integer batchSize = 10;

        List<I_RM_Affiliation__c> preRollover10s = [Select Id From I_RM_Affiliation__c Where I_RM_Enquirer_Type__c = 'Year 10'];

        List<I_RM_Affiliation__c> preRolloverNulls = [Select Id From I_RM_Affiliation__c Where I_RM_Time_Frame_to_Study__c = null];

        List<I_RM_Affiliation__c> preRolloverUnqualifieds = [Select Id From I_RM_Affiliation__c Where I_RM_Time_Frame_to_Study__c = 'Unsure' AND I_RM_Enquirer_Type__c = 'Other'];

        

        Test.startTest();

        

        String hour = String.valueOf(Datetime.now().hour());

        String min = String.valueOf(Datetime.now().minute() ); 

        String ss = String.valueOf(Datetime.now().second() + 2);

        

        //parse to cron expression

        String nextFireTime = ss + ' ' + min + ' ' + hour + ' * * ?';

        

        System.schedule('Job Started At ' + String.valueOf(Datetime.now()), nextFireTime, new I_ST_InformationRolloverBatchScheduler(batchSize));

        

        I_ST_InformationRolloverBatch obj = new I_ST_InformationRolloverBatch();

        DataBase.executeBatch(obj); 

        Test.stopTest();

        

        List<I_RM_Affiliation__c> postRollover10s = [Select Id From I_RM_Affiliation__c Where I_RM_Enquirer_Type__c = 'Year 11'];

        List<I_RM_Affiliation__c> postRolloverNulls = [Select Id From I_RM_Affiliation__c Where I_RM_Time_Frame_to_Study__c = null];

        List<I_RM_Affiliation__c> postRolloverUnqualifieds = [Select Id From I_RM_Affiliation__c Where I_RM_Time_Frame_to_Study__c = 'Unsure' AND I_RM_Enquirer_Type__c = 'Other'];

        

        System.assertEquals(preRollover10s.size(), postRollover10s.size());

        System.assertEquals(preRolloverNulls.size(), postRolloverNulls.size());

        System.assertEquals(preRolloverUnqualifieds.size(), postRolloverUnqualifieds.size());

    }

}