force-app/main/default/objects/Contact/fields/I_ST_Incremental_Score__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Incremental_Score__c</fullName>
    <label>Activity Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/I_RM_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Part of the remediation project to store different personas</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_RM_Affiliation__c/fields/I_RM_Incremental_Score__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Incremental_Score__c</fullName>
    <description>This field is used for automated Contact scoring</description>
    <label>Activity Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/I_RM_Affiliation__c/recordTypes/I_RM_Lead.recordType-meta.xml
<RecordType>
    <fullName>I_RM_Lead</fullName>
    <active>true</active>
    <description>New Domestic Lead who is a prospective student of La Trobe University</description>
    <label>Student Lead (Dom)</label>
</RecordType>

force-app/main/default/objects/I_RM_Affiliation_Settings__c/I_RM_Affiliation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Affiliation Settings</label>
</CustomObject>

force-app/main/default/objects/I_ST_BatchScoring__c/I_ST_BatchScoring__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>I_ST_BatchScoring</label>
</CustomObject>

force-app/main/default/objects/I_ST_BatchScoring__c/fields/I_ST_BatchSize__c.field-meta.xml
<CustomField>
    <fullName>I_ST_BatchSize__c</fullName>
    <description>This is the batch size to control the Lead/Activity scoring jobs for IST</description>
    <label>I_ST_BatchSize</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/I_ST_BatchScoring__c/fields/I_ST_Last_N_Hour__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Last_N_Hour__c</fullName>
    <description>Used for Activity Scoring batch to run batch and pick records modified &apos;N&apos; hours before current time</description>
    <label>I_ST_Last_N_Hour</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/I_ST_BatchScoring__c/fields/I_ST_RecordType_SFIDs__c.field-meta.xml
<CustomField>
    <fullName>I_ST_RecordType_SFIDs__c</fullName>
    <description>Provide comma separated RecordTypeIds of Case object which is to be considered for Activity Scoring. To get the record type Ids =&gt; Navigate to Setup -&gt; Object Manager -&gt; Case -&gt; RecordTypes -&gt; Select the record type -&gt; copy the 18 digit Id from the URL</description>
    <label>I_ST_RecordType_SFIDs</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/I_ST_Interaction__c/I_ST_Interaction__c.object-meta.xml
<CustomObject>
    <description>For Lead Forms, tracks interactions(forms) filled out by the Lead (domestic)</description>
    <label>Interaction</label>
    <nameField>
        <displayFormat>INT-{DD}{MM}{YY}-{0000}</displayFormat>
        <label>Interaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/I_ST_Interaction__c/fields/I_RM_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>I_RM_Affiliation__c</fullName>
    <description>Facilitate relationship with the Affiliation object</description>
    <label>Affiliation</label>
    <referenceTo>I_RM_Affiliation__c</referenceTo>
    <relationshipLabel>Interactions</relationshipLabel>
    <relationshipName>Interactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/I_ST_Interaction__c/fields/I_ST_Contact__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Added for LTU360-16, To track Associated Contact of domestic Lead Forms.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Interactions</relationshipLabel>
    <relationshipName>Interactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/I_ST_Interaction__c/fields/I_ST_Email__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Email__c</fullName>
    <description>Added for LTU360-16, To track  Email of domestic Lead Forms.</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/I_ST_Interaction__c/fields/I_ST_Incremental_Score__c.field-meta.xml
<CustomField>
    <fullName>I_ST_Incremental_Score__c</fullName>
    <label>Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/I_ST_Interaction__c/recordTypes/I_ST_Lead_Interaction.recordType-meta.xml
<RecordType>
    <fullName>I_ST_Lead_Interaction</fullName>
    <active>true</active>
    <label>Lead Interaction</label>
</RecordType>

force-app/main/default/classes/I_ST_InteractionScoringBatchTest.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* I_ST_InteractionScoringBatchTest
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Teja Yenduri   <tyenduri@au1.ibm.com>
* @version        1.0
* @created        2022-02-18
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* @changes
* v1.0           Teja Yenduri
* 2022-02-18      Created
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/
@isTest
public class I_ST_InteractionScoringBatchTest{
    @TestSetup
    static void setup() {
        
        String caseRecordTypeIds = I_ST_UnitTestUtilities.recordTypeIds(GlobalConstants.CASE_OBJECT_API_NAME,GlobalConstants.CASE_RECORD_TYPE_API_NAME_ENQUIRY);  
        String interactionRecordTypeIds = I_ST_UnitTestUtilities.recordTypeIds(GlobalConstants.INTERACTION_OBJECT_API_NAME,GlobalConstants.INTERACTION_RECORD_TYPE_API_NAME_LEAD_INTERACTION);
        String affiliationRecordTypIds = I_ST_UnitTestUtilities.recordTypeIds(GlobalConstants.AFFILIATION_OBJECT_API_NAME,GlobalConstants.AFFILIATION_RECORD_TYPE_NAME_LEAD);
        
        List<I_ST_BatchScoring__c> listBatchScoringSetting = I_ST_UnitTestUtilities.createBatchScoringCustomSetting(affiliationRecordTypIds,20,caseRecordTypeIds,20,interactionRecordTypeIds,20);           
        insert listBatchScoringSetting;
        
        I_RM_Affiliation_Settings__c objAffiliationSettings = I_ST_UnitTestUtilities.createAffiliationSettings();
        insert objAffiliationSettings;
        
        Profile integrationUserRec = [SELECT Id FROM Profile WHERE Name='LTU Integration']; 
        User integrationUser = I_ST_UnitTestUtilities.newUser('interactionUser',integrationUserRec.Id);
        
        Id interactionRecordTypeId = Schema.SObjectType.I_ST_Interaction__c.getRecordTypeInfosByDeveloperName().get('I_ST_Lead_Interaction').getRecordTypeId();        
        Id affiliationDomesticLeadRecordTypeId = Schema.SObjectType.I_RM_Affiliation__c.getRecordTypeInfosByDeveloperName().get('I_RM_Lead').getRecordTypeId();
        
        List<Contact> contactsforTest = new List<Contact>();
        
        for(Integer i =0; i<10; i++){
            Contact newDomesticLead = I_ST_UnitTestUtilities.createContactForScore('test_unique001'+i,
                                                                                   'unique_test001'+i,
                                                                                   'test_unique001'+i+'@unique.com',
                                                                                   'test_unique001'+i+'@unique.com',                                                                                   
                                                                                   '3029'); 
                                                                                         
            contactsforTest.add(newDomesticLead);
        }
        Insert contactsforTest;
        
        List<I_RM_Affiliation__c> testAffiliation = I_ST_UnitTestUtilities.createAffiliationRecords(affiliationDomesticLeadRecordTypeId,contactsforTest[0].Id);
        insert testAffiliation;
         system.debug('testAffiliation'+testAffiliation);
              
        
        //system.runAs(integrationUser){
            //Insert batch of Interactions
            List<I_ST_Interaction__c> interactionsforTest = new List<I_ST_Interaction__c>();
            for(Integer j=0; j<contactsforTest.size(); j++) {
                I_ST_Interaction__c newinteraction =  I_ST_UnitTestUtilities.newListOfContactRelatedInteractions(interactionRecordTypeId,contactsforTest[j],'FirstTest'+j,'LastTest'+j,'039948757',
                                                                                                                                                              'testInteractionEmail'+j+'@test.com','Web','Keep in touch form', testAffiliation[0]);
                //newinteraction.I_RM_Affiliation__c= testAffiliation.Id;
                interactionsforTest.add(newinteraction);
            }
            Insert interactionsforTest;     
       // }   
        
    }
    
    //IST - Test method to test the scheduler - I_ST_Interaction_Scoring_Batch_Scheduler 
    @isTest
    public static void testInteractionScoringScheduler(){
        
        I_ST_BatchScoring__c batchScoringSettingInteraction = I_ST_BatchScoring__c.getValues(GlobalConstants.I_ST_INTERACTIONSCORING);
        Integer lastNHours = (Integer)batchScoringSettingInteraction.I_ST_Last_N_Hour__c;
        Set<Id> newrecordTypeIds = GlobalUtility.convertCommaSeparatedStringsToSetIds(batchScoringSettingInteraction.I_ST_RecordType_SFIDs__c);
        
        String jobId = '';
        Test.startTest();           
          jobId  = I_ST_InteractionScoring_Batch_Scheduler.scheduleActivityScoring();
        Test.stopTest();       
        System.assert(String.isNotBlank(jobId));
    }
    
    //IST - Test method to test the execution of batch class - I_ST_InteractionScoring_Batch - Positive Test
    @isTest
    public static void testInteractionScoringBatch(){
        
        List<String> contactIdsForInteractions = new List<String>();
        for(I_ST_Interaction__c interaction: [SELECT id,
                                              I_ST_Contact__c,
                                              I_RM_Affiliation__c,
                                              I_ST_Interaction__c.I_RM_Affiliation__r.I_RM_Incremental_Score__c,
                                              I_ST_Incremental_Score__c 
                                              FROM I_ST_Interaction__c
                                              WHERE I_ST_Email__c = 'testInteractionEmail1@test.com' 
                                              LIMIT 1]) {     
                                                  System.assertEquals(0,interaction.I_RM_Affiliation__r.I_RM_Incremental_Score__c);
                                                  contactIdsForInteractions.add(interaction.I_RM_Affiliation__c);
                                              }
        
        
        I_ST_BatchScoring__c batchScoringSettingInteraction = I_ST_BatchScoring__c.getValues(GlobalConstants.I_ST_INTERACTIONSCORING);
        Integer lastNHours = (Integer)batchScoringSettingInteraction.I_ST_Last_N_Hour__c;
        Integer batchSize = (Integer)batchScoringSettingInteraction.I_ST_BatchSize__c;
        Set<Id> newrecordTypeIds = GlobalUtility.convertCommaSeparatedStringsToSetIds(batchScoringSettingInteraction.I_ST_RecordType_SFIDs__c);
        
        Test.startTest();           
            I_ST_InteractionScoring_Batch leadScoringBatch = new I_ST_InteractionScoring_Batch(GlobalConstants.INTERACTION_OBJECT_API_NAME,newrecordTypeIds,lastNHours);
            Database.executeBatch(leadScoringBatch,batchSize);
        Test.stopTest();
        
        List<I_RM_Affiliation__c> affAfterBatchUpdate = new List<I_RM_Affiliation__c>();
        affAfterBatchUpdate = [SELECT Id,I_RM_Incremental_Score__c FROM I_RM_Affiliation__c WHERE id =: contactIdsForInteractions[0] LIMIT 1];
        //Assert on Score calculated based on metadata mapping in Lead Scoring metadata. Hence asserting increment in score NOT actual score calculated as it keeps on changing
        system.assert(Integer.valueOf(affAfterBatchUpdate[0].I_RM_Incremental_Score__c)>0);  
    } 
}