force-app/main/default/objects/Authorship_Research_Output_Team_Member__c/Authorship_Research_Output_Team_Member__c.object-meta.xml
<CustomObject>
    <label>Authorship/Research Output Team Member</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Title</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorships/Research Output Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Authorship_Research_Output_Team_Member__c/fields/I_RS_Contact__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Authorships/Research Output Team Members</relationshipLabel>
    <relationshipName>Authorships_Research_Output_Team_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Authorship_Research_Output_Team_Member__c/fields/I_RS_Research_Output__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Research_Output__c</fullName>
    <description>This is the mater field</description>
    <label>Research Output</label>
    <referenceTo>Research_Output__c</referenceTo>
    <relationshipLabel>Authorships/Research Output Team Members</relationshipLabel>
    <relationshipName>Authorships_Research_Output_Team_Members</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Research_Output_Classification_Code__c/Research_Output_Classification_Code__c.object-meta.xml
<CustomObject>
    <label>Research Output Classification Code</label>
    <nameField>
        <displayFormat>RO-{00000}</displayFormat>
        <label>Research Output Classification Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Research Output Classification Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Research_Output_Classification_Code__c/fields/I_RS_Research_Output__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Research_Output__c</fullName>
    <label>Research Output</label>
    <referenceTo>Research_Output__c</referenceTo>
    <relationshipLabel>Classification Codes</relationshipLabel>
    <relationshipName>Research_Output_Classification_Codes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User/fields/I_RS_Is_Researcher_User__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Is_Researcher_User__c</fullName>
    <formula>IF(Profile.Name = &quot;LTU Partner Community User&quot; ||
Profile.Name = &quot;LTU Partner Community Login User&quot;, &quot;1&quot;, &quot;0&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Researcher User?</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ResearchOutputClassificationCodeHelper.cls
public class ResearchOutputClassificationCodeHelper {
    public void validateUserIsPartOfAuthorship(List<Research_Output_Classification_Code__c> roccList){
        User currentUser = [SELECT ID, ContactId, I_RS_Is_Researcher_User__c FROM User WHERE Id = :UserInfo.getUserId()];
        if ((currentUser.I_RS_Is_Researcher_User__c == '1')&& (currentUser.ContactId <> null) ){
            Map<Id, set<Id>> roAuthorMap = new Map<Id, set<Id>>();
            // get the map of Research Output and Authors Ids
            for (Research_Output_Classification_Code__c rocc: roccList) {
                if (!roAuthorMap.containsKey(rocc.I_RS_Research_Output__c)) {
                    roAuthorMap.put(rocc.I_RS_Research_Output__c, new set<Id>());
                }
            }
            
            //get Authors associated to Research Output
            if (!roAuthorMap.isEmpty()){
                set<Id> tempAuths;
                for (Authorship_Research_Output_Team_Member__c auth: 
                [Select Id,I_RS_Contact__c,I_RS_Research_Output__c 
                 FROM Authorship_Research_Output_Team_Member__c
                 WHERE I_RS_Research_Output__c IN :roAuthorMap.keySet()]){
                    tempAuths = roAuthorMap.get(auth.I_RS_Research_Output__c);
                     if (!tempAuths.contains(auth.I_RS_Contact__c)) {
                         tempAuths.add(auth.I_RS_Contact__c);
                     }
                     roAuthorMap.put(auth.I_RS_Research_Output__c, tempAuths);
                 }
            }
            
            //now parse through and validate if the user is part of authorship table for the Researchoutput
            for (Research_Output_Classification_Code__c rocc: roccList){
            	if ((!roAuthorMap.containsKey(rocc.I_RS_Research_Output__c)) ||
                    (!roAuthorMap.get(rocc.I_RS_Research_Output__c).contains(currentUser.ContactId))) {
                        //rocc.addError(GlobalConstants.RESTRICT_CREATE_MODIFY_CODE_TO_RESEARCHOUTPUT);
                        rocc.addError('You do not have permission to create/modify codes for this research Output');                        
                }
            }
        }        
    }
}