force-app/main/default/objects/Object_Metadata__c/Object_Metadata__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Captures information about objects that would otherwise be hard to obtain, even with code. Useful for flows.

Used in: 
- &apos;Approval Process: Approver&apos;s Queue&apos; to filter results by a specific object, as object name is not readily available in underlying system data.</description>
    <label>Object Metadata</label>
</CustomObject>

force-app/main/default/objects/Object_Metadata__c/fields/I_RS_Deletion_Blocker_Check_Formula__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Deletion_Blocker_Check_Formula__c</fullName>
    <description>If the formula field specific equates to false, then a deletion of the given record is invalid and should be blocked in code.</description>
    <inlineHelpText>If the formula field specific equates to false, then a deletion of the given record is invalid and should be blocked in code.</inlineHelpText>
    <label>Deletion Blocker Check-Formula</label>
    <length>43</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_Metadata__c/fields/I_RS_Deletion_Blocker_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Deletion_Blocker_Error_Message__c</fullName>
    <description>The specific error message to appear if a deletion fails</description>
    <label>Deletion Blocker Error Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Object_Metadata__c/fields/I_RS_Enable_Deletion_Blocker__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Enable_Deletion_Blocker__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, invalid deletions will be prevented. Validity is provided through specified formula field</description>
    <inlineHelpText>If checked, invalid deletions will be prevented. Validity is provided through specified formula field</inlineHelpText>
    <label>Enable Deletion-Blocker</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DeletionBlocker.cls
public without sharing class DeletionBlocker {
    
    public static List<SObject> blockDelete(String objectName, List<SObject> records)
    {

        String debugPrefix = 'DeletionBlocker.blockDelete>>> ';
        System.debug(debugPrefix + objectName);
        System.debug(debugPrefix + records);


        Object_Metadata__c blockerCustomSetting = Object_Metadata__c.getInstance(objectName);       
        System.debug(debugPrefix + blockerCustomSetting);


        if (blockerCustomSetting != null && blockerCustomSetting.I_RS_Enable_Deletion_Blocker__c) 
        {

            List<SObject> failedRecords = new List<SObject>();

            String fieldNameToValidate = blockerCustomSetting.I_RS_Deletion_Blocker_Check_Formula__c;
            String errorMessage = blockerCustomSetting.I_RS_Deletion_Blocker_Error_Message__c;

            
            for (SObject record : records){

                Boolean validToDelete = (Boolean) record.get(fieldNameToValidate);
                if (!validToDelete){
                    failedRecords.add(record);
                    record.addError(errorMessage);
                }
            }

            System.debug(debugPrefix + failedRecords);
            return failedRecords;

        }
        else if (blockerCustomSetting != null && !blockerCustomSetting.I_RS_Enable_Deletion_Blocker__c)
        {
            System.debug(debugPrefix + ' Delete blocker disabled');
            return new List<SObject>{};
        }
        else if (blockerCustomSetting == null)
        {
            System.debug(debugPrefix + ' Delete blocker not found');
        }
        
        return null;
    }

}