force-app/main/default/objects/Object_Metadata__c/Object_Metadata__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Captures information about objects that would otherwise be hard to obtain, even with code. Useful for flows.

Used in: 
- &apos;Approval Process: Approver&apos;s Queue&apos; to filter results by a specific object, as object name is not readily available in underlying system data.</description>
    <label>Object Metadata</label>
</CustomObject>

force-app/main/default/objects/Object_Metadata__c/fields/I_RS_First_3_Characters_on_Record_Ids__c.field-meta.xml
<CustomField>
    <fullName>I_RS_First_3_Characters_on_Record_Ids__c</fullName>
    <description>In the &quot;Approval Process: Approver&apos;s Queue&quot; flow, we use this field to find records of the relevant object that have been submitted for approval. We cannot simply use the object&apos;s api name as this isn&apos;t recorded in the underlying system data that we are querying.</description>
    <inlineHelpText>Simply go to any record of the specific object, find the 15-character record Id in the URL, and copy its first 3 characters</inlineHelpText>
    <label>First 3 Characters on Record Ids</label>
    <length>3</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Object_Metadata__c/fields/I_RS_Object_Label_Singular__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Object_Label_Singular__c</fullName>
    <description>Object label. Use for UI display.</description>
    <inlineHelpText>Object label. Use for UI display. e.g. Project Proposal</inlineHelpText>
    <label>Object Label - Singular</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ParentToChildRecordNameCopy.cls
public class ParentToChildRecordNameCopy {

    public static void copyRelatedToDataToChildActivities(List<Task> childActivities)
    {
        Map<String, Object_Metadata__c> parentObjectMetadataMap = new Map<String, Object_Metadata__c>();
        Set<String> parentObjectApiNames = new Set<String>();
        Set<Id> parentRecordIds = new Set<Id>();

        for (Object_Metadata__c metadata : Object_Metadata__c.getAll().values())
        {
            parentObjectMetadataMap.put(metadata.I_RS_First_3_Characters_on_Record_Ids__c, metadata);
        }

        for (Task childActivity : childActivities)
        {
            childActivity.I_RS_Parent_Object_Label_Singular__c = null;
            childActivity.I_RS_Parent_Object_Name__c = null;
            childActivity.I_RS_Parent_Record_Name__c = null;

            if (childActivity.WhatId != null)
            {
                parentRecordIds.add(childActivity.WhatId);

                String objectIdPrefix = ((String) childActivity.WhatId).left(3);
                Object_Metadata__c parentObjectMetadata = parentObjectMetadataMap.get(objectIdPrefix);
                if (parentObjectMetadata != null)
                {
                    childActivity.I_RS_Parent_Object_Label_Singular__c = parentObjectMetadata.I_RS_Object_Label_Singular__c;
                    childActivity.I_RS_Parent_Object_Name__c = parentObjectMetadata.Name;

                    parentObjectApiNames.add(parentObjectMetadata.Name);
                }

                
            }
        }

        for (String parentObjectApiName : parentObjectApiNames)
        {
            String dynamicParentSOQL = 'SELECT Id, Name from '+parentObjectApiName+' WHERE ID IN :parentRecordIds';
            Map<Id, SObject> parentRecords = new Map<Id, SObject>(Database.query(dynamicParentSOQL));

            for (Task childActivity : childActivities)
            {
                if (childActivity.get('WhatId') != null)
                {
                    SObject parentRecord = parentRecords.get((String) childActivity.get('WhatId'));
                    if (parentRecord != null)
                    {
                        childActivity.I_RS_Parent_Record_Name__c = (String) parentRecord.get('Name');
                    }
                }
            }
        }

    }
}