force-app/main/default/objects/L_PR_Idea__c/L_PR_Idea__c.object-meta.xml
<CustomObject>
    <description>Idea/ Lead object being used for PRM Application</description>
    <label>PRM Lead</label>
    <nameField>
        <label>Lead Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PRM Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/L_PR_Idea__c/fields/L_PR_Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Lead_Status__c</fullName>
    <description>Indicates the progress of the Lead/Idea.</description>
    <label>Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Open – Contacted</fullName>
            </value>
            <value>
                <fullName>Open – Unqualified</fullName>
            </value>
            <value>
                <fullName>Open – Qualified</fullName>
            </value>
            <value>
                <fullName>Closed – Converted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/L_PR_Idea_Organisation__c/L_PR_Idea_Organisation__c.object-meta.xml
<CustomObject>
    <description>Junction object to capture relationship between Lead/Idea and Organisations</description>
    <label>Lead Organisation</label>
    <nameField>
        <displayFormat>IO-{000000}</displayFormat>
        <label>PRM Lead Organisation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Organisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/L_PR_Idea_Organisation__c/fields/L_PR_Idea__c.field-meta.xml
<CustomField>
    <fullName>L_PR_Idea__c</fullName>
    <label>PRM Lead</label>
    <referenceTo>L_PR_Idea__c</referenceTo>
    <relationshipLabel>Lead Organisations</relationshipLabel>
    <relationshipName>Lead_Organisations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/L_PR_Idea_Organisation__c/fields/L_PR_LeadStatus__c.field-meta.xml
<CustomField>
    <fullName>L_PR_LeadStatus__c</fullName>
    <label>Lead Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/L_PR_Idea_OrganisationTriggerHandler.cls
public class L_PR_Idea_OrganisationTriggerHandler{
    public static void execute() {

        List<L_PR_Idea_Organisation__c> listOfIdeaOrgToUpdate = New List<L_PR_Idea_Organisation__c>();
        if(Trigger.isAfter){
            if(Trigger.isInsert){
                List<L_PR_Idea_Organisation__c> listOfIdeaOrg = [Select Id, L_PR_Idea__r.L_PR_Lead_Status__c from L_PR_Idea_Organisation__c where Id In : Trigger.New];
                for(L_PR_Idea_Organisation__c ideaOrg :listOfIdeaOrg){
                    L_PR_Idea_Organisation__c idea = New L_PR_Idea_Organisation__c();
                    idea.L_PR_LeadStatus__c = ideaOrg.L_PR_Idea__r.L_PR_Lead_Status__c;
                    idea.Id = ideaOrg.Id;
                    listOfIdeaOrgToUpdate.add(idea);
                }
                system.debug('###listOfIdeaOrgToUpdate'+ listOfIdeaOrgToUpdate);
                if(!listOfIdeaOrgToUpdate.isEmpty()){
                    update listOfIdeaOrgToUpdate;
                }

            }
        }
    }
}