force-app/main/default/objects/Ethics_Request__c/Ethics_Request__c.object-meta.xml
<CustomObject>
    <label>Ethics Request</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ethics Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ethics_Request__c/fields/I_RS_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Status__c</fullName>
    <inlineHelpText>This is the status that corresponds with the ethics request status at the top of the page. If this status is ‘draft’ this means the researcher has an action to complete. Populated by the Research Office.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>I_RS_Ethics_Application_Review_Outcome__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Review by Research Office</fullName>
            </value>
            <value>
                <fullName>Assigned for Review</fullName>
            </value>
            <value>
                <fullName>Outcome Communicated</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Decided</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Proposal__c/Project_Proposal__c.object-meta.xml
<CustomObject>
    <description>Project Proposal: An application for funding either through a grant request, a tender response, or a contract proposal.
Project: The work that is undertaken to satisfy a commitment made to a funding body or client.  The commitment is likely to be a contract (and possible variations) resulting from the acceptance of a project proposal.  This occurs after a grant, contract of philanthropic donation has been awarded.</description>
    <label>Project Proposal</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Proposal__c/fields/I_RS_Allow_Updates_on_Approval__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Allow_Updates_on_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When &quot;checked&quot; the record will be locked after submitted for approval.</description>
    <label>Allow Updates on Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_Proposal__c/fields/I_RS_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PlaceHolder</fullName>
            </value>
            <value>
                <fullName>Create Proposal</fullName>
            </value>
            <value>
                <fullName>Proposal Review</fullName>
            </value>
            <value>
                <fullName>Recommended</fullName>
            </value>
            <value>
                <fullName>Dismissed</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Create EOI</fullName>
            </value>
            <value>
                <fullName>Drafting NOI</fullName>
            </value>
            <value>
                <fullName>Final draft</fullName>
            </value>
            <value>
                <fullName>Draft Proposal</fullName>
            </value>
            <value>
                <fullName>Provide Project Details</fullName>
            </value>
            <value>
                <fullName>Contract Instructions</fullName>
            </value>
            <value>
                <fullName>Review by Research Office</fullName>
            </value>
            <value>
                <fullName>Panel Review</fullName>
            </value>
            <value>
                <fullName>HoS NOI Validation</fullName>
            </value>
            <value>
                <fullName>Pitch Session</fullName>
            </value>
            <value>
                <fullName>Peer review draft</fullName>
            </value>
            <value>
                <fullName>Peer review draft complete</fullName>
            </value>
            <value>
                <fullName>Review Contract</fullName>
            </value>
            <value>
                <fullName>Draft contract</fullName>
            </value>
            <value>
                <fullName>Approvals</fullName>
            </value>
            <value>
                <fullName>Formalise Contract</fullName>
            </value>
            <value>
                <fullName>Submission to Client</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Ready for Submission to Funding Body</fullName>
            </value>
            <value>
                <fullName>Submission to Funding Body</fullName>
                <label>Funding Body Submission</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Rejoinders</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Research_Opportunity__c/Research_Opportunity__c.object-meta.xml
<CustomObject>
    <label>Funding Opportunity</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Research_Opportunity__c/fields/I_RS_Status__c.field-meta.xml
<CustomField>
    <fullName>I_RS_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initial</fullName>
                <default>true</default>
                <label>Initial</label>
            </value>
            <value>
                <fullName>Drafted</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Internal Applications Closed</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContentDocumentTriggerHelper.cls
//Trigger helper for ContentDocument
public class ContentDocumentTriggerHelper {
        private static String projPropKeyPrefix = Project_Proposal__c.sObjectType.getDescribe().getKeyPrefix();
        private static String roKeyPrefix = Research_Opportunity__c.sObjectType.getDescribe().getKeyPrefix();
        private static String erKeyPrefix = Ethics_Request__c.sObjectType.getDescribe().getKeyPrefix();
    
    public static void blockAttachmentDeleteWhenProjectlocked(List<ContentDocument> oldConDoc) {
      
        Map<Id, ContentDocument> contentDocMap = new Map<Id, ContentDocument>();
        Map<Id, Id> ppMap = new Map<Id, Id>();
        
        for(ContentDocument con : oldConDoc){
            contentDocMap.put(con.Id, con);
        }
        
        //get all the content document link for the project proposal only
        if(contentDocMap != null && contentDocMap.size()>0){
            for(ContentDocumentLink cdl : [SELECT ContentDocumentId, LinkedEntityId FROM ContentDocumentLink WHERE ContentDocumentId IN : contentDocMap.keySet()]){
                if(String.valueOf(cdl.LinkedEntityId).left(3) == projPropKeyPrefix)  {
                    ppMap.put(cdl.ContentDocumentId, cdl.LinkedEntityId);
                }
                
                if(String.valueOf(cdl.LinkedEntityId).left(3) == roKeyPrefix){
                	handleResearchOpportunityDocument(contentDocMap.get(cdl.ContentDocumentId));    
                }
                
                if(String.valueOf(cdl.LinkedEntityId).left(3) == roKeyPrefix){
                	handleEthicsRequestDocument(contentDocMap.get(cdl.ContentDocumentId));    
                }
            }
        }
        
        if (ppMap.size() > 0) {
        	handleProjectProposalDocument(ppMap, oldConDoc);    
        }
        
    }
    
    private static void handleProjectProposalDocument(Map<Id, Id> ppMap, List<ContentDocument> oldConDoc){
        //create a map of project proposal for which the attachments are deleted
        Map<Id,Project_Proposal__c> mapLockedProjectProposals;
        if(ppMap.values() != null) {
            mapLockedProjectProposals = new Map<Id,Project_Proposal__c>([Select I_RS_Status__c, I_RS_Allow_Updates_on_Approval__c FROM Project_Proposal__c WHERE Id IN :ppMap.values()]);
        }
        
        if(mapLockedProjectProposals != null && mapLockedProjectProposals.size()>0) {
            for(ContentDocument cdoc : oldConDoc){
                if(mapLockedProjectProposals.get(ppMap.get(cdoc.Id)) != null) {
                    if(projPropKeyPrefix == String.valueOf(ppMap.get(cdoc.Id)).left(3) 
                       && !mapLockedProjectProposals.get(ppMap.get(cdoc.Id)).I_RS_Allow_Updates_on_Approval__c
                       && (GlobalConstants.PROJECT_PROPOSAL_STATUS_REVIEW_BY_RESEARCH_OFFICE.EqualsIgnoreCase(mapLockedProjectProposals.get(ppMap.get(cdoc.Id)).I_RS_Status__c)
                           || GlobalConstants.PROJECT_PROPOSAL_STATUS_APPROVALS.EqualsIgnoreCase(mapLockedProjectProposals.get(ppMap.get(cdoc.Id)).I_RS_Status__c))){
                               System.debug('--> ContentDocumentTrigger throw error -->');
                               cdoc.addError(GlobalConstants.ADDED_ERROR_ATTACHMENT_UPLOAD_PROECT_IN_REVIEW);
                           }
                }
            }
        }
    }
    
    private static void handleResearchOpportunityDocument(ContentDocument cdoc){
        if (GlobalUtility.currentUserIsResearcher()) {
    		cdoc.addError(GlobalConstants.RESTRICT_DOCUMENT_UPLOAD_BY_RESEARCHER);
        }
    }

    private static void handleEthicsRequestDocument(ContentDocument cdoc){
        if (GlobalUtility.currentUserIsResearcher()) {
    		cdoc.addError(GlobalConstants.RESTRICT_DOCUMENT_UPLOAD_BY_RESEARCHER);
        }
    }
}